### ISSUE TITLE
Will Double CA certs work (if not, how to disable ES's self-signed cert creation?)

### ISSUE THREAD

**Issue by devdattakulkarni** [elastic/cloud-on-k8s#1010]
I know that ES Operator creates a Self-signed cert for the Elasticsearch endpoint.

I was contemplating following setup and wanted to know if there might be any problems with it, and if so, how to address them.

My plan is to deploy ES and Kibana as ClusterIP services. While deploying ES, I am going to pass in nginx-ingress-controller's LB IP so that ES Operator can associate that IP with the Self-signed CA cert. Then, I am going to generate a LetsEncrypt certificate for my custom domain name. I will associate that domain name with the LB IP. In my ingress resource I will be setting up path based routes such that https://domain-name/elastic will route to Elasticsearch service and https://domain-name/kibana will route to Kibana service. 

I read in the docs that configuring user-defined certificate with ES and Kibana endpoints is planned for a future release. So wanted to understand if above setup will work? Essentially in the above setup, there are two certs associated with the LB IP - one from LetsEncrypt and another the Self-signed cert created by ES Operator. 

My guess is it should work.

If not, I was wondering if there is a way to disable the generation of self-signed cert by the ES Operator.

**Comment by devdattakulkarni** [comment]
I tried this setup, but it did not work!

I also tried using the self-signed cert generated by the ES Operator in the Ingress's tls field (not generating a new LetsEncrypt cert). That did not work either.

In both cases the calls timeout.

It seems like the LB is not able to route requests to the ES and Kibana Services in the cluster. Are there any specific annotations/settings that need to be set on the ES or Kibana Custom Resources?

General question is - what is the best approach to expose ES and Kibana endpoints externally without each creating a new LoadBalancer?

**Comment by sebgl** [comment]
Hey @devdattakulkarni,

This is something we are discussing a lot. The general mid-term (next release) approach is the following:

* the operator takes care of internal node-to-node communication (transport protocol) through its own CA and certificates. This is all "internal" and hidden fro the end-user.
* by default, it also generates another self-signed certificate for the HTTP endpoint: this is the certificate users will see when communicating with Elasticsearch. Users are welcome to provide their own certificate here instead in a Kubernetes secret for the operator to pick up and configure for Elasticsearch. That could be, for example, a certificate signed by Let's Encrypt for a particular DNS on which the ES service is exposed. There are many ways to deal with Let's Encrypt and Acme challenges, we don't have any recommendations yet regarding the easiest/best way to do it. Also the plan is to support any user-provided certificate, signed by any authority of their choice.

This is planned for next release. In the current release, we generate a single set of CA and certs used both for transport and http communication. Users cannot override it.

It is (and will) always be possible for users to setup their own proxy (ingress for example) in front of the Elasticsearch http service.

Regarding NGINX ingress, I did play a bit with the following example a while back. Note that **we do not promote this as "the best way to expose Elasticsearch"**: it's generally something we're still thinking about. Also there is probably not a solution that fits everyone's use case.

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-es-kibana-sample
  annotations:
    # Use the nginx ingress controller, not the cloud-provider default one
    kubernetes.io/ingress.class: "nginx"

    # Rewrite routes: eg. "/elasticsearch/_cat/nodes" to "/_cat/nodes"
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"

    # If the ES cluster is already configured to use TLS,
    # use https to reach the cluster.
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"

    # Auto-generate a Let's Encrypt certificate with cert-manager
    certmanager.k8s.io/issuer: "letsencrypt-prod"
    certmanager.k8s.io/acme-challenge-type: http01

    # Restrict access to a range of IP addresses
    # nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/24,35.26.87.5

spec:
  rules:
  - host: foo.bar.com
    http:
      paths:
        - path: /elasticsearch/?(.*)
          backend:
            # specify the ES service name
            serviceName: elasticsearch-sample-es
            servicePort: 9200
        - path: /kibana/?(.*)
          backend:
            # specify the kibana service name
            serviceName: kibana-sample-kibana
            servicePort: 5601
  tls:
    # TLS termination configuration
    # see https://github.com/kubernetes/ingress-nginx/tree/master/docs/examples/tls-termination
    - hosts:
      - foo.bar.com
      secretName: es-kibana-sample-tls-secret
```

The idea with this ingress resource is to:

* expose both Elasticsearch and Kibana on the same DNS, pointing to a single LoadBalancer IP Address (that's the LoadBalancer service of the nginx controller itself)
* automatically request a TLS certificate from Let's Encrypt, using the cert-manager, for the configured DNS
* route requests to Elasticsearch and Kibana services. Path rewrite rules can be configured as desired.
* potentially setup some IP whitelist mechanism.
* terminate TLS connections at NGINX level using the Let's Encrypt cert. Then communication from NGINX to the cluster is also using HTTPS, this time based on the "internal" cluster TLS cert (this is skipping TLS cert verification by default, the example could be extended to see how nginx controller supports that)

It seemed to work as expected, though I did not test it again recently.

Following next release, a simpler process would be to provide the Let's Encrypt certificate to the operator directly, to be used as TLS cert for Elasticsearch HTTP endpoint. This way we could avoid the 2 successive TLS encryptions, and keep a single TLS termination done by Elasticsearch. Any ingress resource could simply do TLS passthrough. But doesn't have to: it's up to the user at this point to pick the best solution that fits their need.

Some interesting resources related to the example above:
* [NGINX ingress controller doc](https://kubernetes.github.io/ingress-nginx/deploy/)
* [Cert-manager doc](https://docs.cert-manager.io/en/latest/getting-started/install.html)
* [NGINX & cert manager guide from DigitalOcean](https://www.digitalocean.com/community/tutorials/how-to-set-up-an-nginx-ingress-with-cert-manager-on-digitalocean-kubernetes)
* [NGINX ingress annotations](https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md)
