### ISSUE TITLE
Can't create index patterns in KIBANA

### ISSUE THREAD

**Issue by bcarriou** [elastic/cloud-on-k8s#1045]
## Bug Report
**What did you do?**
I want to create index pattern in KIBANA.

**What did you expect to see?**
I expect after creating an index pattern, to be able to discover it in KIBANA.

**What did you see instead? Under which circumstances?**
When I follow the procedure to create an index pattern in KIBANA, it is not created and I can not discover it.
More information: https://discuss.elastic.co/t/i-cant-create-indexes-patterns-with-eck/184194/9

We are several in this case and for the moment, we have no feedback from the members of Elastic, which has the consequence of not being able to use the Elastic stack for our projects ...

**Environment**

* Version information:

`0.8 / 7.1.0`

* Kubernetes information:

`Cloud: OVH`

```
$ kubectl version

Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:41:57Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

* Resource definition:

- Elasticsearch

```
 kubectl get elasticsearch

 NAME    HEALTH   NODES   VERSION   PHASE         AGE
 cloud   green    2       7.1.0     Operational   4h
```

- Kibana

```
 kubectl get kibana

 NAME    HEALTH   NODES   VERSION   AGE
 cloud   green    1       7.1.0     4h
```

```
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: cloud
spec:
  version: 7.1.0
  nodes:
  - nodeCount: 2
    config:
      node.master: true
      node.data: true
      node.ingest: true
    volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: cinder-high-speed # can be any available storage class
----
apiVersion: kibana.k8s.elastic.co/v1alpha1
kind: Kibana
metadata:
  name: cloud
spec:
  version: 7.1.0
  nodeCount: 1
  elasticsearchRef:
    name: cloud
```

* Logs:
When I open chrome development console,  I can see:

![Capture d’écran de 2019-06-03 15-51-34](https://user-images.githubusercontent.com/43808903/59255209-f4cef200-8c31-11e9-96b6-55609a5e33ea.png)

The following query:
`/api/saved_objects/_find?type=index-pattern&fields=title&fields=type&per_page=10000 `

returns the following result:
`{"page":1,"per_page":10000,"total":0,"saved_objects":}`

Thanks for your help

**Comment by thbkrkr** [comment]
I can not reproduce this. It seems similar to https://github.com/elastic/kibana/issues/15110.

Can you test without running filebeat and [adding sample data](https://www.elastic.co/guide/en/kibana/current/add-sample-data.html)?
Can you test without the `volumeClaimTemplates`?
Can you test with another browser?

**Comment by bcarriou** [comment]
Hi, it's seem be have a fix
https://discuss.elastic.co/t/kibana-7-cant-load-index-pattern/180167/15?u=benjamin_carriou

`set kibana.index in kibana.yml to some new name, which causes creating new index for kibana. After restart index patterns work fine.`

It is possibile to set "kibana.index" in kibana.yml with ECK ?

**Comment by thbkrkr** [comment]
> It is possibile to set "kibana.index" in kibana.yml with ECK ?

Not in `0.8` but it is in the `master` branch and it will be in the next release.

```yaml
apiVersion: kibana.k8s.elastic.co/v1alpha1
kind: Kibana
metadata:
  name: test
spec:
  version: 7.1.1
  nodeCount: 1
  config:
    kibana.index: <newname>
```
