### ISSUE TITLE
Improve updateStrategy.groups to 

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#1055]
## Context

This is how a user can create an availability zone aware Elasticsearch cluster:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.1.0
  nodes:
  - nodeCount: 1
    config:
      node.attr.zone: europe-west3-a
      cluster.routing.allocation.awareness.attributes: zone
    podTemplate:
      meta:
        labels:
          nodesGroup: group-a
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: failure-domain.beta.kubernetes.io/zone
                  operator: In
                  values:
                  - europe-west3-a
  - nodeCount: 1
    config:
      node.attr.zone: europe-west3-b
      cluster.routing.allocation.awareness.attributes: zone
    podTemplate:
      meta:
        labels:
          nodesGroup: group-b
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: failure-domain.beta.kubernetes.io/zone
                  operator: In
                  values:
                  - europe-west3-b
  updateStrategy:
    groups:
    - selector:
        matchLabels:
          nodesGroup: group-a
    - selector:
        matchLabels:
          nodesGroup: group-b
```

The `updateStrategy.groups` section of the spec logically groups pods together based on a label. We use this [when calculating changes](https://github.com/elastic/cloud-on-k8s/blob/5b7bbfb869f97a1ebab719851b7239813364b53e/operators/pkg/controller/elasticsearch/mutation/performable.go#L66-L70): before deciding on creating/deleting pods based on our budget's maxSurge & maxUnavailable, we do make sure each "logical" group gets the targeted number of pods.
This is done through a zero-ed ChangeBudet: we are not allowed to create any new pod passed the target number of pods, nor delete any pod that would get us below the target number.
This is useful for disaster recovery scenarios. For instance, if an entire region goes down (all pods deleted at once): we make sure this entire region is restored before going through the usual pod creation/deletion. Otherwise, we could end up eating all the budget adding pods to a "healthy" region, whereas some pods in another region that is critical (maybe containing primary shards are completely dead).

## Potential problem

This is a useful but quite advanced feature. Looking at the spec above, it seems pretty straightforward to understand how zones are setup through Elasticsearch node attributes and Kubernetes affinities, but harder to get how users should map this to another label on each pod, along with the corresponding groups in the `updateStrategy` section.

Should we consider having an "implicit" default updateStrategy groups, based on:

1. "logical" groups in the spec? They are not named, but we could still group them logically.
2. adding names to those groups to be event more explicit?
3.  the `failure-domain.beta.kubernetes.io/zone` "standard" label and its values, present in the spec?
4. propagating ES node attributes into labels, and use these labels to form groups.
