### ISSUE TITLE
Enable running Elastic Stack build candidates

### ISSUE THREAD

**Issue by jordansissel** [elastic/cloud-on-k8s#1065]
I would like to run build candidates. At present, it seems like this is not possible. 

When attempting to run a 7.2.0 build candidate, creating the cluster appears to fail. The controller shows the following log:

```
"level":"error","ts":1560383124.4001148,"logger":"kubebuilder.controller","msg":"Reconciler error","controller":"elasticsearch-controller","request":"default/quickstart","error":"admission webhook \"validation.elasticsearch.elastic.co\" denied the request: unsupported version upgrade from 7.2.0 to 7.2.0","errorCauses":[{"error":"admission webhook \"validation.elasticsearch.elastic.co\" denied the request: unsupported version upgrade from 7.2.0 to 7.2.0"}]... {omitted for brevity}
```

Here's my resource definition:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.2.0
  image: gcr.io/{redacted}/elasticsearch:7.2.0-a07f8500
  nodes:
  - nodeCount: 1
    config:
      node.master: true
      node.data: true
      node.ingest: true
```
