### ISSUE TITLE
Request Timeout after 30s

### ISSUE THREAD

**Issue by weeco** [elastic/cloud-on-k8s#1100]
Hey, in my Kibana I get for almost all queries "**Discover: Request Timeout after 30000ms**". If I run the query a couple minutes later again it returns the desired result. I am just querying Logs as this cluster is only used for Logging.

I believe this might be caused by slow HDDs (persistent volumes in Google Cloud) and/or not enough CPU resources. Both usages seem to spike upon queries. Increasing the RAM from 4Gi to 10Gi didn't have any effect. Is there a better way beside looking at the hardware usages in order to figure out why queries timeout in Elasticsearch?

**We have:**

6 ES Nodes each one with 1 CPU & 10Gi RAM
one index per day with 10 Shards plus 2 replicas (I believe lowering it to 2 shards makes sense)
250GB HDD persistent volume at Google Cloud
Ingesting 30Gb / 18m docs every day

**Increasing CPU**
I believe as of now it is not possible to setup elasticsearch pods so that they have burstable CPU resources instead of guaranteed resources. As queries are rather rarely executed I don't want Elasticsearch to reserve the resources all the time, instead I'd highly prefer to define burstable CPU resources. How can I do this with v0.8 (it seems like the operator always sets guaranteed CPU)?

**Comment by sebgl** [comment]
Hey @weeco,

You can specify your nodes this way to end up with an unbound CPU limit (burstable QoS):
```yaml
  nodes:
    podTemplate:
      spec:
        containers:
          - name: elasticsearch
            resources:
              limits:
                memory: 2Gi
              requests:
                memory: 2Gi
                cpu: 1
    nodeCount: 3
```

I'd love to know more about the potential storage performance issue. Can you give more details about what persistent volume you are using and how you specify them in the ES cluster spec?

**Comment by weeco** [comment]
Sure I am using persistent volumes at Google Cloud (see https://cloud.google.com/compute/docs/disks/). The throughput is coupled with the size of the disk. We currently use a 250GB HDD (non SSD) for each ES node, which equals to:

- 187.5 Read IOPS & 30MB/s throughput
 - 375 Write IOPS & 30MB/s throughput

We usually run simple ES queries in Kibana (e. g. `kubernetes.labels.app: "my-app-label"`) on a timerange spanning the recent 3 hours. When I do run such queries I initially get a error notification shown like this:

> Discover: Service Unavailable

Afterwards a couple timeout notifications and ultimately the query works after a couple minutes. I specify the HDD in my ES spec like this:

```
      volumeClaimTemplates:
        - metadata:
            name: data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 250Gi
            storageClassName: standard
```


Setting burstable CPU did not work. When I use

```
          containers:
            - name: elasticsearch
              resources:
                requests:
                  cpu: 1
                limits:
                  cpu: 4
                  memory: 6Gi
```

the operator will always set requested CPU to 4 as well. I believe there already is a PR merged to address this, but with v0.8 I cannot set burstable CPUs I guess?
