### ISSUE TITLE
Error starting an hot-warm cluster

### ISSUE THREAD

**Issue by MaxenceAdnot** [elastic/cloud-on-k8s#1111]
## Bug Report
**What did you do?**

I tried to deploy a hot-warm cluster.

**What did you expect to see?**

The cluster being set up normally. 

**What did you see instead? Under which circumstances?**

Failure in master election and/or discovery in my opinion. 

ES nodes are sending the messages below for 1 hour now: 

https://pastebin.com/8UMwaKJy

**Environment**

* Version information:

	0.8.0

* Kubernetes information:

	On Premise
        Rancher 2.2.4 with Kubernetes 1.13.5

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```	

* Resource definition:

```
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: test-ilm
spec:
  version: 7.1.0
  nodes:
  - nodeCount: 3
    config:
      node.attr.data: hot
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: 8Gi
              cpu: 2
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
        storageClassName: default
  - nodeCount: 3
    config:
      node.attr.data: warm
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: 8Gi
              cpu: 2
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
        storageClassName: default
```

* Logs:

https://pastebin.com/8UMwaKJy

**Comment by sebgl** [comment]
Hi @MaxenceAdnot,

* One detail, unrelated the master election issue you're encountering:

The hot-warm topology [doc](https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-advanced-node-scheduling.html) applies for the `master` HEAD branch, not for release 0.8. There are a few breaking changes in master compared to 0.8, that will be included in 0.9.

One particular change here is the name of the Elasticsearch data volume: we moved from `data` in `0.8` to `elasticsearch-data` on current master and `0.9`.
While you're using version 0.8 you should probably adapt your `volumeClaimTemplates` names to `data` instead of `elasticsearch-data`. Otherwise you would be using an additional emptyDir and not the expected persistent volume.

* Now regarding the master election error:

The part I'm worried about is `[cluster.initial_master_nodes] is empty on this node`. Normally the `initial_master_nodes` setting should be set in the ES config volume.

Let's try to debugging this by inspecting the nodes configuration volume:

```
kubectl get secret test-ilm-es-4djfgjd9lh -o json | jq -r '.data["elasticsearch.yml"]' | base64 -D
```

This should show us the configuration for that node, let's check if there is the `initial_master_nodes` setting defined there. Can you try that?

**Comment by MaxenceAdnot** [comment]
I recreated the pods so don't be surprised if the pod names changed.

kubectl get secret test-ilm-es-gtghh9z7cz-config -o json | jq -r '.data["elasticsearch.yml"]' | base64 -d 
```
cluster:
  name: test-ilm
discovery:
  zen:
    hosts_provider: file
    minimum_master_nodes: "4"
network:
  host: 0.0.0.0
  publish_host: ${POD_IP}
node:
  attr:
    data: hot
  name: ${POD_NAME}
path:
  data: /usr/share/elasticsearch/data
  logs: /usr/share/elasticsearch/logs
xpack:
  security:
    authc:
      reserved_realm:
        enabled: "false"
    enabled: "true"
    http:
      ssl:
        certificate: /usr/share/elasticsearch/config/node-certs/cert.pem
        certificate_authorities: /usr/share/elasticsearch/config/node-certs/ca.pem
        enabled: "true"
        key: /usr/share/elasticsearch/config/private-key/node.key
    transport:
      ssl:
        certificate: /usr/share/elasticsearch/config/node-certs/cert.pem
        certificate_authorities: /usr/share/elasticsearch/config/node-certs/ca.pem
        enabled: "true"
        key: /usr/share/elasticsearch/config/private-key/node.key
        trust_restrictions:
          path: /usr/share/elasticsearch/config/extrafiles/trust.yml
        verification_mode: certificate

```

On another node from the second node group (warm): 
 kubectl get secret test-ilm-es-9lj74btlc8-config -o json | jq -r '.data["elasticsearch.yml"]' | base64 -d 
```
cluster:
  name: test-ilm
discovery:
  zen:
    hosts_provider: file
    minimum_master_nodes: "4"
network:
  host: 0.0.0.0
  publish_host: ${POD_IP}
node:
  attr:
    data: warm
  name: ${POD_NAME}
path:
  data: /usr/share/elasticsearch/data
  logs: /usr/share/elasticsearch/logs
xpack:
  security:
    authc:
      reserved_realm:
        enabled: "false"
    enabled: "true"
    http:
      ssl:
        certificate: /usr/share/elasticsearch/config/node-certs/cert.pem
        certificate_authorities: /usr/share/elasticsearch/config/node-certs/ca.pem
        enabled: "true"
        key: /usr/share/elasticsearch/config/private-key/node.key
    transport:
      ssl:
        certificate: /usr/share/elasticsearch/config/node-certs/cert.pem
        certificate_authorities: /usr/share/elasticsearch/config/node-certs/ca.pem
        enabled: "true"
        key: /usr/share/elasticsearch/config/private-key/node.key
        trust_restrictions:
          path: /usr/share/elasticsearch/config/extrafiles/trust.yml
        verification_mode: certificate
```
