### ISSUE TITLE
APM Server cannot find ElasticSearch 

### ISSUE THREAD

**Issue by iekulyk** [elastic/cloud-on-k8s#1112]
## Bug Report
**What did you do?**

Deployed ElasticsSearch with name ```es-poc```
Once ElasticSearch became green - deployed apm-server

```
apiVersion: apm.k8s.elastic.co/v1alpha1
kind: ApmServer
metadata:
  name: apm-server-sample
spec:
  version: "7.1.0"
  nodeCount: 1
  output:
    elasticsearch:
      ref:
        name: es-poc
        namespace: default
```

**What did you expect to see?**

Operator to have logs about successful start of APM Server
APM UI available in Kibana

**What did you see instead? Under which circumstances?**

Error Finding ElasticSearch from ```apm-controller```  in operator's logs
No APM UI available in Kibana

**Environment**

* Version information: 0.8 

* Kubernetes information:

On top of AWS, built with kops

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T18:55:03Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.9", GitCommit:"16236ce91790d4c75b79f6ce96841db1c843e7d2", GitTreeState:"clean", BuildDate:"2019-03-25T06:30:48Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
``` 
* Resource definition:
elastic + kibana
```
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: es-poc
  labels:
    controller-tools.k8s.io: "1.0"
    app: elasticsearch
    component: elasticsearch-cluster
    release: poc-1.0.0
spec:
  # Cluster setup
  version: 7.1.0
  nodes:
  # Master Nodes
  - nodeCount: 1
    config:
      node.master: true
      node.data: false
      node.ingest: false
      cluster.remote.connect: false
      xpack.monitoring.collection.enabled: true
    podTemplate:
      spec:
        containers:        
          resources:
            requests:
              memory: "4096Mi"
            limits:
              memory: "4096Mi"
# -------------
  # Data Ingest Nodes
  - nodeCount: 3
    config:
      node.master: false
      node.data: true
      node.ingest: true
      xpack.monitoring.collection.enabled: true 
    podTemplate:
      spec:
        containers:
        - name: elasticsearch        
          resources:
            requests:
              memory: "2048Mi"
            limits:
              memory: "2048Mi"
    volumeClaimTemplates:
    - metadata:
       name: elasticsearch-data
      spec:
       accessModes:
       - ReadWriteOnce
       resources:
         requests:
           storage: 50Gi
       storageClassName: es-io1-3iops
---
apiVersion: kibana.k8s.elastic.co/v1alpha1
kind: Kibana
metadata:
  name: kibana-poc
  labels:
    controller-tools.k8s.io: "1.0"
    app: elasticsearch
    component: kibana
    release: poc-1.0.0
spec:
  version: 7.1.0
  nodeCount: 1
  elasticsearchRef:
    name: es-poc

```

apm-server
```
apiVersion: apm.k8s.elastic.co/v1alpha1
kind: ApmServer
metadata:
  name: apm-server-sample
spec:
  version: "7.1.0"
  nodeCount: 1
  output:
    elasticsearch:
      ref:
        name: es-poc
        namespace: default
```

* Logs:

```
{"level":"info","ts":1560947774.6646252,"logger":"apmserver-controller","msg":"Start reconcile iteration","iteration":10}
{"level":"info","ts":1560947774.6646705,"logger":"finalizer","msg":"Registering finalizer","name":"dynamic-watches.finalizers.apm.k8s.elastic.co"}
{"level":"info","ts":1560947774.664701,"logger":"apmserver-controller","msg":"Aborting ApmServer deployment reconciliation as no Elasticsearch output is configured"}
{"level":"info","ts":1560947774.6647358,"logger":"generic-reconciler","msg":"Creating Service dev-telemetry/apm-server-sample-apm-server"}
{"level":"info","ts":1560947774.6825085,"logger":"apm-es-association-controller","msg":"End reconcile iteration","iteration":7357,"took":0.017919053}
{"level":"info","ts":1560947774.6825573,"logger":"apm-es-association-controller","msg":"Start reconcile iteration","iteration":7358}
{"level":"info","ts":1560947774.682592,"logger":"apm-es-association-controller","msg":"End reconcile iteration","iteration":7358,"took":0.000034526}
{"level":"info","ts":1560947774.6832368,"logger":"apmserver-controller","msg":"Updating status","iteration":10}
{"level":"info","ts":1560947774.6870782,"logger":"apmserver-controller","msg":"End reconcile iteration","iteration":10,"took":0.022464887}
{"level":"error","ts":1560947774.6871192,"logger":"kubebuilder.controller","msg":"Reconciler error","controller":"apmserver-controller","request":"dev-telemetry/apm-server-sample","error":"Operation cannot be fulfilled on apmservers.apm.k8s.elastic.co \"apm-server-sample\": the object has been modified; please apply your changes to the latest version and try again","stacktrace":"github.com/elastic/cloud-on-k8s/operators/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/elastic/cloud-on-k8s/operators/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/elastic/cloud-on-k8s/operators/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/elastic/cloud-on-k8s/operators/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:217\ngithub.com/elastic/cloud-on-k8s/operators/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/elastic/cloud-on-k8s/operators/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/elastic/cloud-on-k8s/operators/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/elastic/cloud-on-k8s/operators/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/elastic/cloud-on-k8s/operators/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/elastic/cloud-on-k8s/operators/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/elastic/cloud-on-k8s/operators/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/elastic/cloud-on-k8s/operators/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
{"level":"info","ts":1560947775.6873043,"logger":"apmserver-controller","msg":"Start reconcile iteration","iteration":11}
{"level":"info","ts":1560947775.6873825,"logger":"apmserver-controller","msg":"Aborting ApmServer deployment reconciliation as no Elasticsearch output is configured"}
{"level":"info","ts":1560947775.6874254,"logger":"apmserver-controller","msg":"Updating status","iteration":11}
{"level":"info","ts":1560947775.692494,"logger":"apm-es-association-controller","msg":"Start reconcile iteration","iteration":7359}
{"level":"info","ts":1560947775.6925442,"logger":"apm-es-association-controller","msg":"End reconcile iteration","iteration":7359,"took":0.000050648}
{"level":"info","ts":1560947775.6926525,"logger":"apmserver-controller","msg":"End reconcile iteration","iteration":11,"took":0.005350396}
{"level":"info","ts":1560947775.692689,"logger":"apmserver-controller","msg":"Start reconcile iteration","iteration":12}
{"level":"info","ts":1560947775.692716,"logger":"apmserver-controller","msg":"Aborting ApmServer deployment reconciliation as no Elasticsearch output is configured"}
{"level":"info","ts":1560947775.6927533,"logger":"apmserver-controller","msg":"End reconcile iteration","iteration":12,"took":0.000064341}
{"level":"info","ts":1560947784.682671,"logger":"apm-es-association-controller","msg":"Start reconcile iteration","iteration":7360}
{"level":"info","ts":1560947784.6827517,"logger":"apm-es-association-controller","msg":"End reconcile iteration","iteration":7360,"took":0.000082306}

```
