### ISSUE TITLE
how to use it on data center if there has no internet access

### ISSUE THREAD

**Issue by Pandoraemon** [elastic/cloud-on-k8s#1152]
We want to use it in our private data center, but we have no internet access for our kebernetes cluster. can we use our own images inited with plugins what we want?

**Comment by sebgl** [comment]
Hi @Pandoraemon, yes you can use your own images, as long as they are based on the official Elasticsearch Docker images, and don't tweak the Docker entrypoint.

In the Elasticsearch spec, you can specify the Elasticsearch image you want to use:

```
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.1.1
  image: your.custom.docker.image/here:7.1.1
  nodes:
  - nodeCount: 1
    config:
      node.master: true
      node.data: true
      node.ingest: true
```

You will also need to push ECK Docker image to your own Docker registry, and override the yaml manifest to specify that image:

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elastic-operator
  namespace: elastic-system
  labels:
    control-plane: elastic-operator
spec:
  selector:
    matchLabels:
      control-plane: elastic-operator
  serviceName: elastic-operator
  template:
    metadata:
      labels:
        control-plane: elastic-operator
    spec:
      serviceAccountName: elastic-operator
      containers:
      - image: docker.elastic.co/eck/eck-operator:0.8.1    <----- HERE
        name: manager
        args: ["manager", "--operator-roles", "all"]
        env:
          - name: OPERATOR_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: WEBHOOK_SECRET
            value: webhook-server-secret
          - name: WEBHOOK_PODS_LABEL
            value: elastic-operator
          - name: OPERATOR_IMAGE
            value: docker.elastic.co/eck/eck-operator:0.8.1 <----- AND HERE
```
