### ISSUE TITLE
Improve updateStrategy.changeBudget to better consider PVC reuse

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#1153]
## Context

Our changeBudget currently looks like this:

```
updateStrategy:
    changeBudget:
        maxSurge: 1   # indicates we allow one more node during cluster mutations
        maxUnavailable: 0 # indicates we allow one less node during cluster mutations
```

I think it maps perfectly well grow-and-shrink (or shrink-and-grow) upgrades, where we migrate data away from a node before deleting it. Either we add new nodes first, then remove deprecated nodes. Either we remove deprecated nodes first (after data is migrated), then add new nodes. It's possible to combine both, which can give interesting options but is rather confusing and hard to understand.

## PVC Reuse

PVC reuse is enabled when `maxUnavailable` is larger than 0. We want to delete nodes first, then create new nodes that will reuse the PVC of the deleted ones. The important distinction here is that we don't migrate data, since we "know" a node will come back online very soon with the missing shards form the stopped node.

With the way things work currently, if `maxUnavailable > 0` and some nodes are identified for PVC reuse, they **will** go through the PVC reuse process (rolling upgrade), and never follow the data migration path. Allowing both to work at the same time could be dangerous, since we would do some back-and-forth between migrating data or shutting down nodes while disabling shards allocations, in different consecutive reconciliations, depending on the resources state.

## Options for the user

I think, generally, users should be able to make the following choices:

1. Request data migrations, don't reuse PVCs. Rely on `maxSurge` and `maxUnavailable` to control that behaviour. This should be the default if nodes are not using PVCs but emptyDirs.
1. Always reuse PVCs, in a safe way. Meaning a node won't be shut down if a cluster health check does not pass (eg. cluster green and/or some replicas of the node indices live elsewhere).
1. Reuse PVCs, in an unsafe way. This would skip the "health check" described above, could cause downtime, and would allow full cluster restarts.
1. Control how many nodes can be shut down while reusing PVCs, in a safe or unsafe way (similar to the `maxUnavailable` setting).
1. (harder to implement safely:) fallback to data migration if a PVC reuse is impossible due to the state of the cluster.

## Example

An idea to express that (to be discussed and improved):

```yaml
updateStrategy:
    changeBudget:
        dataMigration:
            maxSurge: 1
            maxUnavailable: 1
        pvcReuse:
            enable: true   # default
            allowUnsafe: false   # default
            maxUnavailable: 1
            fallbackToDataMigrationAfter: 2m    # not sure about that one
```
