### ISSUE TITLE
Expose a dedicated service for coordinator nodes

### ISSUE THREAD

**Issue by mfouilleul** [elastic/cloud-on-k8s#1165]
Hello!

We tried to expose a dedicated k8s service to expose "coordinator" nodes. It works well with the label selectors but we face of certificate issue when using the non-default service, do you have good practices to share to do this? 

```
kubectl -n sre get svc -l elasticsearch.k8s.elastic.co/cluster-name=log
NAME               TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
log-es             ClusterIP   10.64.134.96    <none>        9200/TCP   3d20h
log-es-client      ClusterIP   10.64.135.210   <none>        9200/TCP   3d21h
log-es-discovery   ClusterIP   None            <none>        9300/TCP   3d20h
```

```
---
apiVersion: v1
kind: Service
metadata:
  labels:
    common.k8s.elastic.co/type: elasticsearch
    elasticsearch.k8s.elastic.co/cluster-name: log
    elasticsearch.k8s.elastic.co/node-ingest: "true"
    elasticsearch.k8s.elastic.co/node-master: "true"
    elasticsearch.k8s.elastic.co/node-data: "false"
  name: log-es-client
  namespace: sre
spec:
  ports:
  - name: https
    port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    common.k8s.elastic.co/type: elasticsearch
    elasticsearch.k8s.elastic.co/cluster-name: log
    elasticsearch.k8s.elastic.co/node-ingest: "true"
    elasticsearch.k8s.elastic.co/node-master: "true"
    elasticsearch.k8s.elastic.co/node-data: "false"
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

Certificate not valid when using log-es-client:
```
Failed to connect to backoff(elasticsearch(https://log-es-client:9200)): Get https://log-es-client:9200: x509: certificate is valid for log-es-b2vzchx4gw.node.log.sre.es.cluster.local, log-es-b2vzchx4gw, log-es, log-es.sre.svc.cluster.local, log-es-discovery, log-es-discovery.sre.svc.cluster.local, not log-es-client
```

Thanks!

**Comment by pebrc** [comment]
Assuming you are running 0.8.0 then there is not much you can do at the moment unfortunately other than doing client-side routing to the nodes you want to prefer.

In 0.9.0 you will be able to  either specify SANs that include your custom service in the Elasticsearch spec:

```yaml
   http:
     tls:
       # Add a list of SANs into the HTTP certificate
       selfSignedCertificate:
         subjectAltNames:
         - dns: log-es-client
```

alternatively you will be able to supply your own HTTP certificates: 

```yaml
   http:
     tls:
      certificate:
        secretName: "your-tls-secret"
```
