### ISSUE TITLE
OSS support

### ISSUE THREAD

**Issue by racevedoo** [elastic/cloud-on-k8s#1172]
## Proposal

Support OSS version. Currently, when I try to use the oss elasticsearch version(image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.2.0), configuring like:
```
node.master: true
node.data: true
xpack.graph.enabled: false
xpack.ml.enabled: false
xpack.monitoring.enabled: false
xpack.security.enabled: false
xpack.watcher.enabled: false
```
I get the following error:
```
Error from server (node[0]: xpack.security.enabled is not user configurable): error when creating "kubernetes/elasticsearch/elasticsearch-logs.yml": admission webhook "validation.elasticsearch.elastic.co" denied the request: node[0]: xpack.security.enabled is not user configurable
```

Is that intended? Are there any plans to support oss?
Thanks!

**Comment by agup006** [comment]
Hi @racevedoo, ECK turns on security on by default for every cluster and requires the [free security features from 6.8+ and 7.1+](https://www.elastic.co/blog/security-for-elasticsearch-is-now-free) which is why that error is appearing. We do not have plans to support OSS at this time

**Comment by dzmitry-lahoda** [comment]
so we are going to secure whole ES via Istio and do not need xpack security. why it is enforced?

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: elastic-tracing
spec:
  version: 7.2.0
  nodes:
  - nodeCount: 2 # at least some safety
    config:
      node.master: true
      node.data: true
      node.ingest: true
      xpack.security.enabled: false
      # xpack.security.authc.token.enabled: false
      # xpack.security.http.ssl.enabled: false
      # xpack.security.transport.ssl.enabled: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data # note: elasticsearch-data must be the name of the Elasticsearch volume
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        #storageClassName: standard # can be any available storage class      
    secureSettings: []
```
