### ISSUE TITLE
Numeric config values lead to unexpected differences

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#1190]
**What did you do?**
Tried to configure SAML which uses a numeric config value
```
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: elasticsearch-saml
spec:
  version: "7.2.0"
  nodes:
  - name: "data"
    nodeCount: 1
    config:
      xpack.security.authc.realms:
        saml:
          saml1:
            order: 2
````

**What did you expect to see?**
Just a cluster with one pod to come up.

**What did you see instead? Under which circumstances?**
Operator was constantly cycling the pods every few seconds. 
Reason was a configuration mismatch between the pods the operator had started and the expected pod spec in the `order` field of the configuration.

Problem is that we use two different ways to parse the configuration we expect and the configuration we observe in the config secret of the pod. 

The config secret in the pod is parsed from yaml which parses `1` into an `uint64` the expected config comes via the API server marshalled via JSON and our `DeepCopy` implementation does also JSON marshalling which turns the `1` into a `float64` which always differs. 

```golang
func TestConfig_PrimitiveConversion(t *testing.T) {
	fixture := Config{Data: map[string]interface{}{"a": 1}}
	copy := fixture.DeepCopy()
	expected, err := settings.NewCanonicalConfigFrom(fixture.Data)
	require.NoError(t, err)
	parsed, err := settings.ParseConfig([]byte(`a: 1`))
	require.NoError(t, err)
	if diff := expected.Diff(parsed, nil); diff != nil {
		t.Error(diff)
	}
	actual, err := settings.NewCanonicalConfigFrom(copy.Data)
	if diff := expected.Diff(actual, nil); diff != nil {
		t.Error(diff) //this fails
	}
}
```

So we either have to make the `Diff` function so that it considers `float64` and `uint64` the same (sounds wrong) or normalize the config before comparing it
