### ISSUE TITLE
Unable to retrieve proper tls key,cert and ca for JagerTracing

### ISSUE THREAD

**Issue by secat** [elastic/cloud-on-k8s#1191]
This is issue is primarily for getting help using an ElasticSearch cluster created by this ElasticSearch Operator.

I am currently using the following versions:
- Elasticsearch Operator version: v0.8.0
- ElasticSearch version: v6.8.0

I am using an ElasticSearch cluster as a storage backend for Jaeger distributed tracing. 

Since the ElasticSearch cluster is using self-signed certificates, I must provide to Jaeger the following files:
- tls.ca
- tls.cert
- tls.key

The ElasticSearch Operator generates multiple secrets file:
```
NAME                               TYPE                                  DATA   AGE
quickstart-ca                      Opaque                                1      4h43m
quickstart-ca-private-key          Opaque                                1      4h43m
quickstart-elastic-user            Opaque                                1      4h43m
quickstart-es                      Opaque                                2      4h41m
quickstart-es-7sc6vtf2xx-certs     Opaque                                3      4h43m
quickstart-es-7sc6vtf2xx-config    Opaque                                1      4h43m
quickstart-es-ca                   Opaque                                1      4h43m
quickstart-es-roles-users          Opaque                                3      4h43m
quickstart-extrafiles              Opaque                                1      4h43m
quickstart-internal-users          Opaque                                3      4h43m
quickstart-kibana-user             Opaque                                1      4h43m
quickstart-secure-settings         Opaque                                0      4h43m
```

What are the secret contents that I should take in order to provide the right tls files to Jaeger?

> **NOTE**: This issue is related to https://github.com/jaegertracing/jaeger-operator/issues/496

**Comment by secat** [comment]
I tried using the current master version of the ElasticSearch Operator with Jaeger tracing and I have the following error: `x509: certificate is valid for quickstart-es-lqtqnnhx57.node.quickstart.observability.es.local, not quickstart-es-http.observability.svc`:
```
$ kubectl --namespace=observability logs local-jaeger-tracing-collector-57f86dc65d-fl9gj -f                                                                                                                                                   2019/07/05 15:06:27 maxprocs: Leaving GOMAXPROCS=6: CPU quota undefined
{"level":"info","ts":1562339187.077162,"caller":"flags/service.go:115","msg":"Mounting metrics handler on admin server","route":"/metrics"}
{"level":"info","ts":1562339187.0772986,"caller":"flags/admin.go:108","msg":"Mounting health check on admin server","route":"/"}
{"level":"info","ts":1562339187.077337,"caller":"flags/admin.go:114","msg":"Starting admin HTTP server","http-port":14269}
{"level":"info","ts":1562339187.0773468,"caller":"flags/admin.go:100","msg":"Admin server started","http-port":14269,"health-status":"unavailable"}
{"level":"fatal","ts":1562339192.1214948,"caller":"collector/main.go:89","msg":"Failed to init storage factory","error":"failed to create primary Elasticsearch client: health check timeout: Head https://quickstart-es-http.observability.svc:9200: x509: certificate is valid for quickstart-es-lqtqnnhx57.node.quickstart.observability.es.local, not quickstart-es-http.observability.svc: no Elasticsearch node available","errorVerbose":"no Elasticsearch node available\ngithub.com/jaegertracing/jaeger/vendor/gopkg.in/olivere/elastic%2ev5.init.ializers\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/gopkg.in/olivere/elastic.v5/client.go:88\nruntime.main\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/proc.go:188\nruntime.goexit\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/asm_amd64.s:1337\nhealth check timeout: Head https://quickstart-es-http.observability.svc:9200: x509: certificate is valid for quickstart-es-lqtqnnhx57.node.quickstart.observability.es.local, not quickstart-es-http.observability.svc\ngithub.com/jaegertracing/jaeger/vendor/gopkg.in/olivere/elastic%2ev5.(*Client).startupHealthcheck\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/gopkg.in/olivere/elastic.v5/client.go:1116\ngithub.com/jaegertracing/jaeger/vendor/gopkg.in/olivere/elastic%2ev5.NewClient\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/gopkg.in/olivere/elastic.v5/client.go:244\ngithub.com/jaegertracing/jaeger/pkg/es/config.(*Configuration).NewClient\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/pkg/es/config/config.go:100\ngithub.com/jaegertracing/jaeger/plugin/storage/es.(*Factory).Initialize\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/plugin/storage/es/factory.go:80\ngithub.com/jaegertracing/jaeger/plugin/storage.(*Factory).Initialize\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/plugin/storage/factory.go:107\nmain.main.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/main.go:88\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).execute\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:762\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).ExecuteC\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:852\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).Execute\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:800\nmain.main\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/main.go:180\nruntime.main\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/proc.go:200\nruntime.goexit\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/asm_amd64.s:1337\nfailed to create primary Elasticsearch client\ngithub.com/jaegertracing/jaeger/plugin/storage/es.(*Factory).Initialize\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/plugin/storage/es/factory.go:82\ngithub.com/jaegertracing/jaeger/plugin/storage.(*Factory).Initialize\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/plugin/storage/factory.go:107\nmain.main.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/main.go:88\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).execute\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:762\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).ExecuteC\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:852\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).Execute\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:800\nmain.main\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/main.go:180\nruntime.main\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/proc.go:200\nruntime.goexit\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/asm_amd64.s:1337","stacktrace":"main.main.func1\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/main.go:89\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).execute\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:762\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).ExecuteC\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:852\ngithub.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra.(*Command).Execute\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/vendor/github.com/spf13/cobra/command.go:800\nmain.main\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/main.go:180\nruntime.main\n\t/home/travis/.gimme/versions/go1.12.1.linux.amd64/src/runtime/proc.go:200"}
```

why is the SAN of the generated certificates using:
```
Other Name:
     CN=0c 3f 71 75 69 63 6b 73 74 61 72 74 2d 65 73 2d 6c 71 74 71 6e 6e 68 78 35 37 2e 6e 6f 64 65 2e 71 75 69 63 6b 73 74 61 72 74 2e 6f 62 73 65 72 76 61 62 69 6c 69 74 79 2e 65 73 2e 6c 6f 63 61 6c
DNS Name=quickstart-es-lqtqnnhx57.node.quickstart.observability.es.local
IP Address=10.1.1.225
IP Address=127.0.0.1
```

**Comment by sebgl** [comment]
Hi @secat, 

I don't know much about how Jaeger tries to connect to Elasticsearch. If it behaves like most ES clients, it should connect to the Elasticsearch HTTPS endpoint, and will (unless verification disabled) verify that the certificate provided by the server (Elasticsearch) is valid. That is, is signed by a known CA.

On 0.8, you should retrieve `quickstart-ca`, and pass the CA certificate to Jaeger for trust.

On master, you should retrieve `quickstart-http-certs-public` and pass the certificate to Jaeger for trust.

Jaeger normally does not need a particular public & private key to reach Elasticsearch. Elasticsearch will not validate the client identity by default. If your Jaeger config still requires them, you can probably generate your own private & public key for Jaeger (completely decoupled form ES certs), this will normally then be ignored by Elasticsearch.

> Why using a DNS name like quickstart-es-lqtqnnhx57.node.quickstart.observability.es.local in the SAN of the generated certificates?

Here you retrieved the TLS certificate generated for transport protocol communication for a particular node (`quickstart-es-lqtqnnhx57` is the named of that node). This is used by the ES node to identify among other ES nodes. You should not use that certificate yourself to connect to Elasticsearch.


If you need to override the SAN of the generated HTTP certs (but I don't think you do here), you can [follow these instructions](https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-accessing-elastic-services.html#k8s-static-ip-custom-domain).

**Comment by secat** [comment]
@sebgl thank you for the information, I will try to make it work at the beginning of next week.

**Comment by secat** [comment]
@sebgl I was finally able to make it work.

Thank you for your help.

For the record, here is the configuration that I have used with the `jaeger` custom resource manifest:
```yaml
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: local-jaeger-tracing
  namespace: observability
spec:
  strategy: allInOne
  allInOne:
    image: docker.io/jaegertracing/all-in-one:1.13
    options:
      collector:
        zipkin:
          http-port: "9411"
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: https://quickstart-es-http.observability.svc.cluster.local:9200
        tls.ca: /etc/ssl/certs/tls.crt
    secretName: quickstart-es
  ingress:
    enabled: false
  agent:
    strategy: Sidecar
  volumeMounts:
  - name: es-tls
    mountPath: /etc/ssl/certs
  volumes:
  - name: es-tls
    secret:
      secretName: quickstart-es-http-certs-public
```

Here is the `elasticsearch` custom resource manifest:
```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: quickstart
  namespace: observability
spec:
  version: 6.8.0
  http:
    tls:
      selfSignedCertificate:
        subjectAltNames:
        - dns: quickstart-es-http.observability.svc.cluster.local
        - dns: quickstart-es-http
  nodes:
  - nodeCount: 1
    config:
      node.master: true
      node.data: true
      node.ingest: true
```
Here is a screenshot taken from kibana:

![image](https://user-images.githubusercontent.com/5402030/60818323-75b6d600-a16b-11e9-8148-71a925b54fd5.png)

**Comment by sebgl** [comment]
Awesome, thanks for the update @secat. Mounting the cert secret is the way to go! 👍 

FWIW I think you can set the Jaeger URL to `https://quickstart-es:9200`, and you can also probably remove the `subjectAltNames` section of the Elasticsearch spec. `quickstart-es` should already be specified in the generated cert by default.

**Comment by sebgl** [comment]
Closing this now, let's reopen if needed.

**Comment by secat** [comment]
@sebgl FYI, the valid URLs to pass to Jaeger are:
- `https://quickstart-es-http.observability.svc:9200`
- `https://quickstart-es-http.observability:9200`

if we remove the `subjectAltNames`.

Self-signed Certificate screenshot:
![image](https://user-images.githubusercontent.com/5402030/60823498-a7349f00-a175-11e9-8220-082e2f96cf7a.png)

Again, thank you for your help!

**Comment by sebgl** [comment]
Interesting @secat, thanks for raising this.
It looks like a bug. Let's make sure this is fixed in the next release: https://github.com/elastic/cloud-on-k8s/issues/1217.

**Comment by vishnuhd** [comment]
@sebgl @secat I am having hard time setting up the TLS for Jaeger with ES backend.
What I did :
1. The Jaeger operator is deployed from master.
2. Deploy the Elastic search operator from https://github.com/elastic/cloud-on-k8s (v0.8.1).
3. Deployed the ES cluster :
```
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: quickstart
  namespace: observability
spec:
  version: 6.8.0
  nodes:
  - nodeCount: 1
    config:
      node.master: true
      node.data: true
      node.ingest: true
```
4. Deployed Jaeger cluster :
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: my-jaeger
  namespace: observability
spec:
  strategy: production
  ui:
    options:
      dependencies:
        menuEnabled: false
      tracking:
        gaID: UA-000000-2
      menu:
        - label: "About Jaeger"
          items:
            - label: "Documentation"
              url: "https://www.jaegertracing.io/docs/latest"
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: https://quickstart-es.observability.svc.cluster.local:9200
        tls.ca: /etc/ssl/certs/ca.pem
    secretName: mysecret
  ingress:
    enabled: false
  agent:
    strategy: DaemonSet
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  volumeMounts:
  - name: es-tls
    mountPath: /etc/ssl/certs
  volumes:
  - name: es-tls
    secret:
      secretName: quickstart-ca
```
The `quickstart-ca` is being deployed by ES operator having the `ca.pem`.
5. The user and password for ES secret :
```
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: observability
type: Opaque
data:
  ES_USERNAME: ZWxhc3RpYwo=       #Base64
  ES_PASSWORD: ejJuczdwNWJrYm5wOHF0c3dkbmJ4bjd4Cg==      #Base64
```
But, both `collector` and `query` are failing with logs :
```
{"level":"fatal","ts":1562781276.0102606,"caller":"collector/main.go:89","msg":"Failed to init storage factory","error":"failed to create primary Elasticsearch client: health check timeout: no Elasticsearch node available","errorVerbose":"no Elasticsearch node available\ngithub.com/jaegertracing
```
The ES cluster node is having the logs :
```
[2019-07-10T17:03:30,644][WARN ][o.e.h.n.Netty4HttpServerTransport] [quickstart-es-2f5spqgbvh] caught exception while handling client http traffic, closing connection [id: 0xd76cf43a, L:0.0.0.0/0.0.0.0:9200 ! R:/100.96.2.77:52448]
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: Received fatal alert: unknown_ca
...
[2019-07-10T11:58:17,030][WARN ][o.e.h.n.Netty4HttpServerTransport] [quickstart-es-2f5spqgbvh] caught exception while handling client http traffic, closing connection [id: 0xab9df0e2, L:0.0.0.0/0.0.0.0:9200 ! R:/100.96.2.70:50728]
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: Received fatal alert: bad_certificate
...
```
However when I do a curl from inside the cluster, the connection is successful :
```
curl --cacert ca.pem -u elastic:$PW https://quickstart-es.observability.svc.cluster.local:9200
{
  "name" : "quickstart-es-2f5spqgbvh",
  "cluster_name" : "quickstart",
  "cluster_uuid" : "u3BrsbGNStG4yCz28VDhGA",
  "version" : {
    "number" : "6.8.0",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "65b6179",
    "build_date" : "2019-05-15T20:06:13.172855Z",
    "build_snapshot" : false,
    "lucene_version" : "7.7.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
```
Can anyone please put some light on it ?
