### ISSUE TITLE
Allow setting pod ephemeral storage resources

### ISSUE THREAD

**Issue by racevedoo** [elastic/cloud-on-k8s#1215]
## Bug Report
**What did you do?**
Set the `containers` field on podTemplate.spec as follows:
```yml
          containers:
            - name: elasticsearch
              resources:
                limits:
                  ephemeral-storage: "10Gi"
                  memory: 13Gi
                  cpu: 1.6
                requests:
                  ephemeral-storage: "5Gi"
                  memory: 13Gi
                  cpu: 1.6
```
**What did you expect to see?**
The ephemeral storage requests/resouces should be propagated to elasticsearch pods

**What did you see instead? Under which circumstances?**
The ephemeral storage is not propagated to the pods

**Environment**
AWS EKS, k8s version 1.11
* Version information:
0.8.1

* Kubernetes information:
AWS EKS 1.11
