### ISSUE TITLE
kibana podTemplate does not support annotations

### ISSUE THREAD

**Issue by donbowman** [elastic/cloud-on-k8s#1235]
## Bug Report
**What did you do?**

WIth the following CRD usage:
```
---
apiVersion: kibana.k8s.elastic.co/v1alpha1
kind: Kibana
metadata:
  name: kibana
  namespace: kibana
spec:
  version: 7.2.0
  nodeCount: 1
  podTemplate:
    metadata:
      labels:
        foo: bar
      annotations:
        fluentbit.io/exclude: "true"
  elasticsearchRef:
    name: elastic
    namespace: elasticsearch

```

THe resulting pod is:

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/podIP: 10.24.1.61/32
  creationTimestamp: "2019-07-13T20:27:51Z"
  generateName: kibana-kibana-57ccb8bfc6-
  labels:
    common.k8s.elastic.co/type: kibana
    foo: bar
    kibana.k8s.elastic.co/config-checksum: 8c88914ab79f72878ac3276024f6441a945246755c0bcb64b14340b4
    kibana.k8s.elastic.co/name: kibana
    pod-template-hash: 57ccb8bfc6
  name: kibana-kibana-57ccb8bfc6-mfmk7
```

you can see that the label worked (`foo: bar`), but the annotation went missing (fluentbit.io/exclude: true).

In the Elasticsearch CRD, however, it worked:

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/podIP: 10.24.1.7/32
    fluentbit.io/exclude: "true"
    update.k8s.elastic.co/timestamp: "2019-07-13T08:30:55.477488576Z"
  creationTimestamp: "2019-07-13T01:02:11Z"
  labels:
    common.k8s.elastic.co/type: elasticsearch
```

so its specific to the Kibana CRD, not generic in the operator.

**What did you expect to see?**

I expected my annotations were carried to the output

**What did you see instead? Under which circumstances?**

Kibana annotations vanished

**Environment**

* Version information:

0.8.1 operator

* Kubernetes information:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-gke.8", GitCommit:"7d3d6f113e933ed1b44b78dff4baf649258415e5", GitTreeState:"clean", BuildDate:"2019-06-19T16:37:16Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}
```
