### ISSUE TITLE
Support APM Agent Config Management:

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#1264]
Starting with 7.3 APM server includes agent config management which requires a Kibana connection. We could facilitate the establishment of that connection in a similar way as we do for the Elasticsearch output by allowing users to simply specify a reference to a Kibana resource. 

We would also need to specify a Kibana user with the correct permissions

**Comment by simitt** [comment]
FYI starting with 7.5 Agent Config Management will be GA and supports backend and RUM agents.

**Comment by simitt** [comment]
In ESS agent configuration management is turned on by default. The mentioned default connection to Kibana would improve usability when making use of this feature.

**Comment by barkbay** [comment]
I started to work on this issue while I'm experimenting with the APM Server.

I guess it makes no sense to just have a Kibana reference in the APM Server specification ? IIUC Kibana and the APM Server must share the same Elasticsearch cluster.
But since every object in ECK can freely set its associations it means that a user may produce a weird topology like:
* APM Server is associated to Kibana1 and Elasticsearch1
* Kibana1 is associated to Elasticsearch2 

It raises the question of how to deal correctly with the Elasticsearch reference:
* Should we infer the Elasticsearch reference/connection for the APM Server from the Kibana spec ?
* If both references _(Elasticsearch+Kibana)_ are specified in the APM specification then should we give precedence to the ones specified by the user ? But what if the 2 Elasticsearch clusters are not the same ? Should we still proceed, create the 2 required users in the 2 clusters but generate a warning ?

**Comment by simitt** [comment]
> I guess it makes no sense to just have a Kibana reference in the APM Server specification ? IIUC Kibana and the APM Server must share the same Elasticsearch cluster.

Right now APM Server uses the Kibana connection only for querying information managed by Kibana. It does _not_ use the Kibana connection for any index pattern or dashboard setup. Therefore it doesn't directly care about the Elasticsearch instance used by Kibana. 

A default reference to the started Kibana instance should be enough, no extra handling for underlying Elasticsearch instances is necessary (from an APM Server point of view). The default reference to ES can be overwritten via APM Server, the default Kibana reference also needs to support user configuration.

**Comment by barkbay** [comment]
> A default reference to the started Kibana instance should be enough

I'm not sure that there is a "default reference", or maybe I didn't get what is it. 
With ECK a user can freely create some associations between objects. As of today to create an association between an Elasticsearch cluster and an APM Server user have to create the 2 following objects:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: es-sample
spec:
  version: 7.5.0
  nodeSets:
  - name: default
    count: 3
```

```yaml
apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-sample
spec:
  version: 7.5.0
  count: 1
  elasticsearchRef:
    name: "es-sample"
```

Now let say that the user has created a Kibana instance somewhere referencing the Elasticsearch cluster:

```yaml
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kb-sample
spec:
  version: 7.5.0
  count: 1
  elasticsearchRef:
    name: "es-sample"
```

And let say that the user wants to add a connexion between the APM Server and Kibana, the idea would be to enhance the spec of the APM Server by adding a reference to Kibana in the APM spec, something like that:

```yaml
apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-sample
spec:
  version: 7.5.0
  count: 1
  elasticsearchRef:
    name: "es-sample"
  kibanaRef: # here
    name: "kb-sample"
```

My questions are:
* What if `kb-sample` is not referencing `es-sample`?
* Does it make sense to only specify `kibanaRef` ?

I don't think we have to answer these questions to have a first implementation. We must add something like `kibanaRef` in the APM Server specification, we can expect from the user to set both of them, without doing any extra check. It was some random thoughts about the possible ways a user can set `elasticsearchRef` and `kibanaRef`.
