### ISSUE TITLE
Kibana 7.2. does not run as root and ECK is not setting a security context

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#1280]
Kubernetes version:  v1.13.6-gke.13

Kibana as of version 7.2 does not allow to be run as root user unless the the `--allow-root` startup flag is set. 

We don't set a default security context in the pod spec so **Kibana fails to start**. 

Setting 
```
spec: 
  containers:
      - name: kibana
         securityContext:
           runAsUser: 1000
```
Seems to workaround the problem but I wonder if the underlying issue is in the Kibana docker image.

We are not detecting the condition in our e2e tests because we set a default security policy there.
