### ISSUE TITLE
Implement grow-and-shrink for StatefulSets

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#1290]
We optimized StatfulSets orchestration for rolling upgrade first.
We could still handle grow and shrink, as [outlined in this issue](https://github.com/elastic/cloud-on-k8s/issues/1173).

**Comment by david-kow** [comment]
@sebgl Can we close this? It seems to me that this is effectively implemented with https://github.com/elastic/cloud-on-k8s/pull/1812 and using:
```
spec:
  updateStrategy:
    changeBudget:
      maxUnavailable: 0
      maxSurge: >0
```
