### ISSUE TITLE
Make sure NodeSpec with EmptyDirs (no PVC) are handled correctly

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#1291]
With the move to StatefulSets, we optimize for rolling-upgrades on clusters using PersistentVolumes.

What about EmptyDirs? It's still a use case we want to support.
Let's make sure the current rolling upgrade process works fine as well with EmptyDir.

Related: https://github.com/elastic/cloud-on-k8s/issues/1290

**Comment by thbkrkr** [comment]
Successfully rolling upgrade from 7.2.0 to 7.3.0 with empty directories without loss of data or downtime.

YAML manifest used:
```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: test-empty-dirs
spec:
  version: 7.2.0
  nodes:
  - name: masters
    nodeCount: 3
    config:
      xpack.monitoring.collection.enabled: true
    podTemplate:
      spec:
        volumes:
        - name: elasticsearch-data
          emptyDir: {}
---
apiVersion: kibana.k8s.elastic.co/v1alpha1
kind: Kibana
metadata:
  name: test-empty-dirs
spec:
  version: 7.2.0
  http:                  
    service:
      spec:
        type: LoadBalancer
  nodeCount: 1
  elasticsearchRef:
    name: test-empty-dirs
```

At the end of the upgrade, the Stack Monitoring ui shows some ghost nodes because the IP has changed.

![2019-08-08-151547_524x700_scrot](https://user-images.githubusercontent.com/582883/62706266-73a49900-b9ef-11e9-9191-7355c830e86c.png)
