### ISSUE TITLE
Setting service type to NodePort has no effect

### ISSUE THREAD

**Issue by dan-evolvere** [elastic/cloud-on-k8s#1436]
## Bug Report
**What did you do?**
Changed the LoadBalancer service type to NodePort
**What did you expect to see?**
A NodePort service be created, instead only a 
**What did you see instead? Under which circumstances?**
A ClusterIP service
**Environment**
Straight Kubernetes on prem
* Version information:
latest alpha 0.9
	insert version or git commit id here

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* On premise ?
	* Kubernetes distribution: Rancher
	
	for each of them please give us the version you are using
```
$ kubectl version
```

Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

```
cat <<EOF | kubectl apply -f -
apiVersion: kibana.k8s.elastic.co/v1alpha1
kind: Kibana
metadata:
  name: test-dev
  namespace: elastic-cloud
spec:
  version: 7.2.0
  nodeCount: 2
  http:
    service:
      type: NodePort
    tls:
      selfSignedCertificate:
        disabled: true
  elasticsearchRef:
    name: test-dev
EOF
```

**Comment by thbkrkr** [comment]
Hi Dan,

Your YAML manifest is missing a `spec` field after the `service` field.

It's:

```
spec:
  http:                  
    service:
      spec:
        type: NodePort
```

instead of:

```
spec:
  http:                  
    service:
      type: NodePort
```
