### ISSUE TITLE
Set default resource limits for ES/Kibana/APM

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#1454]
Currently, we:

* don't set any default resources for APM & Kibana (no JVM, not stateful)
* set a default memory requests for Elasticsearch (2GB to match the 1GB default Elasticsearch JVM heap size) if the user does not provide resources deafults or limits in the Elasticsearch

With no default limits, the Elasticsearch pod can be evicted from a k8s host if the host is out of memory. For stateful workloads such as Elasticsearch, this can be pretty bad.

We discussed 2 approaches to solve this:

## 1. Set default memory requests AND default memory limits

Just enforce 2GB memory (requests and limits) for the ES pod. We already do this for requests, so that's just also adding it for limits.

## 2. Remove any default and encourage the user to set one

We would remove our default memory request, and ask the user to provide one. Probably changing our quickstart example from:

```
cat <<EOF | kubectl apply -f -
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.2.0
  nodes:
  - nodeCount: 1
    config:
      node.master: true
      node.data: true
      node.ingest: true
EOF
```

to: 

```
cat <<EOF | kubectl apply -f -
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.2.0
  nodes:
  - nodeCount: 1
    config:
      node.master: true
      node.data: true
      node.ingest: true
     podTemplate:
       spec:
         containers:
         - name: elasticsearch
           env:
           - name: ES_JAVA_OPTS
             value: -Xms1g -Xmx1g
           resources:
             requests:
               memory: 2Gi
             limits:
               memory: 2Gi
EOF
```

**Comment by sebgl** [comment]
I would be in favor of option 1.
Option 2 makes it more explicit to the user that these should be overridden (since users probably don't read the doc), but feels much more verbose for a quickstart.

**Comment by thbkrkr** [comment]
Related to #236, #815, #819, #1097 and #1029.

**Comment by anyasabo** [comment]
I don't think if we expand the quickstart example, we would also need to remove the default requests (or limits). Personally I think I'm okay with both.

As far as I know, the only performance downside of adding a default limit is that the pod will not be able to use >2Gi for the cache. But that's a relatively small downside and I am okay with it.

Another downside: other resources that use pod templates (e.g. deployments, ssets) just create pods and don't set defaults, so you just end up with regular pod defaults. So this is a little bit of a departure from "normal" behavior for types that create pods. That said, we know a little bit more about our use case here than those more generic types, so I think it is justified.

But just to spell out the upside of a default limit:
Having the request == limits means it will run as a Guaranteed QoS and should be in the last group of pods to be evicted in the event of resource pressure.


For expanding the quickstart example, I think starting people closer to a "Production" configuration outweighs the extra verbosity. If people want to change it in the future, they don't need to come back to our documentation to look up how to set resource requests, they can just `kubectl edit elasticsearch quickstart` and be done. But having a default limit also gets a lot of the same benefit, so I don't feel too strongly. Curious what other people's thoughts are.

**Comment by barkbay** [comment]
The main concern I have with adding some default behind the scene is that it could break the user experience when there are some Limit Ranges applied in the cluster _(must confess here that maybe I'm more sensitive to that because I have used them to manage some projects in my previous shop)_

tbh I think that applying an empty `limits` as workaround is a little bit odd:

 ```yaml
podTemplate:
  spec:
    containers:
    - name: elasticsearch
      resources:
        limits: {}
```

I don't think that expanding the quickstart example is really that bad and I agree with @anyasabo that it's closer to a "Production" configuration, it is a "quick start" and a "good start" 😄 

What should be improved imho is that the user should not have to manage the memory settings in 2 different places, `Xmx` could be calculated automatically, see https://github.com/elastic/cloud-on-k8s/pull/1029#pullrequestreview-247393459
It would save 3 lines :)

So I would vote for 2 but in the mean time check if the Docker image could be improved to automatically adjust the JVM settings depending on the control groups applied to the container.

**Comment by pebrc** [comment]
We decided to go with option 2 for now.

**Comment by sebgl** [comment]
I'm wondering if it could be worth adding an optional extra field to the ES CRD. See `memory` below:

```
cat <<EOF | kubectl apply -f -
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.2.0
  nodes:
  - name:  master-nodes
    memory: 2Gi
    nodeCount: 3
  - name:  data-nodes
    memory: 32Gi
    nodeCount: 3
EOF
```

Behaviour:
- If memory is set (>0), ECK will set resources limits and resources requests to that value, and JVM heap size to half that value.
- If not set (=0), ECK does nothing.
- podTemplate can still be used to further tweak memory settings.
- If both podTemplate memory values and `memory` are set, one gets the priority over the other (priority to `memory` is probably simpler?).

Benefits:
- Less verbose approach
- Does not require getting into/understanding podTemplate stuff
- Sets sane pod resource vs. JVM heap size ratio

Concerns:
- An extra field in the CRD
- Possible conflicting values with the podTemplate
- Should we do the same for Kibana and APM?

Note this does not prevent to move forward with Option 2 above as a first step.
