### ISSUE TITLE
Support Regional clusters

### ISSUE THREAD

**Issue by nicholasklem** [elastic/cloud-on-k8s#1462]
We use regional Kubernetes clusters 1.13.7-gke.8 on GCE. Regional clusters do not work for this operator, as one of the disks are created in a zone and not moved around as it should.

A scheduled ES pod requires 2 disks:
```
Containers:
  elasticsearch:
    Image:       docker.elastic.co/elasticsearch/elasticsearch:7.2.0
...
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  es-logs-es-jbdllnfvnp-data
    ReadOnly:   false
...
  elasticsearch-data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  es-logs-es-jbdllnfvnp-elasticsearch-data
    ReadOnly:   false
...
```

90% of creation times the operator fails to create the pod, and it ends in a `Pending` state

```
Events:
  Type     Reason             Age                    From                Message
  ----     ------             ----                   ----                -------
  Warning  FailedScheduling   4m45s (x139 over 83m)  default-scheduler   0/5 nodes are available: 1 Insufficient cpu, 4 node(s) had volume node affinity conflict.
  Normal   NotTriggerScaleUp  22s (x3319 over 10h)   cluster-autoscaler  pod didn't trigger scale-up (it wouldn't fit if a new node is added): 3 node(s) had volume node affinity conflict
```

elasticsearch.yaml says "use regionalssd":
```
...
    volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        storageClassName: regionalssd # can be any available storage class
```
But this spec is only used for one pvc:
```
es-logs-es-jbdllnfvnp-data                 Bound    pvc-eb0b68ee-b4a1-11e9-a5f9-42010a840142   20Gi       RWO            regionalssd    10h
es-logs-es-jbdllnfvnp-elasticsearch-data   Bound    pvc-eb0d337d-b4a1-11e9-a5f9-42010a840142   1Gi        RWO            standard       10h
```
and this pv ends up in a specific zone. On pod deletion this pv is not deleted.

```
$ kubectl describe pv pvc-60481df4-b488-11e9-a5f9-42010a840142 
Name:              pvc-60481df4-b488-11e9-a5f9-42010a840142
Labels:            failure-domain.beta.kubernetes.io/region=europe-west1
                   failure-domain.beta.kubernetes.io/zone=europe-west1-b
Annotations:       kubernetes.io/createdby: gce-pd-dynamic-provisioner
                   pv.kubernetes.io/bound-by-controller: yes
                   pv.kubernetes.io/provisioned-by: kubernetes.io/gce-pd
Finalizers:        [kubernetes.io/pv-protection]
StorageClass:      standard
Status:            Bound
Claim:             ops/es-logs-es-frnsvjc64l-elasticsearch-data
Reclaim Policy:    Delete
Access Modes:      RWO
VolumeMode:        Filesystem
Capacity:          1Gi
Node Affinity:     
  Required Terms:  
    Term 0:        failure-domain.beta.kubernetes.io/region in [europe-west1]
                   failure-domain.beta.kubernetes.io/zone in [europe-west1-b]
Message:           
Source:
    Type:       GCEPersistentDisk (a Persistent Disk resource in Google Compute Engine)
    PDName:     gke-kubernetes03-eu-w1-pvc-60481df4-b488-11e9-a5f9-42010a840142
    FSType:     ext4
    Partition:  0
    ReadOnly:   false
Events:         <none>
```

For now, I'm creating a zonal cluster for elastic-operator, but we would like to use regional clusters for resilience.

**Comment by barkbay** [comment]
Hi,

By default it's only require 1 volume.
Could you set the `name` attribute in the metadata of the `volumeClaimTemplates` to `elasticsearch-data` ?

```yaml
   [...]
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
   [...]
```
