### ISSUE TITLE
reconcile error, data/cluster destroyed, reformed as new

### ISSUE THREAD

**Issue by donbowman** [elastic/cloud-on-k8s#1466]
I have (had) a 3-node elastic cluster. (0.9.0, 7.2.0). It was installed as below.
After some hours (24 or so) of running, it lost all the data (and the added users) and reformed.
The status is now green, but ...

the pods did not show restart (all 33h).
the pvc were still up.

my data is gone, my cluster shows green, but its a new cluster as far as I can tell.

the cluster was 3 -nodes, consuming a modest amount of logging data [~10 rows/s].
the nodes have a fair bit of capacity left:
```
$ kubectl top node
NAME                                     CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
gke-noc-noc-preempt-pool-356e72e3-q9cn   1399m        17%    18388Mi         69%       
gke-noc-noc-preempt-pool-9df19f3b-tgkf   1125m        14%    9918Mi          37%       
gke-noc-noc-preempt-pool-bc2cfcf6-3fdx   1250m        15%    10018Mi         37%       
```

the init-container from my operator def did not run (so i have no prometheus scrapes for this post this time).

The 1 restart below is me diagnosing this, they were all 0.

```
kubectl -n elasticsearch get pods
NAME                    READY   STATUS    RESTARTS   AGE
elastic-es-5llmsjnwjg   1/1     Running   0          34h
elastic-es-8zhgf59v47   1/1     Running   1          34h
elastic-es-b6l2znbnc9   1/1     Running   0          34h
```

I will attach the error message from the operator as its a bit long, but the top line when it happened shows:

[elastic-es-5llmsjnwjg.log](https://github.com/elastic/cloud-on-k8s/files/3461379/elastic-es-5llmsjnwjg.log)
[elastic-es-5llmsjnwjg-describe.log](https://github.com/elastic/cloud-on-k8s/files/3461382/elastic-es-5llmsjnwjg-describe.log)

```
{"level":"error","ts":1564716220.952083,"logger":"kubebuilder.controller","msg":"Reconciler error","controller":"elasticsearch-controller","request":"elasticsearch/elastic","error":"unable to delete /_cluster/voting_config_exclusions: Delete https://elastic-es.elasticsearch.svc.cluster.local:9200/_cluster/voting_config_exclusions?wait_for_removal=false: dial tcp 10.27.245.81:9200: connect: connection timed out","errorCauses":[{"error":"unable to delete /_cluster/voting_config_exclusions: Delete https://elastic-es.elasticsearch.svc.cluster.local:9200/_cluster/voting_config_exclusions?wait_for_removal=false: dial tcp 10.27.245.81:9200: connect: connection timed out","errorVerbose":"Delete https://elastic-es.elasticsearch.svc.cluster.local:9200/_cluster/voting_config_exclusions?wait_for_removal=false: dial tcp 10.27.245.81:9200: connect: connection timed out\nunable to delete /_cluster/voting_c
[operator.log](https://github.com/elastic/cloud-on-k8s/files/3461373/operator.log)
```

It seems to have consumed a bunch of memory and been OOM. I'm not 100% sure this lines up in time.
```
  Warning  OOMKilling  32m   kernel-monitor, gke-noc-noc-preempt-pool-356e72e3-q9cn  Memory cgroup out of memory: Kill process 19346 (java) score 1588 or sacrifice child
Killed process 19564 (controller) total-vm:68780kB, anon-rss:688kB, file-rss:7968kB, shmem-rss:0kB
  Warning  OOMKilling  32m  kernel-monitor, gke-noc-noc-preempt-pool-356e72e3-q9cn  Memory cgroup out of memory: Kill process 19346 (java) score 1588 or sacrifice child
Killed process 19346 (java) total-vm:6560748kB, anon-rss:1345000kB, file-rss:27984kB, shmem-rss:0kB
  Warning  OOMKilling  13m  kernel-monitor, gke-noc-noc-preempt-pool-356e72e3-q9cn  Memory cgroup out of memory: Kill process 679351 (java) score 2003 or sacrifice child
Killed process 679351 (java) total-vm:9991520kB, anon-rss:599520kB, file-rss:19168kB, shmem-rss:0kB
```

```
---
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: elastic
  namespace: elasticsearch
spec:
  version: 7.2.0
  nodes:
    - nodeCount: 3
      config:
        node.master: true
        node.data: true
        node.ingest: true
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
      podTemplate:
        metadata:
          annotations:
            fluentbit.io/exclude: "true"
        spec:
          initContainers:
            - name: install-plugins
              command:
                - sh
                - -c
                - |
                  bin/elasticsearch-plugin install \
                   -b https://github.com/vvanholl/elasticsearch-prometheus-exporter/releases/download/7.2.0.0/prometheus-exporter-7.2.0.0.zip
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 80
                  podAffinityTerm:
                    labelSelector:
                      matchLabels:
                        elasticsearch.k8s.elastic.co/cluster-name: logs
                    topologyKey: kubernetes.io/hostname
```
```
operator is 0.9.0 all-in-one.yaml.

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:18:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-gke.8", GitCommit:"7d3d6f113e933ed1b44b78dff4baf649258415e5", GitTreeState:"clean", BuildDate:"2019-06-19T16:37:16Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}
