### ISSUE TITLE
Can't add data nodes

### ISSUE THREAD

**Issue by devorigin** [elastic/cloud-on-k8s#1467]
## Bug Report
**What did you do?**
Load a cluster with 1 master node and 2 data nodes on kubernetes in docker for windows

**What did you expect to see?**
1 master node and 2 data nodes on the cluster

**What did you see instead? Under which circumstances?**
Only 1 master node

**Environment**

Kubernetes on docker for windows (Windows 10)

* Version information:

* Kubernetes information:

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

* Resource definition:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 6.8.0
  nodes:
  - nodeCount: 1
    config:
      node.master: true
      node.data: true
      node.ingest: true
  - podTemplate:
      spec:
        containers:
        - name: elasticsearch
          env:
        - name: ES_JAVA_OPTS
          value: -Xms256m -Xmx256m
          resources:
            requests:
              memory: 512m
            limits:
              memory: 512m              
  - nodeCount: 2
    config:
      node.master: false
      node.data: true
      node.ingest: false
  - podTemplate:
      spec:
        containers:
        - name: elasticsearchdata
          env:
        - name: ES_JAVA_OPTS
          value: -Xms256m -Xmx256m
          resources:
            requests:
              memory: 512m
            limits:
              memory: 512m              
              
  http:
    service:
      spec:
        type: LoadBalancer
```

* Logs:

{"level":"info","ts":1564750996.897782,"logger":"transport","msg":"Skipping pod because it has no IP yet","namespace":"default","pod_name":"quickstart-es-v9xhgd9zjd"}
{"level":"info","ts":1564750997.6961637,"logger":"driver","msg":"Calculated all required changes","to_create:":0,"to_keep:":3,"to_delete:":1,"namespace":"default","es_name":"quickstart"}
{"level":"info","ts":1564750997.6967852,"logger":"driver","msg":"Calculated performable changes","schedule_for_creation_count":0,"schedule_for_deletion_count":0,"namespace":"default","es_name":"quickstart"}
{"level":"info","ts":1564750997.7631907,"logger":"elasticsearch-controller","msg":"Updating status","iteration":37,"namespace":"default","es_name":"quickstart"}
{"level":"info","ts":1564750997.763259,"logger":"generic-reconciler","msg":"Aggregated reconciliation results complete","result":{"Requeue":true,"RequeueAfter":10000000000}}
{"level":"info","ts":1564750997.7633328,"logger":"elasticsearch-controller","msg":"End reconcile iteration","iteration":37,"took":0.9070695,"namespace":"default","es_ame":"quickstart"}
{"level":"info","ts":1564751007.7642858,"logger":"elasticsearch-controller","msg":"Start reconcile iteration","iteration":38,"namespace":"default","es_name":"quickstart"}
{"level":"info","ts":1564751007.7874932,"logger":"generic-reconciler","msg":"Updating resource","kind":"Service","namespace":"default","name":"quickstart-es-http"}
{"level":"info","ts":1564751007.8136356,"logger":"transport","msg":"Reconciling transport certificate secrets","namespace":"default","es_name":"quickstart"}
{"level":"info","ts":1564751007.8138783,"logger":"transport","msg":"Skipping pod because it has no IP yet","namespace":"default","pod_name":"quickstart-es-5lffmw9sp5"}
{"level":"info","ts":1564751007.8139987,"logger":"transport","msg":"Skipping pod because it has no IP yet","namespace":"default","pod_name":"quickstart-es-nk855cmx79"}
{"level":"info","ts":1564751007.8151925,"logger":"transport","msg":"Skipping pod because it has no IP yet","namespace":"default","pod_name":"quickstart-es-v9xhgd9zjd"}
{"level":"info","ts":1564751008.6138775,"logger":"driver","msg":"Calculated all required changes","to_create:":0,"to_keep:":3,"to_delete:":1,"namespace":"default","es_name":"quickstart"}
{"level":"info","ts":1564751008.6140182,"logger":"driver","msg":"Calculated performable changes","schedule_for_creation_count":0,"schedule_for_deletion_count":0,"namespace":"default","es_name":"quickstart"}
{"level":"info","ts":1564751008.646924,"logger":"elasticsearch-controller","msg":"Updating status","iteration":38,"namespace":"default","es_name":"quickstart"}
{"level":"info","ts":1564751008.6472511,"logger":"generic-reconciler","msg":"Aggregated reconciliation results complete","result":{"Requeue":true,"RequeueAfter":10000000000}}
{"level":"info","ts":1564751008.649292,"logger":"elasticsearch-controller","msg":"End reconcile iteration","iteration":38,"took":0.8850144,"namespace":"default","es_ame":"quickstart"}
{"level":"info","ts":1564751018.6520898,"logger":"elasticsearch-controller","msg":"Start reconcile iteration","iteration":39,"namespace":"default","es_name":"quickstart"}
{"level":"info","ts":1564751018.6531932,"logger":"generic-reconciler","msg":"Updating resource","kind":"Service","namespace":"default","name":"quickstart-es-http"}
{"level":"info","ts":1564751018.6734586,"logger":"transport","msg":"Reconciling transport certificate secrets","namespace":"default","es_name":"quickstart"}
{"level":"info","ts":1564751018.6742823,"logger":"transport","msg":"Skipping pod because it has no IP yet","namespace":"default","pod_name":"quickstart-es-5lffmw9sp5"}
{"level":"info","ts":1564751018.6744266,"logger":"transport","msg":"Skipping pod because it has no IP yet","namespace":"default","pod_name":"quickstart-es-nk855cmx79"}
{"level":"info","ts":1564751018.6744645,"logger":"transport","msg":"Skipping pod because it has no IP yet","namespace":"default","pod_name":"quickstart-es-v9xhgd9zjd"}
{"level":"info","ts":1564751019.468436,"logger":"driver","msg":"Calculated all required changes","to_create:":0,"to_keep:":3,"to_delete:":1,"namespace":"default","es_name":"quickstart"}
{"level":"info","ts":1564751019.4685724,"logger":"driver","msg":"Calculated performable changes","schedule_for_creation_count":0,"schedule_for_deletion_count":0,"namespace":"default","es_name":"quickstart"}
{"level":"info","ts":1564751019.5103126,"logger":"elasticsearch-controller","msg":"Updating status","iteration":39,"namespace":"default","es_name":"quickstart"}
{"level":"info","ts":1564751019.510394,"logger":"generic-reconciler","msg":"Aggregated reconciliation results complete","result":{"Requeue":true,"RequeueAfter":10000000000}}
{"level":"info","ts":1564751019.51043,"logger":"elasticsearch-controller","msg":"End reconcile iteration","iteration":39,"took":0.8583425,"namespace":"default","es_ame":"quickstart"}

**Comment by thbkrkr** [comment]
Hello,

I tested your resource definition and it works for me.

```bash
> kubectl get pods
NAME                       READY   STATUS    RESTARTS   AGE
quickstart-es-fxfmq64n2q   1/1     Running   0          1m15s
quickstart-es-ghsstvs2sv   1/1     Running   0          1m15s
quickstart-es-jg5cqmtw87   1/1     Running   0          1m15s
```
What's the output of `kubectl get pods` for you?

Requesting `_cat/nodes` indicates the presence of 3 nodes with 1 master node and 3 data nodes.
```bash
> curl -ku $auth https://$ip:9200/_cat/nodes 
10.56.2.90 12 29 5 0.06 0.14 0.11 d   - quickstart-es-fxfmq64n2q
10.56.0.73 16 46 5 0.10 0.17 0.12 mdi * quickstart-es-ghsstvs2sv
10.56.1.42 10 51 5 0.12 0.23 0.13 d   - quickstart-es-jg5cqmtw87
```

Moreover, your `podTemplate` is not taken in account because it's badly declared. It's not an array. This [example](https://github.com/elastic/cloud-on-k8s/blob/master/operators/config/samples/elasticsearch/elasticsearch.yaml#L16) can help. 
Please also look at this [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/heap-size.html), it is not recommended to start Elasticsearch with less than 1GB.

**Comment by devorigin** [comment]
Hi, first  I try to add 1 data node, then 2 data nodes, that why you see 3 pods pendind

NAME                       READY   STATUS    RESTARTS   AGE
quickstart-es-5lffmw9sp5   0/1     Pending   0          16h
quickstart-es-nk855cmx79   0/1     Pending   0          99m
quickstart-es-v9xhgd9zjd   0/1     Pending   0          99m
quickstart-es-zxf2h8xdcs   1/1     Running   0          16h

**Comment by devorigin** [comment]
I try with this 

apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
spec:
  version: 6.8.0
  nodes:
  - config:
      # most Elasticsearch configuration parameters are possible to set, e.g:
      node.attr.attr_name: attr_value
      node.master: true
      node.data: true
      node.ingest: true
      node.ml: true
    podTemplate:
      metadata:
        labels:
          # additional labels for pods
          foo: bar
      spec:
        containers:
        - name: elasticsearch
          # specify resource limits and requests
          resources:
            limits:
              memory: 1Gi
              cpu: 1
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms512m -Xmx512m"
    nodeCount: 2


and the log has the same error "Skipping pod because it has no IP yet"

{"level":"info","ts":1564775240.7527163,"logger":"driver","msg":"Calculated all required changes","to_create:":0,"to_keep:":2,"to_delete:":0,"namespace":"default","es_name":"elasticsearch-sample"}
{"level":"info","ts":1564775240.7528787,"logger":"driver","msg":"Calculated performable changes","schedule_for_creation_count":0,"schedule_for_deletion_count":0,"namespace":"default","es_name":"elasticsearch-sample"}
{"level":"info","ts":1564775240.7553704,"logger":"driver","msg":"ES external service not ready yet for shard migration reconciliation. Requeuing.","namespace":"default","es_name":"elasticsearch-sample"}
{"level":"info","ts":1564775240.755429,"logger":"elasticsearch-controller","msg":"Updating status","iteration":1574,"namespace":"default","es_name":"elasticsearch-sample"}
{"level":"info","ts":1564775240.755457,"logger":"generic-reconciler","msg":"Aggregated reconciliation results complete","result":{"Requeue":true,"RequeueAfter":10000000000}}
{"level":"info","ts":1564775240.7554839,"logger":"elasticsearch-controller","msg":"End reconcile iteration","iteration":1574,"took":0.9037487,"namespace":"default","es_ame":"elasticsearch-sample"}
{"level":"info","ts":1564775250.756325,"logger":"elasticsearch-controller","msg":"Start reconcile iteration","iteration":1575,"namespace":"default","es_name":"elasticsearch-sample"}
{"level":"info","ts":1564775250.8019464,"logger":"transport","msg":"Reconciling transport certificate secrets","namespace":"default","es_name":"elasticsearch-sample"}
{"level":"info","ts":1564775250.812447,"logger":"transport","msg":"Skipping pod because it has no IP yet","namespace":"default","pod_name":"elasticsearch-sample-es-9m7p65jzv9"}
{"level":"info","ts":1564775251.6179729,"logger":"driver","msg":"Calculated all required changes","to_create:":0,"to_keep:":2,"to_delete:":0,"namespace":"default","es_name":"elasticsearch-sample"}
{"level":"info","ts":1564775251.6181276,"logger":"driver","msg":"Calculated performable changes","schedule_for_creation_count":0,"schedule_for_deletion_count":0,"namespace":"default","es_name":"elasticsearch-sample"}
{"level":"info","ts":1564775251.6266034,"logger":"driver","msg":"ES external service not ready yet for shard migration reconciliation. Requeuing.","namespace":"default","es_name":"elasticsearch-sample"}
{"level":"info","ts":1564775251.6267157,"logger":"elasticsearch-controller","msg":"Updating status","iteration":1575,"namespace":"default","es_name":"elasticsearch-sample"}
{"level":"info","ts":1564775251.6267498,"logger":"generic-reconciler","msg":"Aggregated reconciliation results complete","result":{"Requeue":true,"RequeueAfter":10000000000}}
{"level":"info","ts":1564775251.6267867,"logger":"elasticsearch-controller","msg":"End reconcile iteration","iteration":1575,"took":0.870471,"namespace":"default","es_ame":"elasticsearch-sample"}

**Comment by anyasabo** [comment]
Hey @devorigin, in this case it might be more informative to `kubectl describe` the pods or look at the logs of the pods. Since they're failing to come up successfully that might provide more information. This doc also has more detail on troubleshooting steps:
https://github.com/elastic/cloud-on-k8s/blob/master/docs/troubleshooting.asciidoc

**Comment by adasari** [comment]
@anyasabo - can you please point me to the sample elastic yaml or doc to create es cluster with different number of master, client and data nodes ? thanks.

**Comment by adasari** [comment]
@andrershov - i used following 
```
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.2.0
  nodes:
  - nodeCount: 1
    config:
      node.master: true
      node.data: false
      node.ingest: true
    podTemplate:
      metadata:
        labels:
          # additional labels for pods
          foo: bar
      spec:
        containers:
        - name: elasticsearch
          # specify resource limits and requests
          resources:
            limits:
              memory: 1Gi
              cpu: 1
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms256m -Xmx256m"
  - nodeCount: 1
    config:
      node.master: false
      node.data: true
      node.ingest: false
    podTemplate:
      metadata:
        labels:
          # additional labels for pods
          foo: bar
      spec:
        containers:
        - name: elasticsearch
          # specify resource limits and requests
          resources:
            limits:
              memory: 1Gi
              cpu: 1
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms512m -Xmx512m"
```

pod describe says -
```
Events:
  Type     Reason            Age                    From               Message
  ----     ------            ----                   ----               -------
  Warning  FailedScheduling  2m43s (x2 over 2m45s)  default-scheduler  pod has unbound immediate PersistentVolumeClaims
  Normal   Scheduled         2m41s                  default-scheduler  Successfully assigned default/quickstart-es-n5fxp9t95t to minikube
  Normal   Pulled            2m40s                  kubelet, minikube  Container image "docker.elastic.co/elasticsearch/elasticsearch:7.2.0" already present on machine
  Normal   Created           2m40s                  kubelet, minikube  Created container elastic-internal-init-os-settings
  Normal   Started           2m40s                  kubelet, minikube  Started container elastic-internal-init-os-settings
  Normal   Pulled            2m38s                  kubelet, minikube  Container image "docker.elastic.co/elasticsearch/elasticsearch:7.2.0" already present on machine
  Normal   Created           2m38s                  kubelet, minikube  Created container elastic-internal-init-filesystem
  Normal   Started           2m38s                  kubelet, minikube  Started container elastic-internal-init-filesystem
  Normal   Pulled            2m37s                  kubelet, minikube  Container image "docker.elastic.co/elasticsearch/elasticsearch:7.2.0" already present on machine
  Normal   Created           2m37s                  kubelet, minikube  Created container elasticsearch
  Normal   Started           2m37s                  kubelet, minikube  Started container elasticsearch
  Warning  Unhealthy         2m3s (x5 over 2m23s)   kubelet, minikube  Readiness probe failed:
```
where can i find the readiness probe details ? 
and 
is node.ingest a client node ?
