### ISSUE TITLE
Should we rename nodes in Elasticsearch spec

### ISSUE THREAD

**Issue by david-kow** [elastic/cloud-on-k8s#1488]
This came up in a [comment](https://github.com/elastic/cloud-on-k8s/pull/1463#discussion_r310187518) for #1463. 

I got a feeling that current name ("nodes") implies that it holds a list of nodes, but that's not accurate and might be misleading. It does hold a list, but each item describes a set of identical es nodes and holds:
- name for the set,
- es config to use for all nodes in the set,
- number of nodes in the set,
- pod template to use for all nodes in the set,
- volume claim templates to use for all nodes in the set.

I don't have full context as this was before my time, but seems like this field was renamed already from topologies to topology and then to nodes. 

Alternatives that came up: nodeGroups, nodeSets, nodeSpecs, nodeTemplates.

I don't really feel strongly about this, but we decided to ask broader, hence calling @agup006 @jordansissel @Crazybus @zanbel @uric.

**Comment by david-kow** [comment]
Since there is no feedback so far, I will wait a little more and close this on Monday concluding that we don't want to rename.

**Comment by sebgl** [comment]
Just to give examples for people looking at this issue.

This is what we currently have:

```yaml
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
spec:
  version: 7.2.0
  nodes:
  - name: masters
    nodeCount: 3
  - name: data-hot
    nodeCount: 3
  - name: data-warm
    nodeCount: 3
```

We are wondering whether `nodes` (and also `name` and `nodeCount`) are the right names here.
Example of what could be possible instead:

```yaml
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
spec:
  version: 7.2.0
  nodeSpecs: # nodeSets, nodeTemplates, nodeGroups, etc.
  - name: masters
    count: 3  # nodeCount, replicas, etc.
  - name: data-hot
    count: 3
  - name: data-warm
    count: 3
```
