### ISSUE TITLE
Disable elastic user ?

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#1527]
Should we create an option to disable the elastic user in case authentication happens through an external realm like SAML?

**Comment by thbkrkr** [comment]
Duplicates of #7719, resolved by #7723.

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
spec:
  auth:
    disableElasticUser: true # ➡️ NEW field to disable elastic user
```
