### ISSUE TITLE
Is there a way to disable default enable TLS and authentication?

### ISSUE THREAD

**Issue by eroji** [elastic/cloud-on-k8s#1539]
I am using the elastic cloud operator 0.9 and deploying a 3 node elasticsearch cluster in k8s. For my usecase, I want to be able to disable TLS and authentication and allow for API access via http and port 9200. Is this possible?

```
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: test
spec:
  version: 7.2.0
  nodes:
  - nodeCount: 3
    config:
      node.master: true
      node.data: true
      node.ingest: true
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
        storageClassName: rook-ceph-block
```
