### ISSUE TITLE
Allow ECK to specify a custom readiness check for Elasticsearch and Kibana

### ISSUE THREAD

**Issue by mikeh-elastic** [elastic/cloud-on-k8s#1581]
It will be helpful to be able to specify a custom readiness check in certain cases such as Centos and RHEL 7 3.10 kernel with kmem accounting to avoid pod improperly being accounted for memory consumption repeatedly by curl against an https endpoint.

Disabling curl at this time is the workaround to avoid the pod being killed, and once an alternative is identified it will be beneficial to be able to specify the alternative.

**Comment by pebrc** [comment]
You can do this today by specifying your own readiness probe via the pod template:
```yaml
spec:
   nodes:
   - podTemplate:
        containers:
        - name: elasticsearch 
           readinessProbe: 
            ...
```

**Comment by jordansissel** [comment]
If you enjoy using yaml anchors, you can reduce the number of times you specify readinessProbe by using yaml anchors and references:

```
spec:
   nodes:
   - count: 6
     podTemplate: &custom
        containers:
        - name: elasticsearch 
          readinessProbe:
            ...
  - count: 3
     podTemplate: *custom
```

This uses yaml anchors to tell the yaml parser that the 2nd podTemplate entry should have its value come from the first podTemplate (an anchor named `custom`)
