### ISSUE TITLE
kibana cannot connect to es using purchased cert

### ISSUE THREAD

**Issue by skame** [elastic/cloud-on-k8s#1583]
## Bug Report
**What did you do?**

Using purchased certificate for elasticsearch and set it to spec.http.tls.certificate.secretName.

**What did you expect to see?**

kibana can connect elasticsearch clustrer.

**What did you see instead? Under which circumstances?**

I could connect to elasticsearch but kibana couldn't.

**Environment**

* Version information:

7.2.0

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* On premise 

* Logs:
```
{"type":"log","@timestamp":"2019-08-16T00:35:36Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: https://example-es-http.elastic.svc:9200/"}
{"type":"log","@timestamp":"2019-08-16T00:35:36Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
{"type":"log","@timestamp":"2019-08-16T00:35:36Z","tags":["warning","task_manager"],"pid":1,"message":"PollError No Living connections"}
```
exec kibana
```
$ curl "https://elastic:password@es7.example.jp:30855/_cluster/health?pretty=true"
{
  "cluster_name" : "dsl",
  "status" : "green",
  "timed_out" : false,
  "number_of_nodes" : 9,
  "number_of_data_nodes" : 3,
  "active_primary_shards" : 106,
  "active_shards" : 212,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 0,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 0,
  "active_shards_percent_as_number" : 100.0
}
$ curl "https://elastic:password@example-es-http.elastic.svc:9200/_cluster/health?pretty=true"
curl: (51) Unable to communicate securely with peer: requested domain name does not match the server's certificate.
```

* Configs:
```
:
kind: Elasticsearch
  http:
    service:
      spec:
        type: NodePort
    tls:
      certificate:
        secretName: my-cert
```

```
apiVersion: kibana.k8s.elastic.co/v1alpha1
kind: Kibana
metadata:
  namespace: elastic
  name: dsl
spec:
  version: 7.2.0
  nodeCount: 1
  elasticsearchRef:
    name: example
  http:
    tls:
      selfSignedCertificate:
        disabled: true
```

I also try this setting, but same error occured.
```
apiVersion: kibana.k8s.elastic.co/v1alpha1
kind: Kibana
metadata:
  namespace: elastic
  name: dsl
spec:
  version: 7.2.0
 elasticsearch:
   url: https://es7.example.jp:30855
   auth:
     secret:
       name: example-es-elastic-user
       key: elastic
   certificateAuthorities:
     secretName: my-cert
  nodeCount: 1
  http:
    tls:
      selfSignedCertificate:
        disabled: true
```

**Comment by david-kow** [comment]
I investigated more and I need to retrack some of the things above. The reason it works for the self-signed cert is that it is its own CA. In your case Kibana is not able to verify the cert because we override its CAs, so it no longer knows about public ones.

The proper fix is on the operator side and is tracked under #1614.

To unblock yourself, you can include your CA cert in ca.crt key in `my-cert` secret. This will make Kibana use it as CA.

**Comment by skame** [comment]
Thank you for your investigation.

I can connect to my elasticsearch cluster w/ following setting on kibana.

```
apiVersion: kibana.k8s.elastic.co/v1alpha1
kind: Kibana
spec:
  version: 7.2.0
  config:
    elasticsearch.ssl.certificateAuthorities: /etc/ssl/certs/ca-bundle.crt
```
