### ISSUE TITLE
master not discovered yet: have discovered ... (reconciling stuck)

### ISSUE THREAD

**Issue by abh** [elastic/cloud-on-k8s#1590]
## Bug Report
**What did you do?**

Changed the cluster CRD changing the resource limits.

**What did you expect to see?**

Cluster restarted.

**What did you see instead? Under which circumstances?**

One data node was added, but the reconciliation never finished. Log entry below.

**Environment**

* Version information:

	0.9.0

* Kubernetes information:

	* On premise, v1.14.5
	* Kubernetes distribution: Rancher, 2.2.7

* Resource definition:
```
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: logging
  namespace: logging
spec:
  version: 7.3.0
  setVmMaxMapCount: false

  nodes:
  - name: ingest
    nodeCount: 2
    config:
      node.ingest: true
      node.master: false
      node.data: false
      path.repo: /var/backup
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: 5Gi
              cpu: 1
            requests:
              memory: 3Gi
              cpu: 100m
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms2g -Xmx2g"
          volumeMounts:
          - name: backup
            mountPath: /var/backup
        volumes:
        - name: backup
          flexVolume:
            driver: rook.io/rook
            fsType: ceph
            options:
              fsName: cephfs
              clusterName: rook-ceph
              path: /elastic/backup

    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 512Mi

  - name: data
    nodeCount: 4
    config:
      node.data: true
      node.master: false
      node.ingest: false
      path.repo: /var/backup
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: 10Gi
              cpu: 2
            requests:
              memory: 5Gi
              cpu: 500m
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms4g -Xmx4g"
          volumeMounts:
          - name: backup
            mountPath: /var/backup
        volumes:
        - name: backup
          flexVolume:
            driver: rook.io/rook
            fsType: ceph
            options:
              fsName: cephfs
              clusterName: rook-ceph
              path: /elastic/backup

    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 25Gi

  - name: master
    nodeCount: 3
    config:
      node.master: true
      node.data: false
      node.ingest: false
      path.repo: /var/backup
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: 3Gi
              cpu: 1
            requests:
              memory: 1Gi
              cpu: 100m
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms512m -Xmx512m"
          volumeMounts:
          - name: backup
            mountPath: /var/backup
        volumes:
        - name: backup
          flexVolume:
            driver: rook.io/rook
            fsType: ceph
            options:
              fsName: cephfs
              clusterName: rook-ceph
              path: /elastic/backup

    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 768Mi
```

* Logs:
```
{
  "level": "info",
  "ts": 1566183172.7006643,
  "logger": "elasticsearch-controller",
  "msg": "End reconcile iteration",
  "iteration": 413,
  "took": 1.714528446,
  "namespace": "logging",
  "es_ame": "logging"
}
{
  "level": "info",
  "ts": 1566183182.7009592,
  "logger": "elasticsearch-controller",
  "msg": "Start reconcile iteration",
  "iteration": 414,
  "namespace": "logging",
  "es_name": "logging"
}
{
  "level": "info",
  "ts": 1566183182.706418,
  "logger": "transport",
  "msg": "Reconciling transport certificate secrets",
  "namespace": "logging",
  "es_name": "logging"
}
{
  "level": "info",
  "ts": 1566183184.3044643,
  "logger": "driver",
  "msg": "Calculated all required changes",
  "to_create:": 9,
  "to_keep:": 0,
  "to_delete:": 10,
  "namespace": "logging",
  "es_name": "logging"
}
{
  "level": "info",
  "ts": 1566183184.3047595,
  "logger": "driver",
  "msg": "Calculated performable changes",
  "schedule_for_creation_count": 0,
  "schedule_for_deletion_count": 0,
  "namespace": "logging",
  "es_name": "logging"
}
{
  "level": "info",
  "ts": 1566183184.3481183,
  "logger": "elasticsearch-controller",
  "msg": "Updating status",
  "iteration": 414,
  "namespace": "logging",
  "es_name": "logging"
}
{
  "level": "info",
  "ts": 1566183184.3482616,
  "logger": "elasticsearch-controller",
  "msg": "End reconcile iteration",
  "iteration": 414,
  "took": 1.647306677,
  "namespace": "logging",
  "es_ame": "logging"
}
{
  "level": "info",
  "ts": 1566183194.348458,
  "logger": "elasticsearch-controller",
  "msg": "Start reconcile iteration",
  "iteration": 415,
  "namespace": "logging",
  "es_name": "logging"
}
{
  "level": "info",
  "ts": 1566183194.3540235,
  "logger": "transport",
  "msg": "Reconciling transport certificate secrets",
  "namespace": "logging",
  "es_name": "logging"
}
{
  "level": "info",
  "ts": 1566183196.009188,
  "logger": "driver",
  "msg": "Calculated all required changes",
  "to_create:": 9,
  "to_keep:": 0,
  "to_delete:": 10,
  "namespace": "logging",
  "es_name": "logging"
}
{
  "level": "info",
  "ts": 1566183196.0094397,
  "logger": "driver",
  "msg": "Calculated performable changes",
  "schedule_for_creation_count": 0,
  "schedule_for_deletion_count": 0,
  "namespace": "logging",
  "es_name": "logging"
}
{
  "level": "info",
  "ts": 1566183196.0448194,
  "logger": "elasticsearch-controller",
  "msg": "Updating status",
  "iteration": 415,
  "namespace": "logging",
  "es_name": "logging"
}
{
  "level": "info",
  "ts": 1566183196.044998,
  "logger": "elasticsearch-controller",
  "msg": "End reconcile iteration",
  "iteration": 415,
  "took": 1.69654436,
  "namespace": "logging",
  "es_ame": "logging"
}
{
  "level": "info",
  "ts": 1566183200.2587614,
  "logger": "elasticsearch-controller",
  "msg": "Start reconcile iteration",
  "iteration": 416,
  "namespace": "logging",
  "es_name": "logging"
}
{
  "level": "info",
  "ts": 1566183200.2678277,
  "logger": "transport",
  "msg": "Reconciling transport certificate secrets",
  "namespace": "logging",
  "es_name": "logging"
}
{
  "level": "info",
  "ts": 1566183201.981543,
  "logger": "driver",
  "msg": "Calculated all required changes",
  "to_create:": 9,
  "to_keep:": 0,
  "to_delete:": 10,
  "namespace": "logging",
  "es_name": "logging"
}
{
  "level": "info",
  "ts": 1566183201.9818172,
  "logger": "driver",
  "msg": "Calculated performable changes",
  "schedule_for_creation_count": 0,
  "schedule_for_deletion_count": 0,
  "namespace": "logging",
  "es_name": "logging"
}
{
  "level": "info",
  "ts": 1566183202.0215142,
  "logger": "elasticsearch-controller",
  "msg": "Updating status",
  "iteration": 416,
  "namespace": "logging",
  "es_name": "logging"
}
{
  "level": "info",
  "ts": 1566183202.021666,
  "logger": "elasticsearch-controller",
  "msg": "End reconcile iteration",
  "iteration": 416,
  "took": 1.762907386,
  "namespace": "logging",
  "es_ame": "logging"
}
{
  "level": "info",
  "ts": 1566183206.0453088,
  "logger": "elasticsearch-controller",
  "msg": "Start reconcile iteration",
  "iteration": 417,
  "namespace": "logging",
  "es_name": "logging"
}
{
  "level": "info",
  "ts": 1566183206.0506523,
  "logger": "transport",
  "msg": "Reconciling transport certificate secrets",
  "namespace": "logging",
  "es_name": "logging"
}
{
  "level": "info",
  "ts": 1566183207.8084288,
  "logger": "driver",
  "msg": "Calculated all required changes",
  "to_create:": 9,
  "to_keep:": 0,
  "to_delete:": 10,
  "namespace": "logging",
  "es_name": "logging"
}
{
  "level": "info",
  "ts": 1566183207.8087468,
  "logger": "driver",
  "msg": "Calculated performable changes",
  "schedule_for_creation_count": 0,
  "schedule_for_deletion_count": 0,
  "namespace": "logging",
  "es_name": "logging"
}
{
  "level": "info",
  "ts": 1566183207.8431778,
  "logger": "elasticsearch-controller",
  "msg": "Updating status",
  "iteration": 417,
  "namespace": "logging",
  "es_name": "logging"
}
{
  "level": "info",
  "ts": 1566183207.8432982,
  "logger": "elasticsearch-controller",
  "msg": "End reconcile iteration",
  "iteration": 417,
  "took": 1.797992043,
  "namespace": "logging",
  "es_ame": "logging"
}
{
  "level": "info",
  "ts": 1566183217.8435738,
  "logger": "elasticsearch-controller",
  "msg": "Start reconcile iteration",
  "iteration": 418,
  "namespace": "logging",
  "es_name": "logging"
}
{
  "level": "info",
  "ts": 1566183217.8487682,
  "logger": "transport",
  "msg": "Reconciling transport certificate secrets",
  "namespace": "logging",
  "es_name": "logging"
}
{
  "level": "info",
  "ts": 1566183219.5093987,
  "logger": "driver",
  "msg": "Calculated all required changes",
  "to_create:": 9,
  "to_keep:": 0,
  "to_delete:": 10,
  "namespace": "logging",
  "es_name": "logging"
}
{
  "level": "info",
  "ts": 1566183219.5096657,
  "logger": "driver",
  "msg": "Calculated performable changes",
  "schedule_for_creation_count": 0,
  "schedule_for_deletion_count": 0,
  "namespace": "logging",
  "es_name": "logging"
}
{
  "level": "info",
  "ts": 1566183219.5438385,
  "logger": "elasticsearch-controller",
  "msg": "Updating status",
  "iteration": 418,
  "namespace": "logging",
  "es_name": "logging"
}
{
  "level": "info",
  "ts": 1566183219.5439422,
  "logger": "elasticsearch-controller",
  "msg": "End reconcile iteration",
  "iteration": 418,
  "took": 1.700373127,
  "namespace": "logging",
  "es_ame": "logging"
}
{
  "level": "info",
  "ts": 1566183229.544263,
  "logger": "elasticsearch-controller",
  "msg": "Start reconcile iteration",
  "iteration": 419,
  "namespace": "logging",
  "es_name": "logging"
}
{
  "level": "info",
  "ts": 1566183229.5498483,
  "logger": "transport",
  "msg": "Reconciling transport certificate secrets",
  "namespace": "logging",
  "es_name": "logging"
}
{
  "level": "info",
  "ts": 1566183231.322747,
  "logger": "driver",
  "msg": "Calculated all required changes",
  "to_create:": 9,
  "to_keep:": 0,
  "to_delete:": 10,
  "namespace": "logging",
  "es_name": "logging"
}
{
  "level": "info",
  "ts": 1566183231.3230681,
  "logger": "driver",
  "msg": "Calculated performable changes",
  "schedule_for_creation_count": 0,
  "schedule_for_deletion_count": 0,
  "namespace": "logging",
  "es_name": "logging"
}
{
  "level": "info",
  "ts": 1566183231.3613791,
  "logger": "elasticsearch-controller",
  "msg": "Updating status",
  "iteration": 419,
  "namespace": "logging",
  "es_name": "logging"
}
{
  "level": "info",
  "ts": 1566183231.3615656,
  "logger": "elasticsearch-controller",
  "msg": "End reconcile iteration",
  "iteration": 419,
  "took": 1.817306365,
  "namespace": "logging",
  "es_ame": "logging"
}
{
  "level": "info",
  "ts": 1566183241.3618214,
  "logger": "elasticsearch-controller",
  "msg": "Start reconcile iteration",
  "iteration": 420,
  "namespace": "logging",
  "es_name": "logging"
}
{
  "level": "info",
  "ts": 1566183241.367352,
  "logger": "transport",
  "msg": "Reconciling transport certificate secrets",
  "namespace": "logging",
  "es_name": "logging"
}
{
  "level": "info",
  "ts": 1566183242.8147466,
  "logger": "driver",
  "msg": "Calculated all required changes",
  "to_create:": 9,
  "to_keep:": 0,
  "to_delete:": 10,
  "namespace": "logging",
  "es_name": "logging"
}
{
  "level": "info",
  "ts": 1566183242.8149285,
  "logger": "driver",
  "msg": "Calculated performable changes",
  "schedule_for_creation_count": 0,
  "schedule_for_deletion_count": 0,
  "namespace": "logging",
  "es_name": "logging"
}
{
  "level": "info",
  "ts": 1566183242.8444989,
  "logger": "elasticsearch-controller",
  "msg": "Updating status",
  "iteration": 420,
  "namespace": "logging",
  "es_name": "logging"
}
{
  "level": "info",
  "ts": 1566183242.8445811,
  "logger": "elasticsearch-controller",
  "msg": "End reconcile iteration",
  "iteration": 420,
  "took": 1.482764451,
  "namespace": "logging",
  "es_ame": "logging"
}
{
  "level": "info",
  "ts": 1566183252.8447728,
  "logger": "elasticsearch-controller",
  "msg": "Start reconcile iteration",
  "iteration": 421,
  "namespace": "logging",
  "es_name": "logging"
}
{
  "level": "info",
  "ts": 1566183252.9099252,
  "logger": "transport",
  "msg": "Reconciling transport certificate secrets",
  "namespace": "logging",
  "es_name": "logging"
}
{
  "level": "info",
  "ts": 1566183254.496384,
  "logger": "driver",
  "msg": "Calculated all required changes",
  "to_create:": 9,
  "to_keep:": 0,
  "to_delete:": 10,
  "namespace": "logging",
  "es_name": "logging"
}
{
  "level": "info",
  "ts": 1566183254.4966488,
  "logger": "driver",
  "msg": "Calculated performable changes",
  "schedule_for_creation_count": 0,
  "schedule_for_deletion_count": 0,
  "namespace": "logging",
  "es_name": "logging"
}
{
  "level": "info",
  "ts": 1566183381.7544858,
  "logger": "elasticsearch-controller",
  "msg": "Updating status",
  "iteration": 421,
  "namespace": "logging",
  "es_name": "logging"
}
{
  "level": "info",
  "ts": 1566183381.7546868,
  "logger": "elasticsearch-controller",
  "msg": "End reconcile iteration",
  "iteration": 421,
  "took": 128.909919607,
  "namespace": "logging",
  "es_ame": "logging"
}
{
  "level": "error",
  "ts": 1566183381.7547467,
  "logger": "kubebuilder.controller",
  "msg": "Reconciler error",
  "controller": "elasticsearch-controller",
  "request": "logging/logging",
  "error": "error during migrate data: Put https://logging-es-http.logging.svc:9200/_cluster/settings: dial tcp 10.43.141.112:9200: connect: connection timed out",
  "errorCauses": [
    {
      "error": "error during migrate data: Put https://logging-es-http.logging.svc:9200/_cluster/settings: dial tcp 10.43.141.112:9200: connect: connection timed out",
      "errorVerbose": "Put https://logging-es-http.logging.svc:9200/_cluster/settings: dial tcp 10.43.141.112:9200: connect: connection timed out\nerror during migrate data\ngithub.com/elastic/cloud-on-k8s/operators/pkg/controller/elasticsearch/driver.(*defaultDriver).Reconcile\n\t/go/src/github.com/elastic/cloud-on-k8s/operators/pkg/controller/elasticsearch/driver/default.go:393\ngithub.com/elastic/cloud-on-k8s/operators/pkg/controller/elasticsearch.(*ReconcileElasticsearch).internalReconcile\n\t/go/src/github.com/elastic/cloud-on-k8s/operators/pkg/controller/elasticsearch/elasticsearch_controller.go:270\ngithub.com/elastic/cloud-on-k8s/operators/pkg/controller/elasticsearch.(*ReconcileElasticsearch).Reconcile\n\t/go/src/github.com/elastic/cloud-on-k8s/operators/pkg/controller/elasticsearch/elasticsearch_controller.go:215\ngithub.com/elastic/cloud-on-k8s/operators/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/elastic/cloud-on-k8s/operators/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215\ngithub.com/elastic/cloud-on-k8s/operators/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/elastic/cloud-on-k8s/operators/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/elastic/cloud-on-k8s/operators/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/elastic/cloud-on-k8s/operators/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/elastic/cloud-on-k8s/operators/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/elastic/cloud-on-k8s/operators/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/elastic/cloud-on-k8s/operators/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/elastic/cloud-on-k8s/operators/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1333"
    }
  ],
  "stacktrace": "github.com/elastic/cloud-on-k8s/operators/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/elastic/cloud-on-k8s/operators/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/elastic/cloud-on-k8s/operators/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/elastic/cloud-on-k8s/operators/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:217\ngithub.com/elastic/cloud-on-k8s/operators/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/elastic/cloud-on-k8s/operators/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/elastic/cloud-on-k8s/operators/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/elastic/cloud-on-k8s/operators/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/elastic/cloud-on-k8s/operators/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/elastic/cloud-on-k8s/operators/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/elastic/cloud-on-k8s/operators/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/elastic/cloud-on-k8s/operators/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"
}
```
Pod listing (note an extra data pod):

```
$ kubectl -n logging get pod
NAME                           READY   STATUS    RESTARTS   AGE
logging-es-data-7rvl488qpb     1/1     Running   0          8h
logging-es-data-7zns7mxzt2     1/1     Running   0          8h
logging-es-data-bf4fppj6p6     1/1     Running   0          5h6m
logging-es-data-gvbmmmls7s     1/1     Running   0          8h
logging-es-data-ng82f24kwz     1/1     Running   0          8h
logging-es-ingest-gf2fbrhcv5   1/1     Running   0          8h
logging-es-ingest-xmc76gkbxw   1/1     Running   0          8h
logging-es-master-82qbg8f2kh   1/1     Running   0          8h
logging-es-master-n4kkzdf7tx   1/1     Running   0          8h
logging-es-master-qk2sj2b4vz   1/1     Running   0          8h
logging-kb-5dfb5657b9-rf274    1/1     Running   1          8h
```

**Comment by abh** [comment]
I enabled debugging on the operator and the messages then were showing that two pods were "still joining". It was the ingest pods. I deleted them and then the rest of the reconciliation continued (though the ingest pods didn't get created again yet ...)

**Comment by abh** [comment]
It seems like it still gets stuck now and then with node putting "master not discovered yet" in the logs (and then listing nodes that don't include the current master).

**Comment by anyasabo** [comment]
Thanks for reporting this @abh. I'll see if I can reproduce it here in a little bit. Can you clarify which node group's resource limits you changed so I can make sure I'm creating an accurate test?

**Comment by getorca** [comment]
having the same issue when I try to update a cluster with a podtemplate from ``kubectl apply -f myyaml.yaml``:

```
- podTemplate:
      spec:
        initContainers:
        - name: install-plugins
          command: ['sh', '-c', '| bin/elasticsearch-plugin install --batch repository-s3']
```
