### ISSUE TITLE
Volume claim template not mounting volume on pod

### ISSUE THREAD

**Issue by racevedoo** [elastic/cloud-on-k8s#1601]
## Bug Report
**What did you do?**
I'm trying to deploy an elasticsearch cluster using local node storage, as follows:
```yml
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: my-cluster
  namespace: my-namespace
spec:
  version: "7.2.0"
  nodes:
    - config:
        node.master: true
        node.data: true
        xpack.graph.enabled: false
        xpack.ml.enabled: false
        xpack.monitoring.enabled: false
        xpack.watcher.enabled: false
      podTemplate:
        metadata:
          labels:
            elasticsearch-cluster: my-cluster
        spec:
          nodeSelector:
            node-role.inloco.com/elasticsearch-i3large: "true"
          containers:
            - name: elasticsearch
              resources:
                limits:
                  ephemeral-storage: "10Gi"
                  memory: 13Gi
                  cpu: 1.6
                requests:
                  ephemeral-storage: "5Gi"
                  memory: 13Gi
                  cpu: 1.6
      nodeCount: 3
      volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: local-storage
          resources:
            requests:
              storage: 400Gi
```
**What did you expect to see?**
The volume claim for `elasticsearch-data` should mount a volume on the pod
**What did you see instead? Under which circumstances?**
The output of running `df -h` on the pod is:
```
Filesystem      Size  Used Avail Use% Mounted on
overlay          30G   11G   20G  35% /
tmpfs           7.5G     0  7.5G   0% /dev
tmpfs           7.5G     0  7.5G   0% /sys/fs/cgroup
/dev/xvda1       30G   11G   20G  35% /etc/hosts
shm              64M     0   64M   0% /dev/shm
tmpfs           7.5G   12K  7.5G   1% /mnt/elastic-internal/xpack-file-realm
tmpfs           7.5G  4.0K  7.5G   1% /mnt/elastic-internal/elasticsearch-config
tmpfs           7.5G  4.0K  7.5G   1% /mnt/elastic-internal/probe-user
tmpfs           7.5G   12K  7.5G   1% /usr/share/elasticsearch/config/transport-certs
tmpfs           7.5G  8.0K  7.5G   1% /usr/share/elasticsearch/config/http-certs
tmpfs           7.5G     0  7.5G   0% /sys/firmware
```
This shows that the volume was not mounted properly.
When no volume claim template is set for `elasticsearch-data`, the following happens with `df -h`:
```
Filesystem      Size  Used Avail Use% Mounted on
overlay          30G   19G   12G  63% /
tmpfs           7.5G     0  7.5G   0% /dev
tmpfs           7.5G     0  7.5G   0% /sys/fs/cgroup
/dev/xvda1       30G   19G   12G  63% /etc/hosts
shm              64M     0   64M   0% /dev/shm
tmpfs           7.5G  4.0K  7.5G   1% /mnt/elastic-internal/probe-user
tmpfs           7.5G   12K  7.5G   1% /mnt/elastic-internal/xpack-file-realm
tmpfs           7.5G  4.0K  7.5G   1% /mnt/elastic-internal/elasticsearch-config
/dev/xvdbe      976M  2.6M  958M   1% /usr/share/elasticsearch/data
tmpfs           7.5G   12K  7.5G   1% /usr/share/elasticsearch/config/transport-certs
tmpfs           7.5G  8.0K  7.5G   1% /usr/share/elasticsearch/config/http-certs
tmpfs           7.5G     0  7.5G   0% /sys/firmware
```
This shows that the default `1GB` volume was mounted for the data dir.
**Environment**
AWS EKS running k8s 1.11
* Version information:
Running ECK 0.9.0

**Comment by sebgl** [comment]
I tested your yaml file against a GKE cluster (changing the storage class name to "standard" and removing nodeSelector), and I can correctly see the volume mounted with the correct size.

I'm wondering if there might be something wrong in the way your "local-storage" storage class works. Can you give more details about your current setup? Did you install any particular local storage plugin?

Also, can you check if corresponding PVCs have been created if you run `kubectl get pvc`?

**Comment by racevedoo** [comment]
I guess the problem is with the storage class.

I changed the storage class to `aws-us-east-1c-gp2`, defined below, and it worked.:
```yml
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: aws-us-east-1c-gp2
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  zone: us-east-1c
```

My `local-storage` storage class is defined as stated in the ECK docs
```yml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
```

There are no local storage plugins installed, I created the PVs manually. Could that be an issue? I don't think so

**Comment by sebgl** [comment]
Could you give more details about how you created the PVs?

**Comment by racevedoo** [comment]
Here's the manifest:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-data-pv-0
spec:
  capacity:
    storage: 400Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage
  local:
    path: /data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: "node-role.inloco.com/elasticsearch-i3large"
              operator: In
              values:
                - "true"
```

My main doubt about it is the `reclaimPolicy`, but it shouldn't make a difference on volume binding

**Comment by abusaidm** [comment]
I am facing the same issue and the PV is created without `persistentVolumeReclaimPolicy: Recycle`
PV is being claimed by other PVC with no issues.

**Comment by racevedoo** [comment]
@sebgl any updates on this?

**Comment by krakrjak** [comment]
I am also having this issue using GKE managed by Rancher. Here is the manifest I'm using:
```
apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: elastic
  namespace: elastic-cloud
spec:
  version: 7.5.0
  nodeSets:
  - name: logging-master
    count: 3
    config:
      node.master: true
      node.data: false
      node.ingest: false
      node.ml: false
      node.store.allow_mmap: false
      index.store.type: niofs
      cluster.remote.connect: false
    PodTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: 8Gi
              cpu: 4
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms2g -Xmx4g"
    volumeClaimTemplates:
    - metadata:
        name: logging-master-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        storageClassName: ssd

          
  - name: logging-bulk
    count: 3
    config:
      node.master: false
      node.data: true
      node.ingest: true
      node.ml: false
      node.store.allow_mmap: false
      index.store.type: niofs
      cluster.remote.connect: false
    PodTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: 32Gi
              cpu: 8
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms8g -Xmx24g"
    volumeClaimTemplates:
    - metadata:
        name: logging-bulk-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 500Gi
        storageClassName: ssd
```

The storage class `ssd` is a synonym of using `gce-pd` with SSD class persistent devices. The operator makes the devices just fine, but in the end the bulk devices are not mounted in the pods as seen here with a df -h from a data node:
```
Filesystem      Size  Used Avail Use% Mounted on
overlay         194G  7.5G  187G   4% /
tmpfs            64M     0   64M   0% /dev
tmpfs            26G     0   26G   0% /sys/fs/cgroup
/dev/sda1       194G  7.5G  187G   4% /etc/hosts
shm              64M  4.0K   64M   1% /dev/shm
tmpfs            26G   12K   26G   1% /mnt/elastic-internal/xpack-file-realm
tmpfs            26G  4.0K   26G   1% /mnt/elastic-internal/elasticsearch-config
tmpfs            26G  4.0K   26G   1% /mnt/elastic-internal/probe-user
/dev/sdc        976M  3.8M  957M   1% /usr/share/elasticsearch/data
tmpfs            26G   52K   26G   1% /usr/share/elasticsearch/config/transport-certs
tmpfs            26G   12K   26G   1% /usr/share/elasticsearch/config/http-certs
tmpfs            26G     0   26G   0% /proc/acpi
tmpfs            26G     0   26G   0% /proc/scsi
tmpfs            26G     0   26G   0% /sys/firmware
```
When I look at the devices allocated to the pod we can see the 500Gi devices requested attached to the pod, but completely ignored.

```
sdf       8:80   0    20G  0 disk 
sdd       8:48   0   500G  0 disk 
sdb       8:16   0    20G  0 disk 
sde       8:64   0     1G  0 disk 
sdc       8:32   0     1G  0 disk /usr/share/elasticsearch/data
sda       8:0    0   200G  0 disk 
|-sda14   8:14   0     4M  0 part 
|-sda15   8:15   0   106M  0 part 
`-sda1    8:1    0 199.9G  0 part /usr/share/elasticsearch/plugins
```

**Comment by sebgl** [comment]
@krakrjak I think there are 2 things to fix:

1. replace `PodTemplate` by `podTemplate`
2. the volumeClaimTemplates you want to use must be named `elasticsearch-data` (and not eg. `logging-bulk-data ` or `logging-master-data `)

**Comment by krakrjak** [comment]
I'm still doing some testing, but there was a marked change in deploying with the modified manifest suggested by @sebgl. Thank you! I'm having some issues with my cluster ATM, but will report back my additional findings once I've ironed out my end.

**Comment by krakrjak** [comment]
OK, my testing is now complete and it looks like everything works well. For completeness sake here is the corrected manifest that I have working now:
```
apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: elastic
  namespace: elastic-cloud
spec:
  version: 7.5.0
  nodeSets:
  - name: logging-master
    count: 3
    config:
      node.master: true
      node.data: false
      node.ingest: false
      node.ml: false
      node.store.allow_mmap: false
      index.store.type: niofs
      cluster.remote.connect: false
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: 8Gi
              cpu: 4
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms4g -Xmx4g"
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        storageClassName: ssd

          
  - name: logging-bulk
    count: 3
    config:
      node.master: false
      node.data: true
      node.ingest: true
      node.ml: false
      node.store.allow_mmap: false
      index.store.type: niofs
      cluster.remote.connect: false
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: 32Gi
              cpu: 8
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms24g -Xmx24g"
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 500Gi
        storageClassName: ssd
```

Which leads to the following disk usage in a data Pod:
```
Filesystem      Size  Used Avail Use% Mounted on
overlay         194G  4.1G  190G   3% /
tmpfs            64M     0   64M   0% /dev
tmpfs            30G     0   30G   0% /sys/fs/cgroup
/dev/sda1       194G  4.1G  190G   3% /etc/hosts
shm              64M  4.0K   64M   1% /dev/shm
tmpfs            30G   12K   30G   1% /mnt/elastic-internal/xpack-file-realm
tmpfs            30G  4.0K   30G   1% /mnt/elastic-internal/probe-user
tmpfs            30G  4.0K   30G   1% /mnt/elastic-internal/elasticsearch-config
/dev/sdb        492G   75M  492G   1% /usr/share/elasticsearch/data
tmpfs            30G   12K   30G   1% /usr/share/elasticsearch/config/http-certs
tmpfs            30G   52K   30G   1% /usr/share/elasticsearch/config/transport-certs
tmpfs            30G     0   30G   0% /proc/acpi
tmpfs            30G     0   30G   0% /proc/scsi
tmpfs            30G     0   30G   0% /sys/firmware
```

Thank you for the help and tips! I am fixed and enjoy using this operator much more than the previous ways of deploying ES on k8s. Keep up the good work!
