### ISSUE TITLE
Allow custom ES data paths

### ISSUE THREAD

**Issue by anyasabo** [elastic/cloud-on-k8s#1690]
Creating this from an interesting use case @jordansissel raised out of band.

We should consider adding support for custom Elasticsearch data (and log?) paths. Some providers have a relatively small maximum size of some disks, but allow you to attach multiple disks. For instance, GCP local SSDs are 375GB max but you can have up to 8 on a machine. Elasticsearch allows multiple data paths, so we could provide ES with a list of disks to use. Currently we blacklist that setting and hardcode it though. If we allow it to be configurable we could enable the multiple disk use case.

Refs:
- https://www.elastic.co/guide/en/elasticsearch/reference/7.3/path-settings.html
- https://github.com/elastic/cloud-on-k8s/blob/master/pkg/controller/elasticsearch/settings/fields.go#L42

**Comment by jordansissel** [comment]
Asking around Elastic, the recommendation seemed to be: RAID/JBOD 

I opened a support ticket with Google about how to raid/jbod on GKE. The answer is: don't do it.

> After further investigation regarding your request, the way mentioned in the Compute Engine documentation is not possible to use in GKE as you are attempting.

I'm trying to dig deeper, but we may have to allow multiple data paths _or_ assume max storage per machine is ~375gb when using local ssds in order to be successful with local ssds on GKE.

**Comment by jordansissel** [comment]
Following up with some news and a workaround.

After some additional diccussion with Google Support and doing some science:

* RAID is not currently easy to do on GKE, but it is possible.
* RAID0 is between 1.5-3x faster than single local SSDs (tested: 1 thread = 1.4x faster, 8 threads = 2.9x faster; 4 local disks)
* We can hack together RAID0 using a DaemonSet to ensure all nodes are correctly configured with a single, large SSD.

In the meantime, I found a workaround to allow ECK to use multiple disks without RAID.

I have a GKE cluster with --local-ssd-disks=4 and Elasticsearch in ECK configured with a podTemplate with the following:

```
        volumes:
        - name: ssd0
          hostPath:
            path: /mnt/disks/ssd0
            type: Directory
        - name: ssd1
          hostPath:
            path: /mnt/disks/ssd1
            type: Directory
        - name: ssd2
          hostPath:
            path: /mnt/disks/ssd2
            type: Directory
        - name: ssd3
          hostPath:
            path: /mnt/disks/ssd3
            type: Directory
        containers:  &containers
        - name: elasticsearch
          image: docker.elastic.co/staging/elasticsearch:7.4.0-1d719509
          env:
          # Curl in the readinessProbe triggers a kernel memory accounting bug(feature?)
          # So we disable it that part of curl.
          # https://github.com/elastic/seceng/issues/651
          - name: NSS_SDB_USE_CACHE
            value: "no"
          - name: path.data
            value: "/mnt/disks/ssd0,/mnt/disks/ssd1,/mnt/disks/ssd2,/mnt/disks/ssd3"
          volumeMounts:
          - name: ssd0
            mountPath: /mnt/disks/ssd0
          - name: ssd1
            mountPath: /mnt/disks/ssd1
          - name: ssd2
            mountPath: /mnt/disks/ssd2
          - name: ssd3
            mountPath: /mnt/disks/ssd3
```

The env var `path.data` overrides the one provided (and forbidden) by ECK, which is nice.

Monitoring reports expected values (4 disks ✖️ 375gb == 1.5tb):

![image](https://user-images.githubusercontent.com/131818/65287547-7c14e700-daf8-11e9-8648-65aea61d1b88.png)

We may be able to use this configuration (hostPath mounts) to test performance of Google Persistent Disk SSD vs local ssd. Noting, however:

* using hostPath means that kubernetes scheduler is likely unaware of the locality of the storage, so a restarted pod may move to another GKE node causing 100% of the data to be effectively lost on the previous GKE node.
* individual disks is not a recommended configuration by Elasticsearch. Instead, RAID providing a single filesystem is preferable.
