### ISSUE TITLE
Bug: the initContainers method does not install plugins or cause the pods to update

### ISSUE THREAD

**Issue by getorca** [elastic/cloud-on-k8s#1691]
## Bug Report
**What did you do?**
Added the below pod template to my elasticsearch yaml file and applied it with ```kubectl apply -f elasticsearch.yaml```:
```
- podTemplate:
      spec:
        initContainers:
        - name: install-plugins
          command: ['sh', '-c', '| bin/elasticsearch-plugin install --batch repository-s3']
  - nodeCount: 3
```

**What did you expect to see?**
The plugin did not install no pods updated. Nothing happened.

**What did you see instead? Under which circumstances?**
I expected the pods to update and the plugin be installed. 

**Environment**

* ECK version:

	0.9.0

* Kubernetes information:

	* Cloud: DigitalOcean
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by artemnikitin** [comment]
Hi @getorca,
Can you provide an additional info, which can help with understanding the reason for failure, using instructions from https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-troubleshooting.html?

**Comment by charith-elastic** [comment]
`command: ['sh', '-c', `**`'| bin/elasticsearch-plugin install --batch repository-s3`**`']` 
                                  
I think the problem is the superfluous pipe (`|`) character. Probably a copy-paste error?

**Comment by feizeikesi** [comment]
I also encountered similar problems.

elastic-operator logs:
`
{"level":"error","ts":1568452557.9417818,"logger":"kubebuilder.controller","msg":"Reconciler error","controller":"kibana-controller","request":"elastic/kibana-sample","error":"Deployment.apps \"kibana-sample-kb\" is invalid: spec.template.spec.initContainers[0].image: Required value","errorCauses":[{"error":"Deployment.apps \"kibana-sample-kb\" is invalid: spec.template.spec.initContainers[0].image: Required value"}],"stacktrace":"github.com/elastic/cloud-on-k8s/operators/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/elastic/cloud-on-k8s/operators/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/elastic/cloud-on-k8s/operators/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/elastic/cloud-on-k8s/operators/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:217\ngithub.com/elastic/cloud-on-k8s/operators/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/elastic/cloud-on-k8s/operators/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/elastic/cloud-on-k8s/operators/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/elastic/cloud-on-k8s/operators/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/elastic/cloud-on-k8s/operators/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/elastic/cloud-on-k8s/operators/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/elastic/cloud-on-k8s/operators/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/elastic/cloud-on-k8s/operators/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
`

**Comment by tuyennguyenngoc-epi** [comment]
I also get the same issue. Could you please reopen this issue?

**Comment by thbkrkr** [comment]
Hi @tuyennguyenngoc-epi,

What version of ECK are you using? Could you share a YAML manifest to reproduce the problem?

I've deployed this ES with ECK 1.7.1 and haven't encountered any issues:
```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: foo
spec:
  version: 7.14.0
  nodeSets:
  - name: master
    config:
      node.store.allow_mmap: false
    count: 1
    podTemplate:
      spec:
        initContainers:
        - name: install-plugins
          command: ['sh', '-c', 'bin/elasticsearch-plugin install --batch repository-s3'] 
```
The plugin has been successfully installed:
```sh
> kubectl logs foo-es-master-0 -c install-plugins
-> Installing repository-s3
-> Downloading repository-s3 from elastic
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.RuntimePermission accessDeclaredMembers
* java.lang.RuntimePermission getClassLoader
* java.lang.reflect.ReflectPermission suppressAccessChecks
* java.net.SocketPermission * connect,resolve
* java.util.PropertyPermission es.allow_insecure_settings read,write
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.
-> Installed repository-s3
-> Please restart Elasticsearch to activate any plugins installed
```
And the ES is up and running:
```sh
> kubectl get es,sts,po   
NAME                                             HEALTH   NODES   VERSION   PHASE   AGE
elasticsearch.elasticsearch.k8s.elastic.co/foo   green    1       7.14.0    Ready   6m36s

NAME                             READY   AGE
statefulset.apps/foo-es-master   1/1     6m33s

NAME                  READY   STATUS    RESTARTS   AGE
pod/foo-es-master-0   1/1     Running   0          5m53s
```

**Comment by tuyennguyenngoc-epi** [comment]
Thank @thbkrkr , I can install `repository-s3` successfully right now.
But I got same error when trying to use `initContainers ` to install `logstash-output-opsgenie`.
I run the command `kubectl logs logstash-prod-0 -c init-logstash -f` and I saw the `logstash-output-opsgenie` has been successfully installed. 
But when `logstash` container is running, I used the command `bin/logstash-plugin list` to check, `logstash-output-opsgenie` wasn't listed. I also saw the logs, it showed that `logstash-plugin list is missing`.
Here is my YAML:
```yaml
---

apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: "logstash-prod-pdb"
  labels:
    app: "logstash-prod"
    chart: "logstash"
    heritage: "Tiller"
    release: "prod"
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: "logstash-prod"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-prod-config
  labels:
    app: "logstash-prod"
    chart: "logstash"
    heritage: "Tiller"
    release: "prod"
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    config.reload.automatic: true
    # Activate only for debugging
    # pipeline.unsafe_shutdown: true
    # log.level: "debug"
    # config.debug: true
    
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-prod-pipeline
  labels:
    app: "logstash-prod"
    chart: "logstash"
    heritage: "Tiller"
    release: "prod"
data:
  logstash.conf: |
    input {
      azure_event_hubs {
        event_hub_connections => ["${EVENTHUB_LOG_LISTENER_CONNECTION_STRING}"]
        threads => 2
        decorate_events => true
        consumer_group => "logstash"
        codec => "json"
        storage_connection => "${STORAGE_ACCOUNT_CONNECTION_STRING}"
        storage_container => "logstash"
      }
    }

    output {
      opsgenie {
          "apiKey" => "api_key"
      }
    }
    
---

kind: Service
apiVersion: v1
metadata:
  name: "logstash-prod-headless"
  labels:
    app: "logstash-prod"
    chart: "logstash"
    heritage: "Tiller"
    release: "prod"
spec:
  clusterIP: None
  selector:
    app: "logstash-prod"
  ports:
    - name: http
      port: 9600

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: logstash-prod
  labels:
    app: "logstash-prod"
    chart: "logstash"
    heritage: "Tiller"
    release: "prod"
spec:
  serviceName: logstash-prod-headless
  selector:
    matchLabels:
      app: "logstash-prod"
      release: "prod"
  replicas: 1
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      name: "logstash-prod"
      labels:
        app: "logstash-prod"
        chart: "logstash"
        heritage: "Tiller"
        release: "prod"
      annotations:
        configchecksum: c59acb5d0213fbd0d0988181a0a78ecca260efe157b12152506abe4177d8163
        pipelinechecksum: 057f13905d2979815c4d5dd34f731577b951ac0ea3b68e1fcb4365ebe884683
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - "logstash-prod"
            topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 120
      volumes:
        - name: logstashconfig
          configMap:
            name: logstash-prod-config
        - name: logstashpipeline
          configMap:
            name: logstash-prod-pipeline
      initContainers:
      - name: init-logstash
        image: docker.elastic.co/logstash/logstash-oss:8.0.0-SNAPSHOT
        securityContext:
          privileged: true
        command: ['sh', '-c', 'bin/logstash-plugin install logstash-output-opsgenie']  
      
      containers:
      - name: "logstash"
        image: "docker.elastic.co/logstash/logstash-oss:8.0.0-SNAPSHOT"
        imagePullPolicy: "IfNotPresent"
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 300
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
          
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 3
          timeoutSeconds: 5
          
        ports:
        - name: http
          containerPort: 9600
        resources:
          limits:
            cpu: 1000m
            memory: 1536Mi
          requests:
            cpu: 100m
            memory: 1536Mi
          
        env:
          - name: LS_JAVA_OPTS
            value: "-Xmx1g -Xms1g"
          - name: EVENTHUB_LOG_LISTENER_CONNECTION_STRING
            value: $(EVENTHUB_LOG_LISTENER_CONNECTION_STRING__PROD)
          
        envFrom:
          - secretRef:
              name: central-logging-secrets
          - secretRef:
              name: cluster-secrets
          
        volumeMounts:
          - name: logstashconfig
            mountPath: /usr/share/logstash/config/logstash.yml
            subPath: logstash.yml
          - name: logstashpipeline
            mountPath: /usr/share/logstash/pipeline/logstash.conf
            subPath: logstash.conf
```
Thanks!
