### ISSUE TITLE
Cluster name cannot be set (default to docker-cluster)

### ISSUE THREAD

**Issue by psalaberria002** [elastic/cloud-on-k8s#1705]
## Bug Report
**What did you do?**
I created a cluster by deploying a Elasticsearch CRD where metadata.name is set to `relationships`.

**What did you expect to see?**
I expected the cluster_name to be `relationships`.

**What did you see instead? Under which circumstances?**
Cluster name is set to `docker-cluster`.
```
{
  name: "SZLwgvP",
  cluster_name: "docker-cluster",
  cluster_uuid: "xbGeAr9zRp291blalP7gkA",
  version: {
    number: "6.3.2",
    build_flavor: "oss",
    build_type: "tar",
    build_hash: "053779d",
    build_date: "2018-07-20T05:20:23.451332Z",
    build_snapshot: false,
    lucene_version: "7.3.1",
    minimum_wire_compatibility_version: "5.6.0",
    minimum_index_compatibility_version: "5.0.0"
  },
  tagline: "You Know, for Search"
}
```

**Environment**

* ECK version:

	insert version or git commit id here

* Kubernetes information:
Cloud: GKE 1.13
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-13T23:15:13Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-gke.19", GitCommit:"bebe882824db5431820e3d59851c8fb52cb41675", GitTreeState:"clean", BuildDate:"2019-07-26T00:09:47Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}

```

* Resource definition:
```
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: relationships
  namespace: relationships
spec:
  version: 7.2.0
  nodes:
    - nodeCount: 3
      config:
        node.master: true
        node.data: false
        node.ingest: false
      podTemplate:
        metadata:
          labels:
            team: relationships
        spec:
          containers:
            - name: elasticsearch
              env:
                - name: ES_JAVA_OPTS
                  value: -Xms3500m -Xmx3500m
              resources:
                requests:
                  cpu: 2
                  memory: 4200Mi
                limits:
                  cpu: 2
                  memory: 4200Mi
      volumeClaimTemplates:
        - metadata:
            namespace: relationships
            name: elasticsearch-data # note: elasticsearch-data must be the name of the Elasticsearch volume
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
    - nodeCount: 2
      config:
        node.master: false
        node.data: true
        node.ingest: false
      podTemplate:
        metadata:
          labels:
            team: relationships
        spec:
          containers:
            - name: elasticsearch
              env:
                - name: ES_JAVA_OPTS
                  value: -Xms12000m -Xmx12000m
              resources:
                requests:
                  memory: 26000Mi
                  cpu: 7
                limits:
                  memory: 26000Mi
                  cpu: 7
      volumeClaimTemplates:
        - metadata:
            namespace: relationships
            name: elasticsearch-data # note: elasticsearch-data must be the name of the Elasticsearch volume
          spec:
            storageClassName: ssd
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 200Gi
    - nodeCount: 2
      config:
        node.master: false
        node.data: false
        node.ingest: true
      podTemplate:
        metadata:
          labels:
            team: relationships
        spec:
          containers:
            - name: elasticsearch
              env:
                - name: ES_JAVA_OPTS
                  value: -Xms5000m -Xmx5000m
              resources:
                requests:
                  memory: 8000Mi
                  cpu: 2
                limits:
                  memory: 8000Mi
                  cpu: 2
```

* Logs:
I have tried passing cluster.name in the config block, but got the following error: `Error from server (node[0]: cluster.name; node[1]: cluster.name; node[2]: cluster.name is not user configurable): error when creating "/Users/paulsmsm/cognite/spinnaker-pipelines/applications/infrastructure/elasticsearch-operator/manifests.yaml": admission webhook "validation.elasticsearch.elastic.co" denied the request: node[0]: cluster.name; node[1]: cluster.name; node[2]: cluster.name is not user configurable`

I already opened an issue in https://discuss.elastic.co/t/cluster-name-in-eck-operator-cannot-be-set/198850, but it seems Github is a better place for this.

Thanks in advance.
