### ISSUE TITLE
Move setVMMaxMapCount from top-level in spec

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#1712]
We think we are giving this attribute too much of prominence given that it is a hack to enable a smooth getting started experience.

Part of https://github.com/elastic/cloud-on-k8s/issues/1141

### Move the existing attribute one level down

```yaml
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
spec:
  version: 7.2.0
  unsafe: # tweaks, hacks, 
    setVmMaxMapCount: true 
  nodeSets:
  - name: default
    count: 3 
```
### Why not just securityContext?
Just using `PodSecurityContext` does not work because of the sysctl we want to use is typically not whitelisted thereby defeating the purpose of this exercise.
```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
spec:
  version: 7.3.0  
  nodeSets:
  - name: default
    podTemplate:
      spec:
        securityContext:
          sysctls:
          - name: vm.max_map_count
            value: "262144"
   count: 1
```

### Annotations
Looks like on [OpenShift](https://docs.openshift.com/container-platform/3.4/admin_guide/sysctls.html) you can use annotations as well, so there is some precedence 

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: sysctl-example
  annotations:
    security.alpha.kubernetes.io/sysctls: kernel.shm_rmid_forced=1
    security.alpha.kubernetes.io/unsafe-sysctls: net.ipv4.route.min_pmtu=1000,kernel.msgmax=1 2 3
spec:
```

This has the downside of creating an implicit API

**Comment by nkvoll** [comment]
Promoting tweaking the host in an init container feels a little rough (but can totally be done, IF you accept the security risks associated with it), so I'm not sure we should be strongly advocating it. This is an ES feature (both memory mapped files -- a lot of them, and bootstrap checks -- yay!), which can be disabled via config (https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-store.html#allow-mmap):

> You can restrict the use of the mmapfs and the related hybridfs store type via the setting node.store.allow_mmap. This is a boolean setting indicating whether or not memory-mapping is allowed. The default is to allow it. This setting is useful, for example, if you are in an environment where you can not control the ability to create a lot of memory maps so you need disable the ability to use memory-mapping.

I think we can make the argument that we can instruct our users to do either 1) set the sysctl setting in one of several ways, or 2) disable mmap because **if you are in an environment where you can not control the ability to create a lot of memory maps**. The description seem to fit.

Thus, I propose the following:

1. Remove `setVmMaxMapCount` from the spec. It's promoting bad behavior from containers.

2. Provide something ala this as a quickstart:
```yaml
cat <<EOF | kubectl apply -f -
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.2.0
  nodes:
  - name: default
    nodeCount: 1
    config:
      node.master: true
      node.data: true
      node.ingest: true
      ## Hosts running ES should set vm.max_map_count according to
      ## https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html
      ##
      ## If you're not able to configure this, node.store.allow_mmap can be set to false to
      ## disable memory mapped files to avoid this requirement, at the cost of performance
      ## (see https://www.elastic.co/guide/en/elasticsearch/reference/current/_maximum_map_count_check.html)
      #node.store.allow_mmap: false
EOF
```

We should probably discuss within the team whether we'd like to have this uncommented by default (for the quickstart only), and if we'd like to further document this (e.g add a section to "troubleshooting" that explains it further and allows for perhaps easier discovery when running into the issue outside of the quickstart).

A follow-up question should go to the ES team whether they are fine with this as the quickstart contents, or whether there are better ways we can/should deal with this. (e.g potentially allowing for a lower number of mem-mapped files for small clusters in the bootstrap-check?)

**Comment by jordansissel** [comment]
> Promoting tweaking the host in an init container feels a little rough 

Agreed. However, this has been in my experience the only way to make host-level changes on GKE. To phrase this another way, 100% of GKE users[1] are likely to need this sysctl vm.max_map_count setting.

In past explorations, I've found folks requesting things like a "DaemonJob" which would act like a DaemonSet (schedule on all nodes) but otherwise act like a Job (run once). I don't think anyone's got a solution for a 'daemon job' style thing.

 An initContainer with elevated privileges is the shortest path to declare "In order for this pod to be successful, the host needs to be configured a certain way." There's been recent work to move sysctl stuff (as mentioned above in the description) with a [PodSecurityPolicy](https://kubernetes.io/docs/tasks/administer-cluster/sysctl-cluster/#podsecuritypolicy), and maybe we can do something along those lines and then set this in the Elasticsearch pod's securityContext?

[1] I don't know how common it is for someone to run GKE but also do config management on their nodes (like with puppet or ansible). On Infosec, we run GKE's default OS image (Google Container-optimized OS) and it has a number of properties, like the filesystem changes revert on reboot and upgrade, which make it hard or annoying to do this.

I think our default behavior should be the same as our best practices. In this case, do change the vm.max_map_count setting unless we can't find any way to have it by default. Otherwise, I feel that our user experience especially involving support would always open the door on a sour note - a user experiencing a performance issue, and we may blame the lack of correct `vm.max_map_count`.

**Comment by jordansissel** [comment]
Checking the [helm chart](https://github.com/elastic/helm-charts/blob/1ad3826f26b4375b8935956d462f8777bd3c78a4/elasticsearch/templates/statefulset.yaml#L130-L139), it has an optional initContainer to set the sysctl settings.

The helm chart docs are interestingly worded to imply that you are _expected_ to set `vm.max_map_count` somehow, whether by the initContainer or by some other means. 

> sysctlInitContainer.enabled | Allows you to disable the sysctlInitContainer if you are setting vm.max_map_count with another method

The way I read this implies that it is not optional (though we know one can choose niofs instead of mmapfs, but our docs warn this [has bugs on windows](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-store.html)

Some prior discussions for this optional sysctl initContainer on the helm chart, if that helps:
* https://github.com/elastic/helm-charts/pull/132
* https://github.com/elastic/helm-charts/pull/220

**Comment by jordansissel** [comment]
> disable mmap because if you are in an environment where you can not control the ability to create a lot of memory maps

I feel like this is waaaaaay below the Kubernetes abstraction layer. A user is thinking about deploying Elasticsearch, and now we're forcing them to think about weird words like "mmap" and "sysctl". I don't think we should hide these details, but I wonder if we could suggest something on the same abstraction level as Kubernetes? Something like:

> In order to achieve best filesystem performance, you should set `vm.max_map_count` sysctl. You can have ECK do this for you if you install the appropriate PodSecurityPolicy
> 
> {example pod security policy}
> 
> If you can't install this PodSecurityPolicy, you will need to set an appropriate sysctl `vm.max_map_count` on all kubelet nodes yourself, or you will need to set [some Elasticsearch CRD setting] to false which causes Elasticsearch to avoid mmap, resulting in slower filesystem performance.

It's possible the operator could detect these situations on its own (Does an appropriate PodSecurityPolicy exist? etc)

It'd be ideal if users didn't have to think about this ;)

**Comment by pebrc** [comment]
>  However, this has been in my experience the only way to make host-level changes on GKE.

Does something provider specific not work, or am I missing your point?
For example:
`gcloud compute ssh $USER:$INSTANCE --project=$GCP_PROJECT --zone=$ZONE --command="sudo sysctl -w vm.max_map_count=262144"`

**Comment by jordansissel** [comment]
This works, manually. But we have dozens of GKE nodes coming and going week
to week. We would have to build a system for detecting new GKE nodes and
deploying this sysctl change quickly before we could deploy elasticsearch.
It adds another step, which adds complexity and room for error.

**Comment by nkvoll** [comment]
@jordansissel you can configure the GKE nodes bootstrap and add the sysctl setting there, so it happens e.g before the kubelet even starts. This makes the most sense to me: configuring host level settings on the host, at bootstrap.

This is a host-level sysctl (not namespaced), so one container setting it will affect all others on the host, so setting it in an init-container and hoping nothing overwrites it with something incompatible doesn't feel like an obvious/perfect solution. Assuming possible multi-tenancy/workloads here.

Nothing would prevent you from including such an init container on your own though if you accept the tradeoff (a few lines of YAML) is sufficient:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.2.0
  nodes:
  - name: default
    nodeCount: 1
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
```

In the end, this is going to have to be a trade-off between ease of use, security, isolation and we need to have this discussion in order to pick the default behavior that we believe makes the most sense. There's different kinds of users that will have different expectations here, and it looks like all options currently on the table seems very odd to at least one of the groups?
