### ISSUE TITLE
ECK is leaking services on StatefulSet rename/replacement

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#1713]
Start with
```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: hello-eck
spec:
  version: 7.3.0
  nodes:
  - name: default
    nodeCount: 1
```
upgrade to
```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: hello-eck
spec:
  version: 7.3.0
  nodes:
  - name: masters
    config:
      node.master: true
      node.data: false
    nodeCount: 3
  - name: data
    config:
      node.master: false
      node.data: true
    nodeCount: 3
```
See that after a while we have, as expected,  
```
 kubectl get sts
NAME                   DESIRED   CURRENT   AGE
hello-eck-es-data      3         3         11m
hello-eck-es-masters   3         3         11m
```

but the service sticks around:
```
kubectl get svc
NAME                   TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)    AGE
hello-eck-es-data      ClusterIP   None          <none>        <none>     12m
hello-eck-es-default   ClusterIP   None          <none>        <none>     15m
hello-eck-es-http      ClusterIP   10.99.9.63    <none>        9200/TCP   15m
hello-eck-es-masters   ClusterIP   None          <none>        <none>     12m
```
