### ISSUE TITLE
Somehow reduce repetition in ES node config.

### ISSUE THREAD

**Issue by jordansissel** [elastic/cloud-on-k8s#1757]
Today we had Kibana giving 500 error and the following error from Elasticsearch in Kibana's logs:

```
[security_exception] Cannot find any matching realm for [SamlPrepareAuthenticationRequest{realmName=cloud-saml, assertionConsumerServiceURL=null}]
```

Ultimately, this occurred because we have 3 different groups of nodes:

```
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: redacted
spec:
  version: 7.3.1
  nodes:
  - nodeCount: 3
    config:
        # some
        # config
        # here
  - nodeCount: 20
    config:
       # basically the same
       # config
      # here

**Comment by jordansissel** [comment]
Oops, premature submission. I fixed the description to be more complete.

**Comment by jordansissel** [comment]
I'm also thinking about maybe using [OPA](https://www.openpolicyagent.org/docs/latest/kubernetes-tutorial/) to reject configurations where we might make small mistakes like this.

**Comment by anyasabo** [comment]
I wasn't familiar with OPA but looks like it is essentially a framework for admission webhooks? We do some validating already but so far have punted on trying to validate ES configs (I believe because of the high chance of not doing it well, but someone may correct me here).

I'm definitely open to this, but I'm wary of having multiple levels of settings, defaults, and overrides. It gets complicated fast. But as you mentioned there can be a lot of repetition and the security configs themselves are pretty nested, so it can be a pain to troubleshoot.

**Comment by jordansissel** [comment]
+1 to it being complicated, and it may not even be possible, since ECK may not be familiar with any business-specific ideas that need validating, such as in my case where I want all nodes to have SAML setup -- I can imagine for some companies, "Only client nodes have saml" or something might be the correct config. I dunno.

**Comment by nkvoll** [comment]
I've hinted a few times at having some kind of base nodeset spec (ignore the specific key name for the purposes of the idea):

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: redacted
spec:
  version: 7.3.1
  nodeSetTemplate:
    # same format as elements under "nodes", will be used as a base template where the node-specific
    # elements may override.
    config:
      xpack.security.authc.realms: &xpack-realms
    podTemplate:
      annotations:
        foo: bar
    ...
  nodes:
  - nodeCount: 3
    config:
      node.data: false
      node.ingest: false
      node.ml: false
  - nodeCount: 20
    config:
      node.master: false
      node.ml: false
  - nodeCount: 1
    config:
      node.master: false
      node.data: false
      node.ingest: false
```

This would provide a base way of providing configuration or settings / pod settings that would be common between all the different nodesets in the resource. WDYT?
