### ISSUE TITLE
nodeSelector for Elasticsearch resource

### ISSUE THREAD

**Issue by SebastianCaceresUltra** [elastic/cloud-on-k8s#1767]
## Proposal

I'd like to be able to specify a nodeSelector on the CRDs of ECK. As far as I know, this is not
possible.

I tried specifying it like this:

```
---
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: elasticsearch-logging
spec:
  version: 7.2.0
  nodes:
  - nodeCount: 1
    config:
      node.master: true
      node.data: true
      node.ingest: true
  nodeSelector:
    role: application
```

But I still see `nodeSelector: <None>` when I describe the Elasticsearch pod.

**Comment by thbkrkr** [comment]
Hi Sebastian,

A `nodeSelector` can be declared for a set of nodes using the `podTemplate.spec` field:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.3.2
  nodes:
  - nodeCount: 3
    podTemplate:
      spec:
        nodeSelector:
          diskType: ssd
          environment: production
```

This is mentioned in the [Advanced Elasticsearch node scheduling](https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-advanced-node-scheduling.html#k8s_node_affinity) documentation.
