### ISSUE TITLE
Resources limits not being set and ES_JAVA_OPTS doesn't exist in pod

### ISSUE THREAD

**Issue by aTGuz** [elastic/cloud-on-k8s#1784]
Elastic container being evicted on kubernates over gcloud, I noted that the pod is consuming too much resources, over 5 gb of RAM, while the resource limits variables are not being set as you can see at the image bellow taked from the gcloud monitor panel, where the values are different from the config limits 2gb vs 3gb of RAM, 100m vs 2 of CPU

![image](https://user-images.githubusercontent.com/5741150/65513602-e8556900-deb1-11e9-9113-37e69c00c71a.png)

I enter into the pod an noted that the ES_JAVA_OPTS enviroment vatiable does not exist there but was set as you can see at the configuration used to deploy showed bellow.

Config:
```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 7.2.0
  nodes:
  - nodeCount: 1
    config:
      node.master: true
      node.data: true
      node.ingest: true
  - podTemplate:
      spec:
        containers:
        - name: elasticsearch
          env:
           - name: ES_JAVA_OPTS
             value: -Xms3g -Xmx3g
          resources:
            limits:
              cpu: 2
              memory: 6Gi
  - volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 60Gi
        storageClassName: standard
```

Thanks!

**Comment by sebgl** [comment]
Hi @aTGuz,

I edited your post to have proper yaml formatting.
It looks like the `podTemplate` section is not at the right place. It should be at the same level as `config` for the first group of nodes, without a `-`:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 7.2.0
  nodes:
  - nodeCount: 1
    config:
      node.master: true
      node.data: true
      node.ingest: true
    podTemplate:             # <----- HERE
      spec:
        containers:
        - name: elasticsearch
          env:
           - name: ES_JAVA_OPTS
             value: -Xms3g -Xmx3g
          resources:
            limits:
              cpu: 2
              memory: 6Gi
  - volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 60Gi
        storageClassName: standard
```
