### ISSUE TITLE
Introduce a separate repository attribute in the CRD

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#1793]
Related to #1141 

Suggested by @nkvoll 

Should we introduce a new attribute called `repository` to allow users in air-gapped environments to just overwrite the repository but keep version and base image name. 

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
spec:
  repository: my-custom-repository # effective image: my-custom-repository/elasticsearch/elasticsearch:7.3.0
  version: 7.3.0
```

Avoids the need to specify the version twice (in the `image` and in `version`)

But `image` would stay as a way to give full control to the user

 ```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
spec:
  repository: bar #ignored
  image: my-custom-repository/foo:1.0.0 # effective image: my-custom-repository/foo:1.0.0
  version: 7.3.0 # relevant to control operator behaviour 
```
