### ISSUE TITLE
Pods are never updated if ES can't be reached

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#1799]
1. Create a cluster with a wrong Pod configuration _(not a bad ES configuration)_ :
```
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
spec:
  version: 7.3.0
  nodes:
  - name: default
    podTemplate:
      spec:
        nodeSelector:
          diskType: mybad
    nodeCount: 1
```

2. Node never starts:
```
NAME                                    READY   STATUS    RESTARTS   AGE   IP       NODE     NOMINATED NODE   READINESS GATES
pod/elasticsearch-sample-es-default-0   0/1     Pending   0          43s   <none>   <none>   <none>           <none>
```
3. Try to fix the problem:
```
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
spec:
  version: 7.3.0
  nodes:
  - name: default
    nodeCount: 1
```

Pod is not updated because Elasticsearch must be reachable in order to restart the Pods and upgrade them: https://github.com/elastic/cloud-on-k8s/blob/master/pkg/controller/elasticsearch/driver/nodes.go#L77
