### ISSUE TITLE
Use a command for Kibana readiness probe due to security constraints with httpGet

### ISSUE THREAD

**Issue by sarjeet2013** [elastic/cloud-on-k8s#1819]
## Proposal

**Use case. Why is this important?**

It is required for reliably checking for kibana pod containers readiness.

The current readiness seems very basic and not sure when it is expect to get the actual readiness.

Current readiness:
```
readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /login
        port: 5601
        scheme: HTTPS
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
```

The above readiness probe just probes on the /login but may hide few other problems with the kibana container readiness itself. 

I feel it could be something to reliably to check the readiness, as done for elasticsearch containers.

**Comment by sarjeet2013** [comment]
I just tried to see if this can be similar to elasticsearch container readiness and it seems to work fine.

curl -o /dev/null -w "%{http_code}" --max-time 3 -XGET -s -k -u default-kibana-1node-kibana-user:zx42xz5fwzqxdw5vtr8hzf7p  https://127.0.0.1:5601/login
200

This works as expected, but require the user and password which I retrieved from `<cr>-kibana-user` secret. I am not sure if this secret user can be used or it may require a new kibana probe user for readiness check.

**Comment by sebgl** [comment]
@sarjeet2013 I'm curious about errors cases you may have found that an authenticated curl against `/login` returned but not an unauthenticated one?

**Comment by sarjeet2013** [comment]
There are 2 reasons for this issue.

1. Currently, our k8s env blocks traffic from host to container (due to security reasons) which blocks the readinessProbe with httpGet.

2. Regarding authenticated vs unauthenticated, AFAICT both returns 200 fine.

➜  curl -o /dev/null -w "%{http_code}" --max-time 3 -XGET -s -k -u default-kibana-1node-kibana-user:xxxx https://x.x.x.x:5601/login
200%                                                                                                                                                                                                    ➜  curl -o /dev/null -w "%{http_code}" https://x.x.x.x:5601/login -k -s
200%

But, It would be preferable if the readinessProbe request could be authenticated, similar to ES using exec based readinessProbe.

**Comment by sebgl** [comment]
> Currently, our k8s env blocks traffic from host to container (due to security reasons) which blocks the readinessProbe with httpGet.

Indeed, that sounds like a good reason.

As a workaround, you can set your own readiness probe, by overriding the podTemplate section of the Kibana resource.

**Comment by sarjeet2013** [comment]
@sebgl Yes. Using this workaround already :)

```
podTemplate:
    spec:
      containers:
        - name: kibana
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            exec:
              command:
                - /bin/bash
                - -c
                - curl -o /dev/null -w "%{http_code}" https://127.0.0.1:5601/login -k -s
```

Please let me know if the above suggestion of using command is the (preferred) workable solution. I am happy to work on it and make a PR for it.
