### ISSUE TITLE
CRD podTemplate schema forces to declare an empty spec.containers

### ISSUE THREAD

**Issue by thbkrkr** [elastic/cloud-on-k8s#1822]
By working to bump the CRD version (#1782 ), TestSmoke fails with: `spec.podTemplate.spec.containers in body must be of type array: "null"`.

With the new controller-gen that comes with kubebuilder 2, the `podTemplate` object schema is fully inlined in our CRDs.

As there must be at least one container in a Pod, the `Containers []Container 'json:"containers"'` does not have the `omitempty` tag.

So when a `podTemplate.spec` property is defined like a `podTemplate.spec.securityContext`, then the `podTemplate.spec.containers` is set by default to `nil` and this is what causes the validation error.

To pass validation, `podTemplate.spec.containers` should always be set to an empty array if not used. It seems very compelling to always have to ask for this declaration.

Example:

```yaml
apiVersion: kibana.k8s.elastic.co/v1beta1
kind: Kibana
metadata:
  name: kibana-sample
spec:
  version: 7.3.0
  nodeCount: 1
  elasticsearchRef:
    name: "elasticsearch-sample"
  podTemplate:
    spec:
      updateStrategy:
        changeBudget:
          maxSurge: 1
          maxUnavailable: 0
      containers: []  # <-------
```

We have identified 4 potential solutions to solve this problem.

#### 1) Use a mutating admission webhook

That we do not have currently.

#### 2) Remove the `podTemplate` schema from the CRD

We loose the `podTemplate` validation which is a very nice feature to have.

#### 3) Have our own `podSpec` struct (copied from the original)

This implies maintaining a kind of fork.

#### 4) Make the `podTemplate.spec.containers` field optional

This involves applying some post-treatment after the CRD generation to remove the `containers` item from the `podTemplate.spec.required` string array.
