### ISSUE TITLE
CRD multi-versions support with schema changes

### ISSUE THREAD

**Issue by thbkrkr** [elastic/cloud-on-k8s#1823]
The CustomResourceDefinition API supports [multiple versions](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definition-versioning/#specify-multiple-versions) and schema validation only from k8s 1.13 (apiextensions.k8s.io/v1).

Prior to 1.13 (apiextensions.k8s.io/v1beta1), there is no way to declare several schemas. The latest version of controller-gen brings the `trivialVersions` option to continue to generate CRD that are compatible with k8s < 1.13. The downside of using this option is, that it results to the generation of a CRD without schema.

With `trivialVersions`, when there is no schema change, the CRD looks like:
```yaml
spec:
  validation:
    openAPIV3Schema:
      description: ...
      properties:
        <...SCHEMA IS DECLARED HERE...>
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: false
  - name: v1beta1
    served: true
    storage: true
```

With `trivialVersions`, and schema changes between the different versions, the `spec.validation.openAPIV3Schema` is omitted and as the `versions` field does not have a `schema` field, we completely lose the schema:

```yaml
spec:
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: false
  - name: v1beta1
    served: true
    storage: true
```

Without `trivialVersions`, the CRD have the two schemas but are compatible only with k8s >= 1.13:

```yaml
  version: v1beta1
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: ...
        properties:
          <...HERE IS THE SCHEMA...>
        type: object
    served: true
    storage: true
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ...
        properties:
          <...HERE IS THE SCHEMA...>
        type: object
    served: true
    storage: false
```
