### ISSUE TITLE
API failure prevents cluster upgrade

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#1847]
This is a follow-up of #1827 

```
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
spec:
  version: 7.3.0
  nodes:
  - name: default
    podTemplate:
      spec:
        nodeSelector:
          diskType: mybad
    nodeCount: 1
  - name: default-2
    nodeCount: 1
```

With the manifest above [ES is considered as "reachable"](https://github.com/elastic/cloud-on-k8s/blob/ca2c732bd1ca9503a203b3902badafeb0a8aed5b/pkg/controller/elasticsearch/services/services.go#L65)  (i.e.`esReachable` is `true`) because there is at least one node in the service.
The problem is that [the subsequent call to the API fail](https://github.com/elastic/cloud-on-k8s/blob/master/pkg/controller/elasticsearch/driver/nodes.go#L78-L83) and do not give a chance to the deployment to be updated.
