### ISSUE TITLE
Promoting failure domains in ES Spec

### ISSUE THREAD

**Issue by nkvoll** [elastic/cloud-on-k8s#187]
@sebgl and I talked briefly about how we could the ES Spec aware of failure domains, and we came up with an option, which might be worth capturing.

## TODO
- [ ] Explore more options
- [ ] Explain option tradeoffs

## Options
Option 1)
```
apiVersion: deployments.k8s.elastic.co/v1alpha1
kind: Stack
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: stack-sample
spec:
  version: "6.4.2"
  elasticsearch:
    setVmMaxMapCount: true
    updateStrategy:
      groups:
      # give each failure domain a chance to reconcile failures before regular changes:
      - selector:
          matchLabels:
            failure-domain.beta.kubernetes.io/zone: europe-west3-a
      - selector:
          matchLabels:
            failure-domain.beta.kubernetes.io/zone: europe-west3-b
      - selector:
          matchLabels:
            failure-domain.beta.kubernetes.io/zone: europe-west3-c
      changeBudget:
        maxSurge: 1
        maxUnavailable: 0
    topologies:
    - nodeTypes:
        master: true
        data: true
        ingest: true
      resources:
        limits:
          memory: 1Gi
          cpu: 800m
      nodes:
        # failureDomains creates replicas of this topology element in different failure domains
        failureDomains:
        - name: a
          # needs to be merged with topology.template.spec.nodeAffinity
          nodeAffinity: ...
          replicas: 1
        - name: b
          nodeAffinity: ...
          replicas: 1
        - name: c
          nodeAffinity: ...
          replicas: 1
        # EXCLUSIVE OR WITH
        # replicas is a simple number of replicas
        replicas: 3
      ## this shows how to add a custom label to all pods created for this topology element
      #template:
      #  metadata:
      #    labels:
      #      foo: bar
    expose: LoadBalancer
  kibana:
    nodeCount: 1
    expose: LoadBalancer
```
