### ISSUE TITLE
Kibana: allow the user to provide its own ES connection settings

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#1875]
It is not possible for the user to provide its own ES connection settings and to connect to an external Elasticsearch cluster.

It is also not consistent with what can be done with the APM Server.

**Comment by Brian-McM** [comment]
I think there's also a problem with internal es clusters as there's no way to configure the elasticsearch credentials specified by the kibana CRD:
`
elasticsearch:
      description: Elasticsearch configures how Kibana connects to Elasticsearch
      properties:
        auth:
          description: Auth configures authentication for Kibana to use.
          properties:
            inline:
              description: Inline is auth provided as plaintext inline credentials.
              properties:
                password:
                  description: Password is the password to use.
                  type: string
                username:
                  description: User is the username to use.
                  type: string
              required:
              - username
              - password
              type: object
            secret:
              description: SecretKeyRef is a secret that contains the credentials
                to use.
              type: object
          type: object
        certificateAuthorities:
          description: CertificateAuthorities names a secret that contains
            a CA file entry to use.
          properties:
            secretName:
              type: string
          type: object
        url:
          description: ElasticsearchURL is the URL to the target Elasticsearch
          type: string
      required:
      - url
      type: object
`
Is there another way to specify the username / password and cert secret?

**Comment by pebrc** [comment]
@Brian-McM the section you are quoting here has been removed from the CRD in #1687 

You can specify username and password as you would for Kibana running outside of k8s:
```
apiVersion: kibana.k8s.elastic.co/v1beta1
kind: Kibana
metadata:
  name: kibana-sample
spec:
  version: 7.4.0
  config:
    elasticsearch.hosts:
    - https://url.to.elasticsearch:9200
    elasticsearch.username: my-kibana-user
    elasticsearch.password: $PASSWORD
    elasticsearch.ssl.certificateAuthorities: /mnt/certs/elasticsearch/ca.crt
  count: 1
  podTemplate:
    spec:
      containers:
      - name: kibana
        volumeMounts:
        - name: certs
          mountPath: /mnt/certs/elasticsearch
      volumes:
      - name: certs
        secret:
          secretName: my-es-http-certs
```

The problem this issue tries to address is that we abort the reconciliation if there is no associated Elasticsearch cluster in k8s for a given Kibana

https://github.com/elastic/cloud-on-k8s/blob/d91679b05ed15f7dbb88d367c7b9b16544f64ca5/pkg/controller/kibana/driver.go#L217-L220
