### ISSUE TITLE
VolumeClaimTemplate memory request getting overridden with default value

### ISSUE THREAD

**Issue by saurabh24292** [elastic/cloud-on-k8s#1877]
## Proposal

**Use case. Why is this important?**
Defaukt setting overriding the user setting leads to cluster breakdown

## Bug Report
**What did you do?**
Followed the guide in this repo for setting PVC memory request for pods

**What did you expect to see?**
pods having specified storage PVC claims

**What did you see instead? Under which circumstances?**
pods having default storage size

**Environment**
GKE

* ECK version:

	0.90

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* On premise ?
	* Cloud: GKE / EKS / AKS ?
	* Kubernetes distribution: Openshift / Rancher / PKS ?
	
GKE```
$ kubectl version
1.14
```

* Resource definition:
This is my elasticsearch yaml file
```
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: es-cluster
  namespace: elastic-system
spec:
  version: 7.2.0
  nodes:
  # 3 dedicated master nodes
  - nodeCount: 3
    config:
      node.master: true
      node.data: false
      node.ingest: false
      cluster.remote.connect: false
    podTemplate:
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    elasticsearch.k8s.elastic.co/cluster-name: es-cluster
                topologyKey: kubernetes.io/hostname
        nodeSelector:
          cloud.google.com/gke-nodepool: es-simple-gke-pool
        initContainers:
        - name: init-sysctl
          image: busybox:1.27.2
          command:
          - sysctl
          - -w
          - vm.max_map_count=2621441
          securityContext:
            privileged: true
        - name: install-plugins
          command:
          - sh
          - -c
          - |
            bin/elasticsearch-plugin install --batch repository-gcs
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms10g -Xmx10g
          - name: NSS_SDB_USE_CACHE
            value: "no"
          resources:
            requests:
              memory: 5Gi
            limits:
              cpu: 4
              memory: 20Gi
  # 3 coordinating nodes
  - nodeCount: 3
    config:
      node.master: false
      node.data: false
      node.ingest: false
    podTemplate:
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    elasticsearch.k8s.elastic.co/cluster-name: es-cluster
                topologyKey: kubernetes.io/hostname
        nodeSelector:
          cloud.google.com/gke-nodepool: es-simple-gke-pool
        initContainers:
        - name: init-sysctl
          image: busybox:1.27.2
          command:
          - sysctl
          - -w
          - vm.max_map_count=2621441
          securityContext:
            privileged: true
        - name: install-plugins
          command:
          - sh
          - -c
          - |
            bin/elasticsearch-plugin install --batch repository-gcs
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms10g -Xmx10g
          - name: NSS_SDB_USE_CACHE
            value: "no"
          resources:
            requests:
              memory: 5Gi
            limits:
              cpu: 4
              memory: 20Gi
  # 4 data nodes
  - nodeCount: 4
    config:
      node.master: false
      node.data: true
      node.ingest: false
    podTemplate:
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    elasticsearch.k8s.elastic.co/cluster-name: es-cluster
                topologyKey: kubernetes.io/hostname
        nodeSelector:
          cloud.google.com/gke-nodepool: es-simple-gke-pool
        initContainers:
        - name: init-sysctl
          image: busybox:1.27.2
          command:
          - sysctl
          - -w
          - vm.max_map_count=2621441
          securityContext:
            privileged: true
        - name: install-plugins
          command:
          - sh
          - -c
          - |
            bin/elasticsearch-plugin install --batch repository-gcs
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms10g -Xmx10g
          - name: NSS_SDB_USE_CACHE
            value: "no"
          resources:
            requests:
              memory: 5Gi
            limits:
              cpu: 4
              memory: 20Gi
  - volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 200Gi
        storageClassName: local-storage
  updateStrategy:
    changeBudget:
      maxSurge: 1
      maxUnavailable: 0
  secureSettings:
    secretName: gcs-credentials
  http:
    service:
      spec:
        type: ClusterIP
```
```
"Suppressed: java.io.IOException: No space left on device",
"\tat sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[?:?]",
"\tat sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:62) ~[?:?]",
"\tat sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113) ~[?:?]",
"\tat sun.nio.ch.IOUtil.write(IOUtil.java:79) ~[?:?]",
"\tat sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:280) ~[?:?]",
```
* Logs:
```
[root@es-cluster-es-2zxqt9x45t elasticsearch]# df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay         582G  4.5G  577G   1% /
tmpfs            64M     0   64M   0% /dev
tmpfs            15G     0   15G   0% /sys/fs/cgroup
/dev/sda1       582G  4.5G  577G   1% /etc/hosts
shm              64M     0   64M   0% /dev/shm
tmpfs            15G   12K   15G   1% /mnt/elastic-internal/xpack-file-realm
tmpfs            15G  4.0K   15G   1% /mnt/elastic-internal/elasticsearch-config
tmpfs            15G  4.0K   15G   1% /mnt/elastic-internal/probe-user
/dev/sdb        976M  663M  298M  70% /usr/share/elasticsearch/data
tmpfs            15G  8.0K   15G   1% /usr/share/elasticsearch/config/http-certs
tmpfs            15G   12K   15G   1% /usr/share/elasticsearch/config/transport-certs
tmpfs            15G     0   15G   0% /proc/acpi
tmpfs            15G     0   15G   0% /proc/scsi
tmpfs            15G     0   15G   0% /sys/firmware
```

**Comment by sebgl** [comment]
Hi @saurabh24292,
The `VolumeClaimTemplates` section setting is per group of node. In your example it is set at a higher level. You have to move it at the same level as `config` and `podTemplate` in each individual group of nodes. You may want to specialize the storage requirements for each group (eg. less storage for dedicated master nodes).

**Comment by saurabh24292** [comment]
Extremely sorry. I just realized that I messed up the format while posting the question. Really thanks for the reply. Indeed I have setup the VolumeClaimTemplates at a higher level. I will incorporate your suggestions and get back.

**Comment by sebgl** [comment]
No worries @saurabh24292! It happens to me as well all the time! We'll work on adding the proper validations to the resource.

**Comment by saurabh24292** [comment]
Tried changing that. But then my elasticsearch pods are not getting created.
```
$ kubectl -n elastic-system get all
NAME                     READY   STATUS    RESTARTS   AGE
pod/elastic-operator-0   1/1     Running   1          3d

NAME                              TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE
service/elastic-webhook-service   ClusterIP   10.79.15.117   <none>        443/TCP   3d

NAME                                READY   AGE
statefulset.apps/elastic-operator   1/1     3d
```

Here is how the yaml segment looks now:
```
  # 4 data nodes
  - nodeCount: 4
    config:
      node.master: false
      node.data: true
      node.ingest: false
    podTemplate:
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    elasticsearch.k8s.elastic.co/cluster-name: es-cluster
                topologyKey: kubernetes.io/hostname
        nodeSelector:
          cloud.google.com/gke-nodepool: es-simple-gke-pool
        initContainers:
        - name: init-sysctl
          image: busybox:1.27.2
          command:
          - sysctl
          - -w
          - vm.max_map_count=2621441
          securityContext:
            privileged: true
        - name: install-plugins
          command:
          - sh
          - -c
          - |
            bin/elasticsearch-plugin install --batch repository-gcs
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms10g -Xmx10g
          - name: NSS_SDB_USE_CACHE
            value: "no"
          resources:
            requests:
              memory: 5Gi
            limits:
              cpu: 4
              memory: 20Gi
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 300Gi
        storageClassName: local-storage
  updateStrategy:
    changeBudget:
      maxSurge: 1
      maxUnavailable: 0
  secureSettings:
    secretName: gcs-credentials
  http:
    service:
      spec:
        type: ClusterIP
```

```
$ kubectl -n elastic-system get elasticsearch
NAME         HEALTH   NODES   VERSION   PHASE   AGE
es-cluster                    6.5.2             2m
```
