### ISSUE TITLE
Not able access Kibana using domain

### ISSUE THREAD

**Issue by swvaibhav** [elastic/cloud-on-k8s#1922]
I have just deployed, Elastic Cloud on Kubernetes (ECK) and not able to access Kibana on the public URL. I have also set up an Ingress to access Kibana using the domain.

Also, when using Kibana 7.2.0 the pod keeps on crashing with error message `Kibana should not be run as root.  Use --allow-root to continue.`

```yaml
apiVersion: kibana.k8s.elastic.co/v1alpha1
kind: Kibana
metadata:
  name: eck-kibana
  namespace: vulcan
spec:
  version: 7.1.0
  imagePullPolicy: Always
  nodeCount: 1
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  elasticsearchRef:
    name: eck-elastic
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: eck-kibana-ingress
  namespace: vulcan
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
    - secretName: eduqfix-tls-cert
  rules:
  - host: ecktest.eduqfix.com
    http:
      paths:
      - path: /
        backend:
          serviceName: eck-kibana-kb-http
          servicePort: 5601
```
