### ISSUE TITLE
Unable to create headless services for kibana and elastic

### ISSUE THREAD

**Issue by kurktchiev** [elastic/cloud-on-k8s#1943]
I see that I can specify the service type in the examples directory. However, I am unable to tell it that I want to create the following:
```
type: ClusterIP
clusterIP: None
```
At the end of the day I would like to create headless services. I am using 0.9 version of the operator on a Kube 1.13 cluster.

**Comment by charith-elastic** [comment]
This works on Kubernetes 1.13 with ECK 0.9.0:

```yaml
---
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
spec:
  version: 7.4.0
  http:
    service:
      spec:
        clusterIP: None
  nodes:
  - nodeCount: 3
    name: default
    config:
      node.store.allow_mmap: false
---
apiVersion: kibana.k8s.elastic.co/v1alpha1
kind: Kibana
metadata:
  name: kibana-sample
spec:
  version: 7.4.0
  nodeCount: 1
  elasticsearchRef:
    name: "elasticsearch-sample"
  http:
    service:
      spec:
        clusterIP: None 
```

```shell
k get elastic                  
NAME                                                              HEALTH   NODES   VERSION   PHASE         AGE
elasticsearch.elasticsearch.k8s.elastic.co/elasticsearch-sample   green    3       7.4.0     Operational   14m

NAME                                         HEALTH   NODES   VERSION   AGE
kibana.kibana.k8s.elastic.co/kibana-sample   green    1       7.4.0     14m

k get svc                           
NAME                           TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)    AGE
elasticsearch-sample-es-http   ClusterIP   None         <none>        9200/TCP   14m
kibana-sample-kb-http          ClusterIP   None         <none>        5601/TCP   14m
```

Please re-open if this doesn't answer your question.
