### ISSUE TITLE
Elasticsearch resources not getting applied

### ISSUE THREAD

**Issue by swvaibhav** [elastic/cloud-on-k8s#1964]
I am trying to change default assigned resources `CPU and RAM` to `Elasticsearch` Pod but it is not reflecting. Below is the YAML config and I am using 7.2.0 version of elastic

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: eck-elastic
  namespace: vulcan
spec:
  version: 7.2.0
  nodes:
  - podTemplate:
      spec:
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xmx3G
          resources:
            requests:
              memory: 3Gi
              cpu: 1
            limits:
              memory: 3Gi
              cpu: 1
  - nodeCount: 1
    config:
      node.master: true
      node.data: true
      node.ingest: true
```

**Comment by pebrc** [comment]
YAML issue: the pod template needs to be part of the node you are specifying, your example has unintentionally two node specs 

You probably want something like: 
```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: eck-elastic
  namespace: vulcan
spec:
  version: 7.2.0
  nodes:
  - nodeCount: 1
    config:
      node.master: true
      node.data: true
      node.ingest: true
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xmx3G
          resources:
            requests:
              memory: 3Gi
              cpu: 1
            limits:
              memory: 3Gi
              cpu: 1
```
