### ISSUE TITLE
Simplify Enterprise license installation

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#1965]
Installing an Enterprise license is needlessly complicated at the moment. Users need to create a secret that fulfills ~three~ two requirements:

1. ~`common.k8s.elastic.co/type: license` label~
2. `license.k8s.elastic.co/type: enterprise` label
3. a key called `license` mapped to the actual license data

Consider this example:
```yaml
apiVersion: v1
kind: Secret
metadata:
  labels:
    common.k8s.elastic.co/type: license # 1. this is optional
    license.k8s.elastic.co/type: enterprise # 2. this is required
  name: you-choice
type: Opaque
data:
  license: "..."  # needs to be called 'license'
```

That seems needlessly complex and redundant. It also means that creating such a secret is a multi-step process

```
kubectl create secret generic eck-license --from-file=license=my-license-file.json -n elastic-system
kubectl label secret eck-license "license.k8s.elastic.co/type"=enterprise -n elastic-system 
kubectl label secret eck-license "common.k8s.elastic.co/type"=license -n elastic-system
```

I think at the very least we should simplify this by 
* allowing any key in the data section 
* requiring only the `license.k8s.elastic.co/type: enterprise`  label (type: license is implied)
