### ISSUE TITLE
Facilitate filebeat autodiscovery with hints annotation

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#1978]
When creating Elasticsearch pods we could add a default filebeat annotation 

```yaml
    podTemplate:
      metadata:
        annotations:
          "co.elastic.logs/module": elasticsearch
```
which would allow filebeat [autodiscovery](https://www.elastic.co/guide/en/beats/filebeat/master/configuration-autodiscover-hints.html) to configure the Elasticsearch filebeat module for the Elasticsearch clusters created by ECK which in turn would give us nicely parsed logs:

![Screenshot 2019-10-11 at 14 36 19](https://user-images.githubusercontent.com/697790/66651976-b6276380-ec34-11e9-8dbe-9d5874b71105.png)

and integration with the Stack Monitoring feature in Kibana

![Screenshot 2019-10-11 at 14 38 25](https://user-images.githubusercontent.com/697790/66652016-db1bd680-ec34-11e9-9ee7-cdb80abee629.png)

I see no harm in the additional annotation for users who don't use filebeat or don't use autodiscovery.

A similar annotation exists for Kibana:
```yaml
 podTemplate:                                                                                                                                         
    metadata:                                                                                                                                          
      annotations:                                                                                                                                     
        co.elastic.logs/module: kibana     
```
