### ISSUE TITLE
FATAL  Error: [server.port]: expected value of type [number] but got [string]

### ISSUE THREAD

**Issue by gaetansnl** [elastic/cloud-on-k8s#1987]
## Bug Report
**What did you do?**
I followed quick start
**What did you expect to see?**
Everything deploying correctly
**What did you see instead? Under which circumstances?**
Elasticsearch server and apm are OK.
But Kibana is reporting a strange error ... I did not touch `server.port`. I tried to manually set it in kibana.yaml but I still get the same error. 

**Environment**

* ECK version:

I tried on 0.8, 0.9 and 1.0 beta

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* On premise **YES**
	* Cloud: GKE / EKS / AKS **NO**
	* Kubernetes distribution: Openshift / Rancher / PKS **Rancher**
	
	for each of them please give us the version you are using
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

* Resource definition:
```
apiVersion: kibana.k8s.elastic.co/v1beta1
kind: Kibana
metadata:
  name: analytics
spec:
  version: 7.4.0
  count: 1
  elasticsearchRef:
    name: analytics
```

* Logs:
```
 FATAL  Error: [server.port]: expected value of type [number] but got [string]
```

**Comment by sebgl** [comment]
Hi @gaetansnl,

I cannot manage to reproduce your error.
Can you give us the content of your Elasticsearch resource (the yaml spec)?

Also can you copy the content of the "internal" Kibana configuration that was created by ECK? you can retrieve it with `kubectl get secret analytics-kb-config -o 'go-template={{index .data "kibana.yml"}}' | base64 -D`. Please take care of removing any credentials from the output (there should be a password in there).

**Comment by gaetansnl** [comment]
Hi. Thank you for your quick reply ! @sebgl 
```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: analytics
spec:
  version: 7.4.0
  nodeSets:
    - name: default
      count: 1
      config:
        node.master: true
        node.data: true
        node.ingest: true
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            storageClassName: "openstack-fast"
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
```
```yaml
elasticsearch:
  hosts: https://analytics-es-http.eduniverse-prod.svc:9200
  password: ***************
  ssl:
    certificateAuthorities: /usr/share/kibana/config/elasticsearch-certs/ca.crt
    verificationMode: certificate
  username: eduniverse-prod-analytics-kibana-user
server:
  host: "0"
  name: analytics
  ssl:
    certificate: /mnt/elastic-internal/http-certs/tls.crt
    enabled: true
    key: /mnt/elastic-internal/http-certs/tls.key
xpack:
  monitoring:
    ui:
      container:
        elasticsearch:
          enabled: true
```

**Comment by sebgl** [comment]
Thanks for the outputs. I don't see anything wrong in there.

Does it also happen if you follow the exact [quickstart instructions](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-quickstart.html)? (Including the default names and so on). 

Since you said `I tried to manually set it in kibana.yaml but I still get the same error.`, I'd like to make sure it also happens on any fresh new cluster. Running a fresh quickstart (no other ES/Kibana resources in the cluster) with the latest version of ECK should help us check that.

**Comment by gaetansnl** [comment]
@sebgl I tried everything, and it seems it's related to the namespace I use. I can deploy kibana everywhere except in this namespace... Is it possible that it is conflicting with other applications in the namespace ? Do you know how I can debug that ?

**Comment by anyasabo** [comment]
@gaetansnl does it happen even with the exact quickstart yaml in that namespace? It's especially odd because there's no setting in the config you shared for `server.port`, so it should just be using the default. Looking at the configuration of the pod might show if something else is setting that field, but I'm grasping at straws a bit

**Comment by gaetansnl** [comment]
I think I reproduced
If I remove the server, kibana is starting
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: server
  namespace: test
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    workload: server
---
apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: analytics
  namespace: test
spec:
  version: 7.4.0
  nodeSets:
    - name: default
      count: 1
      config:
        node.master: true
        node.data: true
        node.ingest: true
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            storageClassName: "openstack-fast"
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
---
apiVersion: kibana.k8s.elastic.co/v1beta1
kind: Kibana
metadata:
  name: analytics
  namespace: test
spec:
  version: 7.4.0
  count: 1
  elasticsearchRef:
    name: analytics
```

**Comment by anyasabo** [comment]
Ah that's an interesting addition I hadn't considered. The service [automatically injects env vars into the pod](https://kubernetes.io/docs/concepts/services-networking/service/#environment-variables) in the format of `{SVCNAME}_SERVICE_HOST`,  `{SVCNAME}_SERVICE_PORT`, and, crucially, `{SVCNAME}_PORT`. So since your service is named `server` it becomes `SERVER_PORT` with a value of `tcp://IP:80`, where Kibana is just looking for a number. If you name your service anything else it should work. I was able to reproduce your error with the yaml provided, but changing the name to `server2` allowed it to go through.

I'm not sure how precedence in Kibana configuration works, so it is possible setting the default port explicitly in the config may allow it to work as well if changing the service name is not an option.

**Comment by sebgl** [comment]
Good catch @anyasabo!
@gaetansnl is there a strong requirement for you to name the service `server`? Anything else would work fine I guess.

**Comment by gaetansnl** [comment]
@sebgl No I can rename it, but I was expecting the deployment to not conflict with other services. If it's not possible to prevent kibana from reading these variables, maybe the forbidden names sould be document somewhere, because it's hard to understand what's happening just with the error.

**Comment by charith-elastic** [comment]
Almost all of Kibana configuration keys can be specified as environment variables: https://www.elastic.co/guide/en/kibana/current/docker.html#environment-variable-config. Unfortunately, I don't think it will be practical to comprehensively document all possible names that could clash as both Kubernetes and Kibana projects have high development velocity.

From Kubernetes 1.13 onwards, environment variable injection can be switched off by setting `enableServiceLinks` to `false` in the pod spec. I have raised #2030 to look into this for a future release. In the mean time, if you prefer to keep the service name as `server`, you can add `enableServiceLinks` option to the Kibana manifest as follows:

```yaml
apiVersion: kibana.k8s.elastic.co/v1beta1
kind: Kibana
metadata:
  name: analytics
  namespace: test
spec:
  version: 7.4.0
  count: 1
  elasticsearchRef:
    name: analytics
  podTemplate:
     spec:
        enableServiceLinks: false
```
