### ISSUE TITLE
Quickstart es and kibana yaml examples for airgapped and secured k8s clusters

### ISSUE THREAD

**Issue by mikeh-elastic** [elastic/cloud-on-k8s#1996]
elastricsearch.yml
```
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.2.0
  setVmMaxMapCount: false
  nodes:
  - nodeCount: 1
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          image: docker.internal.repo/elasticsearch/elasticsearch:7.2.0
        securityContext:
          runAsUser: 1000
    config:
      node.master: true
      node.data: true
      node.ingest: true
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        storageClassName: some-storage-class
```
kibana.yml
```
apiVersion: kibana.k8s.elastic.co/v1alpha1
kind: Kibana
metadata:
  name: quickstart
spec:
  version: 7.2.0
  nodeCount: 1
  podTemplate:
    spec:
      containers:
      - name: kibana
        image: docker.internal.repo/kibana/kibana:7.2.1
      securityContext:
        runAsUser: 1000
  elasticsearchRef:
    name: quickstart
  http:
    service:
      spec:
        type: NodePort
```

Tested on 0.9 of the operator.

The changes we needed were stopping the root init container running the sysctl commands.
Using an internal docker repository for the image.

We had to add the numeric id for the container user as it did not work with elasticsearch and kibana as the users listed in the dockerfile and generated an error about a non root uid specified but was unsure that it was not uid 0.

We also had to add a storage class as there was no default storage class configured in this environment.
