### ISSUE TITLE
Setting the spec.http.service.spec.nodePort property in the Elasticsearch CRD does not set the correct port

### ISSUE THREAD

**Issue by glennslaven** [elastic/cloud-on-k8s#1997]
## Bug Report
**What did you do?**
Applied the Elasticsearch CRD with 
```
spec:
  http:
    service:
      spec:
        type: NodePort
        nodePort: 30200
```

**What did you expect to see?**

The `region-es-http` service created as a NodePort with a `nodePort` value of 30200

**What did you see instead? Under which circumstances?**

The `region-es-http` service has a different nodePort value of `31259`, which I'm assuming is just a random one.

**Environment**

* ECK version:

	0.9.0

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* minikube 1.4.0
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

* Resource definition:
```
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: region
  namespace: elastic-system
spec:
  http:
    service:
      spec:
        nodePort: 30200
        type: NodePort
  nodes:
    - config:
        node.data: true
        node.ingest: true
        node.master: true
      nodeCount: 1
      podTemplate:
        spec:
          containers:
            - env:
                - name: ES_JAVA_OPTS
                  value: '-Xms500M -Xmx500M'
              name: elasticsearch
              resources:
                requests:
                  cpu: 0.01
                  memory: 500M
          volumes:
            - emptyDir: {}
              name: elasticsearch-data
  version: 7.4.0

```

* Logs:
```
{"level":"info","ts":1571197080.31713,"logger":"generic-reconciler","msg":"Updating resource","kind":"Service","namespace":"elastic-system","name":"region-es-http"}
```
