### ISSUE TITLE
master node configuration creates custom volume but doesnt use it, uses default 1GB instead

### ISSUE THREAD

**Issue by dan-evolvere** [elastic/cloud-on-k8s#1999]
## Bug Report
**What did you do?**
Created a custom cluster specifying persistent volume sizes of 20GB per master node
**What did you expect to see?**
Master nodes mount 20GB volume and this be visible in monitoring in Kibana
**What did you see instead? Under which circumstances?**
The master nodes create a 20GB PV and bind it, but also create a default 1GB PV and bind that aswell. The 1GB becomes default and shows as the storage for that node in cluster monitoring
**Environment**

* ECK version:

1.0.0beta1

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* On premise 
	* Kubernetes distribution: Rancher
	
	for each of them please give us the version you are using
```
$ kubectl version
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:41:55Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

* Resource definition:
```
apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: elasticsearch-dev
  namespace: elasticsearch
spec:
  version: 7.4.0
  nodeSets:
  - name: masters
    count: 3
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-master
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        storageClassName: vsphere
    config:
      node.master: true
      node.data: false
      node.ingest: false
      node.ml: false
      xpack.ml.enabled: true
      cluster.remote.connect: false
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: 4Gi
              cpu: 2
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms2g -Xmx2g"

  - name: data
    config:
      node.master: false
      node.data: true
      node.ingest: true
      node.ml: true
      node.store.allow_mmap: false
    count: 5
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 200Gi
        storageClassName: vsphere
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: 8Gi
              cpu: 4
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms4g -Xmx4g"
```

* Logs:
