### ISSUE TITLE
`xpack.security.transport.ssl.certificate_authorities` in node config seems to be ignored

### ISSUE THREAD

**Issue by glennslaven** [elastic/cloud-on-k8s#2006]
## Bug Report
**What did you do?**

I'm pretty sure I'm doing something wrong. I'm trying to customise the CA so I can configure a trust relationship with a remote cluster.

I've set this:
```  nodes:
    - nodeCount: 1
      config:
        node.master: true
        node.data: true
        node.ingest: true
        xpack.security.transport.ssl.certificate_authorities:
          - /foo/bar
```
in the elasticsearch CRD

**What did you expect to see?**
The config secret updated with a new setting for `xpack.security.transport.ssl.certificate_authorities`. According to https://github.com/elastic/cloud-on-k8s/issues/962 this should now be configurable.

**What did you see instead? Under which circumstances?**
The config transport block is still the default:
```
    transport:
      ssl:
        certificate: /usr/share/elasticsearch/config/transport-certs/tls.crt
        certificate_authorities:
        - /usr/share/elasticsearch/config/transport-certs/ca.crt
        enabled: "true"
        key: /usr/share/elasticsearch/config/transport-certs/tls.key
        verification_mode: certificate
```
**Environment**

* ECK version:

	0.9.0

* Kubernetes information:

	minikube 1.4.0
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

* Resource definition:
```
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: region
  namespace: elastic-system
spec:
  version: 7.4.0
  http:
    service:
      spec:
        type: NodePort
        ports:
          - name: https
            nodePort: 30200
            port: 9200
            protocol: TCP
            targetPort: 9200
          - name: transport
            nodePort: 30300
            port: 9300
            protocol: TCP
            targetPort: 9300
  nodes:
    - nodeCount: 1
      config:
        node.master: true
        node.data: true
        node.ingest: true
        xpack.security.transport.ssl.certificate_authorities:
          - /foo/bar
      podTemplate:
        spec:
          volumes:
            - name: elasticsearch-data
              emptyDir: {}
          containers:
            - name: elasticsearch
              env:
                - name: ES_JAVA_OPTS
                  value: -Xms500M -Xmx500M
              resources:
                requests:
                  memory: 500M
                  cpu: 0.01
```

* Logs:
```
nil
```
