### ISSUE TITLE
Multiple persistent volumes used for Datanodes

### ISSUE THREAD

**Issue by weeco** [elastic/cloud-on-k8s#2024]
## Bug Report
**What did you do?**

I want to create a zone aware Elastic cluster with 3 master nodes and 4 data nodes (2 in each zone)

**What did you expect to see?**

I expected them starting and readying up with no issues.

**What did you see instead? Under which circumstances?**

I saw 2 out of 4 data nodes pending because of a node volume conflict. I figured out that I have to set `volumeBindingMode: WaitForFirstConsumer` for my "ssd" storage class, which I did and which worked. However apparently each data node in my case creates TWO persistent volumes which I did not expect.

One of the two PVCs uses as expected my SSD storageclass, the other volume is a 1Gi sized PVC for each data node and this one uses the standard storage class. I assume that this PVC is created because I am using an init container

**Environment**

GKE 1.14

* ECK version:

1.0-beta1

* Kubernetes information:

GKE 1.14 with dedicated nodepool for elasticsearch data nodes.

* Resource definition:

**My SSD storageclass:**
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd
provisioner: kubernetes.io/gce-pd
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: pd-ssd
```

**My elasticsearch cluster:**
```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: logging
  namespace: elastic-system
spec:
  version: 7.4.0
  nodeSets:
    - name: master
      count: 3
      config:
        node.master: true
        node.data: false
        node.ingest: false
        cluster.remote.connect: false
      podTemplate:
        spec:
          # Set virtual memory on Kubernetes host, see: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-virtual-memory.html
          initContainers:
            - name: sysctl
              securityContext:
                privileged: true
              command: ["sh", "-c", "sysctl -w vm.max_map_count=262144"]
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: cloud.google.com/gke-nodepool
                        operator: In
                        values:
                          - default-v2
    - name: data-zone-b
      count: 2
      config:
        node.master: false
        node.data: true
        node.ingest: true
        node.attr.zone: europe-west1-b
        cluster.routing.allocation.awareness.attributes: zone
      volumeClaimTemplates:
        - metadata:
            name: logging-es-zb-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 100Gi
            storageClassName: ssd
      podTemplate:
        spec:
          tolerations:
            - effect: NoSchedule
              key: app
              operator: Equal
              value: elasticsearch
          # Set virtual memory on Kubernetes host, see: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-virtual-memory.html
          initContainers:
            - name: sysctl
              securityContext:
                privileged: true
              command: ["sh", "-c", "sysctl -w vm.max_map_count=262144"]
          containers:
            - name: elasticsearch
              # specify resource limits and requests
              resources:
                requests:
                  memory: "10Gi"
                  cpu: 1
                limits:
                  memory: "10Gi"
                  cpu: 4
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: failure-domain.beta.kubernetes.io/zone
                        operator: In
                        values:
                          - europe-west1-b
                      - key: cloud.google.com/gke-nodepool
                        operator: In
                        values:
                          - elasticsearch
    - name: data-zone-c
      count: 2
      config:
        node.master: false
        node.data: true
        node.ingest: true
        node.attr.zone: europe-west1-c
        cluster.routing.allocation.awareness.attributes: zone
      volumeClaimTemplates:
        - metadata:
            name: logging-es-zc-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 100Gi
            storageClassName: ssd
      podTemplate:
        spec:
          tolerations:
            - effect: NoSchedule
              key: app
              operator: Equal
              value: elasticsearch
          # Set virtual memory on Kubernetes host, see: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-virtual-memory.html
          initContainers:
            - name: sysctl
              securityContext:
                privileged: true
              command: ["sh", "-c", "sysctl -w vm.max_map_count=262144"]
          containers:
            - name: elasticsearch
              # specify resource limits and requests
              resources:
                requests:
                  memory: "10Gi"
                  cpu: 1
                limits:
                  memory: "10Gi"
                  cpu: 4
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: failure-domain.beta.kubernetes.io/zone
                        operator: In
                        values:
                          - europe-west1-c
                      - key: cloud.google.com/gke-nodepool
                        operator: In
                        values:
                          - elasticsearch
```

Get Pods, PVC, PV:

```
➜  cortex git:(master) ✗ kubectl get pvc
NAME                                          STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
elasticsearch-data-logging-es-data-zone-b-0   Bound     pvc-d3466d43-f1aa-11e9-a0fd-42010a840043   1Gi        RWO            standard       10m
elasticsearch-data-logging-es-data-zone-b-1   Bound     pvc-d350f84f-f1aa-11e9-a0fd-42010a840043   1Gi        RWO            standard       10m
elasticsearch-data-logging-es-data-zone-c-0   Bound     pvc-d360840a-f1aa-11e9-a0fd-42010a840043   1Gi        RWO            standard       10m
elasticsearch-data-logging-es-data-zone-c-1   Bound     pvc-d36a92c7-f1aa-11e9-a0fd-42010a840043   1Gi        RWO            standard       10m
elasticsearch-data-logging-es-master-0        Bound     pvc-d31f274a-f1aa-11e9-a0fd-42010a840043   1Gi        RWO            standard       10m
elasticsearch-data-logging-es-master-1        Bound     pvc-d32a8fdc-f1aa-11e9-a0fd-42010a840043   1Gi        RWO            standard       10m
elasticsearch-data-logging-es-master-2        Bound     pvc-d3343124-f1aa-11e9-a0fd-42010a840043   1Gi        RWO            standard       10m
logging-es-zb-data-logging-es-data-zone-b-0   Pending                                                                        ssd            10m
logging-es-zb-data-logging-es-data-zone-b-1   Bound     pvc-d34e9a4c-f1aa-11e9-a0fd-42010a840043   100Gi      RWO            ssd            10m
logging-es-zc-data-logging-es-data-zone-c-0   Pending                                                                        ssd            10m
logging-es-zc-data-logging-es-data-zone-c-1   Bound     pvc-d3686db3-f1aa-11e9-a0fd-42010a840043   100Gi      RWO            ssd            10m
➜  cortex git:(master) ✗ kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                                        STORAGECLASS   REASON   AGE
pvc-6b7ba997-ad32-11e9-a18f-42010a840063   100Gi      RWO            Delete           Bound    monitoring/prometheus-remote-remote-prometheus-0             standard                87d
pvc-71d24cc2-a324-11e9-9a4a-42010a840fd8   10Gi       RWO            Delete           Bound    hashicorp/data-consul-server-0                               standard                99d
pvc-71d7b818-a324-11e9-9a4a-42010a840fd8   10Gi       RWO            Delete           Bound    hashicorp/data-consul-server-1                               standard                99d
pvc-71e49e7f-a324-11e9-9a4a-42010a840fd8   10Gi       RWO            Delete           Bound    hashicorp/data-consul-server-2                               standard                99d
pvc-d31f274a-f1aa-11e9-a0fd-42010a840043   1Gi        RWO            Delete           Bound    elastic-system/elasticsearch-data-logging-es-master-0        standard                10m
pvc-d32a8fdc-f1aa-11e9-a0fd-42010a840043   1Gi        RWO            Delete           Bound    elastic-system/elasticsearch-data-logging-es-master-1        standard                10m
pvc-d3343124-f1aa-11e9-a0fd-42010a840043   1Gi        RWO            Delete           Bound    elastic-system/elasticsearch-data-logging-es-master-2        standard                10m
pvc-d3466d43-f1aa-11e9-a0fd-42010a840043   1Gi        RWO            Delete           Bound    elastic-system/elasticsearch-data-logging-es-data-zone-b-0   standard                10m
pvc-d34e9a4c-f1aa-11e9-a0fd-42010a840043   100Gi      RWO            Delete           Bound    elastic-system/logging-es-zb-data-logging-es-data-zone-b-1   ssd                     10m
pvc-d350f84f-f1aa-11e9-a0fd-42010a840043   1Gi        RWO            Delete           Bound    elastic-system/elasticsearch-data-logging-es-data-zone-b-1   standard                10m
pvc-d360840a-f1aa-11e9-a0fd-42010a840043   1Gi        RWO            Delete           Bound    elastic-system/elasticsearch-data-logging-es-data-zone-c-0   standard                10m
pvc-d3686db3-f1aa-11e9-a0fd-42010a840043   100Gi      RWO            Delete           Bound    elastic-system/logging-es-zc-data-logging-es-data-zone-c-1   ssd                     10m
pvc-d36a92c7-f1aa-11e9-a0fd-42010a840043   1Gi        RWO            Delete           Bound    elastic-system/elasticsearch-data-logging-es-data-zone-c-1   standard                10m
➜  cortex git:(master) ✗ kubectl get pods
NAME                       READY   STATUS    RESTARTS   AGE
elastic-operator-0         1/1     Running   0          3h12m
logging-es-data-zone-b-0   0/1     Pending   0          10m
logging-es-data-zone-b-1   1/1     Running   0          10m
logging-es-data-zone-c-0   0/1     Pending   0          10m
logging-es-data-zone-c-1   1/1     Running   0          10m
logging-es-master-0        1/1     Running   0          10m
logging-es-master-1        1/1     Running   0          10m
logging-es-master-2        1/1     Running   0          10m
```
