### ISSUE TITLE
Load Balancer not starting on AWS EKS

### ISSUE THREAD

**Issue by suratpyari** [elastic/cloud-on-k8s#2031]
Hi,

I have been trying ECK on AWS EKS. My pod is running but not able to start load balancer. 

following is the code which I was trying ...
```
apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 6.8.0
  http:
    service:
      spec:
        type: LoadBalancer
``` 

Please let me know how can I debug it and why load balancer is not starting.
