### ISSUE TITLE
Reference docs for Kibana deployment

### ISSUE THREAD

**Issue by weeco** [elastic/cloud-on-k8s#2063]
Hey, I am looking for reference docs to deploy Kibana. I have only found https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-kibana.html .

For instance I am currently trying to disable the need of a user/pass authentication as I use an OAuth proxy in front of it. Therefore my resource looks like this:

```yaml
apiVersion: kibana.k8s.elastic.co/v1beta1
kind: Kibana
metadata:
  name: logging # -kb is suffixed for kibana pods/deployments
  namespace: elastic-system
spec:
  version: 7.4.0
  count: 2
  config:
    xpack.security.enabled: false
    xpack.apm.enabled: false
  elasticsearchRef:
    name: logging
    namespace: elastic-system
  http:
    tls:
      selfSignedCertificate:
        disabled: true
```

For some reason I end up with a basic auth, which btw apparently also causes the readiness probe to fail. More documentation about the Kibana resource is highly appreciated, and if possible someone can tell me how I can disable the user/pass authentication.
