### ISSUE TITLE
Installing Elastic with custom image from Private registry fails

### ISSUE THREAD

**Issue by adurai81** [elastic/cloud-on-k8s#2067]
## Bug Report
**What did you do?**
Successfully installed eck operator on Oracle Cloud Infrastructure (OCI).
Image of Elasticsearch resides in OCI registry.
Elastic installation in Invalid state.

This is how the Elastic image was sourced and stored in OCIR
```
docker pull docker.elastic.co/elasticsearch/elasticsearch:7.3.2
docker tag docker.elastic.co/elasticsearch/elasticsearch:7.3.2 phx.ocir.io/test/elasticsearch/elasticsearch:7.3.2
docker push phx.ocir.io/test/elasticsearch/elasticsearch:7.3.2
```

**What did you expect to see?**
Elasticsearch should be up and running.

**What did you see instead? Under which circumstances?**
```
NAME                   HEALTH   NODES   VERSION   PHASE     AGE
jaeger-elasticsearch                    7.3.2     Invalid   6m
```

**Environment**
Oracle Cloud Infrastructure

* ECK version:

	Downloaded from here: https://download.elastic.co/downloads/eck/1.0.0-beta1/all-in-one.yaml

* Kubernetes information:

	* Cloud: Oracle Cloud Infrastructure
	* Kubernetes distribution: OKE. 
	* Kubernetes version: 1.13.5
	
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T12:38:36Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.5-6+d6ea2e3ed7815b", GitCommit:"d6ea2e3ed7815b9b53d854038041f43b0a98555e", GitTreeState:"clean", BuildDate:"2019-09-19T23:10:35Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Resource definition:
```
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: jaeger-elasticsearch
  namespace: observability
spec:
  image: phx.ocir.io/test/elasticsearch/elasticsearch:7.3.2
  version: 7.3.2
  nodes:
    - nodeCount: 1
      config:
        node.master: true
        node.data: true
        node.ingest: true
```

* Logs:
Pls let me know what logs should be of interest.

* More info:
Verified that the operator is up and running
```
NAME                     READY   STATUS    RESTARTS   AGE
pod/elastic-operator-0   1/1     Running   0          112m

NAME                                READY   AGE
statefulset.apps/elastic-operator   1/1     112m
```

However the state of the ElasticSearch is invalid

```
NAME                   HEALTH   NODES   VERSION   PHASE     AGE
jaeger-elasticsearch                    7.3.2     Invalid   6m
```

**Comment by adurai81** [comment]
The describe shows this -

```
Status:
  Phase:  Invalid
Events:
  Type     Reason      Age                From                      Message
  ----     ------      ----               ----                      -------
  Warning  Validation  31m (x3 over 31m)  elasticsearch-controller  Spec validation failed: at least one nodeSet must be defined
  Warning  Validation  31m (x3 over 31m)  elasticsearch-controller  Elasticsearch needs to have at least one master node
```

**Comment by adurai81** [comment]
Once I switched to `NodeSets` definition, it went through fine.

```
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: jaeger-elasticsearch
  namespace: observability
spec:
  image: phx.ocir.io/test/elasticsearch/elasticsearch:7.3.2
  version: 7.3.2
  nodeSets:
    - name: default
      config:
        node.master: true
        node.data: true
        node.ingest: true
      podTemplate:
        metadata:
          labels:
            jaeger: jaeger-elasticsearch
        spec:
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: 4Gi
                  cpu: 1
                limits:
                  memory: 4Gi
                  cpu: 2
      count: 3
```
