### ISSUE TITLE
nodeSets.count set to -1 causes the operator to panic

### ISSUE THREAD

**Issue by thbkrkr** [elastic/cloud-on-k8s#2068]
Even if it makes no sense, submitting to ECK an Elasticsearch cluster with a nodeSet count set to a negative value causes the operator to crash.

Steps to reproduce:

1. Deploy a _simple_ Elasticsearch cluster:
```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: blurb
spec:
  version: 7.4.0  
  nodeSets:
  - name: default
    count: 1
    config:   
      node.store.allow_mmap: false
```

2. Add a `nodeSets` with `count` set to `-1`:
```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: blurb
spec:
  version: 7.4.0  
  nodeSets:
  - name: default
    count: 1
    config:   
      node.store.allow_mmap: false
  - name: default2
    count: -1
    config:   
      node.store.allow_mmap: false
```

3. Contemplate how the operator crashed:
```go
E1028 10:46:57.818825     615 runtime.go:73] Observed a panic: "makeslice: cap out of range" (...)
goroutine 468 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(...)
        /home/thb/dev/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/runtime/runtime.go:69 +0x7b
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(...)
        /home/thb/dev/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/runtime/runtime.go:51 +0x82
panic(...)
        /home/thb/dev/tools/go/src/runtime/panic.go:679 +0x1b2
github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/sset.PodNames(...)
        /home/thb/dev/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/sset/pod.go:29 +0x83
github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/sset.StatefulSetList.PVCNames(...)
        /home/thb/dev/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/sset/list.go:124 +0x16d
github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/driver.pvcsToRemove(...)
        /home/thb/dev/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/driver/pvc.go:59 +0xa9
github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/driver.GarbageCollectPVCs(...)
        /home/thb/dev/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/driver/pvc.go:38 +0x290
github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/driver.(... 0x1, ...)
        /home/thb/dev/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/driver/nodes.go:56 +0x6ab
github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/driver.(...)
        /home/thb/dev/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/driver/driver.go:234 +0x1aff
github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch.(... ...)
        /home/thb/dev/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/elasticsearch_controller.go:286 +0xaf3
github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch.(...)
        /home/thb/dev/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/elasticsearch_controller.go:221 +0x91b
```

Why? We can't allocate a slice with a negative length:

https://github.com/elastic/cloud-on-k8s/blob/5b2fb3b9976189cba7e285ea9c363c7334dabf6b/pkg/controller/elasticsearch/sset/pod.go#L28-L29
