### ISSUE TITLE
Follow istio's service port requirements

### ISSUE THREAD

**Issue by PaulGrandperrin** [elastic/cloud-on-k8s#2069]
Right now a service port looks like this:
```yaml
  ports:
  - port: 5601
    protocol: TCP
    targetPort: 5601
```
but istio requires to set a name so that it can know about the protocol used on top of TCP:
https://istio.io/docs/setup/additional-setup/requirements/

so, if TLS is used, it should look like that:
```yaml
  ports:
  - name: https
    port: 5601
    protocol: TCP
    targetPort: 5601
```
or if TLS is disabled, like that:
```yaml
  ports:
  - name: http
    port: 5601
    protocol: TCP
    targetPort: 5601
```

same with the es service.
