### ISSUE TITLE
Elasticsearch pod cannot be created when using with PSP

### ISSUE THREAD

**Issue by tapih** [elastic/cloud-on-k8s#2108]
## Bug Report
**What did you do?**

I deployed ECK 1.0.0-beta1 with PSP which configures `readOnlyRootFilesystem: true`, and found that the pod creation failed, though ECK 0.9.0 works with the same PSP.

**What did you expect to see?**

ECK 1.0.0-beta1 can be deployed successfully with the PSP in the "Resource definition" section.

**What did you see instead? Under which circumstances?**

The pod creation of ECK 1.0.0-beta1 failed when running the init container with saying that "ln: cannot remove '/usr/share/elasticsearch/config/users': Read-only file system".

**Environment**

* ECK version: 1.0.0-beta1

* Kubernetes information:

	* Cloud: GKE **with enabling PSP**
	
```
%$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:51:13Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-gke.12", GitCommit:"188432a69210ca32cafded81b4dd1c063720cac0", GitTreeState:"clean", BuildDate:"2019-11-07T19:27:01Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
```

* Resource definition:

I applied the all-in-one manifest mentioned in your Quickstart doc and the following resources(Elasticsearch/RBAC).

```
apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: sample
  namespace: test-es
spec:
  version: 7.4.2
  nodeSets:
  - count: 1
    name: master-nodes
    config:
      node.master: true
      node.data: true
      node.ingest: true
    podTemplate:
      spec:
        containers:
          - name: elasticsearch
            env:
              - name: ES_JAVA_OPTS
                value: "-Xms1g -Xmx1g"
            resources:
              limits:
                memory: 2Gi
              requests:
                memory: 2Gi
        securityContext:
          fsGroup: 1000
          runAsGroup: 1000
          runAsUser: 1000
```

```
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: restricted
spec:
  privileged: false
  # Required to prevent escalations to root.
  allowPrivilegeEscalation: false
  # This is redundant with non-root + disallow privilege escalation,
  # but we can provide it for defense in depth.
  requiredDropCapabilities:
    - ALL
  # Allow core volume types.
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    # Assume that persistentVolumes set up by the cluster admin are safe to use.
    - 'persistentVolumeClaim'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    # Require the container to run without root privileges.
    rule: 'MustRunAsNonRoot'
  seLinux:
    # This policy assumes the nodes are using AppArmor rather than SELinux.
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  readOnlyRootFilesystem: true
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: psp:restricted
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - restricted
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default:psp:restricted
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
roleRef:
  kind: ClusterRole
  name: psp:restricted
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: system:serviceaccounts
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: system:authenticated
```

* Logs:
```
$ kubectlget po -n test-es
NAME                       READY   STATUS       RESTARTS   AGE
sample-es-master-nodes-0   0/1     Init:Error   4          113s

$ kubectl logs -n test-es sample-es-master-nodes-0 -c elastic-internal-init-filesystem
Starting init script
Linking /mnt/elastic-internal/xpack-file-realm/users to /usr/share/elasticsearch/config/users
ln: cannot remove '/usr/share/elasticsearch/config/users': Read-only file system
```
