### ISSUE TITLE
Kibana ghosts in monitoring

### ISSUE THREAD

**Issue by thbkrkr** [elastic/cloud-on-k8s#2113]
Any recreation of a Kibana pod creates a new Kibana instance that can disrupt the monitoring view a bit.

Steps to reproduce:
- Deploy 1 ES+Kibana
<details>
   <summary>YAML manifest</summary>

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: d3m0
spec:
  version: 7.4.2
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
---
apiVersion: kibana.k8s.elastic.co/v1beta1
kind: Kibana
metadata:
  name: d3m0
spec:
  version: 7.4.2
  http:
    service:
      spec:
        type: LoadBalancer
  count: 1
  elasticsearchRef:
    name: d3m0
```
</details>

- Turn on monitoring (https://${KB_IP}:5601/app/monitoring)
- Kill the pod or update the config (to force a pod recreation)
- Go back to see the monitoring again (https://${KB_IP}:5601/app/monitoring#/kibana/instances)

![2019-11-13-164557_1618x1001_scrot](https://user-images.githubusercontent.com/582883/68779781-81446d00-0635-11ea-8d10-d261472b0f04.png)

You see 2 green instances while only one instance is operational.

Important notes: 
- by waiting for a few minutes, the old instance becomes `Offline`
- by adjusting the time window to be after restarting the pod, the old instance disappears

I think it comes from the fact that the uuid is stored on disk and is not persisted when a pod is recreated.

```sh
> kubectl exec d3m0-kb-84cd967b58-jxgjc cat data/uuid 
a60eea7b-1071-45de-acfa-fbfbcdb89401
> kubectl exec d3m0-kb-84cd967b58-gr5w6 cat data/uuid 
60a86abd-a487-444e-9c30-9ef5f7f70128
```

For me, it does not seem to be a bug, it is the normal behaviour even if it can be a bit disturbing the first time.

We could imagine managing the uuid to avoid this, but I do not know if it's worth it.
