### ISSUE TITLE
Unable to run more than 1 node

### ISSUE THREAD

**Issue by booboothefool** [elastic/cloud-on-k8s#2115]
## Bug Report
**What did you do?**
I started off with 1 Elasticsearch node. I changed my yaml count from 1 to 3 because I wanted to add more.

**What did you expect to see?**
3 nodes, all recognized as part of the cluster, and a healthy green status.

**What did you see instead? Under which circumstances?**
2 nodes, 1 doesn't seem to be recognized, and a yellow status.
A 2nd pod came up but not the 3rd, and it's still stuck in yellow status because it doesn't recognize the new 2nd node, it thinks I still have just 1.
In addition, I can't even bring it back down to 1 pod. I set the `count: 1` but the 2nd pod keeps coming back up.
I'm also frequently getting this error when I curl (like every other time, 2nd node is causing issues?):
```
{
  "error": {
    "root_cause": [
      {
        "type": "master_not_discovered_exception",
        "reason": null
      }
    ],
    "type": "master_not_discovered_exception",
    "reason": null
  },
  "status": 503
}
```
```
{
  "error": {
    "root_cause": [
      {
        "type": "cluster_block_exception",
        "reason": "blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];"
      }
    ],
    "type": "cluster_block_exception",
    "reason": "blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];"
  },
  "status": 503
}
```

**Environment**
IBM Cloud Kubernetes

* ECK version:
1.0

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* On premise ? no
	* Cloud: IBM IKS
	* Kubernetes distribution: 
	
	for each of them please give us the version you are using
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5+IKS", GitCommit:"46ea161061498e0ebd9b11d66b3b7dba16fa594d", GitTreeState:"clean", BuildDate:"2019-10-17T13:24:04Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

* Resource definition:
```
apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: elastic
spec:
  version: 7.4.2
  nodeSets:
    - name: default
      count: 3
      config:
        node.master: true
        node.data: true
        node.ingest: true
        node.store.allow_mmap: false
  http:
    tls:
      selfSignedCertificate:
        disabled: true
```

* Logs:
```
kubectl describe elasticsearch elastic
Name:         elastic
Namespace:    default
Labels:       <none>
Annotations:  common.k8s.elastic.co/controller-version: 1.0.0-beta1
              elasticsearch.k8s.elastic.co/cluster-uuid: MfYdMrYSRkutr4vjsKcp3g
              kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"elasticsearch.k8s.elastic.co/v1beta1","kind":"Elasticsearch","metadata":{"annotations":{},"name":"elastic","namespace":"def...
API Version:  elasticsearch.k8s.elastic.co/v1beta1
Kind:         Elasticsearch
Metadata:
  Creation Timestamp:  2019-11-06T22:58:39Z
  Finalizers:
    finalizer.elasticsearch.k8s.elastic.co/observer
    finalizer.elasticsearch.k8s.elastic.co/secure-settings-secret
    finalizer.elasticsearch.k8s.elastic.co/http-certificates-secret
  Generation:        14
  Resource Version:  10268794
  Self Link:         /apis/elasticsearch.k8s.elastic.co/v1beta1/namespaces/default/elasticsearches/elastic
  UID:               4b230e28-adae-4f84-8ba1-21d1e193cda7
Spec:
  Http:
    Service:
      Metadata:
        Creation Timestamp:  <nil>
      Spec:
    Tls:
      Certificate:
      Self Signed Certificate:
        Disabled:  true
  Node Sets:
    Config:
      Node . Data:                true
      Node . Ingest:              true
      Node . Master:              true
      Node . Store . Allow Mmap:  false
    Count:                        3
    Name:                         default
  Update Strategy:
    Change Budget:
  Version:  7.4.2
Status:
  Available Nodes:  2
  Health:           yellow
  Phase:            ApplyingChanges
Events:             <none>
```
```
elastic-es-default-0                            2/2     Running   0          7d7h
elastic-es-default-1                            2/2     Running   0          51m
```

In addition, Kibana never comes up.
```
apiVersion: kibana.k8s.elastic.co/v1beta1
kind: Kibana
metadata:
  name: elastic
spec:
  version: 7.4.2
  count: 1
  elasticsearchRef:
    name: elastic
spec:
  http:
    tls:
      selfSignedCertificate:
        disabled: true
```
```
NAME      HEALTH   NODES   VERSION   AGE
elastic                    7.4.2     14m
```

Please help and let me know if you need any other information.
