### ISSUE TITLE
Ingress rule for Kibana webUI gives http code 502 (bad gateway)

### ISSUE THREAD

**Issue by ledroide** [elastic/cloud-on-k8s#2118]
Hi,
I am unable to make an ingress rule that matches the Kibana service.

Here is the running kibana service :
```bash
$ kubectl get svc kibana-kb-http
NAME             TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
kibana-kb-http   ClusterIP   10.233.28.30   <none>        5601/TCP   23h
```

The kibana service works fine in port-forwarding, from any port, say 8080, to port 5601 - using `kubectl port-forward svc/kibana-kb-http 8080:5601` (`Forwarding from 127.0.0.1:8080 -> 5601`), and kibana's pod logs look good:
```json
{"type":"response","@timestamp":"2019-11-14T13:56:50Z","tags":[],"pid":6,"method":"post","statusCode":200,"req":{"url":"/api/telemetry/report","method":"post","headers":{"host":"localhost:8080","connection":"keep-alive","content-length":"477","accept":"application/json, text/plain, */*","origin":"https://localhost:8080","kbn-version":"7.4.2","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) snap Chromium/78.0.3904.97 Chrome/78.0.3904.97 Safari/537.36","content-type":"application/json;charset=UTF-8","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","referer":"https://localhost:8080/app/kibana","accept-encoding":"gzip, deflate, br","accept-language":"fr,en-US;q=0.9,en;q=0.8"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1","referer":"https://localhost:8080/app/kibana"},"res":{"statusCode":200,"responseTime":468,"contentLength":9},"message":"POST /api/telemetry/report 200 468ms - 9.0B"}
```

So I wanted to create a simple ingress rule, like this :
```yaml
spec:
  rules:
  - host: kibana.monitoring.gailuron.fr
    http:
      paths:
      - path: /
        backend:
          serviceName: kibana-kb-http
          servicePort: 5601
```

But I get an http error code 502 (bad gateway), and this appears on the kibana's pod logs :
```json
{"type":"error","@timestamp":"2019-11-14T13:43:26Z","tags":["connection","client","error"],"pid":6,"level":"error","error":{"message":"139712361707392:error:1408F09C:SSL routines:ssl3_get_record:http request:../deps/openssl/openssl/ssl/record/ssl3_record.c:242:\n","name":"Error","stack":"Error: 139712361707392:error:1408F09C:SSL routines:ssl3_get_record:http request:../deps/openssl/openssl/ssl/record/ssl3_record.c:242:\n"},"message":"139712361707392:error:1408F09C:SSL routines:ssl3_get_record:http request:../deps/openssl/openssl/ssl/record/ssl3_record.c:242:\n"}
```

Searching in issues, I have tried to disable the selfSignedCertificate (no difference) :
```yaml
apiVersion: kibana.k8s.elastic.co/v1beta1
kind: Kibana
metadata:
  name: kibana
spec:
   http:
     tls:
       selfSignedCertificate:
         disabled: true
```

Also tried enable it (no difference) :
```yaml
     tls:
       selfSignedCertificate:
         disabled: false
```

Also tried to define a SERVER_BASEPATH variable this way (gives http code 404) :
```yaml
apiVersion: kibana.k8s.elastic.co/v1beta1
kind: Kibana
metadata:
  name: kibana
spec:
  podTemplate:
    spec:
      containers:
      - name: kibana
         env:
          - name: SERVER_BASEPATH
            value: "/kibana"
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kibana
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/kibana/(.*)$ /$1 break;
      proxy_set_header Authorization "";
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: kibana.monitoring.gailuron.fr
    http:
      paths:
      - path: /kibana
        backend:
          serviceName: kibana-kb-http
          servicePort: 5601
```

What is the right rule for this ingress ? Am I the only one to get this issue ?

Additional info :
```bash
$ kubectl describe $(kubectl get pod -l common.k8s.elastic.co/type=kibana -o name | tail -1) | grep -B2 "Image:"
  kibana:
    Container ID:   docker://6dd4fca9beab1e397ddc3854d870e5471c1211d7abf0183b984f8ae0593516b5
    Image:          docker.elastic.co/kibana/kibana:7.4.2
$
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-17T17:16:09Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
$
$ kubectl describe pod/ingress-nginx-controller-28tk4 -n ingress-nginx | grep -B2 "Image:"
  ingress-nginx-controller:
    Container ID:  docker://cb182e7c7f09881a92795d798c6a212a85cb21f54db6042d09edd065b702fbc7
    Image:         quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.26.1
```

**Comment by thbkrkr** [comment]
Hello,

Your first attempt with the simple rule and disabling tls should be ok.

Here is what works for me on GKE.

- Deploy the ingress-controller:
```sh
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/mandatory.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/cloud-generic.yaml
```

- Deploy Elasticsearch, Kibana and an Ingress:
```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: d3m0
spec:
  version: 7.4.2
  nodeSets:
  - name: default
    count: 3
    config:
      node.store.allow_mmap: false
---
apiVersion: kibana.k8s.elastic.co/v1beta1
kind: Kibana
metadata:
  name: d3m0
spec:
  version: 7.4.2
  count: 1
  elasticsearchRef:
    name: d3m0
  http:
    tls:
      selfSignedCertificate:
        disabled: true       
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kibana-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
 rules:
 - host: kibana.domain.example
   http:
     paths:
     - path: /
       backend:
         serviceName: d3m0-kb-http
         servicePort: 5601
```

- Configure my DNS to map the ingress IP with the host declared in the ingress rule:
```sh
> kubectl get ing 
NAME             HOSTS                   ADDRESS    PORTS   AGE
kibana-ingress   kibana.domain.example   35.0.1.2   80      13m
                                                                                                                                                                                      
> host kibana.domain.example
kibana.domain.example has address 35.0.1.2
```

Note: with multiple Kibana instances, the ingress must have the `nginx.ingress.kubernetes.io/affinity: "cookie"` annotation.

**Comment by ledroide** [comment]
> Your first attempt with the simple rule and disabling TLS should work.

You are right : that works the way you recommend it, now.
I suggest this trick to be documented in the [cloud-on-k8s](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-quickstart.html#k8s-deploy-kibana) page.

Solved. Thank you very much Thibault.

**Comment by zhanghba** [comment]
@ledroide 
how to access kibana with outsite network.

**Comment by ledroide** [comment]
> how to access kibana with outsite network? thanks

@zhanghba : The way @thbkrkr recommends it works for me : 
* disable selfSignedCertificate in your Kibana manifest
* set an Ingress rule that redirects a public FQDN to the path / of your kibana service name and port (depending on how you named it).

If you don't succeed, I can give you my whole Kibana configuration in a gist/snippet.

**Comment by thbkrkr** [comment]
> how to access kibana with outsite network? thanks

If it's only about making Kibana accessible from the public Internet, using an ingress is not mandatory, you can also just declare the `http.service.spec.type` as `LoadBalancer`.

```
spec:
  version: 7.4.2
  http:
    service:
      spec:
        type: LoadBalancer
```

Documentation: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-accessing-elastic-services.html#k8s-allow-public-access.

**Comment by zhanghba** [comment]
@ledroide @thbkrkr 
use ingress successful. on k8s cluster , and through nginx to access the kibana on outside network. Many thanks.

**Comment by krixzZ** [comment]
> * public FQDN

Hi @ledroide 

Can u please share your Kibana configuration? Very thanks in advance.

**Comment by ledroide** [comment]
> Hi @ledroide
> Can u please share your Kibana configuration? Very thanks in advance.

```yaml
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: logging
spec:
  version: 7.7.1
  count: 2
  config:
    elasticsearch.hosts:
      - https://elasticsearch-es-http:9200
    xpack.encryptedSavedObjects.encryptionKey: xxxxxxxxxxxxxxxxxxxx
  podTemplate:
    spec:
      containers:
      - name: kibana
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
          limits:
            memory: 2Gi
            cpu: 1500m
        env:
          - name: ELASTICSEARCH_USERNAME
            value: elastic
          - name: ELASTICSEARCH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: elasticsearch-es-elastic-user
                key: elastic
  http:
    tls:
      selfSignedCertificate:
        disabled: true
    service:
      spec:
        type: LoadBalancer
  elasticsearchRef:
    name: elasticsearch
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kibana
  namespace: logging
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: kibana.logging.kube-prd.prd.questel.fr
    http:
      paths:
      - path: /
        backend:
          serviceName: kibana-kb-http
          servicePort: 5601
```

**Comment by harshitmahapatra** [comment]
Is there way to expose kibana behind a subpath?
I tried the following, but it does not work:

`apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 7.9.2
  count: 1
  elasticsearchRef:
    name: elasticsearch
  podTemplate:
    spec:
        containers:
        - name: kibana
          env:
          - name: "SERVER_BASEPATH"
            value: "/kibana"
          - name: "SERVER_REWRITEBASEPATH"
            value: "true"`

**Comment by anyasabo** [comment]
@harshitmahapatra I think you would need to override the path for the readiness probe in the podtemplate of your kibana resource. Currently it is hardcoded to `/login`.

**Comment by harshitmahapatra** [comment]
@anyasabo  Thank you!

**Comment by mdrideout** [comment]
Just posting an update for anyone using the newer version of [ingress-nginx](https://github.com/kubernetes/ingress-nginx) which has slightly different syntax [(docs)](https://kubernetes.io/docs/concepts/services-networking/ingress/).

With this setup, Kibana is accessible locally at [http://localhost/](http://localhost/), tested on Docker Desktop Kubernetes

**elasticsearch.yaml**
```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: myexample
spec:
  version: 7.14.0
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: 2Gi
                  cpu: 0.25
          volumes:
            - name: elasticsearch-data
              persistentVolumeClaim:
                claimName: elasticsearch-persistent-volume-claim

```

**kibana.yaml**
```yaml
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: myexample
spec:
  version: 7.14.0
  count: 1
  elasticsearchRef:
    name: myexample
    namespace: default
  http:
    tls:
      selfSignedCertificate:
        disabled: true
    service:
      spec:
        type: LoadBalancer
  podTemplate:
    spec:
      containers:
        - name: kibana
          resources:
            requests:
              memory: 0.5Gi
              cpu: 0.25
```

**kibana-ingress.yaml**
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: "localhost"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: myexample-kb-http
                port:
                  number: 5601
```

**Comment by thiDucTran** [comment]
we are using eck 2.8.0 with subpath to access kibana..thanks all for the help ..below is what got us working

`kibana.yaml` . Fixes from https://github.com/elastic/helm-charts/issues/597 is included
```yaml
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic-system
spec:
  version: 8.7.1
  count: 1
  podTemplate:
    spec:
        containers:
        - name: kibana
          env:
          - name: "SERVER_BASEPATH"
            value: "/kibana"
          - name: "SERVER_REWRITEBASEPATH"
            value: "true"
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /kibana/status
              port: 5601
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
  elasticsearchRef:
    name: elasticsearch
    namespace: elastic-system    
  http:
    tls:
      selfSignedCertificate:
        disabled: true
```

`ingress.yaml`
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-signin: https://changeme/oauth2/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: https://changeme/oauth2/auth
  name: kibana-ingress
  namespace: elastic-system
spec:
  ingressClassName: nginx
  rules:
  - host: changeme
    http:
      paths:
      - backend:
          service:
            name: kibana-kb-http
            port:
              name: http
        path: /kibana(/|$)(.*)
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - changeme
    secretName: wildcard-tls
```

**Comment by usersina** [comment]
Helm Charts solution with a subpath at `/kibana`:

- `eck-elasticsearch-values.yaml`

```yaml
# reference: https://github.com/elastic/cloud-on-k8s/blob/main/deploy/eck-stack/charts/eck-elasticsearch/values.yaml

version: 8.12.0
annotations:
  eck.k8s.elastic.co/license: basic
nodeSets:
  - name: default
    count: 1
    podTemplate:
      spec:
        containers:
          - name: elasticsearch
            resources:
              requests:
                memory: 2Gi
                cpu: 1
              limits:
                memory: 4Gi
                cpu: 2
    volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 80Gi
          # storageClassName: managed-nfs-storage
```

- `eck-kibana-values.yaml`

```yaml
# reference: https://github.com/elastic/cloud-on-k8s/blob/main/deploy/eck-stack/charts/eck-kibana/values.yaml

version: 8.12.0
annotations:
  eck.k8s.elastic.co/license: basic
spec:
  elasticsearchRef:
    name: eck-elasticsearch
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  podTemplate:
    spec:
      containers:
        - name: kibana
          env:
            - name: "SERVER_BASEPATH"
              value: "/kibana"
            - name: "SERVER_REWRITEBASEPATH"
              value: "true"
            - name: "SERVER_PUBLICBASEURL"
              value: "http://minikube.test/kibana"
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /kibana/status
              port: 5601
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
```

- `ingress.yaml`

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana-ingress
  namespace: elastic-stack
  annotations:
    # cert-manager.io/cluster-issuer: letsencrypt-production
   # no need for path writing, `SERVER_REWRITEBASEPATH` in Kibana config takes care of it
spec:
  # ingressClassName: public # Value specific to MicroK8s
  # tls:
  #   - hosts:
  #       - minikube.test
  #     secretName: minikube.test
  rules:
    - host: minikube.test
      http:
        paths:
          - path: /kibana
            pathType: ImplementationSpecific
            backend:
              service:
                name: eck-kibana-kb-http
                port:
                  name: http
```


### Installation

- Add the operator to the Helm repository

```bash
helm repo add elastic https://helm.elastic.co
helm repo update

# Show available charts
helm search repo elastic
```

- Install the operator which includes the custom resources definitions

```bash
helm install eck-operator elastic/eck-operator --namespace elastic-system --create-namespace
```

- Install the necessary resources one by one

```bash
kubectl create namespace elastic-stack

helm install eck-elasticsearch elastic/eck-elasticsearch --values ./eck-elasticsearch-values.yaml --namespace elastic-stack
helm install eck-kibana elastic/eck-kibana --values ./eck-kibana-values.yaml --namespace elastic-stack
```

- Get the password for the default `elastic` user

```bash
kubectl get secret eck-elasticsearch-es-elastic-user -n elastic-stack -o=jsonpath='{.data.elastic}' | base64 --decode; echo
```

**Comment by SJFCS** [comment]
No need to turn off the `selfSignedCertificate`, just add an ingress annotation: `nginx.ingress.kubernetes.io/backend-protocol: HTTPS`
```yaml
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
spec:
  version: 8.13.2
  count: 1
  elasticsearchRef:
    name: quickstart
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  name: quickstart-kb-http
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: kibana.domin.com
      http:
        paths:
          - backend:
              service:
                name: quickstart-kb-http
                port:
                  number: 5601
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - kibana.domin.com
      secretName: kibana-server-tls
```

**Comment by younsl** [comment]
I successfully configured Kibana behind an ingress-nginx-controller using [eck-stack](https://github.com/elastic/cloud-on-k8s/tree/main/deploy) 0.15.0.

Ingress Network Architecture:

```mermaid
---
title: Bad Gateway response from ECK Kibana pod
---
flowchart LR
    Client([Client]) 
    NLB["`**NLB**
    Internal`"]
    
    subgraph K8S["Kubernetes Cluster"]
        Service["`**Service**
        LoadBalancer`"]
        IngressPod["`**Pod**
        ingress-nginx`"]
        KibanaPod["`**Pod**
        Kibana`"]
        
        IngressPod --HTTP--> KibanaPod
        KibanaPod --"`Verify
        HTTPS?`"--> KibanaPod
        KibanaPod -.Bad Gateway.-> IngressPod
    end

    Service --Reconcile--> NLB
    
    Client -->|HTTPS| NLB
    NLB --Route--> IngressPod
    IngressPod -.Bad Gateway.-> NLB
    NLB -.Bad Gateway.-> Client
    
    style Client fill:#333,stroke:#fff,color:#fff
    style NLB fill:#333,stroke:#fff,color:#fff
    style IngressPod fill:#333,stroke:#fff,color:#fff
    style KibanaPod fill:#333,stroke:#fff,color:#fff
    style K8S fill:#1a1a1a,stroke:#666,stroke-width:2px,color:#fff

    linkStyle 7 stroke:#ff8c00,stroke-width:1px
    linkStyle 6 stroke:#ff8c00,stroke-width:1px
    linkStyle 2 stroke:#ff8c00,stroke-width:1px

    note1["**Note**: In this diagram, kubernetes service resources was omitted in front of pods for brevity"]
    note1 ~~~ NLB 
    style note1 fill:transparent,color:gray,stroke-width:0px
```


Simply adding the `nginx.ingress.kubernetes.io/backend-protocol: HTTPS` annotation to kibana Ingress resource enables end-to-end HTTPS communication. This single annotation allows the setup to work without requiring complex modifications to Kibana's default readiness probe configuration, which already operate over HTTPS on port 5601.

```yaml
# eck-stack/values_my.yaml (0.15.0)
eck-kibana:
  enabled: true
  elasticsearchRef:
    name: elasticsearch
  config:
    console.ui.enabled: true
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: "/"
      # This annotation is important to support end-to-end HTTPS communication!
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      nginx.ingress.kubernetes.io/service-upstream: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    labels: {}
    pathType: Prefix
    hosts:
      - host: my-kibana.example.com
        path: /
    tls:
      enabled: false
```
