### ISSUE TITLE
Kibana init container image is not set by default

### ISSUE THREAD

**Issue by thbkrkr** [elastic/cloud-on-k8s#2122]
The custom Kibana init containers do not have a default image.

```go
> k describe kb test | tail -1
Warning  ReconciliationError  41s  kibana-controller     
  Reconciliation error: Deployment.apps "test-kb" is invalid: 
    spec.template.spec.initContainers[0].image: Required value
```

#### Manifest to reproduce the error:
```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: test
spec:
  version: 7.4.1
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
---
apiVersion: kibana.k8s.elastic.co/v1beta1
kind: Kibana
metadata:
  name: test
spec:
  version: 7.4.1
  count: 1
  elasticsearchRef:
    name: test
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  podTemplate:
    spec:
      initContainers:
      - name: install-plugins
        command:
        - sh
        - -c
        - bin/kibana-plugin install https://github.com/sivasamyk/logtrail/releases/download/v0.1.31/logtrail-7.4.1-0.1.31.zip'
```

#### What is wrong?

The init containers for Kibana inherit from the default settings only if the keystore is used.

https://github.com/elastic/cloud-on-k8s/blob/3731fa5af7d6efbf5c0caf97c44206e041a56ef0/pkg/controller/kibana/pod/pod.go#L68-L84
