### ISSUE TITLE
ECK from internal registry

### ISSUE THREAD

**Issue by aceeric** [elastic/cloud-on-k8s#2129]
We are using ECK 0.9.0. Our container images are all hosted in an internal RedHat registry, in image streams, in a specific namespace. I would like to be able to specify - in the ECK CSV - the image source for the elasticsearch deployment.

Currently, I *can* specify the operator image as follows:
```
...
  install:
    spec:
      deployments:
      - name: elastic-operator
        spec:
          template:
            spec:
              containers:
              - args:
                ...
                - name: OPERATOR_IMAGE
                  value: docker-registry.default.svc:5000/images/eck-eck-operator:0.9.0
```
I would also like to be able to specify the ES deployment image. Compare Grafana, where the Grafana CSV allows me to specify the image source for the operator, as well as the Grafana deployment itself:
```
...
  install:
    spec:
      deployments:
      - name: grafana-operator
        spec:
          template:
            spec:
              containers:
              - args:
                - --grafana-image=docker-registry.default.svc:5000/images/openshift-origin-grafana
```
Is something similar available for ECK?
Thanks

**Comment by thbkrkr** [comment]
Hi,

You can specify a custom image using the `spec.image` field. Note: you still have to set the `spec.version`.

Example:
```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.4.2
  image: private.registry.io/elasticsearch/elasticsearch:7.4.2
  nodeSets:
  - name: default
    count: 1
    config:
      node.master: true
      node.data: true
      node.ingest: true
```
Documentation: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-custom-images.html
