### ISSUE TITLE
Nodes scheduled on same hosts, not respecting affinity rules

### ISSUE THREAD

**Issue by simonwh** [elastic/cloud-on-k8s#2130]
## Bug Report
I created an elasticsearch cluster with anti-affinity rules based on `kubernetes.io/hostname`. At first scheduling, 3 nodes were correctly scheduled on 3 separate kubernetes host/nodes.

After changing resource request limits and `ES_JAVA_OPTS` and reapplying the yaml, 2/3 nodes were suddenly scheduled on the same host.

**What did you expect to see?**

I expected cluster to keep adhering to the podAntiAffinity rules. I followed the guide from documentation: https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-advanced-node-scheduling.html

**What did you see instead? Under which circumstances?**

2 nodes schedule on same host.

I've tried to change between `requiredDuringSchedulingIgnoredDuringExecution` and `preferredDuringSchedulingIgnoredDuringExecution` with no change after applying yml. 

**Environment**

* ECK version:
v1alpha1

* Kubernetes information:

Baremetal cluster, Rancher. 
3 hosts with SSD disks for elasticsearch, marked with `openebs=true` labels:

```
NAME                       STATUS    ROLES               AGE       VERSION   LABELS
ex41s-1                    Ready     worker              139d      v1.13.5   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,disk=true,failure-domain.beta.kubernetes.io/region=FSN1,hetzner/location=FSN1,kubernetes.io/hostname=ex41s-1,node-role.kubernetes.io/worker=true,openebs=true
ex41s-2                    Ready     worker              132d      v1.13.5   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=FSN1,hetzner/location=FSN1,kubernetes.io/hostname=ex41s-2,node-role.kubernetes.io/worker=true,openebs=true
ex41s-3                    Ready     worker              139d      v1.13.5   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=FSN1,hetzner/location=FSN1,kubernetes.io/hostname=ex41s-3,node-role.kubernetes.io/worker=true
ex52-1                     Ready     worker              137d      v1.13.5   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=HEL1,hetzner/location=HEL1,kubernetes.io/hostname=ex52-1,node-role.kubernetes.io/worker=true,openebs=true
ex52-2                     Ready     worker              140d      v1.13.5   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=,hetzner/location=HEL1,kubernetes.io/hostname=ex52-2,node-role.kubernetes.io/worker=true
```

* Resource definition:
```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: elasticsearch
spec:
  version: 7.2.0
  http:
    tls:
      selfSignedCertificate:
        subjectAltNames:
        - dns: xxx
  nodes:
  - nodeCount: 3
    config:
      node.master: true
      node.data: true
      node.ingest: true
    podTemplate:
      metadata:
        annotations:
          prometheus.io/scrape: "false"
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: openebs
                  operator: In
                  values:
                  - "true"
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    elasticsearch.k8s.elastic.co/cluster-name: elasticsearch
              topologyKey: kubernetes.io/hostname
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms12g -Xmx12g
          resources:
            requests:
              memory: 24Gi
              cpu: 4
            limits:
              memory: 24Gi
              cpu: 6
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: openebs-hostpath-ssd
```

**Comment by barkbay** [comment]
> I've tried to change between requiredDuringSchedulingIgnoredDuringExecution and preferredDuringSchedulingIgnoredDuringExecution with no change after applying yml.

`requiredDuringSchedulingIgnoredDuringExecution` and `preferredDuringSchedulingIgnoredDuringExecution` are not interchangeable.

I think this is the correct syntax for what you want to achieve: 

```yaml
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: openebs
                  operator: In
                  values:
                  - "true"
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                  matchLabels:
                    elasticsearch.k8s.elastic.co/cluster-name: elasticsearch
              topologyKey: kubernetes.io/hostname
```

**Comment by barkbay** [comment]
Also `preferredDuringSchedulingIgnoredDuringExecution` [gives you no guarantee on where the `Pods` are allocated](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#node-affinity):

> while the latter *(preferredDuringSchedulingIgnoredDuringExecution)* specifies preferences that the scheduler will try to enforce but will not guarantee

**Comment by barkbay** [comment]
I'm closing this issue, feel free to reopen if needed.

**Comment by simonwh** [comment]
As stated in the issue, I've tried with `requiredDuringSchedulingIgnoredDuringExecution` (see yaml) which according the the docs:

> To enforce a strict single node per host, specify requiredDuringSchedulingIgnoredDuringExecution instead:
(https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-advanced-node-scheduling.html)

**Comment by anyasabo** [comment]
@simonwh were you able to get it sorted? I saw a notification of a response from you and was attempting to repro it, but looks like it was deleted. For what it's worth I was able to get it to work, but did notice that if the syntax was incorrect it still lets you create it but does not add the correct anti affinity term to the underlying sset (in the beta version at least). This is likely due to a limitation we have with validating pod template specs

**Comment by simonwh** [comment]
Hi @anyasabo, thanks for your response. You are right, I did write a message, but quickly after realized the Elasticsearch resource was reporting some yaml errors that I didn't notice. It worked with the correct syntax:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: elasticsearch
spec:
  version: 7.2.0
  http:
    tls:
      selfSignedCertificate:
        subjectAltNames:
        - dns: xxx
  nodes:
  - nodeCount: 3
    config:
      node.master: true
      node.data: true
      node.ingest: true
    podTemplate:
      metadata:
        annotations:
          prometheus.io/scrape: "false"
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: openebs
                  operator: In
                  values:
                  - "true"
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  elasticsearch.k8s.elastic.co/cluster-name: elasticsearch
              topologyKey: "kubernetes.io/hostname"
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms12g -Xmx12g
          resources:
            requests:
              memory: 24Gi
              cpu: 4
            limits:
              memory: 24Gi
              cpu: 6
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: openebs-hostpath-ssd
```
