### ISSUE TITLE
[e2e] InvalidImageName

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#2150]
Some of our e2e tests are failing because of this:

```
NAMESPACE                  NAME                                                      READY   STATUS             RESTARTS   AGE
e2e-my2yt-elastic-system   e2e-my2yt-global-operator-0                               0/1     InvalidImageName   0          2m51s
e2e-my2yt-ns-operators     e2e-my2yt-ns-operator-0                                   0/1     InvalidImageName   0          2m48s
e2e-my2yt                  eck-e2e-my2yt-nzzkn                                       1/1     Running            0          2m47s
```

```
  containerStatuses:
  - image: docker.elastic.co/eck-snapshot​s/eck-operator:1.0.0-beta1-201​9-11-18-3731fa5
    imageID: ""
    lastState: {}
    name: manager
    ready: false
    restartCount: 0
    state:
      waiting:
        message: 'Failed to apply default image tag "docker.elastic.co/eck-snapshot\u200bs/eck-operator:1.0.0-beta1-201\u200b9-11-18-3731fa5":
          couldn''t parse image reference "docker.elastic.co/eck-snapshot\u200bs/eck-operator:1.0.0-beta1-201\u200b9-11-18-3731fa5":
          invalid reference format'
        reason: InvalidImageName
```
