### ISSUE TITLE
init containers should have request and limit set.

### ISSUE THREAD

**Issue by sanderma** [elastic/cloud-on-k8s#2179]
## Proposal

Set reasonable limits on the default init containers. It should be easy to guess what is needed.

If you run a cluster with pod security policies that enforce this behaviour, the pod isn't scheduled.
As it is hard to change the config of the init containers ([see issue 1617](https://github.com/elastic/cloud-on-k8s/issues/1617)) this is hard to accomplish.

**Environment**

* ECK version:

	1.0.0-beta1

* Kubernetes information:

	* On premise (PKS)

**Deployed Resources** (Note the missing limits)

```yaml
initContainers:
- command:
  - bash
  - -c
  - /mnt/elastic-internal/scripts/prepare-fs.sh
  env:
  - name: POD_IP
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: status.podIP
  - name: POD_NAME
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: metadata.name
  - name: POD_IP
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: status.podIP
  - name: POD_NAME
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: metadata.name
  image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
  imagePullPolicy: IfNotPresent
  name: elastic-internal-init-filesystem
  resources: {}
  securityContext:
    privileged: false
  terminationMessagePath: /dev/termination-log
  terminationMessagePolicy: File
  volumeMounts:
  - mountPath: /mnt/elastic-internal/elasticsearch-config-local
    name: elastic-internal-elasticsearch-config-local
  - mountPath: /mnt/elastic-internal/elasticsearch-plugins-local
    name: elastic-internal-elasticsearch-plugins-local
  - mountPath: /mnt/elastic-internal/elasticsearch-bin-local
    name: elastic-internal-elasticsearch-bin-local
  - mountPath: /mnt/elastic-internal/transport-certificates
    name: elastic-internal-transport-certificates
    readOnly: true
  - mountPath: /mnt/elastic-internal/scripts
    name: elastic-internal-scripts
    readOnly: true
  - mountPath: /usr/share/elasticsearch/data
    name: elasticsearch-data
  - mountPath: /usr/share/elasticsearch/logs
    name: elasticsearch-logs
  - mountPath: /mnt/elastic-internal/elasticsearch-config
    name: elastic-internal-elasticsearch-config
    readOnly: true
  - mountPath: /usr/share/elasticsearch/config/http-certs
    name: elastic-internal-http-certificates
    readOnly: true
  - mountPath: /mnt/elastic-internal/probe-user
    name: elastic-internal-probe-user
    readOnly: true
  - mountPath: /mnt/elastic-internal/unicast-hosts
    name: elastic-internal-unicast-hosts
    readOnly: true
  - mountPath: /mnt/elastic-internal/xpack-file-realm
    name: elastic-internal-xpack-file-realm
    readOnly: true
```
