### ISSUE TITLE
StatefulSet's VolumeClaimTemplates ownerReference cannot be patched from apiVersion v1beta1 to v1

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#2192]
There's a problem with StatefulSets updates when upgrading from ECK using crd v1beta1 to ECK using crd v1 and existing clusters.

To reproduce:
* use the Elasticsearch CRD v1beta1 (only)
* deploy an Elasticsearch cluster
* update to use CRD v1 by applying the new operator manifests
* the reconciliation attempts to update the existing StatefulSets because their VolumeClaimTemplates ownerReference has changed from

```yaml
 "volumeClaimTemplates": [
    {
      "metadata": {
        "creationTimestamp": null,
        "name": "elasticsearch-data",
        "ownerReferences": [
          {
            "apiVersion": "elasticsearch.k8s.elastic.co/v1beta1",
            "blockOwnerDeletion": false,
            "controller": true,
            "kind": "Elasticsearch",
            "name": "elasticsearch-sample",
            "uid": "7c589a2d-11f5-11ea-8528-42010a840041"
          }
        ]
```
to:
```yaml
 "volumeClaimTemplates": [
    {
      "metadata": {
        "creationTimestamp": null,
        "name": "elasticsearch-data",
        "ownerReferences": [
          {
            "apiVersion": "elasticsearch.k8s.elastic.co/v1",   <--------- HERE
            "blockOwnerDeletion": false,
            "controller": true,
            "kind": "Elasticsearch",
            "name": "elasticsearch-sample",
            "uid": "7c589a2d-11f5-11ea-8528-42010a840041"
          }
        ]
```
* it returns the following error, since the `volumeClaimTemplates` section of a StatefulSet cannot be updated:

```
"Failed to apply spec change: StatefulSet.apps 
\"elasticsearch-sample-es-default\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden"
```
