### ISSUE TITLE
Support for remote ES clusters within a single k8s cluster

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#2203]
https://github.com/elastic/cloud-on-k8s/issues/963 removed support for two CRDs we used initially to facilitate remote cluster support. We want to reinstate support for automatic setup of remote cluster relationships within one k8s cluster (setup of remote clusters spanning multiple k8s clusters or ES clusters hosted outside of k8s are beyond the scope of what ECK can do)

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
spec:
  version: 7.5.0
  nodeSets:
  - name: default
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.ml: true
    count: 3
  remoteClusters:
  - name: my-other-cluster
    namespace: my-custom-ns
  - name: yet-another-cluster
    # namespace: default # can be omitted
```

* ECK would configure the CA of `elasticsearch-sample` as one of the CAs in `xpack.security.transport.ssl.certificate_authorities` for `my-other-cluster` and `yet-another-cluster`
* ECK would configure the CA's of `my-other-cluster` and `yet-another-cluster` as two of the trusted CAs for `elasticsearch-sample` in `xpack.security.transport.ssl.certificate_authorities`
* ECK would create `my-other-cluster` and `yet-another-cluster` as [remote clusters](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-remote-clusters.html) in `elasticsearch-sample`

Questions:
* responsibilities and conflicts: are we re-introducing a remote cluster controller for this, that watches subsections of the Elasticseach resource (the `remoteClusters` attribute effectively), or is this going to be reconciled by the regular Elasticsearch controller? 
* where do we persist the additional CA's on "the other side" (in this example  `my-other-cluster` and `yet-another-cluster`)? Annotation, config map or another attribute on the CRD? If we just edit the other CRD to add the CA to the `config` section how do we distinguish between user created manual config and operator created config. We have some precedence for an [annotation driven config ](https://github.com/elastic/cloud-on-k8s/blob/3326d27df95d2393eadcfa068a016f01cff18ae4/pkg/controller/common/association/conf.go)mechnism in APM and Kibana controllers, which seems most consistent to follow here too.

**Comment by anyasabo** [comment]
This also introduces some RBAC concerns. Say the operator is deployed globally, but a user only has permissions in a single namespace. Depending on how we implement this, it may give them access to ES clusters in a different namespace that their user does not have access to.

One potential path I can think of:

- we could ship remote cluster mgmt off by default, and make it clear that enabling it means that the operator's permissions (rather than the user's permissions) define what clusters they can potentially access. So they should use different operators per namespace if that is how they want to restrict access


---

>responsibilities and conflicts: are we re-introducing a remote cluster controller for this, that watches subsections of the Elasticseach resource (the remoteClusters attribute effectively), or is this going to be reconciled by the regular Elasticsearch controller?

it seems reasonable to have this be part of the regular ES reconcile loop but maybe I'm missing something.

>where do we persist the additional CA's on "the other side"?

Can you help me understand in more detail what is required? I don't understand why we would need annotations. The ES docs don't really help clarify the certificate part of the configuration.

I would think that in your example, we have the CA that our ES cluster is using (stored in a secret). And if we set up a remote cluster, we would need to add the CA the remote cluster is using. It looks like the `certificate_authorities` field in the ES config [is a list](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html#_pem_encoded_files_2), so we could either create a new secret or add a new field to an existing secret with the remote cluster's CA, correct?

I could see this tripping us up if say, a remote cluster's CA is changed we also want to reconcile our copy of the CA. We could add another owner reference to the remote CA secret, but not across namespaces :/

**Comment by pebrc** [comment]
> Can you help me understand in more detail what is required? 

The desired configuration is something like this
```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: my-other-cluster
spec:
  image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
  nodeSets:
  - config:
      xpack.security.transport.ssl.certificate_authorities:
      - /usr/share/elasticsearch/config/other/elasticsearch-sample.ca.crt
    count: 3
    name: default
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          volumeMounts:
          - mountPath: /usr/share/elasticsearch/config/other
            name: remote-certs
        volumes:
        - name: remote-certs
          secret:
            secretName: elasticsearch-sample-ca
  version: 7.6.0
```

Consider  a user  configures `elasticsearch-sample` to be have a remote cluster in `my-other-cluster` (my original example), now the Elasticsearch controller could of course go ahead and just reconfigure the CRD for `my-other-cluster` directly, as shown above,  but it that would then also be visible to users and is now indistinguishable from user provided configuration. Instead we could use an annotation to communicate the name of the CA secret to `my-other-cluster` and create the necessary mounts and Elasticsearch configuration without reflecting this in the user provided CRD (similarly to what we do for other aspects of configuration the operator controls)

**Comment by pebrc** [comment]
An idea we discussed offline to future proof the API for remote cluster relationships that go beyond a single k8s cluster (or include ES clusters hosted on different platforms) is to plan ahead for manual specification of a CA secret and an endpoint e.g.:


```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
spec:
  version: 7.5.0
  nodeSets:
  - name: default
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.ml: true
    count: 3
  remoteClusters:
  - name: my-other-cluster
    namespace: my-custom-ns
  - seed_hosts: 
     - http://my-cluster-outside-k8s:9300
     caSecret: 
         name: my-ca
    # namespace: default # can be omitted
```

I am not sure if a nested structure would be a bit clearer (at the price of being more verbose):

```yaml
remoteClusters:
  - internal: 
       name: my-other-cluster
       namespace: my-custom-ns
  - external: 
       seed_hosts: 
       - http://my-cluster-outside-k8s:9300
        caSecret: 
          name: my-ca
```

**Comment by thbkrkr** [comment]
It reminds me of an old brainstorming that was favorable to a nested structure:

```yaml
  remote:
    inCluster:
      name: foo
      namespace: some-namespace
    elasticCloud:
      cloudId: ...
      ???
    externalKubernetesBasedCluster:
      id: asdf
      namespace: asdf
      name: asdf
    bareMetal:
      seedHosts: ...
      caCert: ...
```
https://github.com/elastic/cloud-on-k8s/issues/369#issuecomment-473218863

**Comment by barkbay** [comment]
> Say the operator is deployed globally, but a user only has permissions in a single namespace. Depending on how we implement this, it may give them access to ES clusters in a different namespace that their user does not have access to

👍  [I share your concern](https://github.com/elastic/cloud-on-k8s/issues/369#issuecomment-471431187), the rights of the user are "escalated" to the rights of the operator.

1. I'm not sure we can solve this with some K8S's RBAC ? We would need to associate the first cluster with a `ServiceAccount` _(with an additional field in the ES schema)_ and then check if this `ServiceAccount` has the right role to create an association.
2. With an annotation somewhere on the remote namespace or on the remote cluster: `remote.k8s.elastic.co/allowed-clusters: "ns1/es1,ns2/es2"` ?
3. By requesting a "reciprocal" declaration in both cluster spec ?

`1.` Would be the best one from a K8S pov but I'm not sure this is doable
`2.` and `3.` sound really "hacky"
 
> it seems reasonable to have this be part of the regular ES reconcile loop but maybe I'm missing something.

My first inclination would be to have a dedicated controller that would copy and manage the certificates of the remote clusters. It could live in the namespace operator. Updating the transport CA and the ES configuration would still be done in the ES reconcile loop.

> An idea we discussed offline to future-proof the API for remote cluster relationships that go beyond a single k8s cluster

Yes, we should agree on a flexible schema that should not prevent us to add some new ways to connect to remote clusters.

I think I'm fine with:

```
remoteClusters:
  - internal: 
       name: my-other-cluster
       namespace: my-custom-ns
```

**Comment by sebgl** [comment]
A few thoughts:

* RBAC mostly controls access to resources in the apiServer, but does not control, for example, access to a service in namespace A from a pod in namespace B. If users [set the appropriate network policies](https://kubernetes.io/docs/tasks/administer-cluster/declare-network-policy/), such access will be forbidden.
* However, it indeed still feels wrong that we create and copy over resources (certificates, passwords) from one namespace to another. Associating this permission to a serviceAccount with RBAC permissions feels a bit overwhelming to me. And I can't really see what it would look like. "User foo" in namespace A would have eg. "read/update" access to “Elasticsearch" in namespace B? It sounds like a different kind of permission (read/update the resource) than what we'd like to achieve here. Also I can imagine a user would not have access to Secrets in namespace B, but should still be able to configure cross-cluster access (or ES-Kibana access) from A to B.
* I think I like the spirit of option 2 from Michael, but we could maybe make it a first class citizen of the Elasticsearch resource (I think we don't need it for Kibana, APM, etc. as Elasticsearch is the only resource that is associated/referenced?):

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  # allow ECK to configure resources in other namespaces to access this cluster
  # defaults to Nil (allow all), can be set to `allow: []` (only allow resources in the current namespace)
  crossNamespaceReferences:
      allow: ["namespaceA", "namespaceB"]
  version: 7.5.2
  nodeSets: []
```

To not break backward compatibility, `crossNamespaceReferences` would be `Nil` by default, which allows resources in all ECK-managed namespaces to be associated to the Elasticsearch cluster (current behaviour).
Users who want to restrict that access specify a list of Namespaces. I don't think we need to go at a deeper level ("namespaceA/cluster1", "namespaceA/kibana1"). Isolation by namespace seems to naturally fits Kubernetes.
Additionally we could add a flag at the operator-level to restrict all cross-namespace accesses: `--allow-cross-namespace-references=false` (default to true).

Let's maybe move this discussion to a new issue since it also concerns Kibana and APM, and keep this issue focused on remote clusters?

**Comment by anyasabo** [comment]
Doh, I didn't actually hit the comment button earlier. I'm +1 with seb on Michael's option #2 (add an annotation or field in spec). I'm also in favor of allowing by namespace. We can extend in the future for specific resources if it makes sense. I see what you're saying about it feeling a little hacky, but it also seems like the best option we have.

We would also allow the local namespace by default, correct? Even if users only have access to say, Kibana in namespace A but not Elasticsearch in namespace A, they likely have access to secrets so could still get credentials for ES and connect.

Beats also contain a [Kibana reference](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-configuration.html), so we will likely want this for both kb and es.

Also +1 to splitting this up to a separate elasticsearchRef (and kibanaRef I suppose) issue, though they are quite intertwined.

**Comment by barkbay** [comment]
I think I'll have to revert https://github.com/elastic/cloud-on-k8s/commit/3ca9ede9a0e9671a8f0048944dfd34fca21546f5 in order to build the seeds.

Let me know if it raises some concerns.

**Comment by barkbay** [comment]
I have tried to sum up the work that need to be done:

## Establish a trust relationship
We have to revive the "trust relationship" mechanism. I think it still deserves its own controller, my main argument would be to keep a clean separation of concern: it is about dealing with CA of remote clusters, I think it would not be clean to do that in the reconciliation loop of the local cluster. 

It used to be a CRD. I guess we don't want to do reintroduce it. I think it could be implemented using a regular `Secret`:

```yaml
apiVersion: v1
kind: Secret
metadata:
  labels:
    common.k8s.elastic.co/type: remote-ca
    elasticsearch.k8s.elastic.co/cluster-name: es1
    remotecluster.k8s.elastic.co/namespace: ns2
    remotecluster.k8s.elastic.co/name: es2
  name: ns2-es2-es-remote-ca # This secret contains the CA and the subject name of ns2/es2
  namespace: ns1
  ownerReferences:
  - apiVersion: elasticsearch.k8s.elastic.co/v1 
    blockOwnerDeletion: true
    kind: Elasticsearch
    name: es1 # Secret is owned by the local cluster
stringData:
  ca.crt: <transport ca of ns2/es2>
  subjectName: "*.node.es2.ns2.es.cluster.local"
type: Opaque
```

## Elasticsearch reconciliation loop overview

### Remote CA reconciliation

Elasticsearch controller would manage a new secret with 2 files:
  - `ca.crt`: a concatenation of all the remote CAs
  - `trust.yml`: the trusted subject names

For exemple:

```yaml
apiVersion: v1
kind: Secret
metadata:
  labels:
    common.k8s.elastic.co/type: remote-ca
    elasticsearch.k8s.elastic.co/cluster-name: es1
  name: es1-es-transport-ca-remote
  namespace: ns1
  ownerReferences:
  - apiVersion: elasticsearch.k8s.elastic.co/v1 
    blockOwnerDeletion: true
    kind: Elasticsearch
    name: es1 # Secret is owned by the local cluster
stringData:
  ca.crt: <concatenation of all the remote CAs>
  trust.yml: <see example below>
type: Opaque
```
  
Example of `trust.yml` :

```json
{
	"trust": {
		"subject_name": ["*.node.es1.ns1.es.cluster.local", "*.node.es2.ns2.es.cluster.local"]
	}
}
```

Example of the updated Elasticsearch configuration file:

```yaml  
    transport:
      ssl:
        certificate: /usr/share/elasticsearch/config/node-transport-cert/transport.tls.crt
        certificate_authorities:
        - /usr/share/elasticsearch/config/transport-certs/ca.crt
        - /usr/share/elasticsearch/config/transport-remote-certs/ca.crt # the remote certificate authorities
        enabled: "true"
        key: /usr/share/elasticsearch/config/node-transport-cert/transport.tls.key
        verification_mode: certificate
        trust_restrictions:
          path: /usr/share/elasticsearch/config/transport-remote-certs/trust.yml
```

### Remote cluster reconciliation (i.e. API call to Elasticsearch) overview

1. Compute the list of the expected remote clusters
2. Get the list of the current remote clusters in the settings of the cluster from an annotation _(an annotation would be used here to save some ES API calls)_.
3. Delete remote clusters that are not expected with an API call to Elasticsearch
4. Store the expected remote clusters in the annotation (see 2.)
5. Add the new remote clusters with some API calls to Elasticsearch

Happy to read your thoughts or concerns.
