### ISSUE TITLE
Empty limits are not take into account

### ISSUE THREAD

**Issue by thbkrkr** [elastic/cloud-on-k8s#2207]
Defining an empty limits section in an ES manifest so that the operator does not apply the default limits does not work as explained [here](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-managing-compute-resources.html).

#### Steps to reproduce

Deploy an Elasticsearch cluster with this manifest:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: nolimitx
spec:
  version: 7.5.0
  nodeSets:
  - name: default
    count: 1
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            limits: {}
```

If we look at the ES custom resource, we can see that the `limits` field has been removed:
```json
> k get elasticsearch nolimit -o json | jq '.spec.nodeSets[0].podTemplate.spec'
{
  "containers": [
    {
      "name": "elasticsearch",
      "resources": {}
    }
  ]
}
```

So the pod inherits from the default limit:
```json
> k get pod nolimit-es-default-0 -o json | jq '.spec.containers[0].resources.limits'
{
  "memory": "2Gi"
}
```

This is due to the `omitempty` tag that decorates the `Limits` field: `Limits ResourceList 'json:“limits,omitempty”'`.

**Comment by barkbay** [comment]
I don't understand how this was supposed to work, and embarrassed because I thought I did some tests.

`omitempty` does not seem to be a recent change, the only idea I have in mind so far is to delete the relevant part in the documentation and discuss an other option to let the user explicitly disable the default resources (an annotation ?).

**Comment by thbkrkr** [comment]
I tested with the latest operator (in master) and it works!

So I double-checked that it does not work with the old operators (0.9, 1.0.0-beta1, 1.0.0) and that it is independent of the k8s version. Confirmed.

Now I have to figure out what has changed to make this work again.

**Comment by thbkrkr** [comment]
01437745 is responsable of the change (if `kubectl apply`, not `kubectl create`).

This is because with this code we mutate the `dest` struct (~ the custom resource) to validate, by using it to decode the JSON coming from the annotation where the object has been stored without modification (`resources:{limits:{}}` is there).

https://github.com/elastic/cloud-on-k8s/blob/b8d6d45654bb42519f0910d4e598b4818e2ac36c/pkg/apis/common/v1/validations.go#L20-L23

**Comment by thbkrkr** [comment]
Reminder: we have already had a lot of debate to decide whether or not to set default limit and we have finally decided to set them (#1454).

I think we don't have a lot of options if we want to support disabling the default limit. 

IMO I'm not completely sure it is important to support it. The main use case that we have identified is being able to benefit from a LimitRange (https://github.com/elastic/cloud-on-k8s/issues/1454#issuecomment-519083444). 
Where I doubt is that with a LimitRange, we lose a precise definition of the allocated memory to the JVM and to the container (same as JVM x 2). This makes me tend to think that it is legitimate to accept only an explicit declaration of the memory.

That said, if we want to support disabling the default limit, we could offer to do so:

* an annotation:
```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: c01
  annotations: 
    common.k8s.elastic.co/default-memory-limit: "false"    # <------- 
spec:
  version: 7.5.2
  nodeSets:
  - name: default
    count: 1
```

* a custom `memory` field, even if it goes beyond this issue, (as suggested in https://github.com/elastic/cloud-on-k8s/issues/1454#issuecomment-523982667 and https://github.com/elastic/cloud-on-k8s/issues/1454#issuecomment-533260923):
```sh
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: c01
spec:
  version: 7.5.2
  nodeSets:
  - name: default
    count: 1
    memory: "unlimited"    # <-------
```
