### ISSUE TITLE
Deployer: can't override numeric values

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#2228]
It is not possible to override a numeric value in the deployer configuration.

In the following example the value of `localSsdCount` is changed to `3`:

```yaml
id: gke-dev
overrides:
  clusterName: a-new-cluster
  kubernetesVersion: "1.14"
  gke:
    gCloudProject: my-gcp-project
    localSsdCount: 3
```

It generates the following error:

```
Error: type mismatch on LocalSsdCount field: found float64, expected int64
type mismatch on LocalSsdCount field: found float64, expected int64
```
