### ISSUE TITLE
podTemplate on ElasticSearch CRD is not validated

### ISSUE THREAD

**Issue by prometherion** [elastic/cloud-on-k8s#2256]
## Bug Report

**What did you do?**

Wrongly read the documentation (my bad) and tried to create a cluster as follows:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: redacted
spec:
  version: 7.5.0
  nodeSets:
  - name: default
    count: 3
    podTemplate:
      tolerations:
      - key: sandbox.gke.io/runtime
        operator: Equal
        value: gvisor
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false
```

**What did you expect to see?**

A validation exception but, obviously, this cannot happen since there is no [validating webhook](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/).

**What did you see instead? Under which circumstances?**

The cluster has been created, even tho without tolerations.

**Environment**

* ECK version:

	docker.elastic.co/eck/eck-operator:1.0.0-beta1

* Kubernetes information:

	* Cloud: GKE
	
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-gke.14", GitCommit:"56d89863d1033f9668ddd6e1c1aea81cd846ef88", GitTreeState:"clean", BuildDate:"2019-11-07T19:12:22Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
```

* Resource definition:
 Already reported.

* Logs:

Not relevant.

**Comment by prometherion** [comment]
I see there's just a webhook regarding [certificates](pkg/controller/webhook/webhook_certificates_controller.go) and I know that this could be interpreted like a feature request: however, I saw that there are some issues with the `podTemplate` interpolation like #2207.

JFI are you using any specific framework like OperatorSDK?

**Comment by sebgl** [comment]
> JFI are you using any specific framework like OperatorSDK?

We rely on Kubebuilder & controller-runtime. Which are now also the foundations of OperatorSDK.

> podTemplate on ElasticSearch CRD is not validated

This is indeed a problem :(

Next release of the operator (`1.0.0` GA) will include [OpenAPI validation automatically enforced by the apiserver](https://github.com/elastic/cloud-on-k8s/issues/2044). This should do a basic validation of fields in the spec.

It also includes a [validating webhook](https://github.com/elastic/cloud-on-k8s/issues/1769) to cover more complicated cases such as an Elasticsearch cluster with no master nodes, for example.

This would however not be enough to catch the example above in the podTemplate.
We [discard the podTemplate validation from our CRD](https://github.com/elastic/cloud-on-k8s/blob/master/config/crds/patches/elasticsearch-patches.yaml#L1-L7). The reason is `kubectl apply -f <operator.yaml>` fails because the [resource stored in annotations becomes too big](https://github.com/kubernetes/kubernetes/issues/85840).

Support for [structural schemas](https://kubernetes.io/blog/2019/06/20/crd-structural-schema/) and [pruning](https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20180731-crd-pruning.md) in CRDs should help detect cases where a field is misplaced, but I think would still silently ignore a misplaced field.

The validating webhook implementation available in controller-runtime does not easily give us access to the underlying raw JSON of an object: we get an already parsed version of the resource.

**Comment by prometherion** [comment]
Just an idea: what about, instead, of implementing a map of JSONPatch6902 rules in order to edit the `podTemplate` [as KinD is performing](https://github.com/kubernetes-sigs/kind/blob/master/pkg/apis/config/v1alpha4/types.go#L58)?

**Comment by sebgl** [comment]
@prometherion I'm not sure I understand how this would work in our case and how the user woud use it. Can you detail a bit more what you have in mind and give some examples?

(We currently use `patchesJson6902` with kustomize to [patch our CRDs](https://github.com/elastic/cloud-on-k8s/blob/master/config/crds/patches/kustomization.yaml#L4))

**Comment by prometherion** [comment]
YMMV:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: redacted
spec:
  version: 7.5.0
  nodeSets:
  - name: default
    count: 3
  podTemplateJsonPatch6902:
  - op: add
    path: /spec/tolerations
    value:
    - key: sandbox.gke.io/runtime
      operator: Equal
      value: gvisor
```
