### ISSUE TITLE
tolerations in apmserver

### ISSUE THREAD

**Issue by rjes** [elastic/cloud-on-k8s#2299]
Hello all!

I'm trying to add tolerations to the apm-server object and expects it to work just like the kibana object but it doesn't.
I use the following yaml:
```
apiVersion: apm.k8s.elastic.co/v1beta1
kind: ApmServer
metadata:
  name: apm-server-quickstart
  namespace: elastic-system
spec:
  image: apmserver:7.5.0
  version: 7.5.0
  count: 1
  spec:
    podTemplate:
      spec:
        nodeSelector:
          node.role: platform-services
        tolerations:
          - operator: "Exists"
  secureSettings:
    secretName: apm-secret-settings
  elasticsearchRef:
    name: quickstart
  config:
    output:
      elasticsearch:
        password: "${ES_PASSWORD}"
```
The same principle for for elasticsearch and kibana.

Anyone else that have this issue?

**Comment by thbkrkr** [comment]
Hi Robert,

You have an extra `spec` field in your manifest.

You shouldn't:
```yaml
spec:
  spec:
    podTemplate:
      spec:
```
But:
```yaml
spec:
  podTemplate:
    spec:
```

This works like a charm with the latest `1.0.0-beta1` version of the operator and using this manifest:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: es-apm-sample
spec:
  version: 7.5.0
  nodeSets:
  - name: default
    count: 3
    config:
      # This setting could have performance implications for production clusters.
      # See: https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-virtual-memory.html
      node.store.allow_mmap: false
    podTemplate:
      spec:
        nodeSelector:
          node.role: platform-services
        tolerations:
          - operator: "Exists"
---
apiVersion: apm.k8s.elastic.co/v1beta1
kind: ApmServer
metadata:
  name: apm-apm-sample
spec:
  version: 7.5.0
  count: 1
  elasticsearchRef:
    name: "es-apm-sample"
  podTemplate:
    spec:
      nodeSelector:
        node.role: platform-services
      tolerations:
        - operator: "Exists"
---
apiVersion: kibana.k8s.elastic.co/v1beta1
kind: Kibana
metadata:
  name: kb-apm-sample
spec:
  version: 7.5.0
  count: 1
  elasticsearchRef:
    name: "es-apm-sample"
  podTemplate:
    spec:
      nodeSelector:
        node.role: platform-services
      tolerations:
        - operator: "Exists"
```

```sh
> k get pods -o json | jq '.items[] | {n:.metadata.name, t:.spec.tolerations[]}' -c 
{"n":"apm-apm-sample-apm-server-568d86bbb-k2tq4","t":{"operator":"Exists"}}
{"n":"apm-apm-sample-apm-server-86f4b4dccd-9tcvx","t":{"operator":"Exists"}}
{"n":"es-apm-sample-es-default-0","t":{"operator":"Exists"}}
{"n":"es-apm-sample-es-default-1","t":{"operator":"Exists"}}
{"n":"es-apm-sample-es-default-2","t":{"operator":"Exists"}}
{"n":"kb-apm-sample-kb-c89f44758-l25gv","t":{"operator":"Exists"}}
```
