### ISSUE TITLE
Patching of v1beta1 ES resource with v1 on k8s 1.12 fails

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#2308]
k8s 1.12 running ECK `1.0.0-rc3` upgraded from `v1beta1`

When upgrading what was created in `v1beta1` as 
```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: es-apm-sample
spec:
  version: 7.4.0
  nodeSets:
    - name: default
      count: 3
      config:
        # This setting could have performance implications for production clusters.
        # See: https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-virtual-memory.html
        node.store.allow_mmap: false
```

with 
```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: es-apm-sample
spec:
  version: 7.5.0
  nodeSets:
    - name: default
      count: 3
      config:
        # This setting could have performance implications for production clusters.
        # See: https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-virtual-memory.html
        node.store.allow_mmap: false
```

I run into the following error:

```
Error from server (InternalError): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"elasticsearch.k8s.elastic.co/v1\",\"kind\":\"Elasticsearch\",\"metadata\":{\"annotations\":{},\"name\":\"es-apm-sample\",\"namespace\":\"default\"},\"spec\":{\"nodeSets\":[{\"config\":{\"node.store.allow_mmap\":false},\"count\":3,\"name\":\"default\"}],\"version\":\"7.5.0\"}}\n"}},"spec":{"nodeSets":[{"config":{"node.store.allow_mmap":false},"count":3,"name":"default"}],"version":"7.5.0"}}
to:
Resource: "elasticsearch.k8s.elastic.co/v1, Resource=elasticsearches", GroupVersionKind: "elasticsearch.k8s.elastic.co/v1, Kind=Elasticsearch"
Name: "es-apm-sample", Namespace: "default"
Object: &{map["apiVersion":"elasticsearch.k8s.elastic.co/v1" "kind":"Elasticsearch" "metadata":map["annotations":map["common.k8s.elastic.co/controller-version":"1.0.0-beta1" "elasticsearch.k8s.elastic.co/cluster-uuid":"3S6znhdkQqK72AXerue8ow" "kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"elasticsearch.k8s.elastic.co/v1beta1\",\"kind\":\"Elasticsearch\",\"metadata\":{\"annotations\":{},\"name\":\"es-apm-sample\",\"namespace\":\"default\"},\"spec\":{\"nodeSets\":[{\"config\":{\"node.store.allow_mmap\":false},\"count\":3,\"name\":\"default\"}],\"version\":\"7.4.0\"}}\n"] "creationTimestamp":"2019-12-19T14:19:20Z" "finalizers":["finalizer.elasticsearch.k8s.elastic.co/observer" "finalizer.elasticsearch.k8s.elastic.co/secure-settings-secret" "finalizer.elasticsearch.k8s.elastic.co/http-certificates-secret"] "generation":'\x02' "name":"es-apm-sample" "namespace":"default" "resourceVersion":"6295" "selfLink":"/apis/elasticsearch.k8s.elastic.co/v1/namespaces/default/elasticsearches/es-apm-sample" "uid":"8c7defe8-226a-11ea-a356-42010a8e00ac"] "spec":map["http":map["service":map["metadata":map["creationTimestamp":<nil>] "spec":map[]] "tls":map["certificate":map[]]] "nodeSets":[map["config":map["node.store.allow_mmap":%!q(bool=false)] "count":'\x03' "name":"default" "podTemplate":map["metadata":map["creationTimestamp":<nil>] "spec":map["containers":<nil>]]]] "updateStrategy":map["changeBudget":map[]] "version":"7.4.0"] "status":map["availableNodes":'\x03' "health":"green" "phase":"Ready"]]}
for: "https://gist.githubusercontent.com/barkbay/f42682b17a41a9aca4c041c218d7b631/raw/477a4b4e73bc47d7c3b99b4d2c7b0121c6096ff0/03-update-v1beta1-with-v1.yml": Internal error occurred: no kind "Elasticsearch" is registered for version "elasticsearch.k8s.elastic.co/v1" in scheme "k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go:51"
```
