### ISSUE TITLE
How to disable username and password when deploying kibana on ECK?  Any examples?

### ISSUE THREAD

**Issue by srflaxu40** [elastic/cloud-on-k8s#2334]
How to disable username and password when deploying kibana on ECK?  Any examples? 

 I'm getting the kibana login prompt but would like to disable it permaneantly.

**Comment by sebgl** [comment]
You can authorize anonymous access through the Elasticsearch configuration: https://www.elastic.co/guide/en/elasticsearch/reference/7.5/anonymous-access.html

**Comment by sebgl** [comment]
An example: https://discuss.elastic.co/t/dont-want-to-use-https-and-user-password/202332/2?u=sebgl

**Comment by moritzluedtke** [comment]
This does work for the elastic search nodes but not for Kibana. I get the following error when adding the mentioned properties:
```
FATAL  Error: [config validation of [xpack.security].authc.anonymous]: definition for this key is missing
```

**Comment by FerencoVonMatterhorn** [comment]
@moritzluedtke I get the same error, can you maybe further explain what the problem was ? 

The Code in my kibana deployment yaml: 
`apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elasticsearch
spec:
  version: 7.8.1
  count: 1
  elasticsearchRef:
    name: logging
  config:
    xpack.reporting.kibanaServer.hostname: 0.0.0.0
    elasticsearch.username: elastic
    elasticsearch.ssl.verificationMode: none
    xpack.security.enabled: true
    xpack.security.authc.providers:
      basic.basic1:
        order: 0
        description: "Log in as an Employee"
      anonymous.anonymous1:
        order: 1
        description: "Continue as guest"
        icon: "globe"
        credentials:
          username: "anonymous"
          password: "anonymous"`

and in my ES-Cluster yaml i have these lines in the spec.nodeSets.config : 
`        xpack.security.authc:
          anonymous:
            username: anonymous_user
            roles: monitoring_user`

I'm now stuck at this state for over 2 days, maybe you can help me out 🤦‍♂️😁

**Comment by artificial-aidan** [comment]
I know this is closed, but I ran into this while searching for exact instructions.

Elasticsearch:

```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 8.1.3
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
  - name: default
    count: 1
    config:
      xpack.security.authc:
        anonymous:
          username: anonymous
          roles: superuser
          authz_exception: false
```

kibana:

```
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 8.1.3
  count: 1
  config:
    xpack.security.authc.providers:
      anonymous.anonymous1:
        order: 0
        credentials: "elasticsearch_anonymous_user"
  elasticsearchRef:
    name: elasticsearch
  http:
    tls:
      selfSignedCertificate:
        disabled: true
    service:
      spec:
        ports:
          - name: http
            port: 5601
            targetPort: 5601
```

**Comment by mertyakan** [comment]
Hi, I use bellow example. It's work;

```
annotations:
  eck.k8s.elastic.co/license: basic

version: 7.15.0

nodeSets:
  - name: default
    count: 1
    config:
      node.roles: ["master"]

    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          env:
          - name: xpack.security.enabled
            value: "false"
          - name: READINESS_PROBE_PROTOCOL
            value: http

http:
  tls:
    selfSignedCertificate:
      disabled: true
```

**Comment by air3ijai** [comment]
To enable anonymous auth, we have several options
1. Disable security at all on Elasticsearch side
2. Enable anonymous auth on Elasticsearch and configure Kibana properly

For a second option, config will look like following
**`elasticsearch-values.yaml`**
```yaml
eck-elasticsearch:
  enabled: true
  fullnameOverride: elastic

  annotations:
    eck.k8s.elastic.co/license: basic

  version: 8.12.2

  nodeSets:
  - name: default
    count: 2

    config:
      xpack.security.authc:
        anonymous:
          username: anonymous
          roles: superuser, kibana_admin
          authz_exception: true
```

**`kibana-values.yaml`**
```yaml
eck-kibana:
  enabled: true
  fullnameOverride: elastic

  annotations:
    eck.k8s.elastic.co/license: basic

  spec:
    version: 8.12.2
    count: 2
    elasticsearchRef:
      name: elastic

    config:
      xpack.security.authc.selector.enabled: false
      xpack.security.authc.providers:
        anonymous.anonymous1:
          order: 0
          credentials: elasticsearch_anonymous_user
        basic.basic1:
          order: 1
```

**Result will be the following**
 1. Elasticsearch is accessible over HTTPS but without auth
    ```shell
    curl -k https://localhost:9200
    ```
 2. User will login automatically in Kibana as anonymous user with a full access to Elasticsearch and Kibana.
 3. A login selector is disabled via `xpack.security.authc.selector.enabled: false` but we still see a login button
    <img width="208" alt="Screenshot 2024-03-17 at 21 30 20" src="https://github.com/elastic/cloud-on-k8s/assets/88528265/82f4c4fd-da25-4899-8bf0-097e0a3c3013">
 4. Basic auth option in Kibana is set as a workaround for the known issue - #6417
    ```yaml
            basic.basic1:
              order: 1
    ```
    And if we would like to remove it, we should update `readinessProbe` to use `/status` endpoint
    <details>
    <summary>kibana-values.yaml</summary>

    ```yaml
    eck-kibana:
      enabled: true
      fullnameOverride: elastic

      annotations:
        eck.k8s.elastic.co/license: basic

      spec:
        version: 8.12.2
        count: 2
        elasticsearchRef:
          name: elastic

        config:
          xpack.security.authc.selector.enabled: false
          xpack.security.authc.providers:
            anonymous.anonymous1:
              order: 0
              credentials: elasticsearch_anonymous_user

        podTemplate:
          spec:
            containers:
            - name: kibana
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /status
                  port: 5601
                  scheme: HTTPS
                initialDelaySeconds: 10
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 5
    ```
    </details>
