### ISSUE TITLE
Webhook does not return any error for resources deployed in version v1beta1

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#2355]
To reproduce: 

* Deploy ECK 1.0.0-beta1 (not sure if necessary)
* Deploy ECK 1.0.0-rc4

Apply the following manifest:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: es-apm-sample-invalid
spec:
  version: 7.4.0
  nodeSets:
    - name: default
      count: 3
      config:
        # This setting could have performance implications for production clusters.
        # See: https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-virtual-memory.html
        node.store.allow_mmap: false
        node.master: false
```

The apply should fail, because the webhook detects no master node, but it does not.
Changing `apiVersion: elasticsearch.k8s.elastic.co/v1beta1` to `apiVersion: elasticsearch.k8s.elastic.co/v1` does trigger the webhook correctly.
