### ISSUE TITLE
A performance issue

### ISSUE THREAD

**Issue by ftyuuu** [elastic/cloud-on-k8s#2402]
I use eck to get an es cluster with 5 nodes:

```
NAME                               READY   STATUS    RESTARTS   AGE   IP              NODE         NOMINATED NODE   READINESS GATES
elasticsearch-sample-es-client-0   1/1     Running   0          22m   10.16.215.128   172.24.5.5   <none>           <none>
elasticsearch-sample-es-data-0     1/1     Running   0          22m   10.16.184.218   172.24.5.4   <none>           <none>
elasticsearch-sample-es-data-1     1/1     Running   0          22m   10.16.33.114    172.24.5.7   <none>           <none>
elasticsearch-sample-es-data-2     1/1     Running   0          22m   10.16.215.172   172.24.5.5   <none>           <none>
elasticsearch-sample-es-master-0   1/1     Running   0          22m   10.16.33.108    172.24.5.7   <none>           <none>
```
Then i use es-rally (https://github.com/elastic/rally) to test this cluster, i use the http_logs dataset and only test with the operation of index-append:

```
{
      "name": "index-append",
      "operation-type": "bulk",
      "bulk-size": {{bulk_size | default(5000)}},
      "ingest-percentage": {{ingest_percentage | default(100)}},
      "corpora": "http_logs"
}
```
The challenges is:
```
"schedule": [
        {
          "operation": "delete-index"
        },
        {
          "operation": {
            "operation-type": "create-index",
            "settings": {{index_settings | default({}) | tojson}}
          }
        },
        {
          "name": "check-cluster-health",
          "operation": {
            "operation-type": "cluster-health",
            "index": "logs-*",
            "request-params": {
              "wait_for_status": "{{cluster_health | default('green')}}",
              "wait_for_no_relocating_shards": "true"
            }
          }
        },
        {
          "operation": "index-append",
          "warmup-time-period": 240,
          "clients": {{bulk_indexing_clients | default(30)}}
        }
      ]
```

I performed 2 sets of tests
1、es-cluster-1, set memory request to 8g and set memory limit to 16g, the cr of es cluster is:
```
apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
  namespace: nes-elasticsearch
spec:
  version: 6.6.1
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
    - name: master
      config:
        node.master: true
        node.data: false
        node.ingest: false
      podTemplate:
        metadata:
          labels:
            by: nes1
        spec:
          initContainers:
            - name: sysctl
              securityContext:
                privileged: true
              command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
          containers:
            - name: elasticsearch
              resources:
                requests:
                  **memory: 8Gi**
                  cpu: 8
                limits:
                  memory: 16Gi
                  cpu: 8
              env:
                - name: ES_JAVA_OPTS
                  value: "-Xms4g -Xmx4g"
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: by
                        operator: In
                        values:
                          - nes1
                  topologyKey: kubernetes.io/hostname
      count: 1
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 32Gi
            storageClassName: localstorage-class
    - name: client
      config:
        node.master: false
        node.data: false
        node.ingest: false
      podTemplate:
        metadata:
          labels:
            by: nes2
        spec:
          initContainers:
            - name: sysctl
              securityContext:
                privileged: true
              command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
          containers:
            - name: elasticsearch
              resources:
                requests:
                  **memory: 8Gi**
                  cpu: 8
                limits:
                  memory: 16Gi
                  cpu: 8
              env:
                - name: ES_JAVA_OPTS
                  value: "-Xms4g -Xmx4g"
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: by
                        operator: In
                        values:
                          - nes2
                  topologyKey: kubernetes.io/hostname
      count: 1
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 32Gi
            storageClassName: localstorage-class
    - name: data
      config:
        node.master: false
        node.data: true
        node.ingest: false
      podTemplate:
        metadata:
          labels:
            by: nes3
        spec:
          initContainers:
            - name: sysctl
              securityContext:
                privileged: true
              command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
          containers:
            - name: elasticsearch
              resources:
                requests:
                  **memory: 8Gi**
                  cpu: 8
                limits:
                  memory: 16Gi
                  cpu: 8
              env:
                - name: ES_JAVA_OPTS
                  value: "-Xms4g -Xmx4g"
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    labelSelector:
                      matchExpressions:
                        - key: by
                          operator: In
                          values:
                            - nes3
                    topologyKey: kubernetes.io/hostname
      count: 3
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 32Gi
            storageClassName: localstorage-class
```
2. es-cluster-2, set memory request to 16g and set memory limit to 16g, the cr of es cluster is:
```
apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
  namespace: nes-elasticsearch
spec:
  version: 6.6.1
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
    - name: master
      config:
        node.master: true
        node.data: false
        node.ingest: false
      podTemplate:
        metadata:
          labels:
            by: nes1
        spec:
          initContainers:
            - name: sysctl
              securityContext:
                privileged: true
              command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
          containers:
            - name: elasticsearch
              resources:
                requests:
                  **memory: 16Gi**
                  cpu: 8
                limits:
                  memory: 16Gi
                  cpu: 8
              env:
                - name: ES_JAVA_OPTS
                  value: "-Xms4g -Xmx4g"
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: by
                        operator: In
                        values:
                          - nes1
                  topologyKey: kubernetes.io/hostname
      count: 1
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 32Gi
            storageClassName: localstorage-class
    - name: client
      config:
        node.master: false
        node.data: false
        node.ingest: false
      podTemplate:
        metadata:
          labels:
            by: nes2
        spec:
          initContainers:
            - name: sysctl
              securityContext:
                privileged: true
              command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
          containers:
            - name: elasticsearch
              resources:
                requests:
                  **memory: 16Gi**
                  cpu: 8
                limits:
                  memory: 16Gi
                  cpu: 8
              env:
                - name: ES_JAVA_OPTS
                  value: "-Xms4g -Xmx4g"
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: by
                        operator: In
                        values:
                          - nes2
                  topologyKey: kubernetes.io/hostname
      count: 1
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 32Gi
            storageClassName: localstorage-class
    - name: data
      config:
        node.master: false
        node.data: true
        node.ingest: false
      podTemplate:
        metadata:
          labels:
            by: nes3
        spec:
          initContainers:
            - name: sysctl
              securityContext:
                privileged: true
              command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
          containers:
            - name: elasticsearch
              resources:
                requests:
                  **memory: 16Gi**
                  cpu: 8
                limits:
                  memory: 16Gi
                  cpu: 8
              env:
                - name: ES_JAVA_OPTS
                  value: "-Xms4g -Xmx4g"
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    labelSelector:
                      matchExpressions:
                        - key: by
                          operator: In
                          values:
                            - nes3
                    topologyKey: kubernetes.io/hostname
      count: 3
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 32Gi
            storageClassName: localstorage-class
```
The only difference between options 1 and 2 is the memory request. And in my opinion, the test results of the two es clusters should be similar, but to my surprise, the test results of cluster 1 actually surpassed that of cluster 2. 

The test results for the first cluster are as follows:
```
Metric,Task,Value,Unit
Cumulative indexing time of primary shards,,237.02848333333336,min
Min cumulative indexing time across primary shards,,0.6988333333333333,min
Median cumulative indexing time across primary shards,,2.20315,min
Max cumulative indexing time across primary shards,,41.33778333333333,min
Cumulative indexing throttle time of primary shards,,0,min
Min cumulative indexing throttle time across primary shards,,0,min
Median cumulative indexing throttle time across primary shards,,0,min
Max cumulative indexing throttle time across primary shards,,0,min
Cumulative merge time of primary shards,,102.83716666666666,min
Cumulative merge count of primary shards,,2462,
Min cumulative merge time across primary shards,,0.09638333333333333,min
Median cumulative merge time across primary shards,,0.4202333333333333,min
Max cumulative merge time across primary shards,,19.96398333333333,min
Cumulative merge throttle time of primary shards,,37.86555,min
Min cumulative merge throttle time across primary shards,,0,min
Median cumulative merge throttle time across primary shards,,0.04936666666666667,min
Max cumulative merge throttle time across primary shards,,9.102066666666667,min
Cumulative refresh time of primary shards,,10.1271,min
Cumulative refresh count of primary shards,,3989,
Min cumulative refresh time across primary shards,,0.05076666666666666,min
Median cumulative refresh time across primary shards,,0.08901666666666667,min
Max cumulative refresh time across primary shards,,1.7370166666666667,min
Cumulative flush time of primary shards,,1.0807499999999999,min
Cumulative flush count of primary shards,,105,
Min cumulative flush time across primary shards,,0.00015,min
Median cumulative flush time across primary shards,,0.0002666666666666667,min
Max cumulative flush time across primary shards,,0.25155,min
Total Young Gen GC,,167.965,s
Total Old Gen GC,,4.527,s
Store size,,23.940757057629526,GB
Translog size,,14.749706984497607,GB
Heap used for segments,,97.18114280700684,MB
Heap used for doc values,,0.10915756225585938,MB
Heap used for terms,,83.89048671722412,MB
Heap used for norms,,0.03704833984375,MB
Heap used for points,,5.798449516296387,MB
Heap used for stored fields,,7.346000671386719,MB
Segment count,,607,
**Min Throughput,index-append,272280.74,docs/s
Median Throughput,index-append,280148.48,docs/s
Max Throughput,index-append,289515.88,docs/s**
50th percentile latency,index-append,521.2981887161732,ms
90th percentile latency,index-append,719.708382152021,ms
99th percentile latency,index-append,959.3234547600144,ms
99.9th percentile latency,index-append,1451.1420910730997,ms
99.99th percentile latency,index-append,2035.4542915585687,ms
100th percentile latency,index-append,2158.126129768789,ms
50th percentile service time,index-append,521.2981887161732,ms
90th percentile service time,index-append,719.708382152021,ms
99th percentile service time,index-append,959.3234547600144,ms
99.9th percentile service time,index-append,1451.1420910730997,ms
99.99th percentile service time,index-append,2035.4542915585687,ms
100th percentile service time,index-append,2158.126129768789,ms
error rate,index-append,0.00,%
```
The test results for the second cluster are as follows:
```
Metric,Task,Value,Unit
Cumulative indexing time of primary shards,,286.6269833333333,min
Min cumulative indexing time across primary shards,,0.8321000000000001,min
Median cumulative indexing time across primary shards,,2.7687000000000004,min
Max cumulative indexing time across primary shards,,56.1978,min
Cumulative indexing throttle time of primary shards,,0,min
Min cumulative indexing throttle time across primary shards,,0,min
Median cumulative indexing throttle time across primary shards,,0,min
Max cumulative indexing throttle time across primary shards,,0,min
Cumulative merge time of primary shards,,122.37433333333334,min
Cumulative merge count of primary shards,,2985,
Min cumulative merge time across primary shards,,0.10341666666666667,min
Median cumulative merge time across primary shards,,0.5313,min
Max cumulative merge time across primary shards,,24.218283333333332,min
Cumulative merge throttle time of primary shards,,52.67661666666667,min
Min cumulative merge throttle time across primary shards,,0,min
Median cumulative merge throttle time across primary shards,,0.052816666666666665,min
Max cumulative merge throttle time across primary shards,,11.339049999999999,min
Cumulative refresh time of primary shards,,12.311833333333334,min
Cumulative refresh count of primary shards,,5081,
Min cumulative refresh time across primary shards,,0.053899999999999997,min
Median cumulative refresh time across primary shards,,0.11418333333333333,min
Max cumulative refresh time across primary shards,,1.94125,min
Cumulative flush time of primary shards,,0.8775833333333334,min
Cumulative flush count of primary shards,,110,
Min cumulative flush time across primary shards,,0.00018333333333333334,min
Median cumulative flush time across primary shards,,0.00046666666666666666,min
Max cumulative flush time across primary shards,,0.20653333333333332,min
Total Young Gen GC,,204.664,s
Total Old Gen GC,,5.794,s
Store size,,24.059551434591413,GB
Translog size,,14.876259396784008,GB
Heap used for segments,,101.440185546875,MB
Heap used for doc values,,0.13336944580078125,MB
Heap used for terms,,88.07503509521484,MB
Heap used for norms,,0.037109375,MB
Heap used for points,,5.794868469238281,MB
Heap used for stored fields,,7.399803161621094,MB
Segment count,,608,
**Min Throughput,index-append,209654.95,docs/s
Median Throughput,index-append,214594.19,docs/s
Max Throughput,index-append,219079.85,docs/s**
50th percentile latency,index-append,689.0642456710339,ms
90th percentile latency,index-append,895.1061829924585,ms
99th percentile latency,index-append,1097.3475325480106,ms
99.9th percentile latency,index-append,1432.848638830708,ms
99.99th percentile latency,index-append,3088.582104871771,ms
100th percentile latency,index-append,3185.553685761988,ms
50th percentile service time,index-append,689.0642456710339,ms
90th percentile service time,index-append,895.1061829924585,ms
99th percentile service time,index-append,1097.3475325480106,ms
99.9th percentile service time,index-append,1432.848638830708,ms
99.99th percentile service time,index-append,3088.582104871771,ms
100th percentile service time,index-append,3185.553685761988,ms
error rate,index-append,0.00,%
```

You can see that the test results of cluster 1 are indeed better. Why is this? Can someone help answer this?
