### ISSUE TITLE
Stack monitoring with Metricbeat

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#2415]
Related to #2051 

Three possible approaches to collecting monitoring data from Elastic stack containers come to mind
* via a centrally managed Metricbeat instance 
* via a process running inside the stack (e.g. Elasticsearch) container
* via a sidecar container next to the stack (e.g. Elasticsearch) container

## Central management
* Basically extending on the `DaemonSet` advertised in https://www.elastic.co/guide/en/beats/metricbeat/current/running-on-kubernetes.html
* Most resource effective (one Metricbeat process per k8s node)
* Difficult to configure: 
    * we need to add configuration stanzas to the Metricbeat config files as pods are scheduled on a specific k8s node and remove them again if they get scheduled somewhere else
    * unclear ownership of the configuration files 
    * multiple processes writing concurrently to same `ConfigMap` to add or remove configuration files if we share a `ConfigMap` between e.g. Elasticsearch clusters
    * or alternatively a potentially high number of volume mounts to manage on the Metricbeat pod if we don't share a k8s resource but every stack pod needs mount its own monitoring configuraiton into the Metricbeat pod with a restart of the Metricbeat pod at each such occasion
* Only one output Elasticsearch cluster possible

The disadvantages seem to outweigh the benefits of saving resources.

## In-container Metricbeat process
While this feels like a container anti-pattern at first, the stack seems to be going into that direction starting with version 8.0.0 see https://github.com/elastic/elasticsearch/issues/49399 and https://github.com/elastic/kibana/issues/51224
* Very hacky to do this before the official images support it (we had a similar approach with the shortlived process manager in one of the ECK alpha versions) 
* Would require introduction of a process manager to handle stray child processes
* I would assume that this could be disruptive to existing deployments if we introduce this in a future version of ECK because sizing and resource requests/limits would have been done without this extra process in mind (we could work around this of course by bumping the resources on rollout, but that in itself is also problematic as we might cause rescheduling of nodes etc)

Unless we have support for this in the official Docker containers we should avoid this route.

## Sidecar Metricbeat process

* would the be the most k8s-native way of a running a Metricbeat process alongside each Elastic stack container
* localhost network access from Metricbeat to the stack process (e.g. Elasticsearch)
* Metricbeat shares the same 'fate' as the stack process and follows it around as it is rescheduled etc
* possible for users to configure this today with hand-crafted sidecar 
* Monitoring data can be reporting into different monitoring clusters as needed (because each monitored container is running it's own instance of Metricbeat)
* ECK could add value by automating (here for an Elasticsearch example, see below) most of the steps in https://www.elastic.co/guide/en/elasticsearch/reference/7.5/configuring-metricbeat.html for example: 
   * access to user credentials on the monitoring cluster
   * propagation of certificates for both the monitoring cluster and the monitored cluster
   * turning on stack monitoring in Elasticsearch
* Challenges: 
    * it looks like new certs on certificate rotation are not automatically picked up by Metricbeat
    * `localhost` access requires `localhost` to be a SAN in the generated certificates (or we have to the turn of cert validation in Metricbeat)
    * migration from the current state to the monitored state (additional resources needed for Metricbeat might trigger rescheduling, or cause problems in use cases with local persistent volumes and limited resources on the k8s nodes)

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: my-cluster
spec:
  version: 7.5.0
  http:
    tls:
      selfSignedCertificate:
        subjectAltNames:
        - dns: localhost        
  nodeSets:
  - name: default
    count: 3
    podTemplate:
      metadata:
         annotations:
           "co.elastic.logs/module": elasticsearch
      spec:
        containers:
        - name: metricbeat
          image: docker.elastic.co/beats/metricbeat:7.5.0
          args: [
          "-c", "/etc/metricbeat.yml",
          "-e"
          ]
          env:
          - name: MONITOR_HOST
            value: monitor-es-http.beats
          - name: MONITOR_PORT
            value: "9200"
          - name: MONITOR_USERNAME
            value: elastic
          - name: MONITOR_PASSWORD
            valueFrom:
              secretKeyRef:
                key: elastic
                name: monitor-es-elastic-user
          - name: ELASTICSEARCH_PASSWORD
            valueFrom:
              secretKeyRef:
                key: elastic
                name: my-cluster-es-elastic-user
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
          - name: config
            mountPath: /etc/metricbeat.yml
            readOnly: true
            subPath: metricbeat.yml
          - name: monitor-certs
            mountPath: /mnt/monitor/tls.crt
            readOnly: true
            subPath: tls.crt
          - name: es-certs
            mountPath:  /mnt/elastic/tls.crt
            readOnly: true
            subPath: tls.crt
        volumes:
        - name: config
          configMap:
            name: my-cluster-metricbeat
        - name: monitor-certs
          secret:
            secretName: monitor-es-http-certs-public
        - name: es-certs
          secret:
            secretName: my-cluster-es-http-certs-public
          
---          
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-cluster-metricbeat
  labels:
    k8s-app: metricbeat
data:
  metricbeat.yml: |-
    metricbeat.modules:
    - module: elasticsearch
      metricsets:
        - ccr
        - enrich
        - cluster_stats
        - index
        - index_recovery
        - index_summary
        - ml_job
        - node_stats
        - shard
      period: 10s
      xpack.enabled: true
      hosts: ["https://localhost:9200"]
      username: "elastic" # TODO use monitoring user
      password: ${ELASTICSEARCH_PASSWORD}
      ssl.certificate_authorities: ["/mnt/elastic/tls.crt"]
        

    processors:
      - add_cloud_metadata:
    
    output.elasticsearch:
      hosts: ['https://${MONITOR_HOST:elasticsearch}:${MONITOR_PORT:9200}']
      username: ${MONITOR_USERNAME}
      password: ${MONITOR_PASSWORD}
      ssl.certificate_authorities:
      - /mnt/monitor/tls.crt
```

**Comment by anyasabo** [comment]
My inclination is the central management (and is similar in deployment to e.g. prometheus scrapers). From the link you mentioned, I think we would only be using a deployment for this use case:
>As a single Metricbeat instance created using a Deployment. This instance is used to retrieve metrics that are unique for the whole cluster, such as Kubernetes events or kube-state-metrics.

There's no need to have a daemon set for this use case since it doesn't need to run on every node or do anything local to the node.

I also don't think we would need to modify the metricbeat configuration regularly if we can get autodiscover working correctly. I had some difficulty using it with label selectors in the past, but it _should_ work.

I don't remember if we can expose prometheus metrics in ES without auth, but that would indeed require modifying the metricbeat deployment whenever we want to make changes and be a pain. IMO we would want to expose them without auth.

**Comment by pebrc** [comment]
I am going to use Elasticsearch as the example below but stack monitoring applies to other Elstic stack products as well of course. 

> I think we would only be using a deployment for this use case: 
> There's no need to have a daemon set for this use case since it doesn't need to run on every node or do anything local to the node.

Hm this might be a misunderstanding, but this issue is about the monitoring feature build into the different stack products. So for Elasticsearch, the monitoring you enable via `xpack.monitoring.collection.enabled` see https://www.elastic.co/guide/en/elasticsearch/reference/7.5/configuring-metricbeat.html For stack monitoring via Metricbeat you have to run Metricbeat on each node 

![](https://www.elastic.co/guide/en/elasticsearch/reference/7.5/monitoring/images/metricbeat.png)

> I also don't think we would need to modify the metricbeat configuration regularly if we can get autodiscover working correctly. I had some difficulty using it with label selectors in the past, but it should work.

If we were to use a shared Metricbeat instance on each k8s node we would need to modify the configuration whenever a new Elasticsearch cluster is created or removed or rescheduled to another node.
Also I don't think autodiscover would work here, in order to talk to Elasticsearch we need credentials and certificates and I don't think we can configure those via autodiscovery because we need to actually mount the relevant secrets into the Metricbeat pods. 

> I don't remember if we can expose prometheus metrics in ES without auth

I don't think you can expose any Prometheus metrics in ES without third-party tooling.

**Comment by exekias** [comment]
> Also I don't think autodiscover would work here, in order to talk to Elasticsearch we need credentials and certificates and I don't think we can configure those via autodiscovery because we need to actually mount the relevant secrets into the Metricbeat pods.

As a note here, this is something we have been thinking on for a while and we may start working on it soon, but we don't have a target release for it yet.

**Comment by anyasabo** [comment]
One hybrid option that may make sense: one metricbeat deployment per Elasticsearch cluster. That way each cluster can output to a separate monitoring cluster if necessary. We don't need to regularly modify the secrets mounted into metricbeat since it is just monitoring one cluster. For the metricbeat configuration, we can also use autodiscover for that cluster's labels so once it is created we shouldn't need to modify it. It also lets us use less resources than we would using a sidecar and is straightforward to implement.

I'm not sure if there's a limit on how many hosts metricbeat can realistically scrape at once.

Another downside is that it is still using more resources than if we had one metricbeat deployment for multiple Elasticsearch clusters (the "Central management" option in Peter's original post). This may be significant for users with many ES clusters.

Maybe it's worth picking one of the simpler to implement options now, and we can potentially alter it later to allow more density?

**Comment by david-kow** [comment]
Do we have any data on the metricbeat resource consumption? It seems that this would get us more insights about how much we really save on not doing sidecar approach.

As for the deployment per cluster, I have mixed feelings, mostly around scalability and spof. Are we sure we can handle any cluster size this way? Would pod running that metricbeat become noisy at some scale?

I think if ES is introducing a solution to this problem in 8.0 we should follow that solution. As to the pre-8.0 versions (for which, I assume, we also want to introduce this) I'd be for doing the sidecar as it seems most straightforward and "native".

**Comment by bleskes** [comment]
@pebrc if we end up doing anything else but using the bundled beats in the stack images, can you ping me? I’m not saying it’s no good but I would like to understand the reasons in that case.

**Comment by anyasabo** [comment]
>In-container Metricbeat process

>While this feels like a container anti-pattern at first, the stack seems to be going into that direction starting with version 8.0.0 see elastic/elasticsearch#49399 and elastic/kibana#51224

>    Very hacky to do this before the official images support it (we had a similar approach with the shortlived process manager in one of the ECK alpha versions)

Agreed this feels like a container anti-pattern. The primary argument in favor of it that I read in any of the stack issues was that it is easier for people to deploy, and remains similar to the in-stack monitoring collection configuration. I didn't see any discussion of the cons in the list, so here are some of the reasons why I'd prefer to keep beats and stack containers separate at least for Kubernetes deployments:
- readiness / liveness checks are per container and much easier to reason about as relevant to one process. If you have multiple independent processes you care about in the same container it becomes harder to reason about. What happens if you need to restart just the metricbeat process? What happens if metricbeat dies but ES continues successfully? Some adjacent discussion in the ES issue [here](https://github.com/elastic/elasticsearch/issues/49399#issuecomment-561756320).
- simplified logging. Centralized logging often tags logs by the container, so if I want to see elasticsearch logs it's common to search for `container:elasticsearch`, and likewise for beats searching for `container:metricbeat`. If they're all bundled together it makes sorting through stack and instrumentation logs difficult. There are similar issues using `kubectl logs`.
- k8s allows per container resource requests/limits. most in-cluster metrics and monitoring are also granular to the container level, not to the process. having both in one container would mean we need to set combined resource requests/limits for both the stack and for beats, and we cannot observe resource utilization for either independently

Note that these are just arguments against having them in the same container -- we could still have them as separate containers in the same pod (so access to the same namespace, fs, etc).

And to reiterate Peter's point, we would only be able to use the in-container method in >=8.0, we would still need some method to support earlier versions.

I don't think the ease of deployment is a very strong argument for adopting in-container metricbeats for ECK, since adding a sidecar results in a very similar end state (one metricbeat/ES node, access to the same namespace/fs) and is pretty straightforward for us to implement.

**Comment by sebgl** [comment]
Is there a particular reason for us to rely on Metricbeat for stack monitoring?

IIUC, stack monitoring in the current stack version can be done through exporters running in Elasticsearch. Which in future Elasticsearch versions may be replaced by Metricbeat.

Isn't it simpler for us to just use that feature instead of deploying Metricbeat in our own way?

Users can already configure Elasticsearch the following way:

```yaml
xpack.monitoring.collection.enabled: true
xpack.monitoring.exporters:
  id1:
    type: http
    host: ["https://es-mon1:9200", "https://es-mon2:9200"]
    auth:
      username: remote_monitoring_user
      password: YOUR_PASSWORD
    ssl:
      truststore.path: /path/to/file
      truststore.password: password
```

If we want to simplify this bit of configuration, I guess we could propose something like the following in the Elasticsearch resource:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.5.2
  monitoring:
    enable: true
    exporters:
      elasticsearchRef:
        namespace: monitoring-ns
        name: my-monitoring-cluster
  nodeSets:
  - name: default
    count: 1
```

If Elasticsearch runs Metricbeat internally in future versions I don't think that would impact us in a meaningful way, we would probably just setup a different ES configuration internally instead, but maybe keep the same ES resource.
