### ISSUE TITLE
Running Beats for k8s monitoring

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#2417]
Relates to #2051 

Should ECK support running Beats on k8s: 

Two main options come to mind:
* create a Helm chart or similar YAML packaging that deploys for example Metricbeat and Filebeat alongside ECK
* support *beats as first class objects in ECK via a CRD

```yaml
apiVersion: beats.k8s.elastic.co/v1beta1
kind: Filebeat
metadata:
  name: ""
  namespace: ""
spec:
  config:
    inline: {}   # we use inline config for all other resources but with structural schema around the corner
    configMap: "" # we might want to support just a ConfigMap reference
  deamonSet:
    template: {}  # give user the ability to template the spec for the DaemonSet similar to what we do for all other resources
  elasticsearchRef:
    name: ""
    namespace: ""
  version: 7.5.0
---
apiVersion: beats.k8s.elastic.co/v1beta1
kind: Metricbeat
metadata:
  name: ""
  namespace: ""
spec:
  config:
    inline: {}
    configMap: ""
  modules:
    inline: {}
    configMap: ""
  deployment:
    template: {}
  deamonSet:
    template: {}
  elasticsearchRef:
    name: ""
    namespace: ""
  version: 7.5.0
```

The main motivation for involving ECK in the deployment of Beats is that it can add value by automating tedious or error prone aspects of configuring Beats. For example:

* ECK could automatically configure the necessary certificates to access a monitoring Elasticsearch cluster 
* ECK could automated user setup for the various beats
* ECK could make sure Beats are rotated if configuration changes happen that are not automatically picked up by Beats. It seems like this is the case for certificate rotation (to be verified)

With that said we could also explore a third option which would be to keep Beats separate from ECK but to facilitate integration for example with a [`MutatingAdmissionWebhook`](https://github.com/elastic/cloud-on-k8s/issues/2418) that injects user credentials and Elasticsearch certificates into arbitrary containers as needed, which could be used to inject these credentials into Beats containers.
