### ISSUE TITLE
How to disable probe?

### ISSUE THREAD

**Issue by srflaxu40** [elastic/cloud-on-k8s#2427]
It seems that kibana does not come up for me when I disable authentication to kibana.  Is there an issue with this?  I extended the probe readiness time but it seems like it does not fix anything.

```
apiVersion: kibana.k8s.elastic.co/v1beta1
kind: Kibana
metadata:
  name: test-kibana
spec:
  containers:
    - name: test-kibana
      image: "{{ .Values.image.repository }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      resources:
        requests:
          memory: 1Gi
          cpu: 0.5
        limits:
          memory: 2Gi
          cpu: 2
      env:
      - name: READINESS_PROBE_TIMEOUT
        value: "1000"
  version: {{ .Values.kibana_version }}
  count: 1
  config:
    xpack.security.enabled: false    
  elasticsearchRef:
    name: test-elasticsearch
  http:
    tls:
      selfSignedCertificate:
        disabled: true
```

```
jknepper@Johns-MacBook-Pro [~/test-solutions/testhub/try-deploy/scripts/kubernetes]kubectl logs -f test-kibana-kb-5994c97c4f-hkb48
{"type":"log","@timestamp":"2020-01-14T23:57:35Z","tags":["info","plugins-service"],"pid":6,"message":"Plugin \"security\" is disabled."}
{"type":"log","@timestamp":"2020-01-14T23:57:35Z","tags":["info","plugins-system"],"pid":6,"message":"Setting up [3] plugins: [translations,inspector,data]"}
{"type":"log","@timestamp":"2020-01-14T23:57:35Z","tags":["info","plugins","translations"],"pid":6,"message":"Setting up plugin"}
{"type":"log","@timestamp":"2020-01-14T23:57:35Z","tags":["info","plugins","data"],"pid":6,"message":"Setting up plugin"}
{"type":"log","@timestamp":"2020-01-14T23:57:35Z","tags":["info","plugins-system"],"pid":6,"message":"Starting [2] plugins: [translations,data]"}
{"type":"log","@timestamp":"2020-01-14T23:58:03Z","tags":["info","optimize"],"pid":6,"message":"Optimizing and caching bundles for graph, monitoring, space_selector, ml, dashboardViewer, apm, code, maps, canvas, infra, siem, uptime, kibana, stateSessionStorageRedirect, status_page and timelion. This may take a few minutes"}
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
```

**Comment by charith-elastic** [comment]
We don't recommend switching off xpack security and the operator works with the assumption that it is enabled. If you do want to customise the container, it should be done using the `podTemplate` and the container name must be `kibana` (see https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-kibana.html#k8s-kibana-pod-configuration). For example:

```yaml
apiVersion: kibana.k8s.elastic.co/v1beta1
kind: Kibana
metadata:
  name: test-kibana
spec:
  version: 7.5.0
  count: 1
  elasticsearchRef:
    name: test-elasticsearch
  podTemplate:
    spec:
      containers:
        - name: kibana
          resources:
            requests:
              memory: 1Gi
              cpu: 0.5
            limits:
              memory: 2Gi
              cpu: 2.0
          readinessProbe:
            tcpSocket:
              port: 5601
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
  http:
    tls:
      selfSignedCertificate:
        disabled: true
```

Please note that disabling plugins triggers an optimisation job in Kibana that may require more memory than normal. If you see `OOMKilled` messages, you will need to temporarily increase the memory limit until the optimisation job is complete.
