### ISSUE TITLE
Mitigating CrashLoop because of lacking HDD space

### ISSUE THREAD

**Issue by weeco** [elastic/cloud-on-k8s#2450]
## Bug Report
**What did you do?**

One of my Elasticsearch nodes apparently consumed all it's available HDD space. It is stuck in a crashloop back off and says `"Suppressed: java.io.IOException: No space left on device",` in the container logs.

**What did you expect to see?**

This behaviour was kinda expected. However now that this has happened I am not sure how I should mitigate this. I don't need the old data, so I could actually delete it - which seems to be impossible because the pod immediately crashes after starting it.

The other option for me would be increasing the persistent volume size. Apparently thhis is forbidden / not supported when changing the volume claim template in the `Elasticsearch` custom resource.

What am I supposed to do to get my cluster in a healthy state again in such a situation?

**Environment**

GKE

* ECK version:

	1.0.0

* Kubernetes information:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-20T04:49:16Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-gke.2", GitCommit:"0f206d1d3e361e1bfe7911e1e1c686bc9a1e0aa5", GitTreeState:"clean", BuildDate:"2019-11-25T19:35:58Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

* Resource definition:
```
apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: logging
  namespace: elastic-system
spec:
  version: 7.4.2
  nodeSets:
    - name: master
      count: 3
      config:
        node.master: true
        node.data: false
        node.ingest: false
        cluster.remote.connect: false
        xpack.monitoring.enabled: true
        xpack.monitoring.collection.enabled: true
        xpack.security.authc.anonymous.username: anonymous
        xpack.security.authc.anonymous.roles: superuser
        xpack.security.authc.anonymous.authz_exception: true
      podTemplate:
        spec:
          # Set virtual memory on Kubernetes host, see: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-virtual-memory.html
          initContainers:
            - name: sysctl
              securityContext:
                privileged: true
              command: ["sh", "-c", "sysctl -w vm.max_map_count=262144"]
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: cloud.google.com/gke-nodepool
                        operator: In
                        values:
                          - default-v2
    - name: data-zone-b
      count: 2
      config:
        node.master: false
        node.data: true
        node.ingest: true
        node.attr.zone: europe-west1-b
        cluster.routing.allocation.awareness.attributes: zone
        xpack.monitoring.enabled: true
        xpack.monitoring.collection.enabled: true
        xpack.security.authc.anonymous.username: anonymous
        xpack.security.authc.anonymous.roles: superuser
        xpack.security.authc.anonymous.authz_exception: true
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 100Gi
            storageClassName: ssd
      podTemplate:
        spec:
          tolerations:
            - effect: NoSchedule
              key: app
              operator: Equal
              value: elasticsearch
          # Set virtual memory on Kubernetes host, see: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-virtual-memory.html
          initContainers:
            - name: sysctl
              securityContext:
                privileged: true
              command: ["sh", "-c", "sysctl -w vm.max_map_count=262144"]
          containers:
            - name: elasticsearch
              # specify resource limits and requests
              resources:
                requests:
                  memory: "10Gi"
                  cpu: 1
                limits:
                  memory: "10Gi"
                  cpu: 4
              env:
                - name: "ES_JAVA_OPTS"
                  value: "-Xms2g -Xmx2g"
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: failure-domain.beta.kubernetes.io/zone
                        operator: In
                        values:
                          - europe-west1-b
                      - key: cloud.google.com/gke-nodepool
                        operator: In
                        values:
                          - elasticsearch
    - name: data-zone-c
      count: 2
      config:
        node.master: false
        node.data: true
        node.ingest: true
        node.attr.zone: europe-west1-c
        cluster.routing.allocation.awareness.attributes: zone
        xpack.monitoring.enabled: true
        xpack.monitoring.collection.enabled: true
        xpack.security.authc.anonymous.username: anonymous
        xpack.security.authc.anonymous.roles: superuser
        xpack.security.authc.anonymous.authz_exception: true
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 100Gi
            storageClassName: ssd
      podTemplate:
        spec:
          tolerations:
            - effect: NoSchedule
              key: app
              operator: Equal
              value: elasticsearch
          # Set virtual memory on Kubernetes host, see: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-virtual-memory.html
          initContainers:
            - name: sysctl
              securityContext:
                privileged: true
              command: ["sh", "-c", "sysctl -w vm.max_map_count=262144"]
          containers:
            - name: elasticsearch
              # specify resource limits and requests
              resources:
                requests:
                  memory: "10Gi"
                  cpu: 1
                limits:
                  memory: "10Gi"
                  cpu: 4
              env:
                - name: "ES_JAVA_OPTS"
                  value: "-Xms2g -Xmx2g"
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: failure-domain.beta.kubernetes.io/zone
                        operator: In
                        values:
                          - europe-west1-c
                      - key: cloud.google.com/gke-nodepool
                        operator: In
                        values:
                          - elasticsearch
```
