### ISSUE TITLE
multi-instance clusters fails due to invalid certificate

### ISSUE THREAD

**Issue by KlavsKlavsen** [elastic/cloud-on-k8s#2527]
Setting up a cluster using this yaml:
```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.5.1
  nodeSets:
  - name: default
    count: 3
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: csi-cephfs
```
Gets 3 nodes up in "running" -but healtcheck fails due to:
```
│ elasticsearch {"type": "server", "timestamp": "2020-02-06T12:30:00,164Z", "level": "WARN", "component": "o.e.h.AbstractHttpServerTransport", "cluster.name": "quickstart", "node.name": "quickstart-es-default-0", "message": "caught exception w │
│ hile handling client http traffic, closing connection Netty4HttpChannel{localAddress=/172.20.190.206:9200, remoteAddress=/172.20.44.212:31531}", "cluster.uuid": "U2ANQXFFRGKPtNGjfBOH3A", "node.id": "iVlS7MsbROu5aHxRg9Hr5A" ,
│ elasticsearch {"type": "server", "timestamp": "2020-02-06T12:30:00,164Z", "level": "WARN", "component": "o.e.h.AbstractHttpServerTransport", "cluster.name": "quickstart", "node.name": "quickstart-es-default-0", "message": "caught exception w │
│ hile handling client http traffic, closing connection Netty4HttpChannel{localAddress=/172.20.190.206:9200, remoteAddress=/172.20.44.212:31531}", "cluster.uuid": "U2ANQXFFRGKPtNGjfBOH3A", "node.id": "iVlS7MsbROu5aHxRg9Hr5A" ,                  │
│ elasticsearch "stacktrace": ["io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: Received fatal alert: bad_certificate",
```
