### ISSUE TITLE
ECK to create/manage services by Node type

### ISSUE THREAD

**Issue by basigabri** [elastic/cloud-on-k8s#2572]
Currently ECK creates only one service inside k8s, exposed at 9200 port and having a ClusterIP.

This service named {cluster_name}-es-http, includes as endpoints all type of nodes(master,data,ingest).

The other services created one by node type(ingest,data,master) are not exposed: they don't have ClusterIP.

Kibana as an example is using exposed svc, for querying elastic. This means that it hits all endpoints including masters.
We need to create services exposed with ClusterIp, by node type. For example a svc only for ingest nodes. Then hit only these pods.

**Comment by sebgl** [comment]
Relates https://github.com/elastic/cloud-on-k8s/issues/2161.

It's fairly easy for users to create their own services targeting any Pods they want using label selectors.
We could automatically create X services, but it's hard to know in advance what subset of Pods are users interested in.
Hence we pre-create only the default one, for an easy quickstart experience.

You can easily setup something like this:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.6.0
  nodeSets:
  - name: ingest-nodes
    count: 3
    config:
      node.ingest: true
      node.data: false
      node.master. false
  - name: master-nodes
    count: 3
    config:
      node.ingest: false
      node.data: false
      node.master. true
  - name: data-nodes
    count: 3
    config:
      node.ingest: false
      node.data: true
      node.master. false

---

apiVersion: v1
kind: Service
metadata:
  name: es-ingest-nodes
spec:
  selector:
    common.k8s.elastic.co/type: elasticsearch
    elasticsearch.k8s.elastic.co/cluster-name: quickstart
    elasticsearch.k8s.elastic.co/node-ingest: true
  ports:
    - name: https 
      protocol: TCP
      port: 9200
      targetPort: 9200
```

@basigabri do you think that's a good alternative?
