### ISSUE TITLE
GKE E2E tests fail for a go dependency issue

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#2576]
```
build github.com/elastic/cloud-on-k8s/test/e2e/cmd: cannot load github.com/Masterminds/sprig: open /go/pkg/mod/cache/download/github.com/!masterminds/sprig/@v/v2.22.0+incompatible.lock: permission denied
```

**Comment by sebgl** [comment]
The dependency to sprig showing up as `+incompatible` just means it's not using go modules.
Looking at their [github page](https://github.com/Masterminds/sprig) it looks like version 3+ is compatible with go modules and we are using v2+.

I don't think this is related to the error we get.

**Comment by sebgl** [comment]
I cannot reproduce the error locally (tried `go clean --modcache` first to re-download all dependencies).

I'm wondering if it could be related to several CI jobs working in parallel with the same go modules cache?

**Comment by sebgl** [comment]
This actually happens [for other modules as well](https://devops-ci.elastic.co/view/cloud-on-k8s/job/cloud-on-k8s-versions-gke/214/consoleFull):

```
22:49:37  go: writing stat cache: open /go/pkg/mod/cache/download/k8s.io/api/@v/v0.17.3.info570321898.tmp: permission denied
```

```
22:49:37  go: writing stat cache: open /go/pkg/mod/cache/download/k8s.io/client-go/@v/v11.0.0+incompatible.info683262243.tmp: permission denied
```

**Comment by sebgl** [comment]
It seems to fail since [build 209](https://devops-ci.elastic.co/view/cloud-on-k8s/job/cloud-on-k8s-versions-gke/209/).

**Comment by sebgl** [comment]
Looking at https://devops-ci.elastic.co/blue/organizations/jenkins/cloud-on-k8s-versions-gke/detail/cloud-on-k8s-versions-gke/216/pipeline/35, I don't understand why some go mod logs are interleaved with the e2e runner logs.

**Comment by sebgl** [comment]
@charith-elastic noticed it could come from this change: https://github.com/elastic/cloud-on-k8s/blob/cda077a249cb828f933b0267ed59ebfc03e06005/test/e2e/Dockerfile#L21

However it does not explain why the tests sometimes run correctly, sometimes don't.
When they don't, [logs reveal](https://devops-ci.elastic.co/view/cloud-on-k8s/job/cloud-on-k8s-versions-gke/214/execution/node/66/log/) the Pod has to fetch go dependencies when running go tests. 
When they run correctly, [logs reveal](https://devops-ci.elastic.co/view/cloud-on-k8s/job/cloud-on-k8s-versions-gke/214/execution/node/55/log/) the Pod does not have to fetch go dependencies.
Both are running with the same image: `eu.gcr.io/****/eck-operator--e2e-tests:f63396e9 `.

It seems we are building and pushing that same docker image from every single E2E job. Is it possible it includes dependencies in some cases, but not others? Which would explain concurrent builds leading to different images?

**Comment by thbkrkr** [comment]
You guessed it right! I have some information to understand what are the conditions that make `chgrp -R 0 /go && chmod -R g=u /go` can be a problem.

The [eck-vanilla](https://devops-ci.elastic.co/job/cloud-on-k8s-versions-vanilla) job fails too. This indicates it is not related to several CI jobs working in parallel with the same go modules cache. This seems to indicate it is related to the kubernetes version (as for the job [eck-versions-k8s](https://devops-ci.elastic.co/job/cloud-on-k8s-versions-gke/)). Looking at the 2 jobs, it seems that the issue occurs from k8s 1.14.

I managed to isolate the problem:

Create 2 k8s clusters, one in version < 1.14 and one in version >= 1.14:
```sh
> kind create cluster --image kindest/node:v1.12.10 --name kind-12
> kind load --name kind-12 docker-image eu.gcr.io/elastic-cloud-dev/eck-operator--e2e-tests:cda077a2

> kind create cluster --image kindest/node:v1.15.3 --name kind-15
> kind load --name kind-15 docker-image eu.gcr.io/elastic-cloud-dev/eck-operator--e2e-tests:cda077a2
```

And deploy this job:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: eck-e2e-debug
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
        fsGroup: 101
        runAsUser: 101
        runAsGroup: 101
      containers:
        - name: e2e
          image: eu.gcr.io/elastic-cloud-dev/eck-operator--e2e-tests:cda077a2
          command: [ "go", "build", "test/e2e/cmd/main.go" ]
      restartPolicy: Never
```

Or just a pod to exec into it and run some commands manually:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: e2e
spec:
  securityContext:
    fsGroup: 101
    runAsGroup: 101
    runAsNonRoot: true
    runAsUser: 101
  containers:
  - name: main
    image: eu.gcr.io/elastic-cloud-dev/eck-operator--e2e-tests:cda077a2
    command: [ "sh", "-c", "sleep 1h" ]
```

In 1.12, it's ok. The current user (uid=101) can read and write files on the filesystem of the container.
In 1.15, it fails. The current user can't write files and can even read only a few files.

Let's compare the output of the `id` command:
```sh
[1.12] > id
[1.12] uid=101 gid=0(root) groups=0(root),101(ssh)

[1.15] > id
[1.15] uid=101 gid=101(ssh) groups=101(ssh)
```

I looked for elements related to the security context in the 1.14 release notes.
Since k8s 1.14, the `RunAsGroup` feature is now in beta and enabled by default. You can set the `runAsGroup` field in a pod’s securityContext to specify the primary group ID of all processes that will run in the pod.

This combined with 43ef707 seems to me to be the cause of the problem.
