### ISSUE TITLE
imagePullSecrets custom Kibana image registry

### ISSUE THREAD

**Issue by FelixRodriguezJara** [elastic/cloud-on-k8s#2580]
Hello elastic team!

I have used the elasticsearch operator to deploy the stack, together with Kibana in kubernetes. I need to use a custom image built based on a Kibana image in which a plugin is installed (for metrics export). I see, from the Kibana crd, that a custom image can be set. However, I am struggling to set up the imagePullSecrets. Could you please provide me with some guidance on the way it can be done?

Thank you very much.

Kind regards.

**Comment by sebgl** [comment]
Hi @FelixRodriguezJara 

Please have a look at the [official K8s doc](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/) to setup a Kubernetes secret containing your registry credentials.

Then, you can specify `imagePullSecrets` in the `podTemplate` section of your Kibana manifest:

```yaml
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-sample
spec:
  version: 7.6.0
  count: 1
  image: my-custom-repo/kibana:7.6.0
  elasticsearchRef:
    name: "elasticsearch-sample"
  podTemplate:
    metadata:
      labels:
        foo: bar
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: kibana
        resources:
          limits:
            memory: 1Gi
            cpu: 1
```
