### ISSUE TITLE
License not working on ES7.6 and ECK 1.0.1

### ISSUE THREAD

**Issue by aleph-zero** [elastic/cloud-on-k8s#2589]
## Bug Report
**What did you do?**

- Create GCP GKE cluster with version 1.14.10-gke.17
- kubectl apply -f https://download.elastic.co/downloads/eck/1.0.1/all-in-one.yaml
- Create single-node Elasticsearch cluster:
```
cat <<EOF  | kubectl apply -f -
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.6.0
  nodeSets:
  - name: default
    count: 1
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false
EOF
```
- Create single-node Kibnana
```
cat <<EOF | kubectl apply -f -
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
spec:
  version: 7.6.0
  count: 1
  elasticsearchRef:
    name: quickstart
EOF
```
- Port forward `kubectl port-forward service/quickstart-es-http 9200`
- Port forward `kubectl port-forward service/quickstart-kb-http 5601`
- Log into Kibana and go to Machine Learning and click on the Start Trial button to start a Platinum trial.

![image](https://user-images.githubusercontent.com/452273/74992966-72244680-53fe-11ea-9c7a-ff9297ae7d87.png)

- After clicking on the Start Trial button, Kibana redirects to the home page:
![image](https://user-images.githubusercontent.com/452273/74993045-b0216a80-53fe-11ea-87f9-9181cd3b4f24.png)

- Go to Stack Monitoring page and you can see that the trial is Basic, not Platinum:
![image](https://user-images.githubusercontent.com/452273/74993094-d3e4b080-53fe-11ea-9b4c-dfe5ea6b0b25.png)

- Go back to the Machine Learning page and you can see that Platinum features are not active:
![image](https://user-images.githubusercontent.com/452273/74993143-fc6caa80-53fe-11ea-99c5-72070f89ec88.png)

**What did you expect to see?**
I expected to have a 30-day Platinum trial license.

**Environment** Google GKE 1.14.10-gke.17

* ECK version: 1.0.1
* Kubernetes information:
	* Cloud: GKE 1.14.10-gke.17
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10", GitCommit:"575467a0eaf3ca1f20eb86215b3bde40a5ae617a", GitTreeState:"clean", BuildDate:"2019-12-11T12:41:00Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.17", GitCommit:"bdceba0734835c6cb1acbd1c447caf17d8613b44", GitTreeState:"clean", BuildDate:"2020-01-17T23:10:13Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}

```
