### ISSUE TITLE
Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden

### ISSUE THREAD

**Issue by JBodkin-LH** [elastic/cloud-on-k8s#2609]
## Bug Report
**What did you do?**
Increased the amount of memory available for the instance by setting the resource request and jvm heap options

**What did you expect to see?**
Elasticsearch updated with the new options

**What did you see instead? Under which circumstances?**
Kubernetes complained that the stateful set could not be updated. The logs do not show the patch that is being applied to the cluster so cannot determine which field is being updated that cannot be.

The messages stop appearing after some time, unsure if this is because of a backoff or the statefulset is being updated whilst a pod is being updated.

**Environment**

* ECK version: docker.elastic.co/eck/eck-operator:1.0.1
* Kubernetes information: GKE

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.9-gke.8", GitCommit:"a9973cbb2722793e2ea08d20880633ca61d3e669", GitTreeState:"clean", BuildDate:"2020-02-07T00:50:57Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

* Logs:
```
{"level":"debug","@timestamp":"2020-02-24T15:31:05.590Z","logger":"elasticsearch-controller","message":"Recording event","ver":"1.0.1-bcb74688","event":{"EventType":"Warning","Reason":"ReconciliationError","Message":"Failed to apply spec change: StatefulSet.apps \"content-repository-elasticsearch-es-default\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden"}}
{"level":"info","@timestamp":"2020-02-24T15:31:05.590Z","logger":"elasticsearch-controller","message":"Ending reconciliation run","ver":"1.0.1-bcb74688","iteration":13,"namespace":"web","name":"content-repository-elasticsearch","took":0.726916995}
{"level":"error","@timestamp":"2020-02-24T15:31:05.590Z","logger":"controller-runtime.controller","message":"Reconciler error","ver":"1.0.1-bcb74688","controller":"elasticsearch-controller","request":"web/content-repository-elasticsearch","error":"StatefulSet.apps \"content-repository-elasticsearch-es-default\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden","errorCauses":[{"error":"StatefulSet.apps \"content-repository-elasticsearch-es-default\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden"}],"stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191028221656-72ed19daf4bb/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191028221656-72ed19daf4bb/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191028221656-72ed19daf4bb/pkg/util/wait/wait.go:88"}
{"level":"debug","@timestamp":"2020-02-24T15:31:05.591Z","logger":"controller-runtime.manager.events","message":"Warning","ver":"1.0.1-bcb74688","object":{"kind":"Elasticsearch","namespace":"web","name":"content-repository-elasticsearch","uid":"808f742a-c970-48f0-a2c4-11c49f732df1","apiVersion":"elasticsearch.k8s.elastic.co/v1","resourceVersion":"268278674"},"reason":"ReconciliationError","message":"Failed to apply spec change: StatefulSet.apps \"content-repository-elasticsearch-es-default\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden"}
```

**Comment by anyasabo** [comment]
That's odd -- do you have the webhook running? It should be running by default and catch these errors up front. Can you also share the before/after ES specs so we can try and reproduce it? We test this scenario so I am curious why this one in particular would be failing.

**Comment by JBodkin-LH** [comment]
Yes, the webhook is running. Also, I see the same issues when trying to create a new nodeSet.

e.g.

```
{"level":"error","@timestamp":"2020-02-24T16:52:18.243Z","logger":"controller-runtime.controller","message":"Reconciler error","ver":"1.0.1-bcb74688","controller":"elasticsearch-controller","request":"web/content-repository-elasticsearch","error":"StatefulSet.apps \"content-repository-elasticsearch-es-default2\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden","errorCauses":[{"error":"StatefulSet.apps \"content-repository-elasticsearch-es-default2\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden"}],"stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191028221656-72ed19daf4bb/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191028221656-72ed19daf4bb/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191028221656-72ed19daf4bb/pkg/util/wait/wait.go:88"}
```


```
---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: content-repository-data
  namespace: web
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
allowVolumeExpansion: true
---
apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: content-repository-elasticsearch
  namespace: web
spec:
  version: 6.8.6
  nodeSets:
    - name: default2
      count: 1
      config:
        node.attr.attr_name: attr_value
        node.master: true
        node.data: true
        node.ingest: true
        node.ml: false
        indices.memory.min_index_buffer_size: 512mb
        http.max_content_length: 250mb
      podDisruptionBudget:
        spec:
          minAvailable: 0
          maxUnavailable: 0
      podTemplate:
        metadata:
          namespace: elastic-system
        spec:
          nodeSelector:
            workload: web
          tolerations:
            - key: workload
              operator: Equal
              value: web
              effect: NoSchedule
          initContainers:
           - name: sysctl
             securityContext:
               privileged: true
             command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
          containers:
            - name: elasticsearch
              resources:
                requests:
                  cpu: 1
                  memory: 8Gi
              env:
                - name: ES_JAVA_OPTS
                  value: "-Xms4g -Xmx4g"
      volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
          namespace: web
        spec:
          storageClassName: content-repository-data
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 200Gi
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  updateStrategy:
    changeBudget:
      maxSurge: -1
      maxUnavailable: -1
```
