### ISSUE TITLE
Kibana not working with nameSuffix or namePrefix applied in Kustomization

### ISSUE THREAD

**Issue by shebang42** [elastic/cloud-on-k8s#2629]
## Bug Report

**What did you do?**

Create a "kustomization.yaml" file with either "nameSuffix" or "namePrefix" config.

**What did you expect to see?**

-  ```kubectl get pods```:  see the Kibana pod in the output.
-  ```kubectl get elastic```: See the number of nodes and health of Kibana in the output

E.g.

```
kubectl get pods
NAME                            READY   STATUS    RESTARTS   AGE
quickstart-es-default-0         1/1     Running   0          52s
quickstart-kb-b795d6c89-ckz4r   0/1     Running   0          51s
```

```
$ kubectl get elastic
NAME                                                    HEALTH   NODES   VERSION   PHASE   AGE
elasticsearch.elasticsearch.k8s.elastic.co/quickstart   green    1       7.6.0     Ready   2m13s

NAME                                      HEALTH   NODES   VERSION   AGE
kibana.kibana.k8s.elastic.co/quickstart   green    1       7.6.0     108s
```

-  **What did you see instead? Under which circumstances?**

1: Pod is missing

```
$ kubectl get pods
NAME                          READY   STATUS    RESTARTS   AGE
quickstart-dev-es-default-0   1/1     Running   0          16m
```

2: No "Health" and "Nodes" output for Kibana

```
$ kubectl get elastic

NAME                                                        HEALTH   NODES   VERSION   PHASE   AGE
elasticsearch.elasticsearch.k8s.elastic.co/quickstart-dev   green    1       7.6.0     Ready   17m

NAME                                          HEALTH   NODES   VERSION   AGE
kibana.kibana.k8s.elastic.co/quickstart-dev                    7.6.0     17m
```

**Environment**

* ECK version: 1.0.1

  Kubernetes information: Cloud:  / EKS

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

- Logs:

```
kubectl apply -k .
elasticsearch.elasticsearch.k8s.elastic.co/quickstart-dev created
kibana.kibana.k8s.elastic.co/quickstart-dev created
```

```
kubectl describe kibana.kibana.k8s.elastic.co/quickstart-dev
Name:         quickstart-dev
Namespace:    default
Labels:       <none>
Annotations:  common.k8s.elastic.co/controller-version: 1.0.0
              kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"kibana.k8s.elastic.co/v1","kind":"Kibana","metadata":{"annotations":{},"name":"quickstart-dev","namespace":"default"},"spec...
API Version:  kibana.k8s.elastic.co/v1
Kind:         Kibana
Metadata:
  Creation Timestamp:  2020-02-27T16:03:59Z
  Generation:          2
  Resource Version:    43312439
  Self Link:           /apis/kibana.k8s.elastic.co/v1/namespaces/default/kibanas/quickstart-dev
  UID:                 c39c31f8-597a-11ea-8c88-0afe12e09030
Spec:
  Count:  1
  Elasticsearch Ref:
    Name:  quickstart
  Http:
    Service:
      Metadata:
        Creation Timestamp:  <nil>
      Spec:
    Tls:
      Certificate:
  Pod Template:
    Metadata:
      Creation Timestamp:  <nil>
    Spec:
      Containers:  <nil>
  Version:         7.6.0
Status:
  Association Status:  Pending
Events:
  Type     Reason                   Age                From                           Message
  ----     ------                   ----               ----                           -------
  Normal   AssociationStatusChange  76s                kibana-association-controller  Association status changed from [] to [Pending]
  Warning  AssociationError         75s                kibana-controller              Elasticsearch backend is not configured
  Warning  AssociationError         6s (x11 over 76s)  kibana-association-controller  Failed to find referenced backend default/quickstart: Elasticsearch.elasticsearch.k8s.elastic.co "quickstart" not found
```

* Files:

```
$ ls
elastic.yaml		kibana.yaml		kustomization.yaml
```

kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -dev

resources:
  - elastic.yaml
  - kibana.yaml
```

elastic.yaml (vanilla example from quickstart)

```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.6.0
  nodeSets:
  - name: default
    count: 1
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false
```

kibana.yaml  (vanilla example from quickstart)

```
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
spec:
  version: 7.6.0
  count: 1
  elasticsearchRef:
    name: quickstart
```

**Comment by thbkrkr** [comment]
Kibana won't come up because its referenced ES backend does not exist:
```sh
Warning  AssociationError 6s (x11 over 76s)  kibana-association-controller  
           Failed to find referenced backend default/quickstart: 
             Elasticsearch.elasticsearch.k8s.elastic.co "quickstart" not found
```

You must configure kustomize to also prefix the `spec.elasticsearchRef.name` of the Kibana resource definition.

**Comment by shebang42** [comment]
Thank you for the (extermely quick) reply.  This seems to fix it:

```
cat kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -dev

resources:
  - elastic.yaml
  - kibana.yaml

patchesStrategicMerge:
  - patch-kibana.yaml
```

```
cat patch-kibana.yaml
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
spec:
  elasticsearchRef:
    name: quickstart-dev
```

However, this is a pretty ugly fix.  Do you have any recommendations for a cleaner kustomization?

**Comment by shebang42** [comment]
This seems a better option.  Although I assume that the metadata.name of Kibana is the same as ES.
```
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
spec:
  version: 7.6.0
  count: 1
  elasticsearchRef:
    name: $(ESREF)
  env:
    - name: ESREF
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
```
