### ISSUE TITLE
Support coordinating-only node

### ISSUE THREAD

**Issue by mrkm4ntr** [elastic/cloud-on-k8s#2653]
## Proposal
I think it's common to use coordinating-only node when we manage a big cluster.
F.Y.I https://blog.softwaremill.com/6-not-so-obvious-things-about-elasticsearch-422491494aa4#2a6f

If some nodeSet has a coordinating-only configuration (data, master and ingest are false), I think it's useful that only such nodes connect the ClusterIP service.

WDYT?

**Comment by pebrc** [comment]
You can implement this behaviour yourself today without any changes to ECK by just creating a service that targets coordinating-only nodes: 

```yaml
spec:
  nodeSets:
  - name: coordinating
    count: 1
    config:
      node.master: false
      node.data: false
      node.ingest: false
      node.ml: false
    podTemplate:
      metadata:
        labels:
          coordinating: true
```

and then target that with a service like 
```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-coordinating-svc
spec:
  ports:
  - name: https
    port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    common.k8s.elastic.co/type: elasticsearch
    elasticsearch.k8s.elastic.co/cluster-name: ${YOUR_CLUSTER}
    coordinating: true
  type: ClusterIP
```

What we could do to facilitate is add a label that marks coordinating-only nodes, then you could leave out the PodTemplate part in the example above.
