### ISSUE TITLE
Kibana resource fails to create in 1.0.1

### ISSUE THREAD

**Issue by pietervincken** [elastic/cloud-on-k8s#2693]
## Bug Report
**What did you do?**
Create a Kibana instance using the Operator
**What did you expect to see?**
A working Kibana instance
**What did you see instead? Under which circumstances?**
The custom resource is present, but the operator fails to create the required resources for the Kibana instance
**Environment**

* ECK version:

	1.0.1

* Kubernetes information:

	* AKS version: 1.15.7
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-14T21:04:32Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"c83d931fb9bece427bc63a02349755e0f8696d3e", GitTreeState:"clean", BuildDate:"2020-01-31T20:09:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

* Resource definition:
```
apiVersion: kibana.k8s.elastic.co/v1beta1
kind: Kibana
metadata:
  name: kibana
spec:
  image: <obfuscated>.azurecr.io/kibana/kibana:7.5.1
  version: 7.5.1
  count: 1
  elasticsearchRef:
    name: elasticsearch
  podTemplate:
    metadata:
      labels:
        managed-by: kustomize
        app: logging
    spec:
      containers:
        - name: kibana
          resources:
            requests:
              memory: 1Gi
              cpu: 0.5
            limits:
              memory: 2Gi
              cpu: 1
  http:
    tls:
      selfSignedCertificate:
        disabled: true
```

* Logs:
```
{"level":"info","@timestamp":"2020-03-12T11:35:45.974Z","logger":"kibana-association-controller","message":"Starting reconciliation run","ver":"1.0.1-bcb74688","iteration":19,"namespace":"operator-logging","name":"kibana"}
{"level":"info","@timestamp":"2020-03-12T11:35:45.974Z","logger":"annotation","message":"Resource was created with older version of operator, will not take action","ver":"1.0.1-bcb74688","controller_version":"1.0.1","resource_controller_version":"0.0.0-UNKNOWN","namespace":"operator-logging","name":"kibana"}
```

We noticed that the annotation that's being set on the Kibana resource is 0.0.0-UNKNOWN when the resource is created. When we (manually) update this to 1.0.1, the operator kicks in and creates the resources. 

```
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:  
    annotations:    
        common.k8s.elastic.co/controller-version: 0.0.0-UNKNOWN
....
```

**Comment by pebrc** [comment]
@pietervincken ECK adds this `0.0.0-UNKNOWN` annotation if it suspects that a resource has been created by an older version of ECK (one of the alpha versions) 

Was that the case here? Were you ever running alpha versions of ECK 

Or did you create a Kibana with the same name in the same namespace prior to this one, that was not completely deleted (e.g. a service still existing)?

**Comment by charith-elastic** [comment]
Closing due to inactivity. Please re-open if there are any new developments.

**Comment by barkbay** [comment]
I think I hit this one today while working on #2777. I noticed that some of my resources were not reconciled and annotated with `0.0.0-UNKNOWN`

**Comment by barkbay** [comment]
Before I describe what is happening in my situation it is important to understand that the default propagation policy when using `kubectl delete` is **`Background`**:

```
I0401 09:40:06.354818     548 request.go:1017] Request Body: {"propagationPolicy":"Background"}
I0401 09:40:06.432116     548 round_trippers.go:443] DELETE https://35.115.7.123/apis/elasticsearch.k8s.elastic.co/v1/namespaces/default/elasticsearches/elasticsearch-sample 200 OK in 77 milliseconds
```

Said differently: when deleting objects with `kubectl delete...` `blockOwnerDeletion` does not actually block parent deletion.

Here is what happened in my situation:

I created an Elasticsearch resource on GKE with a `LoadBalancer`.
Services of type `LoadBalancer` have a `finalizer` that can slow down their deletion:
```yaml
apiVersion: v1
kind: Service
metadata:
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  name: elasticsearch-sample-es-http
  namespace: default
  ownerReferences:
  - apiVersion: elasticsearch.k8s.elastic.co/v1
    blockOwnerDeletion: true
    controller: true
    kind: Elasticsearch
    name: elasticsearch-sample
    uid: bff751a3-9233-49b3-8bcd-2b7f5b440be6
```

As you can see `blockOwnerDeletion` is set to  `true`, but keep in mind that it is useless if I delete the parent object (Elasticsearch) with `kubectl`:

```
> kubectl delete es elasticsearch-sample    
elasticsearch.elasticsearch.k8s.elastic.co "elasticsearch-sample" deleted
```

```
> kubectl get es
No resources found in default namespace.
```

```
> kubectl get svc
NAME                           TYPE           CLUSTER-IP     EXTERNAL-IP    PORT(S)          AGE
elasticsearch-sample-es-http   LoadBalancer   10.28.25.3   34.7.22.94   9200:31596/TCP   9m15s
```

As you can see the Elasticsearch resource has been deleted but the service is still there, waiting for its finalizer to be removed.

This is a problem because if the user creates an Elasticsearch resource with the same name while the `Service` is still there then ECK assumes that the Elasticsearch resource has been created by a previous, incompatible, version of ECK:

https://github.com/elastic/cloud-on-k8s/blob/master/pkg/controller/common/annotation/controller_version.go#L150-L156

```golang
	var svcs corev1.ServiceList
	err = client.List(&svcs, labelSelector, nsSelector)
	if err != nil {
		return false, err
	}
	// if we listed any services successfully, then we know this cluster was reconciled by an old version since any objects reconciled by a 0.9.0+ operator would have a label
	return len(svcs.Items) != 0, nil
```

_The comments are misleading since we don't add labels on `Services`_
