### ISSUE TITLE
Elasticsearch 8.0.0-SNAPSHOT fails at startup due to volume permissions

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#2791]
Exception raised at startup:

```
["org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: failed to obtain node locks, tried [/usr/share/elasticsearch/d
ata]; maybe these locations are not writable or multiple nodes were started on the same data path?",
```

I think that's because the Docker image runs with user `elasticsearch` by default, whereas it was using user `root` before (even though the elasticsearch process itself runs as user `elasticsearch`):

```
⟩ docker run -ti docker.elastic.co/elasticsearch/elasticsearch:7.6.0 id
uid=0(root) gid=0(root) groups=0(root)
⟩ docker run -ti docker.elastic.co/elasticsearch/elasticsearch:8.0.0-SNAPSHOT id
uid=1000(elasticsearch) gid=0(root) groups=0(root)
```

**Comment by sebgl** [comment]
We run an init container to change the owner of the data volume to `elasticsearch`, but only if the init container runs with the `root` user:

```bash
        # chown the data and logs volume to the elasticsearch user
	# only done when running as root, other cases should be handled
	# with a proper security context
	chown_start=$(date +%s)
	if [[ $EUID -eq 0 ]]; then
		{{range .ChownToElasticsearch}}
			echo "chowning {{.}} to elasticsearch:elasticsearch"
			chown -v elasticsearch:elasticsearch {{.}}
		{{end}}
	fi
```

In 8.0.0-SNAPSHOT the init container runs with the `elasticsearch` user, hence does not have permission to chown the volume.
If I comment the `if` condition above, the init container fails with:

```
chowning /usr/share/elasticsearch/data to elasticsearch:elasticsearch
chown: changing ownership of '/usr/share/elasticsearch/data': Operation not permitted
failed to change ownership of '/usr/share/elasticsearch/data' from root:root to elasticsearch:elasticsearch
```

**Comment by pebrc** [comment]
Related to https://github.com/elastic/cloud-on-k8s/issues/2599

**Comment by sebgl** [comment]
I think the way we currently deal with volumes permissions is not great: we run an init container to `chown` the mounted volumes (with write access to user `root`) so they belong to the `elasticsearch` user instead.

I think this would be better dealt with [`securityContext.fsGroup` in the pod spec](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod).
This modified podTemplate allows file to be written in the mounted volume by a user with group ID 1000, and works fine with Elasticsearch 8.0.0-SNAPSHOT:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
spec:
  version: 8.0.0-SNAPSHOT
  nodeSets:
  - name: default
    count: 3
    podTemplate:
      spec:
        securityContext:
          fsGroup: 1000
```

I think the right thing to do is replace our custom init container chown mechanism by a default `fsGroup` that works out of the box.

However I'm not exactly sure of the implications on Openshift. [This documentation](https://docs.openshift.com/container-platform/3.11/install_config/persistent_storage/pod_security_context.htmlhttps://docs.openshift.com/container-platform/3.11/install_config/persistent_storage/pod_security_context.html) gives more details.

**Comment by sebgl** [comment]
The difference in Elasticsearch behaviour comes from https://github.com/elastic/elasticsearch/pull/50277, where `tini` was added to the image as process manager. It does not default to using the `root` user, which is a good thing IMO.

___

I've done some tests regarding `fsGroup` on Openshift 3.11 (using `minishift`).

First, there is no problem running 8.0..0-SNAPSHOT on Openshift. Openshift changes the default user the container runs with to an arbitrary one for security reasons (in my example: UID `1000140000`). It also ensures this arbitrary user is member of the `root` group (but is not the `root` user), which gives it write access to our mounted volume.

Whereas in "regular" Kubernetes, the `elasticsearch` user in the container cannot write to the mounted volumes owned by `root`. To fix this, we can set `fsGroup: 1000` in the pod spec, which allows the user with UID 1000 to write in mounted volumes.

Setting `fsGroup: 1000` on Openshift leads to the Pod not being created at all:

```
create Pod elasticsearch-sample-es-default-0 in StatefulSet elasticsearch-sample-es-default failed error: pods "elasticsearch-sample-es-default-0" is forbidden: unable to validate against any security context constraint: [fsGroup: Invalid val
ue: []int64{1000}: 1000 is not an allowed group]  
```

One solution to this, [detailed in Openshift docs](https://docs.openshift.com/container-platform/3.11/install_config/persistent_storage/pod_security_context.html#fsgroup) is to not use the default `restricted` SCC, but to create a custom one where group 1000 is allowed (or part of a range that is allowed).

tl;dr:
* we can use `fsGroup` on most k8s distributions
* we cannot use `fsGroup` on Openshift unless using a custom SCC

Let's see if we can find a common solution here. In any case, changing permissions in the init container does not feel like the right thing to do.

**Comment by barkbay** [comment]
> we can use fsGroup on most k8s distributions

I think it will work as long as the cluster is not secured. If there is a PSP that restrict the range for the fsGroup _(which is I would expect on production clusters)_ chances are it will fail the same way I guess.

**Comment by sebgl** [comment]
You're right @barkbay this goes beyond the scope of Openshift vs. not Openshift.

The question is more: is there a PSP (or SCC on Openshift) or not?

IIUC [this doc](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod) correctly, setting an `fsGroup` automatically makes all processes running in the container (which may or not be using a `runAsUser` range) part of the `fsGroup` supplementary group. So as long as the default PSP specifies an `fsGroup` (can be a range), the assigned arbitrary user will be able to write in the mounted volumes. So we should just do nothing in this situation.

When no PSP/SCC is enforced, we probably need to set `fsGroup: 1000`.

Should we default to one or the other, or try to auto-detect what's best? Users can still override the `securityContext` in the podTemplate, but picking a default seems hard :(

**Comment by sebgl** [comment]
Assuming we want to rely on `securityContext.fsGroup`, we can write a dedicated documentation page that explains:
- what is the default applied by ECK
- how to remove that default (if there's one) if you don't want any fsGroup set, because you already rely on a PSP/SCC
- how to override the podTemplate to set your own fsGroup

Regarding ECK defaults, we have several options.

## 1. Don't set a default `securityContext.fsGroup`

If we don't set a default value, it is likely that:

- Vanilla K8s users with no PSP set will run into troubles
- Openshift users running with the default SCC will not have any problem
- Vanilla K8s users or Openshift users with a custom PSP/SCC may run into troubles if that PSP does not set the `fsGroup`

The first point seems quite representative of a quickstart experience, so we probably have to adapt the quickstart to explain what `fsGroup` is and why it matters.

```
cat <<EOF | kubectl apply -f -
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.6.2
  nodeSets:
  - name: default
    count: 1
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false
    # allow the elasticsearch user in the container to write on mounted volumes
    # remove this if you already have an SCC (Openshift) or PSP (Kubernetes) set
    podTemplate:
      spec:
        securityContext:
          fsGroup: 1000
EOF
```

It's important to notice this example does not "just work": it will probably work on a basic Kubernetes setup, but not on a basic Openshift setup. Users have to understand they need to remove or comment some lines in the yaml.

I think if we go this path we also have to adapt other examples in the rest of the documentation, and also adapt the recipes we have in the Github repository.

## 2. Set a default `securityContext.fsGroup: 1000`

If we set a default value, it is likely that:

- Vanilla K8s users with no PSP set will not have any problem
- Openshift users running with the default SCC will run into troubles
- Vanilla K8s users or Openshift users with a custom PSP/SCC may run into troubles if that PSP conflicts with the default `securityContext`

We probably need to adapt the quickstart example to mention the `securityContext`, especially for Openshift users.

We can either mention it explicitly in the quickstart (and other examples):

```
cat <<EOF | kubectl apply -f -
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.6.2
  nodeSets:
  - name: default
    count: 1
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false
    # # if a PSP (Kubernetes) or SCC (Openshift) is set, ensure ECK does not set any custom
    # # securityContext, by uncommenting this line. This is likely to be the case on Openshift.
    # podTemplate:
    #  spec:
    #    securityContext: {}

EOF
```

Or add a note about it:

```
cat <<EOF | kubectl apply -f -
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.6.2
  nodeSets:
  - name: default
    count: 1
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false
EOF
```

```
NOTE: ECK sets a default security context to allow the `elasticsearch` user to access mounted volumes. On Openshift, this conflicts with the default `restricted` SCC. It may also conflict with any custom PSP or SCC configured on your Kubernetes cluster. If that is the case you can disable the default pod security context with:

apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.6.2
  nodeSets:
  - name: default
    count: 1
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false
    # don't set any default securityContext
    podTemplate:
      spec:
        securityContext: {}

See [this page](link) for more details.
```

We also need to highlight this on the documentation page dedicated to OpenShift.

## 3. Attempt to set the best default depending on the environment

We could attempt the following:

* If we detect ECK is deployed on Openshift, don't set a default pod `securityContext`.
* Otherwise, set a default `securityContext.fsGroup: 1000`.

Detecting Openshift can probably be done in various ways (an [example](https://github.com/kubevirt/kubevirt/blob/f71e9c9615a6c36178169d66814586a93ba515b5/pkg/util/cluster/cluster.go#L21)), but there does not seem to be a documented robust way of doing it.
This have to be done in agreement with the existing RBAC permissions. Requiring additional RBAC permissions for this call feels wrong.

It is also an option to list the existing PSP/SCC in the cluster, and don't set the `securityContext` if the returned list is not empty, but that would require an explicit RBAC permission that may differ in K8s vs. Openshift.

We probably still need to add the following to the quickstart:

```
NOTE: ECK sets a default pod `securityContext` to allow the `elasticsearch` user to access mounted volumes, unless deployed on Openshift. This may conflict with existing PSP and SCC. See [this page](link) for more information.
```
