### ISSUE TITLE
ignore the default the "elasticsearch-es-http" service

### ISSUE THREAD

**Issue by balusarakesh** [elastic/cloud-on-k8s#2813]
## Bug Report
**What did you do?**

Trying to deploy kibana by following the guidelines here - https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-kibana.html.
The default service `elasticsearch-es-http` created by the operator points to both data and master nodes. We want our elasticsearch queries routed to only the data nodes. So, we created a service `elasticsearch-data` which points to only data nodes and specified in the `elasticsearch.hosts` variable.

**What did you expect to see?**
We expected the `elasticsearch-es-http` service to be ignored and use the custom service defined in kibana.

**What did you see instead? Under which circumstances?**
We see the new service and the default service used in the kibana config

* ECK version:
`docker.elastic.co/eck/eck-operator:1.0.1`

* Kubernetes information:
EKS (using the operator - https://github.com/elastic/cloud-on-k8s/blob/master/config/crds/all-crds.yaml)

```
 Rakesh$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:25:00Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.10-eks-bac369", GitCommit:"bac3690554985327ae4d13e42169e8b1c2f37226", GitTreeState:"clean", BuildDate:"2020-02-26T01:12:54Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by charith-elastic** [comment]
If you are still opted into automatic Elasticsearch connection management by setting `elasticsearchRef`, then the `elasticsearch-es-http` service would take precedence. You should remove the automatic association if you want Kibana traffic to go through the custom service you declared.  For the quickstart example, this would look like the following:

```yaml
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
spec:
  version: 7.6.1
  count: 1
  config:
    elasticsearch.hosts: 
      - https://elasticsearch-data-nodes:9200
    elasticsearch.username: elastic
  podTemplate:
    spec:
      containers:
        - name: kibana
          env:
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: quickstart-es-elastic-user
                  key: elastic
```
