### ISSUE TITLE
Elasticsearch fails to create in 1.0.1

### ISSUE THREAD

**Issue by balusarakesh** [elastic/cloud-on-k8s#2822]
## Bug Report
**What did you do?**
Create elasticsearch resource using ECK version 1.0.1.
**What did you expect to see?**
A working elasticsearch data and master instances.
**What did you see instead? Under which circumstances?**
Elasticsearch kind resource is created but the nodes and masters are not created.
The operator complains that the elasticsearch might be created from an older version of elastic operator.

* ECK version:
1.0.1
* Kubernetes information:
EKS

$ kubectl version
```
MacBook-Pro-2:elk Rakesh$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:25:00Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.10-eks-bac369", GitCommit:"bac3690554985327ae4d13e42169e8b1c2f37226", GitTreeState:"clean", BuildDate:"2020-02-26T01:12:54Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

Resource definition
```
# Source: elasticsearch/templates/elasticsearch.yaml
apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: elasticsearch
  labels:
    helm.sh/chart: elasticsearch-1.0.0
    common.k8s.elastic.co/type: elasticsearch
    elasticsearch.k8s.elastic.co/cluster-name: elasticsearch
    elasticsearch.k8s.elastic.co/statefulset-name: elasticsearch-es-data
    app.kubernetes.io/version: "7.6.1"
    app.kubernetes.io/managed-by: Helm
spec:
  version: 7.6.1
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
  - name: masters
    count: 3
    config:
      node.master: true
      node.data: false
      node.ingest: false

      cluster.remote.connect: false
      index.store.type: mmapfs
      xpack.monitoring.collection.enabled: true
      xpack.monitoring.exporters:
        my_local:
          index.name.time_format: YYYY-MM
          type: local
      xpack.security.authc.realms:
        native:
          native1:
            order: 1
    podTemplate:
      spec:
        containers:
        - name: elasticsearch

    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-masters
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: "1Gi"
  - name: data
    count: 2
    config:
      node.master: false
      node.data: true
      node.ingest: true

      cluster.remote.connect: false
      index.store.type: mmapfs
      indices.recovery.max_bytes_per_sec: 500mb
      xpack.monitoring.collection.enabled: true
      xpack.monitoring.exporters:
        my_local:
          index.name.time_format: YYYY-MM
          type: local
      xpack.security.authc.realms:
        native:
          native1:
            order: 1
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          env:
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 400Gi
```

logs:
```
Resource was created with older version of operator, will not take action
```

kinda related to this one - https://github.com/elastic/cloud-on-k8s/issues/2693

```
Happening ONLY IN ELASTICSEARCH. I re-built the entire namespace and the issue is still happening. When I put the annotation common.k8s.elastic.co/controller-version: 1.0.1 it seems to be fixed. This doesn't happen in Kibana though.
```
