### ISSUE TITLE
services other than -http do not get populated 

### ISSUE THREAD

**Issue by kurktchiev** [elastic/cloud-on-k8s#2824]
## Bug Report
**What did you do?**
Deployed a ECK cluster and the associated services

**What did you expect to see?**
A list of services with the appropriate endpoints for each resource service defined

**What did you see instead? Under which circumstances?**
```
┌─[12:46:24][0.64s][boris][aristotle][elastic][~/Sources]
└─▪ kubectl get svc
NAME                          TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)    AGE
production-1-es-coordinator   ClusterIP   None         <none>        <none>     63m
production-1-es-data-cold     ClusterIP   None         <none>        <none>     63m
production-1-es-data-hot      ClusterIP   None         <none>        <none>     63m
production-1-es-data-warm     ClusterIP   None         <none>        <none>     63m
production-1-es-http          ClusterIP   None         <none>        9200/TCP   63m
production-1-es-ingest        ClusterIP   None         <none>        <none>     63m
production-1-es-master        ClusterIP   None         <none>        <none>     63m
```

**Environment**
Kubernetes v1.15.6 on prem

* ECK version:

	1.0.1
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.6", GitCommit:"7015f71e75f670eb9e7ebd4b5749639d42e20079", GitTreeState:"clean", BuildDate:"2019-11-13T11:20:18Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.6", GitCommit:"7015f71e75f670eb9e7ebd4b5749639d42e20079", GitTreeState:"clean", BuildDate:"2019-11-13T11:11:50Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

* Resource definition:
```
┌─[12:53:34][0.51s][boris][aristotle][elastic][~/Sources]
└─▪ kubectl describe svc production-1-es-ingest
Name:              production-1-es-ingest
Namespace:         elastic
Labels:            common.k8s.elastic.co/type=elasticsearch
                   elasticsearch.k8s.elastic.co/cluster-name=production-1
                   elasticsearch.k8s.elastic.co/statefulset-name=production-1-es-ingest
Annotations:       <none>
Selector:          common.k8s.elastic.co/type=elasticsearch,elasticsearch.k8s.elastic.co/cluster-name=production-1,elasticsearch.k8s.elastic.co/statefulset-name=production-1-es-ingest
Type:              ClusterIP
IP:                None
Session Affinity:  None
Events:            <none>


┌─[12:54:27][0.55s][boris][aristotle][elastic][~/Sources]
└─▪ kubectl describe sts production-1-es-ingest
Name:               production-1-es-ingest
Namespace:          elastic
CreationTimestamp:  Mon, 06 Apr 2020 11:49:39 +0200
Selector:           common.k8s.elastic.co/type=elasticsearch,elasticsearch.k8s.elastic.co/cluster-name=production-1,elasticsearch.k8s.elastic.co/statefulset-name=production-1-es-ingest
Labels:             common.k8s.elastic.co/template-hash=2441148279
                    common.k8s.elastic.co/type=elasticsearch
                    elasticsearch.k8s.elastic.co/cluster-name=production-1
                    elasticsearch.k8s.elastic.co/statefulset-name=production-1-es-ingest
```

I expect that just like the -http service the rest of the services and the selectors they use match up and actually populate, right now, there are services but they are unusable as they do not actually have endpoints.

**Comment by thbkrkr** [comment]
We recently added a documentation to [create services for exposing different node types](https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-traffic-splitting.html) that could help.

I followed it and the endpoints are well created:
```sh
> k get svc,ep | grep nodes               
service/hulk-es-coordinator-nodes   ClusterIP   10.1.111.41    <none>        9200/TCP   9m58s
service/hulk-es-ingest-nodes        ClusterIP   10.1.111.48    <none>        9200/TCP   9m58s
service/hulk-es-non-master-nodes    ClusterIP   10.1.103.137   <none>        9200/TCP   9m58s
endpoints/hulk-es-coordinator-nodes                      9m58s
endpoints/hulk-es-ingest-nodes                           9m58s
endpoints/hulk-es-non-master-nodes                       9m58s
```

If not, could you please share the YAML manifest that you used to create your Elastic Stack and the associated services?

**Comment by kurktchiev** [comment]
Right but this is done after the cluster is created rather than using the services that get created by the operator automatically. Essentially what you are doing just updates the existing services to add the port and targets, which are missing by default in the services created by the operator.

So I guess the ask is to let the operator create a functioning service that I do not need to update at a later time (later step). As far as my manifest, sure here it is:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: production-1
spec:
  version: 7.6.1
  updateStrategy:
    changeBudget:
      maxSurge: 1
      maxUnavailable: 1
  podDisruptionBudget:
    spec:
      disruptionsAllowed: 1
      maxUnavailable: 1
      selector:
        matchLabels:
          elasticsearch.k8s.elastic.co/cluster-name: production-1
  http:
    service:
      spec:
        clusterIP: None
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
  - name: master
    count: 3
    config:
      node.master: true
      node.data: false
      node.ingest: false
      node.ml: false
      node.store.allow_mmap: false
      cluster.remote.connect: false
      node.attr.hostname: ${DIAMANTI_NODE_NAME}
      cluster.routing.allocation.awareness.attributes: hostname
      indices.lifecycle.poll_interval: 1m
    volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 256Gi
          storageClassName: high-m3
    podTemplate:
      metadata:
        labels:
          forceUpdate: 'true'
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      elasticsearch.k8s.elastic.co/cluster-name: production-1
                  topologyKey: kubernetes.io/hostname
        containers:
          - name: elasticsearch
            env:
              - name: ES_JAVA_OPTS
                value: -Xms8g -Xmx8g
              - name: DIAMANTI_NODE_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
            resources:
              requests:
                memory: 16Gi
                cpu: 4
              limits:
                memory: 16Gi
                cpu: 4
  - name: data-hot
    count: 3
    config:
      node.master: false
      node.data: true
      node.ingest: true
      node.ml: false
      node.store.allow_mmap: false
      cluster.remote.connect: false
      node.attr.data: hot
      node.attr.hostname: ${DIAMANTI_NODE_NAME}
      cluster.routing.allocation.awareness.attributes: hostname
      indices.lifecycle.poll_interval: 1m
    volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 256Gi
          storageClassName: high
    podTemplate:
      metadata:
        labels:
          forceUpdate: 'true'
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      elasticsearch.k8s.elastic.co/cluster-name: production-1
                  topologyKey: kubernetes.io/hostname
        containers:
          - name: elasticsearch
            env:
              - name: ES_JAVA_OPTS
                value: -Xms8g -Xmx8g
              - name: DIAMANTI_NODE_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
            resources:
              requests:
                memory: 16Gi
                cpu: 8
              limits:
                memory: 16Gi
                cpu: 8
  - name: data-warm
    count: 3
    config:
      node.master: false
      node.data: true
      node.ingest: true
      node.ml: false
      node.store.allow_mmap: false
      cluster.remote.connect: false
      node.attr.data: warm
      node.attr.hostname: ${DIAMANTI_NODE_NAME}
      cluster.routing.allocation.awareness.attributes: hostname
      indices.lifecycle.poll_interval: 1m
    volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 256Gi
          storageClassName: medium
    podTemplate:
      metadata:
        labels:
          forceUpdate: 'true'
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      elasticsearch.k8s.elastic.co/cluster-name: production-1
                  topologyKey: kubernetes.io/hostname
        containers:
          - name: elasticsearch
            env:
              - name: ES_JAVA_OPTS
                value: -Xms8g -Xmx8g
              - name: DIAMANTI_NODE_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
            resources:
              requests:
                memory: 16Gi
                cpu: 4
              limits:
                memory: 16Gi
                cpu: 4
  - name: data-cold
    count: 3
    config:
      node.master: false
      node.data: true
      node.ingest: true
      node.ml: false
      node.store.allow_mmap: false
      cluster.remote.connect: false
      node.attr.data: cold
      node.attr.hostname: ${DIAMANTI_NODE_NAME}
      cluster.routing.allocation.awareness.attributes: hostname
      indices.lifecycle.poll_interval: 1m
    volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 256Gi
          storageClassName: best-effort
    podTemplate:
      metadata:
        labels:
          forceUpdate: 'true'
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      elasticsearch.k8s.elastic.co/cluster-name: production-1
                  topologyKey: kubernetes.io/hostname
        containers:
          - name: elasticsearch
            env:
              - name: ES_JAVA_OPTS
                value: -Xms4g -Xmx4g
              - name: DIAMANTI_NODE_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
            resources:
              requests:
                memory: 8Gi
                cpu: 1
              limits:
                memory: 8Gi
                cpu: 1
  - name: ingest
    count: 3
    config:
      node.master: false
      node.data: false
      node.ingest: true
      node.ml: false
      node.store.allow_mmap: false
      cluster.remote.connect: false
      node.attr.hostname: ${DIAMANTI_NODE_NAME}
      cluster.routing.allocation.awareness.attributes: hostname
      indices.lifecycle.poll_interval: 1m
    podTemplate:
      metadata:
        labels:
          forceUpdate: 'true'
        annotations:
          #diamanti.com/endpoint0: '{"network":"v3041-nr","perfTier":"high"}'
          #diamanti.com/endpoint1: '{"network":"elastic-ingest-r","perfTier":"high"}'
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      elasticsearch.k8s.elastic.co/cluster-name: production-0
                  topologyKey: kubernetes.io/hostname
        containers:
          - name: elasticsearch
            env:
              - name: ES_JAVA_OPTS
                value: -Xms8g -Xmx8g
              - name: DIAMANTI_NODE_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
            resources:
              requests:
                memory: 16Gi
                cpu: 8
              limits:
                memory: 16Gi
                cpu: 8
  - name: coordinator
    count: 2
    config:
      node.master: false
      node.data: false
      node.ingest: true
      node.ml: false
      node.store.allow_mmap: false
      cluster.remote.connect: false
      node.attr.hostname: ${DIAMANTI_NODE_NAME}
      cluster.routing.allocation.awareness.attributes: hostname
      indices.lifecycle.poll_interval: 1m
    podTemplate:
      metadata:
        labels:
          forceUpdate: 'true'
        annotations:
          #diamanti.com/endpoint0: '{"network":"v3041-nr","perfTier":"high"}'
          #diamanti.com/endpoint1: '{"network":"elastic-ingest-r","perfTier":"high"}'
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      elasticsearch.k8s.elastic.co/cluster-name: production-0
                  topologyKey: kubernetes.io/hostname
        containers:
          - name: elasticsearch
            env:
              - name: ES_JAVA_OPTS
                value: -Xms8g -Xmx8g
              - name: DIAMANTI_NODE_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
            resources:
              requests:
                memory: 16Gi
                cpu: 8
              limits:
                memory: 16Gi
                cpu: 8
```
