### ISSUE TITLE
Volume claim templates validation fails if the storage unit is different

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#2856]
Observed in https://discuss.elastic.co/t/volume-claim-templates-cannot-be-modified/219493/7.

If we apply the following manifest:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
spec:
  version: 7.6.0
  nodeSets:
  - name: default
    count: 3
    config:
      node.store.allow_mmap: false
    volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1024Gi
```

The underlying StatefulSet is created with `1Ti` storage (not `1024Gi`).
Any update on the above manifest, while keeping `1024Gi`, fails because the webhook rejects the volumeClaimTemplates update.
I guess because it's comparing `1024Gi` to `1Ti`.
