### ISSUE TITLE
Support Volume Claims for Kibana

### ISSUE THREAD

**Issue by orfeas0** [elastic/cloud-on-k8s#2867]
## Support Volume Claims for Kibana

**Kibana sometimes needs data persistence too, for example for custom plugins or image files.**

It would be quite useful to be able to persist data in kibana as well, instead of only in ES nodes.

**Comment by sebgl** [comment]
Hey @orfeas0,

Kibana is mostly stateless, and stores data in Elasticsearch directly.
What sort of persistent Kibana data do you have in mind here?

**Comment by orfeas0** [comment]
Custom images/icons to be used inside dashboards/visualizations.

Unless they can be stored inside elastic and used from kibana (highly unlikely), they need to be available inside a kibana folder, more specifically:
`/usr/share/kibana/src/legacy/ui/public/assets/images/`

This means we have to "kubectl scp" everything if the kibana pod dies and is re-created.

I looked at volumes created by the Kibana Deployment (using ECK) and it's `kibana-data, kibana-config and certs`.
I can imagine those can be overwritten by a PV Template to use my custom volumes, but the folder we use (.../src/legacy/etc) is not included in any of those.

**Comment by sebgl** [comment]
Got it @orfeas0, thanks for the details.

I think you can do something like the following:
```yaml
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-sample
spec:
  version: 7.6.0
  count: 1
  elasticsearchRef:
    name: "elasticsearch-sample"
  podTemplate:
    spec:
      containers:
      - name: kibana
        volumeMounts:
        - name: my-assets
          mountPath: /usr/share/kibana/src/legacy/ui/public/assets/images
      volumes:
      - name: my-assets
        emptyDir: {}
```

I chose an `emptyDir` volume type here as an example, but you could specify any kind of volume here. Including `persistentVolumeClaim`, as long as you have created that claim yourself beforehand.

Closing the issue for now, please reopen if needed :)

**Comment by orfeas0** [comment]
Thanks sebgl, that worked (with some debugging)!

I created a PVC and mounted it instead of emptyDir.

The problem was that it was mounted as root, and `kubectl exec -it kibana-pod bash` logged me in as kibana.
I had to ssh to the host and `docker exec -it kibana-container bash` as root.

I researched extensively on how to mount a PV/PVC as a specific user or with specific permissions, but found nothing in Kubernetes docs.

**Comment by sebgl** [comment]
> I researched extensively on how to mount a PV/PVC as a specific user or with specific permissions, but found nothing in Kubernetes docs.

Look at [`securityContext.fsGroup`](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod). I think you can set to to UID 1000, which is the uid of the `kibana` user in the container:

```yaml
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-sample
spec:
  version: 7.6.0
  count: 1
  elasticsearchRef:
    name: "elasticsearch-sample"
  podTemplate:
    spec:
        securityContext:
            fsGroup: 1000
```

It should allow the Kibana user to access your mounted volumes.
