### ISSUE TITLE
Istio guide broken with 7.6.2 vs 7.4.0 / cluster nodes comm failure

### ISSUE THREAD

**Issue by haf** [elastic/cloud-on-k8s#2922]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.6.2 vs 7.4.0
**Plugins installed**: [] None
**JVM version** (`java -version`): Operator decides
**OS version** (`uname -a` if on a Unix-like system): COS / GKE

### Description of the problem including expected versus actual behavior

Following this guide should work: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-service-mesh-istio.html but it never forms a cluster.

I'm coming from 7.4.0 that I had working with istio, with a similarly disabled TLS generation for the elasticsearch nodes. Upgrading to 7.6.2 broke its ability to provision.

### Steps to reproduce:

 1. **Follow the guide** with Istio mTLS **being PERMISSIVE**, i.e. encrypting all connections unless specified otherwise, and allowing for pods outside the mesh. You can also follow the guide with the mesh being `STRICT`, or you can follow it with `mTLS: DISABLED` with the `DestinationRule` from the guide; all have the same effect.
 2. Outcome:

```
$ k get elastic

NAME                                             HEALTH    NODES   VERSION   PHASE             AGE
elasticsearch.elasticsearch.k8s.elastic.co/apm   unknown           7.6.2     ApplyingChanges   25m

NAME                               HEALTH   NODES   VERSION   AGE
kibana.kibana.k8s.elastic.co/apm   red              7.6.2     25m
```

#### Evidence 1

**Mesh connectivity; can we connect from the operator to the nodes**? Yes.

With faulty credentials:

```
$ k exec -n elastic-system -c manager elastic-operator-0 -- curl -XGET http://10.48.3.9:9200/_cluster/health -i
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   411  100   411    0     0  86055      0 --:--:-- --:--:-- --:--:--  100k
HTTP/1.1 401 Unauthorized
www-authenticate: Basic realm="security" charset="UTF-8"
content-type: application/json; charset=UTF-8
content-length: 411
x-envoy-upstream-service-time: 3
date: Tue, 21 Apr 2020 08:54:11 GMT
server: envoy

{"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication credentials for REST request [/_cluster/health]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}}],"type":"security_exception","reason":"missing authentication credentials for REST request [/_cluster/health]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}},"status":401}%
```

(in the above case I target the pod IP straight away to do away with Service/VirtualService routing interference and DNS)

You get the same if you replace the above IP with the internal load balancer IP: `http://apm-es-http.monitoring.svc:9200/_cluster/health`; 401 Permission Denied. Similarly, with `-u wrong:creds` you get `unable to authenticate user [wrong] for REST request [...]`. Point being; connectivity to the cluster nodes works fine from the operator.

#### Evidence 2

Is Istio misconfigured? No.

`istioctl x analyze -k` doesn't tell me about any errors in the mesh.

#### Evidence 3

Would it have worked with valid creds? No.

Now, with valid credentials:

```
$ k exec -n elastic-system -c manager elastic-operator-0 -- curl -XGET http://10.48.3.9:9200/_cluster/health -i -u elastic:flchpsm9qmh4jptfqdhdlfx5
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    24  100    24    0     0      1      0  0:00:24  0:00:15  0:00:09     6
HTTP/1.1 504 Gateway Timeout
content-length: 24
content-type: text/plain
date: Tue, 21 Apr 2020 08:47:53 GMT
server: envoy

upstream request timeout%
```

As you can see, this comes from the envoy sidecar after 15 seconds.

After 30 seconds, you see this in the logs (`stern -n monitoring -c elasticsearch elastic`):

```
apm-es-violet-0 elasticsearch {"type": "server", "timestamp": "2020-04-21T08:56:04,807Z", "level": "DEBUG", "component": "o.e.a.s.m.TransportMasterNodeAction", "cluster.name": "apm", "node.name": "apm-es-violet-0", "message": "timed out while retrying [cluster:monitor/health] after failure (timeout [30s])" }
apm-es-violet-0 elasticsearch {"type": "server", "timestamp": "2020-04-21T08:56:04,808Z", "level": "WARN", "component": "r.suppressed", "cluster.name": "apm", "node.name": "apm-es-violet-0", "message": "path: /_cluster/health, params: {}",
apm-es-violet-0 elasticsearch "stacktrace": ["org.elasticsearch.discovery.MasterNotDiscoveredException: null",
apm-es-violet-0 elasticsearch "at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$2.onTimeout(TransportMasterNodeAction.java:220) [elasticsearch-7.6.2.jar:7.6.2]",
apm-es-violet-0 elasticsearch "at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:325) [elasticsearch-7.6.2.jar:7.6.2]",
apm-es-violet-0 elasticsearch "at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:252) [elasticsearch-7.6.2.jar:7.6.2]",
apm-es-violet-0 elasticsearch "at org.elasticsearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:598) [elasticsearch-7.6.2.jar:7.6.2]",
apm-es-violet-0 elasticsearch "at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:633) [elasticsearch-7.6.2.jar:7.6.2]",
apm-es-violet-0 elasticsearch "at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]",
apm-es-violet-0 elasticsearch "at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]",
apm-es-violet-0 elasticsearch "at java.lang.Thread.run(Thread.java:830) [?:?]"] }
```

Because the nodes don't reply at all in this ES version, the operator is very confused:

```
elastic-operator-0 manager {"level":"info","@timestamp":"2020-04-21T08:58:47.936Z","logger":"elasticsearch-controller","message":"Ending reconciliation run","ver":"1.0.1-bcb74688","iteration":102,"namespace":"monitoring","name":"apm","took":180.894045952}
elastic-operator-0 manager {"level":"error","@timestamp":"2020-04-21T08:58:47.936Z","logger":"controller-runtime.controller","message":"Reconciler error","ver":"1.0.1-bcb74688","controller":"elasticsearch-controller","request":"monitoring/apm","error":"[failed to revert to basic: 503 Service Unavailable: unknown, unable to delete /_cluster/voting_config_exclusions: 503 Service Unavailable: ]","errorCauses":[{"error":"failed to revert to basic: 503 Service Unavailable: unknown","errorVerbose":"503 Service Unavailable: unknown\nfailed to revert to basic\ngithub.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/license.startBasic\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/license/apply.go:77\ngithub.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/license.applyLinkedLicense\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/license/apply.go:51\ngithub.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/license.Reconcile\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/license/reconcile.go:21\ngithub.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/driver.(*defaultDriver).Reconcile.func1\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/driver/driver.go:198\ngithub.com/elastic/cloud-on-k8s/pkg/controller/common/reconciler.(*Results).Apply\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/common/reconciler/results.go:90\ngithub.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/driver.(*defaultDriver).Reconcile\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/driver/driver.go:191\ngithub.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch.(*ReconcileElasticsearch).internalReconcile\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/elasticsearch_controller.go:291\ngithub.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch.(*ReconcileElasticsearch).Reconcile\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/elasticsearch_controller.go:223\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191028221656-72ed19daf4bb/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191028221656-72ed19daf4bb/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191028221656-72ed19daf4bb/pkg/util/wait/wait.go:88\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357"},{"error":"unable to delete /_cluster/voting_config_exclusions: 503 Service Unavailable: unknown","errorVerbose":"503 Service Unavailable: unknown\nunable to delete /_cluster/voting_config_exclusions\ngithub.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/client.(*clientV7).DeleteVotingConfigExclusions\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/client/v7.go:63\ngithub.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/version/zen2.ClearVotingConfigExclusions\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/version/zen2/voting_exclusions.go:78\ngithub.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/driver.(*defaultDriver).reconcileNodeSpecs\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/driver/nodes.go:117\ngithub.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/driver.(*defaultDriver).Reconcile\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/driver/driver.go:239\ngithub.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch.(*ReconcileElasticsearch).internalReconcile\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/elasticsearch_controller.go:291\ngithub.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch.(*ReconcileElasticsearch).Reconcile\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/elasticsearch_controller.go:223\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191028221656-72ed19daf4bb/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191028221656-72ed19daf4bb/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191028221656-72ed19daf4bb/pkg/util/wait/wait.go:88\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357"}],"stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191028221656-72ed19daf4bb/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191028221656-72ed19daf4bb/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191028221656-72ed19daf4bb/pkg/util/wait/wait.go:88"}
elastic-operator-0 istio-proxy {"start_time":"2020-04-21T08:57:17.815Z","method":"DELETE","request_id":"ed4e2992-c605-9050-a855-a9d280d7cd39","upstream_host":"10.48.2.29:9200","x_forwarded_for":"-","requested_server_name":"-","bytes_received":"0","istio_policy_status":"-","bytes_sent":"115","upstream_cluster":"outbound|9200||apm-es-http.monitoring.svc.cluster.local","downstream_remote_address":"10.48.3.5:49778","authority":"apm-es-http.monitoring.svc:9200","path":"/_cluster/voting_config_exclusions?wait_for_removal=false","protocol":"HTTP/1.1","upstream_service_time":"90119","upstream_local_address":"-","duration":"90120","downstream_local_address":"10.54.5.207:9200","upstream_transport_failure_reason":"-","route_name":"default","response_code":"503","user_agent":"Go-http-client/1.1","response_flags":"URX"}
elastic-operator-0 manager {"level":"info","@timestamp":"2020-04-21T08:58:50.496Z","logger":"elasticsearch-controller","message":"Starting reconciliation run","ver":"1.0.1-bcb74688","iteration":103,"namespace":"monitoring","name":"apm"}
```

### Background

CRD instance:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: apm

  labels:
    app: apm
    component: elasticsearch

spec:
  version: 7.6.2
  http:
    tls:
      # Relates to: https://github.com/jaegertracing/jaeger-operator/pull/114
      selfSignedCertificate:
        disabled: true

  nodeSets:
  - name: violet
    count: 1
    volumeClaimTemplates:
    - metadata:
        name: apm-es-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false

    podTemplate:
      metadata:
        annotations:
          traffic.sidecar.istio.io/excludeOutboundPorts: "9300"
          traffic.sidecar.istio.io/excludeInboundPorts: "9300"
```

**Comment by charith-elastic** [comment]
What is the version of Istio you are running? 

Try adding `traffic.sidecar.istio.io/includeInboundPorts: "*"` annotation to your Elasticsearch resource as described in the latest documentation (https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-service-mesh-istio.html#k8s-service-mesh-istio-elasticsearch) and see if that helps.

**Comment by haf** [comment]
I think the issue is that podTemplate doesn't carry. `k get elasticsearch -o yaml` doesn't include it, so port `9300` times out (as can be seen in the `istio_proxy` logs (not in the elastic logs). The difference between these versions is that the operator was bumped to 1.0.1 (because podTemplate doesn't bite on the previous version either), and in the beginning of starting the new operator, this gets logged:

```
elastic-operator-0 istio-proxy {"protocol":"-","upstream_service_time":"-","upstream_local_address":"10.48.6.3:57170","duration":"32049","downstream_local_address":"10.54.0.1:443","upstream_transport_failure_reason":"-","route_name":"-","response_code":"0","user_agent":"-","response_flags":"-","start_time":"2020-04-21T11:43:08.682Z","method":"-","request_id":"-","upstream_host":"10.55.0.2:443","x_forwarded_for":"-","requested_server_name":"-","bytes_received":"18720","istio_policy_status":"-","bytes_sent":"87323","upstream_cluster":"outbound|443||kubernetes.default.svc.cluster.local","downstream_remote_address":"10.48.6.3:51654","authority":"-","path":"-"}
```

Which itself doesn't really tell you much, except the duration is just above 30 seconds, thus being a timeout.

**Comment by haf** [comment]
After fixing that, so the operator can connect to the k8s API,

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: k8s-api
  namespace: elastic-system

  labels:
    tier: control-plane

spec:
  host: kubernetes.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
```

the pods are still missing the annotations.

**Comment by charith-elastic** [comment]
That is very odd. Did you have the init container definition in the manifest before? I don't see it in the manifest you pasted above (which worked correctly when I tried it out).

It's also worth checking to see if you have multiple copies of the operator running. Because it looks like communication with the API server was blocked before, you could also try re-applying your manifest see if it goes through this time.

**Comment by haf** [comment]
Trying from another angle: since I'm running in PERMISSIVE mode, but with a global DestinationRule that enabled mTLS unless opted out of explicitly, this paragraph in the docs doesn't apply:

> If you have configured Istio in permissive mode, examples defined elsewhere in the ECK documentation will continue to work without requiring any modifications. However, if you have enabled strict mutual TLS authentication between services either via global (MeshPolicy) or namespace-level (Policy) configuration, the following modifications to the resource manifests are necessary for correct operation.

Because it leaves you with this error in the logs:

```
apm-es-violet-0 elasticsearch {"type": "server", "timestamp": "2020-04-21T12:33:15,731Z", "level": "WARN", "component": "o.e.x.s.t.n.SecurityNetty4HttpServerTransport", "cluster.name": "apm", "node.name": "apm-es-violet-0", "message": "received plaintext http traffic on an https channel, closing connection Netty4HttpChannel{localAddress=/127.0.0.1:9200, remoteAddress=/127.0.0.1:36000}" }
```

**Comment by haf** [comment]
> Did you have the init container definition in the manifest before?

Yes, this was it.

**Comment by haf** [comment]
No, it just keeps hanging. I've got the pod annotations now, but calls the `/_license` endpoint keeps timing out. It's unclear what it's timing out on though.

**Comment by charith-elastic** [comment]
This is very hard to debug over the internet because there could be other policies or settings in the cluster that are interfering with each other. It'd be interesting to see the  output of `istioctl  proxy-config cluster elastic-operator-0 -n elastic-system` and `istioctl  proxy-config route elastic-operator-0 -n elastic-system`  if you are able to produce those.

There are some discrepancies between the provided manifest and the output from Kubernetes (node count, init container etc.). If the cluster is discardable (i.e. you don't care about preserving the data), you could try deleting the cluster and recreating it to see if that clears up any corrupt state.

Finally, please provide the Istio version running on your cluster so that I can try to reproduce the upgrade scenario on my end.

**Comment by haf** [comment]
```
$ istioctl proxy-config cluster elastic-operator-0 -n elastic-system
SERVICE FQDN                                                  PORT      SUBSET         DIRECTION     TYPE
BlackHoleCluster                                              -         -              -             STATIC
InboundPassthroughClusterIpv4                                 -         -              -             ORIGINAL_DST
PassthroughCluster                                            -         -              -             ORIGINAL_DST
alertmanager-operated.monitoring.svc.cluster.local            9093      -              outbound      ORIGINAL_DST
alertmanager-operated.monitoring.svc.cluster.local            9094      -              outbound      ORIGINAL_DST
apm-es-http.monitoring.svc.cluster.local                      9200      -              outbound      EDS
apm-kb-http.monitoring.svc.cluster.local                      5601      -              outbound      EDS
calico-typha.kube-system.svc.cluster.local                    5473      -              outbound      EDS
cert-manager-webhook.cert-manager.svc.cluster.local           443       -              outbound      EDS
cert-manager.cert-manager.svc.cluster.local                   9402      -              outbound      EDS
elastic-webhook-server.elastic-system.svc.cluster.local       443       -              inbound       STATIC
elastic-webhook-server.elastic-system.svc.cluster.local       443       -              outbound      EDS
grafana-pg-repl.monitoring.svc.cluster.local                  5432      -              outbound      EDS
grafana-pg.monitoring.svc.cluster.local                       5432      -              outbound      EDS
grafana.monitoring.svc.cluster.local                          80        -              outbound      EDS
grafana.monitoring.svc.cluster.local                          3000      -              outbound      EDS
heapster.kube-system.svc.cluster.local                        80        -              outbound      EDS
istio-citadel.istio-system.svc.cluster.local                  8060      -              outbound      EDS
istio-citadel.istio-system.svc.cluster.local                  15014     -              outbound      EDS
istio-egressgateway.istio-system.svc.cluster.local            80        -              outbound      EDS
istio-egressgateway.istio-system.svc.cluster.local            443       -              outbound      EDS
istio-egressgateway.istio-system.svc.cluster.local            15443     -              outbound      EDS
istio-galley.istio-system.svc.cluster.local                   443       -              outbound      EDS
istio-galley.istio-system.svc.cluster.local                   9901      -              outbound      EDS
istio-galley.istio-system.svc.cluster.local                   15014     -              outbound      EDS
istio-galley.istio-system.svc.cluster.local                   15019     -              outbound      EDS
istio-ingressgateway.istio-system.svc.cluster.local           80        -              outbound      EDS
istio-ingressgateway.istio-system.svc.cluster.local           443       -              outbound      EDS
istio-ingressgateway.istio-system.svc.cluster.local           15020     -              outbound      EDS
istio-ingressgateway.istio-system.svc.cluster.local           15029     -              outbound      EDS
istio-ingressgateway.istio-system.svc.cluster.local           15030     -              outbound      EDS
istio-ingressgateway.istio-system.svc.cluster.local           15031     -              outbound      EDS
istio-ingressgateway.istio-system.svc.cluster.local           15032     -              outbound      EDS
istio-ingressgateway.istio-system.svc.cluster.local           15443     -              outbound      EDS
istio-pilot.istio-system.svc.cluster.local                    8080      -              outbound      EDS
istio-pilot.istio-system.svc.cluster.local                    15010     -              outbound      EDS
istio-pilot.istio-system.svc.cluster.local                    15011     -              outbound      EDS
istio-pilot.istio-system.svc.cluster.local                    15014     -              outbound      EDS
istio-policy.istio-system.svc.cluster.local                   9091      -              outbound      EDS
istio-policy.istio-system.svc.cluster.local                   15004     -              outbound      EDS
istio-policy.istio-system.svc.cluster.local                   15014     -              outbound      EDS
istio-sidecar-injector.istio-system.svc.cluster.local         443       -              outbound      EDS
istio-telemetry.istio-system.svc.cluster.local                9091      -              outbound      EDS
istio-telemetry.istio-system.svc.cluster.local                15004     -              outbound      EDS
istio-telemetry.istio-system.svc.cluster.local                15014     -              outbound      EDS
istio-telemetry.istio-system.svc.cluster.local                42422     -              outbound      EDS
jaeger-operator-metrics.jaeger-system.svc.cluster.local       8383      -              outbound      EDS
jaeger-operator-metrics.jaeger-system.svc.cluster.local       8686      -              outbound      EDS
kiali.monitoring.svc.cluster.local                            9090      -              outbound      EDS
kiali.monitoring.svc.cluster.local                            20001     -              outbound      EDS
kube-controller-manager.monitoring.svc.cluster.local          10252     -              outbound      ORIGINAL_DST
kube-coredns.monitoring.svc.cluster.local                     9153      -              outbound      ORIGINAL_DST
kube-dns.kube-system.svc.cluster.local                        53        -              outbound      EDS
kube-etcd.monitoring.svc.cluster.local                        2379      -              outbound      ORIGINAL_DST
kube-proxy.monitoring.svc.cluster.local                       10249     -              outbound      ORIGINAL_DST
kube-scheduler.monitoring.svc.cluster.local                   10251     -              outbound      ORIGINAL_DST
kube-state-metrics.monitoring.svc.cluster.local               8080      -              outbound      EDS
kubernetes.default.svc.cluster.local                          443       -              outbound      EDS
metrics-server.kube-system.svc.cluster.local                  443       -              outbound      EDS
mgmtCluster                                                   15020     mgmt-15020     inbound       STATIC
prometheus-alertmanager.monitoring.svc.cluster.local          9093      -              outbound      EDS
prometheus-node-exporter.monitoring.svc.cluster.local         9100      -              outbound      EDS
prometheus-operated.monitoring.svc.cluster.local              9090      -              outbound      ORIGINAL_DST
prometheus-operator-kubelet.kube-system.svc.cluster.local     10250     -              outbound      ORIGINAL_DST
prometheus-operator.monitoring.svc.cluster.local              443       -              outbound      EDS
prometheus-operator.monitoring.svc.cluster.local              8080      -              outbound      EDS
prometheus.monitoring.svc.cluster.local                       9090      -              outbound      EDS
prometheus_stats                                              -         -              -             STATIC
sealed-secrets-controller.kube-system.svc.cluster.local       8080      -              outbound      EDS
xds-grpc                                                      -         -              -             STRICT_DNS
zipkin                                                        -         -              -             STRICT_DNS
```

and

```
$ istioctl proxy-config route elastic-operator-0 -n elastic-system
NOTE: This output only contains routes loaded via RDS.
NAME                                                             VIRTUAL HOSTS
istio-ingressgateway.istio-system.svc.cluster.local:15032        1
calico-typha.kube-system.svc.cluster.local:5473                  1
elastic-webhook-server.elastic-system.svc.cluster.local:443      1
istio-ingressgateway.istio-system.svc.cluster.local:15029        1
grafana-pg.monitoring.svc.cluster.local:5432                     1
80                                                               14
istio-ingressgateway.istio-system.svc.cluster.local:15031        1
jaeger-operator-metrics.jaeger-system.svc.cluster.local:8686     1
istio-ingressgateway.istio-system.svc.cluster.local:15030        1
3000                                                             2
cert-manager.cert-manager.svc.cluster.local:9402                 1
sealed-secrets-controller.kube-system.svc.cluster.local:8080     1
metrics-server.kube-system.svc.cluster.local:443                 1
istio-telemetry.istio-system.svc.cluster.local:42422             1
grafana-pg-repl.monitoring.svc.cluster.local:5432                1
istio-sidecar-injector.istio-system.svc.cluster.local:443        1
heapster.kube-system.svc.cluster.local:80                        1
istio-ingressgateway.istio-system.svc.cluster.local:15020        1
5601                                                             2
8060                                                             2
8080                                                             5
8383                                                             2
9090                                                             4
9091                                                             3
9093                                                             3
9094                                                             2
9100                                                             2
9153                                                             2
9200                                                             2
9901                                                             2
10249                                                            2
10251                                                            2
10252                                                            2
15004                                                            3
15010                                                            2
15014                                                            6
15019                                                            2
20001                                                            2
                                                                 1
```

Istio v1.4.6 at the time of writing.

This is the profile I deploy:

```
# https://cloud.google.com/istio/docs/istio-on-gke/installing
apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  profile: sds

  tag: 1.4.6

  defaultNamespace: istio-system

  cni:
    enabled: true
    components:
      cni:
        namespace: kube-system

  autoInjection:
    enabled: true
    components:
      injector:
        enabled: true
        k8s:
          hpaSpec:
            minReplicas: 2

  trafficManagement:
    enabled: true
    components:
      pilot:
        k8s:
          hpaSpec:
            minReplicas: 2

  security:
    components:
      cert_manager:
        # https://github.com/istio/istio/issues/19417#issuecomment-584611325
        enabled: false
      node_agent:
        enabled: true

  telemetry:
    enabled: true
    components:
      telemetry:
        k8s:
          hpaSpec:
            minReplicas: 2

  policy:
    components:
      policy:
        k8s:
          hpaSpec:
            minReplicas: 2

  gateways:
    enabled: true

    components:
      ingressGateway:
        enabled: true
        k8s:
          hpaSpec:
            minReplicas: 2

      egressGateway:
        enabled: true
        k8s:
          hpaSpec:
            minReplicas: 2

  # https://istio.io/docs/tasks/observability/logs/access-log/
  # https://issuetracker.google.com/issues/126527530
  values:
    global:
      mtls:
        enabled: false
      k8sIngress:
        enabled: true
        enableHttps: true
        gatewayName: ingressgateway
      controlPlaneSecurityEnabled: true
      logAsJson: true
      logging:
        level: default:info
      proxy:
        accessLogFile: /dev/stdout
        accessLogEncoding: JSON

      tracer:
        zipkin:
          address: jaeger-collector.monitoring:9411

    telemetry:
      enabled: true
      v2:
        enabled: true

    prometheus:
      enabled: false

    cni:
      enabled: true
      cniBinDir: /home/kubernetes/bin

    sidecarInjectorWebhook:
      rewriteAppHTTPProbe: true
      # https://github.com/istio/istio/pull/16539/files
      objectSelector:
        autoInject: true
        enabled: false

    kiali:
      enabled: false

    pilot:
      enabled: true
      policy:
        enabled: true
      traceSampling: 100

    gateways:
      istio-ingressgateway:
        sds:
          enabled: true
```

With these extras:

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: k8s-api
spec:
  host: "kubernetes.default.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: DISABLE
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: default
  namespace: istio-system

spec:
  host: '*.local'
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
```
