### ISSUE TITLE
PDB per Node type (Master, Data, Injest)

### ISSUE THREAD

**Issue by akrzos-bw** [elastic/cloud-on-k8s#2936]
## PodDisruptionBudget per node type (master, data, injest, ...)

If we are performing maintenance on a kubernetes cluster (cordon, drain, updates/upgrades, then reboot) an ECK cluster can end up blocking the upgrade for a lengthy period of time while the ECK cluster goes into yellow status while a data node is removed from service but replaced on a separate node.  This disruption often causes re-balancing of shards and now the Elastic PDB prevents other ECK cluster pods from being evicted even though they may not have an impact on data loss such as a master pod.  If we had a PDB per node type we could mitigate some of the nodes that would be blocked while waiting for the ECK cluster to return to healthy green state.

It also appears that regardless of the underlying data redundancy the cluster is limited to a single disruption at this point.

**Comment by anyasabo** [comment]
Just to address your last point, the `maxUnavailable` setting can be tuned to modify that behavior: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-update-strategy.html

**Comment by sebgl** [comment]
`updateStrategy.maxUnavailable` only impacts rolling upgrades of the cluster, not disruptions related to the PodDisruptionBudget.

Note that you can also [set your own PodDisruptionBudget](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-pod-disruption-budget.html), or override the default one. For your use case I think you may want something similar to the following:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.6.2
  nodeSets:
  - name: default
    count: 3
  podDisruptionBudget: {} # disable the default PDB
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: data-nodes-pdb
spec:
  minAvailable: 2 # should probably be (number of data nodes - 1), I'm considering you have 3 data nodes here
  selector:
    matchLabels:
      elasticsearch.k8s.elastic.co/cluster-name: your-es-cluster
      elasticsearch.k8s.elastic.co/node-data: true
      elasticsearch.k8s.elastic.co/node-master: false
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: master-nodes-pdb
spec:
  minAvailable: 2 # should probably be (number of master nodes - 1), I'm considering you have 3 master nodes here
  selector:
    matchLabels:
      elasticsearch.k8s.elastic.co/cluster-name: your-es-cluster
      elasticsearch.k8s.elastic.co/node-data: false
      elasticsearch.k8s.elastic.co/node-master: true
```

This example (to adapt to your use case) would:
* allow one data node to go down
* also allow one master node to go down
* allow any number of other node roles (eg. ingest) to go down, since no PDB is defined for them

**Comment by sebgl** [comment]
It's hard for ECK to come up with the best default depending on use cases here. In which case the example above demonstrates more flexibility to achieve one's needs.
Still keeping the issue open though, we may want to consider improving the existing defaults to allow disrupting more than one node under certain conditions.

**Comment by sanderma** [comment]
I also have some issues with the default pdb.
I have changed the operator to set the pdb to 0 when nodecount is 1. IMHO when someone sets a nodecount of 1, he or she is not interested in being highly available.

**Comment by sanderma** [comment]
By setting this default this way, when one does not give a manual pdb, the operator will set the pdb to 0 when there is a single node cluster:
```bash
NAME                    MIN AVAILABLE   MAX UNAVAILABLE   ALLOWED DISRUPTIONS   AGE
quickstart-es-default   0               N/A               1                     8s
```

When you scale the cluster up, the operator will set the pdb as intended, and treat the cluster as highly available:

```bash
NAME                    MIN AVAILABLE   MAX UNAVAILABLE   ALLOWED DISRUPTIONS   AGE
quickstart-es-default   1               N/A               1                     38s
```

**Comment by sebgl** [comment]
@sanderma this makes sense to me. Thanks for mentioning the idea in the issue and then opening a PR! Will review it shortly.

**Comment by erdody** [comment]
@sebgl if you configure your own PDBs (and disable the default), you disable the ability of the operator to adjust it dynamically based on the cluster status ("It allows one Elasticsearch Pod to be taken down, as long as the cluster has a green health"). I would like to keep that behavior but restricted to data nodes only.

**Comment by sebgl** [comment]
@erdody indeed. Can you give more details about what you're trying to achieve? Allowing all master nodes to be taken down would be rather dangerous?

I'm thinking about relaxing the way the default PDB can be configured to allow users to override the Pod selector only. So that you can restrict it to data nodes labels only and come up with your own additional PDBs for other type of nodes.

**Comment by erdody** [comment]
@sebgl that would work for us. I was in fact thinking of setting the non-data nodes PDBs separately. Besides data nodes, the other PDBs don't need any dynamic behavior anyways.

**Comment by Tommmster** [comment]
> @erdody indeed. Can you give more details about what you're trying to achieve? Allowing all master nodes to be taken down would be rather dangerous?
> 
> I'm thinking about relaxing the way the default PDB can be configured to allow users to override the Pod selector only. So that you can keep that default logic for data nodes only and come up with your own additional PDBs for other type of nodes.

Is this a possibility or has it been discarded. We're facing the same issues (master node is restarted, no other nodes can be restarted -> rack drain is blocked). 
Thanks!

**Comment by BenjaminHerbert** [comment]
I understand, the default behavior is turned off, once I create creates PDBs.

> It allows one Elasticsearch Pod to be taken down, as long as the cluster has a green health

**Comment by RikuXan** [comment]
I found this issue due to a similar situation with Kubernetes cluster upgrades being delayed or even timing out due to the described causal chain of (only that my cluster contains only master nodes, so the per-role PDB doesn't apply): cluster is green (PDB minAvailable=<nodes-1>) -> Pod goes down (OK by the PDB) -> cluster becomes yellow -> ECK updates the PDB to minAvailable=Nodes -> StatefulSet reschedules down Pod onto another node and Elastic discards the data associated with the Pod -> cluster takes a long time for rebalancing, hindering or failing the upgrade process due to any drains of another Elasticsearch Pods failing.

My conclusion is that the best thing to do is adjusting the PDB before a cluster upgrade (or any process that sequentially drains/restarts nodes) to a fixed minAvailable=<nodes-1> to stop the StatefulSet from rescheduling the downed Pods and simply wait for the node to become available again, keeping the shards. After the upgrade is through, I would then simply revert to the ECK-managed PDB.

Is this approach reasonable or are there better ways to handle such temporary node unavailabilities?

**Comment by ebuildy** [comment]
> What is the risk if this is turned off? Let's say I create separate `master` and `data` node PDBs.

PDB ensure a minimum pods always exist. There is no risk if you create a PDB for each nodes type.

You can lost a master and a data node in same time

**Comment by BenjaminHerbert** [comment]
I know about PDB behaviour. I am trying to understand the impact of using a separate PDB for each node with regard to the health of the Elasticsearch cluster. Because this would allow that a second Kubernetes pod is terminated, even though the cluster might be already in a yellow state. This is not allowed when the dynamic PDB handling is in place.

**Comment by barkbay** [comment]
Just to be sure I understand, if we can use `maxUnavailable ` instead of `minAvailable` as suggested in https://github.com/elastic/cloud-on-k8s/pull/8590, what is the value of managing the PDBs from the operator? Automatically manage the labels in the selector?

_Edit: Answering to myself: dynamically managing `maxUnavailable ` or `minAvailable`  depending on the cluster state._

**Comment by naemono** [comment]
# Update on the default PodDisruptionBudget Enhancements for NodeSets in ECK

We’ve been discussing ways to improve the management of PodDisruptionBudgets (PDBs) in the ECK operator, specifically addressing the limitations outlined in this issue. Our goal is to optimize disruption handling for Elasticsearch clusters, particularly during operations like Kubernetes upgrades. Below, we outline our proposed approach, the rationale behind it, and invite your feedback to help shape this feature.

## Current State

Currently, the ECK operator creates a single PDB for an entire Elasticsearch cluster, using a label selector that spans all nodeSets backed by StatefulSets. The minAvailable field is dynamically managed based on the total number of replicas and the cluster’s health (typically allowing disruptions only when the cluster is green).

## Problem

The single PDB approach causes delays in operations like Kubernetes upgrades, particularly for large clusters with diverse nodeSet roles (e.g., master, data_hot, coordinating). During operations like node maintenance or upgrades, the cluster may temporarily go yellow, halting further disruptions and prolonging the process. Users have expressed a need to allow disruptions for certain nodeSets (e.g., coordinating or ingest) even in a yellow state, while maintaining stricter protections for others (e.g., data_hot). The current workaround requires users to manually define PDBs per nodeSet, which is cumbersome and lacks operator-managed intelligence.

## Proposed Solution:

After evaluating several options we believe that the following solution is the best fit for our needs. This solution enhances the default PDB behavior for customers by creating dedicated PDBs per nodeSet with smarter disruption rules based on the nodeSet’s role and cluster health. The operator will automatically manage these PDBs, setting `maxUnavailable: 1` for specific nodeSets under the following conditions:

* Dedicated master nodeSet: Allow `maxUnavailable: 1` if the cluster is yellow or green.
* Dedicated coordinating nodeSet (no roles defined): Allow `maxUnavailable: 1` if the cluster is yellow or green.
* Dedicated pure data nodeSets (e.g., data_hot, data_warm, data_cold, data_content): Allow `maxUnavailable: 1` only if the cluster is green.
* Dedicated frozen data nodeSets: Allow `maxUnavailable: 1` if the cluster is yellow or green.
* Dedicated ingest, ML, or transform nodeSets: Allow maxUnavailable: 1 if the cluster is yellow or green.
* Mixed nodeSets (e.g., data_hot + ingest): Use the most conservative rule (e.g., maxUnavailable: 1 only when green).

### Pros

* No CRD changes: Maintains backward compatibility and avoids modifying the Elasticsearch spec.
* Automated management: The operator intelligently adjusts PDBs based on cluster health and nodeSet roles, reducing user effort.
* Optimized disruptions: Allows faster operations (e.g., upgrades) by permitting disruptions for certain nodeSets in yellow states.

### Cons

* Limited customization: Users cannot easily override maxUnavailable (e.g., set to 2 for specific nodeSets).
* Potential complexity: The “magic” of automatic PDB management may be less transparent to users.

## Alternatives Considered

We explored several other options, including:

* Extend the Elasticsearch spec to allow a PDB per nodeSet, fully user-controlled. This adds flexibility but requires CRD changes and potentially removes operator-managed health-based disruption controls. Unfortunately this option didn't allow PDBs to span multiple nodeSets.
* Allow a list of named PDBs in the spec, referenced within the nodeSets by name, supporting PDBs across multiple nodeSets but potentially removing operator-managed health checks.

# Example: Elasticsearch CRD with Multiple NodeSets and Resulting PDBs

Below is an example of an Elasticsearch Custom Resource Definition (CRD) with multiple nodeSets, each with distinct Elasticsearch roles, and the corresponding PodDisruptionBudgets (PDBs) generated by the ECK operator using the proposed option. This example illustrates how the operator would create dedicated PDBs per nodeSet (or group of nodeSets with similar roles) based on their roles and cluster health.

## Elasticsearch CRD Example

This CRD defines an Elasticsearch cluster with six nodeSets, each with different roles: master, data_hot, data_cold, coordinating, data_transform, and data_frozen.

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: elastic
spec:
  version: 8.16.1
  nodeSets:
  - name: master
    count: 3
    config:
      node.roles: ["master"]
  - name: data_hot
    count: 4
    config:
      node.roles: ["data_hot"]
  - name: data_cold
    count: 3
    config:
      node.roles: ["data_cold"]
  - name: coordinating
    count: 2
    config:
      node.roles: []
  - name: data-transform
    count: 2
    config:
      node.roles: ["transform"]
  - name: data-frozen
    count: 3
    config:
      node.roles: ["data_frozen"]
```

## Resulting PodDisruptionBudgets

Using the previously described approach, the ECK operator will automatically create dedicated PDBs for each nodeSet, with `maxUnavailable: 1` set based on the nodeSet's role and cluster health. Below are the PDBs that would be generated for the above CRD. Note that the operator groups nodeSets by their roles and applies the appropriate disruption policy.

### 1. PDB for Master NodeSet
- **Role**: Master
- **Policy**: Allow `maxUnavailable: 1` if the cluster is yellow or green.

```yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: elasticsearch-es-master-pdb
  namespace: elastic
  labels:
    elasticsearch.k8s.elastic.co/cluster-name: elasticsearch
  ownerReferences:
  - apiVersion: elasticsearch.k8s.elastic.co/v1
    kind: Elasticsearch
    name: elasticsearch
    blockOwnerDeletion: true
    controller: true
spec:
  maxUnavailable: 1
  selector:
    matchExpressions:
      - { key: elasticsearch.k8s.elastic.co/cluster-name, operator: In, values: [elasticsearch] }
      - { key: elasticsearch.k8s.elastic.co/statefulset-name, operator: In, values: [elasticsearch-es-master] }
```

### 2. PDB for Data NodeSet (data_hot, data_cold)
- **Role**: Data (data_hot, data_cold)
- **Policy**: Allow `maxUnavailable: 1` only if the cluster is green (most conservative due to mixed data roles).

```yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: elasticsearch-es-data-pdb
  namespace: elastic
  labels:
    elasticsearch.k8s.elastic.co/cluster-name: elasticsearch
  ownerReferences:
  - apiVersion: elasticsearch.k8s.elastic.co/v1
    kind: Elasticsearch
    name: elasticsearch
    blockOwnerDeletion: true
    controller: true
spec:
  maxUnavailable: 1
  selector:
    matchExpressions:
        - { key: elasticsearch.k8s.elastic.co/cluster-name, operator: In, values: [elasticsearch] }
        - { key: elasticsearch.k8s.elastic.co/statefulset-name, operator: In, values: [elasticsearch-es-data-hot, elasticsearch-es-data-cold] }
```

### 3. PDB for Coordinating NodeSet
- **Role**: Coordinating (no roles defined)
- **Policy**: Allow `maxUnavailable: 1` if the cluster is yellow or green (stateless, so more flexible).

```yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: elasticsearch-es-coordinating-pdb
  namespace: elastic
  labels:
    elasticsearch.k8s.elastic.co/cluster-name: elasticsearch
  ownerReferences:
  - apiVersion: elasticsearch.k8s.elastic.co/v1
    kind: Elasticsearch
    name: elasticsearch
    blockOwnerDeletion: true
    controller: true
spec:
  maxUnavailable: 1
  selector:
    matchExpressions:
      - { key: elasticsearch.k8s.elastic.co/cluster-name, operator: In, values: [elasticsearch] }
      - { key: elasticsearch.k8s.elastic.co/statefulset-name, operator: In, values: [elasticsearch-es-coordinating] }
```

### 4. PDB for Data Transform NodeSet
- **Role**: Transform
- **Policy**: Allow `maxUnavailable: 1` if the cluster is yellow or green (stateless, so more flexible).

```yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: elasticsearch-es-data-transform-pdb
  namespace: elastic
  labels:
    elasticsearch.k8s.elastic.co/cluster-name: elasticsearch
  ownerReferences:
  - apiVersion: elasticsearch.k8s.elastic.co/v1
    kind: Elasticsearch
    name: elasticsearch
    blockOwnerDeletion: true
    controller: true
spec:
  maxUnavailable: 1
  selector:
    matchExpressions:
      - { key: elasticsearch.k8s.elastic.co/cluster-name, operator: In, values: [elasticsearch] }
      - { key: elasticsearch.k8s.elastic.co/statefulset-name, operator: In, values: [elasticsearch-es-data-transform] }
```

### 5. PDB for Data Frozen NodeSet
- **Role**: Data Frozen
- **Policy**: Allow `maxUnavailable: 1` if the cluster is yellow or green (searchable snapshots reduce data-loss risk).

```yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: elasticsearch-es-data-frozen-pdb
  namespace: elastic
  labels:
    elasticsearch.k8s.elastic.co/cluster-name: elasticsearch
  ownerReferences:
  - apiVersion: elasticsearch.k8s.elastic.co/v1
    kind: Elasticsearch
    name: elasticsearch
    blockOwnerDeletion: true
    controller: true
spec:
  maxUnavailable: 1
  selector:
    matchExpressions:
      - { key: elasticsearch.k8s.elastic.co/cluster-name, operator: In, values: [elasticsearch] }
      - { key: elasticsearch.k8s.elastic.co/statefulset-name, operator: In, values: [elasticsearch-es-data-frozen] }
```

## Feedback

We believe the proposed change meets the main requirement of protecting Elasticsearch during external disruptions while still allowing quick rollouts of planned upgrades, but additional feedback is welcome. 

Pinging those involved in this issue: @akrzos-bw @sanderma @erdody @Tommmster @BenjaminHerbert @ebuildy
