### ISSUE TITLE
Cluster not formed in TestMutationHTTPSToHTTP: local volume reused

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#2937]
https://devops-ci.elastic.co/job/cloud-on-k8s-e2e-tests-stack-versions/62/testReport/

```
=== RUN   TestMutationHTTPSToHTTP/ES_cluster_health_should_eventually_be_green
Retries (5m0s timeout): ....................................................................................................
    TestMutationHTTPSToHTTP/ES_cluster_health_should_eventually_be_green: utils.go:84: 
        	Error Trace:	utils.go:84
        	Error:      	Received unexpected error:
        	            	health is unknown
        	Test:       	TestMutationHTTPSToHTTP/ES_cluster_health_should_eventually_be_green
```

It looks like the cluster never formed (even before the mutation was applied).
Logs on the ES nodes report no master node.

I'm considering this a bug until proven it's not.

**Comment by sebgl** [comment]
One of the node reports a weird `STALE_STATE_CONFIG`:

```
master not discovered or elected yet, an election requires a node with id [STALE_STATE_CONFIG], have discovered [{test-mutation-https-to-http-m6kd-es-masterdata-2}{B78hx00_TP-UiXTKho4r4A}{GmmXPDo4S4OAhEydH2EZfA}{10.14.34.24}{10.14.34.24:9300}{dilm}{ml.machine_memory=2147483648, xpack.installed=true, ml.max_open_jobs=20}, {test-mutation-https-to-http-m6kd-es-masterdata-1}{acyA4-gdSTOcprQCl0Dl8w}{1OwZW4gGT4WQ86t54ldBiQ}{10.14.32.40}{10.14.32.40:9300}{dilm}{ml.machine_memory=2147483648, ml.max_open_jobs=20, xpack.installed=true}, {test-mutation-https-to-http-m6kd-es-masterdata-0}{hRKFgCGyT3CRQ9YaPgJm7Q}{vUamjdJrTROJO7kOXWUcVw}{10.14.33.39}{10.14.33.39:9300}{dilm}{ml.machine_memory=2147483648, ml.max_open_jobs=20, xpack.installed=true}] which is not a quorum; discovery will continue using [127.0.0.1:9300, 127.0.0.1:9301, 127.0.0.1:9302, 127.0.0.1:9303, 127.0.0.1:9304, 127.0.0.1:9305, 10.14.32.40:9300, 10.14.33.39:9300] from hosts providers and [{test-mutation-https-to-http-m6kd-es-masterdata-2}{B78hx00_TP-UiXTKho4r4A}{GmmXPDo4S4OAhEydH2EZfA}{10.14.34.24}{10.14.34.24:9300}{dilm}{ml.machine_memory=2147483648, xpack.installed=true, ml.max_open_jobs=20}] from last-known cluster state; node term 1, last-accepted version 45 in term 1
```

**Comment by sebgl** [comment]
It looks like this failing node reused a data volume from a previous test one hour earlier: test-failure-kill-a-data-node-frf7.
It reports the same node ID and cluster UUID.

**Comment by sebgl** [comment]
That's the volume we talk about:

```yaml
{
            "apiVersion": "v1",
            "kind": "PersistentVolume",
            "metadata": {
                "annotations": {
                    "pv.kubernetes.io/bound-by-controller": "yes",
                    "pv.kubernetes.io/provisioned-by": "local-volume-provisioner-gke-eck-76-62-e2e-default-pool-5dd59f7e-j533"
                },
                "creationTimestamp": "2020-04-23T05:37:43Z",
                "finalizers": [
                    "kubernetes.io/pv-protection"
                ],
                "name": "local-pv-72d14209",
                "resourceVersion": "27210",
                "selfLink": "/api/v1/persistentvolumes/local-pv-72d14209",
                "uid": "8e0c7692-8524-11ea-9984-42010a9a00fe"
            },
            "spec": {
                "accessModes": [
                    "ReadWriteOnce"
                ],
                "capacity": {
                    "storage": "368Gi"
                },
                "claimRef": {
                    "apiVersion": "v1",
                    "kind": "PersistentVolumeClaim",
                    "name": "elasticsearch-data-test-mutation-https-to-http-m6kd-es-masterdata-2",
                    "namespace": "e2e-bz7ps-mercury",
                    "resourceVersion": "27198",
                    "uid": "a9447fdc-852a-11ea-9978-42010a9a00fc"
                },
                "local": {
                    "path": "/mnt/disks/pvs/pv-7"
                },
                "nodeAffinity": {
                    "required": {
                        "nodeSelectorTerms": [
                            {
                                "matchExpressions": [
                                    {
                                        "key": "kubernetes.io/hostname",
                                        "operator": "In",
                                        "values": [
                                            "gke-eck-76-62-e2e-default-pool-5dd59f7e-j533"
                                        ]
                                    }
                                ]
                            }
                        ]
                    }
                },
                "persistentVolumeReclaimPolicy": "Delete",
                "storageClassName": "e2e-default",
                "volumeMode": "Filesystem"
            },
            "status": {
                "phase": "Bound"
            }
        },
```
