### ISSUE TITLE
elasticsearch Pending 

### ISSUE THREAD

**Issue by willzhang** [elastic/cloud-on-k8s#2961]
instlal operator
```
kubectl apply -f https://download.elastic.co/downloads/eck/1.0.1/all-in-one.yaml
```
run elasticsearch cluster
```
cat <<EOF | kubectl apply -f -
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.6.2
  nodeSets:
  - name: default
    count: 1
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false
EOF
```
pod pending

```
[root@master01 ~]# kubectl get pods
NAME                       READY   STATUS    RESTARTS   AGE
quickstart-es-default-0    0/1     Pending   0          2m37s

[root@master01 ~]# kubectl get pvc
NAME                                         STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
elasticsearch-data-quickstart-es-default-0   Pending                                                     23s
```
how can i change the storage class name , my storage cluster name not standard.
