### ISSUE TITLE
Admission webhook does not seem to work on Openshift 3.11

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#2962]
It may "just" be due to the way we install Openshift though, that does not [enable the admission controller](https://github.com/openshift/openshift-ansible/issues/7983#issuecomment-394330604).

**Comment by sebgl** [comment]
I just tested on Minishift for version 3.11. The admission add-on isn't enabled by default.
I got admission webhooks working correctly after running:
```
minishift apply admissions-webhook
```

So I'm pretty sure the "problem" here is just our default Openshift 3.11 playbooks that don't enable the admission controller by default.

**Comment by sebgl** [comment]
Got it working with our Openshift 3.11 cluster from ansible playbooks, by:
* ssh-ing into the master host
* modifying `/etc/origin/master/master-config.yaml` to add the following:
```
admissionConfig:                                                                                                                                                                                                                                                              
  pluginConfig:                                                                                                                                                                                                                                                               
    ValidatingAdmissionWebhook:                                                                                                                                                                                                                                               
      configuration: {kind: DefaultAdmissionConfig, apiVersion: v1, disable: false} 
```
* restart apiserver and controllers:
```
/usr/local/bin/master-restart api
/usr/local/bin/master-restart controllers
``` 

So I would consider there's no bug here. Just that the admission controller is not enabled by default.
