### ISSUE TITLE
Why there are multiple pvc？

### ISSUE THREAD

**Issue by wajika** [elastic/cloud-on-k8s#3008]
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: elastic-local-volume
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-data-pv-1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: elastic-local-volume
  local:
    path: /data/elastic-pv1/
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - 'node-2'
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-data-pv-2
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: elastic-local-volume
  local:
    path: /data/elastic-pv2/
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - 'node-2'




apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic
spec:
  version: 7.6.2
  image: ccr.ccs.tencentyun.com/elk-oss/elasticsearch:7.6.2
  nodeSets:
  - name: elastic-master
    count: 2
    config:
      node.master: true
      node.data: false
      node.ingest: false
      node.ml: false
      node.store.allow_mmap: false
      index.store.type: niofs
      cluster.remote.connect: false
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: 4Gi
              cpu: 2
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms2g -Xmx4g"
    volumeClaimTemplates:
    - metadata:
        name: elastic-master-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
        storageClassName: elastic-local-volume
```

 

![image](https://user-images.githubusercontent.com/17058349/80565486-28ba2e00-8a23-11ea-8cc9-2963afc36066.png)

elasticsearch-data-elastic-es-elastic-master-0
elasticsearch-data-elastic-es-elastic-master-1
How does "elasticsearch-data" appear?

Why does elasticsearch pod show "pod has unbound immediate PersistentVolumeClaims"
