### ISSUE TITLE
es service type can't change to NodePort from yaml file

### ISSUE THREAD

**Issue by willzhang** [elastic/cloud-on-k8s#3009]
## Proposal

**Use case. Why is this important?**

## Bug Report
**What did you do?**
install operator
```
kubectl apply -f https://download.elastic.co/downloads/eck/1.0.1/all-in-one.yaml
```
install es
```
cat > eck-es.yaml <<EOF
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.6.2
  nodeSets:
  - name: default
    count: 3
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: openebs-jiva-default
    http:
      service:
        spec:
          type: NodePort
EOF
```

**What did you expect to see?**

i hope es service type is NodePort

**What did you see instead? Under which circumstances?**

quickstart-es-http  type is still ClusterIP type

```
[root@master01 ~]# kubectl get svc
NAME                    TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)    AGE
kubernetes              ClusterIP   10.96.0.1    <none>        443/TCP    52m
quickstart-es-default   ClusterIP   None         <none>        <none>     5m49s
quickstart-es-http      ClusterIP   10.98.17.1   <none>        9200/TCP   5m50s
```

**Environment**

* ECK version:

1.0.1

* Kubernetes information:

install k8s cluster with kubeadm ,

```
[root@master01 ~]# kubectl version --short
Client Version: v1.18.2
Server Version: v1.18.2
```

## question
why the configuration is not avaliabel for es ,
```
    http:
      service:
        spec:
          type: NodePort
```

i config it in kibana is ok 
```
cat > eck-kibana.yaml <<EOF
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
spec:
  version: 7.6.2
  count: 1
  elasticsearchRef:
    name: quickstart
  http:
    service:
      spec:
        type: NodePort
EOF
```
follow is my reference
https://github.com/elastic/cloud-on-k8s/blob/master/config/samples/elasticsearch/elasticsearch.yaml

**Comment by sebgl** [comment]
@willzhang the `service` section is not at the right level of indentation in your yaml example. It should be under the top-level `spec`, not under a particular nodeSet.

```yaml
cat > eck-es.yaml <<EOF
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.6.2
  nodeSets:
  - name: default
    count: 3
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: openebs-jiva-default
  http:
    service:
      spec:
        type: NodePort
EOF
```
