### ISSUE TITLE
I changed elastic CR but changes are not effecting.

### ISSUE THREAD

**Issue by bikkinamahesh369** [elastic/cloud-on-k8s#3013]
My current CR:

```
apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: eck
  namespace: elastic
spec:
  version: 7.2.0
  nodeSets:
  - count: 3
    name: data
    config:
      xpack.security.authc.realms: &xpack-realms
        file.file1:
          order: 0
        native.native1:
          order: 1
      node.master: false
      node.data: true
      node.ingest: false
      node.ml: false
      cluster.remote.connect: false
      thread_pool.write.queue_size: 500
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        containers:
        - name: elasticsearch
          env:
           - name: ES_JAVA_OPTS
             value: -Xms12g -Xmx12g
          resources:
            limits:
              memory: 24Gi
              cpu: 4000m
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        storageClassName: elastic-block
        resources:
          requests:
            storage: 250Gi
  - count: 1
    name: master
    config:
      xpack.security.authc.realms: &xpack-realms
        file.file1:
          order: 0
        native.native1:
          order: 1

      node.master: true
      node.data: false
      node.ingest: false
      node.ml: false
      cluster.remote.connect: false
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        containers:
        - name: elasticsearch
          env:
           - name: ES_JAVA_OPTS
             value: -Xms12g -Xmx12g
          resources:
            limits:
              memory: 24Gi
              cpu: 4000m
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        storageClassName: elastic-block
        resources:
          requests:
            storage: 100Gi
  - count: 2
    name: master-ingress
    config:
      xpack.security.authc.realms: &xpack-realms
        file.file1:
          order: 0
        native.native1:
          order: 1
      node.master: true
      node.data: false
      node.ingest: true
      node.ml: false
      cluster.remote.connect: false
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        containers:
        - name: elasticsearch
          env:
           - name: ES_JAVA_OPTS
             value: -Xms12g -Xmx12g
          resources:
            limits:
              memory: 24Gi
              cpu: 4000m
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        storageClassName: elastic-block
        resources:
          requests:
            storage: 100Gi
```

Now I updated to 

```
apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: eck
  namespace: elastic
spec:
  version: 7.2.0
  nodeSets:
  - count: 4
    name: data
    config:
      xpack.security.authc.realms: &xpack-realms
        file.file1:
          order: 0
        native.native1:
          order: 1
      node.master: false
      node.data: true
      node.ingest: false
      node.ml: false
      cluster.remote.connect: false
      thread_pool.write.queue_size: 500
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        - name: pem-to-truststore
          env:
          - name: truststore_jks
            value: /var/run/secrets/keystore/truststore.jks
          - name: cafile
            value: /var/run/secrets/certs/tls.crt
          - name: password
            value: changeit
          - name: alias
            value: s3cert
          command: ['/bin/bash']
          args: ['-c', "/usr/share/elasticsearch/jdk/bin/keytool -import -alias $alias -file $cafile -keystore $truststore_jks -deststorepass $password -noprompt "]
          volumeMounts:
           - name: keystore-volume
             mountPath: /var/run/secrets/keystore
           - name: s3-internal-certs
             mountPath: /var/run/secrets/certs
        - name: install-plugins
          env:
           - name: ES_JAVA_OPTS
             value: -Dhttp.proxyHost=10.20.48.24 -Dhttp.proxyPort=8080 -Dhttps.proxyHost=10.20.48.24 -Dhttps.proxyPort=8080
          command:
          - sh
          - -c
          - |
            bin/elasticsearch-plugin install --batch  repository-s3
        containers:
        - name: elasticsearch
          env:
           - name: ES_JAVA_OPTS
             value: -Xms1g -Xmx1g -Djavax.net.ssl.trustStore=/var/run/secrets/keystore/truststore.jks -Djavax.net.ssl.trustStorePassword=changeit  -Djavax.net.ssl.trustStoreType=jks
          resources:
            limits:
              memory: 2Gi
              cpu: 1000m
          volumeMounts:
          - mountPath: /var/run/secrets/keystore
            name: keystore-volume
          - name: s3-internal-certs
            mountPath: /var/run/secrets/certs
        volumes:
         - name: keystore-volume
           emptyDir: {}
         - name: s3-internal-certs
           secret:
            secretName: s3-internal-certs

    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        storageClassName: elastic-block
        resources:
          requests:
            storage: 100Gi
  - count: 1
    name: master
    config:
      xpack.security.authc.realms: &xpack-realms
        file.file1:
          order: 0
        native.native1:
          order: 1

      node.master: true
      node.data: false
      node.ingest: false
      node.ml: false
      cluster.remote.connect: false
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        - name: pem-to-truststore
          env:
          - name: truststore_jks
            value: /var/run/secrets/keystore/truststore.jks
          - name: cafile
            value: /var/run/secrets/certs/tls.crt
          - name: password
            value: changeit
          - name: alias
            value: s3cert
          command: ['/bin/bash']
          args: ['-c', "/usr/share/elasticsearch/jdk/bin/keytool -import -alias $alias -file $cafile -keystore $truststore_jks -deststorepass $password -noprompt "]
          volumeMounts:
           - name: keystore-volume
             mountPath: /var/run/secrets/keystore
           - name: s3-internal-certs
             mountPath: /var/run/secrets/certs
        - name: install-plugins
          env:
           - name: ES_JAVA_OPTS
             value: -Dhttp.proxyHost=10.20.48.24 -Dhttp.proxyPort=8080 -Dhttps.proxyHost=10.20.48.24 -Dhttps.proxyPort=8080
          command:
          - sh
          - -c
          - |
            bin/elasticsearch-plugin install --batch  repository-s3
        containers:
        - name: elasticsearch
          env:
           - name: ES_JAVA_OPTS
             value: -Xms1g -Xmx1g -Djavax.net.ssl.trustStore=/var/run/secrets/keystore/truststore.jks -Djavax.net.ssl.trustStorePassword=changeit  -Djavax.net.ssl.trustStoreType=jks
          resources:
            limits:
              memory: 2Gi
              cpu: 1000m
          volumeMounts:
          - mountPath: /var/run/secrets/keystore
            name: keystore-volume
          - name: s3-internal-certs
            mountPath: /var/run/secrets/certs
        volumes:
         - name: keystore-volume
           emptyDir: {}
         - name: s3-internal-certs
           secret:
            secretName: s3-internal-certs
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        storageClassName: elastic-block
        resources:
          requests:
            storage: 100Gi
  - count: 2
    name: master-ingress
    config:
      xpack.security.authc.realms: &xpack-realms
        file.file1:
          order: 0
        native.native1:
          order: 1
      node.master: true
      node.data: false
      node.ingest: true
      node.ml: false
      cluster.remote.connect: false
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        - name: pem-to-truststore
          env:
          - name: truststore_jks
            value: /var/run/secrets/keystore/truststore.jks
          - name: cafile
            value: /var/run/secrets/certs/tls.crt
          - name: password
            value: changeit
          - name: alias
            value: s3cert
          command: ['/bin/bash']
          args: ['-c', "/usr/share/elasticsearch/jdk/bin/keytool -import -alias $alias -file $cafile -keystore $truststore_jks -deststorepass $password -noprompt "]
          volumeMounts:
           - name: keystore-volume
             mountPath: /var/run/secrets/keystore
           - name: s3-internal-certs
             mountPath: /var/run/secrets/certs
        - name: install-plugins
          env:
           - name: ES_JAVA_OPTS
             value: -Dhttp.proxyHost=10.20.48.24 -Dhttp.proxyPort=8080 -Dhttps.proxyHost=10.20.48.24 -Dhttps.proxyPort=8080
          command:
          - sh
          - -c
          - |
            bin/elasticsearch-plugin install --batch  repository-s3
        containers:
        - name: elasticsearch
          env:
           - name: ES_JAVA_OPTS
             value: -Xms1g -Xmx1g -Djavax.net.ssl.trustStore=/var/run/secrets/keystore/truststore.jks -Djavax.net.ssl.trustStorePassword=changeit  -Djavax.net.ssl.trustStoreType=jks
          resources:
            limits:
              memory: 2Gi
              cpu: 1000m
          volumeMounts:
          - mountPath: /var/run/secrets/keystore
            name: keystore-volume
          - name: s3-internal-certs
            mountPath: /var/run/secrets/certs
        volumes:
         - name: keystore-volume
           emptyDir: {}
         - name: s3-internal-certs
           secret:
            secretName: s3-internal-certs

    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        storageClassName: elastic-block
        resources:
          requests:
            storage: 100Gi
  secureSettings:
  - secretName: s3-secrets

```

Can someone please help me here.

If I delete old cluster start new cluster with updated configuration . it is working.  (but data loss)
But without deleting old cluster if I update with new configuration  on existing cluster. changes are not reflecting

**Comment by david-kow** [comment]
Hi @bikkinamahesh369. Did you look at operator logs - `kubectl logs -n elastic-system elastic-operator-0`? I think the issue is that you are trying to modify `volumeClaimTemplates` (from `250Gi` to `100Gi`) which is not allowed due to Kubernetes limitations. You can see the [docs](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-volume-claim-templates.html) for more context.

You can either:
1. avoid changing `volumeClaimTemplates`
2. rename the `nodeSet` that contains that `volumeClaimTemplate` you are modifying. This will cause the operator to create new underlying statefulset and migrate over the data.

**Comment by bikkinamahesh369** [comment]
I tried changing node name, but even though it not creating new stateful sets.
in elastic operator logs i could see only this log 
`{"level":"error","@timestamp":"2020-04-30T12:27:58.978Z","logger":"controller-runtime.controller","message":"Reconciler error","ver":"1.0.0-beta1-84792e30","controller":"kibana-controller","request":"moss-elastic/moss-eck","error":"Operation cannot be fulfilled on kibanas.kibana.k8s.elastic.co \"moss-eck\": the object has been modified; please apply your changes to the latest version and try again","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.1/pkg/internal/controller/controller.go:218\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.1/pkg/internal/controller/controller.go:192\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.1/pkg/internal/controller/controller.go:171\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:88"}
`

**Comment by bikkinamahesh369** [comment]
@david-kow hi David if you observe correctly I didn't change volume claim templates for existing nodes. It is same values as previous.

**Comment by david-kow** [comment]
The log doesn't seem connected with this issue. Is there anything else around the time you apply the config?

In your first comment I see moving from:
```
spec:
  version: 7.2.0
  nodeSets:
  - count: 3
    name: data
...
    volumeClaimTemplates:
      spec:
        resources:
          requests:
            storage: 250Gi
```
to:
```
spec:
  version: 7.2.0
  nodeSets:
  - count: 4
    name: data
...
    volumeClaimTemplates:
      spec:
        resources:
          requests:
            storage: 100Gi
```
These are lines 48 and 86 respectively.

Can you check whether it works if you keep storage at `250Gi`? 

You can also check events by running: `kubectl describe es eck -n elastic`. 

It could show `Failed to apply spec change: StatefulSet.apps "elasticsearch-sample-es-default" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden`
