### ISSUE TITLE
Allow easier management of config for Kibana (disable xpack)

### ISSUE THREAD

**Issue by leosunmo** [elastic/cloud-on-k8s#3027]
## Proposal
I am trying to deploy the `docker.elastic.co/kibana/kibana-oss:7.6.2` kibana Docker image since I do not want to enable authentication ( `xpack.security.enabled: false` ). While I tried to just disable the `xpack.security` setting in the Kibana CRD, it gets OOMKilled because of the mad optimise memory requirements (for example, 4GB in this example: https://discuss.elastic.co/t/dont-want-to-use-https-and-user-password/202332/5). This is not something I really want to pay every time Kibana gets restarted.

The obvious solution is to run the OSS image of Kibana as it presumably doesn't contain the xpack security features. However when you boot it up you get the following error:
```
{"type":"log","@timestamp":"2020-05-05T03:32:03Z","tags":["fatal","root"],"pid":6,"message":"{ Error: Unknown configuration key(s): \"xpack.license_management.ui.enabled\", \"xpack.monitoring.ui.container.elasticsearch.enabled\", \"xpack.security.encryptionKey\". Check for spelling errors and ensure that expected plugins are installed.\n    at ensureValidConfiguration (/usr/share/kibana/src/core/server/legacy/config/ensure_valid_configuration.js:46:11) code: 'InvalidConfig', processExitCode: 64, cause: undefined }"}

 FATAL  Error: Unknown configuration key(s): "xpack.license_management.ui.enabled", "xpack.monitoring.ui.container.elasticsearch.enabled", "xpack.security.encryptionKey". Check for spelling errors and ensure that expected plugins are installed.
```
This is because ECK injects a default config that contain these `xpack` config lines. I can't find a way to disable that or easily override it (possibly using https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-kibana-secure-settings.html# to overwrite the same path? That doesn't feel right).

**Environment**

* ECK version:
	1.1.0

* Kubernetes information:
v1.15.10 self-hosted on EC2.

**Default Kibana config**
```
k get secret logging-kb-config -o go-template='{{ index .data "kibana.yml"|base64decode }}'
elasticsearch:
  hosts:
  - http://logging-es-http.monitoring.svc:9200
  password: mahsecrets
  ssl:
    certificateAuthorities: /usr/share/kibana/config/elasticsearch-certs/ca.crt
    verificationMode: certificate
  username: monitoring-logging-kibana-user
server:
  host: "0"
  name: logging
  ssl:
    certificate: /mnt/elastic-internal/http-certs/tls.crt
    enabled: true
    key: /mnt/elastic-internal/http-certs/tls.key
xpack:
  license_management:
    ui:
      enabled: false
  monitoring:
    ui:
      container:
        elasticsearch:
          enabled: true
  security:
    encryptionKey: s3cretz
```
