### ISSUE TITLE
Kibana, Unable to revive connection to svc:9200

### ISSUE THREAD

**Issue by StefanSa** [elastic/cloud-on-k8s#3033]
## Bug Report
**What did you do?**
We rolled out eck (latest version) several times as a test and also restarted the kube nodes several times without any problems. Now when eck is rolled out again, kibana no longer gets a connection to the service.

**What did you expect to see?**
kibana dasboard

**What did you see instead? Under which circumstances?**
`Unable to revive connection: https://monitoring-elasticsearch-es-http.elastic-monitoring.svc:9200/"`

**Environment**

* ECK version: 1.1
	
* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* On premise = yes
	
	for each of them please give us the version you are using
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

* Resource definition:
```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: monitoring-elasticsearch
  namespace: elastic-monitoring
spec:
  version: 7.6.2
  updateStrategy:
    changeBudget:
      maxSurge: 2 # The default value is - 1, which means the new Pod will be created immediately, which will consume a lot of resources in an instant, and then replace the old Pod to upgrade
      maxUnavailable: 1 # The default is 1.
  podDisruptionBudget:
    spec:
      minAvailable: 1 # The default is 1.
      selector:
        matchLabels:
          elasticsearch.k8s.elastic.co/cluster-name: monitoring-elasticsearch # That is, the value of metadata.nam
  nodeSets:
  - name: master-eligible
    count: 3
    config:
      node.master: true
      node.data: false
      node.ingest: false
      node.ml: false
      node.store.allow_mmap: false
      xpack.ml.enabled: false
      cluster.remote.connect: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 32Gi
        storageClassName: openebs-hostpath-san
    podTemplate:
      metadata:
        labels:
          app: master-eligible
      spec:
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms10g -Xmx10g
          resources:
            requests:
              memory: 12Gi # The default is 2Gi.
              cpu: 2 # No restrictions by default
            limits:
              memory: 16Gi # The default is 2Gi.
              # cpu: # There is no definition here and no definition by default, so there is no limit
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
  - name: master-voting # Defining election nodes
    count: 1
    config:
      node.master: true
      node.voting_only: true # The default value is false
      node.data: false
      node.ingest: false
      node.ml: false
      node.store.allow_mmap: false
      xpack.ml.enabled: false
      cluster.remote.connect: false
    podTemplate:
      metadata:
        labels:
          app: master-voting
      spec:
        containers:
        - name: elasticsearch
          resources:
            requests:
              cpu: 1 # default is not set
              memory: 2Gi # default is 2Gi
            limits:
              cpu: 1 # default is not set
              memory: 2Gi # default is 2Gi
          env:
          - name: ES_JAVA_OPTS # default is 1 Gi
            value: -Xms1g -Xmx1g
        volumes:
        - name: elasticsearch-data
          emptyDir: {} # Use empty directory
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
  - name: ingest
    count: 1
    config:
      node.master: false
      node.data: false
      node.ingest: true
      node.ml: false
      node.store.allow_mmap: false
      cluster.remote.connect: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 32Gi
        storageClassName: openebs-hostpath-san
    podTemplate:
      metadata:
        labels:
          app: ingest
      spec:
        containers: # Define resource limits
        - name: elasticsearch
          resources:
            requests:
              cpu: 2 # No restrictions by default
              memory: 12Gi # The default is 2Gi.
            limits:
            # cpu: # There is no definition here and no definition by default, so there is no limit
              memory: 16Gi # The default is 2Gi.
          env:
          - name: ES_JAVA_OPTS # The default is 1Gi.
            value: -Xms10g -Xmx10g
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
  - name: coordinate
    count: 2
    config:
      node.master: false
      node.data: false
      node.ingest: false
      node.ml: false
      node.store.allow_mmap: false
      cluster.remote.connect: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 32Gi
        storageClassName: openebs-hostpath-san
    podTemplate:
      metadata:
        labels:
          app: coordinate
      spec:
        containers: # Define resource limits
        - name: elasticsearch
          resources:
            requests:
              cpu: 2 # No restrictions by default
              memory: 12Gi # The default is 2Gi.
            limits:
              # cpu: # There is no definition here and no definition by default, so there is no limit
              memory: 16Gi # The default is 2Gi.
          env:
          - name: ES_JAVA_OPTS # The default is 1Gi.
            value: -Xms8g -Xmx8g
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
  - name: data
    count: 9
    config:
      node.master: false
      node.data: true
      node.ingest: false
      node.ml: false
      node.store.allow_mmap: false
      cluster.remote.connect: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 110Gi
        storageClassName: openebs-hostpath-san
    podTemplate:
      metadata:
        labels:
          app: data
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    elasticsearch.k8s.elastic.co/cluster-name: monitoring-elasticsearch
                topologyKey: kubernetes.io/hostname
        containers: # Define resource limits
        - name: elasticsearch
          resources:
            requests:
              cpu: 2 # No restrictions by default
              memory: 24Gi # The default is 2Gi.
            limits:
              # cpu: # There is no definition here and no definition by default, so there is no limit
              memory: 32Gi # The default is 2Gi.
          env:
          - name: ES_JAVA_OPTS # The default is 1Gi.
            value: -Xms16g -Xmx16g
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: monitoring-elasticsearch
  namespace: elastic-monitoring
spec:
  version: 7.6.2
  count: 1
  elasticsearchRef: # Name of the connected es cluster
    name: monitoring-elasticsearch
  podTemplate:
    spec:
      containers:
      - name: kibana
        resources:
          requests:
            cpu: 1
            memory: 2Gi
          limits:
            memory: 8Gi

```

* Logs:
```
{"type":"log","@timestamp":"2020-05-11T14:12:25Z","tags":["warning","elasticsearch","data"],"pid":8,"message":"Unable to revive connection: https://monitoring-elasticsearch-es-http.elastic-monitoring.svc:9200/"}
{"type":"log","@timestamp":"2020-05-11T14:12:32Z","tags":["error","plugins","taskManager","taskManager"],"pid":8,"message":"Failed to poll for work: Error: Request Timeout after 30000ms"}
{"type":"response","@timestamp":"2020-05-11T14:12:03Z","tags":[],"pid":8,"method":"get","statusCode":200,"req":{"url":"/login","method":"get","headers":{"user-agent":"curl/7.29.0","host":"127.0.0.1:5601","accept":"*/*"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1"},"res":{"statusCode":200,"responseTime":30044,"contentLength":9},"message":"GET /login 200 30044ms - 9.0B"}
```
