### ISSUE TITLE
[META] Beat CRD

### ISSUE THREAD

**Issue by david-kow** [elastic/cloud-on-k8s#3040]
ECK will support a new Beat CRD that enables to deploy and manage any Beat.

### CRD

Spec (WIP):

```yaml
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata: ...
spec:
  type: filebeat

  elasticsearchRef:
    name: quickstart
    namespace: default
  version: 7.6.0
  image: ...
  serviceAccountName: sa-name
  
  preset: filebeat-k8s-autodiscover

  config: {}

  secureSettings:
  - secretName: my-secret

  daemonSet:
    podTemplate:
      containers:
      - name: filebeat

  # Alternatively to daemonSet:
  #deployment:
  #  podTemplate:
  #    containers:
  #    - name: metricbeat
```

### Work tracking

[Existing issues](https://github.com/elastic/cloud-on-k8s/issues?q=is%3Aissue+is%3Aopen+label%3A%3Abeats)
