### ISSUE TITLE
Update Openshift documentation re. APM Server deployment

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#3110]
With the merge of https://github.com/elastic/beats/pull/12905 Openshift users should be able to run the APM Server with the default, restricted, SCC and without any additional privileges.

Let's update our documentation when the PR is included in a release (should be 7.9).

**Comment by SeanPlacchetti** [comment]
@barkbay Just making sure I'm reading this correctly, after the 7.9 drop of Elasticsearch, we'll be able to deploy the beats from the ECK pattern without the block that's in the current examples for the beats:
```
    podTemplate:
      spec:
        securityContext:
          runAsUser: 0
```
But for now, the beats need to run as `user:0` and therefore will not run in OpenShift 3.11
