### ISSUE TITLE
How about add Ingest CRD for Elasticsearch.

### ISSUE THREAD

**Issue by leptonyu** [elastic/cloud-on-k8s#3127]
Then we can define pipelines in k8s config files.

**Comment by barkbay** [comment]
Hi, can you share more about your use case or any specific example you have in mind ?

Note that there are some [ongoing](https://github.com/elastic/cloud-on-k8s/issues/3040) [work](https://github.com/elastic/cloud-on-k8s/pull/3041) about supporting beats.

**Comment by leptonyu** [comment]
I want to deploy elk on k8s, but use ingest feature of elasticsearch in stead of logstash.

The problem is I can use k8s yaml to configure elasticsearch and filebeat. But I must use es restful api to create `Ingest pipeline` **manually**. 

If eck operator can define Ingest CRD, which can auto create ingests in elasticsearch, then I can deploy the whole stack automatically. Put ingest config in `FileBeat CRD` or `Elasticsearch CRD`  are good too.


I use two ingest pipeline in the following config.
```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: elastic-system
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |-
    filebeat.autodiscover.providers:
      - type: kubernetes
        node: ${NODE_NAME}
        hints.enabled: true
        templates:
          - condition:
              equals: 
                kubernetes.container.name: nginx-ingress-controller
            config:
              - type: container
                paths:
                - /var/log/containers/*${data.kubernetes.container.id}.log
                pipeline: nginx
          - condition:
              equals: 
                kubernetes.labels.lang: java
            config:
              - type: container
                paths:
                - /var/log/containers/*${data.kubernetes.container.id}.log
                pipeline: my_java_app
```
