### ISSUE TITLE
APM tracing enabled on ECK creates a service named "main"

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#3143]
I just ran ECK with APM tracing enabled and saw the following in the APM Kibana app:

![image](https://user-images.githubusercontent.com/1050393/82886550-f37ffd80-9f46-11ea-9634-b61a4e36bf0a.png)

I don't know where this `main` comes from.

**Comment by pebrc** [comment]
I am curious are there any transactions associated with it (does not seem to be the case looking at the screenshot)? It might also help to get the corresponding Elasticsearch document in case it contains any clues as to where this comes from.

**Comment by anyasabo** [comment]
@sebgl are you still having this happen? I couldn't reproduce it.
![Screen Shot 2020-07-22 at 2 14 41 PM](https://user-images.githubusercontent.com/1638148/88218517-c8074f80-cc25-11ea-9da5-123a21c76946.png)


Here's what I was using (assuming you already deployed the all in one previously):

```yaml
apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-server-quickstart
  namespace: elastic-system
spec:
  version: 7.8.0
  count: 1
  elasticsearchRef:
    name: quickstart
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
  namespace: elastic-system
spec:
  version: 7.8.0
  nodeSets:
  - name: default
    count: 1
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
  namespace: elastic-system
spec:
  version: 7.8.0
  count: 1
  elasticsearchRef:
    name: quickstart
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elastic-operator
  namespace: elastic-system
  labels:
    control-plane: elastic-operator
spec:
  selector:
    matchLabels:
      control-plane: elastic-operator
  serviceName: elastic-operator
  template:
    metadata:
      annotations:
        "co.elastic.logs/raw": "[{\"type\":\"container\",\"json.keys_under_root\":true,\"paths\":[\"/var/log/containers/*${data.kubernetes.container.id}.log\"],\"processors\":[{\"convert\":{\"mode\":\"rename\",\"ignore_missing\":true,\"fields\":[{\"from\":\"error\",\"to\":\"_error\"}]}},{\"convert\":{\"mode\":\"rename\",\"ignore_missing\":true,\"fields\":[{\"from\":\"_error\",\"to\":\"error.message\"}]}},{\"convert\":{\"mode\":\"rename\",\"ignore_missing\":true,\"fields\":[{\"from\":\"source\",\"to\":\"_source\"}]}},{\"convert\":{\"mode\":\"rename\",\"ignore_missing\":true,\"fields\":[{\"from\":\"_source\",\"to\":\"event.source\"}]}}]}]"
      labels:
        control-plane: elastic-operator
    spec:
      serviceAccountName: elastic-operator
      containers:
      - image: "docker.elastic.co/eck/eck-operator:1.2.0"
        name: manager
        args: ["manager", "--enable-webhook", "--log-verbosity=1"]
        env:
          - name: OPERATOR_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: WEBHOOK_SECRET
            value: elastic-webhook-server-cert
          - name: ELASTIC_APM_SECRET_TOKEN
            valueFrom:
              secretKeyRef:
                name: apm-server-quickstart-apm-token
                key: secret-token
          - name: ELASTIC_APM_VERIFY_SERVER_CERT
            value: "false"
          - name: ELASTIC_APM_SERVER_URL
            value: https://apm-server-quickstart-apm-http:8200
          - name: ENABLE_TRACING
            value: "true"
        resources:
          limits:
            cpu: 1
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 150Mi
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        volumeMounts:
          - mountPath: /tmp/k8s-webhook-server/serving-certs
            name: cert
            readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: elastic-webhook-server-cert
```
