### ISSUE TITLE
Configs containing key: null result in invalid config

### ISSUE THREAD

**Issue by david-kow** [elastic/cloud-on-k8s#3177]
Following up on https://github.com/elastic/cloud-on-k8s/pull/3041#discussion_r433766190.

When Beat config is updated with a config that contains any `key: null` kubectls patching internals will interpret this as an indication to delete `key` from the dictionary. This is the expected behavior (https://tools.ietf.org/html/rfc7396).

The `key: null` is used often in [processors configuration](https://www.elastic.co/guide/en/beats/filebeat/current/add-cloud-metadata.html). Given that:

1. We have to avoid this in our defaults, samples and docs. At least for processors, using empty dictionary (`{}`) instead should suffice and shouldn't change Beat behavior.
2. For users applying a config containing `key: null` we need to provide a feedback that this is likely to cause not intended behavior. We could: 
    1. validate `processors` path in the config specifically for empty entries 
    2. use `last-applied-config` annotation to figure out whether the resource sent reflects user intention

**Comment by sebgl** [comment]
One alternative way to avoid this problem would be to remove our `config` field entirely so there's no config interpreted by kubectl operations.
Instead we could only allow referencing configmaps/secrets that contain raw bytes (uninterpreted by k8s json/yaml processors):

```yaml
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: filebeat-sample
spec:
  type: filebeat
  version: 7.7.0
  elasticsearchRef:
    name: elasticsearch-sample
  configRef:
    secretName: my-config
---
apiVersion: v1
kind: Secret
metadata:
  name: my-config
type: Opaque
stringData:
  beat.yaml: |-
  filebeat.autodiscover.providers:
    - node: ${NODE_NAME}
      type: kubernetes
      templates:
      - config:
        - paths: ["/var/log/containers/*${data.kubernetes.container.id}.log"]
          type: container
    processors:
    - add_cloud_metadata: null
    - add_host_metadata: null
```

The downside is the lack of consistency with other CRDs: they all have the `config` field.
