### ISSUE TITLE
ECK 1.1.2: controller-version is not consistent

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#3180]
Resources created with ECK 1.1.2 are annotated with the previous patch version:

```yaml
apiVersion: v1
items:
- apiVersion: elasticsearch.k8s.elastic.co/v1
  kind: Elasticsearch
  metadata:
    annotations:
      common.k8s.elastic.co/controller-version: 1.1.1
...
```

I guess it is because the `VERSION` file has been [updated after the release](https://github.com/elastic/cloud-on-k8s/blob/1.1.2/VERSION). Updating this file manually before each release is an error prone procedure.

I'm wondering if we could generate this file automatically, either from `TAG_NAME` or from the current branch/tag.
