### ISSUE TITLE
Error 401 on /_security/user/_has_privileges

### ISSUE THREAD

**Issue by irizzant** [elastic/cloud-on-k8s#3215]
## Bug Report
**What did you do?**
I deployed ECK 1.1.2 with Istio service mesh

**What did you expect to see?**
ECK to be deployed without any errors reported by Istio

**What did you see instead? Under which circumstances?**
There are 401 errors in traffic to all nodes 
![image](https://user-images.githubusercontent.com/15982257/84317157-a0c05b80-ab6c-11ea-97a1-234661302d8b.png)

The logs states the error is the following  
`2020-06-10T15:30:43.520085374Z [2020-06-10T15:30:38.477Z] "POST /_security/user/_has_privileges HTTP/1.1" 401 - "-" "-" 121 441 1 0 "-" "-" "07ab8159-2577-9932-a06e-41b904765d04" "hulk-es-http.elastic-system.svc:9200" "127.0.0.1:9200" inbound|9200|http|hulk-es-http.elastic-system.svc.cluster.local 127.0.0.1:50444 172.17.34.12:9200 172.17.34.8:37374 outbound_.9200_._.hulk-es-http.elastic-system.svc.cluster.local default
`

**Environment**
IKS on VPC gen2

* ECK version: 
1.1.2

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* On premise ? NO
	* Cloud: GKE / EKS / AKS ? IKS, Kubernetes 1.17
	* Kubernetes distribution: Openshift / Rancher / PKS ? 
	
	for each of them please give us the version you are using
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6+IKS", GitCommit:"43e4e6c4d0732364dff505878c79211999c58e04", GitTreeState:"clean", BuildDate:"2020-05-20T20:29:26Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

```

* Resource definition:
```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: hulk
spec:
  version: 7.7.1
  http:
    tls: 
      selfSignedCertificate:
        disabled: true
  nodeSets:
  # Dedicated master nodes
  - name: master
    count: 2
    config:
      node.master: true
      node.data: false
      node.ingest: false
      node.ml: false
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
      metadata:
        annotations:
          traffic.sidecar.istio.io/includeInboundPorts: "*"
          traffic.sidecar.istio.io/excludeOutboundPorts: "9300"
          traffic.sidecar.istio.io/excludeInboundPorts: "9300"
  # Dedicated data nodes
  - name: data
    count: 2
    config:
      node.master: false
      node.data: true
      node.ingest: false
      node.ml: false
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
      metadata:
        annotations:
          traffic.sidecar.istio.io/includeInboundPorts: "*"
          traffic.sidecar.istio.io/excludeOutboundPorts: "9300"
          traffic.sidecar.istio.io/excludeInboundPorts: "9300"
  # Dedicated ingest nodes
  - name: ingest
    count: 1
    config:
      node.master: false
      node.data: false
      node.ingest: true
      node.ml: false
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
      metadata:
        annotations:
          traffic.sidecar.istio.io/includeInboundPorts: "*"
          traffic.sidecar.istio.io/excludeOutboundPorts: "9300"
          traffic.sidecar.istio.io/excludeInboundPorts: "9300"
  # Dedicated coordinator nodes
  - name: coordinator
    count: 1
    config:
      node.master: false
      node.data: false
      node.ingest: false
      node.ml: false
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
      metadata:
        annotations:
          traffic.sidecar.istio.io/includeInboundPorts: "*"
          traffic.sidecar.istio.io/excludeOutboundPorts: "9300"
          traffic.sidecar.istio.io/excludeInboundPorts: "9300"
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: elastic-istio
spec:
  version: 7.7.1
  count: 1
  elasticsearchRef:
    name: hulk
  http:
    tls: 
      selfSignedCertificate:
        disabled: true
```

* Logs:
```
insert operator logs or any relevant message to the issue here
```
