### ISSUE TITLE
Compatibility with Istio requirements

### ISSUE THREAD

**Issue by irizzant** [elastic/cloud-on-k8s#3225]
## Bug Report
**What did you do?**
 I deployed ECK 1.1.2 with Istio service mesh

**What did you expect to see?**
ECK to be compatible with [Istio requirements](https://istio.io/latest/docs/ops/deployment/requirements/)

**What did you see instead? Under which circumstances?**
I see that statefulsets are missing `app` and `version` labels.

Moreover, `istioctl analyze` reports:
```sh
$ istioctl analyze -n elastic-system
Info [IST0118] (Service elastic-webhook-server.elastic-system) Port name  (port: 443, targetPort: 9443) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service hulk-es-transport.elastic-system) Port name  (port: 9300, targetPort: 9300) doesn't follow the naming convention of Istio port.
```

**Environment**
 IKS on VPC gen2

* ECK version:
 1.1.2

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* On premise ? NO
	* Cloud: GKE / EKS / AKS ? IKS Kubernetes 1.17
	* Kubernetes distribution: Openshift / Rancher / PKS ?
	
	for each of them please give us the version you are using
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6+IKS", GitCommit:"43e4e6c4d0732364dff505878c79211999c58e04", GitTreeState:"clean", BuildDate:"2020-05-20T20:29:26Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

* Resource definition:
```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: hulk
spec:
  version: 7.7.1
  http:
    tls: 
      selfSignedCertificate:
        disabled: true
  nodeSets:
  # Dedicated master nodes
  - name: master
    count: 2
    config:
      node.master: true
      node.data: false
      node.ingest: false
      node.ml: false
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
      metadata:
        annotations:
          traffic.sidecar.istio.io/includeInboundPorts: "*"
          traffic.sidecar.istio.io/excludeOutboundPorts: "9300"
          traffic.sidecar.istio.io/excludeInboundPorts: "9300"
  # Dedicated data nodes
  - name: data
    count: 2
    config:
      node.master: false
      node.data: true
      node.ingest: false
      node.ml: false
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
      metadata:
        annotations:
          traffic.sidecar.istio.io/includeInboundPorts: "*"
          traffic.sidecar.istio.io/excludeOutboundPorts: "9300"
          traffic.sidecar.istio.io/excludeInboundPorts: "9300"
  # Dedicated ingest nodes
  - name: ingest
    count: 1
    config:
      node.master: false
      node.data: false
      node.ingest: true
      node.ml: false
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
      metadata:
        annotations:
          traffic.sidecar.istio.io/includeInboundPorts: "*"
          traffic.sidecar.istio.io/excludeOutboundPorts: "9300"
          traffic.sidecar.istio.io/excludeInboundPorts: "9300"
  # Dedicated coordinator nodes
  - name: coordinator
    count: 1
    config:
      node.master: false
      node.data: false
      node.ingest: false
      node.ml: false
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
      metadata:
        annotations:
          traffic.sidecar.istio.io/includeInboundPorts: "*"
          traffic.sidecar.istio.io/excludeOutboundPorts: "9300"
          traffic.sidecar.istio.io/excludeInboundPorts: "9300"
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: elastic-istio
spec:
  version: 7.7.1
  count: 1
  elasticsearchRef:
    name: hulk
  http:
    tls: 
      selfSignedCertificate:
        disabled: true
```

* Logs:
[manager.txt](https://github.com/elastic/cloud-on-k8s/files/4765703/manager.txt)
