### ISSUE TITLE
Allow configurable JVM options

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#323]
For now, we only hardcode `"-Xms%dM -Xmx%dM -Djava.security.properties=%s", heapSize, heapSize, version.SecurityPropsFile`

**Comment by nithril** [comment]
Is there already a release date associated to this issue? 

Thank you!

**Comment by sebgl** [comment]
@nithril can you share what you would like to achieve with JVM options override? That would help us prioritize this.

**Comment by nithril** [comment]
To configure the GC options (G1)

**Comment by sebgl** [comment]
https://github.com/elastic/cloud-on-k8s/pull/943 propagates user-defined environment variables from the ES spec's podTemplate to the pod.

We do override the `ES_JAVA_OPTS` with our own though, so this does not solve the issue.

We should probably should pass those settings through a file (`jvm.option`) - relates https://github.com/elastic/cloud-on-k8s/issues/931.

This way, the user-provided `ES_JAVA_OPTS` should be used on top of our defaults in `jvm.options`. We should first check that providing both `jvm.options` and `ES_JAVA_OPTS` does work in a way that suits us (giving priority to the environment variable but still considering what's in `jvm.options`).

**Comment by nrobert13** [comment]
I see an inconsistent propagation of the env var `ES_JAVA_OPTS`:
I have the following in my CR:
```
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms512M -Xmx768M"
          resources:
            limits:
              memory: 1Gi
              cpu: 500m
```
and when I check the pod I get: 
```
    env:
    - name: ES_JAVA_OPTS
      value: -Xms512M -Xmx512M -Djava.security.properties=/usr/share/elasticsearch/config/managed/security.properties
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 1Gi
```
1. Not sure where the Xmx512 is coming from, is neither the one requested by me (768M) nor the default (1024M).
2. also noticed that updating the ES_JAVA_OPTS and reapplying the manifest will not re-conciliate...
