### ISSUE TITLE
ElasticSearch: Back-off restarting failed container

### ISSUE THREAD

**Issue by sentatr** [elastic/cloud-on-k8s#3236]
## Proposal

**Use case. Why is this important?**

## Bug Report
**What did you do?**
 Install ECK on GKE, 7.7.0 version.
 
Install Elastic Search.

cat <<EOF | kubectl --request-timeout=1m apply -f -
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  image: ****/***********/elasticsearch:7.7.0
  version: "7.7.0"
  nodeSets:
  - name: default
    count: 1
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false
EOF

**What did you expect to see?

 Elastic search pod should up & running. 

**What did you see instead? Under which circumstances?**

Getting error on the pod,  ---> CrashLoopBackOff

kubectl describe po/quickstart-es-default-0
Warning  BackOff    5m9s (x118 over 30m)  ********  Back-off restarting failed container

**Environment**
Dev
* ECK version:

  1.1.1

* Kubernetes information:

	Cloud: GKE - 1.14
	
	for each of them please give us the version you are using
```
$ kubectl version

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10", GitCommit:"", GitTreeState:"clean", BuildDate:"2019-12-11T12:41:00Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.36", GitCommit:"", GitTreeState:"clean", BuildDate:"2020-04-06T16:33:17Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```
 

* Resource definition:
```
if relevant insert the resource definition
```

* Logs:
```
{"log.level":"info","@timestamp":"2020-06-12T17:13:49.260Z","log.logger":"driver","message":"ES cannot be reached yet, re-queuing","service.version":"1.1.1-b6f69fc4","service.type":"eck","ecs.version":"1.4.0","namespace":"default","es_name":"quickstart"}
```

**Comment by anyasabo** [comment]
The [logs](https://www.elastic.co/guide/en/cloud-on-k8s/1.1/k8s-troubleshooting-methods.html#k8s-get-elasticsearch-logs) of the failing pod will likely have more information needed to troubleshoot

**Comment by david-kow** [comment]
I'll close this due to inactivity. @sentatr feel free to reopen if you can provide us with some more information (logs) that are needed to investigate this.

**Comment by skorpion8909** [comment]
I got the same error.
**What did you do?**
```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elk-monitoring
  namespace: prod-elk
spec:
  monitoring:
    metrics:
      elasticsearchRefs:
      - name: elk-monitoring
        namespace: prod-elk
    logs:
      elasticsearchRefs:
      - name: elk-monitoring
        namespace: prod-elk
  version: 7.15.0
  nodeSets:
  - name: hot
    count: 1
    config:
      node.store.allow_mmap: false
      node.roles: ["master", "data", "ingest"]
      index.store.type: niofs
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
        namespace: prod-elk
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: premium-rwo
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: false
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        containers:
        - name: elasticsearch
          resources:
              requests:
                memory: 4Gi
                cpu: 4
              limits:
                memory: 16Gi
                cpu: 8

  http:
    service:
      spec:
        type: ClusterIP
        ports:
          - name: https
            port: 9200
            protocol: TCP
            targetPort: 9200
#            nodePort: 30001
  #transport:
```
**What did you expect to see?**

Elastic search pod should up & running.

**What did you see instead? Under which circumstances?**
kubectl get events
`2m27s       Warning   BackOff                    pod/elk-monitoring-es-hot-0                                        Back-off restarting failed container`

**Environment**
Dev

**ECK version:**

1.8

**Kubernetes information:**

Cloud: GKE - 1.21.5-gke.1302

for each of them please give us the version you are using

**$ kubectl version**

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5-gke.1302", GitCommit:"639f3a74abf258418493e9b75f2f98a08da29733", GitTreeState:"clean", BuildDate:"2021-10-21T21:35:48Z", GoVersion:"go1.16.7b7", Compiler:"gc", Platform:"linux/amd64"}

**Resource definition:**
if relevant insert the resource definition
Logs:
`error: a container name must be specified for pod elk-monitoring-es-hot-0, choose one of: [elasticsearch metricbeat filebeat] or one of the init containers: [elastic-internal-init-filesystem sysctl]`
