### ISSUE TITLE
Kibana fails when quickstart is followed

### ISSUE THREAD

**Issue by apenney** [elastic/cloud-on-k8s#3237]
## Bug Report
**What did you do?**

Followed the quickstart guide, both ES and kibana steps:

```
❯ cat elasticsearch.yaml 
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: staging
spec:
  version: 7.7.1
  nodeSets:
  - name: elasticsearch
    count: 1
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false

---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: staging
spec:
  version: 7.7.1
  count: 1
  elasticsearchRef:
    name: elasticsearch
```

**What did you expect to see?**

A working kibana!

**What did you see instead? Under which circumstances?**

I can see the cluster is green (and connect to it):

```
❯ kubectl get elasticsearch -n staging
NAME            HEALTH   NODES   VERSION   PHASE   AGE
elasticsearch   green    1       7.7.1     Ready   52m
```

But Kibana stays red:

```
❯ kubectl get kibana -n staging
NAME     HEALTH   NODES   VERSION   AGE
kibana   red              7.7.1     52m
```

If we look at the logs for kibana:

```
❯ kubectl logs kibana-kb-5c48f69679-s8gqd -n staging
{"type":"log","@timestamp":"2020-06-14T19:32:18Z","tags":["warning","plugins-discovery"],"pid":7,"message":"Expect plugin \"id\" in camelCase, but found: apm_oss"}
{"type":"log","@timestamp":"2020-06-14T19:32:18Z","tags":["warning","plugins-discovery"],"pid":7,"message":"Expect plugin \"id\" in camelCase, but found: file_upload"}
{"type":"log","@timestamp":"2020-06-14T19:32:18Z","tags":["warning","plugins-discovery"],"pid":7,"message":"Expect plugin \"id\" in camelCase, but found: triggers_actions_ui"}
{"type":"log","@timestamp":"2020-06-14T19:32:37Z","tags":["fatal","root"],"pid":7,"message":"{ ValidationError: child \"server\" fails because [child \"port\" fails because [\"port\" must be a number]]\n    at Object.exports.process (/usr/share/kibana/node_modules/joi/lib/errors.js:196:19)\n    at internals.Object._validateWithOptions (/usr/share/kibana/node_modules/joi/lib/types/any/index.js:675:31)\n    at module.exports.internals.Any.root.validate (/usr/share/kibana/node_modules/joi/lib/index.js:146:23)\n    at Config._commit (/usr/share/kibana/src/legacy/server/config/config.js:132:34)\n    at Config.set (/usr/share/kibana/src/legacy/server/config/config.js:103:10)\n    at Config.extendSchema (/usr/share/kibana/src/legacy/server/config/config.js:75:10)\n    at _lodash.default.each.child (/usr/share/kibana/src/legacy/server/config/config.js:64:14)\n    at arrayEach (/usr/share/kibana/node_modules/lodash/index.js:1315:13)\n    at Function.<anonymous> (/usr/share/kibana/node_modules/lodash/index.js:3393:13)\n    at Config.extendSchema (/usr/share/kibana/src/legacy/server/config/config.js:63:30)\n    at new Config (/usr/share/kibana/src/legacy/server/config/config.js:54:10)\n    at Function.withDefaultSchema (/usr/share/kibana/src/legacy/server/config/config.js:48:12)\n    at defaultConfig (/usr/share/kibana/src/legacy/plugin_discovery/find_plugin_specs.js:44:25)\n    at findLegacyPluginSpecs (/usr/share/kibana/src/core/server/legacy/plugins/find_legacy_plugin_specs.js:38:63)\n    at LegacyService.discoverPlugins (/usr/share/kibana/src/core/server/legacy/legacy_service.js:98:50) name: 'ValidationError' }"}

 FATAL  ValidationError: child "server" fails because [child "port" fails because ["port" must be a number]]
```

**Environment**

* ECK version:

I downloaded 1.1.2 today

* Kubernetes information:

	* Cloud: AWS
	* Kubernetes distribution: EKS
        * Kubernetes version: v1.16.8-eks-e16311
