### ISSUE TITLE
Cluster health went red during 1min when applying changes

### ISSUE THREAD

**Issue by mtparet** [elastic/cloud-on-k8s#3297]
## Bug Report
**What did you do?**

We applied changes on podTemplate spec to fix our `podAntiAffinity` which were missing `labelSelector`.

**What did you expect to see?**

No downtime. 

**What did you see instead? Under which circumstances?**
We have 4 data nodes, 2 ingest nodes and 3 master nodes.

During the reboot of the 4 data and 2 ingests nodes all were going well. But during (or after) the reboot of one the master, we observed that the cluster heath went `red`.

We observed in the logs that right after a new master was elected, it did not succeed to propagate this information to other masters node.

We observed also that new certificates were issued.

**Environment**

* ECK version:

1.1.0

* Kubernetes information:

AWS EKS 1.16

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.10", GitCommit:"f3add640dbcd4f3c33a7749f38baaac0b3fe810d", GitTreeState:"clean", BuildDate:"2020-05-20T14:00:52Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

```

* Resource definition:
```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 6.8.8
  nodeSets:
  - name: masters-zone-a
    count: 1
    config:
      node.master: true
      node.data: false
      node.ingest: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: gp2
    podTemplate:
      spec:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchLabels:
                    elasticsearch.k8s.elastic.co/cluster-name: elasticsearch
                    elasticsearch.k8s.elastic.co/node-master: "true"
                topologyKey: kubernetes.io/hostname
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: failure-domain.beta.kubernetes.io/zone
                  operator: In
                  values:
                  - eu-west-3a
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms2g -Xmx2g
          resources:
            requests:
              cpu: 200m
              memory: 3Gi
            limits:
              cpu: 500m
              memory: 3Gi
  - name: masters-zone-b
    count: 1
    config:
      node.master: true
      node.data: false
      node.ingest: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: gp2
    podTemplate:
      spec:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchLabels:
                    elasticsearch.k8s.elastic.co/cluster-name: elasticsearch
                    elasticsearch.k8s.elastic.co/node-master: "true"
                topologyKey: kubernetes.io/hostname
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: failure-domain.beta.kubernetes.io/zone
                  operator: In
                  values:
                  - eu-west-3b
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms2g -Xmx2g
          resources:
            requests:
              cpu: 200m
              memory: 3Gi
            limits:
              cpu: 500m
              memory: 3Gi
  - name: masters-zone-c
    count: 1
    config:
      node.master: true
      node.data: false
      node.ingest: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: gp2
    podTemplate:
      spec:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchLabels:
                    elasticsearch.k8s.elastic.co/cluster-name: elasticsearch
                    elasticsearch.k8s.elastic.co/node-master: "true"
                topologyKey: kubernetes.io/hostname
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: failure-domain.beta.kubernetes.io/zone
                  operator: In
                  values:
                  - eu-west-3c
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms2g -Xmx2g
          resources:
            requests:
              cpu: 200m
              memory: 3Gi
            limits:
              cpu: 500m
              memory: 3Gi
  - name: ingest-zone-a
    count: 1
    config:
      node.master: false
      node.data: false
      node.ingest: true

    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: gp2
    podTemplate:
      spec:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchLabels:
                    elasticsearch.k8s.elastic.co/cluster-name: elasticsearch
                    elasticsearch.k8s.elastic.co/node-ingest: "true"
                topologyKey: kubernetes.io/hostname
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: failure-domain.beta.kubernetes.io/zone
                  operator: In
                  values:
                  - eu-west-3a
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms2g -Xmx2g
          resources:
            requests:
              cpu: 500m
              memory: 3Gi
            limits:
              cpu: 1500m
              memory: 3Gi
  - name: ingest-zone-b
    count: 1
    config:
      node.master: false
      node.data: false
      node.ingest: true

    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: gp2
    podTemplate:
      spec:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchLabels:
                    elasticsearch.k8s.elastic.co/cluster-name: elasticsearch
                    elasticsearch.k8s.elastic.co/node-ingest: "true"
                topologyKey: kubernetes.io/hostname
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: failure-domain.beta.kubernetes.io/zone
                  operator: In
                  values:
                  - eu-west-3b
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms2g -Xmx2g
          resources:
            requests:
              cpu: 500m
              memory: 3Gi
            limits:
              cpu: 1500m
              memory: 3Gi
  - name: data-zone-a
    count: 2
    config:
      node.master: false
      node.data: true
      node.ingest: false
      node.attr.zone: eu-west-3a
      cluster.routing.allocation.awareness.attributes: zone
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 2200Gi
        storageClassName: gp2
    podTemplate:
      spec:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchLabels:
                    elasticsearch.k8s.elastic.co/cluster-name: elasticsearch
                    elasticsearch.k8s.elastic.co/node-data: "true"
                topologyKey: kubernetes.io/hostname
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: failure-domain.beta.kubernetes.io/zone
                  operator: In
                  values:
                  - eu-west-3a
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms12g -Xmx12g
          resources:
            requests:
              cpu: 3
              memory: 24Gi
            limits:
              cpu: 4
              memory: 24Gi
  - name: data-zone-b
    count: 2
    config:
      node.master: false
      node.data: true
      node.ingest: false
      node.attr.zone: eu-west-3b
      cluster.routing.allocation.awareness.attributes: zone
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 2200Gi
        storageClassName: gp2
    podTemplate:
      spec:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchLabels:
                    elasticsearch.k8s.elastic.co/cluster-name: elasticsearch
                    elasticsearch.k8s.elastic.co/node-data: "true"
                topologyKey: kubernetes.io/hostname
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: failure-domain.beta.kubernetes.io/zone
                  operator: In
                  values:
                  - eu-west-3b
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms12g -Xmx12g
          resources:
            requests:
              cpu: 3
              memory: 24Gi
            limits:
              cpu: 4
              memory: 24Gi
```

* Logs:

```
"Jun 19, 2020 @ 11:57:46.816","Certificate SANs do not match expected one, should issue new","{""log.level"":""info"",""@timestamp"":""2020-06-19T11:57:46.816Z"",""log.logger"":""transport"",""message"":""Certificate SANs do not match expected one, should issue new"",""service.version"":""1.1.0-29e7447f"",""service.type"":""eck"",""ecs.version"":""1.4.0"",""namespace"":""namespace-elasticsearch"",""pod_name"":""elasticsearch-api-es-data-zone-b-1""}
"
"Jun 19, 2020 @ 11:57:46.816","Issuing new certificate","{""log.level"":""info"",""@timestamp"":""2020-06-19T11:57:46.816Z"",""log.logger"":""transport"",""message"":""Issuing new certificate"",""service.version"":""1.1.0-29e7447f"",""service.type"":""eck"",""ecs.version"":""1.4.0"",""pod_name"":""elasticsearch-api-es-data-zone-b-1""}
"

"Jun 19, 2020 @ 12:05:52.589",,"org.elasticsearch.discovery.MasterNotDiscoveredException: null
"
"Jun 19, 2020 @ 12:05:52.589",,"	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$4.onTimeout(TransportMasterNodeAction.java:262) [elasticsearch-6.8.8.jar:6.8.8]
"
"Jun 19, 2020 @ 12:05:52.589",,"	at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:322) [elasticsearch-6.8.8.jar:6.8.8]
"
"Jun 19, 2020 @ 12:05:52.589",,"	at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:249) [elasticsearch-6.8.8.jar:6.8.8]
"
"Jun 19, 2020 @ 12:05:52.589",,"	at org.elasticsearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:564) [elasticsearch-6.8.8.jar:6.8.8]
"
"Jun 19, 2020 @ 12:05:52.589",,"	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:681) [elasticsearch-6.8.8.jar:6.8.8]
"
"Jun 19, 2020 @ 12:05:52.589",,"	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
"
"Jun 19, 2020 @ 12:05:52.589",,"	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
"
"Jun 19, 2020 @ 12:05:52.589",,"	at java.lang.Thread.run(Thread.java:832) [?:?]
```

Full logs https://gist.github.com/mtparet/57c3293a266d74df4106d492528d05f5
