### ISSUE TITLE
Add support for the "node.roles" setting

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#3324]
With Elasticsearch 7.9 the individual settings `node.*` are deprecated in favor of a `node.roles` setting.

Related ES PR:
* main branch: https://github.com/elastic/elasticsearch/pull/54998
* For 7.x https://github.com/elastic/elasticsearch/pull/58512

We need to update several places in the code where ECK relies on the `node.*` attributes to detect the nature of a node:

* Validation function
* When we set the labels on the Pods

Note that it is not possible for the user to use both the legacy method and the new one:

e.g.

```yaml
config:
node.master: true
node.roles:
    - data
```

produces the following error:

```
java.lang.IllegalArgumentException: can not explicitly configure node roles and use legacy role setting [node.master]=[true]
```

_See https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/cluster/node/DiscoveryNode.java#L57 for implementation details_

A concern I have is that it does not seem possible to render an empty array with ucfg, I did a few tests and the following manifest:

```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 8.0.0
  image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0-SNAPSHOT
  nodeSets:
    - name: coordinating
      podTemplate:
        spec:
          securityContext:
            runAsUser: 1000
            fsGroup: 1000
      count: 1
      config:
        node.roles: []
        node.store.allow_mmap: false
...
```

is rendered as:

```
node:
  roles: null
  store:
    allow_mmap: false
```

Which produces the following error: 

```
Exception in thread "main" org.elasticsearch.ElasticsearchParseException: null-valued setting found for key [node.roles] found at line number [10], column number [10]
```
