### ISSUE TITLE
Keystore file created by initContainer is not accessible by the elasticsearch user 

### ISSUE THREAD

**Issue by smahalingam** [elastic/cloud-on-k8s#3332]
## Bug Report
**What did you do?**
I tried setting up Elasticsearch cluster using ECK Operator. I attached the secrets using ```secureSettings``` and ran the container as ```elasticsearch``` user. 

**What did you expect to see?**
Container should run as `elasticsearch`  user 

**What did you see instead? Under which circumstances?**
File access permission
`Exception in thread "main" java.nio.file.AccessDeniedException: /usr/share/elasticsearch/config/elasticsearch.keystore
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:375)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:426)
	at org.apache.lucene.store.SimpleFSDirectory.openInput(SimpleFSDirectory.java:77)
	at org.elasticsearch.common.settings.KeyStoreWrapper.load(KeyStoreWrapper.java:220)
	at org.elasticsearch.common.settings.HasPasswordKeyStoreCommand.execute(HasPasswordKeyStoreCommand.java:42)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:91)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.common.settings.KeyStoreCli.main(KeyStoreCli.java:43)
Exception in thread "main" org.elasticsearch.bootstrap.BootstrapException: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/config/elasticsearch.keystore`

**Environment**

* ECK version:
	1.1.0

* Kubernetes information:

It's running on GKE. K8s version - v1.14.10-gke.36  

* Resource definition:
```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version:  7.7.0
  secureSettings:
    - secretName: gcs-bucket-credentials
  nodeSets:
  - name: default
    count: 1
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
```

**Root cause of issue:**
I looked at commands run in the initContainer `elastic-internal-init-keystore`. It creates keystore fie as `root` user but doesn't give access to `elasticsearch` user.

```/usr/bin/env
      bash
      -c
      #!/usr/bin/env bash

      set -eux

      echo "Initializing keystore."

      # create a keystore in the default data path
      /usr/share/elasticsearch/bin/elasticsearch-keystore create

      # add all existing secret entries into it
      for filename in  /mnt/elastic-internal/secure-settings/*; do
        [[ -e "$filename" ]] || continue # glob does not match
        key=$(basename "$filename")
        echo "Adding "$key" to the keystore."
        /usr/share/elasticsearch/bin/elasticsearch-keystore add-file "$key" "$filename"
      done

      echo "Keystore initialization successful."```

**Comment by barkbay** [comment]
Use `fsGroup` at the `Pod` level in order for the keystore volume to be readable by all the containers:

```yaml
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version:  7.7.0
  secureSettings:
    - secretName: es-secret
  nodeSets:
    - name: default
      count: 1
      config:
        node.master: true
        node.data: true
        node.ingest: true
        node.store.allow_mmap: false
      podTemplate:
        spec:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
```
