### ISSUE TITLE
Error during compatibility check: context deadline exceeded

### ISSUE THREAD

**Issue by laverya** [elastic/cloud-on-k8s#3441]
## Bug Report
**What did you do?**
Created an elasticsearch resource.

```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: myname
  namespace: mynamespace
spec:
  version: 7.8.0
  nodeSets:
  - name: zone-b
    count: 1
    config:
      node.attr.zone: us-east-1b
      cluster.routing.allocation.awareness.attributes: zone
    podTemplate:
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: failure-domain.beta.kubernetes.io/zone
                  operator: In
                  values:
                  - us-east-1b
                - key: <an additional scheduling constraint>
                  operator: In
                  values:
                  - elasticsearch
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms2g -Xmx2g
          resources:
            requests:
              memory: 4Gi
              cpu: 0.5
            limits:
              memory: 4Gi
              cpu: 2
    volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data-east1b
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
          storageClassName: gp2
  - name: zone-d
    count: 1
    config:
      node.attr.zone: us-east-1d
      cluster.routing.allocation.awareness.attributes: zone
    podTemplate:
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: failure-domain.beta.kubernetes.io/zone
                  operator: In
                  values:
                  - us-east-1d
                - key: <an additional scheduling constraint>
                  operator: In
                  values:
                  - elasticsearch
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms2g -Xmx2g
          resources:
            requests:
              memory: 4Gi
              cpu: 0.5
            limits:
              memory: 4Gi
              cpu: 2
    volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data-east1d
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
          storageClassName: gp2
```

**What did you expect to see?**
An elasticsearch cluster is created in response.

**What did you see instead? Under which circumstances?**
I see CompatibilityCheckError. Forever.

```
Events:
  Type     Reason                   Age                   From                      Message
  ----     ------                   ----                  ----                      -------
  Warning  CompatibilityCheckError  52s (x15 over 9m14s)  elasticsearch-controller  Error during compatibility check: context deadline exceeded
```

**Environment**

* ECK version:

uses image: `docker.elastic.co/eck/eck-operator:1.1.2`

* Kubernetes information:

	* Cloud: EKS v1.16.8-eks-e16311
	
	for each of them please give us the version you are using
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-18T02:59:13Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

* Resource definition:
applied from https://download.elastic.co/downloads/eck/1.1.2/all-in-one.yaml

* Logs:
in the operator logs:

```
{"log.level":"info","@timestamp":"2020-07-15T23:00:44.867Z","log.logger":"elasticsearch-controller","message":"Starting reconciliation run","service.version":"1.1.1-f13b6d26","service.type":"eck","ecs.version":"1.4.0","iteration":25,"namespace":"auditlog-platform","es_name":"auditlog-platform"}
{"log.level":"info","@timestamp":"2020-07-15T23:01:14.870Z","log.logger":"elasticsearch-controller","message":"Ending reconciliation run","service.version":"1.1.1-f13b6d26","service.type":"eck","ecs.version":"1.4.0","iteration":25,"namespace":"auditlog-platform","es_name":"auditlog-platform","took":30.003203397}
{"log.level":"error","@timestamp":"2020-07-15T23:01:14.870Z","log.logger":"controller-runtime.controller","message":"Reconciler error","service.version":"1.1.1-f13b6d26","service.type":"eck","ecs.version":"1.4.0","controller":"elasticsearch-controller","request":"auditlog-platform/auditlog-platform","error":"context deadline exceeded","error.stack_trace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:88"}
{"log.level":"info","@timestamp":"2020-07-15T23:01:14.890Z","log.logger":"elasticsearch-controller","message":"Starting reconciliation run","service.version":"1.1.1-f13b6d26","service.type":"eck","ecs.version":"1.4.0","iteration":26,"namespace":"auditlog-platform","es_name":"auditlog-platform"}
```

Repeated many, many times.
