### ISSUE TITLE
APM Server and Beats are unable to start if association to Kibana without TLS is specified

### ISSUE THREAD

**Issue by david-kow** [elastic/cloud-on-k8s#3523]
### Order of events
1. TLS in Kibana is disabled, so a Secret with public cert is [not created](https://github.com/elastic/cloud-on-k8s/blob/986aea4763a4ff019d0f3c44bbe1a4471c6ad716/pkg/controller/common/certificates/reconcile.go#L60).
2. Association controller [tries to fetch](https://github.com/elastic/cloud-on-k8s/blob/986aea4763a4ff019d0f3c44bbe1a4471c6ad716/pkg/controller/association/ca.go#L38) that Secret of the referenced resource when setting Accociation config on association holder resource. E.g.: Kibana-Beat association controller tries to fetch public-certs Secret for Kibana.
3. When that Secret can't be found, association controller assumes that it wasn't yet created and returns [an empty struct](https://github.com/elastic/cloud-on-k8s/blob/986aea4763a4ff019d0f3c44bbe1a4471c6ad716/pkg/controller/association/ca.go#L40). 
4. When APM Server and Beat controllers validate referenced resources with `IsConfiguredIfSet` -> ` IsConfigured()` -> `CAIsConfigured()` function chain the `CASecretName` is expected to be [not empty](https://github.com/elastic/cloud-on-k8s/blob/986aea4763a4ff019d0f3c44bbe1a4471c6ad716/pkg/apis/common/v1/association.go#L97). But it is, because an empty struct was used to set it.
5. Reconciliation ends and event regarding association not being configured is posted.

### Potential fix
We should check whether CA (with `GetCACertProvided()`) was provided at all and only then expect the `CASecretName` to be present. 

### Repro:
<details>
  <summary>Click to see repro steps</summary>

```
cat << EOF | kubectl apply -f -
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: filebeat
spec:
  type: filebeat
  version: 7.8.0
  elasticsearchRef:
    name: elasticsearch
  kibanaRef:
    name: kibana
  config:
    filebeat.inputs:
    - type: container
      paths:
      - /var/log/containers/*.log
    processors:
    - add_host_metadata: {}
    - add_cloud_metadata: {}
  daemonSet:
    podTemplate:
      spec:
        automountServiceAccountToken: true
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true # Allows to provide richer host metadata
        securityContext:
          runAsUser: 0
        containers:
        - name: filebeat
          # If using Red Hat OpenShift uncomment this:
          #securityContext:
            #privileged: true
          volumeMounts:
          - name: varlogcontainers
            mountPath: /var/log/containers
          - name: varlogpods
            mountPath: /var/log/pods
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
        volumes:
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
        - name: varlogpods
          hostPath:
            path: /var/log/pods
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 7.8.0
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
  - name: default
    count: 3
    config:
      node.store.allow_mmap: false
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  version: 7.8.0
  count: 1
  elasticsearchRef:
    name: elasticsearch
---
apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm
spec:
  version: 7.8.0
  count: 1
  elasticsearchRef:
    name: elasticsearch
  kibanaRef:
    name: kibana
```

</details>

### Repro output:
```
$ kubectl tree apm apm
NAMESPACE  NAME                      READY  REASON  AGE
default    ApmServer/apm             -              16s
default    ├─Secret/apm-apm-es-ca    -              15s
default    ├─Secret/apm-apm-kb-user  -              16s
default    └─Secret/apm-apm-user     -              16s

$ k tree beats filebeat
NAMESPACE  NAME                            READY  REASON  AGE
default    Beat/filebeat                   -              20s
default    ├─Secret/filebeat-beat-es-ca    -              19s
default    ├─Secret/filebeat-beat-kb-user  -              20s
default    └─Secret/filebeat-beat-user     -              20s
```

### Does this affect Elasticsearch?

No. For Elasticsearch we always create a public cert Secret, even if TLS is disabled. 

### Are there any workarounds?

1. Enable TLS in Kibana, or
2. (not recomended as this may have unintended consequences and was not tested in any way) "trick" association controller to thinking that the public cert exists by running `kubectl create secret generic kibana-kb-http-certs-public --from-literal=tls.crt=fake`
