### ISSUE TITLE
Status of Kibana deployments is `unknown` in the Openshift console

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#3584]
Even if Kibana is successfully started its status remains to `unknown` in the Openshift console:

```
NAME                                         HEALTH   NODES   VERSION   AGE
kibana.kibana.k8s.elastic.co/kibana-sample   green    1       7.8.0     2m3s
```

![image](https://user-images.githubusercontent.com/976373/89383842-7ff42c80-d6fd-11ea-8c80-df88148acfb5.png)

I think this is because Openshift is expecting a `phase` field in the object status, e.g:

```yaml
status:
  associationStatus: Established
  availableNodes: 1
  health: green
  phase: Ready # this
```

We should also check if it is the case for other resources.
