### ISSUE TITLE
Zone awareness doesn't work

### ISSUE THREAD

**Issue by haizaar** [elastic/cloud-on-k8s#3627]
## Bug Report
**What did you do?**
Configured zone-aware shard allocation as per [docs](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-advanced-node-scheduling.html#k8s-availability-zone-awareness)

**What did you expect to see?**
Primary and replicas residing in a different zones.

**What did you see instead? Under which circumstances?**
Zone awareness settings seem to be ignored:
![image](https://user-images.githubusercontent.com/58201/90165886-afc9c100-dddc-11ea-9f80-1632a99ef4c0.png)
Though node's `elasticsearch.yml` does seem to contain the relevant settings:
```console
$ kubectl exec quickstart-es-zone-a-0 head config/elasticsearch.yml
cluster:
  name: quickstart
  routing:
    allocation:
      awareness:
        attributes: zone
...
```

**How to reproduce**
* Load the yaml resources definition below
* Wait couple of minutes
* run `kubectl port-forward service/cerebro 9000`
* go to http://localhost:9000/#/overview?host=http:%2F%2Fquickstart-es-http:9200
* login using `elastic` user and password obtained from `kubectl get secret quickstart-es-elastic-user -o=jsonpath='{.data.elastic}' | base64 --decode`
* observe that each node has a green-colored node label assigned to it
* navigate to "more -> create index". Type `t1` as index name, `6` as number of shards and `1` as number of replicas. Click "Create"
* Click "overview" in the top left and look at `t1` index primary shards (solid line cubes) spread across both zones instead of just one.

**Environment**

* ECK version:
        1.2.1

* Kubernetes information:
        GKE 1.16.11-gke.5
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.8", GitCommit:"0c6d31a99f81476dfc9871ba3cf3f597bec29b58", GitTreeState:"clean", BuildDate:"2019-07-08T08:46:01Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.11-gke.5", GitCommit:"baccd25d44f1a0d06ad3190eb508784efbb990a5", GitTreeState:"clean", BuildDate:"2020-06-25T22:55:26Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

* Resource definition:
```yaml
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.8.1
  http:
    tls:
      selfSignedCertificate:
        # To simplify connecting via cerbero
        disabled: true
  nodeSets:
  - name: zone-a
    count: 1
    config:
      node.attr.zone: us-central1-a
      cluster.routing.allocation.awareness.attributes: zone
    podTemplate:
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: failure-domain.beta.kubernetes.io/zone
                  operator: In
                  values:
                  - us-central1-a
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: stdwait
  - name: zone-b
    count: 1
    config:
      node.attr.zone: us-central1-b
      cluster.routing.allocation.awareness.attributes: zone
    podTemplate:
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: failure-domain.beta.kubernetes.io/zone
                  operator: In
                  values:
                  - us-central1-b
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: stdwait
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: stdwait
provisioner: kubernetes.io/gce-pd
# Mandatory to make pods land properly
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: pd-standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cerebro
  name: cerebro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cerebro
  template:
    metadata:
      labels:
        app: cerebro
    spec:
      containers:
      - image: lmenezes/cerebro:0.9.2
        name: cerebro
        env:
        - name: "CEREBRO_PORT"
          value: "9000"
        ports:
        - name: http
          containerPort: 9000
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: cerebro
spec:
  ports:
    - name: http
      port: 9000
      targetPort: http
  selector:
    app: cerebro
```
