### ISSUE TITLE
OpenShift 3.11 Troubleshooting for ECK beat deployment

### ISSUE THREAD

**Issue by SeanPlacchetti** [elastic/cloud-on-k8s#3663]
## Update the troubleshooting page with notes on deploying beats to OpenShift 3.11

**Beats (metricbeat, auditbeat, filebeat) will not go to all the nodes without this step in OpenShift 3.11**

Per this documentation: https://docs.openshift.com/container-platform/3.11/dev_guide/daemonsets.html

You need to run this: `oc patch namespace myproject -p '{"metadata": {"annotations": {"openshift.io/node-selector": ""}}}'` to open up any project where you'd apply yaml using the beat CRD. This might be helpful to others, as it's a hidden default value.

**Comment by barkbay** [comment]
On OpenShift 4, I _think_, we might need these tolerations on the `Pods`:

```yaml
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
```

This is because master nodes have this `taint` by default on OCP 4:

```yaml
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
```

As a side note, regarding "monitoring Pods" like Beats deployments, we might also want to tolerate [other kinds of conditions/taints](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#taint-based-evictions), but it is not OCP specific.
