### ISSUE TITLE
Document heap dump behavior and potential impact with a small elasticsearch-data persistent volume

### ISSUE THREAD

**Issue by mikeh-elastic** [elastic/cloud-on-k8s#3683]
If you heap dump elasticsearch with eck the java heap will dump write to the root of the elasticsearch-data volume, with a heap larger than the physical volume you will run out of space and then enter a crashloop where the pod cannot restart as the volume is unable to be written to by elasticsearch as the heap has filled all space.

Documenting that heap dumps will need enough space on these volumes would be beneficial to prevent confusion.

Documenting a simple heap dump collection from the pod via kuebctl cp or other mechanism would also be helpful.

Longer term there is a question of should heaps dumps continue to write to elasticsearch-data and other considerations like could anything be done for automatic heap dump collection and clean up.

**Comment by anyasabo** [comment]
I generalized the title a little bit because I think we want to cover this more broadly (as suggested in your initial text). I'd also add that this is useful at a minimum for enterprise search as well, we may want to start with elasticsearch but not end there.

If we can find a better method than `kubectl exec` and `kubectl cp` that would be great. It works for one offs but isn't great for any kind of automatic process. If the ES image has the necessary tools to upload the dump somewhere then that could work.

Otherwise it may make sense to attach an ephemeral container with said tools and upload the dump somewhere (S3 etc). Downside is that ephemeral containers are still in alpha and have been since 1.16, so will not be available in a large number of environments we currently support.

To enable elastic cloud-like troubleshooting tools we would want some automatic process for on demand heap dumps. I'm not JVM fluent enough to know if we recommend configurations that can get heap dumps remotely via jmx or something.

**Comment by pebrc** [comment]
I did a few experiments to see what our options are:

* `kubectl exec` works, but needs additional explanation. Depending on the k8s flavour we might need to be explicit about the user to execute the `jmap` command with. E.g. on GKE the below does the trick (on OCP `root` works directly) :  
```sh
kubectl exec -ti  $POD_NAME \
-- su elasticsearch -g root -c \
'/usr/share/elasticsearch/jdk/bin/jmap -dump:format=b,file=heap.hprof $(pgrep java)'
```

Followed by  a `kubectl cp`. Of course the caveat about having enough free storage storage applies.


* I have not tested ephemeral containers

* JMX allows you to connect from remote to the Elasticsearch JVM and monitor it and trigger diagnostics like thread dumps or heap dumps. However the result of that operation will still be on the Pod. E.g. triggering a heap dump works from remote without resorting to `kubectl exec` but in order to get to the heap dump we need to resort to `kubectl cp` again to get it out. 

For completeness sake here is a minimal sample manifest how to do it: 
```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
spec:
  version: 7.9.2
  nodeSets:
  - name: default
    config:
      node.roles: ["master", "data", "ingest", "ml", "transform", "remote_cluster_client"]
      node.store.allow_mmap: false
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: "-Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=11391 -Dcom.sun.management.jmxremote.rmi.port=11391 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false"
    count: 1
```
The `jmxremote` options are informed by [this post ](https://stackoverflow.com/a/39927197/10614587). Just to repeat: make sure that `rmi` and the other JMX traffic just use one port (the one you port-forward with `kubectl`) . 

Then `kubectl port-forward elasticsearch-sample-es-default-0 11391` and use `jconsole 127.0.0.1:11391` to give you a UI to take a heap dump, but unless you also mount a dedicated volume for the heap dump and use it will use up storage on the pod or the data volume (depending on the path you specify to store the heap dump under in `jconsole`) 

Alternatively `jvisualvm` is also an option. It gives a slightly nicer UI (see screenshot)
![Screenshot 2020-10-13 at 18 57 42](https://user-images.githubusercontent.com/697790/95892006-24da5800-0d86-11eb-8086-e4e82650884f.png)
 but I failed to take a heap dump via the Visual VM UI.

**Comment by pebrc** [comment]
One more update regarding [ephemeral containers](https://kubernetes.io/docs/concepts/workloads/pods/ephemeral-containers/):
* only available behind a feature flag since 1.16
* requires modifications to the container we want to take the heap dump from. For example we need`shareProcessNamespace: true` and probably a shared tmp folder
* does not solve the problem of where to put the resulting heap dump, we still need a place to store it at least temporarily 
* tools like `jmap` use a facility called [dynamic attach](https://openjdk.java.net/groups/hotspot/docs/Serviceability.html) to hook into the running JVM. Afaik it requires the `uid` and `gid` of the attaching process to be identical to the one of the JVM (see above my `kubectl exec` example). It also uses a unix socket in the `tmp` directory to communicate between the JVM and the attaching agent. I **have not been able to make this work** from an ephemeral container even with process namespace sharing turned on and a shared `tmp` directory. 

Below the config I used for my experiment: 

1. create a test ES cluster like so
```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
spec:
  version: 7.9.2
  nodeSets:
  - name: default
    config:
      node.roles: ["master", "data", "ingest", "ml", "transform", "remote_cluster_client"]
      node.store.allow_mmap: false
    podTemplate:
      spec:
        shareProcessNamespace: true
        containers:
        - name: elasticsearch
          volumeMounts:
          - name: tmp
            mountPath: /tmp
        volumes:
          - name: tmp
            emptyDir: {}
    count: 1
```
2. define an ephemeral container: 
```json
{
    "apiVersion": "v1",
    "kind": "EphemeralContainers",
    "metadata": {
            "name": "elasticsearch-sample-es-default-0"
    },
    "ephemeralContainers": [{
        "command": [
            "sh"
        ],
        "image": "docker.elastic.co/elasticsearch/elasticsearch:7.9.2",
        "imagePullPolicy": "IfNotPresent",
        "name": "heapdumper",
        "stdin": true,
        "tty": true,
        "terminationMessagePolicy": "File",
        "volumeMounts": [
            {
                "mountPath": "/mnt/data",
                "name": "elasticsearch-data"             
            },
            {
                "mountPath": "/tmp",
                "name": "tmp"
            }
            
        ]
    }]
}
```
3. add the ephemeral container to the Elasticsearch pod: 
` kubectl replace --raw /api/v1/namespaces/default/pods/elasticsearch-sample-es-default-0/ephemeralcontainers -f ephemeral-container-from-above.json`
4. attach to it with `kubectl attach -it elasticsearch-sample-es-default-0 -c heapdumper`
5. try to take a heap dump with ` runuser -u elasticsearch -g root -- /usr/share/elasticsearch/jdk/bin/jmap -dump:format=b,file=/mnt/data/heap.hprof $(pgrep java)`
