### ISSUE TITLE
ECK Quickstart - Elasticsearch 7.9.0 fails to start with a "permission denied" error

### ISSUE THREAD

**Issue by kurbar** [elastic/cloud-on-k8s#3701]
## Bug Report
**What did you do?**
1. Install ECK from the `all-in-one.yaml` manifest file.
2. Per the [Quickstart guide](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-deploy-elasticsearch.html) install Elasticsearch

**What did you expect to see?**
A running Elasticsearch cluster

**What did you see instead? Under which circumstances?**
Elasticsearch fails to start with the following error:
```
chroot: failed to run command '/usr/share/elasticsearch/bin/elasticsearch': Permission denied
```

**Environment**

* ECK version: 1.2.1

* Kubernetes information:
kubeadm cluster with Kubernetes v1.15.7.
Storage backend: GlusterFS v5.11 with Heketi

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:06:54Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"clean", BuildDate:"2019-12-11T12:34:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

* Resource definition:
Elasticsearch manifest
```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: monitoring
  namespace: <redacted>
spec:
  version: 7.9.0
  nodeSets:
  - name: default
    count: 1
    # podTemplate: <-- Tried setting this as well, result is the same error
    #   spec:
    #     securityContext:
    #       runAsUser: 1000
    #       runAsGroup: 1000
    #       fsGroup: 1000
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
        storageClassName: standard
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false
```

**Comment by sebgl** [comment]
ECK spins up an init container that copies the content of /usr/share/elasticsearch/bin into an emptyDir, for plugin install purposes. That emptyDir is then mounted into the main container. Is it possible that the emptyDir you end up with does not persist the right file permissions?

What you could do for further troubleshooting is patch the main Elasticsearch container podTemplate to run a dummy bash script. This gives us the opportunity to exec into the container and figure out what's wrong with the file system.

Apply the following yaml:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
spec:
  version: 7.9.0
  nodeSets:
  - name: default
    count: 1
    config:
      # This setting could have performance implications for production clusters.
      # See: https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-virtual-memory.html
      node.store.allow_mmap: false
    podTemplate:
      spec:
        containers:
          - name: elasticsearch
            command: ["sh"]
            args: ["-c", "while true; do sleep 1; done"]
```

Wait until the container is in a `Running` phase.

Then run:

```
kubectl exec  elasticsearch-sample-es-default-0  -- ls -la /usr/share/elasticsearch/bin
```

This should give us more details about the permissions in that directory.

**Comment by kurbar** [comment]
I exec'd in the container and a quick permission overview looks like this:
```
[root@monitoring-es-default-0 elasticsearch]# pwd
/usr/share/elasticsearch
[root@monitoring-es-default-0 elasticsearch]# ls -la 
total 584
drwxrwxr-x  1 elasticsearch root              17 Sep  1 21:27 .
drwxr-xr-x  1 root          root              27 Sep  1 21:26 ..
-rw-r--r--  1 elasticsearch root              18 Apr  1 02:17 .bash_logout
-rw-r--r--  1 elasticsearch root             193 Apr  1 02:17 .bash_profile
-rw-r--r--  1 elasticsearch root             231 Apr  1 02:17 .bashrc
-rw-r--r--  1 elasticsearch root           13675 Sep  1 21:19 LICENSE.txt
-rw-r--r--  1 elasticsearch root          544318 Sep  1 21:24 NOTICE.txt
-rw-r--r--  1 elasticsearch root            7007 Sep  1 21:19 README.asciidoc
drwxrwxrwx  2 root          root            4096 Sep  4 12:41 bin
drwxrwxrwx  7 root          root             292 Sep  4 12:41 config
drwxrwsr-x  3 elasticsearch elasticsearch   4096 Sep  4 12:41 data
drwxr-xr-x  1 elasticsearch root              17 Sep  1 21:25 jdk
drwxr-xr-x  3 elasticsearch root            4096 Sep  1 21:25 lib
drwxrwxrwx  2 elasticsearch elasticsearch      6 Sep  4 12:41 logs
drwxr-xr-x 51 elasticsearch root            4096 Sep  1 21:25 modules
drwxrwxrwx  2 root          root               6 Sep  4 12:41 plugins
[root@monitoring-es-default-0 elasticsearch]# whoami
root
[root@monitoring-es-default-0 elasticsearch]# cd bin/
[root@monitoring-es-default-0 bin]# ll
total 20480
-rwxr-xr-x 1 elasticsearch root     2877 Sep  1 21:19 elasticsearch
-rwxr-xr-x 1 elasticsearch root      491 Sep  1 21:24 elasticsearch-certgen
-rwxr-xr-x 1 elasticsearch root      483 Sep  1 21:24 elasticsearch-certutil
-rwxr-xr-x 1 elasticsearch root      996 Sep  1 21:19 elasticsearch-cli
-rwxr-xr-x 1 elasticsearch root      433 Sep  1 21:24 elasticsearch-croneval
-rwxr-xr-x 1 elasticsearch root     4462 Sep  1 21:26 elasticsearch-env
-rwxr-xr-x 1 elasticsearch root     1828 Sep  1 21:19 elasticsearch-env-from-file
-rwxr-xr-x 1 elasticsearch root      184 Sep  1 21:19 elasticsearch-keystore
-rwxr-xr-x 1 elasticsearch root      440 Sep  1 21:24 elasticsearch-migrate
-rwxr-xr-x 1 elasticsearch root      126 Sep  1 21:19 elasticsearch-node
-rwxr-xr-x 1 elasticsearch root      172 Sep  1 21:19 elasticsearch-plugin
-rwxr-xr-x 1 elasticsearch root      431 Sep  1 21:24 elasticsearch-saml-metadata
-rwxr-xr-x 1 elasticsearch root      438 Sep  1 21:24 elasticsearch-setup-passwords
-rwxr-xr-x 1 elasticsearch root      118 Sep  1 21:19 elasticsearch-shard
-rwxr-xr-x 1 elasticsearch root      441 Sep  1 21:24 elasticsearch-sql-cli
-rwxr-xr-x 1 elasticsearch root 20882402 Sep  1 21:24 elasticsearch-sql-cli-7.9.1.jar
-rwxr-xr-x 1 elasticsearch root      426 Sep  1 21:24 elasticsearch-syskeygen
-rwxr-xr-x 1 elasticsearch root      426 Sep  1 21:24 elasticsearch-users
-rwxr-xr-x 1 elasticsearch root      346 Sep  1 21:24 x-pack-env
-rwxr-xr-x 1 elasticsearch root      354 Sep  1 21:24 x-pack-security-env
-rwxr-xr-x 1 elasticsearch root      353 Sep  1 21:24 x-pack-watcher-env
```

**Comment by sebgl** [comment]
I don't see anything suspicious in your output.
Can you provide the complete Elasticsearch logs?

**Comment by kurbar** [comment]
Full logs from `elastic-internal-init-filesystem` during startup (fresh volume):
```
Starting init script
Linking /mnt/elastic-internal/xpack-file-realm/users to /usr/share/elasticsearch/config/users
Linking /mnt/elastic-internal/xpack-file-realm/roles.yml to /usr/share/elasticsearch/config/roles.yml
Linking /mnt/elastic-internal/xpack-file-realm/users_roles to /usr/share/elasticsearch/config/users_roles
Linking /mnt/elastic-internal/elasticsearch-config/elasticsearch.yml to /usr/share/elasticsearch/config/elasticsearch.yml
Linking /mnt/elastic-internal/unicast-hosts/unicast_hosts.txt to /usr/share/elasticsearch/config/unicast_hosts.txt
File linking duration: 0 sec.
Copying /usr/share/elasticsearch/config/* to /mnt/elastic-internal/elasticsearch-config-local/
'/usr/share/elasticsearch/config/elasticsearch.yml' -> '/mnt/elastic-internal/elasticsearch-config-local/elasticsearch.yml'
'/usr/share/elasticsearch/config/http-certs' -> '/mnt/elastic-internal/elasticsearch-config-local/http-certs'
'/usr/share/elasticsearch/config/http-certs/..data' -> '/mnt/elastic-internal/elasticsearch-config-local/http-certs/..data'
'/usr/share/elasticsearch/config/http-certs/ca.crt' -> '/mnt/elastic-internal/elasticsearch-config-local/http-certs/ca.crt'
'/usr/share/elasticsearch/config/http-certs/tls.key' -> '/mnt/elastic-internal/elasticsearch-config-local/http-certs/tls.key'
'/usr/share/elasticsearch/config/http-certs/tls.crt' -> '/mnt/elastic-internal/elasticsearch-config-local/http-certs/tls.crt'
'/usr/share/elasticsearch/config/http-certs/..2020_09_04_12_41_07.927008313' -> '/mnt/elastic-internal/elasticsearch-config-local/http-certs/..2020_09_04_12_41_07.927008313'
'/usr/share/elasticsearch/config/http-certs/..2020_09_04_12_41_07.927008313/tls.key' -> '/mnt/elastic-internal/elasticsearch-config-local/http-certs/..2020_09_04_12_41_07.927008313/tls.key'
'/usr/share/elasticsearch/config/http-certs/..2020_09_04_12_41_07.927008313/tls.crt' -> '/mnt/elastic-internal/elasticsearch-config-local/http-certs/..2020_09_04_12_41_07.927008313/tls.crt'
'/usr/share/elasticsearch/config/http-certs/..2020_09_04_12_41_07.927008313/ca.crt' -> '/mnt/elastic-internal/elasticsearch-config-local/http-certs/..2020_09_04_12_41_07.927008313/ca.crt'
'/usr/share/elasticsearch/config/jvm.options' -> '/mnt/elastic-internal/elasticsearch-config-local/jvm.options'
'/usr/share/elasticsearch/config/jvm.options.d' -> '/mnt/elastic-internal/elasticsearch-config-local/jvm.options.d'
'/usr/share/elasticsearch/config/log4j2.properties' -> '/mnt/elastic-internal/elasticsearch-config-local/log4j2.properties'
'/usr/share/elasticsearch/config/role_mapping.yml' -> '/mnt/elastic-internal/elasticsearch-config-local/role_mapping.yml'
'/usr/share/elasticsearch/config/roles.yml' -> '/mnt/elastic-internal/elasticsearch-config-local/roles.yml'
'/usr/share/elasticsearch/config/transport-remote-certs' -> '/mnt/elastic-internal/elasticsearch-config-local/transport-remote-certs'
'/usr/share/elasticsearch/config/transport-remote-certs/..data' -> '/mnt/elastic-internal/elasticsearch-config-local/transport-remote-certs/..data'
'/usr/share/elasticsearch/config/transport-remote-certs/ca.crt' -> '/mnt/elastic-internal/elasticsearch-config-local/transport-remote-certs/ca.crt'
'/usr/share/elasticsearch/config/transport-remote-certs/..2020_09_04_12_41_07.730706606' -> '/mnt/elastic-internal/elasticsearch-config-local/transport-remote-certs/..2020_09_04_12_41_07.730706606'
'/usr/share/elasticsearch/config/transport-remote-certs/..2020_09_04_12_41_07.730706606/ca.crt' -> '/mnt/elastic-internal/elasticsearch-config-local/transport-remote-certs/..2020_09_04_12_41_07.730706606/ca.crt'
'/usr/share/elasticsearch/config/unicast_hosts.txt' -> '/mnt/elastic-internal/elasticsearch-config-local/unicast_hosts.txt'
'/usr/share/elasticsearch/config/users' -> '/mnt/elastic-internal/elasticsearch-config-local/users'
'/usr/share/elasticsearch/config/users_roles' -> '/mnt/elastic-internal/elasticsearch-config-local/users_roles'
Empty dir /usr/share/elasticsearch/plugins
Copying /usr/share/elasticsearch/bin/* to /mnt/elastic-internal/elasticsearch-bin-local/
'/usr/share/elasticsearch/bin/elasticsearch' -> '/mnt/elastic-internal/elasticsearch-bin-local/elasticsearch'
'/usr/share/elasticsearch/bin/elasticsearch-certgen' -> '/mnt/elastic-internal/elasticsearch-bin-local/elasticsearch-certgen'
'/usr/share/elasticsearch/bin/elasticsearch-certutil' -> '/mnt/elastic-internal/elasticsearch-bin-local/elasticsearch-certutil'
'/usr/share/elasticsearch/bin/elasticsearch-cli' -> '/mnt/elastic-internal/elasticsearch-bin-local/elasticsearch-cli'
'/usr/share/elasticsearch/bin/elasticsearch-croneval' -> '/mnt/elastic-internal/elasticsearch-bin-local/elasticsearch-croneval'
'/usr/share/elasticsearch/bin/elasticsearch-env' -> '/mnt/elastic-internal/elasticsearch-bin-local/elasticsearch-env'
'/usr/share/elasticsearch/bin/elasticsearch-env-from-file' -> '/mnt/elastic-internal/elasticsearch-bin-local/elasticsearch-env-from-file'
'/usr/share/elasticsearch/bin/elasticsearch-keystore' -> '/mnt/elastic-internal/elasticsearch-bin-local/elasticsearch-keystore'
'/usr/share/elasticsearch/bin/elasticsearch-migrate' -> '/mnt/elastic-internal/elasticsearch-bin-local/elasticsearch-migrate'
'/usr/share/elasticsearch/bin/elasticsearch-node' -> '/mnt/elastic-internal/elasticsearch-bin-local/elasticsearch-node'
'/usr/share/elasticsearch/bin/elasticsearch-plugin' -> '/mnt/elastic-internal/elasticsearch-bin-local/elasticsearch-plugin'
'/usr/share/elasticsearch/bin/elasticsearch-saml-metadata' -> '/mnt/elastic-internal/elasticsearch-bin-local/elasticsearch-saml-metadata'
'/usr/share/elasticsearch/bin/elasticsearch-setup-passwords' -> '/mnt/elastic-internal/elasticsearch-bin-local/elasticsearch-setup-passwords'
'/usr/share/elasticsearch/bin/elasticsearch-shard' -> '/mnt/elastic-internal/elasticsearch-bin-local/elasticsearch-shard'
'/usr/share/elasticsearch/bin/elasticsearch-sql-cli' -> '/mnt/elastic-internal/elasticsearch-bin-local/elasticsearch-sql-cli'
'/usr/share/elasticsearch/bin/elasticsearch-sql-cli-7.9.1.jar' -> '/mnt/elastic-internal/elasticsearch-bin-local/elasticsearch-sql-cli-7.9.1.jar'
'/usr/share/elasticsearch/bin/elasticsearch-syskeygen' -> '/mnt/elastic-internal/elasticsearch-bin-local/elasticsearch-syskeygen'
'/usr/share/elasticsearch/bin/elasticsearch-users' -> '/mnt/elastic-internal/elasticsearch-bin-local/elasticsearch-users'
'/usr/share/elasticsearch/bin/x-pack-env' -> '/mnt/elastic-internal/elasticsearch-bin-local/x-pack-env'
'/usr/share/elasticsearch/bin/x-pack-security-env' -> '/mnt/elastic-internal/elasticsearch-bin-local/x-pack-security-env'
'/usr/share/elasticsearch/bin/x-pack-watcher-env' -> '/mnt/elastic-internal/elasticsearch-bin-local/x-pack-watcher-env'
Files copy duration: 1 sec.
chowning /usr/share/elasticsearch/data to elasticsearch:elasticsearch
changed ownership of '/usr/share/elasticsearch/data' from root:2000 to elasticsearch:elasticsearch
chowning /usr/share/elasticsearch/logs to elasticsearch:elasticsearch
changed ownership of '/usr/share/elasticsearch/logs' from root:root to elasticsearch:elasticsearch
chown duration: 0 sec.
waiting for the transport certificates (/mnt/elastic-internal/transport-certificates/monitoring-es-default-0.tls.key)
wait duration: 1 sec.
Linking /usr/share/elasticsearch/config/transport-certs/monitoring-es-default-0.tls.crt to /mnt/elastic-internal/elasticsearch-config-local/node-transport-cert/transport.tls.crt
Linking /usr/share/elasticsearch/config/transport-certs/monitoring-es-default-0.tls.crt to /mnt/elastic-internal/elasticsearch-config-local/node-transport-cert/transport.tls.crt
Certs linking duration: 0 sec.
Init script successful
Script duration: 2 sec.
```

After init `elasticsearch` container only reports the error, no other output:
```
chroot: failed to run command '/usr/share/elasticsearch/bin/elasticsearch': Permission denied
```

`elastic-operator` logs don't report any error as well. Only reconciliation run logs that just report `ES cannot be reached yet, re-queuing`.

**Comment by sebgl** [comment]
Is there a chance you have a conflicting PSP that prevents the `CAP_SYS_CHROOT` capability in the Elasticsearch container?
The [default entrypoint relies on chroot to switch to the user 1000](https://github.com/elastic/elasticsearch/blob/a479a2a7fce0389512d6a9361301708b92dff667/distribution/docker/src/docker/bin/docker-entrypoint.sh#L7-L11).

You may have a PSP that does something such as:
```
requiredDropCapabilities:
    - ALL
```

**Comment by kurbar** [comment]
The cluster only has a MetalLB PSP (metallb-speaker) but it doesn't have any requiredDropCapabilities set.

**Comment by sebgl** [comment]
Can you try extending the podTemplate container spec to add the `CAP_SYS_CHROOT ` capability as explained in https://unofficial-kubernetes.readthedocs.io/en/latest/concepts/policy/container-capabilities/?

**Comment by kurbar** [comment]
Tried setting `SYS_CHROOT` (and `CAP_SYS_CHROOT` for good measure) but unfortunately the same permission error remains.

However... I did some manual testing.

I tried to replay the chroot part of the entrypoint script and noticed something.

chroot by default seems to open an `sh` instance. Under `sh`, the error happens. but if I run the elasticsearch bin under `/bin/bash`, elasticsearch starts booting up.

```
[root@monitoring-es-node-0 elasticsearch]# chroot --userspec=1000 /
sh-4.2$ /usr/share/elasticsearch/bin/elasticsearch
sh: /usr/share/elasticsearch/bin/elasticsearch: Permission denied
sh-4.2$ /bin/bash /usr/share/elasticsearch/bin/elasticsearch
/usr/share/elasticsearch/bin/elasticsearch: line 40: bin/elasticsearch-keystore: Permission denied
{"type": "server", "timestamp": "2020-09-04T15:17:16,988Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "monitoring", "node.name": "monitoring-es-node-0", "message": "version[7.9.1], pid[3405], build[default/docker/083627f112ba94dffc1232e8b42b73492789ef91/2020-09-01T21:22:21.964974Z], OS[Linux/3.10.0-1062.9.1.el7.x86_64/amd64], JVM[AdoptOpenJDK/OpenJDK 64-Bit Server VM/14.0.1/14.0.1+7]" }
{"type": "server", "timestamp": "2020-09-04T15:17:17,006Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "monitoring", "node.name": "monitoring-es-node-0", "message": "JVM home [/usr/share/elasticsearch/jdk]" }
...
```

Maybe it needs to start under bash but for some reason it isn't?

**Comment by barkbay** [comment]
Could you copy/paste here the yaml spec of the Pod, you can get it with something like `kubectl get pod monitoring-es-node-0 -o yaml` ?

**Comment by barkbay** [comment]
> Could you copy/paste here the yaml spec of the Pod, you can get it with something like `kubectl get pod monitoring-es-node-0 -o yaml` ?

Also could you do the same when attempting to add a security context to set the uid to 1000 (as mentioned in you original message). It is a bit surprising that the container still attempt to do a `chroot` if it is not running as root.

Thanks

**Comment by kurbar** [comment]
Here is the YAML output with fsGroup set: https://gist.github.com/kurbar/434fe944e879917d5bd712d71bba3f4c

With fsGroup set it gives the same chroot error
```
chroot: failed to run command '/usr/share/elasticsearch/bin/elasticsearch': Permission denied
```

```
spec:
  version: 7.9.1
  nodeSets:
    - name: default
      count: 1
      config:
        node.master: true
        node.data: true
        node.ingest: true
      podTemplate:
        spec:
          ...
          securityContext:
            fsGroup: 1000
```

**Comment by barkbay** [comment]
I don't understand where this container `configure-sysctl` comes from:

```
  - command:
    - sysctl
    - -w
    - vm.max_map_count=262144
    env:
    - name: POD_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    imagePullPolicy: IfNotPresent
    name: configure-sysctl
    resources: {}
    securityContext:
      privileged: true
      runAsUser: 0
```

This does not seem to match the manifest you provided in your original message, also you suggested that `runAsUser` was set to 1000:

```yaml
    # podTemplate: <-- Tried setting this as well, result is the same error
    #   spec:
    #     securityContext:
    #       runAsUser: 1000
    #       runAsGroup: 1000
    #       fsGroup: 1000
```

Which is not the case here ?

I'm a bit confused, could you provide the Elasticsearch manifest used to generate the Pod ?

**Comment by kurbar** [comment]
Apologies. I was testing different ways that I left a bit of noise in my manifest that I forgot to remove.

Cleaned it up and ran again. The chroot error is not thrown any more but the permission issue persists:
```
/usr/local/bin/docker-entrypoint.sh: line 14: /usr/share/elasticsearch/bin/elasticsearch: Permission denied
```

Used manifest and pod YAML: https://gist.github.com/kurbar/2a49ef147b6a968b5aaeb25499d57d6c

**Comment by kurbar** [comment]
@sebgl @barkbay Any updates on this?

**Comment by barkbay** [comment]
I tried to reproduce on a cluster created with Kubespray (which is itself relying on kubeadm) but without success. It is working as expected.

- What is the operating system ? Any special security enforcement in place at the OS level ?
- Did you customize the Docker images at some point ? I want to be sure that you are using the ones provided by Elastic.
- What is the container runtime ?
- Is it only happening with Elasticsearch ? Is there the same issue with other containers ?

**Comment by kurbar** [comment]
* The nodes run on CentOS release 7.7.1908. No special security enforcements applied. SELinux is disabled
* The images are not modified. Directly pulled from Elastic
* Container runtime is Docker 19.03.6
* Seems to be only happening to Elasticsearch. e.g. Kibana does start up (just not fully since it can't connect to any Elasticsearch).

**Comment by pebrc** [comment]
I am closing this due to inactivity. Let's reopen if needed.

**Comment by MrOwen** [comment]
I also ran into this issue. Pretty much same setup as @kurbar but on CentOS 8.4 with SELinux enabled. The fix that worked for me was this particular `securityContext` pod spec:

```yaml
podTemplate:
  spec:
    securityContext:
      fsGroup: 0
      runAsUser: 1000
      runAsGroup: 0
```

I attempted various permutations of this and only this particular combination seemed to work. I run this at home so don't care too much how this fixes it but perhaps it's useful for anyone else running into the same issue.
