### ISSUE TITLE
Create the ability to target a custom service with `elasticsearchRef`

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#3732]
Currently `elasticsearchRef` always uses the default HTTP service ECK creates to make requests to Elasticsearch. While we offer the ability to customize that default service and adjust its selector there are cases where that is not enough: 

Consider: 
* target coordinator nodes with Kibana
* target data/ingest nodes with Beats

We should investigate whether it makes sense to allow users to specify a custom service in the `elasticsearchRef`. 

```yaml
elasticsearchRef:
  name: my-elasticsearch-cluster
  service: my-custom-service
```

**Comment by mjmbischoff** [comment]
As ECK is 'opinionated' in the sense that it has our best practices backed in we should consider a defaulting in the given  examples as well. I think this also means that default service that targets coordinator nodes and service that targets data/ingest nodes should be created. - Perhaps when the es cluster is created or perhaps deferred until a kibana resp. beat resource is created.

**Comment by tommasopozzetti** [comment]
Is there any update on this feature?
I believe this would be extremely useful for big Elasticsearch clusters that contain nodes with varying roles.
As it has been mentioned, pointing Kibana to coordinator-only nodes is an example.
Another example would be that if dedicated master-eligible nodes are created, using the default service will allow clients (such as Kibana) to send query requests to dedicated master-eligible nodes, which is [explicitly discouraged](https://www.elastic.co/guide/en/elasticsearch/reference/7.11/modules-node.html#dedicated-master-node) in the docs. 
Currently the only way to achieve this is to configure Kibana as if it was connecting to an [external Elasticsearch cluster](https://www.elastic.co/guide/en/cloud-on-k8s/1.4/k8s-kibana-es.html#k8s-kibana-external-es), which is however less then ideal because it no longer allows eck to auto-manage the user creation and some of the configs.

**Comment by pebrc** [comment]
Another option that comes to mind here is to allow users to specify label selector rather than a service name. Allowing them to spec our their custom service. This would have the advantage that the service itself would still be managed by the ECK operator and its lifecycle would be tied to the resources it exposes.

**Comment by pebrc** [comment]
Following up on the idea of spec'ing a custom service inline in the `elasticsearchRef` I believe the following could work:

```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  annotations:
  name: test-coord
  namespace: default
spec:
  nodeSets:
  - config:
      node.roles: []
      node.store.allow_mmap: false
    count: 1
    name: coord
    podTemplate:
      metadata:
        labels:
          app: coord-node
  - config:
      node.store.allow_mmap: false
    count: 1
    name: default
  version: 7.12.0
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-sample
spec:
  version: 7.12.0
  count: 1
  elasticsearchRef:
    name: "test-coord"
    service:
      spec:
        selector:
          app: coord-node
```

The association controller would create a custom service just for this association in the namespace of the Elasticsearch cluster, using the name of the association, owned by the associated resource (here: Kibana). I am using a custom label here but it is of course also possible to use the labels we set on the Elasticsearch Pods by default. It is just a bit difficult for this coordinator node example as we don't set a "coordinating" label, so you would have to negate all other labels e.g. `master: false`, data: false`, `ingest: false` etc.

To note: 
* this would add the `service` template to any *Ref (not only Elasticsearch refs but also Kibana refs) because we have a shared implementation for all associations. 
*

**Comment by sebgl** [comment]
```yaml
 elasticsearchRef:
    name: "test-coord"
    service:
      spec:
        selector:
          app: coord-node
```

so this would trigger the creation of a new service in the Elasticsearch namespace to target Pods of the `test-coord` ES cluster? How would that service be named? Something based on the Kibana name + namespace, I guess?

The part we automate here is the creation of a named service in the Elasticsearch namespace. Setting the right labels on the ES Pods + the right selector in the Kibana resource + the potential service spec is still the user's responsibility.

My first feeling about this is that there's a lot of implicit magic involved I don't feel comfortable with.

The first post approach seems a bit simpler and more explicit to me:

```
kind: Kibana
elasticsearchRef:
  name: my-elasticsearch-cluster
  service: es-coordinator-nodes
---
kind: Service
metadata:
    name: es-coordinator-nodes
<entirely user-defined>
```

I can easily see how to document that behaviour through an example, and I guess it will speak by itself to anyone used to Kubernetes services.
Documenting the implicit service feature seems a bit more complicated.
