### ISSUE TITLE
context deadline exceeded with Reconciler error

### ISSUE THREAD

**Issue by asfalots** [elastic/cloud-on-k8s#3799]
<!-- Bug report -->
## Bug Report
**What did you do?**

I wrongly edit my elasticsearch ressource.  I tried to update volume size instead of following documentation (about creating or renaming the stack).  So the operator only show the status: "Applying change".
After fixing my mistake in the manifest, I'll try to update it and get
```
Error from server: error when applying patch: 
{...}                                                                                                                          
to Resource: "elasticsearch.k8s.elastic.co/v1, Resource=elasticsearches", GroupVersionKind: "elasticsearch.k8s.elastic.co/v1,Kind=Elasticsearch",Name: "live", Namespace: "logging" 
for: "elastic.yaml": context deadline exceeded                                                                                                                                                                                                                                                                                                                                                                                                      
```

**What did you expect to see?**

Be able to fix my mistake and not block further deployment

**What did you see instead? Under which circumstances?**
`context deadline exceeded`
**Environment**

* ECK version:

	1.2.1

* Kubernetes information:
** EKS 1.16.10

```
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-eks-2ba888", GitCommit:"2ba888155c7f8093a1bc06e3336333fbdb27b3da", GitTreeState:"clean", BuildDate:"2020-07-17T18:48:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

* Resource definition:
```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: live
spec:
  version: 7.9.2
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  updateStrategy:
    changeBudget:
      maxSurge: 3
      maxUnavailable: 1
  nodeSets:
  - name: master
    count: 3
    config:
      node.master: true
      node.data: false
      node.ingest: false
      node.store.allow_mmap: false
    podTemplate:
      spec:
        nodeSelector:
          group: infra
        containers:
          - name: elasticsearch
            env:
              - name: ES_JAVA_OPTS
                value: "-Xms2g -Xmx2g"
            resources:
              requests:
                memory: 2Gi
                cpu: 0.5
              limits:
                memory: 4Gi
                cpu: 1
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        - name: install-plugins
          command:
          - sh
          - -c
          - |
            bin/elasticsearch-plugin install --batch repository-s3
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: gp2
  - name: data
    count: 3
    config:
      node.master: false
      node.data: true
      node.ingest: false
      node.ml: false
    podTemplate:
      spec:
        nodeSelector:
          group: infra
        containers:
          - name: elasticsearch
            env:
              - name: ES_JAVA_OPTS
                value: "-Xms4g -Xmx4g"
            resources:
              requests:
                memory: 4Gi
                cpu: 0.5
              limits:
                memory: 8Gi
                cpu: 2
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        - name: install-plugins
          command:
          - sh
          - -c
          - |
            bin/elasticsearch-plugin install --batch repository-s3
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: gp2
  - name: data200
    count: 2
    config:
      node.master: false
      node.data: true
      node.ingest: false
      node.ml: false
    podTemplate:
      spec:
        nodeSelector:
          group: infra
        containers:
          - name: elasticsearch
            env:
              - name: ES_JAVA_OPTS
                value: "-Xms4g -Xmx4g"
            resources:
              requests:
                memory: 4Gi
                cpu: 0.5
              limits:
                memory: 8Gi
                cpu: 2
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        - name: install-plugins
          command:
          - sh
          - -c
          - |
            bin/elasticsearch-plugin install --batch repository-s3
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 200Gi
        storageClassName: gp2
  - name: ingest
    count: 2
    config:
      node.master: false
      node.data: false
      node.ingest: true
      node.ml: false
    podTemplate:
      spec:
        nodeSelector:
          group: infra
        containers:
          - name: elasticsearch
            env:
              - name: ES_JAVA_OPTS
                value: "-Xms4g -Xmx4g"
            resources:
              requests:
                memory: 4Gi
                cpu: 0.5
              limits:
                memory: 6Gi
                cpu: 1
        volumes:
        - name: elasticsearch-data
          emptyDir: {}
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        - name: install-plugins
          command:
          - sh
          - -c
          - |
            bin/elasticsearch-plugin install --batch repository-s3

```

* Logs:
```
{
  "log.level": "error",
  "@timestamp": "2020-10-06T13:30:06.236Z",
  "log.logger": "controller-runtime.controller",
  "message": "Reconciler error",
  "service.version": "1.2.1-b5316231",
  "service.type": "eck",
  "ecs.version": "1.4.0",
  "controller": "elasticsearch-controller",
  "request": "logging/live",
  "error": "StatefulSet.apps \"live-es-data\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden",
  "errorCauses": [
    {
      "error": "StatefulSet.apps \"live-es-data\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden"
    }
  ],
  "error.stack_trace": "github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:88"
}
```
