### ISSUE TITLE
helm chart: missing Role for operator

### ISSUE THREAD

**Issue by weisdd** [elastic/cloud-on-k8s#3807]
## Bug Report
There's an issue with the ECK Operator helm chart:
When using `managedNamespaces` with `createClusterScopedResources: false`, and the operator is being installed in a different namespace (not listed in `managedNamespaces`), `operator-role-binding.yaml` creates a RoleBinding pointing at a non-existent Role.

```yaml
managedNamespaces: ["eck"]

createClusterScopedResources: false

refs:
  enforceRBAC: true

webhook:
  enabled: false
```

```bash

(microk8s:elastic-system)➜  ~ k describe rolebinding
Name:         elastic-operator
Labels:       app.kubernetes.io/instance=eck-operator
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=elastic-operator
              app.kubernetes.io/version=1.3.0-SNAPSHOT
              helm.sh/chart=eck-operator-1.3.0-SNAPSHOT
Annotations:  meta.helm.sh/release-name: eck-operator
              meta.helm.sh/release-namespace: elastic-system
Role:
  Kind:  Role
  Name:  elastic-operator
Subjects:
  Kind            Name              Namespace
  ----            ----              ---------
  ServiceAccount  elastic-operator  elastic-system

(microk8s:elastic-system)➜  ~ k get role
No resources found in elastic-system namespace.
```

**What did you expect to see?**
Both Role and RoleBinding are created in the operator's namespace.

**What did you see instead? Under which circumstances?**
Only RoleBinding is created the operator's namespace when using `managedNamespaces` with `createClusterScopedResources: false`, and the operator is being installed in a different namespace (not listed in managedNamespaces).

**Environment**

* ECK version:

	1.2.1 (I've adjusted the chart a bit to make it work with 1.2.1)

* Kubernetes information:
	* Kubernetes distribution: microk8s v1.19.0 (v1.19.0-34+1a52fbf0753680)
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-19T09:16:25Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.0-34+1a52fbf0753680", GitCommit:"1a52fbf07536803015220f0a991187db5b42c8ae", GitTreeState:"clean", BuildDate:"2020-09-02T11:33:05Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by weisdd** [comment]
If trying to follow the current chart structure, I think something like this will do the trick:
`operator-role.yaml`
```yaml
{{- $operatorNSIsManaged := has .Release.Namespace .Values.managedNamespaces -}}
{{- if and (not $operatorNSIsManaged) (not .Values.createClusterScopedResources) -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "eck-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "eck-operator.labels" $ | nindent 4 }}
rules:
{{ template "eck-operator.rbacRules" . | toYaml | indent 2 }}
{{- end -}}
```
