### ISSUE TITLE
Failed to parse PEM block containing private key

### ISSUE THREAD

**Issue by Xat59** [elastic/cloud-on-k8s#3819]
## Bug Report
**What did you do?**
I'm trying to configure my own certificate within elastic-on-k8s and I've followed this documentation : https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-tls-certificates.html#k8s-setting-up-your-own-certificate .

My own certificate is signed by a well-known CA (not self signed).

**What did you expect to see?**
kibana and elasticsearch pods start with my own certificate.

**What did you see instead? Under which circumstances?**
Kibana and elasticsearch pods do not start at all, and elastic-operator gives me this information : "Updated current TLS certificate". 
Then after, I always get the following error from the elastic-operator pod : "failed to parse PEM block containing private key."

**Environment**

* ECK version: 7.9.1

* Kubernetes information: Kubernetes cluster is deployed on AKS.

kubectl version : 

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.11", GitCommit:"3a3612132641768edd7f7e73d07772225817f630", GitTreeState:"clean", BuildDate:"2020-09-02T06:46:33Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

* Resource definition:

create k8s resource named ```secretName: elastic-ssl-certificates``` :

```
---
apiVersion: v1
kind: Secret
metadata:
  name: elastic-ssl-certificates
  namespace: elastic-system
type: Opaque
stringData:
  tls.crt: "<certificate>"
  tls.req: "<certificate>"
  tls.key: "<privkey>"
...
```

elastic deployment : 

```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
  namespace: elastic-system
spec:
  version: 7.9.1
  nodeSets:
  - name: default
    count: 3
    config:
      node.master: true
      node.data: true
      node.ingest: true
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        - name: install-plugins
          command: ['sh', '-c', 'bin/elasticsearch-plugin install --batch repository-azure']

  http:
    tls:
      certificate:
        secretName: elastic-ssl-certificates
      selfSignedCertificate:
        disabled: true

  secureSettings:
  - secretName: 'es-azure-repo-settings'
```

* Logs:

See the TLS certificiate has been updated when looking into elastic-operator logs : 

```
{"log.level":"info","@timestamp":"2020-10-09T15:11:40.248Z","log.logger":"controller-runtime.certwatcher","message":"Updated current TLS certificate","service.version":"1.2.1-b5316231","service.type":"eck","ecs.version":"1.4.0"}
{"log.level":"info","@timestamp":"2020-10-09T15:11:40.248Z","log.logger":"controller-runtime.certwatcher","message":"Updated current TLS certificate","service.version":"1.2.1-b5316231","service.type":"eck","ecs.version":"1.4.0"}
```

Then after, I always get the following error, always from the elastic-operator logs : 

```
{"log.level":"info","@timestamp":"2020-10-09T15:21:12.218Z","log.logger":"elasticsearch-controller","message":"Starting reconciliation run","service.version":"1.2.1-b5316231","service.type":"eck","ecs.version":"1.4.0","iteration":25,"namespace":"elastic-system","es_name":"quickstart"}
{"log.level":"info","@timestamp":"2020-10-09T15:21:12.219Z","log.logger":"elasticsearch-controller","message":"Ending reconciliation run","service.version":"1.2.1-b5316231","service.type":"eck","ecs.version":"1.4.0","iteration":25,"namespace":"elastic-system","es_name":"quickstart","took":0.000987162}
{"log.level":"error","@timestamp":"2020-10-09T15:21:12.219Z","log.logger":"controller-runtime.controller","message":"Reconciler error","service.version":"1.2.1-b5316231","service.type":"eck","ecs.version":"1.4.0","controller":"elasticsearch-controller","request":"elastic-system/quickstart","error":"**failed to parse PEM block containing private key**","errorCauses":[{"error":"failed to parse PEM block containing private key","errorVerbose":"failed to parse PEM block containing private key\ngithub.com/elastic/cloud-on-k8s/pkg/controller/common/certificates.ParsePEMPrivateKey\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/common/certificates/pem.go:63\ngithub.com/elastic/cloud-on-k8s/pkg/controller/common/certificates.CertificatesSecret.Validate\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/common/certificates/secret.go:92\ngithub.com/elastic/cloud-on-k8s/pkg/controller/common/certificates.Reconciler.ReconcileInternalHTTPCerts\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/common/certificates/http_reconcile.go:106\ngithub.com/elastic/cloud-on-k8s/pkg/controller/common/certificates.Reconciler.ReconcileCAAndHTTPCerts\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/common/certificates/reconcile.go:81\ngithub.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/certificates.Reconcile\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/certificates/reconcile.go:72\ngithub.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/driver.(*defaultDriver).Reconcile\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/driver/driver.go:134\ngithub.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch.(*ReconcileElasticsearch).internalReconcile\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/elasticsearch_controller.go:308\ngithub.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch.(*ReconcileElasticsearch).Reconcile\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/elasticsearch_controller.go:215\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:88\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373"}],"error.stack_trace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:88"}
```
