### ISSUE TITLE
Cannot apply patch with merge strategy on nodeSets field

### ISSUE THREAD

**Issue by wmellouli** [elastic/cloud-on-k8s#3878]
## Proposal

Given this base definition of an elasticsearch cluster of 3 masters nodes and 6 data-ingest nodes.

```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 7.9.2
  image: elasticsearch
  nodeSets:
    - name: masters
      count: 3
      config:
        node.master: true
        node.data: false
        node.ingest: false
    - name: ingest-data
      count: 6
      config:
        node.master: false
        node.data: true
        node.ingest: true
```

When I apply a `patchesStrategicMerge` with `kustomize`, to patch elasticsearch `image` and change `masters` count to `1` instead of `3`, with this patch:

```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  image: elasticsearch/elasticsearch:7.9.2
  nodeSets:
  - name: masters
    count: 1
```

So when applying this patch to base version defined above, I get this result (I notice `replace` behavior instead of `merge`):

```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 7.9.2
  image: elasticsearch/elasticsearch:7.9.2
  nodeSets:
    - name: masters
      count: 1
```

But I was expecting a merge with base version and with `patchMergeKey` the field `name` of each `NodeSet`:

```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 7.9.2
  image: elasticsearch/elasticsearch:7.9.2
  nodeSets:
    - name: masters
      count: 1
      config:
        node.master: true
        node.data: false
        node.ingest: false
    - name: ingest-data
      count: 6
      config:
        node.master: false
        node.data: true
        node.ingest: true
```
