### ISSUE TITLE
Keystore error when upgrading to 7.10.0

### ISSUE THREAD

**Issue by hamishforbes** [elastic/cloud-on-k8s#3934]
## Bug Report
**What did you do?**
Changed `.spec.version` on my Elasticsearch resource from `7.9.3` to `7.10.0`

**What did you expect to see?**
Upgrade to 7.10.0

**What did you see instead? Under which circumstances?**
New pods launched with the 7.10.0 container crash loop with an error:

```
Exception in thread "main" org.elasticsearch.bootstrap.BootstrapException: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/config/elasticsearch.keystore
Likely root cause: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/config/elasticsearch.keystore
```

The `elastic-internal-init-filesystem` logs that it completed successfully

```
Keystore initialization successful.
```

I have 1 `secureSettings` entry, to inject AWS credentials because the S3 snapshot plugin doesn't support EKS IAM role authentication properly.

I also can't back out of this upgrade with just the operator, even though a 7.10.0 pod has never successfully started the only way I can get my cluster back to green is to manually edit the statefulsets from 7.10.0 back to 7.9.3, which then start up perfectly.

--

**Environment**

* ECK version:  1.3.0

* Kubernetes information: EKS v1.18.8

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T19:10:21Z", GoVersion:"go1.15.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.8-eks-7c9bda", GitCommit:"7c9bda52c425d0d56d7b93f1377a826b4132c05c", GitTreeState:"clean", BuildDate:"2020-08-28T23:04:33Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by sebgl** [comment]
@hamishforbes thanks for creating the issue.
I'm trying to reproduce locally. I didn't get into any similar error so far.

To reproduce, I'm upgrading from a 7.9.2 cluster with secure settings in the keystore:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
spec:
  version: 7.9.2
  nodeSets:
  - name: default
    count: 3
    config:
      node.store.allow_mmap: false
  secureSettings:
  - secretName: your-secure-settings-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: your-secure-settings-secret
stringData:
  xpack.notification.email.account.foo.smtp.secure_password: mypassword
```

to a 7.10.0 cluster:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
spec:
  version: 7.10.0
  nodeSets:
  - name: default
    count: 3
    config:
      node.store.allow_mmap: false
  secureSettings:
  - secretName: your-secure-settings-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: your-secure-settings-secret
stringData:
  xpack.notification.email.account.foo.smtp.secure_password: mypassword
```

The version upgrade to 7.10.0 goes smoothly.

@hamishforbes could you give us your Elasticsearch yaml manifests (similar to the above) and keystore content (hiding your AWS credentials, of course) so we can try to reproduce?
