### ISSUE TITLE
How to enable audit logs for elasticssearch and kibana

### ISSUE THREAD

**Issue by bikkinamahesh369** [elastic/cloud-on-k8s#3936]
how to enable audit logs for kibana and elasticsearch using the operator in k8s env.
Can anyone help me here

Thanks in advance.

**Comment by sebgl** [comment]
You can set `xpack.security.audit.enabled: true` in the Elasticsearch config. Audit logs will end up in the container's stdout by default.

Example:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
spec:
  version: 7.10.0
  nodeSets:
  - name: default
    count: 1
    config:
      xpack.security.audit.enabled: true
```

Note that you need a non-basic license to rely on audit logs. See [this example](https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-licensing.html) to setup a trial ECK license.
