### ISSUE TITLE
[docs] Add example or recommend using YAML anchors for Elasticsearch

### ISSUE THREAD

**Issue by a03nikki** [elastic/cloud-on-k8s#3947]
### Overview

Add an example or include information about YAML anchors to make users' lives easier.

### Details

For large Elasticsearch clusters, the YAML file for building them includes [multiple `nodeSets` for multiple Elasticsearch node roles](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-advanced-node-scheduling.html#k8s-define-elasticsearch-nodes-roles).  When there are multiple [`nodeSets`](https://www.elastic.co/guide/en/cloud-on-k8s/1.4/k8s-orchestration.html#k8s-nodesets), repeating "common" Elasticsearch configuration across them becomes cumbersome and error prone.

Most users of YAML do not know the advanced features of the language. Rather, they understand the basics of "no spaces, not tabs" and the common syntax seen in program configuration files such as Arrays.  The [anchors functionality](https://yaml.org/spec/1.2/spec.html#id2765878) can be used to [not repeat blocks of code](https://support.atlassian.com/bitbucket-cloud/docs/yaml-anchors/).

By using YAML anchors, the "common" Elasticsearch configuration does not need to be repeated.

For example, instead of repeating `xpack.monitoring.*` and `node.store.allow_mmap` in each `config` block, such as 

```yaml
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.9.3
  nodeSets:
    - name: master
      count: 1
      config:
        xpack.monitoring.collection.enabled: true
        xpack.monitoring.elasticsearch.collection.enabled: false
        node.store.allow_mmap: false
        node.master: true
        node.data: false
        node.ingest: false
        node.remote_cluster_client: false
    - name: ingest-data
      count: 1
      config:
        xpack.monitoring.collection.enabled: true
        xpack.monitoring.elasticsearch.collection.enabled: false
        node.store.allow_mmap: false
        node.master: false
        node.data: true
        node.ingest: true
        node.attr.data: hot
    - name: warm-data
      count: 1
      config:
        xpack.monitoring.collection.enabled: true
        xpack.monitoring.elasticsearch.collection.enabled: false
        node.store.allow_mmap: false
        node.master: false
        node.data: true
        node.attr.data: warm
```

it can be declared once and re-used as follows

```yaml
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.9.3
  nodeSets:
    - name: master
      count: 1
      #Uses Yaml anchors to avoid repeating config
      config: &myconf
        xpack.monitoring.collection.enabled: true
        xpack.monitoring.elasticsearch.collection.enabled: false
        node.store.allow_mmap: false
        node.master: true
        node.data: false
        node.ingest: false
        node.remote_cluster_client: false
    - name: ingest-data
      count: 1
      config:
        <<: *myconf
        node.master: false
        node.data: true
        node.ingest: true
        node.attr.data: hot
    - name: warm-data
      count: 1
      config:
        <<: *myconf
        node.master: false
        node.data: true
        node.attr.data: warm
```
