### ISSUE TITLE
Filebeat 7.11.0-SNAPSHOT e2e tests fail due to k8s api nodes permissions

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#3966]
https://devops-ci.elastic.co/job/cloud-on-k8s-e2e-tests-snapshot-versions/190//testReport

Filebeat logs: 

```
E1120 01:39:41.347999       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125: Failed to list *v1.Node: nodes "gke-eck-7x-snapshot-190--default-pool-58ca238c-cz38" is forbidden: User "system:serviceaccount:e2e-zsko0-mercury:test-fb-default-cfg-fbwq-sa" cannot list resource "nodes" in API group "" at the cluster scope
```

Looks like this recent version of Filebeat requests the k8s api for k8s nodes by default, but didn't do it in earlier versions?

File beat config:

```
filebeat:
  autodiscover:
    providers:
    - type: kubernetes
      host: ${HOSTNAME}
      hints:
        enabled: true
        default_config:
          type: container
          paths:
          - /var/log/containers/*${data.kubernetes.container.id}.log
processors:
- add_cloud_metadata: {}
- add_host_metadata: {}
```
