### ISSUE TITLE
[META] Elastic Agent CRD (standalone)

### ISSUE THREAD

**Issue by david-kow** [elastic/cloud-on-k8s#3997]
### Elastic Agent
ECK will support a new Elastic Agent CRD that enables to deploy and manage Elastic Agent. The current goal is to only provide support for the Agent running in the [standalone](https://www.elastic.co/guide/en/fleet/current/run-elastic-agent-standalone.html) mode.

### CRD
The approach I propose to take is based on our experience with Beats. There are only few changes between those CRDs, as below. I would not include any indication of `mode` (standalone vs fleet) yet, because we will only support one for now.

#### Remove
- `type` - there are no types of Elastic Agent to deploy, as it's driven by the config
- `kibanaRef` - as of now, Elastic Agent doesn't have any direct ties to Kibana, hence no ref
- `elasticsearchRef` - see "Add" below

#### Add
- `elasticsearchRefs` - multiple outputs can be defined for a single Elastic Agent, different inputs can use different outputs to send the data. Given that, we need:
  1. a way to reference multiple ES clusters (hence list, not a single item)
  2. an ability to name them, as this is how users will refer to them in other parts of the config (alternatively, we could derive the name from namespace and name, but this would force users to use those names instead of defining their own - I'd be against that).

#### Spec example

```yaml
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: elastic-agent
spec:
  version: 7.10.0
  image: docker.elastic.co/beats/elastic-agent:7.10.0

  configRef: ... # optional, instead of `config`
  secureSettings: ... # optional
  serviceAccountName: ... # optional
  daemonSet: ... # optional, one of `daemonSet, deployment`
  deployment: ... # optional, one of `daemonSet, deployment`

  elasticsearchRefs:
  - name: elasticsearch
    outputName: default
  - name: k8s-monitoring
    namespace: monitoring
    outputName: monitoringOut

  config:
    id: 2d70a6f0-33a5-11eb-bb2f-418d0388a8cf
    revision: 2
    agent:
      monitoring:
        enabled: true
        use_output: monitoringOut
        logs: true
        metrics: true
    inputs:
      - id: 2e187fb0-33a5-11eb-bb2f-418d0388a8cf
        name: system-1
        revision: 1
        type: logfile
        use_output: default
        meta:
          package:
            name: system
            version: 0.9.1
        data_stream:
          namespace: default
        streams:
...
```

### Not in scope
- Fleet and everything related to it (fetching api keys, agent enrolment)

### Work tracking

[Existing issues](https://github.com/elastic/cloud-on-k8s/issues?q=is%3Aissue+is%3Aopen+label%3Aelastic-agent)
