### ISSUE TITLE
Autoscaling specification placeholder

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#3998]
Users should be able to use the [Elasticsearch autoscaling API](https://github.com/elastic/elasticsearch/issues/51191) to automatically manage resources (storage, memory and cpu for now) allocated to `nodeSets`.

For example the user should be able to:
* [create associations between nodeSets and Elasticsearch autoscaling policies](https://github.com/elastic/cloud-on-k8s/issues/3955)
* describe resource constraints (min. / max. values) on the associated nodeSets
* tweak deciders settings

_(non-exhaustive list, the content of the spec should be discussed in a dedicated issue)_

It requires a place to specify the autoscaling configuration. As mentioned in https://github.com/elastic/cloud-on-k8s/issues/3955 we want to be able to iterate over the autoscaling specification without introducing a new version of the Elasticsearch CRD.

Two proposals have been identified so far:

### Option 1: Introduce a new (maybe temporary) CRDs ElasticsearchAutoscaling

```yaml
apiVersion: elasticsearch.k8s.elastic.co/alphav1
kind: ElasticsearchAutoscaling
metadata:
 name: quickstart
spec:
 elasticsearchRef:
    name: quickstart
 autoscalingPolicies:
 - name: master_data_ingest
   roles:  [ master, data, ingest ]
   minAllowed:
      count: 2
      cpu: 16
      memory: 8Gi
      storage: 10G
   maxAllowed:
      count: 6
      cpu: 16
      memory: 8Gi
      storage: 100G
   deciders: # optional, only for advanced users
   - storage:
       settings:
       - name: "forecast_window"
         value: "60s"
   behavior: # optional, we would provide some "sane" defaults
     scaleDown:
       stabilizationWindow: "5m"
       policies: TBD
```

| Pros              | Cons                                                                                                                                |
|-------------------|-------------------------------------------------------------------------------------------------------------------------------------|
| • Schema validation on the client side | • Require a symbolic reference to a cluster, it might be not obvious for a user to understand which `ElasticsearchAutoscaling` is managing a given cluster<br>• CRD lifecycle management in the long term might be a burden (move to beta ? deprecate it ?) |

### Option 2: Store the autoscaling spec in an annotation. Once stable update the Elasticsearch v1 CRD.

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  annotations:
    elasticsearch.alpha.elastic.co/autoscaling-spec: '[
          {
              "name": "mdi",
              "roles": [ "master", "data", "ingest" ],
              "minAllowed" : {
                "count" : 1,
                "cpu" : "1",
                "memory" : "3Gi",
                "storage" : "5Gi"
              },
              "maxAllowed" : {
                "count" : 6,
                "cpu" : "3",
                "memory" : "4Gi",
                "storage" : "10Gi"
              }
          }
      ]'
 name: quickstart
spec:
  version: 7.11.0
  nodeSets:
    - name: data-zone-b
      config:
        node.attr.zone: europe-west1-b
        cluster.routing.allocation.awareness.attributes: zone
        node:
          roles: [ "master", "data", "ingest" ]
  nodeSets:
    - name: data-zone-c
      config:
        node.attr.zone: europe-west1-c
        cluster.routing.allocation.awareness.attributes: zone
        node:
          roles: [ "master", "data", "ingest" ]
```

| Pros              | Cons                                                                                                                                |
|-------------------|-------------------------------------------------------------------------------------------------------------------------------------|
| • Lifecycle of an annotation is easier to manage<br>• Autoscaling spec is integrated with the Elasticsearch spec, which seems more intuitive | • No schema validation, but it can still be done in the webhook or in the controller _(also it would be a temporary situation)_  |

I would lean towards option 2, it seems lightweight, also it seems to me that it is easier to understand the whole cluster behaviour if the autoscaling spec is a part of the Elasticsearch one.
