### ISSUE TITLE
Support for custom realms for Elasticsearch authentication.

### ISSUE THREAD

**Issue by nkvoll** [elastic/cloud-on-k8s#40]
By default we will use the file realm for our internal uses and let consumers of our deployment use the ES native realm. For larger deployments, custom realms become more important:

These resources might have to include a versioned component as well (not all of these are as important as the others):

- SAML
- LDAP
- Oauth / OpenID connect

In some cases, this would also entail installing a certificate (e.g ldaps) so we can support encryption.

**Comment by nkvoll** [comment]
Now supported through a mixture of `podTemplate` and `config.

**Comment by iahmad-khan** [comment]
Hi,

Any documentation how to enable LDAP user auth through ECK operator?

**Comment by thbkrkr** [comment]
> Any documentation how to enable LDAP user auth through ECK operator?

There is no special thing to do to configure LDAP authentication for Elasticsearch when using ECK.

See the Elasticsearch documentation to configure LDAP: https://www.elastic.co/guide/en/elasticsearch/reference/current/ldap-realm.html#ldap-realm-configuration

See the ECK documentation to add settings to the Elasticsearch configuration:
https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-node-configuration.html

Note that in version `1.0.0-beta1`, we introduced a regression that by default disables the native realm. If you want it, you need explicitely declare it (https://discuss.elastic.co/t/new-user-cant-login-kibana/204810/2).

**Comment by iahmad-khan** [comment]
Great, Thanks

**Comment by iahmad-khan** [comment]
@thbkrkr I tried this config but doesnt seem to take any effect , is there a way to chck where it is failing? I don't see any ldap config created by operator.


```
cat <<EOF | kubectl apply -f -
apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: livelogs
  namespace: livelogs
spec:
  version: 7.5.0
  nodeSets:
  - name: livelogs
    count: 3
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
          resources:
            limits:
              memory: 24Gi
              cpu: 4
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms16g -Xmx16g"
  http:
    service:
      spec:
        type: NodePort
    tls:
      selfSignedCertificate:
        disabled: true
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 500Gi
        storageClassName: standard-01
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: true
      xpack.security.authc.realms:
        ldap:
          ldap1:
            order: 0
            url: "ldaps://hh-ldap.mydomain"
            bind_dn: "ou=people, dc=example, dc=com"
            user_search:
              base_dn: "dc=example,dc=com"
              filter: "(uid={0})"
            group_search:
              base_dn: "example,dc=com"
EOF


```

**Comment by thbkrkr** [comment]
The `volumeClaimTemplates` and `config` fields must be under a `nodeSet` object. In your manifest, the `http` section is misplaced and breaks this.

Corrected manifest:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: livelogs
  namespace: livelogs
spec:
  version: 7.5.0
  nodeSets:
  - name: livelogs
    count: 3
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
          resources:
            limits:
              memory: 24Gi
              cpu: 4
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms16g -Xmx16g"
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: true
      xpack.security.authc.realms:
        ldap:
          ldap1:
            order: 0
            url: "ldaps://hh-ldap.mydomain"
            bind_dn: "ou=people, dc=example, dc=com"
            user_search:
              base_dn: "dc=example,dc=com"
              filter: "(uid={0})"
            group_search:
              base_dn: "example,dc=com"
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 500Gi
        storageClassName: standard-01
  http:
    service:
      spec:
        type: NodePort
    tls:
      selfSignedCertificate:
        disabled: true
```
