### ISSUE TITLE
Updating Pod Template Annotations does not update the StatefulSet  

### ISSUE THREAD

**Issue by austince** [elastic/cloud-on-k8s#4004]
## Bug Report
**What did you do?**

Update an `v1/Elasticsearch`'s `podTemplate.metadata.annotations`.

**What did you expect to see?**

Changed annotations propagated to the stateful set. Changes are propagated when changing other pod info, like the env.

**What did you see instead? Under which circumstances?**

The reconciliation end without updating the stateful set.

**Environment**

* ECK version:

	1.3.0

* Kubernetes information:
	* Cloud: EKS  w/ k8s v1.17

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:47:40Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.12-eks-7684af", GitCommit:"7684af4ac41370dd109ac13817023cb8063e3d45", GitTreeState:"clean", BuildDate:"2020-10-20T22:57:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

```

* Resource definition:
I can provide, but any should work.

* Logs:
```
elastic-system/elastic-operator-0[manager]: {"log.level":"info","@timestamp":"2020-12-02T20:01:41.214Z","log.logger":"elasticsearch-controller","message":"Starting reconciliation run","service.version":"1.3.0+6db1914b","service.type":"eck","ecs.version":"1.4.0","iteration":806,"namespace":"entity-resolution","es_name":"eck-entity-resolution"}
elastic-system/elastic-operator-0[manager]: {"log.level":"info","@timestamp":"2020-12-02T20:01:41.228Z","log.logger":"license-controller","message":"Starting reconciliation run","service.version":"1.3.0+6db1914b","service.type":"eck","ecs.version":"1.4.0","iteration":458,"namespace":"entity-resolution","es_name":"eck-entity-resolution"}
elastic-system/elastic-operator-0[manager]: {"log.level":"info","@timestamp":"2020-12-02T20:01:41.229Z","log.logger":"remotecluster-remoteca","message":"Starting reconciliation run","service.version":"1.3.0+6db1914b","service.type":"eck","ecs.version":"1.4.0","iteration":1640,"namespace":"entity-resolution","es_name":"eck-entity-resolution"}
elastic-system/elastic-operator-0[manager]: {"log.level":"info","@timestamp":"2020-12-02T20:01:41.230Z","log.logger":"remotecluster-remoteca","message":"Ending reconciliation run","service.version":"1.3.0+6db1914b","service.type":"eck","ecs.version":"1.4.0","iteration":1640,"namespace":"entity-resolution","es_name":"eck-entity-resolution","took":0.000599707}
elastic-system/elastic-operator-0[manager]: {"log.level":"info","@timestamp":"2020-12-02T20:01:41.230Z","log.logger":"association.kb-es-association-controller","message":"Starting reconciliation run","service.version":"1.3.0+6db1914b","service.type":"eck","ecs.version":"1.4.0","iteration":837,"namespace":"entity-resolution","kb_name":"eck-entity-resolution"}
elastic-system/elastic-operator-0[manager]: {"log.level":"info","@timestamp":"2020-12-02T20:01:41.268Z","log.logger":"license-controller","message":"Ending reconciliation run","service.version":"1.3.0+6db1914b","service.type":"eck","ecs.version":"1.4.0","iteration":458,"namespace":"entity-resolution","es_name":"eck-entity-resolution","took":0.040335938}
elastic-system/elastic-operator-0[manager]: {"log.level":"info","@timestamp":"2020-12-02T20:01:41.369Z","log.logger":"association.kb-es-association-controller","message":"Ending reconciliation run","service.version":"1.3.0+6db1914b","service.type":"eck","ecs.version":"1.4.0","iteration":837,"namespace":"entity-resolution","kb_name":"eck-entity-resolution","took":0.139097844}
elastic-system/elastic-operator-0[manager]: {"log.level":"info","@timestamp":"2020-12-02T20:01:41.643Z","log.logger":"zen2","message":"Ensuring no voting exclusions are set","service.version":"1.3.0+6db1914b","service.type":"eck","ecs.version":"1.4.0","namespace":"entity-resolution","es_name":"eck-entity-resolution"}
elastic-system/elastic-operator-0[manager]: {"log.level":"info","@timestamp":"2020-12-02T20:01:41.662Z","log.logger":"migrate-data","message":"Setting routing allocation excludes","service.version":"1.3.0+6db1914b","service.type":"eck","ecs.version":"1.4.0","namespace":"entity-resolution","es_name":"eck-entity-resolution","value":"none_excluded"}
elastic-system/elastic-operator-0[manager]: {"log.level":"info","@timestamp":"2020-12-02T20:01:41.854Z","log.logger":"elasticsearch-controller","message":"Ending reconciliation run","service.version":"1.3.0+6db1914b","service.type":"eck","ecs.version":"1.4.0","iteration":806,"namespace":"entity-resolution","es_name":"eck-entity-resolution","took":0.639720261}
```

Seems very similar to https://github.com/elastic/cloud-on-k8s/issues/2854, though I've checked that the pods are able to be created. There don't seem to be any events about this either. 

I'm trying to force a reboot of these pods when the file realm user config changes by adding the checksums as annotations. Without this, I'm unable to update the passwords/ user info.

**Comment by barkbay** [comment]
> Update an v1/Elasticsearch's podTemplate.metadata.annotations

I did a test using the following manifest:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
spec:
  version: 7.10.0
  nodeSets:
  - name: default
    config:
      node.roles: ["master", "data", "ingest", "ml"]
      node.store.allow_mmap: false
    podTemplate:
      metadata:
        annotations:
          annotation1: value1
    count: 1
```

A first Pod is deployed with the expected annotation:

```
k get pod/elasticsearch-sample-es-default-0 -o jsonpath='{.metadata.annotations}' | jq
```

```json
{
  "annotation1": "value1",
  "co.elastic.logs/module": "elasticsearch",
  "kubernetes.io/limit-ranger": "LimitRanger plugin set: cpu request for container elasticsearch",
  "update.k8s.elastic.co/timestamp": "2020-12-03T13:25:42.970731188Z"
}
```

If I update the Elasticsearch resource with a new value for `annotation1` the Pod is deleted and recreated as expected:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
spec:
  version: 7.10.0
  nodeSets:
  - name: default
    config:
      node.roles: ["master", "data", "ingest", "ml"]
      node.store.allow_mmap: false
    podTemplate:
      metadata:
        annotations:
          annotation1: value2
    count: 1
```

```
k get pod/elasticsearch-sample-es-default-0 -o jsonpath='{.metadata.annotations}' | jq
```
```json
{
  "annotation1": "value2",
  "co.elastic.logs/module": "elasticsearch",
  "kubernetes.io/limit-ranger": "LimitRanger plugin set: cpu request for container elasticsearch",
  "update.k8s.elastic.co/timestamp": "2020-12-03T13:30:19.228146722Z"
}
```

It seems to be working as expected but maybe I'm missing something. Could you give me more details about how you are updating your Elasticsearch resource ?
