### ISSUE TITLE
Cannot create Kibana with the pod security policy "readOnlyRootFilesystem=true"

### ISSUE THREAD

**Issue by masa213f** [elastic/cloud-on-k8s#4022]
## Bug Report
**What did you do?**

I try to deploy Kibana using ECK 1.2.1.

**What did you expect to see?**

The Kibana is deployed successfully.

**What did you see instead? Under which circumstances?**

The initContainer of Kibana get failed due to the pod security policy of `readOnlyRootFilesystem=true`.

**Environment**

* ECK version:

	1.2.1 (Commit ID: b53162318c2013478398a966d6cd6f43ddb95a02 )

* Kubernetes information:

	* On premise
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-16T13:56:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"archive", BuildDate:"2020-09-17T02:53:25Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

* Resource definition:

**Kibana CR**
```
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-sample
  namespace: sandbox
spec:
  version: 7.4.2
  count: 1
  elasticsearchRef:
    name: "elastic-sample"
  http:
    service:
      metadata:
        annotations:
          projectcontour.io/upstream-protocol.tls: "5601,https"
  podTemplate:
    spec:
      containers:
      - name: kibana
        volumeMounts:
          - mountPath: /usr/share/kibana/optimize
            name: kibana-optimize
          - mountPath: /usr/share/kibana/data
            name: kibana-data
        resources:
          requests:
            memory: 4Gi
            cpu: 1
          limits:
            memory: 8Gi
            cpu: 2
      securityContext:
        runAsUser: 1000
      volumes:
        - name: kibana-optimize
          emptyDir: {}
        - name: kibana-data
          emptyDir: {}
```

* Logs:
```
$ kubectl logs -n sandbox kibana-sample-kb-78c568b88-w4279 elastic-internal-init-config
+ init_config_initialized_flag=/usr/share/kibana/config/elastic-internal-init-config.ok
+ [[ -f /usr/share/kibana/config/elastic-internal-init-config.ok ]]
+ echo 'Setup Kibana configuration'
Setup Kibana configuration
+ ln -sf /mnt/elastic-internal/kibana-config/kibana.yml /mnt/elastic-internal/kibana-config/telemetry.yml /mnt/elastic-internal/kibana-config-local/
+ touch /usr/share/kibana/config/elastic-internal-init-config.ok
touch: cannot touch '/usr/share/kibana/config/elastic-internal-init-config.ok': Read-only file system
```

* In my survey, the following path may be wrong.

https://github.com/elastic/cloud-on-k8s/blob/1.2.1/pkg/controller/kibana/init_configuration.go#L20

The `elastic-internal-init-config.ok` file should be created in `InitContainerConfigVolumeMountPath`.
