### ISSUE TITLE
ECK 

### ISSUE THREAD

**Issue by yoitsro** [elastic/cloud-on-k8s#4029]
## Bug Report
**What did you do?**
GKE performed an auto-upgrade.

**What did you expect to see?**
The elasticsearch cluster being spun back up with the same number of master nodes (2) and data nodes (2), with data intact and operational, along with the same `elastic` user password.

**What did you see instead? Under which circumstances?**
The elasticsearch cluster has started back up, but with 1 master node instead of the 2 as defined in the configuration. The `elastic` user has a different password.

The operator is stuck in this state:
```
NAME      HEALTH   NODES   VERSION   PHASE             AGE
staging   yellow   3       7.8.0     ApplyingChanges   17d
```

**Environment**

* ECK version:
1.3.0

* Kubernetes information:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.13-gke.1401", GitCommit:"00c919adfe4adf308bcd7c02838f2a1b60482f02", GitTreeState:"clean", BuildDate:"2020-11-25T01:04:47Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

I'm running an elasticsearch cluster on my Google Kubernetes Engine deployment.

The GKE deployment is made up of two preemptible nodes, meaning the nodes can be pulled down at any time. They're also setup with auto-upgrade enabled, auto-repair enabled, and surge upgrade enabled with a max surge size of 1.

When a node is pulled down due to preemptibility, a new node is spun up in its place and elasticsearch resumes without a problem.

This happens on another of our clusters which does not use preemptible nodes, and is setup with 3 master nodes, 3 data nodes and 3 client nodes. When the failure happens, the number of masters drops down to 2 and the same thing happens as what happens on our other cluster.

* Resource definition:
```
apiVersion: elasticsearch.k8s.elastic.co/v1beta1
kind: Elasticsearch
metadata:
  name: staging
  namespace: staging-internal
spec:
  version: 7.8.0
  updateStrategy:
    changeBudget:
      maxSurge: 1
      maxUnavailable: 0
  http:
    service:
      spec:
        selector:
          common.k8s.elastic.co/type: elasticsearch
          elasticsearch.k8s.elastic.co/cluster-name: staging
          elasticsearch.k8s.elastic.co/statefulset-name: staging-es-data
  nodeSets:
    # master nodes
    - count: 2
      name: masters
      config:
        node.master: true
        node.data: false
        node.ingest: false
        xpack.security.authc.realms.native.native1.order: 0
      podTemplate:
        spec:
          initContainers:
            - command:
                - sh
                - -c
                - sysctl -w vm.max_map_count=262144
              image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
              imagePullPolicy: IfNotPresent
              name: sysctl
              resources: {}
              securityContext:
                privileged: true
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          containers:
            - name: elasticsearch
              # specify resource limits and requests
              resources:
                limits:
                  cpu: 3
                  memory: 4Gi
                requests:
                  cpu: 2
                  memory: 2Gi
              env:
                - name: ES_JAVA_OPTS
                  value: "-Xms2g -Xmx2g"
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data # note: elasticsearch-data must be the name of the Elasticsearch volume
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
            storageClassName: elasticsearch-ssd
    # data nodes
    - count: 2
      name: data
      config:
        node.master: false
        node.data: true
        node.ingest: false
        xpack.security.authc.realms.native.native1.order: 0
      podTemplate:
        spec:
          initContainers:
            - command:
                - sh
                - -c
                - sysctl -w vm.max_map_count=262144
              image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
              imagePullPolicy: IfNotPresent
              name: sysctl
              resources: {}
              securityContext:
                privileged: true
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          containers:
            - name: elasticsearch
              # specify resource limits and requests
              resources:
                limits:
                  cpu: 3
                  memory: 4Gi
                requests:
                  cpu: 2
                  memory: 2Gi
              env:
                - name: ES_JAVA_OPTS
                  value: "-Xms2g -Xmx2g"
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data # note: elasticsearch-data must be the name of the Elasticsearch volume
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
            storageClassName: elasticsearch-ssd
```

* Logs:
### 1 hour's worth of operator logs
[downloaded-logs-20201210-111644.json.zip](https://github.com/elastic/cloud-on-k8s/files/5671943/downloaded-logs-20201210-111644.json.zip)

### 1 hour's worth of master node logs (for the same period)
[downloaded-logs-20201210-112342.json.zip](https://github.com/elastic/cloud-on-k8s/files/5671955/downloaded-logs-20201210-112342.json.zip)

### 1 hour's worth of data node logs (for the same period)
[downloaded-logs-20201210-112630.json.zip](https://github.com/elastic/cloud-on-k8s/files/5671972/downloaded-logs-20201210-112630.json.zip)
