### ISSUE TITLE
Configurable operator CLI tool to generate yaml files

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#404]
Configurable operator [meta issue](https://github.com/elastic/k8s-operators/issues/374) and [design proposal](https://github.com/elastic/k8s-operators/blob/master/docs/design/0005-configurable-operator.md).

As described in the design proposal, we need some tooling to generate yaml specifications of the operator(s) to deploy, including RBAC permissions.

An example (just a draft, can be implemented differently):

```bash
# cli sample usage (exact specification TBD)
> ./elastic-operator generate --config=operators.yaml
# generates one or multiple yaml files ready-to-deploy, including Deployment, ServiceAccount, (Cluster)Roles, (Cluster)RoleBindings, etc.
```

```yaml
# sample configuration (exact specification TBD)
operators:
    # manage clusters in namespace "team-A-production"
    - image: docker.elastic.co/k8s-operators:1.0
      roles: ["elasticsearch", "kibana"]
      managedNamespaces: ["team-A-production"]
      namespace: "team-A-production"
    # manage clusters in namespace "team-A-development"
    - image: docker.elastic.co/k8s-operators:1.1-alpha1
      roles: ["elasticsearch", "kibana"]
      managedNamespaces: ["team-A-development"]
      namespace: "team-A-development"
    # manage enterprise licenses in all namespaces
    - image: docker.elastic.co/k8s-operators:1.0
      roles: ["licensing"]
      clusterWide: true
      namespace: "elastic-system"
    # manage CCS/CCR in namespaces "team-A-production" and "team-B-production"
    - image: docker.elastic.co/k8s-operators:1.0
      roles: ["cross-cluster"]
      managedNamespaces: ["team-A-production", "team-B-production"]
      namespace: "elastic-system"
```
