### ISSUE TITLE
File realm roles.yml are not taken into account in Elasticsearch

### ISSUE THREAD

**Issue by paweltatarczuk** [elastic/cloud-on-k8s#4043]
## Bug Report
**What did you do?**

I have created a basic Elasticsearch instance following the quickstart guide with filerealm secret containg one user and role.

**What did you expect to see?**

Elasticsearch instance containing the user and role from the filerealm secret.

**What did you see instead? Under which circumstances?**

Elasticsearch instance containg the user and **no role** from the filerealm secret.

**Environment**

* ECK version:

	1.3.1

* Kubernetes information:

	Minikube v1.14.2

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

* Resource definition:
```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 7.10.1
  nodeSets:
    - name: default
      count: 1
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
      config:
        node.store.allow_mmap: false
  auth:
    fileRealm:
      - secretName: my-filerealm-secret
---
kind: Secret
apiVersion: v1
metadata:
  name: my-filerealm-secret
stringData:
  users: |-
    foo:$2a$10$BBJ/ILiyJ1eBTYoRKxkqbuDEdYECplvxnqQ47uiowE7yGqvCEgj9W
  users_roles: |-
    my_role:foo
  roles.yml: |-
    my_role:
      cluster: [ 'monitor' ]

```

* Logs:

elasticsearch-es-default-0:
```
{"type": "server", "timestamp": "2020-12-15T10:37:44,761Z", "level": "INFO", "component": "o.e.x.s.a.s.FileRolesStore", "cluster.name": "elasticsearch", "node.name": "elasticsearch-es-default-0", "message": "parsed [47] roles from file [/usr/share/elasticsearch/config/roles.yml]" }
```

elasticsearch-users:
```
$ kubectl exec elasticsearch-es-default-0 -- elasticsearch-users list
elastic-internal-probe: elastic_internal_probe_user
foo            : my_role*
elastic        : superuser
elastic-internal: superuser

 [*]   Role is not in the [/usr/share/elasticsearch/config/roles.yml] file. If the role has been created using the API, please disregard this message.
```
