### ISSUE TITLE
ECK didn't remove old nodes after changing the topology of the cluster

### ISSUE THREAD

**Issue by cebidhem** [elastic/cloud-on-k8s#4055]
## Bug Report
**What did you do?**
I have changed my elasticsearch definition from non zone-aware to zone-aware.

Basically, I ran a cluster with a nodeSet of 3 master nodes and 3 data nodes. It was not configured with nodeAffinity for zone awareness
I changed it to be zone-aware. I've updated the Elasticsearch CR to reflect it. Changed naming of nodes as well to include zone names (for masters and datas), and added the nodeAffinity to each, alongside a replicaSet per zone.

**What did you expect to see?**
I expected to have 3 masters and 3 datas, but dispatch into one zone each:
zone a=1 master+1 data
zone c=1 master+1 data
zone c=1 master+1 data

**What did you see instead? Under which circumstances?**
My cluster is now 12 nodes: 6 masters + 6 datas.

It looks like the operator hasn't detected the changes in the nodes that were already there, and instead has added new nodes without removing the old ones.

**Environment**

* ECK version:

1.3.0

* Kubernetes information:
EKS cluster

```
$ kubectl version
Client Version: v1.18.9
Server Version: v1.18.9-eks-d1db3c
```

* Resource definition:
BEFORE:
```yaml
nodeSets:
  - name: masters
    count: {{ .Values.elasticsearch.master.replicas }}
    config:
      node.roles: ["master"]
      xpack.ml.enabled: false
    podTemplate:
      spec:
```
AFTER:
```yaml
nodeSets:
  {{- range $values.elasticsearch.master.zones }}
  - name: master-{{ $values.elasticsearch.region }}{{ .id }}
    count: {{ .replicas }}
    config:
      node.roles: ["master"]
      xpack.ml.enabled: false
      node.attr.zone: {{ $values.elasticsearch.region }}{{ .id }}
      cluster.routing.allocation.awareness.attributes: k8s_node_name,zone
    podTemplate:
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: topology.kubernetes.io/zone
                  operator: In
                  values:
                  - {{ $values.elasticsearch.region }}{{ .id }}
  {{- end }}
```
* Logs:
```
{"log.level":"info","@timestamp":"2020-12-21T14:19:15.976Z","log.logger":"driver","message":"Creating master node","service.version":"1.3.0+6db1914b","service.type":"eck","ecs.version":"1.4.0","namespace":"monitoring","statefulset_name":"elastic-es-master-eu-west-1a","actualReplicas":0,"targetReplicas":1}
{"log.level":"info","@timestamp":"2020-12-21T14:19:15.977Z","log.logger":"driver","message":"Limiting master nodes creation to one at a time","service.version":"1.3.0+6db1914b","service.type":"eck","ecs.version":"1.4.0","namespace":"monitoring","statefulset_name":"elastic-es-master-eu-west-1b","target":1,"actual":0}
{"log.level":"info","@timestamp":"2020-12-21T14:19:15.978Z","log.logger":"driver","message":"Limiting master nodes creation to one at a time","service.version":"1.3.0+6db1914b","service.type":"eck","ecs.version":"1.4.0","namespace":"monitoring","statefulset_name":"elastic-es-master-eu-west-1c","target":1,"actual":0}
{"log.level":"info","@timestamp":"2020-12-21T14:19:15.983Z","log.logger":"generic-reconciler","message":"Creating resource","service.version":"1.3.0+6db1914b","service.type":"eck","ecs.version":"1.4.0","kind":"Secret","namespace":"monitoring","name":"elastic-es-master-eu-west-1a-es-config"}
{"log.level":"info","@timestamp":"2020-12-21T14:19:15.997Z","log.logger":"generic-reconciler","message":"Creating resource","service.version":"1.3.0+6db1914b","service.type":"eck","ecs.version":"1.4.0","kind":"Service","namespace":"monitoring","name":"elastic-es-master-eu-west-1a"}
{"log.level":"info","@timestamp":"2020-12-21T14:19:16.007Z","log.logger":"generic-reconciler","message":"Creating resource","service.version":"1.3.0+6db1914b","service.type":"eck","ecs.version":"1.4.0","kind":"StatefulSet","namespace":"monitoring","name":"elastic-es-master-eu-west-1a"}
{"log.level":"info","@timestamp":"2020-12-21T14:19:16.035Z","log.logger":"generic-reconciler","message":"Creating resource","service.version":"1.3.0+6db1914b","service.type":"eck","ecs.version":"1.4.0","kind":"Secret","namespace":"monitoring","name":"elastic-es-master-eu-west-1b-es-config"}
{"log.level":"info","@timestamp":"2020-12-21T14:19:16.046Z","log.logger":"generic-reconciler","message":"Creating resource","service.version":"1.3.0+6db1914b","service.type":"eck","ecs.version":"1.4.0","kind":"Service","namespace":"monitoring","name":"elastic-es-master-eu-west-1b"}
{"log.level":"info","@timestamp":"2020-12-21T14:19:16.055Z","log.logger":"generic-reconciler","message":"Creating resource","service.version":"1.3.0+6db1914b","service.type":"eck","ecs.version":"1.4.0","kind":"StatefulSet","namespace":"monitoring","name":"elastic-es-master-eu-west-1b"}
{"log.level":"info","@timestamp":"2020-12-21T14:19:16.076Z","log.logger":"generic-reconciler","message":"Creating resource","service.version":"1.3.0+6db1914b","service.type":"eck","ecs.version":"1.4.0","kind":"Secret","namespace":"monitoring","name":"elastic-es-master-eu-west-1c-es-config"}
{"log.level":"info","@timestamp":"2020-12-21T14:19:16.082Z","log.logger":"generic-reconciler","message":"Creating resource","service.version":"1.3.0+6db1914b","service.type":"eck","ecs.version":"1.4.0","kind":"Service","namespace":"monitoring","name":"elastic-es-master-eu-west-1c"}
{"log.level":"info","@timestamp":"2020-12-21T14:19:16.093Z","log.logger":"generic-reconciler","message":"Creating resource","service.version":"1.3.0+6db1914b","service.type":"eck","ecs.version":"1.4.0","kind":"StatefulSet","namespace":"monitoring","name":"elastic-es-master-eu-west-1c"}
```
In the logs I can see that the operator took the changes for adding es data nodes, but I would have expect to also see delete operations no ?
