### ISSUE TITLE
Document custom transport CA certificate

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#4061]
https://github.com/elastic/cloud-on-k8s/pull/4053 introduces a new `certificate` attribute in the transport TLS options section of the Elasticsearch spec:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: certs-test
spec:
  version: 7.10.1
  transport:
    tls:
      certificate:
        secretName: custom-ca
  nodeSets:
  - name: default
    count: 3    
    config:
      node.store.allow_mmap: false
```

We should document this feature.
