### ISSUE TITLE
Error: container has runAsNonRoot and image has non-numeric user, cannot verify user is non-root

### ISSUE THREAD

**Issue by r0bj** [elastic/cloud-on-k8s#4070]
## Bug Report
**What did you do?**

Run ECK 1.3.1 on cluster with PodSecurityPolicy enabled.

**What did you expect to see?**

ECK run without issues.

**What did you see instead? Under which circumstances?**

Containers with apm, kibana, es failed with:
apm:
```
Error: container has runAsNonRoot and image has non-numeric user (apm-server), cannot verify user is non-root
```
kibana:
```
Error: container has runAsNonRoot and image has non-numeric user (kibana), cannot verify user is non-root
```
es:
```
Error: container has runAsNonRoot and image will run as root
```

PSP definition:
```
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: restricted-with-root
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default,runtime/default'
    apparmor.security.beta.kubernetes.io/allowedProfileNames: 'runtime/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'runtime/default'
    apparmor.security.beta.kubernetes.io/defaultProfileName:  'runtime/default'
spec:
  privileged: false
  volumes:
  - 'configMap'
  - 'emptyDir'
  - 'projected'
  - 'secret'
  - 'downwardAPI'
  - 'persistentVolumeClaim'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  readOnlyRootFilesystem: false
```

ECK 1.2.1 works fine with this PSP.

**Environment**

* ECK version: 1.3.1
* Kubernetes information:
	* Cloud: GKE	
```
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.14-gke.1200", GitCommit:"7c407f5cc8632f9af5a2657f220963aa7f1c46e7", GitTreeState:"clean", BuildDate:"2020-12-01T09:20:59Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```
