### ISSUE TITLE
Create a CRD for external users

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#416]
External user in this context means:

1. an Elasticsearch user created by a (human) user of the operator
2. an Elasticsearch user created by another controller (e.g. KibanaElasticsearchAssociation)

```
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: User
metadata:
  name: foo-bar-kibana
  namespace: foo
  labels:
    # option 1: uses a simple k/v label
    elasticsearch.k8s.elastic.co/cluster: <cluster id>
spec:
  user: foo-bar-kibana
  password_hash: ...
  <..roles omitted for brevity..>
```

Take these CRDs into account when reconciling Elasticsearch users in the Elasticsearch controller

Questions:
* how to reconcile conflicting or overlapping role specs aggregated from multiple users?
