### ISSUE TITLE
Introduce  KibanaElasticsearchAssociation

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#417]
Draft CRD

```
apiVersion: k8s.elastic.co/v1alpha1
kind: KibanaElasticsearchAssociation
metadata:
  name: foo-bar
  namespace: elastic
spec:
  elasticsearch:
    name: <name of ElasticsearchCluster resource>
    namespace: foo
  kibana:
    name: <name of Kibana resource>
    namespace: bar
```

- introduce association controller
- remove stack controller
