### ISSUE TITLE
[DOCS] Document how to set Kibana heap space on ECK

### ISSUE THREAD

**Issue by kostasb** [elastic/cloud-on-k8s#4176]
## Request
Document how to modify Kibana's heap size in ECK per https://www.elastic.co/guide/en/kibana/current/production.html#memory

Users should set the env variable NODE_OPTIONS with the desired max-old-space-size value.

Example:

```
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: test-kibana
spec:
  version: 7.10.2
  count: 1
  podTemplate:
    spec:
      containers:
        - name: kibana
          env:
            - name: NODE_OPTIONS
              value: "--max-old-space-size=2048"
```

Ideally there should be such an example in the more examples section here: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-customize-pods.html#k8s_more_examples
