### ISSUE TITLE
[eck-operator]: Auto un/manage on helm release upgrade

### ISSUE THREAD

**Issue by oliverbaehler** [elastic/cloud-on-k8s#4182]
## Proposal

When upgrading the eck-operator helm release it might be useful to have a mechanism to unmanage resources during an upgrade. This is also proposed in the official upgrade documentation for eck ([https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-upgrading-eck.html#k8s-beta-to-ga-rolling-restart](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-upgrading-eck.html#k8s-beta-to-ga-rolling-restart)). This functionality could simplify the upgrade scenario for the eck operator (especially in complex environments). It could make sense to have a `manage-lifecycle`value which provisions two jobs with the operator chart. 

The first job the unmanage resources, once an eck release is upgraded. Done with Helm Chart lifecycle Hooks. After the Upgrade was successful another job is triggered to remanage the resources (reannotate).

Just a quick and dirty proposal:

**pre-upgrade-unamage.yaml**
``` 
{{- if $.Values.manage-lifecycle }}
apiVersion: batch/v1
kind: Job
metadata:
  name: eck-unmanage
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded, hook-failed
spec:
  activeDeadlineSeconds: 600
  template:
    spec:
      serviceAccountName: "elastic-operator"
      containers:
      - name: unmanage
        restartPolicy: Never  
        image: bitnami/kubectl
        env:
          - name: "ANNOTATION"
            value: "eck.k8s.elastic.co/managed=false"
        args: 
          - 'annotate'
          - '--overwrite'
          - 'elastic'
          - '--all'
          - '$ANNOTATION'
{{- end }}
``` 

**post-upgrade-manage.yaml**

``` 
{{- if $.Values.manage-lifecycle }}
apiVersion: batch/v1
kind: Job
metadata:
  name: eck-manage
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded, hook-failed
spec:
  activeDeadlineSeconds: 600
  template:
    spec:
      serviceAccountName: "elastic-operator"
      containers:
      - name: manage
        restartPolicy: Never  
        image: bitnami/kubectl
        env:
          - name: "ANNOTATION"
            value: "eck.k8s.elastic.co/managed=true"
        args: 
          - 'annotate'
          - '--overwrite'
          - 'elastic'
          - '--all'
          - '$ANNOTATION'
{{- end }}
``` 
**Note**:

This is just a quick draft. It does not take into consideration the option to unmanage only certain elastic api resources. Also this would run for every chart release increment, we could probably add logic to only trigger it when the docker image changes or whatever. It's a proposal, i am curious what you think about it :).

**Use case. Why is this important?**

Simplifies ECK Operator Upgrades on Helm Chart basis.
