### ISSUE TITLE
Kibana NODE_OPTS vs NOTE_OPTIONS

### ISSUE THREAD

**Issue by kostasb** [elastic/cloud-on-k8s#4184]
## Potential bug

The code here:
https://github.com/elastic/cloud-on-k8s/blob/master/pkg/license/testdata/stack.yaml#L108
sets NODE_OPTS with `--max-old-space-size`.

The parameter `--max-old-space-size` refers to node.js heap size per [https://www.elastic.co/guide/en/kibana/current/production.html#memory](https://www.elastic.co/guide/en/kibana/current/production.html#memory).
The relevant env variable for this should be NODE_OPTIONS (not NODE_OPTS) - ref. https://nodejs.org/api/cli.html#cli_environment_variables.

```
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: test-kibana-2
spec:
  version: 7.9.0
  count: 1
  podTemplate:
    spec:
      containers:
        - name: kibana
          env:
            - name: NODE_OPTS
              value: "--max-old-space-size=2048"
```

The code here 
https://github.com/elastic/cloud-on-k8s/blob/master/pkg/controller/kibana/config_settings.go#L34
also refers to increasing Kibana maximum memory limit. It is unclear if it is referring to something else (container memory?) or incorretly referring to the node.js NODE_OPTIONS env variable.

**What did you expect to see?**
Clarify which case each of NODE_OPTIONS and NODE_OPTS should cover: if node.js heap memory, then it should be changed to NODE_OPTIONS and ideally documented per https://github.com/elastic/cloud-on-k8s/issues/4176
