### ISSUE TITLE
Unsupported Distribution in Elastic Search 7.11 ECK 1.3.0

### ISSUE THREAD

**Issue by deepaksinghcs14** [elastic/cloud-on-k8s#4234]
Hi,

I am getting unsupported_distribution error in Elastic 7.11.0, 
while earlier we were using Elastic 7.8.1 which was working fine

here's my config
```
#kubectl apply -f elastic/elastic.yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic
spec:
  version: 7.11.0
  nodeSets:
  - name: default-45
    count: 1
    podTemplate:
      spec:
        nodeSelector:
          tool: xyz
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false
    volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 45Gi
          storageClassName: standard-io
```

while if we change version 7.8.1 it works. but now I am not able to downgrade. 

Below are the logs from elastic filesystem
<img width="506" alt="Screenshot 2021-02-11 at 2 36 27 PM" src="https://user-images.githubusercontent.com/38810134/107617799-8a781b80-6c76-11eb-82c3-26b122936c9c.png">

Here's the described logs
![image](https://user-images.githubusercontent.com/38810134/107618014-e0e55a00-6c76-11eb-8975-c1e86f790a94.png)
