### ISSUE TITLE
ECK 1.4 all-in-one, can't start kibana on arm64 host.

### ISSUE THREAD

**Issue by chenyg0911** [elastic/cloud-on-k8s#4278]
test with quickstart es/kibana. 
kubernetes: aws eks, v1.19.6-eks-49a6c0

Amd64 arch: all work.
Arm64 arch: es work. kibana crash loop on init.
```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.11.1
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
```

```yaml
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
spec:
  version: 7.11.1
  count: 1
  elasticsearchRef:
    name: quickstart

```
