### ISSUE TITLE
Missing SYS_CHROOT capability for Elasticsearch on OCP >=4.6 

### ISSUE THREAD

**Issue by thbkrkr** [elastic/cloud-on-k8s#4334]
To increase security, the `NET_RAW` and `SYS_CHROOT` capabilities are no longer available in the default list of CRI-O capabilities and this impacts OpenShift from version `4.6`.

So, if you deploy Elasticsearch on OCP `4.6`, **in the default namespace**, its pods will be in the `CrashLoopBackOff` status because of this error:

```
> k logs test-es-master-0 
chroot: cannot change root directory to '/': Operation not permitted
```

A quick solution to this problem is to add the necessary capacity directly to the container:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: test
spec:
  version: 7.11.1
  nodeSets:
  - name: master
    count: 1
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          securityContext:
            capabilities:
              add: ["SYS_CHROOT"] 
```

Another approach consists to give the namespace the missing capability using a security context.

~I think it's annoying enough to deserve a note in the 'Deploy ECK on OpenShift' [documentation](https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-openshift-deploy-elasticsearch.html)?~

When following the [Deploy ECK on OpenShift documentation](https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-openshift-deploy-the-operator.html) which asks to create a new project `oc new-project elastic`, there is no need to add this capability because new projects get more permissions.

It is visible by looking at the template used to create projects: `oc adm create-bootstrap-project-template -o yaml > template.yaml`.
