### ISSUE TITLE
Shard allocation awareness - not working as documented

### ISSUE THREAD

**Issue by KannappanSomu** [elastic/cloud-on-k8s#4367]
[https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-advanced-node-scheduling.html#k8s-availability-zone-awareness](url)

> **Note that by default ECK creates a k8s_node_name attribute with the name of the Kubernetes node running the Pod, and configures Elasticsearch to use this attribute. This allows Elasticsearch to allocate primary and replica shards on different Kubernetes nodes, even if there are multiple Elasticsearch Pods on the same Kubernetes node.**

the highlighted part is not working as expected ,, so out of 2 elastic data pods, if both pods are scheduled on same k8s node ,  it says unable to allocate shard , as there is already a shard allocated to that k8s_node_name. below is the error message

`there are too many copies of the shard allocated to nodes with attribute [k8s_node_name], there are [2] total configured shard copies for this shard id and [3] total attribute values, expected the allocated shard count per attribute [2] to be less than or equal to the upper bound of the required number of shards per attribute [1]"`

**Comment by KannappanSomu** [comment]
Is there a way to disable this default - shard allocation awareness based on k8s_node_name

**Comment by KannappanSomu** [comment]
We are using eck version 1.3.0

**Comment by charith-elastic** [comment]
The wording in the documentation is a bit confusing, but, I think it is working as expected. 

A Kubernetes node is the physical unit of failure in a cluster. If you have two or more pods scheduled on to the same Kubernetes node and if the node fails or gets taken out for maintenance, then you lose all of those pods at once. If all your replicas are on those pods then your cluster will become unhealthy. This is why the ECK operator sets the shard allocation awareness attribute to Kubernetes node name by default.

If you are aware of the risks and do not mind potential outages or data loss, you can remove the default by explicitly setting `cluster.routing.allocation.awareness.attributes` to the empty string.

```yaml
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: hulk  
spec:
  version: 7.11.2
  nodeSets:
  - name: default
    count: 3
    config:
      cluster.routing.allocation.awareness.attributes: ""
```

**Comment by charith-elastic** [comment]
Closing due to inactivity. Please reopen if there's new information.

**Comment by KannappanSomu** [comment]
Got the purpose of making this default behaviour. May be updating this page with correct words will avaoid confusion . 

[https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-advanced-node-scheduling.html#k8s-availability-zone-awareness](url)

Note that by default ECK creates a k8s_node_name attribute with the name of the Kubernetes node running the Pod, and configures Elasticsearch to use this attribute. This allows Elasticsearch to allocate primary and replica shards on different Kubernetes nodes, even if there are multiple Elasticsearch Pods on the same Kubernetes node.

**Comment by kaykhancheckpoint** [comment]
Right now i am having the same problem:

```
    {
      "node_id" : "-9BqxfpmTlKXxfeQaHTiOw",
      "node_name" : "elasticsearch-prod-es-monitoring-0",
      "transport_address" : "10.0.4.115:9300",
      "node_attributes" : {
        "ml.max_jvm_size" : "2147483648",
        "type" : "monitoring",
        "k8s_node_name" : "ip-10-0-4-141.eu-west-2.compute.internal",
        "xpack.installed" : "true",
        "ml.machine_memory" : "4294967296"
      },
      "node_decision" : "no",
      "weight_ranking" : 3,
      "deciders" : [
        {
          "decider" : "awareness",
          "decision" : "NO",
          "explanation" : "there are [2] copies of this shard and [2] values for attribute [k8s_node_name] ([ip-10-0-4-141.eu-west-2.compute.internal, ip-10-0-4-224.eu-west-2.compute.internal] from nodes in the cluster and no forced awareness) so there may be at most [1] copies of this shard allocated to nodes with each value, but (including this copy) there would be [2] copies allocated to nodes with [node.attr.k8s_node_name: ip-10-0-4-141.eu-west-2.compute.internal]"
        }
      ]
    },
    {
      "node_id" : "mlRJn1MaTTqyceZRKzfo4A",
      "node_name" : "elasticsearch-prod-es-monitoring-1",
      "transport_address" : "10.0.4.91:9300",
      "node_attributes" : {
        "k8s_node_name" : "ip-10-0-4-141.eu-west-2.compute.internal",
        "ml.machine_memory" : "4294967296",
        "xpack.installed" : "true",
        "ml.max_jvm_size" : "2147483648",
        "type" : "monitoring"
      },
      "node_decision" : "no",
      "weight_ranking" : 4,
      "deciders" : [
        {
          "decider" : "same_shard",
          "decision" : "NO",
          "explanation" : "a copy of this shard is already allocated to this node [[.ds-filebeat-8.2.0-2022.05.12-000001][0], node[mlRJn1MaTTqyceZRKzfo4A], [P], s[STARTED], a[id=OqGgkVZxSgKtnSICtndi6A]]"
        },
        {
          "decider" : "awareness",
          "decision" : "NO",
          "explanation" : "there are [2] copies of this shard and [2] values for attribute [k8s_node_name] ([ip-10-0-4-141.eu-west-2.compute.internal, ip-10-0-4-224.eu-west-2.compute.internal] from nodes in the cluster and no forced awareness) so there may be at most [1] copies of this shard allocated to nodes with each value, but (including this copy) there would be [2] copies allocated to nodes with [node.attr.k8s_node_name: ip-10-0-4-141.eu-west-2.compute.internal]"
        }
      ]
    }
```

Folloiwng on from what @charith-elastic said. Im curious then, if i have a elastic nodeset with a count of `2`. How can i assign 1 elastic node to 1 kubernetes node.

```
  - name: monitoring 
    count: 2
    config:
      node.store.allow_mmap: false
      node.attr.type: monitoring 
    podTemplate:
      spec:
        nodeSelector: 
          geeiq/node-type: ops
        initContainers:
        - name: install-plugin
          command:
          - sh
          - -c
          - |
            bin/elasticsearch-plugin install --batch repository-s3
        - name: add-aws-keys
          env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-secret
                key: access-key-id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-secret
                key: access-secret-key
          command:
          - sh
          - -c
          - |
            echo $AWS_ACCESS_KEY_ID | bin/elasticsearch-keystore add --stdin --force s3.client.default.access_key
            echo $AWS_SECRET_ACCESS_KEY | bin/elasticsearch-keystore add --stdin --force s3.client.default.secret_key
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: 4Gi
              cpu: 2
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms2g -Xmx2g"
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 25Gi 
        storageClassName: elasticsearch
```

As you can see i am using a nodeSelector 

```
        nodeSelector: 
          geeiq/node-type: ops
```

I have a group of kubernetes nodes called `ops` this kubernetes nodeset has 2 nodes.

```
 kubectl get nodes                                     NAME                                       STATUS   ROLES    AGE     VERSION
ip-10-0-1-83.eu-west-2.compute.internal    Ready    <none>   7d23h   v1.22.6-eks-7d68063
ip-10-0-2-219.eu-west-2.compute.internal   Ready    <none>   7d21h   v1.22.6-eks-7d68063
ip-10-0-4-141.eu-west-2.compute.internal   Ready    <none>   6d20h   v1.22.6-eks-7d68063 // OPS
ip-10-0-4-224.eu-west-2.compute.internal   Ready    <none>   6d20h   v1.22.6-eks-7d68063 // OPS
``

Right now i can see both elasticnodes are on the same kubernetes node

```
 kubectl get pods --all-namespaces -o wide --field-selector spec.nodeName=ip-10-0-4-141.eu-west-2.compute.internal
NAMESPACE        NAME                                 READY   STATUS    RESTARTS      AGE     IP           NODE                                       NOMINATED NODE   READINESS GATES
elastic-system   elastic-operator-0                   1/1     Running   0             17h     10.0.4.85    ip-10-0-4-141.eu-west-2.compute.internal   <none>           <none>
elastic-system   elasticsearch-prod-es-monitoring-0   1/1     Running   0             16h     10.0.4.115   ip-10-0-4-141.eu-west-2.compute.internal   <none>           <none>
elastic-system   elasticsearch-prod-es-monitoring-1   1/1     Running   0             16h     10.0.4.91    ip-10-0-4-141.eu-west-
```

**Comment by kaykhancheckpoint** [comment]
@KannappanSomu thank it worked (put each monitoring node on a seperate k8s node) however it did something slightly unexpected. 

You see my actual elasticsearch cluster i have 3 nodesets (defualt, data & monitoring). When i applied the change a 3rd `ops` node had to be created. Because 1/2 of the monitoring nodes could not be satisfied.

I believe 1 of my other 2 elastic node sets (default, data) was assigned to 1/2 existing ops node so a 3rd had to be created (because of that newly added podAntiAffinity). 

I wonder if there is anyway to make this afinity be specific to the nodeset? (i don't mind having for example 1 elastic data node and 1 elastic monitoring node on the same k8s node)

```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-prod
  namespace: elastic-system
spec:
  version: 8.2.0
  volumeClaimDeletePolicy: DeleteOnScaledownOnly
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
      node.attr.type: default 
    podTemplate:
      spec:
        nodeSelector: 
          geeiq/node-type: ops
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 250Gi 
        storageClassName: elasticsearch
  - name: monitoring 
    count: 2
    config:
      node.store.allow_mmap: false
      node.attr.type: monitoring 
    podTemplate:
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: geeiq/node-type
                  operator: In
                  values:
                  - ops
          podAntiAffinity:
             requiredDuringSchedulingIgnoredDuringExecution:
             - labelSelector:
                 matchLabels:
                   elasticsearch.k8s.elastic.co/cluster-name: elasticsearch-prod 
               topologyKey: kubernetes.io/hostname
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 25Gi 
        storageClassName: elasticsearch
  - name: data 
    count: 1
    config:
      node.store.allow_mmap: false
      node.attr.type: data 
    podTemplate:
      spec:
        nodeSelector: 
          geeiq/node-type: ops
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 25Gi 
        storageClassName: elasticsearch
```
