### ISSUE TITLE
Isolate the operator from misconfiguration of HTTP service

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#4394]
Related https://github.com/elastic/cloud-on-k8s/issues/3732 and https://github.com/elastic/cloud-on-k8s/issues/2572

Currently it is possible for users to misconfigure the default HTTP service in such a way the ability of the operator to roll out further configuration changes is impeded.

Consider: 
```yaml
...
spec:
  http:
    service:
      spec:
        selector:
          app: coordinating-node
...
  - config:
       node.roles: []
    count: 1
    name: coordinating-node
    podTemplate:
      metadata:
        labels:
          app: client-node

```

There two ways for users to fix this misconfiguration: a) either change the service selector to `client-node` or b) change the labels on the `client-node` nodeSet to `coordinating-node`.  Approach a) would work while b) would not 

Once the user has rolled out the change with the incorrect selector in the service, the operator has only limited ability to roll out further changes because it lost connectivity with Elasticsearch. In such a situation any rolling upgrade of existing nodes is effectively blocked while new nodes can still be added to the cluster. Also any updates to the service would be rolled out. This is because these operations don't require API access to Elasticsearch while a rolling upgrade or a downscale does require API access. 

We could consider isolating the operator from this class of configuration errors by either not relying on the service (talking to Pods directly as we already when we switch form HTTP to HTTPS ) or creating an internal service that users cannot configure that is used by the operator.
