### ISSUE TITLE
APM from operator has wrong elasticsearch output

### ISSUE THREAD

**Issue by process0** [elastic/cloud-on-k8s#4412]
## Bug Report
**What did you do?**

Install operator (ECK 1.5.0) and installed the quickstart manifests for Elasticsearch, Kibana, and APM. 

**What did you expect to see?**

APM outputting to Elasticsearch

**What did you see instead? Under which circumstances?**

APM forwards nothing to elasticsearch.

```
 $ k exec -ti -n elasticsearch apm-server-quickstart-apm-server-5b7b99c79f-f4s6v -- bash
bash-4.2$ apm-server test output
elasticsearch: http://elasticsearch:9200...
  parse url... OK
  connection...
    parse host... OK
    dns lookup... ERROR lookup elasticsearch on 10.43.0.10:53: no such host
```

**Environment**

* ECK version:

	1.5.0

* Kubernetes information:

On prem.

```

 $ k version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"fbf646b339dc52336b55d8ec85c181981b86331a", GitTreeState:"clean", BuildDate:"2020-12-18T12:01:36Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

```yaml
---
apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-server-quickstart
spec:
  version: 7.12.0
  count: 1
  elasticsearchRef:
    name: quickstart
  kibanaRef:
    name: quickstart
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.12.0
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
  http:
    service:
      spec:
        type: LoadBalancer
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
spec:
  version: 7.12.0
  count: 1
  http:
    service:
      spec:
        type: LoadBalancer
  elasticsearchRef:
    name: quickstart
```
