### ISSUE TITLE
E2E OCP cluster is not created 

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#4420]
Looks like it is related to the recent changes we made on the [OCP deployer](https://github.com/elastic/cloud-on-k8s/pull/4387) :

```
02:42:00  Error: clientVersion must not be empty
02:42:00  clientVersion must not be empty
02:42:00  make: *** [Makefile:500: run-deployer] Error 1
02:42:00  Makefile:48: recipe for target 'ci-internal' failed
```

At first glance I would say this is because `clientVersion` is not set for `ocp-ci`:

```yaml
- id: ocp-ci
  operation: create
  clusterName: ci
  provider: ocp
  machineType: n1-standard-8
  serviceAccount: true
  ocp:
    region: europe-west2
    nodeCount: 3
- id: ocp-dev
  operation: create
  clusterName: dev
  clientVersion: 4.7.0
  provider: ocp
  machineType: n1-standard-8
  serviceAccount: true
  ocp:
    region: europe-west1
    nodeCount: 3
```
