### ISSUE TITLE
Can't discover master nodes if the plugin has issues

### ISSUE THREAD

**Issue by maxisam** [elastic/cloud-on-k8s#4425]
## Bug Report
**What did you do?**

install a S3 plugin with the following secret in secureSettings 

 s3.client.Client.access_key: 
 s3.client.Client.secret_key: 

**What did you expect to see?**

Form a cluster correctly

**What did you see instead? Under which circumstances?**

Master nodes keep trying to connect with each other. but fail (correct ip in the array from logs).
**Environment**

* ECK version:
1.5.0

* Kubernetes information:

	* On premise, created by Rancher 

```
$ kubectl version 1.19.8
```

Note:

It seems like it works if I install it without secureSettings  first and add it later.

**Comment by david-kow** [comment]
Thanks for the report. Can you share logs from the operator and the Elasticsearch Pods that you see when the cluster is unable to form?

**Comment by maxisam** [comment]
Too bad, I don't have it now. But it is very easy to reproduce. I tested it couple times. 

Create 3 master nodes with the following config and S3 Plugin before setting the Client endpoint. 

s3.client.Client.access_key:
s3.client.Client.secret_key:

The workaround is Create nodes with S3 and Setup the Client enpoint first and add the config and update the cluster.

I am not 100% sure but it seems like once the cluster get into this state, I can't even fix it by removing the config.  

I bet it stores the config in the keystore and won't get removed by removing them from the yaml config. 


And you guys might wanna update the document about s3 config for Minio. It requires region, which is local for in general, this simple settings cost me 4 hours.

**Comment by david-kow** [comment]
Hi @maxisam, thanks for more details.

I've tried to reproduce the issue by applying the below, but the cluster forms without any issues. Did you have a different setup in mind? Would it be possible to share the Elasticsearch spec you've used? 

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.12.0
  secureSettings:
  - secretName: s3-client-settings
  nodeSets:
  - name: default
    count: 3
    config:
      node.store.allow_mmap: false
    podTemplate:
      spec:
        initContainers:
          - name: install-plugins
            command:
            - sh
            - -c
            - |
              bin/elasticsearch-plugin install --batch repository-s3
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-client-settings
type: Opaque
stringData:
  s3.client.Client.access_key: abc
  s3.client.Client.secret_key: def
```

As for your other comments:

> I am not 100% sure but it seems like once the cluster get into this state, I can't even fix it by removing the config.

That's interesting. Given I can't repro this myself, any ES/operator logs would be useful to investigate further.

> I bet it stores the config in the keystore and won't get removed by removing them from the yaml config.

We don't remove from the keystore explicitly, the operator force recreates it on each Pod restart.

> And you guys might wanna update the document about s3 config for Minio. It requires region, which is local for in general, this simple setting costs me 4 hours.

Ah, apologies for that. Can you share the URL where this information was omitted? I don't think we mention it in the ECK docs.
