### ISSUE TITLE
readiness probe always failed when deploy elastic-search on GKE autopilot mode

### ISSUE THREAD

**Issue by bram-abe** [elastic/cloud-on-k8s#4426]
## Bug Report
**What did you do?**
Deploying elastic-search on GKE with autopilot mode. 
I was set readiness probe variable accroding to elasticsearch guide.
```
podTemplate:
        spec:
          containers:
          - name: elasticsearch
            readinessProbe:
              exec:
                command:
                - bash
                - -c
                - /mnt/elastic-internal/scripts/readiness-probe-script.sh
              failureThreshold: 3
              initialDelaySeconds: 10
              periodSeconds: 12
              successThreshold: 1
              timeoutSeconds: 12
            env:
            - name: READINESS_PROBE_TIMEOUT
              value: "10"
```
**What did you expect to see?**
Form a workload correctly

**What did you see instead? Under which circumstances?**
pod never get green health status. 
got a message: "readiness probe failed " from pod logs over and over again.

**Environment**

* ECK version:
1.5.0

* Kubernetes information:
	* Cloud: GKE Autopilot mode
	* v1.18.16-gke.502

$ kubectl version
```
Client Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.14-dispatcher", GitCommit:"766e62361387c284022a97270f0997d67ae792d0", GitTreeState:"clean", BuildDate:"2020-12-01T16:18:05Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.16-gke.502", GitCommit:"a2a88ab32201dca596d0cdb116bbba3f765ebd36", GitTreeState:"clean", BuildDate:"2021-03-08T22:06:24Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by sebgl** [comment]
@bram-abe could you provide:

* the entire Elasticsearch resource (yml)
* logs from a Pod which fails the readiness probe

Does the readiness probe succeed if you don't specify it yourself but let ECK provide a default for you?

**Comment by bram-abe** [comment]
With default ECK setup still have the same problem.

Is it possible the cause of the problem related to mmap settings? Because
we can change that settings on autopilot mode.

**Comment by bram-abe** [comment]
Finnaly I resolve the problem after set elasticsearch config :
`config:
      index.store.type: niofs
      node.store.allow_mmap: false`
The autopilot mode on GKE does not allowed user to override the default mmap size on linux kernel.

But I got a new problem with enterprise-search. After doing `kubectl apply -f` there is no pod contain enterprise-search container.
Do `kubectl get events` showing some warnings;
1. (combined from similar events): System OOM encountered, victim process: java, pid: 1650105
2. (combined from similar events): Memory cgroup 
out of memory: Killed process 1650105 (java) total-vm:5876148kB, anon-rss:1030964kB, file-rss:25004kB, shmem-rss:0kB, UID:1000 pgtables:2312kB oom_score_adj:-998.

How to solve this problems ?

**Comment by david-kow** [comment]
Hey @bram-abe, I can't seem to reproduce your issue.

After applying the below on GKE Autopilot cluster

```console
kubectl apply -f https://download.elastic.co/downloads/eck/1.5.0/all-in-one.yaml
kubectl apply -f https://raw.githubusercontent.com/elastic/cloud-on-k8s/master/config/samples/enterprisesearch/ent_es.yaml
```

and a bit of wait, both Pods are up and running:


```console
NAME                                    READY   STATUS    RESTARTS   AGE
pod/elasticsearch-sample-es-default-0   1/1     Running   0          9m1s
pod/ent-sample-ent-575d4f9697-lj7hz     1/1     Running   1          13m

NAME                                                              HEALTH   NODES   VERSION   PHASE   AGE
elasticsearch.elasticsearch.k8s.elastic.co/elasticsearch-sample   green    1       7.9.2     Ready   14m

NAME                                                          HEALTH   NODES   VERSION   AGE
enterprisesearch.enterprisesearch.k8s.elastic.co/ent-sample   green    1       7.9.2     14m
```

Can you share what manifest for ES and EnterpriseSearch you applied? Also, could you check events for the Enterprise resource (`kubectl describe ent _your_enterprisesearch_resource_name_`) and its deployment (`kubectl describe deployments.apps _your_enterprisesearch_resource_name_`)?

**Comment by bram-abe** [comment]
this is my ES manifest :
`apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
  annotations:
    linkerd.io/inject: enabled
spec:
  version: 7.12.0
  secureSettings:
    - secretName: gcs-credential
  http:
    tls:
      selfSignedCertificate:
        disabled: false
  updateStrategy:
    changeBudget:
      maxSurge: 3
      maxUnavailable: 1
  podDisruptionBudget:
    spec:
      minAvailable: 2
      selector:
        matchLabels:
          elasticsearch.k8s.elastic.co/cluster-name: quickstart
  nodeSets:
    - name: default-2gi
      count: 2
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 2Gi
            storageClassName: standard-rwo
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: 2Gi
                limits:
                  memory: 4Gi
          automountServiceAccountToken: true`

and below for EnterpriseSearch manifest:

`apiVersion: enterprisesearch.k8s.elastic.co/v1
kind: EnterpriseSearch
metadata:
  name: enterprise-search-quickstart
spec:
  version: 7.12.0
  count: 1
  elasticsearchRef:
    name: quickstart
  http:
    service:
      spec:
        type: LoadBalancer
  podTemplate:
    spec:
      containers:
        - name: enterprisesearch
          resources:
            requests:
              memory: 2Gi
            limits:
              memory: 4Gi
  config:
    ent_search.external_url: 'http://localhost:3002'`

**Comment by bram-abe** [comment]
This is for ES manifest :
```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
  annotations:
    linkerd.io/inject: enabled
spec:
  version: 7.12.0
  secureSettings:
    - secretName: gcs-credential
  http:
    tls:
      selfSignedCertificate:
        disabled: false
  updateStrategy:
    changeBudget:
      maxSurge: 3
      maxUnavailable: 1
  podDisruptionBudget:
    spec:
      minAvailable: 2
      selector:
        matchLabels:
          elasticsearch.k8s.elastic.co/cluster-name: quickstart
  nodeSets:
    - name: default-2gi
      count: 3
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 2Gi
            storageClassName: standard-rwo
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: 2Gi
                limits:
                  memory: 4Gi
          automountServiceAccountToken: true
          initContainers:
            - name: install-plugins
              command:
                - sh
                - -c
                - |
                  bin/elasticsearch-plugin install --batch repository-gcs
            - name: sysctl
              securityContext:
                privileged: true
              command: ["sh", "-c", "sysctl -w vm.max_map_count=262144"]
```

and below for enterprise-search:

```
apiVersion: enterprisesearch.k8s.elastic.co/v1
kind: EnterpriseSearch
metadata:
  name: enterprise-search-quickstart
  annotations:
    linkerd.io/inject: enabled
spec:
  version: 7.12.0
  count: 2
  elasticsearchRef:
    name: quickstart
  http:
    service:
      spec:
        type: LoadBalancer
  podTemplate:
    spec:
      containers:
        - name: enterprisesearch
          resources:
            requests:
              memory: 2Gi
            limits:
              memory: 4Gi
  config:
    ent_search.external_url: "http://localhost:3002"
```
