### ISSUE TITLE
Upgrade to 7.11.x fails with Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden

### ISSUE THREAD

**Issue by raffis** [elastic/cloud-on-k8s#4433]
## Bug Report
**What did you do?**

Tried upgrading from 7.10.x to 7.11.2. With operator version v1.1.x.
This ended in the problem described in #4282 so I upgraded the controller to v1.5.0.

The problem is that the controller is not able to apply the elasticsearch-master sts as an immutable field gets updated.
The problem is I don't know which one, I guess it's `volumeClaimTemplates` because we deployed the cluster initially with the wrong pvc field name in there `elasticsearch-master` instead `elasticsearch-data` (And according to some other issues here we were not the only ones who did that as it was just not clearly documented or prevented).
Update with v1.1 of the controller to previous elasticsearch versions were successfully applied. This is now a blocker with v1.5.0

The elasticsearch specs:
```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: logging
spec:
  version: 7.11.2
  nodeSets:
  - name: masters
    count: 3
    config:
      node.master: true
      node.data: false
      node.ingest: false
      node.ml: false
      xpack.ml.enabled: true
      cluster.remote.connect: false
      xpack.security.authc:
          anonymous:
            username: anonymous
            roles: superuser
            authz_exception: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-master
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
  - name: data
    count: 3
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 2Gi
              cpu: 1
            limits:
              memory: 4Gi
              cpu: 1
          env:
          - name: ES_JAVA_OPTS
            value: -Xms2g -Xmx2g
    config:
      node.master: false
      node.data: true
      node.ingest: true
      node.ml: true
      cluster.remote.connect: false
      xpack.security.authc:
          anonymous:
            username: anonymous
            roles: superuser
            authz_exception: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
```

As this was on the staging environment I removed the statefulset of the masters with cascade=false and waited for it to be reapplied by the controller. However the pvs got removed and the states of the masters was somewhat lost and the cluster offline. In the end I set the data volumes to retain to at least keep them and killled the whole cluster afterwards as it was not able to recover from the master loss.

**What did you expect to see?**

Successful apply of the sts despite the fact that the pvc has the wrong name.
It should just be the same specs as the currently deployed sts. I guess v1.5 of the controller either removes it or tries to add fields which were not around before. I don't even see the statefulset spec which wants to be added so it's impossible to see what the controller tries to update.

**What did you see instead? Under which circumstances?**

```
{"log.level":"error","@timestamp":"2021-04-20T10:24:58.511Z","log.logger":"manager.eck-operator.controller.elasticsearch-controller","message":"Reconciler error","service.version":"1.5.0+8091c0da","service.type":"eck","ecs.version":"1.4.0","name":"elasticsearch","namespace":"logging","error":"reconcile StatefulSet: StatefulSet.apps \"elasticsearch-es-masters\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden","errorCauses":[{"error":"reconcile StatefulSet: StatefulSet.apps \"elasticsearch-es-masters\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden"}],"error.stack_trace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.2/pkg/internal/controller/controller.go:252\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.2/pkg/internal/controller/controller.go:215\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:99"}
```

**Environment**

* ECK version: v1.5.0

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* On premise ?
	* Cloud: GKE / EKS / AKS ?
	* Kubernetes distribution: Openshift / Rancher / PKS ?
	
	for each of them please give us the version you are using
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-19T07:38:38Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.17", GitCommit:"68b4e26caf6ede7af577db4af62fb405b4dd47e6", GitTreeState:"clean", BuildDate:"2021-03-18T00:54:02Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

* Resource definition:
```
if relevant insert the resource definition
```

* Logs:
```
insert operator logs or any relevant message to the issue here
```

**Comment by david-kow** [comment]
Hi @raffis, thanks for the detailed report.

I reproduced your issue and I believe this is an unintended breaking change introduced by https://github.com/elastic/cloud-on-k8s/pull/3806 in ECK `1.4.0`.

### The bug

This PR changed the operator behavior to not add default `elasticsearch-data` if _any_ volume claim template is provided by the user. This means that users with custom templates upgrading across `1.4.x` will hit this issue, because instead of creating stateful set with user templates _and_ `elasticsearch-data` the operator will create stateful set with user templates only.

### Repro

```yaml
# es.yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: logging
spec:
  version: 7.10.0
  nodeSets:
  - name: masters
    count: 3
    config:
      node.store.allow_mmap: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-master
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50
```

```yaml
kubectl apply -f https://download.elastic.co/downloads/eck/1.3.0/all-in-one.yaml
kubectl apply -f es.yaml # from above
# wait until statefulset is created
kubectl apply -f https://download.elastic.co/downloads/eck/1.4.0/all-in-one.yaml
```

The change that ECK `1.4.0` attempts to make is removal of `elasticsearch-data` volume claim and results in:

`{"log.level":"error","@timestamp":"2021-04-23T04:56:15.917Z","log.logger":"controller","message":"Reconciler error","service.version":"1.4.0+4aff0b98","service.type":"eck","ecs.version":"1.4.0","controller":"elasticsearch-controller","name":"elasticsearch","namespace":"logging","error":"reconcile StatefulSet: StatefulSet.apps \"elasticsearch-es-masters\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden","errorCauses":[{"error":"reconcile StatefulSet: StatefulSet.apps \"elasticsearch-es-masters\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden"}],...`

### Workaround 

I'm not yet sure what is the right fix for this, but there is a workaround: rename your node set to any other name. This forces the operator to recreate stateful set resource. You can see the [docs](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-volume-claim-templates.html#k8s_updating_the_volume_claim_settings) for more details.

Note that the above will cause migration of data. Alternatively, you can add the below volume claim template to any node set that defines any template other than `elasticsearch-data`. This will make the statefulset that operator tries to send to the APIServer the same as the one already present there.

```yaml
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
```
