### ISSUE TITLE
Recipe Stack-monitoring fails on Openshift 4.6.16

### ISSUE THREAD

**Issue by MastanaGuru** [elastic/cloud-on-k8s#4450]
ECK operator version 1.5
MetricBeats 7.12.0
Openshift 4.6.16

Trying to install metricsbeats stackmonitoring recipe in openshift 4.16 fails with below error. Installing only metricbeats (no filebeat) as a deployment (not daemonset) and replaced runasuser with priviledged: true.

pods "metricbeat-beat-metricbeat-7cb6b8fb7c-" is forbidden: unable to validate against any security context constraint: [spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used]

How can we use a PVC instead of hostpath ?

**Comment by thbkrkr** [comment]
Hi,

As written in the [recipes/beats/README](https://github.com/elastic/cloud-on-k8s/blob/8870369140d2c14a92cb49f1e375b49d161eb761/config/recipes/beats/README.asciidoc), these manifests are self-contained and work out-of-the-box on any **non-secured** Kubernetes cluster. By default, the OpenShift Container Platform registry is **secured** during cluster installation.

There is a dedicated recipe to show how to deploy Beats on OpenShift: [recipes/beats/openshift_monitoring.yaml](https://github.com/elastic/cloud-on-k8s/blob/8870369140d2c14a92cb49f1e375b49d161eb761/config/recipes/beats/openshift_monitoring.yaml). 

If you still want to deploy [recipes/beats/stack_monitoring.yaml](https://github.com/elastic/cloud-on-k8s/blob/8870369140d2c14a92cb49f1e375b49d161eb761/config/recipes/beats/stack_monitoring.yaml) on OpenShift, you have to move the `securityContext` under the container and add `privileged: true` to it.

```yaml
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: metricbeat
spec:
  type: metricbeat
  version: 7.12.0
  deployment:
    podTemplate:
      spec:
        serviceAccountName: metricbeat
        automountServiceAccountToken: true
        containers:
        - name: metricbeat
          securityContext:
            runAsUser: 0
            privileged: true
```

You also have to grant privileged permissions to Metricbeat as shown in the [ECK documentation](https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-openshift-beats.html#k8s-openshift-beats) and the [Metricbeat documentation](https://www.elastic.co/guide/en/beats/metricbeat/current/running-on-kubernetes.html#_red_hat_openshift_configuration).

```sh
# Grant the metricbeat service account access to the privileged SCC
oc adm policy add-scc-to-user privileged -z metricbeat -n <namespace>
```
