### ISSUE TITLE
Associated resource status is misleading

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#4451]
For non-Elasticsearch resources the status calculated from the underlying deployment can be misleading.  In the following example even if the underlying resource's `Deployment` is failing (`Progressing` condition is `False` with reason `ProgressDeadlineExceeded`) the calculated status for the resource is `green`:

```
% kubectl get ems,deployment,pods
NAME                                               HEALTH   NODES   VERSION   AGE
elasticmapsserver.maps.k8s.elastic.co/quickstart   green    4       7.12.0    18h # should not be green imho

NAME                             READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/quickstart-ems   4/5     3            4           18h

NAME                                  READY   STATUS             RESTARTS   AGE
pod/quickstart-ems-859d7d6d4d-59ppw   1/1     Running            0          22m
pod/quickstart-ems-859d7d6d4d-m7bk7   1/1     Running            0          29m
pod/quickstart-ems-859d7d6d4d-pqpn8   1/1     Running            0          22m
pod/quickstart-ems-859d7d6d4d-rpkxn   1/1     Running            0          22m
pod/quickstart-ems-9cd9dd74f-9lklm    0/1     CrashLoopBackOff   8          17m
pod/quickstart-ems-9cd9dd74f-k7kt6    0/1     CrashLoopBackOff   8          17m
pod/quickstart-ems-9cd9dd74f-rv2m7    0/1     CrashLoopBackOff   8          17m
```

```yaml
status:
  availableReplicas: 4
  conditions:
  - lastTransitionTime: "2021-04-27T06:19:38Z"
    lastUpdateTime: "2021-04-27T06:19:38Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-04-27T06:33:49Z"
    lastUpdateTime: "2021-04-27T06:33:49Z"
    message: ReplicaSet "quickstart-ems-9cd9dd74f" has timed out progressing.
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  observedGeneration: 5
  readyReplicas: 4
  replicas: 7
  unavailableReplicas: 3
  updatedReplicas: 3
```

The reason is that [only the `appsv1.DeploymentAvailable` condition is considered](https://github.com/elastic/cloud-on-k8s/blob/8870369140d2c14a92cb49f1e375b49d161eb761/pkg/controller/common/status.go#L22) to compute the status: 

```golang
// DeploymentStatus returns a DeploymentStatus computed from the given args.
// Unknown fields are inherited from current.
func DeploymentStatus(current commonv1.DeploymentStatus, dep appsv1.Deployment, pods []corev1.Pod, versionLabel string) commonv1.DeploymentStatus {
	status := *current.DeepCopy()
	status.AvailableNodes = dep.Status.AvailableReplicas
	status.Version = LowestVersionFromPods(status.Version, pods, versionLabel)
	status.Health = commonv1.RedHealth
	for _, c := range dep.Status.Conditions {
		if c.Type == appsv1.DeploymentAvailable && c.Status == corev1.ConditionTrue {
			status.Health = commonv1.GreenHealth
		}
	}
	return status
}
```

I think that from a user POV this is misleading, we should either:

* Have an "in between" health colour for those kind of situations. For example `yellow` as soon as the deployment is `Available` but at least one other condition is `False` - I'm not sure I like this one because it reminds the Elasticsearch status while being completely unrelated, but it would have the benefit to alert the user that something is wrong.
* Add a `Phase` as it has already been stated in the following issues:
  * [Status of Kibana deployments is unknown in the Openshift console](https://github.com/elastic/cloud-on-k8s/issues/3584)
  * [Kibana and APM resources should have Phase column](https://github.com/elastic/cloud-on-k8s/issues/2139)
