### ISSUE TITLE
Reduce keystore-updater mounted volumes to minimum required

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#449]
Volumes currently mounted into the keystore-sidecar:

```yaml
   volumeMounts:
    - mountPath: /usr/share/elasticsearch/config
      name: config-volume
    - mountPath: /usr/share/elasticsearch/plugins
      name: plugins-volume
    - mountPath: /usr/share/elasticsearch/bin
      name: bin-volume
    - mountPath: /usr/share/elasticsearch/data
      name: data
    - mountPath: /usr/share/elasticsearch/logs
      name: logs
    - mountPath: /opt/sidecar/bin
      name: sidecar-bin
    - mountPath: /usr/share/elasticsearch/config/node-certs
      name: node-certificates
      readOnly: true
    - mountPath: /mnt/elastic/keystore-secrets
      name: keystore
      readOnly: true
    - mountPath: /mnt/elastic/reload-creds-user
      name: reload-creds-user
      readOnly: true
```

I think the following volume mounts are not required:

```yaml
    - mountPath: /usr/share/elasticsearch/config
      name: config-volume
    - mountPath: /usr/share/elasticsearch/plugins
      name: plugins-volume
    - mountPath: /usr/share/elasticsearch/data
      name: data
    - mountPath: /usr/share/elasticsearch/logs
      name: logs
```

I guess we got them from reusing the same volume mounts as the prepare-fs init container, to simplify the codebase.
