### ISSUE TITLE
topologySpreadConstraints not working

### ISSUE THREAD

**Issue by mortyre** [elastic/cloud-on-k8s#4496]
I tried to install ECK with param topologySpreadConstraints

```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elsearch
  namespace: elsearch
spec:
  version: 7.12.1
  http:
    service:
      spec:
        type: ClusterIP
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
  - name: master
    count: 3
    config:
      node.roles: ["master"]
      node.store.allow_mmap: false
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              elasticsearch.k8s.elastic.co/node-master: "true"
          maxSkew: 1
          topologyKey: failure-domain.beta.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: failure-domain.beta.kubernetes.io/zone
                  operator: In
                  values:
                  - us-east-1a
                  - us-east-1b
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: elasticsearch.k8s.elastic.co/node-master
                  operator: In
                  values:
                  - "true"
              topologyKey: "kubernetes.io/hostname"
```

But my created StatefulSets elsearch-es-master does not have topologySpreadConstraints, only affinity

Can you help me please
