### ISSUE TITLE
"There are no ingest nodes in this cluster" log message in Beat despite monitoring turned off

### ISSUE THREAD

**Issue by SilvM** [elastic/cloud-on-k8s#4497]
## Bug Report
**What did you do?**
Deployed a 3 node Elasticsearch cluster, daemonset Filebeat and Kibana on several different OCP 4.5 clusters.
Elasticsearch nodes are not set as ingest nodes intentionally.
I've configured in Filebeat to stop monitoring.

**What did you expect to see?**
Normal operation like the other pods with just the stats every 30s as usual

**What did you see instead? Under which circumstances?**
Everything is working as expected, but I noticed some filebeat pods are spamming the logs with:

**Environment**
Openshift v4.5, v4.6
Elasticsearch, Filebeat, Kibana v7.11.2

* ECK version:
	1.5

* Kubernetes information:
	* Hosted on AWS EC2
	* Kubernetes distribution: Openshift

* Logs:
```
2021-05-19T10:12:40.250Z	INFO	[publisher_pipeline_output]	pipeline/output.go:143	Connecting to backoff(elasticsearch(https://elasticsearch-logging-es-http.ci-logging-elk.svc:9200))
2021-05-19T10:12:40.250Z	INFO	[publisher]	pipeline/retry.go:213	retryer: send wait signal to consumer
2021-05-19T10:12:40.250Z	INFO	[publisher]	pipeline/retry.go:217	  done
2021-05-19T10:12:40.252Z	INFO	[esclientleg]	eslegclient/connection.go:314	Attempting to connect to Elasticsearch version 7.11.2
2021-05-19T10:12:40.271Z	INFO	[license]	licenser/es_callback.go:51	Elasticsearch license: Basic
2021-05-19T10:12:40.271Z	INFO	[index-management]	idxmgmt/std.go:261	Auto ILM enable success.
2021-05-19T10:12:40.274Z	INFO	[index-management.ilm]	ilm/std.go:139	do not generate ilm policy: exists=true, overwrite=false
2021-05-19T10:12:40.274Z	INFO	[index-management]	idxmgmt/std.go:274	ILM policy successfully loaded.
2021-05-19T10:12:40.274Z	INFO	[index-management]	idxmgmt/std.go:407	Set setup.template.name to '{filebeat-7.11.2 {now/d}-000001}' as ILM is enabled.
2021-05-19T10:12:40.274Z	INFO	[index-management]	idxmgmt/std.go:412	Set setup.template.pattern to 'filebeat-7.11.2-*' as ILM is enabled.
2021-05-19T10:12:40.274Z	INFO	[index-management]	idxmgmt/std.go:446	Set settings.index.lifecycle.rollover_alias in template to {filebeat-7.11.2 {now/d}-000001} as ILM is enabled.
2021-05-19T10:12:40.274Z	INFO	[index-management]	idxmgmt/std.go:450	Set settings.index.lifecycle.name in template to {filebeat {"policy":{"phases":{"hot":{"actions":{"rollover":{"max_age":"30d","max_size":"50gb"}}}}}}} as ILM is enabled.
2021-05-19T10:12:40.282Z	INFO	template/load.go:97	Template filebeat-7.11.2 already exists and will not be overwritten.
2021-05-19T10:12:40.282Z	INFO	[index-management]	idxmgmt/std.go:298	Loaded index template.
2021-05-19T10:12:40.285Z	INFO	[index-management]	idxmgmt/std.go:309	Write alias successfully generated.
2021-05-19T10:12:40.324Z	INFO	[publisher_pipeline_output]	pipeline/output.go:151	Connection to backoff(elasticsearch(https://elasticsearch-logging-es-http.ci-logging-elk.svc:9200)) established
2021-05-19T10:12:40.324Z	INFO	[publisher]	pipeline/retry.go:213	retryer: send wait signal to consumer
2021-05-19T10:12:40.324Z	INFO	[publisher]	pipeline/retry.go:217	  done
2021-05-19T10:12:40.334Z	ERROR	[elasticsearch]	elasticsearch/client.go:224	failed to perform any bulk index operations: 500 Internal Server Error: {"error":{"root_cause":[{"type":"illegal_state_exception","reason":"There are no ingest nodes in this cluster, unable to forward request to an ingest node."}],"type":"illegal_state_exception","reason":"There are no ingest nodes in this cluster, unable to forward request to an ingest node."},"status":500}
```

**Comment by thbkrkr** [comment]
Hi,

Could you expand on how you configured Filebeat to stop monitoring?

What do you mean with "Normal operation like the other pods with just the stats every 30s as usual"?  In particular, what stats are you talking about?

Could you share your Elasticsearch, Kibana and Filebeat YAML manifests?

**Comment by SilvM** [comment]
Hi,

> Could you expand on how you configured Filebeat to stop monitoring?
I used the configuration from the [reference](https://www.elastic.co/guide/en/beats/filebeat/7.11/filebeat-reference-yml.html) :
```
spec:
  config:
    # TODO Did this stop the spamming ingest log?
    monitoring.enabled: false
```
I checked the /etc/beat.yml in the pod and it does show up.

> What do you mean with "Normal operation like the other pods with just the stats every 30s as usual"? In particular, what stats are you talking about?
I meant the default logs that filebeat outputs with stats of last 30s
```
2021-05-19T10:12:38.136Z	INFO	[monitoring]	log/log.go:144	Non-zero metrics in the last 30s	
...
```

Here are my manifests
```
---
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: filebeat-logging
  namespace: {{ .Values.namespace }}
spec:
  type: filebeat
  version: {{ .Values.filebeat.version }}
  elasticsearchRef:
    name: elasticsearch-logging
  config:
    # TODO Did this stop the spamming ingest log?
    monitoring.enabled: false
    # TODO Set to true to log messages in JSON format.
    #logging.json: false
    filebeat.autodiscover.providers:
      - type: kubernetes
        node: ${NODE_NAME}
        hints:
          enabled: true
          default_config:
            type: container
            paths:
              - /var/log/containers/*${data.kubernetes.container.id}.log
    processors:
      - add_observer_metadata:
          geo.name: "prep"
      - dissect:
          when:
            and:
              - equals:
                  kubernetes.labels.app_component: ci-isam-wrp
              - regexp:
                  message: "^\\[.*"
          tokenizer: "[%{request_timestamp}] RQH:%{target_host} USER:%{client_login_name} RQM:%{http_method} RQP:%{rqp} SC:%{response|integer} B:%{bytes|integer}"
          field: "message"
          target_prefix: "rp"
          # Log error and prevent subsequent processors
          ignore_failure: false
          # TODO endpoint_junction extraction
          # TODO rp. prefix for fields
          # TODO integer times
          # TODO parse json logs
      # TODO Timestamp conversion
      - timestamp:
          when:
            has_fields: ['rp.request_timestamp']
          field: rp.request_timestamp
          layouts:
            # Format is 01/02 03:04:05PM '06 -0700
            - "02/Jan/2006:03:04:05.999 -0700"
            - "02/01/2006:03:04:05.999 -0700"
          test:
            - "14/May/2021:09:59:35.313 +0000"
  daemonSet:
    podTemplate:
      spec:
        serviceAccountName: filebeat-logging
        automountServiceAccountToken: true
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true  # Allows to provide richer host metadata
        containers:
          - name: filebeat
            securityContext:
              runAsUser: 0
              # If using Red Hat OpenShift uncomment this:
              privileged: true
            volumeMounts:
              - name: varlogcontainers
                mountPath: /var/log/containers
              - name: varlogpods
                mountPath: /var/log/pods
              - name: varlibdockercontainers
                mountPath: /var/lib/docker/containers
            env:
              - name: NODE_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
            resources:
              requests:
                memory: {{ .Values.filebeat.resources.requests.memory }}
                cpu: {{ .Values.filebeat.resources.requests.cpu }}
              limits:
                memory: {{ .Values.filebeat.resources.limits.memory }}
        volumes:
          - name: varlogcontainers
            hostPath:
              path: /var/log/containers
          - name: varlogpods
            hostPath:
              path: /var/log/pods
          - name: varlibdockercontainers
            hostPath:
              path: /var/lib/docker/containers
```

```
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-logging
  namespace: ci-logging-elk
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}"
spec:
  nodeSets:
    - name: logging
      config:
        node.roles:
          - master
          - data
      podTemplate:
        spec:
          initContainers:
            - name: install-plugins
              command:
                - sh
                - -c
                - |
                  # Download plugin, compare sha512 and put in place for elasticsearch
                  # bundled plugin installer fails due to permissions issue
                  # https://github.com/elastic/cloud-on-k8s/issues/1801
                  set -e -u
                  plugin="repository-s3-7.11.2.zip"
                  pluginrepo="https://artifacts.elastic.co/downloads/elasticsearch-plugins"
                  espath="/usr/share/elasticsearch"
                  pluginpath="$espath/plugins/repository-s3"
                  zippath="$pluginpath/$plugin"

                  mkdir $pluginpath || exit 42
                  curl "$pluginrepo/repository-s3/$plugin" -o "$zippath"
                  shazip=$(sha512sum "$zippath")
                  sharepo=$(curl "$pluginrepo/repository-s3/$plugin.sha512")
                  if [ "$shazip" -ne "$sharepo" ]; then
                    echo "SHA512 doesn't match"
                    exit 43
                  fi
                  unzip "$zippath" -d "$pluginpath"
                  rm -f "$zippath"

                  # Keystore settings
                  $espath/bin/elasticsearch-keystore create
                  # TODO setup secret (?) to add in keystore
                  $espath/bin/elasticsearch-keystore add --stdin s3.client.default.access_key <<< ""
                  $espath/bin/elasticsearch-keystore add --stdin s3.client.default.secret_key <<< ""
                  $espath/bin/elasticsearch-keystore list

          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: {{ .Values.es.resources.requests.memory }}
                  cpu: {{ .Values.es.resources.requests.cpu }}
                limits:
                  # Must put limits on memory for the heap calculation. memory/2=heap
                  memory: {{ .Values.es.resources.limits.memory }}
      count: {{ .Values.es.count }}
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: {{ .Values.es.resources.requests.storage }}
  version: "{{ .Values.es.version }}"
  volumeClaimDeletePolicy: DeleteOnScaledownOnly
```

```
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-logging
  namespace: "{{ .Values.namespace }}"
spec:
  count: {{ .Values.kb.count }}
  elasticsearchRef:
    name: elasticsearch-logging
    namespace: "{{ .Values.namespace }}"
  version: "{{ .Values.kb.version }}"
  podTemplate:
    spec:
      containers:
        - name: kibana
          resources:
            requests:
              memory: {{ .Values.kb.resources.requests.memory }}
              cpu: {{ .Values.kb.resources.requests.cpu }}
            limits:
              memory: {{ .Values.kb.resources.limits.memory }}

```
