### ISSUE TITLE
How to use secureSettings when deploying Beats via ECK?

### ISSUE THREAD

**Issue by ryan-atkins** [elastic/cloud-on-k8s#4524]
## Bug Report
**What did you do?**
Deploy eck operator and Beats resource for running a Heartbeat
Looking to use the secureSettings for the Beat to setup elastic user passwords from k8s secrets since the elasticsearch clusters in this case are running outside ECK.

**What did you expect to see?**
init containers for heartbeat ran similar to operations when deploying Kibana with ECK and using the secureSettings so that the secureSettings SecretSource can be utilized for configuring the heartbeat output.elasticsearch.password value

**What did you see instead? Under which circumstances?**
no init containers run with the heartbeat pod therefore nothing updated in the heartbeat keystore

**Environment**

* ECK version:

	1.5.0

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* Cloud: GKE
	
	for each of them please give us the version you are using
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T21:16:14Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.6-gke.1000", GitCommit:"3ae0998c5052f420a17cb96bacf860ec5d6822a3", GitTreeState:"clean", BuildDate:"2021-04-29T09:17:16Z", GoVersion:"go1.15.10b5", Compiler:"gc", Platform:"linux/amd64"}
```

* Resource definition:
```
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: kibana-monitoring-beat
  namespace: elastic-system
spec:
  type: heartbeat
  version: 7.12.0
  config:
    heartbeat.monitors:
      - schedule: '@every 5s'
        type: http
        urls:
          - 'https://my.kibana.domain'
    output.elasticsearch:
      hosts:
        - 'https://some.cluster.domain:9200'
      protocol: https
      ssl:
        verification_mode: none
      username: metricbeat_publisher
    secureSettings:
      - entries:
          - key: password
            path: output.elasticsearch.password
        secretName: metricbeat-publisher-pw
  deployment:
    podTemplate:
      spec:
        securityContext:
          runAsUser: 0
    replicas: 1
```

* Logs:
```
2021-05-27T01:09:46.651Z	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(elasticsearch(https://some.cluster.domain:9200)): 401 Unauthorized: {"error":{"root_cause":[{"type":"security_exception","reason":"unable to authenticate user [metricbeat_publisher] for REST request [/]","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","Bearer realm=\"security\"","ApiKey"]}}],"type":"security_exception","reason":"unable to authenticate user [metricbeat_publisher] for REST request [/]","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","Bearer realm=\"security\"","ApiKey"]}},"status":401}
```

**Comment by thbkrkr** [comment]
Hi,

I see two problems with your manifest:
- an indentation issue: `secureSettings` must be defined in the `spec` field and not in `config`.
- not the right syntax for referencing secret keys in the Beats config. You need to explicity define `output.elasticsearch.password: ${KEY}`.

See the [documentation](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-beat-configuration.html#k8s-beat-secrets-keystore-for-secure-settings).

Full example:

```yaml
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: abcd
spec:
  type: heartbeat
  version: 7.13.0
  secureSettings:
  - secretName: abcd-es-elastic-user
    entries:
    - key: elastic
      path: ES_PWD
  config:
    heartbeat.monitors:
    - schedule: '@every 5s'
      type: http
      urls:
        - 'https://abcd-kb-http.default.svc:5601'
    output.elasticsearch:
      hosts:
        - 'https://abcd-es-http.default.svc:9200'
      protocol: https
      ssl:
        verification_mode: none
      username: elastic
      password: "${ES_PWD}"
  deployment:
    replicas: 1
    podTemplate:
      spec:
        securityContext:
          runAsUser: 0
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: abcd
spec:
  version: 7.13.0
  nodeSets:
  - name: master
    count: 1 
    config:
      node.store.allow_mmap: false
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: abcd
spec:
  version: 7.13.0
  count: 1
  elasticsearchRef:
    name: abcd
```
