### ISSUE TITLE
can i get elastic-operato 1.6 without check like this?

### ISSUE THREAD

**Issue by MicroftClock** [elastic/cloud-on-k8s#4532]
## Proposal

**Use case. Why is this important?**
es info:
version:7.7.0

nodes:233
The amount of data：700TB

## Bug Report
**What did you do?**
question:
Disk space reaches the upper limit and needs to be expanded，But i meet the problem 
"Secret \"tais-es-transport-certificates\" is invalid: data: Too long: must have at most 1048576 characters

i see the issuses,And I did an experiment in the test environment, I found that upgrading to 1.6 can solve this problem，but when i upgraing elastic-operator to 1.6 version, i meet this problem 

Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**
```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: tais
spec:
  version: 7.7.0
  nodeSets:
  - name: client
    count: 5
    config:
      node.master: false
      node.data: false
      node.ingest: true
      discovery.zen.minimum_master_nodes: 2
      cluster.routing.allocation.same_shard.host: true
      node.max_local_storage_nodes: 1
      cluster.routing.allocation.balance.index: "0.25f"
      cluster.routing.allocation.balance.shard: "0.25f"
      cluster.routing.allocation.node_concurrent_recoveries: "1"
      cluster.routing.allocation.node_initial_primaries_recoveries: "2"
      cluster.routing.allocation.cluster_concurrent_rebalance: "1"
      cluster.routing.allocation.disk.watermark.high: "90%"
      cluster.routing.allocation.disk.watermark.low: "89%"
      cluster.publish.info_timeout: "40s"
      cluster.publish.timeout: "120s"
      discovery.zen.fd.ping_interval: "10s"
      discovery.zen.fd.ping_timeout: "60s"
    podTemplate:
      spec:
        initContainers:
        - name: install-plugins
          command: ['sh', '-c', 'bin/elasticsearch-plugin install --batch repository-hdfs;bin/elasticsearch-plugin install file:/usr/share/elasticsearch/elasticsearch-analysis-urlaware-tokenizer-7.7.0.zip']
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms31g -Xmx31g -XX:ActiveProcessorCount=40
          resources:
            requests:
              memory: 60Gi
          volumeMounts:
            - name: config-toml-es-log4j2
              mountPath: /usr/share/elasticsearch/config/log4j2.properties
              subPath: log4j2.properties
            - name: config-toml-es-jvm
              mountPath: /usr/share/elasticsearch/config/jvm.options
              subPath: jvm.options
            - name: elasticsearch-logs
              mountPath: /usr/share/elasticsearch/logs
            - name: zip-es-analysis-plugin
              mountPath: /usr/share/elasticsearch/elasticsearch-analysis-urlaware-tokenizer-7.7.0.zip
              subPath: elasticsearch-analysis-urlaware-tokenizer-7.7.0.zip
        volumes:
          - name: config-toml-es-log4j2
            configMap:
              name: es-log4j2
              items:
              - key: log4j2.properties
                path: log4j2.properties
          - name: config-toml-es-jvm
            configMap:
              name: es-jvm
              items:
              - key: jvm.options
                path: jvm.options
          - name: zip-es-analysis-plugin
            configMap:
              name: es-analysis-plugin
              items:
              - key: elasticsearch-analysis-urlaware-tokenizer-7.7.0.zip
                path: elasticsearch-analysis-urlaware-tokenizer-7.7.0.zip
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-logs
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "local-volume"
        resources:
          requests:
            storage: 500Gi
```
* ECK version:

	1.1.2->1.6.0

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* On premise ?
	* Cloud: GKE / EKS / AKS ?
	* Kubernetes distribution: Openshift / Rancher / PKS ?
	
	for each of them please give us the version you are using
```
$ kubectl version
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:23:26Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

* Resource definition:
```
if relevant insert the resource definition
```

* Logs:
"Secret \"tais-es-transport-certificates\" is invalid: data: Too long: must have at most 1048576 characters
Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
insert operator logs or any relevant message to the issue here
```

**Comment by MicroftClock** [comment]
The amount of data in the cluster is too large, and our own plug-in is installed, it is too expensive to restore the configuration file to its original state, so can there be other ways to solve the upgrade problem or "1048576 characters"?

**Comment by pebrc** [comment]
In ECK version 1.4.0 we changed the defaulting behaviour when it comes to the persistent volumes. See https://github.com/elastic/cloud-on-k8s/pull/3806

What that means for you is that in 1.1.2 you had a default volume defined called `elasticsearch-data` ([docs](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-volume-claim-templates.html)) mounted to `/usr/share/elasticsearch/data` when you upgraded to 1.6.0 you no longer got the default volume because you are defining you own persistent volume 

```yaml
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-logs
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "local-volume"
        resources:
          requests:
            storage: 500Gi
```

If you update your manifest to also include the `elasticsearch-data` volume, that error about `updates to statefulset`  should go away.  You should be able to see the exact spec in your existing Pods but it is in all likelihood:

```yaml
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
```

As a side note: I am a little confused by your setup as you are giving 500Gi to the Elasticsearch logs per node and but are running with the default 1Gi persistent volume for the actual data. I am also wondering how your arrived at the 700Gi data set size given that your 233 node cluster with 1Gi default volumes should only have around 233Gi of storage capacity.

**Comment by MicroftClock** [comment]
> 在ECK版本1.4.0中，我们更改了有关持久卷的默认行为。请参阅[＃3806，](https://github.com/elastic/cloud-on-k8s/pull/3806)该错误是Kubernetes StatefulSet控制器的限制，它仅允许在现有StatefulSet的某些字段上进行更新。
> 
> 这对您而言意味着在1.1.2中，当您升级到1.6.0时已安装了一个名为`elasticsearch-data`（[docs](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-volume-claim-templates.html)）`/usr/share/elasticsearch/data`的默认卷，由于您正在定义自己的持久卷声明模板，因此不再拥有该默认卷：
> 
> ```yaml
>     volumeClaimTemplates：
>     -元数据：
>         名称：elasticsearch -logs
>       规范：
>          accessModes：[“ ReadWriteOnce”] 
>         storageClassName：“ local-volume ”
>         资源：
>           请求：
>             存储量：500Gi
> ```
> 
> 如果您将清单更新为也包括该`elasticsearch-data`卷，则该错误`updates to statefulset` 将消失。您应该能够在现有的Pod中看到确切的规格，但是很可能是这样的：
> 
> ```yaml
>     volumeClaimTemplates：
>     -元数据：
>         名称：elasticsearch -data 
>       spec：
>          accessModes：[“ ReadWriteOnce”]
>         资源：
>           请求：
>             存储：1Gi
> ```
> 
> 附带说明：我对您的设置有些困惑，因为您要为每个节点的Elasticsearch日志提供500Gi的资源，但使用默认的1Gi永久卷来运行实际数据。我还想知道您是如何得出700Gi数据集大小的，因为具有1Gi默认卷的233节点群集应该只有大约233Gi的存储容量。

this is my pv-pvc
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-data-tais-es-data-cold-a-1
  namespace: es-tais
  labels:
    k8s-pvname: elasticsearch-data-tais-es-data-cold-a-1
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-volume
  local:
    path: /data1/elasticsearch/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - 10.191.3.10
and in this machine ,es can use 8T disk
![image](https://user-images.githubusercontent.com/30529481/119939225-1ad93280-bfc0-11eb-91ad-acdc1fb6ac41.png)

**Comment by MicroftClock** [comment]
My cluster is divided into hot and cold data，Each hot loads more than 2T of data，and cold 8T.Hope it can solve your confusion

**Comment by MicroftClock** [comment]
> In ECK version 1.4.0 we changed the defaulting behaviour when it comes to the persistent volumes. See #3806 The error is a limitation of the Kubernetes StatefulSet controller that only allows update on certain fields of an existing StatefulSet.
> 
> What that means for you is that in 1.1.2 you had a default volume defined called `elasticsearch-data` ([docs](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-volume-claim-templates.html)) mounted to `/usr/share/elasticsearch/data` when you upgraded to 1.6.0 you no longer got the default volume because you are defining you own persistent volume claim template:
> 
> ```yaml
>     volumeClaimTemplates:
>     - metadata:
>         name: elasticsearch-logs
>       spec:
>         accessModes: [ "ReadWriteOnce" ]
>         storageClassName: "local-volume"
>         resources:
>           requests:
>             storage: 500Gi
> ```
> 
> If you update your manifest to also include the `elasticsearch-data` volume, that error about `updates to statefulset` should go away. You should be able to see the exact spec in your existing Pods but it is in all likelihood:
> 
> ```yaml
>     volumeClaimTemplates:
>     - metadata:
>         name: elasticsearch-data
>       spec:
>         accessModes: [ "ReadWriteOnce" ]
>         resources:
>           requests:
>             storage: 1Gi
> ```
> 
> As a side note: I am a little confused by your setup as you are giving 500Gi to the Elasticsearch logs per node and but are running with the default 1Gi persistent volume for the actual data. I am also wondering how your arrived at the 700Gi data set size given that your 233 node cluster with 1Gi default volumes should only have around 233Gi of storage capacity.

can i get 1.6 version without check #3806

**Comment by MicroftClock** [comment]
![截屏2021-05-28 下午4 02 31](https://user-images.githubusercontent.com/30529481/119951045-1d428900-bfce-11eb-8f4c-92d9bffacb94.png)
**"Secret "tais-es-transport-certificates" is invalid: data: Too long: must have at most 1048576 characters**

**Comment by sebgl** [comment]
> "Secret "tais-es-transport-certificates" is invalid: data: Too long: must have at most 1048576 characters

This is solved in ECK 1.4.0 (https://github.com/elastic/cloud-on-k8s/pull/3828).

 > can i get 1.6 version without check #3806

I don't think so, this check does matter for many users.

I think you may have misunderstood @pebrc's comments above.
When using version 1.6.0, you need to update your manifest with the following volume claim templates:

```
  volumeClaimTemplates:
  # the additional elasticsearch-logs volume you added
  - metadata:
        name: elasticsearch-logs
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "local-volume"
        resources:
          requests:
            storage: 500Gi
    # the elasticsearch-data volume that is was added automatically in old versions of ECK
    # but not any more
  - metadata:
      name: elasticsearch-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
```

This should likely remove the `Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden` error.

**Comment by MicroftClock** [comment]
> > "Secret "tais-es-transport-certificates" is invalid: data: Too long: must have at most 1048576 characters
> 
> This is solved in ECK 1.4.0 (#3828).
> 
> > can i get 1.6 version without check #3806
> 
> I don't think so, this check does matter for many users.
> 
> I think you may have misunderstood @pebrc's comments above.
> When using version 1.6.0, you need to update your manifest with the following volume claim templates:
> 
> ```
>   volumeClaimTemplates:
>   # the additional elasticsearch-logs volume you added
>   - metadata:
>         name: elasticsearch-logs
>       spec:
>         accessModes: [ "ReadWriteOnce" ]
>         storageClassName: "local-volume"
>         resources:
>           requests:
>             storage: 500Gi
>   # the elasticsearch-data volume that was added automatically in old versions of ECK
>   # but not any more since https://github.com/elastic/cloud-on-k8s/pull/3806
>   - metadata:
>       name: elasticsearch-data
>     spec:
>       accessModes: [ "ReadWriteOnce" ]
>       resources:
>         requests:
>           storage: 1Gi
> ```
> 
> This should likely remove the `Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden` error.

hello,According to what you said, I removed this configuration in the test environment and can be upgraded normally, but in this way my log cannot be persisted. Although I have declared its PVC, it does not seem to take effect, and the persistence of data is normal

**Comment by sebgl** [comment]
@MicroftClock can you post your entire Elasticsearch yml resource? I suspect something may be off in the volume specification.

**Comment by sebgl** [comment]
@MicroftClock I don't see any `volumeClaimTemplates` section in your manifest.
I was expecting to see what I described in https://github.com/elastic/cloud-on-k8s/issues/4532#issuecomment-851266057:

```
 volumeClaimTemplates:
  # the additional elasticsearch-logs volume you added
  - metadata:
        name: elasticsearch-logs
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "local-volume"
        resources:
          requests:
            storage: 500Gi
  # the elasticsearch-data volume that was added automatically in old versions of ECK
  # but not any more since https://github.com/elastic/cloud-on-k8s/pull/3806
  - metadata:
      name: elasticsearch-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
```

**Comment by MicroftClock** [comment]
> @MicroftClock I don't see any `volumeClaimTemplates` section in your manifest.
> I was expecting to see what I described in [#4532 (comment)](https://github.com/elastic/cloud-on-k8s/issues/4532#issuecomment-851266057):
> 
> ```
>  volumeClaimTemplates:
>   # the additional elasticsearch-logs volume you added
>   - metadata:
>        name: elasticsearch-logs
>      spec:
>        accessModes: [ "ReadWriteOnce" ]
>        storageClassName: "local-volume"
>        resources:
>          requests:
>            storage: 500Gi
>   # the elasticsearch-data volume that was added automatically in old versions of ECK
>   # but not any more since https://github.com/elastic/cloud-on-k8s/pull/3806
>   - metadata:
>       name: elasticsearch-data
>     spec:
>       accessModes: [ "ReadWriteOnce" ]
>       resources:
>         requests:
>           storage: 1Gi
> ```

Because I upgraded to elastic-operato 1.6 version, I deleted them. In the old version I used the following configuration
```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: danxias
spec:
  version: 7.10.2
  nodeSets:
  - name: node
    count: 3
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.max_local_storage_nodes: 2
      discovery.zen.minimum_master_nodes: 2
      cluster.routing.allocation.balance.index: "0.25f"
      cluster.routing.allocation.balance.shard: "0.25f"
      cluster.routing.allocation.node_concurrent_recoveries: "1"
      cluster.routing.allocation.node_initial_primaries_recoveries: "2"
      cluster.routing.allocation.cluster_concurrent_rebalance: "1"
      cluster.routing.allocation.disk.watermark.high: "90%"
      cluster.routing.allocation.disk.watermark.low: "89%"
      cluster.publish.info_timeout: "40s"
      cluster.publish.timeout: "120s"
      discovery.zen.fd.ping_interval: "10s"
      discovery.zen.fd.ping_timeout: "60s"
    podTemplate:
      spec:
        initContainers:
        - name: install-plugins
          command: ['sh', '-c', 'bin/elasticsearch-plugin install --batch repository-hdfs;bin/elasticsearch-plugin install file:/usr/share/elasticsearch/elasticsearch-analysis-urlaware-tokenizer-7.7.0.zip']
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms2g -Xmx2g
          resources:
            requests:
              memory: 4Gi
              cpu: 2
          volumeMounts:
            - name: config-toml-es-log4j2
              mountPath: /usr/share/elasticsearch/config/log4j2.properties
              subPath: log4j2.properties
            - name: zip-es-analysis-plugin
              mountPath: /usr/share/elasticsearch/elasticsearch-analysis-urlaware-tokenizer-7.7.0.zip
              subPath: elasticsearch-analysis-urlaware-tokenizer-7.7.0.zip
            - name: elasticsearch-logs
              mountPath: /usr/share/elasticsearch/logs
            - name: elasticsearch-data
              mountPath: /usr/share/elasticsearch/data
        volumes:
          - name: config-toml-es-log4j2
            configMap:
              name: es-log4j2
              items:
              - key: log4j2.properties
                path: log4j2.properties
          - name: zip-es-analysis-plugin
            configMap:
              name: es-analysis-plugin
              items:
              - key: elasticsearch-analysis-urlaware-tokenizer-7.7.0.zip
                path: elasticsearch-analysis-urlaware-tokenizer-7.7.0.zip
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-logs
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "local-volume"
        resources:
          requests:
            storage: 1Gi
```
