### ISSUE TITLE
Allow users to suspend the Elasticsearch process for debugging purposes

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#4546]
Currently it is not possible to run debug or run disaster recovery operations like the [elasticsearch-node](https://www.elastic.co/guide/en/elasticsearch/reference/current/node-tool.html) on clusters managed by ECK. 

We should create a mechanism by which users can specify to suspend the Elasticsearch process to then allow users/admins to exec into the the container to run the necessary operations. 

A possible implementation approach: 

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
  annotations: 
        eck.elastic.co/suspend: "pod-1,pod-2'
spec:
  version: 7.13.0
```

This could be implemented by mounting a ConfigMap into the  init container with a list of Pods to be suspended and the init container would simply not terminate as long as the Pods name is in that file or file exists with the Pods name.
