### ISSUE TITLE
*Feature Request* Accept annotations in http.service.spec to create loadbalancer service with internal IP

### ISSUE THREAD

**Issue by justin-silveri** [elastic/cloud-on-k8s#4557]
## Proposal

Allow the use of annotations in http.service.spec. Currently, the only way to allow access to elasticsearch from outside the cluster is to use a load balancer with an external IP. AKS/EKS/GKE allow annotations to configure the load balancer service to use an internal IP.

*Example for AKS*
``` http:
    service:
      spec:
        type: LoadBalancer
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
        loadBalancerIP: x.x.x.x
```

**Use case. Why is this important?**

Expose the elasticsearch service outside of the K8s cluster without making it publicly accessible.

**Comment by barkbay** [comment]
`annotations` must be placed under the `metadata` parent field:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: es-sample
spec:
  version: 7.13.1
  nodeSets:
  - name: default
    config:
      node.store.allow_mmap: false
    count: 1
  http:
    service:
      metadata:
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      spec:
        type: LoadBalancer
```

```
% k get svc es-sample-es-http --output=jsonpath={.metadata.annotations}
{"cloud.google.com/neg":"{\"ingress\":true}","service.beta.kubernetes.io/azure-load-balancer-internal":"true"}%
```

Please reopen if I needed.
