### ISSUE TITLE
[Beat] Exiting: error loading config file: open /etc/beat.yml: permission denied

### ISSUE THREAD

**Issue by mtparet** [elastic/cloud-on-k8s#4562]
## Bug Report
**What did you do?**
Deploy a filebeat using Beat CRD

**What did you expect to see?**
No error or container crash

**What did you see instead? Under which circumstances?**
"Exiting: error loading config file: open /etc/beat.yml: permission denied"

**Environment**

* ECK version:

	1.6.0

* Kubernetes information:
- EKS , Kubernetes 1.20
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-eks-6b7464", GitCommit:"6b746440c04cb81db4426842b4ae65c3f7035e53", GitTreeState:"clean", BuildDate:"2021-03-19T19:33:03Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

```

* Resource definition:
```
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: filebeatcloudtrail
spec:
  type: filebeat
  version: 7.13.1
  elasticsearchRef:
    name: elasticsearch
  kibanaRef:
    name: elasticsearch
  config:
    filebeat.modules:
      - module: aws
        cloudtrail:
          enabled: true
          var.queue_url: https://sqs.eu-west-3.amazonaws.com/XXXX/XXXX
          #var.shared_credential_file: /etc/filebeat/aws_credentials
          #var.credential_profile_name: fb-aws
          var.access_key_id: XXXX
          var.secret_access_key: XXX
          #var.session_token: session_token
          #var.visibility_timeout: 300s
          #var.api_timeout: 120s
          #var.endpoint: amazonaws.com
          #var.role_arn: arn:aws:iam::123456789012:role/test-mb
      # autodiscover:
  deployment: {}
```

* Logs:
```
"Exiting: error loading config file: open /etc/beat.yml: permission denied"
```

**Comment by mtparet** [comment]
I don't know if it is expected but the "defaultMode" of the config is "384", I fix by overriding the mount of the config beat.
```
  deployment:
    podTemplate:
      spec:
        volumes:
        - name: config
          secret:
            defaultMode: 420
            optional: false
            secretName: filebeatcloudtrail-beat-filebeat-config
```

But now, I am getting another error:
```
2021-06-09T14:46:20.661Z	INFO	instance/beat.go:665	Home path: [/usr/share/filebeat] Config path: [/usr/share/filebeat] Data path: [/usr/share/filebeat/data] Logs path: [/usr/share/filebeat/logs]
2021-06-09T14:46:20.661Z	INFO	instance/beat.go:391	filebeat stopped.
2021-06-09T14:46:20.661Z	ERROR	instance/beat.go:989	Exiting: Failed to create Beat meta file: open /usr/share/filebeat/data/meta.json.new: permission denied
Exiting: Failed to create Beat meta file: open /usr/share/filebeat/data/meta.json.new: permission denied

```

**Comment by barkbay** [comment]
Hi @mtparet,

I think you're right, the default mode for the configuration file (currently `0600` or `-rw-------`) should be a bit more permissive. The current mode prevents the default user (`1000`) to read it. I'll raise a PR to fix it.

Regarding the meta file I'm not sure there is a good workaround if you do not want to run the container with an other user than `root` (which, I agree, can make sense in some situations). You can still use an empty directory instead:

```yaml
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: filebeatcloudtrail
spec:
  type: filebeat
  version: 7.13.1
  elasticsearchRef:
    name: elasticsearch
  kibanaRef:
    name: kibana
  config:
    logging.level: debug
    filebeat.modules:
      - module: aws
        cloudtrail:
          enabled: true
          var.queue_url: https://sqs.eu-west-3.amazonaws.com/XXXX/XXXX
          #var.shared_credential_file: /etc/filebeat/aws_credentials
          #var.credential_profile_name: fb-aws
          var.access_key_id: XXXX
          var.secret_access_key: XXX
          #var.session_token: session_token
          #var.visibility_timeout: 300s
          #var.api_timeout: 120s
          #var.endpoint: amazonaws.com
          #var.role_arn: arn:aws:iam::123456789012:role/test-mb
      # autodiscover:
  deployment:
    podTemplate:
      spec:
        volumes:
          - name: config
            secret:
              defaultMode: 420
              optional: false
              secretName: filebeatcloudtrail-beat-filebeat-config
          - emptyDir: { }
            name: beat-data
```
