### ISSUE TITLE
Feature request: Ability to annotate PVC through the ElasticSearch manifest

### ISSUE THREAD

**Issue by mapdegree** [elastic/cloud-on-k8s#4570]
## Proposal
In order to tag EBS volumes / Azure disks for ECK managed clusters, we would need to introduce annotations on the PVC object on Kubernetes. This should really come from the ElasticSearch manifest (yaml) instead of us adding annotation outside the manifest.

**Use case. Why is this important?**
- Cost monitoring, management and recovery of storage for ElasticSearch volumes

**Comment by barkbay** [comment]
Hi,

You can already add annotations thought the `volumeClaimTemplates` :

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
spec:
  version: 7.13.1
  nodeSets:
  - name: default
    config:
      node.roles: ["master", "data", "ingest"]
      node.store.allow_mmap: false
    count: 1
    volumeClaimTemplates:
    - metadata:
        annotations:
          foo: bar
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
```

```
> k get pvc elasticsearch-data-elasticsearch-sample-es-default-0 --output=jsonpath={.metadata.annotations.foo}
bar%
```

Is it what you are looking for ?
