### ISSUE TITLE
Simplify multi availability zones setup

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#4609]
As of today the right way to setup multi-AZ Elasticsearch clusters is to create one NodeSet per zone, with the right Kubernetes affinity settings, and the right Elasticsearch configuration bits:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.13.2
  nodeSets:
  - name: zone-a
    count: 1
    config:
      node.attr.zone: europe-west3-a
      cluster.routing.allocation.awareness.attributes: k8s_node_name,zone
    podTemplate:
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: failure-domain.beta.kubernetes.io/zone
                  operator: In
                  values:
                  - europe-west3-a
  - name: zone-b
    count: 1
    config:
      node.attr.zone: europe-west3-b
      cluster.routing.allocation.awareness.attributes: k8s_node_name,zone
    podTemplate:
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: failure-domain.beta.kubernetes.io/zone
                  operator: In
                  values:
                  - europe-west3-b
```

On one hand this is very explicit, gives a lot of control to the user, and is entirely transparent to the operator code which does not need to be aware of availability zones at all.

On the other hand it makes the Elasticsearch resource specification quite cumbersome. Even more if we assume any production-grade cluster must have this kind of setup.

We could simplify this setup by delegating availability zone management to the operator, so users just provide the number of zones they want per NodeSet.

---

**Design ideas**

I see 2 main paths to explore.

1. Rely on Pod topology spread constraints

We could let the user configure Pod topology spread constraints if they want to, so the Kubernetes scheduler has full control over the Pod <-> zone mapping and spreads Pods around on its own.
However the zone into which a Pod is scheduled [isn't easily available from within the Pod itself](https://github.com/kubernetes/kubernetes/issues/40610), making it quite hard to configure Elasticsearch for zone awareness. As of today, this would likely require an init container to grab the node labels and edit the `elasticsearch.yml` configuration.
I'm also afraid this may not play well with [grown-and-shrink -like update strategies](https://github.com/elastic/cloud-on-k8s/issues/4549). If we create the replacing Pod before removing the existing one, it could be hard to ensure they are both scheduled into the same availability zone.

2. Make the operator responsible for managing zones

We could extend the Elasticsearch CRD with optional zone management settings:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.13.2
  nodeSets:
  - name: my-nodes
    count: 1
    availabilityZones:
      count: 3  # effectively means we get 3*1=3 nodes
      topologyKey: zone  # label key set on the nodes to distinguish zones. Could default to "topology.kubernetes.io/zone" if not provided?
      allowedZones: # TBD - allows restricting to a subset of all available zones so users could for example remove an entire zone
      - us-east1a
      - us-east1b
      - us-east1c
```

The impact on the operator is quite important:
- it needs to has RBAC access to get k8s Nodes resources (may not be a big deal, especially if read-only?)
- it needs to manage several StatefulSets per NodeSet. We can't rely on the direct nodeSet name -> statefulSet name association anymore, and likely require a suffix instead (e.g. `my-nodes-us-east1a`). For each managed StatefulSet, the operator would set the right node affinity rule in the Pod spec, and setup the Elasticsearch configuration accordingly.
