### ISSUE TITLE
[APM-Server Deployment] APM-Server User Deployed with missing permissions/role

### ISSUE THREAD

**Issue by BenB196** [elastic/cloud-on-k8s#4615]
## Bug Report
**What did you do?**
Deploy APM server via ECK and attempt to generate API Key
**What did you expect to see?**
I expected an API key to be successfully generated
**What did you see instead? Under which circumstances?**
Got error stating the user is missing permissions
**Environment**

* ECK version:

	v1.6.0

* Kubernetes information:

	* On premise: yes
	* Kubernetes distribution: Openshift / Rancher / PKS: Rancher RKE2, v1.20.5+rke2r1 
	
```
$ kubectl version
```

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5+rke2r1", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-04-02T03:22:00Z", GoVersion:"go1.15.8b5", Compiler:"gc", Platform:"linux/amd64"}
```

Resource definition:
```yaml
---
apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-prod
  namespace: apm-prod
spec:
  version: 7.13.2
  count: 1
  elasticsearchRef:
    name: es-prod
    namespace: elastic-prod
  kibanaRef:
    name: kibana-prod
    namespace: kibana-prod
  http:
    tls:
      certificate:
        secretName: apm-cert
  config:
    apm-server:
      auth:
        api_key:
          enabled: true
          limit: 100
      capture_personal_data: true # TODO check if we want this enabled
      # TODO RUM?
      kibana:
        enabled: true
        ssl.enabled: true
        ssl.verification_mode: certificate
        ssl.certificate_authorities: ["/usr/share/apm-server/certs/<snipped>"]
    output:
      elasticsearch:
        ssl.enabled: true
        ssl.certificate_authorities: ["/usr/share/apm-server/certs/<snipped>"]
        ssl.verification_mode: certificate
    http:
      enabled: true
      host: 0.0.0.0
      port: 5067
    monitoring:
      enabled: false
      cluster_uuid: "<snipped>"
  podTemplate:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        config.linkerd.io/proxy-cpu-limit: "2"
        co.elastic.metrics/raw: '[{"enabled":true,"module":"beat","hosts":["http://${data.host}:5067"],"metricsets":["stats","state"],"period":"10s","timeout":"3s","xpack":{"enabled":true}}]'
    spec:
      automountServiceAccountToken: true
      containers:
        - name: apm-server
          resources:
            limits:
              memory: 2Gi
              cpu: 2
          volumeMounts:
            - name: <snipped>
              mountPath: /usr/share/apm-server/certs
      volumes:
        - name: <snipped>
          secret:
            secretName: <snipped>
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    elasticsearch.k8s.elastic.co/cluster-name: es-prod
                topologyKey: kubernetes.io/hostname
```

When attempting to generate an API key via the command (executed inside the APM pod):

```
apm-server -c config/config-secret/apm-server.yml apikey create --ingest --agent-config --name go-app
```

The following error is gotten:

```
apm-prod-apm-prod-apm-user is missing the following requested privilege(s): event:write, config_agent:read.

You might try with the superuser, or add the APM application privileges to the role of the authenticated user, eg.:
PUT /_security/role/my_role {
        ...
        "applications": [{
          "application": "apm",
          "privileges": ["sourcemap:write", "event:write", "config_agent:read"],
          "resources": ["*"]
        }],
        ...
}
```

When I look at the APM user created on the Elasticsearch deployment in Kubernetes, I see the following roles assigned:

```
eck_apm_user_role_v75,ingest_admin,apm_system
```
None of these roles provide the above needed permissions.

Discussion thread: https://discuss.elastic.co/t/apm-apikey-failing-with-unauthorized-wrong-permissions-documented/277663
