### ISSUE TITLE
Reduce number of labels added to Pods managed by ECK

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#4617]
We are currently adding around 20 labels to each Pod. 

```yaml
# identity labels to select all Elasticsearch pods belonging to a certain cluster
common.k8s.elastic.co/type: elasticsearch
elasticsearch.k8s.elastic.co/cluster-name: quickstart

# configuration hashes to manage the Pod lifecycle on changes
elasticsearch.k8s.elastic.co/config-hash: "2979869328"
elasticsearch.k8s.elastic.co/secure-settings-hash: a94ef9597b096fdbe2d3a47db79f2889bc724340879ade22ac31aace

# internal labels used by the orchestration logic 
elasticsearch.k8s.elastic.co/http-scheme: https
elasticsearch.k8s.elastic.co/statefulset-name: quickstart-es-default
elasticsearch.k8s.elastic.co/version: 7.13.2


# labels exposing the different tiers to customers for label selectors
elasticsearch.k8s.elastic.co/node-data: "false"
elasticsearch.k8s.elastic.co/node-ingest: "false"
elasticsearch.k8s.elastic.co/node-master: "false"
elasticsearch.k8s.elastic.co/node-ml: "false"
elasticsearch.k8s.elastic.co/node-remote_cluster_client: "false"
elasticsearch.k8s.elastic.co/node-transform: "false"
elasticsearch.k8s.elastic.co/node-voting_only: "false"
elasticsearch.k8s.elastic.co/node-data_cold: "false"
elasticsearch.k8s.elastic.co/node-data_content: "false"
elasticsearch.k8s.elastic.co/node-data_hot: "false"
elasticsearch.k8s.elastic.co/node-data_warm: "false"

# labels added by the StatefulSet controlller
controller-revision-hash: quickstart-es-default-7f4588b7c5
statefulset.kubernetes.io/pod-name: quickstart-es-default-0

```

Some Kubernetes flavours, namely VMWare Tanzu restrict the overall number of labels on a Pod to 25. We should investigate whether we can reduce the number of labels added by the operator to give users a larger chunk of the available labels for the own use.

One approach would be to drop the node tier labels altogether. Users could add them back when needed through the `podTemplate`. This would be a potentially breaking change for customers relying on the presence of those labels today. We would need to call it out explicitly and prominently in the documentation and release notes that prior to upgrading to the version of ECK that removes these labels customers would have to add them to the `podTemplate` to be able to upgrade without interruption.
