### ISSUE TITLE
Can update but not create an Elasticsearch cluster with monitoring data sent to itself

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#4624]
The following manifest leads to error logs in the operator:

```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.14.0-SNAPSHOT
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
  monitoring:
    metrics:
      elasticsearchRefs:
      - name: quickstart
    logs:
      elasticsearchRefs:
      - name: quickstart
```

```
2021-07-09T11:05:27.820+0200	ERROR	manager.eck-operator.controller.es-monitoring-association-controller	Reconciler error	{"service.version": "1.7.0-SNAPSHOT+30579acb", "name": "quickstart", "namespace": "default", "error": "while fetching referenced service: Service \"quickstart-es-http\" not found", "errorCauses": [{"error": "while fetching referenced service: Service \"quickstart-es-http\" not found"}, {"error": "while fetching referenced service: Service \"quickstart-es-http\" not found"}]}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/Users/sebgl/work/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:253
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/Users/sebgl/work/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:214
```

I think we have a circular dependency on the Elasticsearch controller vs. association controller, both are waiting for each other t do something. The association controller waits for the service to be created while the Elasticsearch controller probably waits for the association to be configured (I haven't investigated much).

This error does not manifest if we first create the Elasticsearch cluster:

```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.14.0-SNAPSHOT
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
```

Then add the monitoring bits:

```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.14.0-SNAPSHOT
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
  monitoring:
    metrics:
      elasticsearchRefs:
      - name: quickstart
    logs:
      elasticsearchRefs:
      - name: quickstart
```
