### ISSUE TITLE
Trial License not enabling X-Pack during Pod Initialisation

### ISSUE THREAD

**Issue by bendudz** [elastic/cloud-on-k8s#4628]
## Bug Report
**What did you do?**

I have got ECK operator deployed on Minikube, following the Quickstart guide. This is a trial environment before moving it to OpenShift for a client.

There is a requirement for me to deploy ECK with a Private Key Infrastructure setup. I have modified the Elastic & Kibana configs to allow my private CA singed certs to access the system & authorise users to carry out actions on the system. This works flawlessly with the trial licence installed.

I want the system to ALWAYS require a certificate for authentication. Setting `xpack.security.http.ssl.client_authentication` to `required` breaks the readiness probe meaning elastic search doesn't become ready to serve requests.

So I have modified the readiness probe to temporarily use my user certificate (I know this is trusted, I'm mapped to the superuser role & can authenticate with it) to hit https://{myip}:9200.

My readiness probe is the same as the regular one that just adds the cacert, cert & key to the curl command:
`curl --cacert ca.crt --cert my.pem --key my.key https://{myip}:9200`

```
containers:
  - name: elastic search
    readinessProbe:
      exec:
        command:
          - bash
          - -c
          - /usr/share/elasticsearch/config/readiness/probe.sh
      initialDelaySeconds: 30 # upped this to see if ES would have chance to load up extra resources ie rolemappings / licence stuff
      timeoutSeconds: 5
      periodSeconds: 5
```

**What did you expect to see?**

I expected the readiness probe script to use my cert to authenticate successfully, return a 200 & elasticsearch pod to become ready to serve requests.

**What did you see instead? Under which circumstances?**

The readiness probe returns a 401. 

There is a persistent log entry:

```
{
  "type": "server",
  "timestamp": "2021-07-09T08:26:26,107Z",
  "level": "WARN",
  "component": "o.e.x.s.a.AuthenticationService",
  "cluster.name": "elasticsearch",
  "node.name": "elasticsearch-es-default-0",
  "message": "No authentication credential could be extracted using realms  reserved/reserved,file/file1,native/native1]. Realms [pki/pki1] were skipped because they are not permitted on the current license",
  "cluster.uuid": "xJ2CqV3kSjyF08wHiqdhAg",
  "node.id": "Wc5UPY_RTSKJmHUXLu5nhg"
}
```

Why is the trial licence no good or not available for when the readiness probe makes a request?

Is there something I need to add to the probe to allow elastic search time to load the licence?

If I leave the basic auth probe in place so that ES becomes available, hitting ES with my user cert proves that Xpack is licensed using the trial secret.

**Environment**

* ECK version:

	1.6.0
        Elasticsearch, Kibana & APM are all v 7.13.2

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* On premise: no
	* Cloud:  none
	* Kubernetes distribution: Minikube v1.21.0 
	
```
$ kubectl version
1.21.2
```

* Resource definition:
```
NA
```

* Logs:

I've added 2 log files. basic-readiness is when the system works without modifying the probe. pki-readiness is the log from when I enable the custom readiness probe that uses a certificate to connect to ES. 

[pki-readiness.txt](https://github.com/elastic/cloud-on-k8s/files/6791126/pki-readiness.txt)
[basic-readiness.txt](https://github.com/elastic/cloud-on-k8s/files/6791127/basic-readiness.txt)

**Comment by thbkrkr** [comment]
Can you share the entire ES yaml manifest you are using?

I do not understand one thing.

Your new readiness probe does:
> curl --cacert ca.crt --cert my.pem --key my.key https://{myip}:9200

When you say:
> hitting ES with my user cert proves that Xpack is licensed using the trial secret

I'm assuming you are using a similar curl command. If yes, what could be different in the two calls?

**Comment by bendudz** [comment]
Thanks for your response. Heres my configuration:

```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 7.13.2
  http:
    tls:
      certificate:
        secretName: tlscert
  nodeSets:
    - name: default
      count: 1
      config:
        #logger.org.elasticsearch: debug
        xpack.security.ssl.diagnose.trust: true
       # Setting this to required is whats needed but breaks the readinessProbe
        xpack.security.http.ssl.client_authentication: optional
        xpack.security.authc:
          token:
            enabled: true
          realms:
            pki:
              pki1:
                delegation:
                  enabled: true
                certificate_authorities:
                  - /usr/share/elasticsearch/config/realm/ca.crt
                order: 0
                files:
                  role_mapping: /usr/share/elasticsearch/config/rolemaps/role-mappings.yml
        node.master: true
        node.data: true
        node.ingest: true
        node.store.allow_mmap: false
      podTemplate:
        metadata:
          labels:
        spec:
          containers:
            - name: elasticsearch
              readinessProbe:
                exec:
                  command:
                    - bash
                    - -c
                    - /usr/share/elasticsearch/config/readiness/readiness-probe-script.sh
                initialDelaySeconds: 30
                timeoutSeconds: 5
                periodSeconds: 5
              volumeMounts:
                - mountPath: /usr/share/elasticsearch/config/realm
                  name: realm-cert
                - mountPath: /usr/share/elasticsearch/config/rolemaps
                  name: role-map
                - mountPath: /usr/share/elasticsearch/config/es-cert
                  name: es-cert
              env:
                - name: READINESS_CERT
                  value: /usr/share/elasticsearch/config/es-cert/es.pem
                - name: READINESS_CERT_KEY
                  value: /usr/share/elasticsearch/config/es-cert/es.key
                - name: CA_CERT
                  value: /usr/share/elasticsearch/config/realm/ca.crt
          volumes:
            - name: realm-cert
              secret:
                secretName: tlscert
            - name: role-map
              configMap:
                name: role-mappings
            - name: es-cert
              secret:
                secretName: es-cert
            - name: readiness-probe
              configMap:
                name: readiness-probe
                defaultMode: 0755

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: role-mappings
data:
  # The mapping has to be the full DN.
  # Its possible to call GET https://localhost:9200/_security/_authenticate with the cert & wil give full DN
  role-mappings.yml: |-
    elastic_internal_probe_user:
      - "EMAILADDRESS=kibanaserviceuser@elastic.demo, CN=kibanaserviceuser"
    user:
      - "EMAILADDRESS=jonvaliduser@elastic.demo, CN=lewisvaliduser"
    superuser:
      - "EMAILADDRESS=benvaliduser@elastic.demo, CN=benvaliduser"
    beats_system:
      - "EMAILADDRESS=metricbeat@elastic.demo, CN=metricbeat"
      - "EMAILADDRESS=filebeat@elastic.demo, CN=filebeat"
    logstash_system:
      - "EMAILADDRESS=logstash@elastic.demo, CN=logstash"
    kibana_system:
      - "EMAILADDRESS=kibanaserviceuser@elastic.demo, CN=kibanaserviceuser"


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: readiness-probe
data:
  # Changing the default readiness probe to use a certificate
  readiness-probe-script.sh: |-
    #!/usr/bin/env bash

    # fail should be called as a last resort to help the user to understand why the probe failed
    function fail {
      timestamp=$(date --iso-8601=seconds)
      echo "{\"timestamp\": \"${timestamp}\", \"message\": \"readiness probe failed\", "$1"}" | tee /proc/1/fd/2 2> /dev/null
      exit 1
    }

    READINESS_PROBE_TIMEOUT=${READINESS_PROBE_TIMEOUT:=3}

    # Check if we are using IPv6
    if [[ $POD_IP =~ .*:.* ]]; then
      LOOPBACK="[::1]"
    else
      LOOPBACK=127.0.0.1
    fi

    # request Elasticsearch on /
    # we are turning globbing off to allow for unescaped [] in case of IPv6
    ENDPOINT="${READINESS_PROBE_PROTOCOL:-https}://${LOOPBACK}:9200/"
    status=$(curl -o /dev/null -w "%{http_code}" --max-time ${READINESS_PROBE_TIMEOUT} -XGET -g -s -k --cacert ${CA_CERT} --cert ${READINESS_CERT} --key ${READINESS_CERT_KEY} $ENDPOINT)
    curl_rc=$?

    if [[ ${curl_rc} -ne 0 ]]; then
      fail "\"curl_rc\": \"${curl_rc}\""
    fi

    if [[ ${status} == "200" ]]; then
      exit 0
    else
      fail " \"status\": \"${status}\" "
    fi
```

> When you say:
> hitting ES with my user cert proves that Xpack is licenced using the trial secret

When the system uses the built in readiness probe that uses basic auth (comment out the readinessProbe section in the config above), I am able to use my cert to authenticate my user. This proves the trial licence works as I'm using a pki realm.

I've included the config map used to create the readiness probe script. Its a tweak on the original one provided by elastic but essentially:

`curl -o /dev/null -w "%{http_code}" --max-time ${READINESS_PROBE_TIMEOUT} -XGET -g -s -k --cacert ${CA_CERT} --cert ${READINESS_CERT} --key ${READINESS_CERT_KEY} $ENDPOINT`

Even exec'ing into the pod & running the curl command results in a 401 & produces the same log message:
`curl --max-time 3 -XGET -g -s -k --cacert ca.crt --cert es.pem --key es.key https://127.0.0.1:9200`

The logs show that the PKI realm is not being interrogated by the AuthenticationService as it believes there is no licence installed when there is.

**Comment by bendudz** [comment]
Hi folks any updates on this please?

**Comment by pebrc** [comment]
I think you might run into a chicken and egg situation here. In order for the ECK operator to start a trial on your Elasticsearch cluster it needs a "Ready" Pod to talk to. However given your setup no Pod ever reaches that "Ready" state. You probably have a bunch of errors in the operator logs that point into that direction.

**Comment by david-kow** [comment]
Closing this. Feel free to reopen as needed.

**Comment by bendudz** [comment]
I’ve tested this on an operator that has an enterprise licence installed but no pods deployed. 

On deployment the symptoms are exactly the same. I can see `realms pki/pki1 were skipped because they are not permitted on the current license`.

So I take it even though we have an enterprise licence we cannot use a certificate in the readiness probe as xpack features are not enabled until a pod has been started with the operator. 

Could I have some guidance on how we can turn off native realm then please?

**Comment by m-adams** [comment]
HI, could we please reopen this as it's been retested with the Ent license.

**Comment by nerophon** [comment]
@david-kow this issue has been reopened with new circumstances and evidence. Please may we re-triage this?

**Comment by nerophon** [comment]
@@david-kow repinging on this issue. Please may we re-triage this at the customer's request, since now the symptom set has changed and the issue is no longer limited to trial licenses?

**Comment by pebrc** [comment]
> So I take it even though we have an enterprise licence we cannot use a certificate in the readiness probe as xpack features are not enabled until a pod has been started with the operator.

Correct, the license is installed via an API call which means at least one running Pod is required. 

> Could I have some guidance on how we can turn off native realm then please?

Since https://github.com/elastic/cloud-on-k8s/pull/2038 the native realm is always added to the configuration and enabled under the name `native1` to turn it off you would therefore simply follow [the Elasticsearch documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html#ref-native-settings) 

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 7.13.2
  nodeSets:
  - name: default
    count: 1
    config:
      xpack.security.authc.realms.native.native1.enabled: false
```
