### ISSUE TITLE
Reconfiguring node roles to create dedicated masters can lead to boot loop situation

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#4660]
When re-configuring an existing node set. For example:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.14.0-SNAPSHOT
  nodeSets:
  - name: default
    count: 3
    config:
      node.roles: [ master, data ]
```

to

```yaml
      node.roles: [ master ] 
# assume other node set with data role exists in the cluster
```

the operator might not be able to successfully roll out this configuration change if the nodes contain shard data. Because we handle this case as a rolling upgrade we don't move data out of the nodes before applying this configuration change. Elasticsearch however will refuse to start up (tested on 7.14.0-SNAPSHOT) the node as a dedicated master node if the data directory still contains shard data. From a Kubernetes perspective this will lead to a Pod stuck in CrashLoopBackoff cycles. 

**Remediation**

Once stuck in the boot loop the user can only reconfigure the Elasticsearch cluster back to the original configuration (i.e. `master` and `data` roles) wait for the node to rejoin the cluster and then create a new node set with dedicated masters instead.

**Workaround** 

Do not reconfigure an existing node set in order to remove the data role but remove the old node set and create a new one with a different name with the desired dedicated masters. 

**Discussion**

Should we try to handle this situation in the operator? We could detect the transition from a data holding node to a dedicated master node and try to move the data with allocation filters to other data nodes in the cluster before applying the configuration change (not tested). While a good workaround exists, as outlined above, I believe the current status is still somewhat unsatisfactory as the cause of the issue can only be determined by inspecting Elasticsearch logs on the boot looping node.
