### ISSUE TITLE
[filebeat] secureSettings keystore init container fail to initialise

### ISSUE THREAD

**Issue by Marchelune** [elastic/cloud-on-k8s#4695]
## Bug Report
**What did you do?**
Hi there! We added a `secureSettings` secret to a filebeat daemon set.

**What did you expect to see?**

A filebeat pod starts on each k8 node.

**What did you see instead? Under which circumstances?**

All pods fail to initialise, their status remains `Init: CrashLoopBackOff`.
The initialized condition is not met (`ContainersNotInitialized`), with the message `containers with incomplete status: [elastic-internal-init-keystore]`.

In order to get more details, I ran `kubectl logs filebeat-application-logs-beat-filebeat-zv9lq -c elastic-internal-init-keystore`, which gave the following result:

```
+ keystore_initialized_flag=/usr/share/filebeat/data/elastic-internal-init-keystore.ok
+ [[ -f /usr/share/filebeat/data/elastic-internal-init-keystore.ok ]]
+ echo 'Initializing keystore.'
+ filebeat keystore create --force
Initializing keystore.
error initializing beat: Beat meta file failed to open: open /usr/share/filebeat/data/meta.json: permission denied
```

I used `secureSettings` with my Elasticsearch deployment, and it works without an issue there.

**Environment**

* ECK version: 1.5.0
* Filebeat version: 7.13.0
* Kubernetes information:
	* Azure AKS
	* Kubernetes v1.18.14
	* kubectl client: 1.21

	

* Resource definition:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: beats-logging
---
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: filebeat-application-logs
  namespace: beats-logging
spec:
  type: filebeat
  version: 7.13.0
  secureSettings:
    - secretName: elastic-cloud-access-config
  config:
    filebeat.autodiscover.providers:
      - type: kubernetes
        node: ${NODE_NAME}
        templates:
          - condition:
              or:
                - equals.kubernetes.namespace: prod-applications
                - equals.kubernetes.namespace: stg-applications
            config:
              - type: container
                paths:
                  - /var/log/containers/*${data.kubernetes.container.id}.log
    processors:
      - add_host_metadata: {}
    output.elasticsearch:
      hosts: ["${ELASTIC_CLOUD_ELASTICSEARCH_HOST}"]
      api_key: ${ELASTIC_CLOUD_BEATS_ELASTICSEARCH_API_KEY}

    setup:
      dashboards.enabled: false
      template:
        name: "filebeat-application-%{[agent.version]}"
        pattern: "filebeat-application-%{[agent.version]}-*"

      ilm:
        enabled: true
        policy_name: "filebeat-application-%{[agent.version]}"
        rollover_alias: "filebeat-application-%{[agent.version]}"
        pattern: "{now/d}-000001"

  daemonSet:
    podTemplate:
      spec:
        serviceAccountName: filebeat
        automountServiceAccountToken: true
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true
        containers:
          - name: filebeat
            securityContext:
              runAsUser: 0
            volumeMounts:
              - name: varlogcontainers
                mountPath: /var/log/containers
              - name: varlogpods
                mountPath: /var/log/pods
              - name: varlibdockercontainers
                mountPath: /var/lib/docker/containers
            env:
              - name: NODE_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
        volumes:
          - name: varlogcontainers
            hostPath:
              path: /var/log/containers
          - name: varlogpods
            hostPath:
              path: /var/log/pods
          - name: varlibdockercontainers
            hostPath:
              path: /var/lib/docker/containers
---
apiVersion: v1
kind: Secret
metadata:
  namespace: beats-logging
  name: elastic-cloud-access-config
type: Opaque
stringData:
  ELASTIC_CLOUD_ELASTICSEARCH_HOST: https://something.com:9200
  ELASTIC_CLOUD_BEATS_ELASTICSEARCH_API_KEY: someapi:key
```
