### ISSUE TITLE
kibana cannot start up with ECK on ppc64le

### ISSUE THREAD

**Issue by bivasda1** [elastic/cloud-on-k8s#4743]
## Bug Report
**What did you do?**

I have been trying to Install Kibana with ECK  on **OCP v4.8.2** ppc64le architecture. However, It's failing with error

`FATAL  Error: Unknown configuration key(s): "xpack.encryptedSavedObjects.encryptionKey", "xpack.license_management.ui.enabled", "xpack.monitoring.kibana.collection.enabled", "xpack.monitoring.ui.container.elasticsearch.enabled", "xpack.reporting.encryptionKey", "xpack.security.audit.enabled", "xpack.security.enabled", "xpack.security.encryptionKey". Check for spelling errors and ensure that expected plugins are installed.`

**What did you expect to see?**
The kibana pod should be in running state.
**Environment**

* ECK version: 
          ` 7.11.2`

* Kubernetes/OpenShift information:
            `OCP v4.8.2`

Any pointers / suggestions would be really helpul. Thanks. 😄

**Comment by thbkrkr** [comment]
We are not testing ECK on the `ppc64le` architecture, so I can't guarantee that it can work on this particular architecture.

We don't officially support OpenShift 4.8.x yet but we will soon (https://github.com/elastic/cloud-on-k8s/issues/4716). I've checked and ECK `1.7.0` is working fine on OpenShift `4.8.2` following this [documentation](https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-openshift.html).
```
> oc version       
Client Version: 4.7.0
Server Version: 4.8.2
Kubernetes Version: v1.21.1+051ac4f
                                                                                                                                                                                         
> oc get elastic,po
NAME                                                              HEALTH   NODES   VERSION   PHASE   AGE
elasticsearch.elasticsearch.k8s.elastic.co/elasticsearch-sample   green    1       7.14.0    Ready   4m9s

NAME                                         HEALTH   NODES   VERSION   AGE
kibana.kibana.k8s.elastic.co/kibana-sample   green    1       7.14.0    4m

NAME                                    READY   STATUS    RESTARTS   AGE
pod/elasticsearch-sample-es-default-0   1/1     Running   0          3m37s
pod/kibana-sample-kb-8448497c94-sgb2v   1/1     Running   0          3m36s
```

There is a high probability that your problem is related to your `ppc64le` architecture. I'm afraid it will be hard to help you but let's try.
`7.11.2` is not an ECK version but a version of the Elastic Stack. What version of ECK are you using?
Can you test with the latest version of the Elastic Stack, the `7.14.0`?
Can you share the YAML manifest that you use to deploy the Elastic Stack resources?
Can you share the full Kibana log?

**Comment by bivasda1** [comment]
Hi @thbkrkr 
Thanks for your quick response. :) 
As **X-pack** is not supported for power(ppc64le) I was trying to disable it in **Intel platform** so if it succeeded then I will implement the same for ppc64le.
**Steps taken**
1.As Elasticsearch and Kibana tightly coupled  I was trying to disable from **Elasticsearch.yaml** . 
In the Elasticsearch.yaml **config  section**  I have disabled x-pack components. While deploying pod got stuck 
```
[root@inverts1 elasticsearch]# oc get all
NAME                                    READY   STATUS    RESTARTS   AGE
**pod/elastic-operator-0**                  1/1     Running   1          30m
pod/elasticsearch-sample-es-default-0   0/1     Running   0          4m33s

NAME                                        TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
service/elastic-webhook-server              ClusterIP   172.30.8.48    <none>        443/TCP    30m
service/elasticsearch-sample-es-default     ClusterIP   None           <none>        9200/TCP   4m33s
service/elasticsearch-sample-es-http        ClusterIP   172.30.88.52   <none>        9200/TCP   4m35s
service/elasticsearch-sample-es-transport   ClusterIP   None           <none>        9300/TCP   4m35s

NAME                                               READY   AGE
statefulset.apps/elastic-operator                  1/1     30m
statefulset.apps/elasticsearch-sample-es-default   0/1     4m33s

**Elasticsearch.yaml:**
# This sample sets up an Elasticsearch cluster with 3 nodes.
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
spec:
  version: 7.14.0
  nodeSets:
  - name: default
    config:
      # most Elasticsearch configuration parameters are possible to set, e.g: node.attr.attr_name: attr_value
      node.roles: ["master", "data", "ingest", "ml"]
      # this allows ES to run on nodes even if their vm.max_map_count has not been increased, at a performance cost
      node.store.allow_mmap: false
      xpack.ml.enabled: false
       xpack.monitoring.enabled: false
       xpack.security.enabled: false

    podTemplate:
      metadata:
        labels:
          # additional labels for pods
          foo: bar
      spec:
        # this changes the kernel setting on the node to allow ES to use mmap
        # if you uncomment this init container you will likely also want to remove the
        # "node.store.allow_mmap: false" setting above
        # initContainers:
        # - name: sysctl
        #   securityContext:
        #     privileged: true
        #   command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        ###
        # uncomment the line below if you are using a service mesh such as linkerd2 that uses service account tokens for pod identification.
        # automountServiceAccountToken: true
        containers:
        - name: elasticsearch
          # specify resource limits and requests
          resources:
            limits:
              memory: 4Gi
              cpu: 1
          env:
          - name: ES_JAVA_OPTS
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms2g -Xmx2g"
    count: 1**

```
2.Even I was trying to disable x-pack from Kibana as well, pod got stuck.

```
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-sample
spec:
  version: 7.14.0
  count: 1
  config:
    xpack.security.enabled: false
    xpack.monitoring.enabled: false
    xpack.security.enabled: false
  elasticsearchRef:
    name: "elasticsearch-sample"
  #http:
  #  service:
  #    spec:
  #      type: LoadBalancer
  # this shows how to customize the Kibana pod
  # with labels and resource limits
  podTemplate:
    metadata:
      labels:
        foo: bar
    spec:
      containers:
      - name: kibana
        resources:
          limits:
            memory: 1Gi
            cpu: 1

[root@inverts1 kibana]# oc get all
NAME                                    READY   STATUS    RESTARTS   AGE
pod/elastic-operator-0                  1/1     Running   2          59m
pod/elasticsearch-sample-es-default-0   1/1     Running   0          21m
pod/kibana-sample-kb-7555c6f87-9lcmc    0/1     Running   0          6m7s
```
I have share the kibana logs as well.
[kibana_logs.txt](https://github.com/elastic/cloud-on-k8s/files/7011964/kibana_logs.txt)

Any pointers / suggestions would be really helpul. Thanks. 😄
