### ISSUE TITLE
Elastic search: unable to update or add new labels after pvc's are created. So elastic cluster pod's and pvc's labels aren't getting updated labels.

### ISSUE THREAD

**Issue by vinodhreddyg** [elastic/cloud-on-k8s#4760]
## Proposal

**Use case. Why is this important?**

## Bug Report
**What did you do?**
Update existing labels on pvc.

**What did you expect to see?**
Expected to see the updated labels on pvc and elastic cluster pod's.

**What did you see instead? Under which circumstances?**
Operator logs throwing an exception stating that it can't statefulset volumeClaimTemplate section. So eventually the pvc and elastic cluster pod's aren't get the labels updated. 

**Environment**

* ECK version: 1.3

	insert version or git commit id here

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* On premise ?
	* Cloud: GKE / EKS / AKS ? GKE 1.9+
	* Kubernetes distribution: Openshift / Rancher / PKS ?
	
	for each of them please give us the version you are using
```
$ kubectl version
```

* Resource definition:
```
if relevant insert the resource definition
```

* Logs:
```
{"log.level":"error","@timestamp":"2021-08-12T18:07:25.193Z","log.logger":"controller","message":"Reconciler error","service.version":"1.3.0+6db1914b","service.type":"eck","ecs.version":"1.4.0","controller":"elasticsearch-controller","name":"elasticsearch-config","namespace":"test","error":"reconcile StatefulSet: StatefulSet.apps \"elasticsearch-config-es-master\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden","errorCauses":[{"error":"reconcile StatefulSet: StatefulSet.apps \"elasticsearch-config-es-master\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden"}],"error.stack_trace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:246\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:218\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:197\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/wait/wait.go:90"}
```

**Comment by thbkrkr** [comment]
This is by design in k8s not in ECK. StatefulSet does not allow to change thing outside 'replicas', 'template', and 'updateStrategy'.

It means that:
> volume claim templates can only have their storage requests increased, if the storage class allows volume expansion. Any other change is forbidden

To update an existing PVC, you can create a new nodeSet with different settings, and remove the existing nodeSet as documented on the '[Updating the volume claim settings](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-volume-claim-templates.html#k8s_updating_the_volume_claim_settings)' section.

You can also specify custom labels during creation. Example:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: foo
spec:
  version: 7.14.0
  nodeSets:
  - name: master
    config:
      node.store.allow_mmap: false
    count: 1
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
        labels:
          custom: label
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: standard
```

```sh
> kubectl get pvc elasticsearch-data-foo-es-master-0 -o json | jq '.metadata.labels' 
{
  "common.k8s.elastic.co/type": "elasticsearch",
  "custom": "label",
  "elasticsearch.k8s.elastic.co/cluster-name": "foo",
  "elasticsearch.k8s.elastic.co/statefulset-name": "foo-es-master"
}

```
