### ISSUE TITLE
[Heartbeat][Synthetics/Browser] Base Heartbeat limits too low for browser monitoring usage

### ISSUE THREAD

**Issue by BenB196** [elastic/cloud-on-k8s#4800]
## Bug Report

---

**This isn't inherently a bug, but something that I think needs to at least be brought up as I'm sure others will run into the issue**

---

**What did you do?**

Test out a simple browser monitor in a Heartbeat deployment:

```javascript
step('go to page', async () => {
    try {
      await page.goto(params.url);
    } catch (e) {
      console.log(e);
    }
});
step ('login', async () => {
    await page.fill('input[name="username"]', params.username);
    await page.fill('input[name="password"]', params.password);
});
step('submit login', async () => {
    try {
      await Promise.all([
        page.waitForNavigation(),
        page.click('input:has-text("Sign In")')
      ]);
    } catch (e) {
      console.log(e);
    }
});
step('validate form to load', async () => {
    try {
      await page.waitForSelector('#theForm')
    } catch (e) {
      console.log(e);
    }
});
```

**What did you expect to see?**

The job completing successfully on each run.

**What did you see instead? Under which circumstances?**

The job randomly crash with errors like:

`Error: page.waitForLoadState: Navigation failed because page crashed!`

By default with ECK Heartbeat deploys with resources of:

```yaml
spec:
  deployment:
    podTemplate:
      spec:
        containers:
          name: heartbeat
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
```

From testing these defaults are far too low for Synthetics/browser monitoring to work, even with a simple monitor.

While I don't believe this needs to fixed directly in ECK, I think it would be helpful to note somewhere that the base resources aren't suitable for browser monitoring, and that they'll need to be changed for it to work.

Note: That the pod itself never got OOM killed, the monitor would always crash before then, so this issue isn't easily detectable from the Kubernetes side.

**Environment**

* ECK version:

	1.7.0

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* On premise ? on-prem
	* Cloud: GKE / EKS / AKS ? N/A
	* Kubernetes distribution: Openshift / Rancher / PKS ? rke2 `v1.20.9+rke2r2`
```
$ kubectl version
```

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9+rke2r2", GitCommit:"7a576bc3935a6b555e33346fd73ad77c925e9e4a", GitTreeState:"clean", BuildDate:"2021-08-05T23:06:55Z", GoVersion:"go1.15.14b5", Compiler:"gc", Platform:"linux/amd64"}
```

* Resource definition:
```yaml
---
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: heartbeat-synthetics-app
  namespace: beats
spec:
  config:
    heartbeat:
      monitors:
      - id: app
        name: App
        params:
          url: <snipped_url>
          password: ${MONITOR_PASSWORD}
          username: ${MONITOR_USERNAME}
        schedule: '@every 5m'
        source:
          inline:
            script: |-
              step('go to page', async () => {
                  try {
                    await page.goto(params.url);
                  } catch (e) {
                    console.log(e);
                  }
              });
              step ('login', async () => {
                  await page.fill('input[name="username"]', params.username);
                  await page.fill('input[name="password"]', params.password);
              });
              step('submit login', async () => {
                  try {
                    await Promise.all([
                      page.waitForNavigation(),
                      page.click('input:has-text("Sign In")')
                    ]);
                  } catch (e) {
                    console.log(e);
                  }
              });
              step('validate form to load', async () => {
                  try {
                    await page.waitForSelector('#theForm')
                  } catch (e) {
                    console.log(e);
                  }
              });
        type: browser
    http:
      enabled: true
      host: 0.0.0.0
      port: 5066
    logging.json: true
  deployment:
    podTemplate:
      metadata:
        annotations:
          co.elastic.metrics/raw: '[{"enabled":true,"module":"beat","hosts":["http://${data.host}:5066"],"metricsets":["stats","state"],"period":"10s","timeout":"3s","xpack":{"enabled":true}}]'
          linkerd.io/inject: enabled
        creationTimestamp: null
      spec:
        automountServiceAccountToken: true
        containers:
        - env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: DEBUG
            value: pw:api
          - name: MONITOR_USERNAME
            valueFrom:
              secretKeyRef:
                key: monitoring_username
                name: heartbeat-synthetics-monitoring
          - name: MONITOR_PASSWORD
            valueFrom:
              secretKeyRef:
                key: monitoring_password
                name: heartbeat-synthetics-monitoring
          - name: GIT_USERNAME
            valueFrom:
              secretKeyRef:
                key: username
                name: heartbeat-synthetics-app-git
          - name: GIT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: heartbeat-synthetics-app-git
          name: heartbeat
          resources: {}
        securityContext: {}
        volumes:
        - emptyDir: {}
          name: beat-data
    replicas: 1
    strategy:
      type: Recreate
  elasticsearchRef:
    name: es-prod
    namespace: elastic-prod
  kibanaRef:
    name: kibana-prod
    namespace: kibana-prod
  type: heartbeat
  version: 7.14.0
```
