### ISSUE TITLE
Upgrading ECK docs imply a restart of all workloads is always required, which is not true

### ISSUE THREAD

**Issue by jonathanrboniface** [elastic/cloud-on-k8s#4804]
## Bug Report
**What did you do?**
Upgraded ECK/elastic-operator 1.4.1 to 1.5.0. Elasticsearch and Kibana were deployed via Helm and used helm diff to ensure that there were no changes so it was clean.

**What did you expect to see?**
Elasticsearch pods successfully restarted after applying the command:
```
kubectl apply -f downloads/eck/1.5.0/all-in-one.yaml
RM_ANNOTATION='eck.k8s.elastic.co/managed-' 
kubectl annotate  --overwrite elasticsearch elk $RM_ANNOTATION
kubectl annotate  --overwrite kibana elk $RM_ANNOTATION
```

**What did you see instead? Under which circumstances?**

The pods in elasticsearch did not restart as the stateful set was not successfully updated.

``` 
kubectl describe elasticsearch elk

Events:
  Type     Reason               Age                From                      Message
  ----     ------               ----               ----                      -------
  Warning  ReconciliationError  59m                elasticsearch-controller  Failed to apply spec change: reconcile StatefulSet: Operation cannot be fulfilled on statefulsets.apps "elk-es-data": the object has been modified; please apply your changes to the latest version and try again
  Warning  Unhealthy            48m (x3 over 63m)  elasticsearch-controller  Elasticsearch cluster health degraded
```

Similar errors are being produced for the Kibana controller as well.
```
kubectl describe kibana

  Warning  ReconciliationError  58m (x397 over 68m)  kibana-controller  Reconciliation error: Operation cannot be fulfilled on deployments.apps "elk-kb": the object has been modified; please apply your changes to the latest version and try again
```

**Environment**
Production

* ECK version:

	1.4.1 to 1.5.0

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* On premise ? No
	* Cloud: GKE / EKS / AKS ? GKE. 1.18.20-gke.501.
	* Kubernetes distribution: Openshift / Rancher / PKS ? GKE. 
	
	for each of them please give us the version you are using
```
$ kubectl version

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-13T15:45:10Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.20-gke.501", GitCommit:"de876a981b936ce528482c45794fb1dfc5005042", GitTreeState:"clean", BuildDate:"2021-06-25T02:54:31Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.18) exceeds the supported minor version skew of +/-1
```

* Resource definition:
```
# Source: elk/templates/elasticsearch.yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elk
spec:
  version: 7.14.0
  http:
    tls:
      certificate:
        secretName: elk-es-cert
  nodeSets:
  - name: master
    count: 3
    podTemplate:
      metadata:
        labels:
          app: elasticsearch
      spec:
        initContainers:
          - name: sysctl
            securityContext:
              privileged: true
            command: [ 'sh', '-c', 'sysctl -w vm.max_map_count=262144' ]
          - name: install-plugins
            command:
            - sh
            - -c
            - |
              bin/elasticsearch-plugin install --batch repository-gcs
        containers:
          - name: elasticsearch
            # specify resource limits and requests
            resources:
             limits:
               cpu: 4
               memory: 4Gi
             requests:
               cpu: 2
               memory: 2Gi
            env:
              - name: ES_JAVA_OPTS
                value: -Xms2g -Xmx2g
    config:
      node.roles: ["master"]
      xpack.security.authc.realms:
        native.native1:
          order: 0
        saml.saml1:
          attributes.groups: groups
          attributes.mail: email
          attributes.principal: nameid:persistent
          idp.entity_id: http://www.okta.com/exkjjm6hhxrz00xtG1t7
          idp.metadata.path: https://example.okta.com/app/m6hhxrz00xtG1t7/sso/saml/metadata
          order: 1
          sp.acs: https://example.internal.example.com/api/security/saml/callback
          sp.entity_id: https://example.internal.example.com/
          sp.logout: https://example.internal.example.com/logout
    volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
                requests:
                    storage: 20Gi
            storageClassName: ssd-resize
  - name: data
    count: 3
    podTemplate:
      metadata:
        labels:
          app: elasticsearch
      spec:
        initContainers:
          - name: sysctl
            securityContext:
              privileged: true
            command: [ 'sh', '-c', 'sysctl -w vm.max_map_count=262144' ]
          - name: install-plugins
            command:
            - sh
            - -c
            - |
              bin/elasticsearch-plugin install --batch repository-gcs
        containers:
          - name: elasticsearch
            # specify resource limits and requests
            resources:
             limits:
               cpu: 16
               memory: 64Gi
             requests:
               cpu: 8
               memory: 64Gi
            env:
              - name: ES_JAVA_OPTS
                value: -Xms31g -Xmx31g
    config:
      node.roles: ["data", "ingest"]
      xpack.security.authc.realms:
        native.native1:
          order: 0
        saml.saml1:
          attributes.groups: groups
          attributes.mail: email
          attributes.principal: nameid:persistent
          idp.entity_id: http://www.okta.com/exkjjm6hhxrz00xtG1t7
          idp.metadata.path: https://example.okta.com/app/exkjjm6hhxrz00xtG1t7/sso/saml/metadata
          order: 1
          sp.acs: https://example.internal.example.com/api/security/saml/callback
          sp.entity_id: https://example.internal.example.com/
          sp.logout: https://example.internal.example.com/logout
    volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
                requests:
                        storage: 50Ti
            storageClassName: ssd-resize
---
# Source: elk/templates/kibana.yaml
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: elk
spec:
  version: 7.14.0
  count: 1
  podTemplate:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          # specify resource limits and requests
          resources:
             limits:
               cpu: 2
               memory: 2.5Gi
             requests:
               cpu: 0.5
               memory: 1Gi
  http:
    service:
      spec:
        type: NodePort
        externalTrafficPolicy: Local
    tls:
      certificate:
        secretName: internal-example-com-wildcard
  elasticsearchRef:
    name: elk
  config:
    server.publicBaseUrl: https://example.internal.example.com
    xpack.security.authc.providers:
      basic.basic1:
        order: 1
      saml.saml1:
        description: Log in with Okta
        icon: https://www.example.com/favicon.ico
        order: 0
        realm: saml1
```

* Logs:
Same as above
``` 
kubectl describe elasticsearch elk

Events:
  Type     Reason               Age                From                      Message
  ----     ------               ----               ----                      -------
  Warning  ReconciliationError  59m                elasticsearch-controller  Failed to apply spec change: reconcile StatefulSet: Operation cannot be fulfilled on statefulsets.apps "elk-es-data": the object has been modified; please apply your changes to the latest version and try again
  Warning  Unhealthy            48m (x3 over 63m)  elasticsearch-controller  Elasticsearch cluster health degraded
```
Similar errors are being produced for the Kibana controller as well.
```
kubectl describe kibana

  Warning  ReconciliationError  58m (x397 over 68m)  kibana-controller  Reconciliation error: Operation cannot be fulfilled on deployments.apps "elk-kb": the object has been modified; please apply your changes to the latest version and try again
```
