### ISSUE TITLE
CustomResource specified for ECK v1.6.0 no longer works with v1.7.1 and parameters set to empty objects

### ISSUE THREAD

**Issue by leifmadsen** [elastic/cloud-on-k8s#4817]
## Bug Report
**What did you do?**

Deployed an ElasticSearch manifest on OCP 4.8 against ECK 1.7.1 which was working on 1.6.0.

**What did you expect to see?**

A deployed ElasticSearch environment based on the CustomResource definition.

**What did you see instead? Under which circumstances?**

The ElasticSearch CR which was specified and working on ECK 1.6.0 no longer works on 1.7.1. In fact various parameters are set to empty objects. Installing ECK 1.6.0, applying the CR, results in a deployed ElasticSearch. If the Operator is upgraded then the ElasticSearch CR is mangled to something invalid for the ECK Operator.

**Environment**

OCP 4.8

* ECK version:

v1.7.1

* Resource definition:

As defined and working with ECK v1.6.0.

```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: service-telemetry
spec:
  auth: {}
  http:
    service:
      metadata:
        creationTimestamp: null
      spec: {}
    tls:
      certificate:
        secretName: elasticsearch-es-cert
  nodeSets:
  - config:
      node.data: true
      node.ingest: true
      node.master: true
      node.store.allow_mmap: true
    count: 1
    name: default
    podTemplate:
      metadata:
        labels:
          tuned.openshift.io/elasticsearch: elasticsearch
      spec:
        containers:
        - name: elasticsearch
          resources:
            limits:
              cpu: "2"
              memory: 4Gi
            requests:
              cpu: "1"
              memory: 4Gi
        volumes:
        - emptyDir: {}
          name: elasticsearch-data
  transport:
    service:
      metadata:
        creationTimestamp: null
      spec: {}
    tls:
      certificate: {}
  updateStrategy:
    changeBudget: {}
  version: 7.10.2
```

Resulting CR if applied against ECK 1.7.1 or an Operator upgrade from 1.6.0 to 1.7.1 is executed.

```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: service-telemetry
spec:
  auth: {}
  http:
    service:
      metadata: {}
      spec: {}
    tls:
      certificate:
        secretName: elasticsearch-es-cert
  monitoring:
    logs: {}
    metrics: {}
  nodeSets:
  - config: {}
    count: 1
    name: default
    podTemplate:
      metadata:
        creationTimestamp: null
      spec:
        containers: null
  transport:
    service:
      metadata: {}
      spec: {}
    tls:
      certificate: {}
  updateStrategy:
    changeBudget: {}
  version: 7.10.2
```

**Comment by thbkrkr** [comment]
When you do `kubectl get es <name> -o yaml`, it's normal to see empty objects.

Could you provide more specific information to reproduce the issue? 
What version of OCP 4.8 are you using?
What ES manifest are you using?
How do you install ECK 1.6.0 and 1.7.1?

In your case, the reset of `spec.nodeSets[0].config`, `spec.nodeSets[0].podTemplate.spec.containers` `spec.nodeSets[0].podTemplate.spec.volumes` is really very surprising. 

I couldn't reproduce the issue on OCP `4.8.10` by following this:

I installed ECK 1.6.0:
```
oc apply -f https://download.elastic.co/downloads/eck/1.6.0/all-in-one.yaml
```

I  deployed this Elasticsearch (almost yours without the custom TLS cert):
```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: test
  namespace: elastic
spec:
  version: 7.10.2
  nodeSets:
  - config:
      node.data: true
      node.ingest: true
      node.master: true
      node.store.allow_mmap: true
    count: 1
    name: default
    podTemplate:
      metadata:
        labels:
          tuned.openshift.io/elasticsearch: elasticsearch
      spec:
        containers:
        - name: elasticsearch
          resources:
            limits:
              cpu: "2"
              memory: 4Gi
            requests:
              cpu: "1"
              memory: 4Gi
        volumes:
        - emptyDir: {}
          name: elasticsearch-data
```

And updated to ECK 1.7.1:
```
oc replace -f https://download.elastic.co/downloads/eck/1.7.1/crds.yaml
oc apply -f https://download.elastic.co/downloads/eck/1.7.1/operator.yaml
```

My Elasticsearch resource and its underlying k8s resources (sts, pod) didn't change.

I ran `kubectl get es test -o yaml` in 1.6.0 and 1.7.1 and here are the differences:
```diff
> diff 160.yaml 171.yaml 
5c5
<     common.k8s.elastic.co/controller-version: 1.6.0
---
>     common.k8s.elastic.co/controller-version: 1.7.1
10c10
<   generation: 2
---
>   generation: 3
44a45,48
>         f:monitoring:
>           .: {}
>           f:logs: {}
>           f:metrics: {}
68c72
<     time: "2021-09-13T14:46:38Z"
---
>     time: "2021-09-13T14:53:37Z"
71c75
<   resourceVersion: "104465"
---
>   resourceVersion: "107297"
77,78c81
<       metadata:
<         creationTimestamp: null
---
>       metadata: {}
81a85,87
>   monitoring:
>     logs: {}
>     metrics: {}
110,111c116
<       metadata:
<         creationTimestamp: null
---
>       metadata: {}
```
