### ISSUE TITLE
[APM] Internal Server Error on new ELK Stack in Kibana

### ISSUE THREAD

**Issue by SharpThunder** [elastic/cloud-on-k8s#4835]
## Bug Report
**What did you do?**
I tried to install APM Server with Elastic Search and Kibana.
**What did you expect to see?**
Working monitoring with internal monitoring in Stack Monitoring
**What did you see instead? Under which circumstances?**
![image](https://user-images.githubusercontent.com/8118323/133293178-99520829-9d9e-4c08-9ab9-20d95e18eb43.png)

in  https://kibana/app/monitoring#/overview?_g=(cluster_uuid:********,inSetupMode:!t,refreshInterval:(pause:!f,value:10000),time:(from:now-15m,to:now))

**Environment**

* ECK version: 1.7.1

* Kubernetes information:
	* Cloud: EKS K8S 1.19

	for each of them please give us the version you are using
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:38:26Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.13-eks-8df270", GitCommit:"8df2700a72a2598fa3a67c05126fa158fd839620", GitTreeState:"clean", BuildDate:"2021-07-31T01:36:57Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.19) exceeds the supported minor version skew of +/-1
```

* Kibana Logs:
```
{"type":"response","@timestamp":"2021-09-14T16:12:59+00:00","tags":[],"pid":1208,"method":"post","statusCode":200,"req":{"url":"/api/ui_counters/_report","method":"post","headers":{"host":"localhost:51945","connection":"keep-alive","content-length":"399","sec-ch-ua":"\"Google Chrome\";v=\"93\", \" Not;A Brand\";v=\"99\", \"Chromium\";v=\"93\"","content-type":"application/json","sec-ch-ua-mobile":"?0","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36","kbn-version":"7.14.0","kbn-system-request":"true","sec-ch-ua-platform":"\"Windows\"","accept":"*/*","origin":"https://localhost:51945","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://localhost:51945/app/monitoring","accept-encoding":"gzip, deflate, br","accept-language":"de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7","dnt":"1","sec-gpc":"1"},"remoteAddress":"127.0.0.1","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36","referer":"https://localhost:51945/app/monitoring"},"res":{"statusCode":200,"responseTime":214,"contentLength":15},"message":"POST /api/ui_counters/_report 200 214ms - 15.0B"}
    {"type":"log","@timestamp":"2021-09-14T16:13:01+00:00","tags":["error","plugins","monitoring","monitoring"],"pid":1208,"message":"TypeError: Cannot destructure property 'beats' of '(intermediate value)(intermediate value)(intermediate value)' as it is undefined.\n    at handleResponse (/usr/share/kibana/x-pack/plugins/monitoring/server/lib/apm/get_apms.js:46:5)\n    at getApms (/usr/share/kibana/x-pack/plugins/monitoring/server/lib/apm/get_apms.js:181:10)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async Promise.all (index 1)\n    at Object.handler (/usr/share/kibana/x-pack/plugins/monitoring/server/routes/api/v1/apm/instances.js:51:31)\n    at handler (/usr/share/kibana/x-pack/plugins/monitoring/server/plugin.js:406:28)\n    at Router.handle (/usr/share/kibana/src/core/server/http/router/router.js:163:30)\n    at handler (/usr/share/kibana/src/core/server/http/router/router.js:124:50)\n    at exports.Manager.execute (/usr/share/kibana/node_modules/@hapi/hapi/lib/toolkit.js:60:28)\n    at Object.internals.handler (/usr/share/kibana/node_modules/@hapi/hapi/lib/handler.js:46:20)\n    at exports.execute (/usr/share/kibana/node_modules/@hapi/hapi/lib/handler.js:31:20)\n    at Request._lifecycle (/usr/share/kibana/node_modules/@hapi/hapi/lib/request.js:370:32)\n    at Request._execute (/usr/share/kibana/node_modules/@hapi/hapi/lib/request.js:279:9)"}
    {"type":"log","@timestamp":"2021-09-14T16:13:01+00:00","tags":["error","http"],"pid":1208,"message":"Error: Cannot wrap an error\n    at new module.exports (/usr/share/kibana/node_modules/@hapi/hoek/lib/error.js:23:19)\n    at Object.module.exports [as assert] (/usr/share/kibana/node_modules/@hapi/hoek/lib/assert.js:20:11)\n    at Toolkit.response (/usr/share/kibana/node_modules/@hapi/hapi/lib/toolkit.js:191:18)\n    at HapiResponseAdapter.toSuccess (/usr/share/kibana/src/core/server/http/router/response_adapter.js:97:43)\n    at HapiResponseAdapter.toHapiResponse (/usr/share/kibana/src/core/server/http/router/response_adapter.js:86:19)\n    at HapiResponseAdapter.handle (/usr/share/kibana/src/core/server/http/router/response_adapter.js:73:17)\n    at Router.handle (/usr/share/kibana/src/core/server/http/router/router.js:164:34)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at handler (/usr/share/kibana/src/core/server/http/router/router.js:124:50)\n    at exports.Manager.execute (/usr/share/kibana/node_modules/@hapi/hapi/lib/toolkit.js:60:28)\n    at Object.internals.handler (/usr/share/kibana/node_modules/@hapi/hapi/lib/handler.js:46:20)\n    at exports.execute (/usr/share/kibana/node_modules/@hapi/hapi/lib/handler.js:31:20)\n    at Request._lifecycle (/usr/share/kibana/node_modules/@hapi/hapi/lib/request.js:370:32)\n    at Request._execute (/usr/share/kibana/node_modules/@hapi/hapi/lib/request.js:279:9)"}
    {"type":"error","@timestamp":"2021-09-14T16:13:01+00:00","tags":[],"pid":1208,"level":"error","error":{"message":"Internal Server Error","name":"Error","stack":"Error: Internal Server Error\n    at HapiResponseAdapter.toInternalError (/usr/share/kibana/src/core/server/http/router/response_adapter.js:61:19)\n    at Router.handle (/usr/share/kibana/src/core/server/http/router/router.js:177:34)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at handler (/usr/share/kibana/src/core/server/http/router/router.js:124:50)\n    at exports.Manager.execute (/usr/share/kibana/node_modules/@hapi/hapi/lib/toolkit.js:60:28)\n    at Object.internals.handler (/usr/share/kibana/node_modules/@hapi/hapi/lib/handler.js:46:20)\n    at exports.execute (/usr/share/kibana/node_modules/@hapi/hapi/lib/handler.js:31:20)\n    at Request._lifecycle (/usr/share/kibana/node_modules/@hapi/hapi/lib/request.js:370:32)\n    at Request._execute (/usr/share/kibana/node_modules/@hapi/hapi/lib/request.js:279:9)"},"url":"https://localhost:51945/api/monitoring/v1/clusters/ltP3ElZARf6pcZ9V3_dJxA/apm/instances","message":"Internal Server Error"}
    {"type":"response","@timestamp":"2021-09-14T16:13:01+00:00","tags":[],"pid":1208,"method":"post","statusCode":500,"req":{"url":"/api/monitoring/v1/clusters/ltP3ElZARf6pcZ9V3_dJxA/apm/instances","method":"post","headers":{"host":"localhost:51945","connection":"keep-alive","content-length":"81","sec-ch-ua":"\"Google Chrome\";v=\"93\", \" Not;A Brand\";v=\"99\", \"Chromium\";v=\"93\"","accept":"application/json, text/plain, */*","content-type":"application/json;charset=UTF-8","sec-ch-ua-mobile":"?0","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36","kbn-version":"7.14.0","sec-ch-ua-platform":"\"Windows\"","origin":"https://localhost:51945","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://localhost:51945/app/monitoring","accept-encoding":"gzip, deflate, br","accept-language":"de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7","dnt":"1","sec-gpc":"1"},"remoteAddress":"127.0.0.1","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36","referer":"https://localhost:51945/app/monitoring"},"res":{"statusCode":500,"responseTime":64,"contentLength":97},"message":"POST /api/monitoring/v1/clusters/ltP3ElZARf6pcZ9V3_dJxA/apm/instances 500 64ms - 97.0B"}
    {"type":"response","@timestamp":"2021-09-14T16:13:01+00:00","tags":[],"pid":1208,"method":"post","statusCode":200,"req":{"url":"/api/monitoring/v1/setup/collection/cluster/ltP3ElZARf6pcZ9V3_dJxA","method":"post","headers":{"host":"localhost:51945","connection":"keep-alive","content-length":"2","sec-ch-ua":"\"Google Chrome\";v=\"93\", \" Not;A Brand\";v=\"99\", \"Chromium\";v=\"93\"","accept":"application/json, text/plain, */*","content-type":"application/json;charset=UTF-8","sec-ch-ua-mobile":"?0","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36","kbn-version":"7.14.0","sec-ch-ua-platform":"\"Windows\"","origin":"https://localhost:51945","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://localhost:51945/app/monitoring","accept-encoding":"gzip, deflate, br","accept-language":"de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7","dnt":"1","sec-gpc":"1"},"remoteAddress":"127.0.0.1","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36","referer":"https://localhost:51945/app/monitoring"},"res":{"statusCode":200,"responseTime":106,"contentLength":1493},"message":"POST /api/monitoring/v1/setup/collection/cluster/ltP3ElZARf6pcZ9V3_dJxA 200 106ms - 1.5KB"}

```

Also I have this but I don't know if it is related or not.
```
  {"type":"log","@timestamp":"2021-09-14T16:13:56+00:00","tags":["error","plugins","monitoring","monitoring"],"pid":1208,"message":"TypeError: Cannot destructure property 'beats' of '(intermediate value)(intermediate value)(intermediate value)' as it is undefined.\n    at handleResponse (/usr/share/kibana/x-pack/plugins/monitoring/server/lib/apm/get_apms.js:46:5)\n    at getApms (/usr/share/kibana/x-pack/plugins/monitoring/server/lib/apm/get_apms.js:181:10)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async Promise.all (index 1)\n    at Object.handler (/usr/share/kibana/x-pack/plugins/monitoring/server/routes/api/v1/apm/instances.js:51:31)\n    at handler (/usr/share/kibana/x-pack/plugins/monitoring/server/plugin.js:406:28)\n    at Router.handle (/usr/share/kibana/src/core/server/http/router/router.js:163:30)\n    at handler (/usr/share/kibana/src/core/server/http/router/router.js:124:50)\n    at exports.Manager.execute (/usr/share/kibana/node_modules/@hapi/hapi/lib/toolkit.js:60:28)\n    at Object.internals.handler (/usr/share/kibana/node_modules/@hapi/hapi/lib/handler.js:46:20)\n    at exports.execute (/usr/share/kibana/node_modules/@hapi/hapi/lib/handler.js:31:20)\n    at Request._lifecycle (/usr/share/kibana/node_modules/@hapi/hapi/lib/request.js:370:32)\n    at Request._execute (/usr/share/kibana/node_modules/@hapi/hapi/lib/request.js:279:9)"} 
```

I installed Elastic Cloud on K8S with Helm
```
helm repo add elastic https://helm.elastic.co
helm repo update

helm install elastic-operator elastic/eck-operator -n elastic-system --create-namespace
```

Here is my yaml files for Elastic Search, Kibana, and APM Server

** Elastic Search **
```
# This sample sets up an Elasticsearch cluster with 3 nodes.
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: es-cluster
  namespace: elastic-system
spec:
  version: 7.14.0
  volumeClaimDeletePolicy: DeleteOnScaledownOnly
  nodeSets:
  - name: us-east-2a
    count: 1
    config:
      node.attr.zone: us-east-2a
      cluster.routing.allocation.awareness.attributes: k8s_node_name,zone
      node.roles: ["master", "data", "ingest", "ml", "transform"]
      # this allows ES to run on nodes even if their vm.max_map_count has not been increased, at a performance cost
      # node.store.allow_mmap: false
    podTemplate:
      spec:
        # this changes the kernel setting on the node to allow ES to use mmap
        # if you uncomment this init container you will likely also want to remove the
        # "node.store.allow_mmap: false" setting above
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        ###
        # uncomment the line below if you are using a service mesh such as linkerd2 that uses service account tokens for pod identification.
        # automountServiceAccountToken: true
        containers:
        - name: elasticsearch
          # specify resource limits and requests
          resources:
            limits:
              memory: 4Gi
              cpu: 1
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms2g -Xmx2g"
        nodeSelector:
          topology.kubernetes.io/zone: us-east-2a
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: topology.kubernetes.io/zone
                  operator: In
                  values:
                  - us-east-2a   

    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 128Gi
        storageClassName: gp2                   
  - name: us-east-2b
    count: 1
    config:
      node.attr.zone: us-east-2b
      cluster.routing.allocation.awareness.attributes: k8s_node_name,zone    
      node.roles: ["master", "data", "ingest", "ml", "transform"]
      # this allows ES to run on nodes even if their vm.max_map_count has not been increased, at a performance cost
      # node.store.allow_mmap: false
    podTemplate:
      spec:
        # this changes the kernel setting on the node to allow ES to use mmap
        # if you uncomment this init container you will likely also want to remove the
        # "node.store.allow_mmap: false" setting above
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        ###
        # uncomment the line below if you are using a service mesh such as linkerd2 that uses service account tokens for pod identification.
        # automountServiceAccountToken: true
        containers:
        - name: elasticsearch
          # specify resource limits and requests
          resources:
            limits:
              memory: 4Gi
              cpu: 1
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms2g -Xmx2g"
        nodeSelector:
          topology.kubernetes.io/zone: us-east-2b
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: topology.kubernetes.io/zone
                  operator: In
                  values:
                  - us-east-2b
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 128Gi
        storageClassName: gp2                      
  - name: us-east-2c
    count: 1
    config:
      node.attr.zone: us-east-2c
      cluster.routing.allocation.awareness.attributes: k8s_node_name,zone        
      node.roles: ["master", "data", "ingest", "ml", "transform"]
      # this allows ES to run on nodes even if their vm.max_map_count has not been increased, at a performance cost
      # node.store.allow_mmap: false
    podTemplate:
      spec:
        # this changes the kernel setting on the node to allow ES to use mmap
        # if you uncomment this init container you will likely also want to remove the
        # "node.store.allow_mmap: false" setting above
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        ###
        # uncomment the line below if you are using a service mesh such as linkerd2 that uses service account tokens for pod identification.
        # automountServiceAccountToken: true
        containers:
        - name: elasticsearch
          # specify resource limits and requests
          resources:
            limits:
              memory: 4Gi
              cpu: 1
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms2g -Xmx2g"
        nodeSelector:
          topology.kubernetes.io/zone: us-east-2c
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: topology.kubernetes.io/zone
                  operator: In
                  values:
                  - us-east-2c    
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 128Gi
        storageClassName: gp2
```
** Kibana **
```
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic-system
spec:
  version: 7.14.0
  count: 1
  elasticsearchRef:
    name: "es-cluster"
    namespace: elastic-system
  podTemplate:
    spec:
      containers:
      - name: kibana
        resources:
          limits:
            memory: 1Gi
            cpu: 1
        env:
          - name: NODE_OPTIONS
            value: "--max-old-space-size=2048"
```
** APM Server **
```
apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm
  namespace: elastic-system
spec:
  version: 7.14.0
  count: 1
  elasticsearchRef:
    name: "es-cluster"
  kibanaRef:
    name: "kibana"
  podTemplate:
    spec:
      containers:
      - name: apm-server
        resources:
          limits:
            memory: 1Gi
            cpu: 1
```

Thanks.

**Comment by thbkrkr** [comment]
For APM Server, you need to add the `monitoring` settings in the configuration to use internal collection to send monitoring data (see the [documentation](https://www.elastic.co/guide/en/apm/server/current/monitoring-internal-collection.html)):
```yaml
apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm
  namespace: elastic-system
spec:
  version: 7.14.0
  count: 1
  elasticsearchRef:
    name: "es-cluster"
  kibanaRef:
    name: "kibana"
  config:
    # enable internal collection to send monitoring data
    monitoring:
      enabled: true
  podTemplate:
    spec:
      containers:
      - name: apm-server
        resources:
          limits:
            memory: 1Gi
            cpu: 1
```
