### ISSUE TITLE
 Getting Forbidden: pod updates may not change fields other than spec.containers[*].image while resizing/increasing the PVC size

### ISSUE THREAD

**Issue by reddymh** [elastic/cloud-on-k8s#4836]
## Proposal

**Use case. Why is this important?**

## Bug Report
**What did you do?**
Increased the PVC size  

**What did you expect to see?**
Should resize/increase the PVC size without error 

**What did you see instead? Under which circumstances?**
Getting forbidden error  spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds` or `spec.tolerations` 

**Environment**
Dev

* ECK version:
1.4.1
	insert version or git commit id here

* Kubernetes information:
v1.19.7
	insert any information about your Kubernetes environment that could help us:
	* On premise ? yes
	* Cloud: GKE / EKS / AKS ?
	* Kubernetes distribution: Openshift / Rancher / PKS ?
	
	for each of them please give us the version you are using
```
$ kubectl version
```

* Resource definition:
```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  annotations:
    common.k8s.elastic.co/controller-version: 1.4.1
    elasticsearch.k8s.elastic.co/cluster-uuid: oOEtkqwRQWumqaKOv5ypPw
  name: lectest12
  namespace: es-lectest12
spec:
  auth: {}
  http:
    service:
      metadata:
      spec: {}
    tls:
      certificate:
        secretName: lectest12-sec-elasticdb
  image: elasticsearch/elasticsearch:7.10.0
  nodeSets:
  - config:
      node.data: false
      node.ingest: false
      node.master: true
      node.store.allow_mmap: false
    count: 3
    name: master
    podTemplate:
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: failure-domain.beta.kubernetes.io/zone
                  operator: Exists
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: component
                    operator: In
                    values:
                    - elasticsearch
                  - key: role
                    operator: In
                    values:
                    - master
                topologyKey: kubernetes.io/hostname
              weight: 100
        containers:
        - env:
          - name: ES_JAVA_OPTS
            value: -Xms1g -Xmx1g
          name: elasticsearch
          resources:
            limits:
              memory: 2Gi
            requests:
              cpu: "2"
              memory: 2Gi
        securityContext:
          fsGroup: 1000
          runAsGroup: 1000
          runAsUser: 1000
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        storageClassName: elastic-sc
      status: {}
  - config:
      node.data: true
      node.ingest: false
      node.master: false
      node.store.allow_mmap: false
    count: 3
    name: data
    podTemplate:
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: failure-domain.beta.kubernetes.io/zone
                  operator: Exists
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: component
                    operator: In
                    values:
                    - elasticsearch
                  - key: role
                    operator: In
                    values:
                    - data
                topologyKey: kubernetes.io/hostname
              weight: 100
        containers:
        - env:
          - name: ES_JAVA_OPTS
            value: -Xms4g -Xmx4g
          name: elasticsearch
          resources:
            limits:
              memory: 8Gi
            requests:
              cpu: "2"
              memory: 8Gi
        securityContext:
          fsGroup: 1000
          runAsGroup: 1000
          runAsUser: 1000
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: elastic-sc
      status: {}
  - config:
      node.data: false
      node.ingest: false
      node.master: false
      node.store.allow_mmap: false
    count: 2
    name: client
    podTemplate:
      metadata:
        labels:
          name: lectest12-client
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: failure-domain.beta.kubernetes.io/zone
                  operator: Exists
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: component
                    operator: In
                    values:
                    - elasticsearch
                  - key: role
                    operator: In
                    values:
                    - client
                topologyKey: kubernetes.io/hostname
              weight: 100
        containers:
        - env:
          - name: ES_JAVA_OPTS
            value: -Xms4g -Xmx4g
          name: elasticsearch
          resources:
            limits:
              memory: 8Gi
            requests:
              cpu: "2"
              memory: 8Gi
        securityContext:
          fsGroup: 1000
          runAsGroup: 1000
          runAsUser: 1000
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        storageClassName: elastic-sc
      status: {}
  - config:
      node.data: true
      node.ingest: true
      node.master: false
      node.store.allow_mmap: false
    count: 1
    name: ingest
    podTemplate:
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: failure-domain.beta.kubernetes.io/zone
                  operator: Exists
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: component
                    operator: In
                    values:
                    - elasticsearch
                  - key: role
                    operator: In
                    values:
                    - ingest
                topologyKey: kubernetes.io/hostname
              weight: 100
        containers:
        - env:
          - name: ES_JAVA_OPTS
            value: -Xms4g -Xmx4g
          name: elasticsearch
          resources:
            limits:
              memory: 8Gi
            requests:
              cpu: "2"
              memory: 8Gi
        securityContext:
          fsGroup: 1000
          runAsGroup: 1000
          runAsUser: 1000
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 102Gi
        storageClassName: elastic-sc
      status: {}
```

* Logs:
```
{"log.level":"info","@timestamp":"2021-09-14T17:33:59.825Z","log.logger":"elasticsearch-controller","message":"Starting reconciliation run","service.version":"1.4.1+512d5431","service.type":"eck","ecs.version":"1.4.0","iteration":16458,"namespace":"es-lectest12","es_name":"lectest12"}
{"log.level":"info","@timestamp":"2021-09-14T17:34:00.230Z","log.logger":"driver","message":"Deleting StatefulSet to account for resized PVCs, it will be recreated automatically","service.version":"1.4.1+512d5431","service.type":"eck","ecs.version":"1.4.0","namespace":"es-lectest12","es_name":"lectest12","statefulset_name":"lectest12-es-ingest"}
{"log.level":"info","@timestamp":"2021-09-14T17:34:00.251Z","log.logger":"elasticsearch-controller","message":"Ending reconciliation run","service.version":"1.4.1+512d5431","service.type":"eck","ecs.version":"1.4.0","iteration":16458,"namespace":"es-lectest12","es_name":"lectest12","took":0.426004365}
{"log.level":"error","@timestamp":"2021-09-14T17:34:00.251Z","log.logger":"controller","message":"Reconciler error","service.version":"1.4.1+512d5431","service.type":"eck","ecs.version":"1.4.0","controller":"elasticsearch-controller","name":"lectest12","namespace":"es-lectest12","error":"StatefulSet recreation: Pod \"lectest12-es-ingest-0\" is invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds` or `spec.tolerations` (only additions to existing tolerations)\n  core.PodSpec{\n  \t... // 10 identical fields\n  \tAutomountServiceAccountToken: &false,\n  ",\n  \tSecurityContext: &core.PodSecurityContext{\n  \t\t... // 11 identical fields\n  \t\tFSGroupChangePolicy: nil,\n  \t\tSysctls:             nil,\n- \t\tSeccompProfile:      nil,\n+ \t\tSeccompProfile:      &core.SeccompProfile{Type: \"RuntimeDefault\"},\n  \t},\n  \tImagePullSecrets: nil,\n        \"lectest12-es-ingest-0\",\n  \t... // 15 identical fields\n  }\n","errorCauses":[{"error":"StatefulSet recreation: Pod \"lectest12-es-ingest-0\" is invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds` or `spec.tolerations` (only additions to existing tolerations)\n  core.PodSpec{\n  \t... // 10 identical fields\n  \tAutomountServiceAccountToken: &false,\n  \tNodeName:                     ,\n  \tSecurityContext: &core.PodSecurityContext{\n  \t\t... // 11 identical fields\n  \t\tFSGroupChangePolicy: nil,\n  \t\tSysctls:             nil,\n- \t\tSeccompProfile:      nil,\n+ \t\tSeccompProfile:      &core.SeccompProfile{Type: \"RuntimeDefault\"},\n  \t},\n  \tImagePullSecrets: nil,\n  \tHostname:         \"lectest12-es-ingest-0\",\n  \t... // 15 identical fields\n  }\n"}],"error.stack_trace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:246\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:218\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:197\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.14/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.14/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.14/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.14/pkg/util/wait/wait.go:90"}
```

**Comment by thbkrkr** [comment]
I don't know if it could be related but your manifest is suspicious. It doesn't look like a manifest to apply but rather the output of `kubectl es lectest12 -o yaml`. This should not be the problem here but why?

The manifest you shared is invalid for two reasons:
- The Elasticsearch "lectest12" is invalid: spec.http.service.metadata: Invalid value: "null": spec.http.service.metadata in body must be of type object: "null"
- The Elasticsearch "lectest12" is invalid: spec.version: Required value `spec.version` is a required value.

The error `spec: Forbidden: pod updates may not change fields other than` should be a sign that you are updating something else than `volumeClaimTemplates[0].spec.resources.requests.storage`. 

Could you double-check on your side? What are you using to deploy your Elasticsearch resource?
Could you also share the output of `kubectl get sc elastic-sc -o yaml`?

I tried but I couldn't reproduce your issue on k8s `v1.19.12-gke.210` with the manifest below which is almost yours.
Note that I commented the `storageClassName` to use the default `standard` storageClass which allows volume expansion.
<details>
<summary>elasticsearch.yml</summary>

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  annotations:
    common.k8s.elastic.co/controller-version: 1.4.1
    elasticsearch.k8s.elastic.co/cluster-uuid: oOEtkqwRQWumqaKOv5ypPw
  name: lectest12
  #namespace: es-lectest12
spec:
  auth: {}
  http:
    service:
      metadata:
      spec: {}
    # tls:
    #   certificate:
    #     secretName: lectest12-sec-elasticdb
  #image: elasticsearch/elasticsearch:7.10.0
  version: 7.10.0
  nodeSets:
  - config:
      node.data: false
      node.ingest: false
      node.master: true
      node.store.allow_mmap: false
    count: 3
    name: master
    podTemplate:
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: failure-domain.beta.kubernetes.io/zone
                  operator: Exists
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: component
                    operator: In
                    values:
                    - elasticsearch
                  - key: role
                    operator: In
                    values:
                    - master
                topologyKey: kubernetes.io/hostname
              weight: 100
        containers:
        - env:
          - name: ES_JAVA_OPTS
            value: -Xms1g -Xmx1g
          name: elasticsearch
          resources:
            limits:
              memory: 2Gi
            requests:
              cpu: "2"
              memory: 2Gi
        securityContext:
          fsGroup: 1000
          runAsGroup: 1000
          runAsUser: 1000
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        #storageClassName: elastic-sc
      status: {}
  - config:
      node.data: true
      node.ingest: false
      node.master: false
      node.store.allow_mmap: false
    count: 3
    name: data
    podTemplate:
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: failure-domain.beta.kubernetes.io/zone
                  operator: Exists
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: component
                    operator: In
                    values:
                    - elasticsearch
                  - key: role
                    operator: In
                    values:
                    - data
                topologyKey: kubernetes.io/hostname
              weight: 100
        containers:
        - env:
          - name: ES_JAVA_OPTS
            value: -Xms4g -Xmx4g
          name: elasticsearch
          resources:
            limits:
              memory: 8Gi
            requests:
              cpu: "2"
              memory: 8Gi
        securityContext:
          fsGroup: 1000
          runAsGroup: 1000
          runAsUser: 1000
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        #storageClassName: elastic-sc
      status: {}
  - config:
      node.data: false
      node.ingest: false
      node.master: false
      node.store.allow_mmap: false
    count: 2
    name: client
    podTemplate:
      metadata:
        labels:
          name: lectest12-client
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: failure-domain.beta.kubernetes.io/zone
                  operator: Exists
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: component
                    operator: In
                    values:
                    - elasticsearch
                  - key: role
                    operator: In
                    values:
                    - client
                topologyKey: kubernetes.io/hostname
              weight: 100
        containers:
        - env:
          - name: ES_JAVA_OPTS
            value: -Xms4g -Xmx4g
          name: elasticsearch
          resources:
            limits:
              memory: 8Gi
            requests:
              cpu: "2"
              memory: 8Gi
        securityContext:
          fsGroup: 1000
          runAsGroup: 1000
          runAsUser: 1000
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        #storageClassName: elastic-sc
      status: {}
  - config:
      node.data: true
      node.ingest: true
      node.master: false
      node.store.allow_mmap: false
    count: 1
    name: ingest
    podTemplate:
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: failure-domain.beta.kubernetes.io/zone
                  operator: Exists
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: component
                    operator: In
                    values:
                    - elasticsearch
                  - key: role
                    operator: In
                    values:
                    - ingest
                topologyKey: kubernetes.io/hostname
              weight: 100
        containers:
        - env:
          - name: ES_JAVA_OPTS
            value: -Xms4g -Xmx4g
          name: elasticsearch
          resources:
            limits:
              memory: 8Gi
            requests:
              cpu: "2"
              memory: 8Gi
        securityContext:
          fsGroup: 1000
          runAsGroup: 1000
          runAsUser: 1000
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 112Gi
        #storageClassName: elastic-sc
      status: {}
```
</details>

**Comment by reddymh** [comment]
@thbkrkr Just tested with the below CR and created the elasticsearch object and tried increasing only storage from 20GB to 25GB and getting the below forbidden error.

**Error Logs:**

```
{"log.level":"info","@timestamp":"2021-09-15T18:41:59.302Z","log.logger":"elasticsearch-controller","message":"Starting reconciliation run","service.version":"1.4.1+512d5431","service.type":"eck","ecs.version":"1.4.0","iteration":18176,"namespace":"es-lectest12","es_name":"test"}
{"log.level":"info","@timestamp":"2021-09-15T18:41:59.615Z","log.logger":"driver","message":"Deleting StatefulSet to account for resized PVCs, it will be recreated automatically","service.version":"1.4.1+512d5431","service.type":"eck","ecs.version":"1.4.0","namespace":"es-lectest12","es_name":"test","statefulset_name":"test-es-data"}
{"log.level":"info","@timestamp":"2021-09-15T18:41:59.634Z","log.logger":"elasticsearch-controller","message":"Ending reconciliation run","service.version":"1.4.1+512d5431","service.type":"eck","ecs.version":"1.4.0","iteration":18176,"namespace":"es-lectest12","es_name":"test","took":0.331366287}
{"log.level":"error","@timestamp":"2021-09-15T18:41:59.634Z","log.logger":"controller","message":"Reconciler error","service.version":"1.4.1+512d5431","service.type":"eck","ecs.version":"1.4.0","controller":"elasticsearch-controller","name":"test","namespace":"es-lectest12","error":"StatefulSet recreation: Pod \"test-es-data-0\" is invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds` or `spec.tolerations` (only additions to existing tolerations)\n  core.PodSpec{\n  \t... // 10 identical fields\n  \tAutomountServiceAccountToken: &false,\n  \tSecurityContext: &core.PodSecurityContext{\n  \t\t... // 11 identical fields\n  \t\tFSGroupChangePolicy: nil,\n  \t\tSysctls:             nil,\n- \t\tSeccompProfile:      nil,\n+ \t\tSeccompProfile:      &core.SeccompProfile{Type: \"RuntimeDefault\"},\n  \t},\n  \tImagePullSecrets: nil,\n  \tHostname:         \"test-es-data-0\",\n  \t... // 15 identical fields\n  }\n","errorCauses":[{"error":"StatefulSet recreation: Pod \"test-es-data-0\" is invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds` or `spec.tolerations` (only additions to existing tolerations)\n  core.PodSpec{\n  \t... // 10 identical fields\n  \tAutomountServiceAccountToken: &false,\n  \tSecurityContext: &core.PodSecurityContext{\n  \t\t... // 11 identical fields\n  \t\tFSGroupChangePolicy: nil,\n  \t\tSysctls:             nil,\n- \t\tSeccompProfile:      nil,\n+ \t\tSeccompProfile:      &core.SeccompProfile{Type: \"RuntimeDefault\"},\n  \t},\n  \tImagePullSecrets: nil,\n  \tHostname:         \"test-es-data-0\",\n  \t... // 15 identical fields\n  }\n"}],"error.stack_trace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:246\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:218\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:197\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.14/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.14/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.14/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.14/pkg/util/wait/wait.go:90"}
```

**elasticsearch-cr.yaml**
```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: test
  namespace: es-lectest12
spec:
  version: 7.10.0
  http:
    tls:
      certificate:
        secretName: lectest12-sec-elasticdb
  image: e-ppsc-docker-virtual.docker.lowes.com/elasticsearch/elasticsearch:7.10.0
  nodeSets:
  - name: master
    count: 1
    podTemplate:
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: failure-domain.beta.kubernetes.io/zone
                  operator: Exists
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: component
                    operator: In
                    values:
                    - elasticsearch
                  - key: role
                    operator: In
                    values:
                    - master
                topologyKey: kubernetes.io/hostname
              weight: 100
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value:  -Xms1g -Xmx1g
          resources:
            requests:
              memory: 2Gi
              cpu: 200m
            limits:
              memory: 3Gi
        securityContext:
          runAsGroup: 1000
          runAsUser: 1000
          fsGroup: 1000
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: elastic-sc
    config:
      node.store.allow_mmap: false
      node.master: true
      node.data: false
      node.ingest: false
  - name: data
    count: 1
    podTemplate:
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: failure-domain.beta.kubernetes.io/zone
                  operator: Exists
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: component
                    operator: In
                    values:
                    - elasticsearch
                  - key: role
                    operator: In
                    values:
                    - data
                topologyKey: kubernetes.io/hostname
              weight: 100
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms1g -Xmx1g
          resources:
            requests:
              memory: 2Gi
              cpu: 200m
            limits:
              memory: 3Gi
        securityContext:
          runAsGroup: 1000
          runAsUser: 1000
          fsGroup: 1000 
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: elastic-sc
    config:
      node.store.allow_mmap: false
      node.master: false
      node.data: true
      node.ingest: false
  - name: client
    count: 1
    podTemplate:
      metadata: 
        labels:
          name: test-client
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: failure-domain.beta.kubernetes.io/zone
                  operator: Exists
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: component
                    operator: In
                    values:
                    - elasticsearch
                  - key: role
                    operator: In
                    values:
                    - client
                topologyKey: kubernetes.io/hostname
              weight: 100
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms1g -Xmx1g
          resources:
            requests:
              memory: 2Gi
              cpu: 200m
            limits:
              memory: 3Gi
        securityContext:
          runAsGroup: 1000
          runAsUser: 1000
          fsGroup: 1000
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: elastic-sc
    config:
      node.store.allow_mmap: false
      node.master: false
      node.data: false
      node.ingest: false
  - name: ingest
    count: 1
    podTemplate:
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: failure-domain.beta.kubernetes.io/zone
                  operator: Exists
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: component
                    operator: In
                    values:
                    - elasticsearch
                  - key: role
                    operator: In
                    values:
                    - ingest
                topologyKey: kubernetes.io/hostname
              weight: 100
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms1g -Xmx1g
          resources:
            requests:
              memory: 2Gi
              cpu: 200m
            limits:
              memory: 3Gi
        securityContext:
          runAsGroup: 1000
          runAsUser: 1000
          fsGroup: 1000 
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: elastic-sc
    config:
      node.store.allow_mmap: false
      node.master: false
      node.data: true
      node.ingest: true
```

**Storage Class Yaml File:**
```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  creationTimestamp: "2021-07-22T06:51:17Z"
  managedFields:
  - apiVersion: storage.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:allowVolumeExpansion: {}
      f:parameters:
        .: {}
        f:csi.storage.k8s.io/fstype: {}
        f:storagepolicyname: {}
      f:provisioner: {}
      f:reclaimPolicy: {}
      f:volumeBindingMode: {}
    manager: OpenAPI-Generator
    operation: Update
    time: "2021-07-22T06:51:17Z"
  name: elastic-sc
  resourceVersion: "42180042"
  selfLink: /apis/storage.k8s.io/v1/storageclasses/elastic-sc
  uid: 2bafe8fb-58f5-4b97-99ca-59666191945f
parameters:
  csi.storage.k8s.io/fstype: ext4
  storagepolicyname: k8s
provisioner: csi.vsphere.vmware.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```

**Comment by thbkrkr** [comment]
Hi, I still cannot reproduce your issue. I wonder if it could be specific to your Kubernetes distribution or your storage class?

Could you test to update the requested storage with this simple manifest?

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: test
spec:
  version: 7.15.2
  nodeSets:
  - name: master
    count: 1
    config:
      node.store.allow_mmap: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: elastic-sc
```

Do you have other storage classes, which support volume expansion, available in your k8s cluster? If so, could you test with each of them?
