### ISSUE TITLE
Update cert-manager.io examples in the doc and recipes

### ISSUE THREAD

**Issue by thbkrkr** [elastic/cloud-on-k8s#4845]
Created from #4843.

### Bump to cert-manager.io/v1

We have a mix of cert-manager.io versions in the doc and recipes. Let's use `cert-manager.io/v1` everywhere.  

```java
> grep cert-manager.io/v -r
config/recipes/istio-gateway/04-certificates.yaml:apiVersion: cert-manager.io/v1alpha2
config/recipes/istio-gateway/04-certificates.yaml:apiVersion: cert-manager.io/v1alpha2
config/recipes/istio-gateway/02-prereq-selfsigning-issuer.yaml:apiVersion: cert-manager.io/v1alpha2
config/recipes/gclb/00-prereq-cluster-issuer.yaml:apiVersion: cert-manager.io/v1
config/recipes/traefik/01-certificate.yaml:apiVersion: cert-manager.io/v1alpha2
config/recipes/traefik/00-prereq-cluster-issuer.yaml:apiVersion: cert-manager.io/v1alpha2
docs/orchestrating-elastic-stack-applications/security/custom-http-certificate.asciidoc:apiVersion: cert-manager.io/v1alpha2
docs/orchestrating-elastic-stack-applications/security/custom-http-certificate.asciidoc:apiVersion: cert-manager.io/v1alpha2
docs/operating-eck/webhook.asciidoc:apiVersion: cert-manager.io/v1beta1
```

### Empty issuer DN not allowed in X509Certificates

As reported in #4843, in the above examples the selfSigned issuer generates a certificate that, while tolerated by Chromium for example, is rejected as malformed by Java, due to lack of an issuer DN. We could address that at the same time by setting `subject.organizations`.

```yaml
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: quickstart-es-cert-v1
spec:
  isCA: true
  dnsNames:
    - quickstart-es-http
    - quickstart-es-http.default.svc
    - quickstart-es-http.default.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: quickstart-es-cert-v1
  subject:
    organizations:
      - "quickstart"
```

### Show a more complex example with a separate CA that can be used to sign multiple clusters certs

#4843 shows a complex example with a separate CA that can be used to sign multiple clusters certs. 
We shouldn't update all the examples with this, but maybe at least one? If yes, which one?
