### ISSUE TITLE
Elastic Agents Unhealthy

### ISSUE THREAD

**Issue by ruler501** [elastic/cloud-on-k8s#4880]
## Bug Report
**What did you do?**

Deployed elastic agent and fleet server instances.

**What did you expect to see?**
Nodes be restarted as needed to stay healthy

**What did you see instead? Under which circumstances?**
When I check usually at least half the elastic agent pods are marked as unhealthy in the fleet dashboard.

**Environment**

* ECK version:

	Tried on v1.7.0 and v1.8.0

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* Cloud: GKE

	
	for each of them please give us the version you are using
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c70
73412212", GitTreeState:"archive", BuildDate:"1980-01-01T00:00:00Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"l
inux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4-gke.301", GitCommit:"66446d1224e45ac4e1738770
1d2e2364e3ed4b8c", GitTreeState:"clean", BuildDate:"2021-08-24T05:19:21Z", GoVersion:"go1.16.6b7", Compiler:"gc", Pla
tform:"linux/amd64"}
```

* Resource definition:
```
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  namespace: kube-logging
  name: fleet-server
spec:
  version: 7.15.0
  kibanaRef:
    name: kibana
    namespace: kube-logging
  elasticsearchRefs:
    - name: elasticsearch
      namespace: kube-logging
  mode: fleet
  fleetServerEnabled: true
  deployment:
    replicas: 1
    podTemplate:
      spec:
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0
        serviceAccountName: fleet-server
        containers:
          - name: agent
            resources:
              limits:
                memory: 1024Mi
                cpu: 1000m
              requests:
                memory: 1024Mi
                cpu: 500m
---
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  namespace: kube-logging
  name: elastic-agent
spec:
  version: 7.15.0
  kibanaRef:
    name: kibana
    namespace: kube-logging
  fleetServerRef:
    name: fleet-server
    namespace: kube-logging
  mode: fleet
  daemonSet:
    podTemplate:
      spec:
        automountServiceAccountToken: true
        serviceAccountName: elastic-agent
        securityContext:
          runAsUser: 0
        containers:
          - name: agent
            resources:
              limits:
                memory: 300Mi
                cpu: 500m
              requests:
                memory: 300Mi
                cpu: 100m
            volumeMounts:
            - mountPath: /var/lib/docker/containers
              name: varlibdockercontainers
            - mountPath: /var/log/containers
              name: varlogcontainers
            - mountPath: /var/log/pods
              name: varlogpods
        volumes:
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
        - name: varlogpods
          hostPath:
            path: /var/log/pods
```
