### ISSUE TITLE
Imbalanced Storage Allocation Across Zone-Aware Cluster

### ISSUE THREAD

**Issue by TheRealDwright** [elastic/cloud-on-k8s#4881]
## Bug Report
**What did you do?**

Deployed a zone-aware cluster using ECK.

**What did you expect to see?**

Shards are evenly distributed among nodes, with storage capacity being (somewhat) balanced across the cluster.

**What did you see instead? Under which circumstances?**

One node is favoured for storing shards and is triggering high disk usage alerts with a lot of excess capacity on other nodes. There are 12 data nodes in the cluster, 11 are using approximately 50% disk and one is sitting around 85%. After shards are manually rerouted, it is immediately filled back up.

**Environment**

* ECK version:

1.71.0

* Kubernetes information:

	* Cloud: EKS
	
	for each of them please give us the version you are using
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T21:16:14Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"
```

* Resource definition:
```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: es3
spec:
  version: 7.13.0
  image: docker.elastic.co/elasticsearch/elasticsearch
  nodeSets:
  - name: master-a # this is repeated for each AZ (us-west-2b + us-west-2c)
    count: 1
    config:
      node.roles: ["master"]
      node.attr.zone: us-west-2a
      cluster.routing.allocation.awareness.attributes: k8s_node_name,zone
    podTemplate:
      spec:
        containers:
          - name: elasticsearch
            resources:
              requests:
                memory: 30Gi
                cpu: 2
              limits:
                memory: 30Gi
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: topology.kubernetes.io/zone
                  operator: In
                  values:
                  - us-west-2a
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: gp3-xfs
  - name: data-a # this is repeated for each AZ (us-west-2b + us-west-2c)
    count: 4
    config:
      node.roles: ["data", "ingest"]
      node.attr.zone: us-west-2a
      cluster.routing.allocation.awareness.attributes: k8s_node_name,zone
    podTemplate:
      spec:
        containers:
          - name: elasticsearch
            resources:
              requests:
                memory: 50Gi
                cpu: 8
              limits:
                memory: 50Gi
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: topology.kubernetes.io/zone
                  operator: In
                  values:
                  - us-west-2a
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 16384Gi
        storageClassName: gp3-16k-iops

```

* Logs:
```
N/A
```
Additional Info:

The graph below shows storage allocation by node, I performed a manual reroute of some large shards to other nodes, and one was immediately filled back up.

<img width="2119" alt="Screen Shot 2021-09-27 at 10 14 17 am" src="https://user-images.githubusercontent.com/15135979/134829480-1f608893-b9c4-42a6-9586-2d1b7038957e.png">
