### ISSUE TITLE
Fleet can't connect to Kibana

### ISSUE THREAD

**Issue by bwright-bronga** [elastic/cloud-on-k8s#4902]
## Bug Report
**What did you do?**
Trying to follow directions to deploy fleet elastic agent.  The agent is throwing errors.  We were following https://www.elastic.co/guide/en/cloud-on-k8s/1.8/k8s-elastic-agent-fleet-quickstart.html

**What did you expect to see?**
Fleet Agent to successfully run

**What did you see instead? Under which circumstances?**
No errors / successful connection to Kibana (and a clean startup)

**Environment**

* ECK version:v 1.8.0

* Kubernetes information:
```
	insert any information about your Kubernetes environment that could help us:
	* On premise ? n/a
	* Cloud: GKE / EKS / AKS ? GKE
	* Kubernetes distribution: Openshift / Rancher / PKS ? n/a
	
	for each of them please give us the version you are using
```
$ kubectl version
```

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeStat
e:"clean", BuildDate:"2021-09-16T02:43:21Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.12-gke.2101", GitCommit:"c8d75ae17b4628860e58bcdbe73c1f29dae62361", 
GitTreeState:"clean", BuildDate:"2021-08-18T18:42:22Z", GoVersion:"go1.15.13b5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.19) exceeds the supported minor version skew of +/-1
```
* Resource definition:
```
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: elk-fleet-server
  namespace: default
spec:
  version: 7.14.0
  kibanaRef:
    name: elk
  elasticsearchRefs:
  - name: elk
  mode: fleet
  fleetServerEnabled: true
  http:
    service:
      metadata: {}
      spec: {}
    tls:
      certificate:
        secretName: internal-exiger-com-wildcard
  deployment:
    replicas: 1
    podTemplate:
      spec:
        serviceAccountName: elk-elastic-agent
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0
---
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: elk-elastic-agent
  namespace: default
spec:
  version: 7.14.0
  kibanaRef:
    name: elk
  fleetServerRef:
    name: elk-fleet-server
  mode: fleet
  daemonSet:
    podTemplate:
      spec:
        serviceAccountName: elk-elastic-agent
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elk-elastic-agent
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - pods
  verbs:
  - get
  - watch
  - list
- apiGroups: ["coordination.k8s.io"]
  resources:
  - leases
  verbs:
  - get
  - create
  - update
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elk-elastic-agent
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: elk-elastic-agent
subjects:
- kind: ServiceAccount
  name: elk-elastic-agent
  namespace: default
roleRef:
  kind: ClusterRole
  name: elk-elastic-agent
  apiGroup: rbac.authorization.k8s.io
```

* Logs:
```
kubectl logs elk-fleet-server-agent-c86c85d7b-hbl8w
Performing setup of Fleet in Kibana

Kibana Fleet setup failed: http POST request to https://elk-kb-http.default.svc:5601/api/fleet/setup fails: fail to execute the HTTP POST request: Post "https://elk-kb-http.default.svc:5601/api/fleet/setup": x509: certificate is valid for example.com, *.example.com, not elk-kb-http.default.svc. Response: 
Kibana Fleet setup failed: http POST request to https://elk-kb-http.default.svc:5601/api/fleet/setup fails: fail to execute the HTTP POST request: Post "https://elk-kb-http.default.svc:5601/api/fleet/setup": x509: certificate is valid for example.com, *.example, not elk-kb-http.default.svc. Response: 
```

Looks like
```
  kibanaRef:
    name: elk
```
is being discovered and used, so it tries to use the internal service: `elk-kb-http.default.svc`.  The issue is that we publicly expose it via ingress with TLS passthrough, so the certificate on the Pods is for a public dns record `kibana.example.com`.  

Is there a way to either:
(a) allow insecure certificates for the connect from fleet agent to Kibana or
(b) update so kibanaRef resolves to `kibana.example.com`

Open to other solutions as well

**Comment by david-kow** [comment]
Hi @bwright-bronga, thanks for your report.

I'd suggest going for option (b), out of the two you've suggested. The way to do it today (`1.8.0`) is cumbersome, but an [improvement](https://github.com/elastic/cloud-on-k8s/pull/4889) is already on track for `1.9.0`.

The way to achieve it today is described in https://github.com/elastic/cloud-on-k8s/issues/4790#issuecomment-911826419, but just to reiterate:

You need to set the correct hosts and ignore ECK provided CA (so that well-known CAs will be looked up instead). 

```yaml
 containers:
        - name: agent
          env:
          - name: FLEET_SERVER_ELASTICSEARCH_HOST
            value: https://elasticsearch.example.com:9200
          - name: KIBANA_FLEET_HOST
            value: https://kibana.example.com:5601
          volumeMounts: 
          - mountPath: /usr/share/elastic-agent/fleet-setup-base.yml
            name: fleet-setup-config # this volume is added by ECK, we only need to change the mount
            subPath: fleet-setup.yml
          command:
          - /usr/bin/env
          - bash
          - -c
          - |
            #!/usr/bin/env bash
            set -e
            grep -v "ca: /mnt/elastic-internal/.*\(elasticsearch\|kibana\).*" fleet-setup-base.yml | grep -v "host: .*" > fleet-setup.yml
            /usr/bin/tini -- /usr/local/bin/docker-entrypoint -e
```

I've also added an [issue](https://github.com/elastic/cloud-on-k8s/issues/4904) to improve our documentation around this. I'll close this for now, but please feel free to reopen if you run into any more issues or the workaround provided doesn't work for you.
