### ISSUE TITLE
Adding additional ES cluster validation

### ISSUE THREAD

**Issue by naemono** [elastic/cloud-on-k8s#5026]
## Proposal

We should add additional validation when creation Elasticsearch clusters, as currently we can create an invalid cluster with the following spec

```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: invalid-cluster-7-14-2-customer
  namespace: default
spec:
  version: 7.14.2
  nodeSets:
  - name: hot1
    count: 1
    config:
      node.roles: ["master", "data_hot", "ingest"]
      node.store.allow_mmap: false
  - name: warm1
    count: 1
    config:
      node.roles: ["master", "data_warm", "ingest"]
      node.store.allow_mmap: false
```
which will never become healthy because of
```
root@testing:/# curl -su elastic:--password-- -k https://node0:9200/_cluster/health | jq '{"status":.status, "unassigned_shards":.unassigned_shards}'
{
  "status": "red",
  "unassigned_shards": 1
}
```

I do not have an exhaustive list of invalid configurations, but I'm aware that system indices need to live on data_content (or data if the node doesn't have any other data_* roles), which aligns with https://www.elastic.co/guide/en/elasticsearch/reference/7.15/modules-node.html#node-roles, which states

```
If you set node.roles, ensure you specify every node role your cluster needs. Every cluster requires the following node roles:

* master
* data_content and data_hot OR data
```

Unfortunately, this validation differs for ES versions, which could certainly complicate the validation logic, but it would prevent these types of misconfigurations from a customer perspective.
