### ISSUE TITLE
Update APM Server examples/samples for 8.0.0

### ISSUE THREAD

**Issue by david-kow** [elastic/cloud-on-k8s#5059]
Standalone APM Server examples should be updated with a change to Kibana config as below.

```yaml
xpack.fleet.packages:
- name: apm
  version: latest 
```

This is due to the fact APM Server will no longer create apm indices/templates and instead, templates will be installed during APM integration installation. The configuration above makes sure that Kibana will install it automatically during startup.
