### ISSUE TITLE
TestFleetCustomLogsIntegrationRecipe is failing in 7.15.2

### ISSUE THREAD

**Issue by thbkrkr** [elastic/cloud-on-k8s#5105]
```
=== RUN   TestFleetCustomLogsIntegrationRecipe/ES_data_should_pass_validations
Retries (30m0s timeout): ..............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
    step.go:43: 
        	Error Trace:	utils.go:87
        	Error:      	Received unexpected error:
        	            	elasticsearch client failed for https://elasticsearch-d66t-es-http.e2e-saklj-mercury.svc:9200/_data_stream/logs-elastic_agent-default: 404 Not Found: {Status:404 Error:{CausedBy:{Reason: Type:} Reason:no such index [logs-elastic_agent-default] Type:index_not_found_exception RootCause:[{Reason:no such index [logs-elastic_agent-default] Type:index_not_found_exception}]}}
        	Test:       	TestFleetCustomLogsIntegrationRecipe/ES_data_should_pass_validations
{"log.level":"error","@timestamp":"2021-12-01T17:58:42.511Z","message":"stopping early","service.version":"0.0.0-SNAPSHOT+00000000","service.type":"eck","ecs.version":"1.4.0","error":"test failure","error.stack_trace":"github.com/elastic/cloud-on-k8s/test/e2e/test/helper.RunFile\n\t/go/src/github.com/elastic/cloud-on-k8s/test/e2e/test/helper/yaml.go:162\ngithub.com/elastic/cloud-on-k8s/test/e2e/agent.runAgentRecipe\n\t/go/src/github.com/elastic/cloud-on-k8s/test/e2e/agent/recipes_test.go:226\ngithub.com/elastic/cloud-on-k8s/test/e2e/agent.TestFleetCustomLogsIntegrationRecipe\n\t/go/src/github.com/elastic/cloud-on-k8s/test/e2e/agent/recipes_test.go:160\ntesting.tRunner\n\t/usr/local/go/src/testing/testing.go:1259"}
    --- FAIL: TestFleetCustomLogsIntegrationRecipe/ES_data_should_pass_validations (1800.00s)
```

Elastic Agent logs:

```
Performing setup of Fleet in Kibana                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     

21 x Kibana Fleet setup failed: http POST request to https://kibana-97f6-kb-http.e2e-mercury.svc:5601/api/fleet/setup fails: Package policy is invalid: inputs.logfile.streams.log.log.vars.paths: Log file path is required: <nil>. Response: {"statusCode":400,"error":"Bad Request","message":"Package policy is invalid: inputs.logfile.streams.log.log.vars.paths: Log file path is required"}

Error: http POST request to https://kibana-97f6-kb-http.e2e-mercury.svc:5601/api/fleet/setup fails: Package policy is invalid: inputs.logfile.streams.log.log.vars.paths: Log file path is required: <nil>. Response: {"statusCode":400,"error":"Bad Request","message":"Pac
kage policy is invalid: inputs.logfile.streams.log.log.vars.paths: Log file path is required"}                                                                                                                                                                              
For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/7.15/fleet-troubleshooting.html 
```


I did not see that it was to be expected.
Relates to https://github.com/elastic/cloud-on-k8s/pull/4873#issuecomment-927792858.
Relates to https://github.com/elastic/kibana/issues/113400.

**Comment by kpollich** [comment]
@thbkrkr - can you clarify the impact this has on ECK for now? Is this is a blocker in any way for now? With 7.16 shipping next week and this issue being fixed in that release, wondering if it's possible to simply punt here for now. 

Also, to close the loop a bit on our discussion over in https://github.com/elastic/kibana/issues/113400 (feel that it's better to move discussion to an open issue here), we do have an issue that causes preconfigured `Custom Logs` integration policies to fail to create in 7.15.2. We've been unable to find a root cause so far, but are continuing to investigate. We'd like to timebox these efforts if possible with 7.16 so close on the horizon. 

For a minimal test case, add the following to `kibana.yml` in 7.15.2, start up Kibana, and load the `/app/fleet` page:

```yml
xpack.fleet.packages:
  - name: log
    version: latest
xpack.fleet.agentPolicies:
  - name: Custom Logs Policy
    id: custom-logs-123
    namespace: default
    package_policies:
      - package:
          name: log
        name: log-1
        inputs:
          - type: logfile
            enabled: true
            streams:
              - data_stream:
                  dataset: log.log
                enabled: true
                vars:
                  - name: paths
                    value:
                      - /var/log/my.log
```

You should receive the following error:

![image](https://user-images.githubusercontent.com/6766512/144645576-67b05204-4936-4205-8a67-5f9d138fb95a.png)
 
We're installing `log-0.4.6` here, which can be referenced in EPR here: https://epr.elastic.co/package/log/0.4.6/. Adding custom logs via the Fleet UI is still possible, only preconfiguration fails. 

Interestingly enough, I attempted to reproduce this in 7.15.2 with the `nginx` integration as well and did not encounter an error. `nginx` also includes a `paths` variable (see https://epr.elastic.co/package/nginx/1.2.0/), so I'm noot sure why custom logs is broken while nginx is functional, but maybe this will be a helpful clue on our way to a root cause. Sample `kibana.yml` below. 

```yml
xpack.fleet.packages:
  - name: nginx
    version: latest
xpack.fleet.agentPolicies:
  - name: Preconfigured Nginx
    id: preconfigured-nginx-123
    namespace: default
    package_policies:
      - package:
          name: nginx
        name: nginx-1
        inputs:
          - type: logfile
            enabled: true
            streams:
              - data_stream:
                  dataset: nginx.access
                enabled: true 
                vars:
                  - name: paths
                    value:
                      - /var/log/nginx/access.log*

```

**Comment by thbkrkr** [comment]
The impact on ECK is minor. This is not a blocker.

Le ven. 3 déc. 2021, 19:09, Kyle Pollich ***@***.***> a
écrit :

**Comment by thbkrkr** [comment]
Closing as we decided to ignore `TestFleetCustomLogsIntegrationRecipe` in `7.15.2` because the underlying issue will not be resolved. We have pinned the test to `7.15.1` (#5108) and will skip ahead to` 7.16.0` (#5141).

**Comment by barkbay** [comment]
I'm reopening this issue as [we have the same error with `8.8.0`](https://github.com/elastic/cloud-on-k8s/pull/6864#issuecomment-1569534530) :

```
[2023-05-30T11:38:37.209+00:00][WARN ][plugins.fleet] PackagePolicyValidationError:
Package policy is invalid: inputs.logfile.streams.log.logs.vars.paths:
Log file path is required
inputs.logfile.streams.log.logs.vars.data_stream.dataset: Dataset name is required
    at validatePackagePolicyOrThrow (/usr/share/kibana/node_modules/@kbn/fleet-plugin/server/services/package_policy.js:1197:13)
    at preconfigurePackageInputs (/usr/share/kibana/node_modules/@kbn/fleet-plugin/server/services/package_policy.js:1584:3)
    at /usr/share/kibana/node_modules/@kbn/fleet-plugin/server/services/preconfiguration.js:282:212
    at addPackageToAgentPolicy (/usr/share/kibana/node_modules/@kbn/fleet-plugin/server/services/agent_policy.js:776:53)
    at addPreconfiguredPolicyPackages (/usr/share/kibana/node_modules/@kbn/fleet-plugin/server/services/preconfiguration.js:282:53)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at ensurePreconfiguredPackagesAndPolicies (/usr/share/kibana/node_modules/@kbn/fleet-plugin/server/services/preconfiguration.js:219:7)
    at createSetupSideEffects (/usr/share/kibana/node_modules/@kbn/fleet-plugin/server/services/setup.js:86:7)
    at awaitIfPending (/usr/share/kibana/node_modules/@kbn/fleet-plugin/server/services/setup_utils.js:35:20)
    at /usr/share/kibana/node_modules/@kbn/fleet-plugin/server/plugin.js:285:9
```

Note that we have this new message: `inputs.logfile.streams.log.logs.vars.data_stream.dataset: Dataset name is required`

I tested various combinations including the one suggested [here](https://github.com/elastic/kibana/issues/113400#issuecomment-1421079676), without success:

```yaml
      package_policies:
      - id: system-1
        name: system-1
        package:
          name: system
      - inputs:
        - enabled: true
          streams:
          - data_stream:
              dataset: log.log
            enabled: true
            vars:
            - name: paths
              value: /var/log/containers/*${kubernetes.container.id}.log
            - name: custom
              value: |
                symlinks: true
                condition: ${kubernetes.namespace} == 'default'
          type: logfile
        name: log-1
        package:
          name: log
```

@kpollich may I ask for help from you or a member of your team? Thanks 🙇 

Note that this configuration works with `8.7.0`, I'm a bit surprised to have a breaking change in the API between 2 minor versions.
