### ISSUE TITLE
Elasticsearch Cluster very slow

### ISSUE THREAD

**Issue by rubenssoto** [elastic/cloud-on-k8s#5115]
Hello,

I made a elasticsearch cluster deploy using elastic operator, but the cluster performance are very strange, is very slow, the cluster is empty and I see slowness on index creation, to insert few rows.

```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-sandbox
  namespace: elastic-system
spec:
  http:
      tls:
        selfSignedCertificate:
          disabled: true
  version: 7.15.0
  nodeSets:
  - name: elasticsearch-master
    count: 2
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
        storageClassName: efs-sc
    config:
      node.master: true
      node.data: true
      node.ingest: false
      node.store.allow_mmap: false
    podTemplate:
      spec:
        securityContext:
          fsGroup: 0
          runAsUser: 1000
          runAsGroup: 0
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms10g -Xmx10g
          resources:
            requests:
              memory: 12Gi
              cpu: 3
            limits:
              cpu: 3
              memory: 12Gi
```

I'm having a lot of timeouts

{"type": "server", "timestamp": "2021-12-04T02:13:42,909Z", "level": "ERROR", "component": "o.e.x.m.e.l.LocalExporter", "cluster.name": "elasticsearch-sandbox", "node.name": "elasticsearch-sandbox-es-elasticsearch-master-0", "message": "failed to set monitoring pipeline [xpack_monitoring_6]", "cluster.uuid": "FlAFvLLaQh-AKMAUmoQm8Q", "node.id": "pmhUiMP1QwyND613CMOZoA" , 
"stacktrace": ["org.elasticsearch.cluster.metadata.ProcessClusterEventTimeoutException: failed to process cluster event (put-pipeline-xpack_monitoring_6) within 30s",
"at org.elasticsearch.cluster.service.MasterService$Batcher.lambda$onTimeout$0(MasterService.java:147) [elasticsearch-7.15.0.jar:7.15.0]",
"at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]",
"at org.elasticsearch.cluster.service.MasterService$Batcher.lambda$onTimeout$1(MasterService.java:146) [elasticsearch-7.15.0.jar:7.15.0]",
"at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:678) [elasticsearch-7.15.0.jar:7.15.0]",
"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]",
"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]",
"at java.lang.Thread.run(Thread.java:831) [?:?]"] }
