### ISSUE TITLE
[xpack.encryptedSavedObjects].keyRotation.decryptionOnlyKeys]: could not parse array value from json input

### ISSUE THREAD

**Issue by imarkvisser** [elastic/cloud-on-k8s#5138]
Hi,

I set a k8s secret containing the xpack.encryptedSavedObjects.keyRotation.decryptionOnlyKeys parameter;

```
xpack.encryptedSavedObjects.keyRotation.decryptionOnlyKeys: 32char_string_here
```

Kibana starts up but the pod errors out;
```
FATAL  Error: [config validation of [xpack.encryptedSavedObjects].keyRotation.decryptionOnlyKeys]: could not parse array value from json input
```

I tried putting it into a yaml array as such;

```
xpack.encryptedSavedObjects.keyRotation.decryptionOnlyKeys: 
  - 32char_string_here
```

This doesn't solve it either, any thoughts on how to make this work?

**Comment by thbkrkr** [comment]
Strange, putting it into a yaml array is the correct syntax. Do you have the same error?

Here's an example that works:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: z
spec:
  version: 7.15.2
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: z
spec:
  version: 7.15.2
  count: 1
  config:
    xpack.encryptedSavedObjects.keyRotation.decryptionOnlyKeys:
      - 012345678901234567890123456789xx
  elasticsearchRef:
    name: z
```
