### ISSUE TITLE
How to pass ldaps cert

### ISSUE THREAD

**Issue by gerardgorrion** [elastic/cloud-on-k8s#5147]
We propose the documentation to add the ldaps certificate to use realm ldaps secure settings.  
We are configuring th ldap configuration into elasticsearch and want to pass our ldap cert.

I think this should be a valid config:

```
      xpack.security.authc.realms:
        ldap:
          ldap1:
            order: 1
            url: "ldaps://dcname.corp:636"
            bind_dn: "bind_DN"
            secure_bind_password: xpack.security.authc.realms.ldap.ldap1.secure_bind_password
            user_search:
              base_dn: "base_DN"
              filter: "(sAMAccountName={0})"
            group_search:
              base_dn: "base_DN"
            ssl 
              certificate_authorities: [ "/usr/share/cert/xpack.security.authc.realms.ldap.ldap1.ssl.certificate_authorities" ]
              verification_mode: certificate
...
  secureSettings:
  - secretName: elasticsearch-es-ldap-conf
    entries:
    - key: xpack.security.authc.realms.ldap.ldap1.secure_bind_password
  - secretName: elasticsearch-es-ldap-conf
    entries:
    - key: xpack.security.authc.realms.ldap.ldap1.ssl.certificate_authorities
      path: /usr/share/cert 
```

Secret.yml
```
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-es-ldap-conf
  namespace: default
type: Opaque
data:
  xpack.security.authc.realms.ldap.ldap1.secure_bind_password: base64
  xpack.security.authc.realms.ldap.ldap1.ssl.certificate_authorities: base64code
```

But this configuration is no working, some idea?

* ECK version:

	eck verion 1.8

* Kubernetes information:

	* Cloud: AWS
	* Kubernetes distribution: EKS

```
$ kubectl version
Server Version: v1.19.13-eks-8df270
```

Thanks!

**Comment by pebrc** [comment]
```
      xpack.security.authc.realms:
        ldap:
          ldap1:
            order: 1
            url: "ldaps://dcname.corp:636"
            bind_dn: "bind_DN"
            secure_bind_password: xpack.security.authc.realms.ldap.ldap1.secure_bind_password
            user_search:
              base_dn: "base_DN"
              filter: "(sAMAccountName={0})"
            group_search:
              base_dn: "base_DN"
            ssl 
              certificate_authorities: [ "/usr/share/cert/xpack.security.authc.realms.ldap.ldap1.ssl.certificate_authorities" ]
              verification_mode: certificate
```
I believe you have to remove the line `secure_bind_password: xpack.security.authc.realms.ldap.ldap1.secure_bind_password` as this is supposed to come out of the Elasticsearch keystore but you are here setting it to the string `xpack.security.authc.realms.ldap.ldap1.secure_bind_password` which is certainly incorrect. See the [Elasticsearch docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/ldap-realm.html)

```
  - secretName: elasticsearch-es-ldap-conf
    entries:
    - key: xpack.security.authc.realms.ldap.ldap1.ssl.certificate_authorities
      path: /usr/share/cert 
```
This won't work. The `secureSettings` attribute's only purpose is to populate the Elasticsearch keystore. You just want to mount a file from a secret. Please use the `podTemplate` to mount the secret with the certificate authorities. See https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-customize-pods.html

Also I would ask you to continue the discussion in our [community forum](https://discuss.elastic.co/c/orchestration/eck/79) as we use GitHub exclusively for bug reports and feature requests. Thank you!
