### ISSUE TITLE
Allow users to provide the name pattern of Elasticsearch's transport certs commonName & otherName

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#5148]
When we generate Elasticsearch transport certificates, we set [both the x509 commonName *and* the Elasticsearch otherName extension](https://github.com/elastic/cloud-on-k8s/blob/9be005d2a4b6e26f98ff9c520ea53ae4d6cc9455/pkg/controller/elasticsearch/certificates/transport/csr.go#L79) to a [value that makes sense for us](https://github.com/elastic/cloud-on-k8s/blob/9be005d2a4b6e26f98ff9c520ea53ae4d6cc9455/pkg/controller/elasticsearch/certificates/transport/csr.go#L117): `<pod_name>.node.<cluster_name>.<namespace>.es.local`.

Currently the name pattern chosen here does not have any particular impact on Elasticsearch. Elasticsearch nodes uses that name to identify other nodes, so it is however important for all nodes to have a deterministic name.

Considering we don't offer a way for users to provide their own transport certs (they can provide a CA from which we generate the certs), it would make sense to allow users to customize the name pattern, similar to how they can customize subject alternative names.

Something like:

```yml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
  namespace: mynamespace
spec:
  version: 7.16.0
  transport:
    tls:
      # also used as otherName in Elasticsearch certs
      commonNamePattern: ${pod_name}.node.quickstart.cluster.mynamespace.namespace
      subjectAltNames:
      - ip: 1.2.3.4
      - dns: hulk.example.com
```

There are a few values we may consider templating  (so the user does not provide the exact value but rather a placeholder): pod name, Elasticsearch resource name, namespace name. For example: `${pod_name}.node.${elasticsearch_name}.cluster.${namespace_name}.namespace`. Meaning we'd have to figure out a nice templating mechanism: what's the format of those placeholders?

Another approach that may actually be enough for most users is to always prefix the given common name with the Pod name, since we do need one certificate per Pod anyway. In which case users could provide a suffix with no variable templating mechanism:

```yml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
  namespace: mynamespace
spec:
  version: 7.16.0
  transport:
    tls:
      # also used as otherName in Elasticsearch certs
      commonNameSuffix: ".node.quickstart.cluster.mynamespace.namespace" # operator will prepend the pod name here
      subjectAltNames:
      - ip: 1.2.3.4
      - dns: hulk.example.com
```
