### ISSUE TITLE
urgent: Not able to create the version of 7.16.0 or 7.16.1, in the same cluster we were able to deploy version 7.9.3

### ISSUE THREAD

**Issue by jagadeeshRS** [elastic/cloud-on-k8s#5159]
Not able to create a pod and getting errors out Init:CrashLoopBackOff

**Logs:** 
Containers:
  elasticsearch:
    Container ID:
    Image:          docker.elastic.co/elasticsearch/elasticsearch:7.16.0
    Image ID:
    Ports:          9200/TCP, 9300/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False

**Events:**
  Type     Reason                  Age               From                     Message
  ----     ------                  ----              ----                     -------
  Warning  FailedScheduling        70s               default-scheduler        0/4 nodes are available: 4 pod has unbound immediate PersistentVolumeClaims.
  Warning  FailedScheduling        68s               default-scheduler        0/4 nodes are available: 4 pod has unbound immediate PersistentVolumeClaims.
  Normal   Scheduled               65s               default-scheduler        Successfully assigned test4/elasticsearch-es-default-0 to aks-nodepool1-46068391-vmss00000k
  Normal   SuccessfulAttachVolume  54s               attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-a5eccad2-bd05-41ea-809a-f0be4f91ca1d"
  Normal   Pulling                 40s               kubelet                  Pulling image "docker.elastic.co/elasticsearch/elasticsearch:7.16.0"
  Normal   Pulled                  27s               kubelet                  Successfully pulled image "docker.elastic.co/elasticsearch/elasticsearch:7.16.0" in 13.342535102s
  Normal   Created                 6s (x3 over 21s)  kubelet                  Created container elastic-internal-init-filesystem
  Normal   Started                 6s (x3 over 21s)  kubelet                  Started container elastic-internal-init-filesystem
  Normal   Pulled                  6s (x2 over 20s)  kubelet                  Container image "docker.elastic.co/elasticsearch/elasticsearch:7.16.0" already present on machine
  Warning  BackOff                 5s (x3 over 19s)  kubelet                  Back-off restarting failed container

**Yaml file used**
```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: test4
spec:
  version: 7.16.0
  nodeSets:
  - name: default
    count: 1
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 2Ti
        storageClassName: elasticsearch-premium-ssd    
    config:
      node.master: true
      node.data: true
      node.ingest: true
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=524288']
```
