### ISSUE TITLE
eck  install kibana Readiness probe failed

### ISSUE THREAD

**Issue by chj9** [elastic/cloud-on-k8s#5182]
## Proposal

eck run kibana can not running

## Bug Report
**What did you do?**
use eck run kibana
**What did you expect to see?**

Get "http://192.168.249.176:5601/login" should response 200 code

**What did you see instead? Under which circumstances?**

Readiness probe failed: Get "http://192.168.249.176:5601/login": dial tcp 192.168.249.176:5601: connect: connection refused
![image](https://user-images.githubusercontent.com/16426260/146499158-b33a3691-6d57-4ac1-9f17-d963ce316465.png)
My es node is normal
![image](https://user-images.githubusercontent.com/16426260/146499688-ba44d3ad-3468-441b-b35e-ae0a14eee19a.png)
![image](https://user-images.githubusercontent.com/16426260/146500217-24a85769-ef8a-47f7-82ca-a314a026c5c2.png)

**Environment**

* ECK version:

	1.9.1

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* Cloud: GKE
	* Kubernetes distribution: Rancher
	
	for each of them please give us the version you are using
```
$ kubectl version
```
1.21.6
* Resource definition:
**kibana.yaml**
```
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: security-kibana
  namespace: elastic-system
spec:
  version: 7.16.1
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  count: 1
  elasticsearchRef:
    name: security-cluster
  config:
    xpack.security.enabled: false    
  podTemplate:
    spec:
      containers:
      - name: kibana
        resources:
          limits:
            memory: 2Gi

```
**es.yaml**
```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: security-cluster
  namespace: elastic-system
spec:
  version: 7.16.1
  image: registry.atai.local/atai/elasticsearch:7.16.1
  http:
     tls:
       selfSignedCertificate:
         disabled: true
  nodeSets:
  - name: es-security
    count: 1
    podTemplate:
      spec:
        imagePullSecrets:
          - name: local-ware
        nodeSelector:
          kubernetes.io/hostname: k8s-114
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: 4Gi
              cpu: 4
          readinessProbe:
            tcpSocket:
              port: 9200
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 12
            successThreshold: 1
            timeoutSeconds: 12
          env:
            - name: READINESS_PROBE_TIMEOUT
              value: "10"
            - name: ES_JAVA_OPTS
              value: "-Xms2g -Xmx2g"
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: local-disk
```
* Logs:

![image](https://user-images.githubusercontent.com/16426260/146499878-12f5c96e-301d-4e96-99b5-558f50f2a364.png)
