### ISSUE TITLE
Stack Monitoring example in ECK docs unclear if a separate Kibana instance should be used

### ISSUE THREAD

**Issue by brsolomon-deloitte** [elastic/cloud-on-k8s#5186]
## Bug Report
**What did you do?**

Enabled monitoring (logs + metrics) by pointing Kibana and Elasticsearch to a dedicated monitoring cluster.

Logged in to Kibana using the `elastic` user and password stored in the secret for the main Elasticsearch cluster below.

```bash
$ k get secret -n REDACTED REDACTED-es-elastic-user -o jsonpath='{.data.elastic}' | base64 --decode
```

**What did you expect to see?**

Stack Monitoring page in Kibana shows monitoring data.

**What did you see instead? Under which circumstances?**

Stack Monitoring page in Kibana displays:

> No monitoring data found

**Environment**

* ECK version:

    1.9.1

* Kubernetes information:

Amazon EKS, k8s 1.21

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-13+d2965f0db10712", GitCommit:"d2965f0db1071203c6f5bc662c2827c71fc8b20d", GitTreeState:"clean", BuildDate:"2021-06-26T01:02:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Resource definition:

Elasticsearch main cluster:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  labels:
    app.kubernetes.io/instance: elasticsearch
  name: REDACTED
  namespace: REDACTED
spec:
  http:
    tls:
      selfSignedCertificate:
        subjectAltNames:
          - dns: REDACTED-es-read-http
          - dns: REDACTED-es-write-http
          - dns: REDACTED-es-read-http.REDACTED
          - dns: REDACTED-es-write-http.REDACTED
          - dns: REDACTED-es-read-http.REDACTED.svc
          - dns: REDACTED-es-write-http.REDACTED.svc
  monitoring:
    logs:
      elasticsearchRefs:
        - name: monitoring
    metrics:
      elasticsearchRefs:
        - name: monitoring
  nodeSets:
    - config:
        node.roles:
          - master
      count: 3
      name: master
      podTemplate:
        spec:
          containers:
            - env:
                - name: ES_JAVA_OPTS
                  value: '-Xms2g -Xmx2g'
              name: elasticsearch
              resources:
                limits: {}
                requests:
                  cpu: 250m
                  memory: 4Gi
          initContainers:
            - command:
                - /bin/bash
                - '-exc'
                - |
                  CURRENT=`sysctl -n vm.max_map_count`;
                  DESIRED="262144";
                  if [ "$DESIRED" -gt "$CURRENT" ]; then
                      sysctl -w vm.max_map_count=262144;
                  fi;
                  CURRENT=`sysctl -n fs.file-max`;
                  DESIRED="65536";
                  if [ "$DESIRED" -gt "$CURRENT" ]; then
                      sysctl -w fs.file-max=65536;
                  fi;
              image: 'docker.io/bitnami/bitnami-shell:10-debian-10-r248'
              imagePullPolicy: IfNotPresent
              name: sysctl
              resources:
                limits: {}
                requests: {}
              securityContext:
                privileged: true
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 8Gi
    - config:
        node.roles:
          - data
      count: 2
      name: data
      podTemplate:
        spec:
          containers:
            - env:
                - name: ES_JAVA_OPTS
                  value: '-Xms10g -Xmx10g'
              name: elasticsearch
              resources:
                limits:
                  cpu: 8
                  memory: 20Gi
                requests:
                  cpu: 2
                  memory: 20Gi
          initContainers:
            - command:
                - /bin/bash
                - '-exc'
                - |
                  CURRENT=`sysctl -n vm.max_map_count`;
                  DESIRED="262144";
                  if [ "$DESIRED" -gt "$CURRENT" ]; then
                      sysctl -w vm.max_map_count=262144;
                  fi;
                  CURRENT=`sysctl -n fs.file-max`;
                  DESIRED="65536";
                  if [ "$DESIRED" -gt "$CURRENT" ]; then
                      sysctl -w fs.file-max=65536;
                  fi;
              image: 'docker.io/bitnami/bitnami-shell:10-debian-10-r248'
              imagePullPolicy: IfNotPresent
              name: sysctl
              resources:
                limits: {}
                requests: {}
              securityContext:
                privileged: true
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 128Gi
  version: 7.16.1
  volumeClaimDeletePolicy: DeleteOnScaledownOnly
```

Kibana:

```yaml
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  labels:
    app.kubernetes.io/instance: kibana
  name: REDACTED
  namespace: REDACTED
spec:
  config:
    server.publicBaseUrl: 'https://kibana.REDACTED.REDACTED'
  count: 1
  elasticsearchRef:
    name: REDACTED
    serviceName: REDACTED-es-read-http
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  monitoring:
    logs:
      elasticsearchRefs:
        - name: monitoring
    metrics:
      elasticsearchRefs:
        - name: monitoring
  version: 7.16.1
```

Elasticsearch monitoring cluster:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  labels:
    app.kubernetes.io/instance: elastic-monitoring
  name: monitoring
  namespace: REDACTED
spec:
  nodeSets:
    - count: 3
      name: default
      podTemplate:
        spec:
          containers:
            - env:
                - name: ES_JAVA_OPTS
                  value: '-Xms1g -Xmx1g'
              name: elasticsearch
              resources:
                limits: {}
                requests:
                  cpu: 250m
                  memory: 2Gi
          initContainers:
            - command:
                - /bin/bash
                - '-exc'
                - |
                  CURRENT=`sysctl -n vm.max_map_count`;
                  DESIRED="262144";
                  if [ "$DESIRED" -gt "$CURRENT" ]; then
                      sysctl -w vm.max_map_count=262144;
                  fi;
                  CURRENT=`sysctl -n fs.file-max`;
                  DESIRED="65536";
                  if [ "$DESIRED" -gt "$CURRENT" ]; then
                      sysctl -w fs.file-max=65536;
                  fi;
              image: 'docker.io/bitnami/bitnami-shell:10-debian-10-r248'
              imagePullPolicy: IfNotPresent
              name: sysctl
              resources:
                limits: {}
                requests: {}
              securityContext:
                privileged: true
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 64Gi
  version: 7.16.1
  volumeClaimDeletePolicy: DeleteOnScaledownOnly
```

* Logs:

I have verified that the monitoring indices exist (command below from a `curlimages/curl` exec'd shell):

```bash
/ $ curl -k -u elastic https://monitoring-es-http:9200/_cat/indices
Enter host password for user 'elastic':
green open .geoip_databases                    YZNpbyWsTgyQgNAv_7o-Bg 1 1   42 0  82.4mb  41.2mb
green open filebeat-7.16.1-2021.12.20-000001   soWDAkaRR6WOmiMavBCVvw 1 1 9403 0   6.4mb   3.2mb
green open metricbeat-7.16.1-2021.12.20-000001 fNOflsKUScmWUG_FXsJqqw 1 1   36 0 450.3kb 225.1kb
green open .monitoring-kibana-7-mb-2021.12.20  KpU7VKYlQc-adW48KZNvPQ 1 1    6 0  88.5kb  44.2kb
green open .monitoring-es-7-mb-2021.12.20      wajpkNxDTNahUjoI8COcbw 1 1 2470 0   9.5mb   5.1mb
```

**Possible cause**

I have noticed that neither `monitoring.ui.elasticsearch.username` or `monitoring.ui.elasticsearch.password` get set in kibana.yml.

This seems to be an issue because, based on https://www.elastic.co/guide/en/kibana/current/monitoring-settings-kb.html, `monitoring.ui.elasticsearch.password` is the 

> password used by Kibana monitoring to establish a persistent connection in Kibana to the Elasticsearch **monitoring cluster** ... If not set, Kibana uses the value of the `elasticsearch.password` setting.

Well, since we only have one Kibana instance, elasticsearch.password points to the "wrong" password - the one used for the main Elasticsearch cluster, _not_ the monitoring cluster.

Furthermore https://www.elastic.co/guide/en/kibana/current/monitor-troubleshooting.html mentions,

> Confirm that Kibana is seeking monitoring data from the appropriate Elasticsearch URL. By default, data is retrieved from the cluster specified in the elasticsearch.hosts setting in the kibana.yml file. If you want to retrieve it from a different monitoring cluster, set monitoring.ui.elasticsearch.hosts. See Monitoring settings.

Again, in our kibana.yml, elasticsearch.hosts points to our main Elasticsearch cluster, _not_ the monitoring cluster, since that is what the `spec.elasticsearchRef` for Kibana points to.

It seems based on all of this that a **separate instance of Kibana is required.** Is this the case? This is not mentioned at https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-stack-monitoring.html, and if so, perhaps the documentation could be made more clear.

- 1 main Elasticsearch instance. Sets `spec.monitoring.xxx.elasticsearchRefs` to `monitoring`
- 1 main Kibana instance, used to discover data from Elasticsearch main. Sets `spec.elasticsearchRefs` to `main` and `spec.monitoring.xxx.elasticsearchRefs` to `monitoring` 
- 1 monitoring Elasticseach cluster, called `monitoring`
- 1 Kibana instance used to display Stack Monitoring, that uses `spec.elasticsearchRefs` to point to `monitoring`
