### ISSUE TITLE
kibana-controller : Association backend for elasticsearch is not configured

### ISSUE THREAD

**Issue by zzhao2010** [elastic/cloud-on-k8s#5210]
## Proposal

**Use case. Why is this important?**

## Bug Report
**What did you do?**
I was testing ECK with the quickstart example provided on the website. Kibana was failed to be deployed with the error Association backend for elasticsearch is not configured from the kibana-controller. 
**What did you expect to see?**
Kibana is deployed via ECK and connects to the elasticsearch cluster.
**What did you see instead? Under which circumstances?**
The issue was at elasticsearchRef because Kibana was able to be deployed if I took this line out, but Kibana will not be able to connect to the elasticsearch cluster that was deployed before kibana.
```
elasticsearchRef:
    name: quickstart
```
**Environment**
On-premise K8S v1.22.5
* ECK version:
1.9
* Kubernetes information:
On-premise K8S on VirtualBox
	for each of them please give us the version you are using
```
$ kubectl version
```
v1.22.5
* Resource definition:
```
https://download.elastic.co/downloads/eck/1.9.1/crds.yaml
if relevant insert the resource definition
```

* Logs:
kibana-controller             Association backend for elasticsearch is not configured

**Comment by zzhao2010** [comment]
Looks like the issue was due to the HTTP service that I created on elasticsearch. Here is the log from the controller:
**"error":"no port named [https] in service [default/quickstart-es-http]"**
```
http:
    service:
      spec:
        type: NodePort
        ports:
          - port: 9200
            targetPort: 9200
            protocol: TCP
            nodePort: 31920
```
