### ISSUE TITLE
chroot: cannot change root directory to '/': Operation not permitted

### ISSUE THREAD

**Issue by ooraini** [elastic/cloud-on-k8s#5212]
## Bug Report
Following the quickstart guide and creating the Elastic search cluster causes the Pod to get into CrashLoopBackOff. Looking at the logs, there is only one line:
```
chroot: cannot change root directory to '/': Operation not permitted
```
Adding the following `securityContext` to the elasticsearch container fixes the issue:
```
securityContext:
  capabilities:
    add: ["SYS_CHROOT"]

```
#4334 was opened for Openshift clusters. I'm not using Openshift and I'm not using the `default` namespace.

**What did you do?**
Follow the qiuckstart guide, deployed the operator and the elastic cluster.
**What did you expect to see?**
`quickstart-es-default-0                         1/1     Running   0`
**What did you see instead? Under which circumstances?**
`quickstart-es-default-0                         0/1     CrashLoopBackOff   6 (4m46s ago)`
**Environment**

* ECK version: 7.16.2

	insert version or git commit id here

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* Kubeadm
	* CRIO
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:42:41Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}

```
```
Installed Packages
Name         : cri-o
Version      : 1.22.1
Release      : 6.2.el8
Architecture : x86_64
Size         : 114 M
Source       : cri-o-1.22.1-6.2.el8.src.rpm
Repository   : @System
From repo    : devel_kubic_libcontainers_stable_cri-o_1.22
Summary      : Open Container Initiative-based implementation of Kubernetes Container Runtime Interface
URL          : https://github.com/cri-o/cri-o
License      : ASL 2.0
Description  : Open Container Initiative-based implementation of Kubernetes Container Runtime
             : Interface.
```

**Comment by naemono** [comment]
@ooraini thank you for the report.  Resolving the security context for all environments is not a simple task, clearly. 

7.16.2 is the elasticsearch version, not the eck version.  Is the eck version something like 1.9.x?  Let us know, thanks.  

Is this k8s environment in any particular public cloud?  The more information you give, the better we can help make this easier to relocate and resolve for future users.

Also please share the full ES custom resource you used to build this cluster.

We will discuss this issue and see if there are any commonalities we can use here to make this work out of the box for users.

**Comment by ooraini** [comment]
@naemono  The ECK version is 1.9.1. I used the following manifest `https://download.elastic.co/downloads/eck/1.9.1/operator.yaml`.

This is a lab environment on my local machine with multiple VMs.

ES resource config:
```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.16.2
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: direct-csi-min-io
        


```

I can tear down the environment and recreate it easily. I will test with K8s 1.23 and CRI-O 1.23.

**Comment by ooraini** [comment]
After some search I found [https://github.com/cri-o/cri-o/issues/5116](https://github.com/cri-o/cri-o/issues/5116). It seems that the default capabilities in CRI-O doesn't include `SYS_CHROOT`.

From the CRI-O man pages:
```
  default_capabilities = [
	  "CHOWN",
	  "DAC_OVERRIDE",
	  "FSETID",
	  "FOWNER",
	  "SETGID",
	  "SETUID",
	  "SETPCAP",
	  "NET_BIND_SERVICE",
	  "KILL",
  ]
```

In the resource config generated by the operator, the list of capabilities  can be more explicit and include all the required capabilities. Which will avoid problems when the defaults change for any container runtime.

For now, any users who is using CRI-O and hasn't modified the `default_capabilities` will face this issue.

**Comment by barkbay** [comment]
> Right now any user who is using CRI-O and hasn't modified the `default_capabilities` will face this issue.

You are also facing this issue because [you are running the container as the `root` user](https://github.com/elastic/elasticsearch/blob/47cad2204f22d9f36753365b7f23e333ad88ca84/distribution/docker/src/docker/bin/docker-entrypoint.sh#L7-L10). I would suggest to set a `securityContext` to control which user is used to run your workloads:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
spec:
  version: 7.15.2
  nodeSets:
  - name: default
    config:
      node.store.allow_mmap: false
    podTemplate:
      spec:
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
    count: 3
```

I think it would not only have the benefit to solve your issue but also increase the security of your deployments.

Note that Elasticsearch 8.0.0 will not run as `root` by default, removing the need of the chroot, and somewhat prevent this issue to happen.
