### ISSUE TITLE
ECK operator is unable to manage the ES cluster after 1.9.1 upgrade

### ISSUE THREAD

**Issue by jkavan** [elastic/cloud-on-k8s#5218]
## Bug Report

**What did you do?**

After upgrading ECK operator to version 1.9.1 from 1.2.1, the operator is no longer able to manage our ES cluster. I tried to update our cluster by changing the version spec and killing the pod manually, but that would just re-create the pod with the old version.

I followed the [upgrade process guide](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-upgrading-eck.html) thoroughly and the operator upgrade went smoothly, no issues there.

**What did you expect to see?**

After upgrading ECK, it should be able to manage the old cluster just like before.

**What did you see instead? Under which circumstances?**

The new version of operator won't manage our old ES cluster that was created by ECK v1.2.0.

**Environment**

ECK is running in its own namespace (elastic-system) and it manages a single-node ES cluster (elastic-ms) that's located in another namespace (custom-ns).

I'm using default configs, the only relevant change is that I added `namespaces: custom-ns` to configmap.

* Elasticsearch version:

	7.9.3

* ECK version:

	1.9.1 (I also tried downgrading to 1.7.1, but same issue)

* Kubernetes information:

	Cloud: GKE, version 1.19.15-gke.500

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.15-gke.500", GitCommit:"8a364d9e63fa843cfb76953371ba71fa198bb114", GitTreeState:"clean", BuildDate:"2021-09-23T09:25:46Z", GoVersion:"go1.15.15b5", Compiler:"gc", Platform:"linux/amd64"}
```

* Logs:

```
$ kubectl get elasticsearches.elasticsearch.k8s.elastic.co -A -o wide
NAMESPACE                    NAME               HEALTH   NODES   VERSION   PHASE   AGE
custom-ns                    elastic-ms         yellow   1                 Ready   253d
```

The cluster is yellow since it's only a single-node. Note that the VERSION is also missing.

```
{"log.level":"info","@timestamp":"2022-01-04T07:27:38.491Z","log.logger":"elasticsearch-controller","message":"Starting reconciliation run","service.version":"1.9.1+75cb4d4d","service.type":"eck","ecs.version":"1.4.0","iteration":5,"namespace":"custom-ns","es_name":"elastic-ms"}

{"log.level":"info","@timestamp":"2022-01-04T07:27:38.491Z","log.logger":"elasticsearch-controller","message":"Ending reconciliation run","service.version":"1.9.1+75cb4d4d","service.type":"eck","ecs.version":"1.4.0","iteration":5,"namespace":"custom-ns","es_name":"elastic-ms","took":0.000058915}

{"log.level":"error","@timestamp":"2022-01-04T07:27:38.491Z","log.logger":"manager.eck-operator.controller.elasticsearch-controller","message":"Reconciler error","service.version":"1.9.1+75cb4d4d","service.type":"eck","ecs.version":"1.4.0","name":"elastic-ms","namespace":"custom-ns","error":"unable to get: custom-ns/elastic-ms because of unknown namespace for the cache","error.stack_trace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.6/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.6/pkg/internal/controller/controller.go:214"}
```

I don't know if the "unable to get: <namespace>/<elastic> because of unknown namespace for the cache" is relevant or not, but that error isn't present in our other environment where ECK is still 1.2.0. To me this sounds like a permission issue, but I tried giving the service account a cluster-admin role and confirmed with `kubectl can-i` that it indeed can access all the required resources.

How would I go about troubleshooting this?

**Comment by barkbay** [comment]
> I don't know if the "unable to get: / because of unknown namespace for the cache"

Yes, it means the K8S client used by the operator does not manage resources in `custom-ns`

Could you share the first lines logged by the operator to double check what namespaces are managed ? You should see something like:

```json
{
        "log.level": "info",
	"log.logger": "manager",
	"message": "Operator configured to manage multiple namespaces",
	"service.version": "1.9.1+75cb4d4d",
	"service.type": "eck",
	"ecs.version": "1.4.0",
	"namespaces": ["custom-ns"],
	"operator_namespace": "elastic-system"
}
```

Could you also:
* share the content of the `ConfigMap`: `kubectl get cm  -n elastic-system elastic-operator -o yaml` 
* check if any additional parameter as been added to the operator either by using a flag or an environment variable in the `StatefulSet` (`kubectl get sts -n elastic-system elastic-operator -o yaml`)?

Thanks

**Comment by jkavan** [comment]
Thanks for the response!

> Could you share the first lines logged by the operator to double check what namespaces are managed ? You should see something like:

Yes, that line is present:

```
{"log.level":"info","@timestamp":"2022-01-07T06:03:37.882Z","log.logger":"manager","message":"maxprocs: Updating GOMAXPROCS=1: determined from CPU quota","service.version":"1.9.1+75cb4d4d","service.type":"eck","ecs.version":"1.4.0"}
{"log.level":"info","@timestamp":"2022-01-07T06:03:37.882Z","log.logger":"manager","message":"Setting default container registry","service.version":"1.9.1+75cb4d4d","service.type":"eck","ecs.version":"1.4.0","container_registry":"docker.elastic.co"}
{"log.level":"info","@timestamp":"2022-01-07T06:03:37.882Z","log.logger":"manager","message":"Setting up scheme","service.version":"1.9.1+75cb4d4d","service.type":"eck","ecs.version":"1.4.0"}
{"log.level":"info","@timestamp":"2022-01-07T06:03:37.883Z","log.logger":"manager","message":"Operator configured to manage multiple namespaces","service.version":"1.9.1+75cb4d4d","service.type":"eck","ecs.version":"1.4.0","namespaces":["custom-ns"],"operator_namespace":"elastic-system"}
I0107 06:03:38.935000       1 request.go:668] Waited for 1.035717011s due to client-side throttling, not priority and fairness, request: GET:https://10.141.0.1:443/apis/elasticsearch.k8s.elastic.co/v1?timeout=1m0s
{"log.level":"info","@timestamp":"2022-01-07T06:03:40.692Z","log.logger":"controller-runtime.metrics","message":"metrics server is starting to listen","service.version":"1.9.1+75cb4d4d","service.type":"eck","ecs.version":"1.4.0","addr":":0"}
{"log.level":"info","@timestamp":"2022-01-07T06:03:40.699Z","log.logger":"manager","message":"Setting up controllers","service.version":"1.9.1+75cb4d4d","service.type":"eck","ecs.version":"1.4.0"}
{"log.level":"info","@timestamp":"2022-01-07T06:03:40.699Z","log.logger":"manager","message":"Automatic management of the webhook certificates enabled","service.version":"1.9.1+75cb4d4d","service.type":"eck","ecs.version":"1.4.0"}
```

> share the content of the `ConfigMap`: `kubectl get cm  -n elastic-system elastic-operator -o yaml`

```yaml
# Source: eck-operator/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-operator
  namespace: elastic-system
  labels:
    control-plane: elastic-operator
    app.kubernetes.io/version: "1.9.1"
data:
  eck.yaml: |-
    log-verbosity: 0
    metrics-port: 0
    container-registry: docker.elastic.co
    max-concurrent-reconciles: 3
    ca-cert-validity: 8760h
    ca-cert-rotate-before: 24h
    cert-validity: 8760h
    cert-rotate-before: 24h
    set-default-security-context: true
    kube-client-timeout: 60s
    elasticsearch-client-timeout: 180s
    disable-telemetry: false
    distribution-channel: all-in-one
    validate-storage-class: true
    enable-webhook: true
    webhook-name: elastic-webhook.k8s.elastic.co
    namespaces: custom-ns
```

> check if any additional parameter as been added to the operator either by using a flag or an environment variable in the `StatefulSet` (`kubectl get sts -n elastic-system elastic-operator -o yaml`)?

There aren't any extra args or environment variables.

```yaml
...
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      control-plane: elastic-operator
  serviceName: elastic-operator
  template:
    metadata:
      annotations:
        checksum/config: 239de074c87fe1f7254f5c93ff9f4a0949c8f111ba15696c460d786d6279e4d6
        co.elastic.logs/raw: '[{"type":"container","json.keys_under_root":true,"paths":["/var/log/containers/*${data.kubernetes.container.id}.log"],"processors":[{"convert":{"mode":"rename","
ignore_missing":true,"fields":[{"from":"error","to":"_error"}]}},{"convert":{"mode":"rename","ignore_missing":true,"fields":[{"from":"_error","to":"error.message"}]}},{"convert":{"mode":"rena
me","ignore_missing":true,"fields":[{"from":"source","to":"_source"}]}},{"convert":{"mode":"rename","ignore_missing":true,"fields":[{"from":"_source","to":"event.source"}]}}]}]'
      creationTimestamp: null
      labels:
        control-plane: elastic-operator
    spec:
      containers:
      - args:
        - manager
        - --config=/conf/eck.yaml
        env:
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: WEBHOOK_SECRET
          value: elastic-webhook-server-cert
        image: docker.elastic.co/eck/eck-operator:1.9.1
...
```
