### ISSUE TITLE
Error patching Kibana when resource definition contains affinity config

### ISSUE THREAD

**Issue by Norskov** [elastic/cloud-on-k8s#5229]
## Bug Report
**What did you do?**
I tried to update Kibana config using kubecfg, which tries to patch it using kubernetes apimachinery.

**What did you expect to see?**
A successful patching.

**What did you see instead? Under which circumstances?**
Error with no error text from the API used by apimachinery.

No error appears in the operator logs.

Removing the affinity section from the resource definition results in success.

**Environment**

* ECK version: 1.7.0 - 1.9.1
	* Works as expected on 1.4.0 - 1.6.0

* Kubernetes information:
	* Cloud: GKE
	* Server Version: 1.21.5-gke.1302
	* Client Version: v1.21.4

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:16:05Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5-gke.1302", GitCommit:"639f3a74abf258418493e9b75f2f98a08da29733", GitTreeState:"clean", BuildDate:"2021-10-21T21:35:48Z", GoVersion:"go1.16.7b7", Compiler:"gc", Platform:"linux/amd64"}
```
* Resource definition:
```
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: mibana
spec:
  config:
    discover.enabled: false
    enterpriseSearch.enabled: false
    logging.verbose: false
    monitoring.enabled: false
    newsfeed.enabled: false
    telemetry.enabled: false
    vis_type_timelion.enabled: false
    xpack.apm.enabled: false
    xpack.fleet.enabled: false
    xpack.fleet.fleet.enabled: false
    xpack.graph.enabled: false
    xpack.grokdebugger.enabled: false
    xpack.infra.enabled: false
    xpack.ml.enabled: false
    xpack.reporting.enabled: false
    xpack.searchprofiler.enabled: false
    xpack.spaces.enabled: false
  count: 2
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  image: docker.elastic.co/kibana/kibana:7.13.4
  podTemplate:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: name
                operator: In
                values:
                - mibana
            topologyKey: kubernetes.io/hostname
      containers:
      - name: kibana
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /translations/en.json
            port: 5601
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            memory: 1500Mi
          requests:
            memory: 500Mi
  version: 7.13.4
```

* Logs: Stacktrace from kubecfg
```
E0105 12:35:27.919793   27155 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 1 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x142ac20, 0x22ec6a0})
        /github/home/.cache/Homebrew/go_mod_cache/pkg/mod/k8s.io/apimachinery@v0.23.1/pkg/util/runtime/runtime.go:74 +0x7d
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc001633e20})
        /github/home/.cache/Homebrew/go_mod_cache/pkg/mod/k8s.io/apimachinery@v0.23.1/pkg/util/runtime/runtime.go:48 +0x75
panic({0x142ac20, 0x22ec6a0})
        /home/linuxbrew/.linuxbrew/Cellar/go/1.17.5/libexec/src/runtime/panic.go:1038 +0x215
k8s.io/apimachinery/pkg/util/strategicpatch.handleMapDiff({0xc000449630, 0xf}, 0xc0006ecc00, 0xc0006c54d0, 0xc0006c54d0, {0x0, 0x0}, {0x1, 0x0, 0x1, ...})
        /github/home/.cache/Homebrew/go_mod_cache/pkg/mod/k8s.io/apimachinery@v0.23.1/pkg/util/strategicpatch/patch.go:263 +0x58
k8s.io/apimachinery/pkg/util/strategicpatch.diffMaps(0x250f788, 0xc0006c54a0, {0x0, 0x0}, {0x20, 0x0, 0x0, 0x0})
        /github/home/.cache/Homebrew/go_mod_cache/pkg/mod/k8s.io/apimachinery@v0.23.1/pkg/util/strategicpatch/patch.go:212 +0x485
k8s.io/apimachinery/pkg/util/strategicpatch.handleMapDiff({0xc000449620, 0x8}, 0xc0006ecbd0, 0xc0006c54a0, 0xc0006c54a0, {0x17e0780, 0xc001633fb0}, {0x1, 0x0, 0x1, ...})
        /github/home/.cache/Homebrew/go_mod_cache/pkg/mod/k8s.io/apimachinery@v0.23.1/pkg/util/strategicpatch/patch.go:286 +0x1de
k8s.io/apimachinery/pkg/util/strategicpatch.diffMaps(0x250f788, 0xc0006c5470, {0x17e0780, 0xc001633fb0}, {0x20, 0xdb, 0x5c, 0x4c})
        /github/home/.cache/Homebrew/go_mod_cache/pkg/mod/k8s.io/apimachinery@v0.23.1/pkg/util/strategicpatch/patch.go:212 +0x485
k8s.io/apimachinery/pkg/util/strategicpatch.handleMapDiff({0xc00044961c, 0x4}, 0xc0006ecba0, 0xc0006c5470, 0xc0006c5470, {0x17e0780, 0xc001633f70}, {0x1, 0x0, 0x1, ...})
        /github/home/.cache/Homebrew/go_mod_cache/pkg/mod/k8s.io/apimachinery@v0.23.1/pkg/util/strategicpatch/patch.go:286 +0x1de
k8s.io/apimachinery/pkg/util/strategicpatch.diffMaps(0x250f788, 0xc0006c5440, {0x17e0780, 0xc001633f70}, {0x0, 0x0, 0x0, 0x0})
        /github/home/.cache/Homebrew/go_mod_cache/pkg/mod/k8s.io/apimachinery@v0.23.1/pkg/util/strategicpatch/patch.go:212 +0x485
k8s.io/apimachinery/pkg/util/strategicpatch.handleMapDiff({0xc000449610, 0xb}, 0xc0006ecb40, 0xc0006c5440, 0xc0006c5440, {0x17e0780, 0xc001633f50}, {0x1, 0x0, 0x1, ...})
        /github/home/.cache/Homebrew/go_mod_cache/pkg/mod/k8s.io/apimachinery@v0.23.1/pkg/util/strategicpatch/patch.go:286 +0x1de
k8s.io/apimachinery/pkg/util/strategicpatch.diffMaps(0x250f788, 0xc0006c5350, {0x17e0780, 0xc001633f50}, {0x0, 0x0, 0x0, 0x0})
        /github/home/.cache/Homebrew/go_mod_cache/pkg/mod/k8s.io/apimachinery@v0.23.1/pkg/util/strategicpatch/patch.go:212 +0x485
k8s.io/apimachinery/pkg/util/strategicpatch.handleMapDiff({0xc000449768, 0x4}, 0xc0006ec8a0, 0xc0006c5350, 0xc0006c5350, {0x17e0780, 0xc001632fc0}, {0x1, 0x0, 0x1, ...})
        /github/home/.cache/Homebrew/go_mod_cache/pkg/mod/k8s.io/apimachinery@v0.23.1/pkg/util/strategicpatch/patch.go:286 +0x1de
k8s.io/apimachinery/pkg/util/strategicpatch.diffMaps(0xc0004ad000, 0xc0006c52c0, {0x17e0780, 0xc001632fc0}, {0xf8, 0x21, 0xe5, 0x0})
        /github/home/.cache/Homebrew/go_mod_cache/pkg/mod/k8s.io/apimachinery@v0.23.1/pkg/util/strategicpatch/patch.go:212 +0x485
k8s.io/apimachinery/pkg/util/strategicpatch.CreateThreeWayMergePatch({0xc00033b000, 0x757, 0x757}, {0xc0006ccc80, 0xc001b792f0, 0xc16}, {0xc0004ad000, 0x1a80, 0x161c}, {0x17e0780, ...}, ...)
        /github/home/.cache/Homebrew/go_mod_cache/pkg/mod/k8s.io/apimachinery@v0.23.1/pkg/util/strategicpatch/patch.go:2053 +0x298
```
