### ISSUE TITLE
GKE Workload Identity support for GCS backups repository plugin.

### ISSUE THREAD

**Issue by aleks-m** [elastic/cloud-on-k8s#5230]
Hi.

Is there any plan for adding support for GKE Workload Identity to GCS backups repository plugin?

I know what there is a way to configure credintials for GCS repository plugin using Service Account credential files but it creates additional toil. And Workload Identity is currently a recommended way (by Google) for authenticating GKE workloads to Google Cloud services  - https://cloud.google.com/kubernetes-engine/docs/concepts/workload-identity

Asking here because all other discussions which I found are outdated and have very little info:
- https://discuss.elastic.co/t/can-we-use-workload-identity-for-leasticsearch-backup-and-restore/247232
- https://discuss.elastic.co/t/using-gke-workflow-identity-to-snapshot-and-restore-elasticsearch-data/223156/3
- https://discuss.elastic.co/t/does-eck-1-3-0-supports-workload-identity/263021

Thanks.

**Comment by barkbay** [comment]
I followed the [GKE documentation](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity):

1. Create a GKE cluster with `--workload-pool=PROJECT_ID.svc.id.goog`
2. Create a namespace and a K8S service account _(`test-gcs` and `gcs-sa` in this example)_
3. Create the bucket, the Google service account _(`gcp-sa` in this example)_ and set the relevant permissions
4. Allow the Kubernetes service account to impersonate the Google service:

```
gcloud iam service-accounts add-iam-policy-binding gcp-sa@PROJECT_ID.iam.gserviceaccount.com \
    --role roles/iam.workloadIdentityUser \
    --member "serviceAccount:PROJECT_ID.svc.id.goog[test-gcs/gcs-sa]"
```

5. Add the annotation on the K8S `ServiceAccount`

```
kubectl annotate serviceaccount gcs-sa \
    --namespace test-gcs \
    iam.gke.io/gcp-service-account=gcp-sa@PROJECT_ID.iam.gserviceaccount.com
```

6. Create the Elasticsearch cluster:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-gcs-sample
  namespace: test-gcs
spec:
  version: 7.15.2
  nodeSets:
  - name: default
    config:
      node.roles: ["master", "data", "ingest", "ml"]
      node.store.allow_mmap: false
    podTemplate:
      metadata:
        labels:
          # additional labels for pods
          foo: bar
      spec:
        initContainers:
          - name: install-plugins
            command:
              - sh
              - -c
              - |
                bin/elasticsearch-plugin install --batch repository-gcs
        automountServiceAccountToken: true
        serviceAccountName: gcs-sa
    count: 3
```

7. Create the snapshot repository:

```
PUT /_snapshot/my_gcs_repository
{
  "type": "gcs",
  "settings": {
    "bucket": "my-gcs-bucket",
    "client": "default"
  }
}
```

```json
{
  "acknowledged" : true
}
```

8. Create a snapshot:

```
PUT _snapshot/my_gcs_repository/my_snapshot?wait_for_completion=true
```
```json
{
  "snapshot" : {
    "snapshot" : "my_snapshot",
    "uuid" : "p3FNqAoJQ9Wv9e4Fe3FFsg",
    "repository" : "my_gcs_repository",
    "version_id" : 7150299,
    "version" : "7.15.2",
    "indices" : [
      ".ds-ilm-history-5-2022.01.05-000001",
      ".kibana-event-log-7.15.2-000001",
      ".kibana_7.15.2_001",
      ".apm-custom-link",
      "kibana_sample_data_flights",
      ".geoip_databases",
      "kibana_sample_data_ecommerce",
      ".tasks",
      ".kibana_security_session_1",
      "kibana_sample_data_logs",
      ".kibana_task_manager_7.15.2_001",
      ".apm-agent-configuration",
      ".security-7"
    ],
    "data_streams" : [
      "ilm-history-5"
    ],
...
```

It seems to be working as expected. Do you think there is anything else to do to support workload identity ?
