### ISSUE TITLE
Enterprise Search controller generates invalid configuration when multiple auth sources are used

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#5290]
When users configure additional authentication sources in ECK for example Active Directory the operator generates an invalid configuration file.

For example following the instructions in https://www.elastic.co/guide/en/enterprise-search/7.16/active-directory-auth.html

Users would set up a configuration like the following in the Enterprise Search manifest:
```
  config:
    ent_search.auth:
      native1:
        source: elasticsearch-native
        order: 1
      my_ad:
        source: elasticsearch-active-directory
        order: 2
```

which leads to a generated configuration as follows: 

```
ent_search:
  auth:
    my_ad:
      order: 2
      source: elasticsearch-active-directory
    native1:
      order: 1
      source: elasticsearch-native
    source: elasticsearch-native
```
which is invalid. 

Omitting the `native` auth source in the Enterprise Search custom resource `config` does not help either. The configuration generated is still invalid.

Affected are versions of the Elastic Stack before 7.17 because of https://github.com/elastic/cloud-on-k8s/pull/5085
