### ISSUE TITLE
ES cluster health reported by the operator might be misleading if a reconciliation error

### ISSUE THREAD

**Issue by thbkrkr** [elastic/cloud-on-k8s#5330]
The ES health reported by the operator in the ES resource status may never be updated if the operator encounters an error during the reconciliation loop.

#### Steps to reproduce
- Create an ES cluster
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: bad-ca
stringData:
  ca.crt: bla
  ca.key: bla
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: yellowforever
spec:
  version: 7.16.2
  # transport:                  
  #   tls:
  #     certificate:
  #       secretName: bad-ca
  nodeSets:
  - name: master
    count: 1
    config:
      node.store.allow_mmap: false
```
- Make cluster health yellow
```
# create an index with 1 replica
-XPUT /my-index-1 -d '{"settings":{"number_of_shards":1,"number_of_replicas":1}}'
```
- Configure the bad CA secret in the cluster
``` uncomment transport.tls.certificate.secretName``` and apply.
- Make cluster health green
```
# delete the index
-XDELETE /my-index-1
```
