### ISSUE TITLE
Operator Shouldn't Delete Standalone Elastic Agent Config Secret

### ISSUE THREAD

**Issue by BenB196** [elastic/cloud-on-k8s#5372]
## Bug Report
**What did you do?**

1. Create a standalone Elastic Agent deployment per the [docs](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-elastic-agent-configuration.html).

1.1. Create secret:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: system-cpu-config
stringData:
  agent.yml: |-
    inputs:
      - name: system-1
        revision: 1
        type: system/metrics
        use_output: default
        meta:
          package:
            name: system
            version: 0.9.1
        data_stream:
          namespace: default
        streams:
          - id: system/metrics-system.cpu
            data_stream:
              dataset: system.cpu
              type: metrics
            metricsets:
              - cpu
            cpu.metrics:
              - percentages
              - normalized_percentages
            period: 10s
```

1.2. Create agent:

```yaml
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: quickstart
spec:
  version: 8.0.0
  elasticsearchRefs:
  - name: quickstart
  daemonSet: {}
  configRef:
    secretName: system-cpu-config
```

2. Delete agent

**What did you expect to see?**

I expected to see the created secret remaining in the cluster.

**What did you see instead? Under which circumstances?**

I see that the secret is missing from the cluster.

**Environment**

* ECK version:

	1.9.1

**Note:** I have not tested this on 2.0, but I did check the release notes and didn't see anything that mentions this, so I'm assuming this issue also happens there.

* Kubernetes information:

	* On premise `yes`
	* Cloud: GKE / EKS / AKS `no`
	* Kubernetes distribution: Openshift / Rancher / PKS `v1.21.8+rke2r2`

## Issue/Problem

The issue/problem with this is in a configuration where the user provides the secret, I would expect the user to have total control over the secret, however, as it currently stands the ECK operator also thinks it has control over the secret.

Use cases where this can be an issue:

1. Manual deletion of a CRD for a standalone agent. If a user wants to delete a standalone Elastic Agent CRD for some reason, they may not expect the secret with the config to be deleted as well, therefore if they go back to add the Agent CRD again, it won't work because the operator will have deleted the config secret. This can be a bad thing, if let's say a user is developing a new standalone config in a cluster, they would potentially lose work if they don't have it saved somewhere else.
2. Management of CRDs via a tool (terraform). If you use terraform to manage your Kubernetes deployments/clusters, and you do something like; Elastic Agent manifest depends on Secret config, so that the secret gets built before the Elastic Agent manifest does. Then if you run something like terraform destroy, it will fail because it deletes the Agent before the secret, and since the secret is deleted by the operator, then terraform can't delete the secret.
