### ISSUE TITLE
Auth fileRealm specified in CRD not being used by operator

### ISSUE THREAD

**Issue by gnadaban** [elastic/cloud-on-k8s#5391]
## Bug Report
**What did you do?**

Tried to create an ElasticSearch cluster using `fileRealm` auth.

**What did you expect to see?**

ES pods to be configured using users specified.

**What did you see instead? Under which circumstances?**

Users not added, secret not even mounted in ES pods.

**Environment**

* ECK version:

	1.8.0

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* On premise ? - `NO`
	* Cloud: `cluster-api provisioned cluster on Azure` 
	* Kubernetes distribution: `cluster-api CAPZ` v1.21.5
	
```
$ kubectl version
```

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T21:10:45Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

* Resource definition:
```YAML
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  annotations:
    common.k8s.elastic.co/controller-version: 1.8.0
  labels:
    app.kubernetes.io/instance: elasticsearch-stack
  name: redacted
  namespace: redacted
spec:
  version: 7.17.0

  auth:
    fileRealm:
    - secretName: elastic-auth-secret

  nodeSets:
  - config:
      node.store.allow_mmap: false
    count: 3
    name: default
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: standard
```

* Logs:
```
{"type": "server", "timestamp": "2022-02-17T07:13:27,882Z", "level": "WARN", "component": "o.e.x.s.a.RealmsAuthenticator", "cluster.name": "redacted", "node.name": "redacted-es-default-0", "message": "Authentication to realm file1 failed - Password authentication failed for redacted", "cluster.uuid": "redacted", "node.id": "redacted"  }
```
