### ISSUE TITLE
Feature Request: config to disable various controllers (kibana, elastic map, etc.)

### ISSUE THREAD

**Issue by leonz** [elastic/cloud-on-k8s#5402]
## Proposal

**Use case. Why is this important?**

Hi,

We are currently using ECK to manage our Elasticsearch clusters, but do not manage any other Elastic resources.  In the interest of minimizing risk surface area, we would like to disable any functionality that we do not actively use.  For instance, one concern is that even though we don't deploy Kibana, we are required to grant the ECK manager permissions to interact with Kibana resources.

A simple feature flag for each resource type would be greatly appreciated.

**Comment by thbkrkr** [comment]
> For instance, one concern is that even though we don't deploy Kibana, we are required to grant the ECK manager permissions to interact with Kibana resources.

Can you explain why this is concerning?

**Comment by leonz** [comment]
Hey - our main concerns come from some environments where we deploy where we are not the only tenants in the Kubernetes stack.

This article describes our concerns well - https://loft.sh/blog/kubernetes-crds-huge-pain-in-multi-tenant-clusters/

But to summarize,
- we can’t prevent other tenants from using these CRDs even if we don’t want them to
- the more CRDs we define the more likely we may overlap with others
- from a principle of least privilege, we would like to permission all of our API server clients to have the very minimal set of authorization to perform their needed tasks (in our case, deploy only Elasticsearch)

**Comment by thbkrkr** [comment]
Ok, thanks for the additional explanation.

> A simple feature flag for each resource type would be greatly appreciated.

Something like that?
```java
--disable-agent-controller
--disable-apmserver-controller
--disable-beat-controller
--disable-elasticsearch-controller
--disable-enterprisesearch-controller
--disable-kibana-controller
--disable-elasticmapsserver-controller
```

Wouldn't a single flag be more practical?
```
--disabled-controllers="agent,apmserver,beat,kibana,elasticmapsserver"
```

Maybe also support the shortnames (obtainable through `kubectl api-resources | grep elastic`)?

```
--disabled-controllers="agent,apm,beat,kb,ems"
```

**Comment by leonz** [comment]
Sure that’s reasonable! I don’t have any strong opinions on the implementation.

**Comment by pebrc** [comment]
While I understand the intention (and we can definitely look into adding the ability to turn off individual controllers) I am still wondering why Kubernetes RBAC is not sufficient to prevent unauthorised users from trying to create Kibanas? 

Could you simply not give them the necessary privileges to create the Kibana custom resource?

**Comment by thbkrkr** [comment]
> I may be wrong, but I’m pretty sure that we can’t use RBAC to prevent other users (we don’t control them) from being authorized to global resources, especially if they are working within their own namespace. And since the Operator listens to all namespaces they will then have the ability to influence our operator.

CRD are cluster-wide but custom resources are namespaces. So you can use RBAC to limit a ServiceAccount to access to a specific custom resource. Here is a small example so that:
- ServiceAccount `my-a` can manage `Elasticsearch` and `Kibana` in namespace `a`.
- ServiceAccount `my-b` can only manage `Elasticsearch` in namespace `b`.

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: es-kb-role
rules:
- apiGroups:
    - ""
  resources:
    - pods
    - events
    - persistentvolumeclaims
    - secrets
    - services
    - configmaps
  verbs: ["get", "list"]
- apiGroups:
    - apps
  resources:
    - deployments
    - statefulsets
  verbs: ["get", "list"]
- apiGroups:
    - elasticsearch.k8s.elastic.co
  resources:
    - elasticsearches
    - elasticsearches/status
    - elasticsearches/finalizers
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
- apiGroups:
    - kibana.k8s.elastic.co
  resources:
    - kibanas
    - kibanas/status
    - kibanas/finalizers
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-a
  namespace: a
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: es-kb-a
  namespace: a
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: es-kb-role
subjects: 
- kind: ServiceAccount
  name: my-a
  namespace: a

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: es-role
rules:
- apiGroups:
    - ""
  resources:
    - pods
    - events
    - persistentvolumeclaims
    - secrets
    - services
    - configmaps
  verbs: ["get", "list"]
- apiGroups:
    - apps
  resources:
    - deployments
    - statefulsets
  verbs: ["get", "list"]
- apiGroups:
    - elasticsearch.k8s.elastic.co
  resources:
    - elasticsearches
    - elasticsearches/status
    - elasticsearches/finalizers
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-b
  namespace: b
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: es-b
  namespace: b
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: es-role
subjects: 
- kind: ServiceAccount
  name: my-b
  namespace: b
```

Then:
```sh

# ~/.kube/config
contexts:
- context:
    cluster: ...
    namespace: a
    user: my-a

> k get es,kb,po     
NAME                                              HEALTH   NODES   VERSION   PHASE   AGE
elasticsearch.elasticsearch.k8s.elastic.co/test   green    1       8.0.0     Ready   95s

NAME                                HEALTH   NODES   VERSION   AGE
kibana.kibana.k8s.elastic.co/test   green    1       8.0.0     95s

NAME                           READY   STATUS    RESTARTS   AGE
pod/test-es-master-0           1/1     Running   0          92s
pod/test-kb-545d78485f-hjljd   1/1     Running   0          91s


# ~/.kube/config
contexts:
- context:
    cluster: ...
    namespace: b
    user: my-b

> k get es,kb,po
NAME                                              HEALTH   NODES   VERSION   PHASE   AGE
elasticsearch.elasticsearch.k8s.elastic.co/test   green    1       8.0.0     Ready   69s

NAME                   READY   STATUS    RESTARTS   AGE
pod/test-es-master-0   1/1     Running   0          69s
Error from server (Forbidden): kibanas.kibana.k8s.elastic.co is forbidden: User "system:serviceaccount:b:my-b" cannot list resource "kibanas" in API group "kibana.k8s.elastic.co" in the namespace "b"
```
