### ISSUE TITLE
OpenShift support

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#541]
Not really an issue but a way to track what I did to deploy the operator on Openshift : 

## Can't set finalizers without appropriate RBAC

If you try to deploy the operators on Openshift the following error is raised : 

```
2019-03-05T08:47:56.006Z        ERROR   kubebuilder.controller  Reconciler error        {"controller": "elasticsearch-controller", "request": "default/elasticsearch-sample", "error": "services \"elasticsearch-sample-es-discovery\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: no RBAC policy matched, <nil>", "errorCauses": [{"error": "services \"elasticsearch-sample-es-discovery\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: no RBAC policy matched, <nil>"}]}
```

It is because Openshift requires to explicitly set some permissions on the `xxx/finalizers`, resources.
To fix the problem add the finalizers sub-resource to the RBAC.
For example : 

```
- apiGroups:
  - elasticsearch.k8s.elastic.co
  resources:
  - elasticsearchclusters
  - elasticsearchclusters/status
  - elasticsearchclusters/finalizers  <---- here
  - clusterlicenses
  - trustrelationships
  - users
  - users/status
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
```

## Users CRD

We should keep in mind that Openshift comes with its own `users` CRD, if a user want to manipulate Elasticsearch `users`  it should be done with the fully qualified name : 

```
(⎈ |default/192-168-99-100:8443/system:admin:default)➜  PR446 git:(e9496ac) ✗ k api-resources |grep users
users                                                elasticsearch.k8s.elastic.co            true         User
users                                                user.openshift.io                       false        User
```
See also https://github.com/elastic/k8s-operators/pull/446

## Default SCC does not allow privileged containers

SCC can be seen as the ancestor of [PSP](https://kubernetes.io/docs/concepts/policy/pod-security-policy/). Openshift clusters are deployed with a set of default SCCs.
The default SCC does not allow a pod/container to run in a privileged mode or to run with the `root` user (even worth, by default the containers are running with a random UID).
One (dirty) solution is to add the service account that need to be privileged in the `privileged` SCC : `oc adm policy add-scc-to-user privileged <sa>` 
A more proper way to do this would be to declare and deploy our own SCC (or PSP) to setup the right amount of privileges that are needed.
