### ISSUE TITLE
v8 sysctl permissions denied

### ISSUE THREAD

**Issue by mike-serchenia** [elastic/cloud-on-k8s#5410]
If using example from the documentation, upgrade from 7.17 to 8.0 fails with 
```
bootstrap check failure [1] of [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least...

sysctl: permission denied on key "vm.max_map_count", ignoring
```
example
```
          initContainers:
            - command:
                - sh
                - -c
                - sysctl -w vm.max_map_count=262144
              name: sysctl
              securityContext:
                privileged: true
```

solution
```
          initContainers:
            - command:
                - sh
                - -c
                - sysctl -w vm.max_map_count=262144
              name: sysctl
              image: busybox:1.28
              securityContext:
                privileged: true
```

**Comment by pebrc** [comment]
We should upgrade the documentation and make sure the init container example for setting this value still works with 8.0.

**Comment by barkbay** [comment]
We don't need to rely on the `busybox` image. Starting with 8.0 Elasticsearch container is not running as `root` anymore, which is required to run `sysctl`. You can add `runAsUser: 0` to force the init container to run as `root`:

```yaml
        initContainers:
          - command:
              - sh
              - -c
              - sysctl -w vm.max_map_count=262144
            name: sysctl
            securityContext:
              privileged: true
              runAsUser: 0
```

I'll create a PR to update the example in the doc.
