### ISSUE TITLE
Investigate why we do so many apiserver requests to reconcile a cluster

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#5450]
**We do ~900 apiserver requests to create a hot/warm/master 3xAZ (9 ssets) ES cluster + Kibana.**

I've been trying to grab numbers about how many requests we do to the apiserver to reconcile a "standard" cluster.
The approach I took was to patch the client go to log all requests being made:

```go
# main.go
type loggingRoundTripper struct {
	initialrt http.RoundTripper
}

var _ http.RoundTripper = loggingRoundTripper{}

func (l loggingRoundTripper) RoundTrip(r *http.Request) (*http.Response, error) {
	resp, err := l.initialrt.RoundTrip(r)
	fmt.Println("req", time.Now().Format("15:04:05"), r.Method, r.URL.RequestURI(), resp.StatusCode)
	return resp, err
}

(...)

# before creating the manager
cfg.WrapTransport = func(rt http.RoundTripper) http.RoundTripper {
		return loggingRoundTripper{initialrt: rt}
	}
```

With a manifest that looks like this:

```
# This sample sets up an Elasticsearch cluster and a Kibana instance preconfigured for that cluster
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
spec:
  version: 8.0.0
  nodeSets:
  - name: hot-zone0
    count: 1
    config:
      node.store.allow_mmap: false
  - name: hot-zone1
    count: 1
    config:
      node.store.allow_mmap: false
  - name: hot-zone2
    count: 1
    config:
      node.store.allow_mmap: false
  - name: warm-zone0
    count: 1
    config:
      node.store.allow_mmap: false
  - name: warm-zone1
    count: 1
    config:
      node.store.allow_mmap: false
  - name: warm-zone2
    count: 1
    config:
      node.store.allow_mmap: false
  - name: master-zone1
    count: 1
    config:
      node.store.allow_mmap: false
  - name: master-zone2
    count: 1
    config:
      node.store.allow_mmap: false
  - name: master-zone3
    count: 1
    config:
      node.store.allow_mmap: false
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-sample
spec:
  version: 8.0.0
  count: 2
  elasticsearchRef:
    name: "elasticsearch-sample"
```

We do 900 apiserver requests for these 2 resources to be fully reconciled (!!!): 
[logs.txt](https://github.com/elastic/cloud-on-k8s/files/8214353/logs.txt)

This seems way too many.
From a quick look, here are a few requests repeated over and over again that look like bugs in the operator:

* Updating PVCs: 56 times per individual  PVC. 500 requests here (!!).
```
req 12:38:04 PUT /api/v1/namespaces/default/persistentvolumeclaims/elasticsearch-data-elasticsearch-sample-es-hot-zone2-0?timeout=1m0s 200
req 12:38:04 PUT /api/v1/namespaces/default/persistentvolumeclaims/elasticsearch-data-elasticsearch-sample-es-master-zone3-0?timeout=1m0s 200
req 12:38:04 PUT /api/v1/namespaces/default/persistentvolumeclaims/elasticsearch-data-elasticsearch-sample-es-hot-zone0-0?timeout=1m0s 200
req 12:38:04 PUT /api/v1/namespaces/default/persistentvolumeclaims/elasticsearch-data-elasticsearch-sample-es-warm-zone1-0?timeout=1m0s 200
req 12:38:04 PUT /api/v1/namespaces/default/persistentvolumeclaims/elasticsearch-data-elasticsearch-sample-es-warm-zone2-0?timeout=1m0s 200
req 12:38:04 PUT /api/v1/namespaces/default/persistentvolumeclaims/elasticsearch-data-elasticsearch-sample-es-master-zone1-0?timeout=1m0s 200
req 12:38:04 PUT /api/v1/namespaces/default/persistentvolumeclaims/elasticsearch-data-elasticsearch-sample-es-hot-zone1-0?timeout=1m0s 200
req 12:38:04 PUT /api/v1/namespaces/default/persistentvolumeclaims/elasticsearch-data-elasticsearch-sample-es-warm-zone0-0?timeout=1m0s 200
req 12:38:04 PUT /api/v1/namespaces/default/persistentvolumeclaims/elasticsearch-data-elasticsearch-sample-es-master-zone2-0?timeout=1m0s 200
```

* Deleting secrets, ending up with an http error 404: 12 times per secret.  124 requests here (!!).
```
req 12:38:27 DELETE /api/v1/namespaces/default/secrets/elasticsearch-sample-es-license?timeout=1m0s 404
req 12:38:28 DELETE /api/v1/namespaces/default/secrets/elasticsearch-sample-es-secure-settings?timeout=1m0s 404
req 12:38:28 DELETE /api/v1/namespaces/default/secrets/elasticsearch-sample-es-transport-certificates?timeout=1m0s 404
```

* Creating secrets (not sure which ones): 34 requests.
```
req 12:37:04 POST /api/v1/namespaces/default/secrets?timeout=1m0s 201
req 12:37:04 POST /api/v1/namespaces/default/secrets?timeout=1m0s 201
req 12:37:04 POST /api/v1/namespaces/default/secrets?timeout=1m0s 201
req 12:37:04 POST /api/v1/namespaces/default/secrets?timeout=1m0s 201
```

* Deleting Kibana secure settings (?): 17 requests
```
req 12:37:12 DELETE /api/v1/namespaces/default/secrets/kibana-sample-kb-secure-settings?timeout=1m0s 404
req 12:37:13 DELETE /api/v1/namespaces/default/secrets/kibana-sample-kb-secure-settings?timeout=1m0s 404
req 12:37:13 DELETE /api/v1/namespaces/default/secrets/kibana-sample-kb-secure-settings?timeout=1m0s 404
req 12:37:14 DELETE /api/v1/namespaces/default/secrets/kibana-sample-kb-secure-settings?timeout=1m0s 404
req 12:37:14 DELETE /api/v1/namespaces/default/secrets/kibana-sample-kb-secure-settings?timeout=1m0s 404
req 12:37:15 DELETE /api/v1/namespaces/default/secrets/kibana-sample-kb-secure-settings?timeout=1m0s 404
```

* Updating Pods: 81 requests
```
req 12:37:21 PUT /api/v1/namespaces/default/pods/elasticsearch-sample-es-warm-zone0-0?timeout=1m0s 200
req 12:37:21 PUT /api/v1/namespaces/default/configmaps/elasticsearch-sample-es-unicast-hosts?timeout=1m0s 200
req 12:37:21 PUT /api/v1/namespaces/default/pods/elasticsearch-sample-es-master-zone1-0?timeout=1m0s 200
req 12:37:21 PUT /api/v1/namespaces/default/pods/elasticsearch-sample-es-master-zone3-0?timeout=1m0s 200
req 12:37:22 PUT /api/v1/namespaces/default/pods/elasticsearch-sample-es-hot-zone0-0?timeout=1m0s 200
req 12:37:22 PUT /api/v1/namespaces/default/pods/elasticsearch-sample-es-hot-zone1-0?timeout=1m0s 200
req 12:37:22 PUT /api/v1/namespaces/default/pods/elasticsearch-sample-es-hot-zone2-0?timeout=1m0s 200
req 12:37:22 PUT /api/v1/namespaces/default/pods/elasticsearch-sample-es-warm-zone0-0?timeout=1m0s 200
req 12:37:22 PUT /api/v1/namespaces/default/pods/elasticsearch-sample-es-warm-zone2-0?timeout=1m0s 200
req 12:37:22 PUT /api/v1/namespaces/default/pods/elasticsearch-sample-es-warm-zone1-0?timeout=1m0s 200
req 12:37:22 PUT /api/v1/namespaces/default/pods/elasticsearch-sample-es-master-zone2-0?timeout=1m0s 200
```
