### ISSUE TITLE
Allow existingSecret parameter for initial 'elastic' superuser

### ISSUE THREAD

**Issue by brsolomon-deloitte** [elastic/cloud-on-k8s#5460]
Chart such as https://github.com/bitnami/charts/tree/master/bitnami/elasticsearch offer an `existingSecret` parameter that can point to an existing secret containing credentials which, when specified, will take precedence and prevent an auto-generated secret.

Does the ECK CRD expose this functionality for the initial `elastic` user in any way, and if so, what would a minimal example look like?

I do realize [It is not recommended to use elastic user credentials for production use cases](https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-rotate-credentials.html) - but, that aside, it would still be nice to control the initial credentials if possible. For example, a common pattern is to use `ExternalSecrets` that point to a ground source of truth in somewhere like AWS Secrets Manager.

**Environment**

ECK 1.9.1, Elastic stack 7.17.1, K8s 1.21 on EKS

**Comment by brsolomon-deloitte** [comment]
After speaking with Elastic support, it looks like this is possible by pre-creating a `Secret` with the name `{{ cluster.name }}-es-elastic-user`, which ECK will look for to use as an existing Secret.

While this appears to work, **it is sub-optimal for several reasons**:

- It is implicit rather than explicit. Relying on an undocumented naming convention that occurs in Go code is prone to error and confusion. It would be better practice to allow the admin to explicitly point to an `existingSecret`.
- It is a GitOps anti-pattern. With the current design, there is no evidence as far as IaC goes of the k8s admin pointing to the existing Secret rather than allowing one to be auto-created
- It is (possibly) subject to a race condition. An example is with using `ExternalSecret` objects from [kubernetes-external-secrets](https://github.com/external-secrets/kubernetes-external-secrets). Namely, ECK will "race" against the  `ExternalSecret` first-creation of the `{{ cluster.name }}-es-elastic-user` Secret, with both fighting for control over the same secret.

**Comment by pebrc** [comment]
As you said yourself we discourage the use of the elastic user for any productive use. For some use cases it also no longer holds the necessary permissions (e.g. stack monitoring). 

We already have a declarative and predictable (and thus automatable) way to setup users through the file realm as documented here: https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-users-and-roles.html#k8s_file_realm
It has the advantage that you can also specify the roles the user should have and is therefore encouraging the use of minimal privileges. 

I do understand however that the fact the you would have to provide the bcrypt hash of the passwords in the secret that we use as the source for creating these users poses a burden for the GitOps/ ExternalSecrets approach you have mentioned in your post. We discussed this a bit out of band and I am wondering that if we were to make the creation of uses through the file realm easier by allowing you to specify simple key/value pairs in the secret where the key is the username and the value is the clear text password it would also address your use case.  

This was [already discussed back in the day](https://github.com/elastic/cloud-on-k8s/issues/728#issuecomment-582810869) when we first implemented support for the file realm in the ECK operator as possible next step in building out that feature. Consider this example for how this could potentially look in YAML: 

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
spec:
  version: 8.1.0
  auth:
    fileRealm:
    - secretName: es-users-file-realm
  nodeSets:
  - name: default
    count: 1
---
kind: Secret
apiVersion: v1
metadata:
  name: es-users-file-realm
stringData:
  # users_cleartext will be internally transformed into 'users' by ECK, with a hash of the provided passwords
  # (the current secret is kept unmodified by ECK)
 my-user:cleartextpassword
 users_roles: |-
    admin:my-user
```
