### ISSUE TITLE
Ensure generated yaml documents are validated

### ISSUE THREAD

**Issue by naemono** [elastic/cloud-on-k8s#5471]
We should probably validate our generated yaml files to ensure we at least maintain some consistency.  This has already caused failures in tooling: #5447 .  We could use something like `yamllint`, which would have caught our previous issue where document start markers were missing, and 2 documents were concatenated together without a break.

```
❯ cat .yamllint
rules:
  braces: enable
  brackets: enable
  colons: enable
  commas: enable
  comments:
    require-starting-space: true
    ignore-shebangs: true
    min-spaces-from-content: 1
  comments-indentation:
    level: warning
  document-end: disable
  document-start:
    present: true
  empty-lines: disable
  empty-values: disable
  hyphens: enable
  indentation:
    spaces: 2
    indent-sequences: whatever
  key-duplicates: enable
  key-ordering: disable
  line-length: disable
  new-line-at-end-of-file: enable
  new-lines: enable
  octal-values: disable
  quoted-strings: disable
  trailing-spaces: enable
  truthy:
    level: warning
❯ /Users/mmontgomery/Library/Python/3.8/bin/yamllint config/operator.yaml
config/operator.yaml
  2:1       error    missing document start "---"  (document-start)
❯ echo $?
1
```

This could be tied into our current CI checks
