### ISSUE TITLE
Adding custom annotations to secrets generated by ECK

### ISSUE THREAD

**Issue by vishnukv64** [elastic/cloud-on-k8s#5474]
**USE CASE**
In order to add custom annotations to secrets generated by ECK ( APM, elasticsearch etc.. ) like reflector annotations 
```
annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"  
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true" # Auto create reflection for matching namespaces
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "ns1,ns2,ns3" 
```
This functionality is currently missing. And copying secrets manually to all namespaces is quite tedious. It would be nice if this were to be added in future releases.

Example:
```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 7.15.0
  nodeSets:
  - name: default
    count: 4
    config:
      node.store.allow_mmap: false
    podTemplate:
      spec:
        secretTemplate:
          annotations:
            reflector.v1.k8s.emberstack.com/reflection-allowed: "true"  
            reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
            reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "ns1,ns2,ns3"
        containers:
          - name: elasticsearch
            # specify resource limits and requests
            resources:
              limits:
                cpu: 4
                memory: 8Gi
              requests:
                cpu: 4
                memory: 8Gi   
            env:
            - name: ES_JAVA_OPTS 
              value: "-Xms4g -Xmx4g"       
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
```
Thanks,
Vishnu

**Comment by barkbay** [comment]
Somewhat related to https://github.com/elastic/cloud-on-k8s/issues/2652 (related old PR: https://github.com/elastic/cloud-on-k8s/pull/3186)

**Comment by pebrc** [comment]
We discussed this a bit out of band. One concern that came up is that it seems the use case here is to copy secrets across namespaces with [Reflector](https://github.com/emberstack/kubernetes-reflector). The problem with that is that adding a `secretTemplate` would add the metadata controlling the copying of secrets to **all** secrets the ECK operator creates and thus all secrets would be copied to the allowed namespaces. 

The problem with is that it would copy also a bunch of internal secrets the operator uses to orchestrate Elasticsearch that have no purpose in other namespaces or in case of certificate secrets contain private keys that we do not want to be copied to other namespaces. 

Coming back once more to your use case I am assuming that the motivation for copying the secrets is to allow clients in other namespaces to connect to Elasticsearch by providing them with the necessary credentials and CA certificates that are necessary in order to establish a connection. One way to achieve that today without adding any additional features to the operator would be to pre-create empty secrets with the reflector metadata. The operator will then adopt those preserving the metadata you added. To give a minimal example, consider the following: 

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-es-elastic-user
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"  
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "ns1,ns2,ns3"
type: Opaque 
---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-es-http-certs-public
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"  
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "ns1,ns2,ns3"
type: Opaque 
```

Then create the cluster:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 8.1.0
  nodeSets:
  - name: default
    count: 3
```

The operator will find the secrets created earlier and preserve the reflector metadata. This will then lead to only the two relevant secrets, the user secret and the certificates, to be copied to the other namespaces.

**Comment by vishnukv64** [comment]
Thanks @pebrc . The example you gave worked like a charm. It would be nice if you could add this to the official documentation. As copying secrets to other namespaces is kinda very vague in the docs.
Your help is much appreciated.

**Comment by brat002** [comment]
This will not work for ArgoCD/Flux/other gitops tools.

**Comment by oussemabhouri** [comment]
@brat002  did you find a way to make it work with flux?

**Comment by bartlaarhoven** [comment]
In Flux, this indeed didn't work out-of-the-box. Instead, what I did, was execute two `kubectl` commands to make it work.

First create the mirror-secret manually by committing the following file to Flux:

```
---
apiVersion: v1
kind: Secret
metadata:
 name: elasticsearch-es-http-certs-public
 namespace: app
 annotations:
   reflector.v1.k8s.emberstack.com/reflects: "es/elasticsearch-es-http-certs-public"
data:
  foo: YmFy
```

with `es` the namespace where Elasticsearch is deployed, and `app` the namespace of my app.

And then two `kubectl` commands to allow and start reflection:

```
# Allow reflection
kubectl annotate secret -n es elasticsearch-es-http-certs-public reflector.v1.k8s.emberstack.com/reflection-allowed=true
# Set the reflected version to empty string to force initial reflection
kubectl annotate secret -n app elasticsearch-es-http-certs-public reflector.v1.k8s.emberstack.com/reflected-version=""
```

Of course you could also add the allowed-namespaces annotation, and use auto-namespaces, as you wish.
