### ISSUE TITLE
enable beats monitoring in ECK

### ISSUE THREAD

**Issue by sophiaxu8** [elastic/cloud-on-k8s#5563]
With the [stack monitoring](https://www.elastic.co/guide/en/cloud-on-k8s/2.1/k8s-stack-monitoring.html#k8s-stack-monitoring) enabled for ECK cluster, this simplify the whole stack monitoring config.
 it would be good to have the similar function for beats monitoring enabled. 
Currently have to add the following in beats yaml file:
```
---
apiVersion: [beat.k8s.elastic.co/v1beta1](https://beat.k8s.elastic.co/v1beta1)
kind: Beat
metadata:
  name: aws
  namespace: eck
spec:
  type: filebeat
  version: 7.16.3
  config:
    name: beat-aws
  monitoring:
    enabled: true
    elasticsearch:
      hosts: ["[https://${MONITORING_CLUSTERNAME_ES_HTTP_SERVICE_HOST}:${MONITORING_CLUSTERNAME_ES_HTTP_SERVICE_PORT}]
      username: ${ES_USER}
      password: ${ES_PASSWORD}
      ssl.certificate_authorities: ["/etc/pki/root/tls.crt"]
      ssl.verification_mode: certificate
```
