### ISSUE TITLE
Document OIDC setup 

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#5631]
We could introduce a page that covers the diff between https://www.elastic.co/guide/en/elasticsearch/reference/current/oidc-guide.html and how it is done on Kubernetes. I think it is only the mounting of configuration files in a Pod through Secrets and ConfigMaps but it might still be helpful for some users.

**Comment by RoseSecurity** [comment]
@pebrc Would we be able to revisit this? Haven't found consistent documentation on how this structure is passed into the helm charts. If we could standardize in this area, that would be awesome

**Comment by RoseSecurity** [comment]
@naemono Would it be beneficial to add documentation on this to the Elasticsearch and Kibana helm charts or `docs` directory?

Such as:

```yaml
          nodeSets:
            - name: master
              count: 
              config:
                xpack:
                  security:
                    audit:
                      enabled: true
                    authc:
                      realms:
                        oidc:
                          oidc1:
                            claims:
                              groups:
                              principal:
                            op:
                              authorization_endpoint: 
                              endsession_endpoint: 
                              issuer: 
                              userinfo_endpoint: 
                              jwkset_path: 
                              token_endpoint: 
                            order: 2
                            rp:
                              client_id:
                              post_logout_redirect_uri: 
                              redirect_uri: 
                              requested_scopes:
                              response_type:
                      token.enabled:
```
