### ISSUE TITLE
Documentation update when settings some transport settings.

### ISSUE THREAD

**Issue by naemono** [elastic/cloud-on-k8s#5707]
Recent issue found when user was modifying the transport port settings:

```
transport:
  service:
    spec:
      ports:
      - name: tls-transport
        port: 9302
        protocol: TCP
        targetPort: 9302
      type: ClusterIP
```

That it wasn't completely clear that the Elasticsearch `nodeSets` configuration also had to be adjusted to work properly:

```
  nodeSets:
    - config:
        node.roles:
          - master
        transport.port: 9302
      name: default
```

We should update our documentation to try and make this more clear.
