### ISSUE TITLE
Node type is incorrect in Kibana monitoring details page

### ISSUE THREAD

**Issue by noslowerdna** [elastic/cloud-on-k8s#5782]
## Bug Report

**What did you do?**

In Kibana, navigated to `Stack Monitoring` > `Clusters` > `{cluster-name}` > `Nodes` > `{data-node-name}`

**What did you expect to see?**

`Type` = `Data Node`

Because this node only possesses the "data" role.

```
  - config:
      node.roles:
      - data
```

**What did you see instead? Under which circumstances?**

`Type` = `Master Node` (always)

<img width="1330" alt="Screen Shot 2022-06-15 at 4 56 22 PM" src="https://user-images.githubusercontent.com/930946/173940930-04ebef26-bb55-4d99-8c2d-8d42bf995992.png">

**Environment**

* ECK version: 2.2.0

* Kubernetes information:

On premise 

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.6", GitCommit:"d921bc6d1810da51177fbd0ed61dc811c5228097", GitTreeState:"clean", BuildDate:"2021-10-27T17:44:26Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
```

* Resource definition:
```
# Source: elasticsearch-helm-chart/templates/elasticsearch.yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: my-test-cluster
  namespace: elasticsearch
spec:
  version: 8.2.3
  http:
    service:
      metadata:
      spec:
        type: NodePort
  monitoring:
    metrics:
      elasticsearchRefs:
      - name: my-monitoring-cluster
        namespace: elasticsearch
    logs:
      elasticsearchRefs:
      - name: my-monitoring-cluster
        namespace: elasticsearch
  nodeSets:
  - name: master-nodes
    count: 1
    config:
      node.roles: ["master"]
      node.store.allow_mmap: false
    podTemplate:
      metadata:
        annotations:
          test-annotation: test-annotation-value
      spec:
        containers:
        - name: elasticsearch
          resources:
            requests:
              cpu: 1
              memory: 4Gi
            limits:
              cpu: 1
              memory: 4Gi
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 4Gi
  - name: data-nodes
    count: 1
    config:
      node.roles: ["data"]
      node.store.allow_mmap: false
    podTemplate:
      metadata:
        annotations:
          test-annotation: test-annotation-value
      spec:
        containers:
        - name: elasticsearch
          resources:
            requests:
              cpu: 1
              memory: 4Gi
            limits:
              cpu: 1
              memory: 4Gi
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 32Gi
  auth:
    fileRealm:
    - secretName: my-test-cluster-es-users
    roles:
    - secretName: my-test-cluster-es-roles
```

* Logs: N/A
