### ISSUE TITLE
kibana Unable to connect to Elasticsearch

### ISSUE THREAD

**Issue by m1iktea** [elastic/cloud-on-k8s#5794]
## Bug Report
**What did you do?**
deploy Elasticsearch and Kibana in ECK
**What did you expect to see?**
Elasticsearch and Kibana work
**What did you see instead? Under which circumstances?**

**Environment**

* ECK version:
v2.1
* Kubernetes information:
local Kubernetes cluster
kubernetes v1.19.11

* Resource definition:
es.yaml
```
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: ok-es
  namespace: elastic-system
spec:
  version: 7.9.3
  nodeSets:
  - name: default
    podTemplate:
        metadata:
          creationTimestamp: null
        spec:
          initContainers:
            - command:
                - sh
                - '-c'
                - sysctl -w vm.max_map_count=262144
              name: sysctl
              resources: {}
              securityContext:
                privileged: true
    volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
            storageClassName: rook-cephfs
    count: 1
    config:
        node.data: true
        node.ingest: true
        node.master: true
  http:
    tls:
      selfSignedCertificate:
         disabled: true
```
kibana.yaml
```
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: xkl-kibana
  namespace: elastic-system
spec:
  version: 7.9.3
  count: 1
  elasticsearchRef:
    name: ok-es
    namespace: elastic-system 
  http:
    tls:
      selfSignedCertificate:
         disabled: true
```
* Logs:
kibana logs
```
{"type":"log","@timestamp":"2022-06-17T08:32:05Z","tags":["warning","plugins-discovery"],"pid":6,"message":"Expect plugin \"id\" in camelCase, but found: beats_management"}
{"type":"log","@timestamp":"2022-06-17T08:32:05Z","tags":["warning","plugins-discovery"],"pid":6,"message":"Expect plugin \"id\" in camelCase, but found: triggers_actions_ui"}
[BABEL] Note: The code generator has deoptimised the styling of /usr/share/kibana/x-pack/plugins/canvas/server/templates/pitch_presentation.js as it exceeds the max of 500KB.
{"type":"log","@timestamp":"2022-06-17T08:33:20Z","tags":["info","plugins-service"],"pid":6,"message":"Plugin \"visTypeXy\" is disabled."}
{"type":"log","@timestamp":"2022-06-17T08:33:20Z","tags":["info","plugins-service"],"pid":6,"message":"Plugin \"auditTrail\" is disabled."}
{"type":"log","@timestamp":"2022-06-17T08:33:21Z","tags":["warning","config","deprecation"],"pid":6,"message":"\"xpack.monitoring.ui.container.elasticsearch.enabled\" is deprecated and has been replaced by \"monitoring.ui.container.elasticsearch.enabled\""}
{"type":"log","@timestamp":"2022-06-17T08:33:21Z","tags":["warning","config","deprecation"],"pid":6,"message":"\"xpack.monitoring\" is deprecated and has been replaced by \"monitoring\". However both key are present, ignoring \"xpack.monitoring\""}
{"type":"log","@timestamp":"2022-06-17T08:33:21Z","tags":["warning","config","deprecation"],"pid":6,"message":"Config key [monitoring.cluster_alerts.email_notifications.email_address] will be required for email notifications to work in 8.0.\""}
{"type":"log","@timestamp":"2022-06-17T08:33:21Z","tags":["info","plugins-system"],"pid":6,"message":"Setting up [92] plugins: [taskManager,licensing,observability,globalSearch,globalSearchProviders,code,usageCollection,ossTelemetry,telemetryCollectionManager,telemetry,telemetryCollectionXpack,kibanaUsageCollection,newsfeed,mapsLegacy,kibanaLegacy,translations,timelion,share,legacyExport,esUiShared,charts,bfetch,expressions,data,home,cloud,console,consoleExtensions,apmOss,searchprofiler,painlessLab,grokdebugger,management,upgradeAssistant,licenseManagement,watcher,indexPatternManagement,advancedSettings,fileUpload,dataEnhanced,savedObjects,visualizations,inputControlVis,visualize,visTypeVega,visTypeVislib,visTypeTimelion,features,security,snapshotRestore,reporting,enterpriseSearch,encryptedSavedObjects,ingestManager,indexManagement,remoteClusters,crossClusterReplication,indexLifecycleManagement,beats_management,transform,ingestPipelines,maps,graph,canvas,visTypeTimeseries,rollup,visTypeTagcloud,visTypeTable,visTypeMetric,visTypeMarkdown,tileMap,regionMap,discover,discoverEnhanced,dashboard,lens,dashboardMode,savedObjectsManagement,spaces,lists,eventLog,actions,case,alerts,alertingBuiltins,ml,securitySolution,infra,monitoring,logstash,apm,uptime]"}
{"type":"log","@timestamp":"2022-06-17T08:33:22Z","tags":["warning","plugins","security","config"],"pid":6,"message":"Session cookies will be transmitted over insecure connections. This is not recommended."}
{"type":"log","@timestamp":"2022-06-17T08:33:22Z","tags":["info","plugins","monitoring","monitoring"],"pid":6,"message":"config sourced from: production cluster"}
{"type":"log","@timestamp":"2022-06-17T08:33:23Z","tags":["info","savedobjects-service"],"pid":6,"message":"Waiting until all Elasticsearch nodes are compatible with Kibana before starting saved objects migrations..."}
{"type":"log","@timestamp":"2022-06-17T08:33:23Z","tags":["warning","plugins","reporting","config"],"pid":6,"message":"Chromium sandbox provides an additional layer of protection, but is not supported for Linux Centos 7.8.2003 OS. Automatically setting 'xpack.reporting.capture.browser.chromium.disableSandbox: true'."}
{"type":"log","@timestamp":"2022-06-17T08:33:23Z","tags":["info","savedobjects-service"],"pid":6,"message":"Starting saved objects migrations"}
{"type":"log","@timestamp":"2022-06-17T08:33:23Z","tags":["info","savedobjects-service"],"pid":6,"message":"Creating index .kibana_task_manager_1."}
{"type":"log","@timestamp":"2022-06-17T08:33:23Z","tags":["info","savedobjects-service"],"pid":6,"message":"Creating index .kibana_1."}
{"type":"log","@timestamp":"2022-06-17T08:33:49Z","tags":["info","savedobjects-service"],"pid":6,"message":"Pointing alias .kibana_task_manager to .kibana_task_manager_1."}
{"type":"log","@timestamp":"2022-06-17T08:33:53Z","tags":["warning","savedobjects-service"],"pid":6,"message":"Unable to connect to Elasticsearch. Error: Request Timeout after 30000ms"}
{"type":"log","@timestamp":"2022-06-17T08:34:09Z","tags":["warning","savedobjects-service"],"pid":6,"message":"Unable to connect to Elasticsearch. Error: [resource_already_exists_exception] index [.kibana_1/w2-uaZQ3QhqRW2fqrO-6RA] already exists, with { index_uuid=\"w2-uaZQ3QhqRW2fqrO-6RA\" & index=\".kibana_1\" }"}
{"type":"log","@timestamp":"2022-06-17T08:34:09Z","tags":["warning","savedobjects-service"],"pid":6,"message":"Another Kibana instance appears to be migrating the index. Waiting for that migration to complete. If no other Kibana instance is attempting migrations, you can get past this message by deleting index .kibana_1 and restarting Kibana."}
{"type":"log","@timestamp":"2022-06-17T08:34:09Z","tags":["info","savedobjects-service"],"pid":6,"message":"Finished in 46164ms."}
```
* What i try:
check elasticsearch cluster
```
curl -u "elastic:$PASSWORD" -k 'elasticsearch.host'
```
```
{
  "name" : "xxxxxxxxxxxxx-es-default-0",
  "cluster_name" : "xxxxxxxxxxxx",
  "cluster_uuid" : "F6eBjOVjR0ifwpt9VR443A",
  "version" : {
    "number" : "7.9.3",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "c4138e51121ef06a6404866cddc601906fe5c868",
    "build_date" : "2020-10-16T10:36:16.141335Z",
    "build_snapshot" : false,
    "lucene_version" : "8.6.2",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```
try delete index in logs
```
curl -u "elastic:$PASSWORD" -k -XDELETE 'elasticsearch.host/.kibana*'
```
try clean everything and start over again , but its happened again
