### ISSUE TITLE
Reconciliation error when creating cluster

### ISSUE THREAD

**Issue by danielbichuetti** [elastic/cloud-on-k8s#5866]
## Bug Report
**What did you do?**
When trying to deploy an scoped es cluster, operator pods is returning this error and not creating the cluster.
**What did you expect to see?**
Operator create CR
**What did you see instead? Under which circumstances?**
ES cluster doesn't get deployed
**Environment**

* ECK version:

2.3.0

* Kubernetes information:

```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-17T22:28:26Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"5a97ee6d15525f6e4a1c2646bf1dfd2ebd5220b5", GitTreeState:"clean", BuildDate:"2022-06-15T04:26:33Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
```

* Resource definition:
```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-cluster
  namespace: elastic-system-d11466a7
spec:
  version: 8.2.2
  secureSettings:
    - secretName: aws-s3-secret
    - secretName: azure-storage-secret
  nodeSets:
  - name: default
    count: 3
    config:
      node.store.allow_mmap: true
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
        storageClassName: gp2
  http:
    service:
      spec:
        type: LoadBalancer
    tls:
      certificate:
        secretName: es-cluster-certificate
  #transport:
```

* Logs:
```
"log.level":"info","@timestamp":"2022-07-07T20:11:11.247Z","log.logger":"elasticsearch-controller","message":"Ending reconciliation run","service.version":"2.3.0+a5aadbdc","service.type":"eck","ecs.version":"1.4.0","iteration":11,"namespace":"elastic-system-b2e89363","es_name":"intelijus","took":0.019394786}
{"log.level":"info","@timestamp":"2022-07-07T20:11:11.247Z","log.logger":"elasticsearch-controller","message":"Starting reconciliation run","service.version":"2.3.0+a5aadbdc","service.type":"eck","ecs.version":"1.4.0","iteration":12,"namespace":"elastic-system-b2e89363","es_name":"intelijus"}
{"log.level":"error","@timestamp":"2022-07-07T20:11:11.247Z","log.logger":"elasticsearch-controller","message":"Elasticsearch manifest validation failed","service.version":"2.3.0+a5aadbdc","service.type":"eck","ecs.version":"1.4.0","namespace":"elastic-system-b2e89363","es_name":"intelijus","error":"Elasticsearch.elasticsearch.k8s.elastic.co \"intelijus\" is invalid: name: Invalid value: \"name\": name field found in the kubectl.kubernetes.io/last-applied-configuration annotation is unknown. This is often due to incorrect indentation in the manifest.","error.stack_trace":"github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch.(*ReconcileElasticsearch).internalReconcile\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/elasticsearch_controller.go:258\ngithub.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch.(*ReconcileElasticsearch).Reconcile\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/controller/elasticsearch/elasticsearch_controller.go:187\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go:121\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go:320\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go:234"}
{"log.level":"info","@timestamp":"2022-07-07T20:11:11.247Z","log.logger":"elasticsearch-controller","message":"Ending reconciliation run","service.version":"2.3.0+a5aadbdc","service.type":"eck","ecs.version":"1.4.0","iteration":12,"namespace":"elastic-system-b2e89363","es_name":"intelijus","took":0.0003455}

```
