### ISSUE TITLE
Kibana Readiness Probe assumes HTTPS regardless of other options

### ISSUE THREAD

**Issue by Woovie** [elastic/cloud-on-k8s#5875]
## Bug Report
**What did you do?**

I am using this example file to create an ECK stack:

https://github.com/elastic/cloud-on-k8s/blob/main/config/recipes/elastic-agent/fleet-kubernetes-integration.yaml

I've made one change, setting `spec.config.server.ssl.enabled: false` to let my ingress handle HTTPS, here's the top lines of my YAML until that point:

```yaml
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 8.2.0
  count: 1
  elasticsearchRef:
    name: elasticsearch
  config:
    server.ssl.enabled: false
```

**What did you expect to see?**

Kibana correctly deploy without issue.

**What did you see instead? Under which circumstances?**

The pod never passes readiness checks due to still trying to use HTTPS.

```
kubectl describe pod/kibana-kb-684466f787-zrrnz | grep 'Events' -A10
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  17m                    default-scheduler  Successfully assigned default/kibana-kb-684466f787-zrrnz to akira
  Normal   Pulled     17m                    kubelet            Container image "docker.elastic.co/kibana/kibana:8.2.0" already present on machine
  Normal   Created    17m                    kubelet            Created container elastic-internal-init-config
  Normal   Started    17m                    kubelet            Started container elastic-internal-init-config
  Normal   Pulled     17m                    kubelet            Container image "docker.elastic.co/kibana/kibana:8.2.0" already present on machine
  Normal   Created    17m                    kubelet            Created container kibana
  Normal   Started    17m                    kubelet            Started container kibana
  Warning  Unhealthy  2m32s (x102 over 17m)  kubelet            Readiness probe failed: Get "https://10.42.0.181:5601/login": http: server gave HTTP response to HTTPS client
```

This seems to be caused by this line:

https://github.com/elastic/cloud-on-k8s/blob/main/pkg/controller/kibana/driver_test.go#L579

**Comment by Woovie** [comment]
As a workaround, I edited the deployment created by the Kibana object.

```
jbanasik@akira:~/k8s/eck$ diff kibana-kb-deployment.original.yaml kibana-kb-deployment.yaml
54c54
<           name: https
---
>           name: http
61c61
<             scheme: HTTPS
---
>             scheme: HTTP
```

```
jbanasik@akira:~/k8s/eck$ grep -i 'HTTPS' kibana-kb-deployment.original.yaml -C3
        name: kibana
        ports:
        - containerPort: 5601
          name: https
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /login
            port: 5601
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
```
