### ISSUE TITLE
All shards are unassigned in Elasticsearch

### ISSUE THREAD

**Issue by Digindataflow** [elastic/cloud-on-k8s#5882]
## Bug Report
**What did you do?**

Follow the example given in https://www.elastic.co/guide/en/cloud-on-k8s/current, set up elasticsearch and kibana in same cluster.  

**What did you expect to see?**

Kibana and elasticsearch could be set up. 

**What did you see instead? Under which circumstances?**

For Kibana

```
[ERROR][savedobjects-service] [.kibana_task_manager] Action failed with 'Request timed out'. Retrying attempt 3 in 8 seconds.
[ERROR][plugins.ruleRegistry] Error: Timeout: it took more than 1200000ms
```

For Elasricsearch 

```
"allocate_explanation":"Elasticsearch isn't allowed to allocate this shard to any of the nodes in the cluster. Choose a node to which you expect this shard to be allocated, find this node in the node-by-node explanation, and address the reasons which prevent Elasticsearch from allocating this shard there."

```

All shards are unassigned

```
.kibana_8.3.2_001                                             0 p UNASSIGNED    
.kibana_8.3.2_001                                             0 r UNASSIGNED    
.ds-ilm-history-5-2022.07.19-000001                           0 p UNASSIGNED    
.kibana_task_manager_8.3.2_001                                0 p UNASSIGNED    
.kibana_task_manager_8.3.2_001                                0 r UNASSIGNED    
.ds-.logs-deprecation.elasticsearch-default-2022.07.19-000001 0 p UNASSIGNED    
.ds-.logs-deprecation.elasticsearch-default-2022.07.19-000001 0 r UNASSIGNED    
```

**Environment**

* ECK version: 2.3

* Kubernetes information: AKS 1.22.4

* Resource definition:
```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: elastic-system
spec:
  version: 8.3.2
  volumeClaimDeletePolicy: DeleteOnScaledownOnly
  nodeSets:
    - name: master-nodes
      count: 3
      config:
        node.roles: ["master"]
      podTemplate:
        spec:
          # allow increased mmap
          initContainers:
          - name: sysctl
            securityContext:
              privileged: true
              runAsUser: 0
            command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
          containers:
          - name: elasticsearch
            # specify resource limits and requests
            resources:
              limits:
                memory: 4Gi
                cpu: 1
            env:
            - name: ES_JAVA_OPTS
              value: "-Xms2g -Xmx2g"
      volumeClaimTemplates:
        - metadata:
            # Do not change this name
            name: elasticsearch-data
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
            storageClassName: custom-azurefile-csi
            selector:
              matchLabels: 
                app: elasticsearch

apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic-system
spec:
  version: 8.3.2
  count: 1
  elasticsearchRef:
    name: elasticsearch
    namespace: elastic-system
  http:
   service:
     spec:
       type: ClusterIP
  podTemplate:
    spec:
      containers:
        - name: kibana
          env:
            - name: NODE_OPTIONS
              value: "--max-old-space-size=2048"
          resources:
            requests:
              memory: 1Gi
              cpu: 0.5
            limits:
              memory: 2Gi
              cpu: 1
```

* Logs:
```
Events:
  Type     Reason     Age                From     Message
  ----     ------     ----               ----     -------
  Normal   Pulled     42m (x3 over 87m)  kubelet  Container image "docker.elastic.co/kibana/kibana:8.3.2" already present on machine
  Normal   Created    42m (x3 over 87m)  kubelet  Created container kibana
  Normal   Started    42m (x3 over 87m)  kubelet  Started container kibana
  Warning  Unhealthy  41m (x2 over 87m)  kubelet  Readiness probe failed: Get "https://44.129.1.21:5601/login": dial tcp 44.129.1.21:5601: connect: connection refused
```

* Result from index `kibana_task_manager`

```
    ".kibana_task_manager_8.3.2_001": {
        "aliases": {},
        "mappings": {
            "dynamic": "strict",
            "_meta": {
                "migrationMappingPropertyHashes": {
                    "migrationVersion": "4a1746014a75ade3a714e1db5763276f",
                    "originId": "2f4316de49999235636386fe51dc06c1",
                    "task": "c716c8022373e7b7fea04dc9a9ff5c70",
                    "updated_at": "00da57df13e94e9d98437d13ace4bfe0",
                    "references": "7997cf5a56cc02bdc9c93361bde732b0",
                    "namespace": "2f4316de49999235636386fe51dc06c1",
                    "coreMigrationVersion": "2f4316de49999235636386fe51dc06c1",
                    "type": "2f4316de49999235636386fe51dc06c1",
                    "namespaces": "2f4316de49999235636386fe51dc06c1"
                }
            },
            "properties": {
                "coreMigrationVersion": {
                    "type": "keyword"
                },
                "migrationVersion": {
                    "type": "object",
                    "dynamic": "true"
                },
                "namespace": {
                    "type": "keyword"
                },
                "namespaces": {
                    "type": "keyword"
                },
                "originId": {
                    "type": "keyword"
                },
                "references": {
                    "type": "nested",
                    "properties": {
                        "id": {
                            "type": "keyword"
                        },
                        "name": {
                            "type": "keyword"
                        },
                        "type": {
                            "type": "keyword"
                        }
                    }
                },
                "task": {
                    "properties": {
                        "attempts": {
                            "type": "integer"
                        },
                        "ownerId": {
                            "type": "keyword"
                        },
                        "params": {
                            "type": "text"
                        },
                        "retryAt": {
                            "type": "date"
                        },
                        "runAt": {
                            "type": "date"
                        },
                        "schedule": {
                            "properties": {
                                "interval": {
                                    "type": "keyword"
                                }
                            }
                        },
                        "scheduledAt": {
                            "type": "date"
                        },
                        "scope": {
                            "type": "keyword"
                        },
                        "startedAt": {
                            "type": "date"
                        },
                        "state": {
                            "type": "text"
                        },
                        "status": {
                            "type": "keyword"
                        },
                        "taskType": {
                            "type": "keyword"
                        },
                        "traceparent": {
                            "type": "text"
                        },
                        "user": {
                            "type": "keyword"
                        }
                    }
                },
                "type": {
                    "type": "keyword"
                },
                "updated_at": {
                    "type": "date"
                }
            }
        },
        "settings": {
            "index": {
                "routing": {
                    "allocation": {
                        "include": {
                            "_tier_preference": "data_content"
                        }
                    }
                },
                "refresh_interval": "1s",
                "hidden": "true",
                "number_of_shards": "1",
                "auto_expand_replicas": "0-1",
                "provided_name": ".kibana_task_manager_8.3.2_001",
                "creation_date": "1658255915514",
                "priority": "10",
                "number_of_replicas": "1",
                "uuid": "X-YlFkygQ36n1liMPUv6Cw",
                "version": {
                    "created": "8030299"
                }
            }
        }
    }
```
