### ISSUE TITLE
Cannot deploy Fleet Server with a secure elasticsearch on k8s

### ISSUE THREAD

**Issue by Mehranh** [elastic/cloud-on-k8s#5888]
Hello 

I want to deploy a Fleet server on K8S but I get the following error , Would you please advise me how I can sort this out?
Is there any way I can change elasticsearch host in the yaml file?
Error:

`{"file.name":"cmd/enroll_cmd.go","file.line":792},"message":"Fleet Server - Error - x509: certificate is valid for elastic.mydomain.io, not elasticsearch-es-http.default.svc","ecs.version":"1.6.0"}`

Fleet:

```
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: fleet-agent

spec:
  version: 8.3.2
  elasticsearchRefs:
    - name: elasticsearch   
  mode: fleet
  fleetServerEnabled: true
  http:
    service:
      spec:
         type: ClusterIP
  daemonSet:
    podTemplate:
      spec:
        automountServiceAccountToken: true
        serviceAccountName: elastic-agent
        mode: fleet
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elastic-agent
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - namespaces
  - pods
  - nodes
  - nodes/metrics
  - nodes/proxy
  - nodes/stats
  - events
  - configmaps
  - services
  - endpoints
  - deployments
  - storages
  verbs:
  - get
  - watch
  - list
- nonResourceURLs:
  - /metrics
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["coordination.k8s.io"]
  #
  # at the HTTP level, the name of the resource for accessing Job
  # objects is "jobs"
  resources:
  - leases
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elastic-agent
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: elastic-agent
subjects:
- kind: ServiceAccount
  name: elastic-agent
  namespace: default
roleRef:
  kind: ClusterRole
  name: elastic-agent
  apiGroup: rbac.authorization.k8s.io

```

Elastic:

```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 8.3.2
  nodeSets:
  - name: default
    count: 3
    config:
      # most Elasticsearch configuration parameters are possible to set, e.g: node.attr.attr_name: attr_value
      node.roles: ["master", "data", "ingest", "ml"]
      # this allows ES to run on nodes even if their vm.max_map_count has not been increased, at a performance cost
      node.store.allow_mmap: false
      path.repo: ["/"]
    podTemplate:
      metadata:
        labels:
          app: elasticsearch
                         
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 4Gi
  http:
    tls:
      certificate:
        secretName: elastic-tls           
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/issuer: "letsencrypt-prod"
        ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    name: elastic-ingress
    namespace: default
spec:
    rules:
        - host: elastic.mydomain.io
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: elasticsearch-es-http
                            port:
                                number: 9200
    tls:
        - hosts:
              - elastic.mydomain.io
          secretName: elastic-tls
```

**Comment by pebrc** [comment]
@Mehranh one option would be to use your Let's encrypt certificate only for the Ingress resource and rely on the self-signed certificates for traffic between the Ingress and Elasticsearch as well as between Fleet Server and Elasticsearch. In practical terms that would mean to remove the http configuration from the Elasticsearch resource.

```yaml
 http:
    tls:
      certificate:
        secretName: elastic-tls 
```

**Comment by Mehranh** [comment]
I've tried it before, when I remove that line I get this error in the Fleep pod

` cp: cannot create regular file '/usr/local/share/ca-certificates/ca.crt': Permission denied
`

**Comment by pebrc** [comment]
https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-elastic-agent-fleet-known-limitations.html Fleet/Agent has to run as root due to the way we manage trust for the Agents.

**Comment by Mehranh** [comment]
since I am working on AKS, can you kindly advise me on how I can do it?

**Comment by naemono** [comment]
Example for running as root is here:
https://github.com/elastic/cloud-on-k8s/blob/main/config/recipes/elastic-agent/fleet-apm-integration.yaml#L106-L107

```
    podTemplate:
      spec:
        securityContext:
          runAsUser: 0
```

**Comment by Mehranh** [comment]
Holy Shit! it works , thanks so much guys

**Comment by pebrc** [comment]
Just for posterity another option would have been to configure Fleet and Agent to go through the Ingress. While this is technically possible it is usually not a desirable solution as traffic is leaving the K8s cluster and re-entering through the Ingress with usually extra data transfer costs etc and potential security implications if traffic filters are in use etc.. 

To make this work both `FLEET_SERVER_ELASTICSEARCH_HOST` and `xpack.fleet.elasticsearch.hosts` have to be adjusted: 

```yaml
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: fleet-server
spec:
  version: 8.3.1
  kibanaRef:
    name: kibana
  elasticsearchRefs:
  - name: elasticsearch
  mode: fleet
  fleetServerEnabled: true
  deployment:
    replicas: 1
    podTemplate:
      spec:
        serviceAccountName: fleet-server
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0
        containers:
        - name: agent
          env:
          - name: FLEET_SERVER_ELASTICSEARCH_HOST
            value: https://elastic.mydomain.io:443
----
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 8.3.2
  count: 1
  elasticsearchRef:
    name: elasticsearch
  config:
    xpack.fleet.agents.elasticsearch.hosts: ["https://elastic.mydomain.io:443"]
... snip
```
