### ISSUE TITLE
Stack Monitoring certificate validation on beats

### ISSUE THREAD

**Issue by mens1205** [elastic/cloud-on-k8s#5917]
## Bug Report
**What did you do?**
I setup Stack monitoring as described here: [Stack Monitoring](https://www.elastic.co/guide/en/cloud-on-k8s/2.3/k8s-stack-monitoring.html)

Config looks like this:

```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: elastic
spec:
  version: 8.3.2
[...]
  monitoring:
    metrics:
      elasticsearchRefs:
      - name: elasticsearch
    logs:
      elasticsearchRefs:
      - name: elasticsearch
[...]
  http:
    tls:
      certificate:
        secretName: elasticsearch-certificate
```

**What did you expect to see?**

I expected that metricbeat and filebeat are able to connect to elasticsearch.

**What did you see instead? Under which circumstances?**

I received the following error message:

`{"log.level":"error","@timestamp":"2022-07-28T13:26:36.239Z","log.logger":"publisher_pipeline_output","log.origin":{"file.name":"pipeline/client_worker.go","file.line":150},"message":"Failed to connect to backoff(elasticsearch(https://elasticsearch-es-http.elastic.svc:9200)): Get \"https://elasticsearch-es-http.elastic.svc:9200\": x509: certificate is valid for REDACTED, REDACTED, not elasticsearch-es-http.elastic.svc","service.name":"metricbeat","ecs.version":"1.6.0"}`

Due to the fact, that I'm providing my own certificate to elasticsearch which didn't include a SAN entry for `elasticsearch-es-http.elastic.svc`.

I think this is a quite common usecase. Is it possible to disable the certificate validation or set it to `ssl.verification_mode: certificate` for the beats?

**Environment**

* ECK version:

	2.3.0

* ES version:

	8.3.2

**Comment by le0nard01** [comment]
@pebrc Doesn't it make sense to do the same verificantion mode: `certificate ` for elasticsearch service too ? As has been done in Kibana as you mentioned.

**Comment by thbkrkr** [comment]
> One way I could think of is to say whenever someone is using custom certificates for their Elasticsearch cluster that is the target of an stack monitoring configuration to switch to verification mode: certificate (we do it by default for Kibana already as I found out today)

This seems like a good compromise to me to solve this without asking anything from the users.

Another more involved idea I had is to propose a way to override the Beat config like it is possible for the Pod definition via the podTemplate. This is more powerful but has the downside of requiring users to have some knowledge of the existing Beat config, which I find unfortunate.
```yaml
spec:
  monitoring:
    metrics:
      elasticsearchRefs:
      - name: elasticsearch
        configTemplate:
          ouput:
            ssl:
              verification_mode: certificate
```
