### ISSUE TITLE
No CPU request/limit by default

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#597]
While working on local volumes with the provided sample (`config/samples/elasticsearch/elasticsearch_local_volume.yaml`)
 I found out that without any explicit resources the ES pods are in the Burstable QoS.
 
 This is because by default no CPU requirement or limit are set:
 
```yaml
apiVersion: v1
kind: Pod
metadata:
[...]
  name: elasticsearch-sample-es-5ls2kg98md
  namespace: default
spec:
  containers:
    name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.0
    resources:
      limits:
        memory: 1Gi
      requests:
        memory: 1Gi
[...]
status:
  qosClass: Burstable
```
 
IIRC we want to avoid that pods fall into this category.

Should we set a default resource for the CPU as it is done for memory ?

https://github.com/elastic/k8s-operators/blob/4cae22f992655e1837fb7225ed8e2b2dccbb753e/operators/pkg/controller/elasticsearch/version/common.go#L138

I would say yes to be consistent, but these default values should be documented somewhere.

We could also use the validation webhook to reject a spec without all the resources explicitly set.
