### ISSUE TITLE
Anonymous auth breaks Kibana healthcheck

### ISSUE THREAD

**Issue by laurivosandi** [elastic/cloud-on-k8s#5990]
I am using following for Kibana, it works as expected besides the healthcheck that seems to be polling `/login`. I suggest making the healthcheck endpoint configurable at least, I have it manually changed to `/app/home` for example

```
  config:
    xpack.security.authc.providers:
      anonymous.anonymous1:
        order: 0
        credentials:
          username: "elastic"
  secureSettings:
  - secretName: elasticsearch-es-elastic-user
    entries:
    - key: elastic
      path: xpack.security.authc.providers.anonymous.anonymous1.credentials.password
```

**Comment by barkbay** [comment]
>  I suggest making the healthcheck endpoint configurable at least, I have it manually changed to `/app/home` for example

Maybe I'm missing something, but as you suggested probes can already be overridden in the `podTemplate`, for example:

```yaml
  podTemplate:
    metadata:
      labels:
        foo: bar
    spec:
      containers:
      - name: kibana
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 5601
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
```

Somewhat duplicated/related with  https://github.com/elastic/cloud-on-k8s/issues/4560
Closing as I'm not sure we can do more here, feel free to reopen if needed.
