### ISSUE TITLE
Additional Breaking Change as part of #5890

### ISSUE THREAD

**Issue by BenB196** [elastic/cloud-on-k8s#5993]
## Bug Report
**What did you do?**

Upgrade ECK from `2.3.0` to `2.4.0`

**What did you expect to see?**

I expect to see my Elastic Agents restart and come up with a new `hostPath` volume as part of https://github.com/elastic/cloud-on-k8s/pull/5890.

**What did you see instead? Under which circumstances?**

I see the agents enter into a crashloop, because they are attempting to change the ownership/permissions of the newly added `hostPath` volume, _but_ they don't have the correct permissions. Because they don't have the correct security context:

```yaml
spec:
  daemonSet:
    podTemplate:
      spec:
        containers:
          name: agent
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
```

**Environment**

* ECK version:

`2.4.0`

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* On premise ? yes
	* Cloud: GKE / EKS / AKS ? n/a
	* Kubernetes distribution: Openshift / Rancher / PKS ? `v1.22.8+rke2r1` & `v1.23.9+rke2r1`
	
## Issue

The documentation for both [Standalone](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-elastic-agent-configuration.html) & [Fleet Managed](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-elastic-agent-fleet-configuration.html) don't mention the requirement for setting the `securityContext` of the container, but it seems that if you don't then the new `hostPath` setup doesn't work.

Current Workaround:
1. Add required `securityContext` information to the container
2. Switch to an `emptyDir` directory if `securityContext` change isn't an option, or if you just don't need/want persistents.

**Comment by barkbay** [comment]
I think you're right. The [examples in our documentation](https://github.com/elastic/cloud-on-k8s/blob/41edbb93f99fd3b5f413512380bb0f8cba032656/docs/orchestrating-elastic-stack-applications/agent-standalone.asciidoc?plain=1#L24-L59) do not work anymore. We should at least fix them with a comment regarding the need of running the containers as user `0`:

```yaml
    podTemplate:
      spec:
        containers:
          - name: agent
            securityContext:
              runAsUser: 0 # required to mount host path volume for Elastic Agent local state
```
