### ISSUE TITLE
When use cpu/mem resource requests elasticsearch provisioning fail

### ISSUE THREAD

**Issue by pmacieje** [elastic/cloud-on-k8s#6002]
# Can't start elastisearch resource using operator.

## Bug Report
I've set up latest version of elasticsearch (8.4.1) using latest operator (2.4.0). According to the documentation I'v set up a resource quotas for es containers but I've got error while reconciliation. I've got error that I need to put to configuration "image:" field, but as far as I know it should be managed by operator. Could anyone tell me if I'm doing something wrong ? I've set up everything like in this document:

[https://www.elastic.co/guide/en/cloud-on-k8s/2.4/k8s-kibana-advanced-configuration.html#k8s-kibana-pod-configuration](url)

**Environment**

* ECK version:

	Operator: 2.4.0
        Elasticsearch: 8.4.1

* Kubernetes information:

	* Cloud: AWS
	* Kubernetes distribution: EKS

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.7-eks-4721010", GitCommit:"b77d9473a02fbfa834afa67d677fd12d690b195f", GitTreeState:"clean", BuildDate:"2022-06-27T22:19:07Z", GoVersion:"go1.17.10", Compiler:"gc", Platform:"linux/amd64"}

```

* Resource definition:
```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
  namespace: elasticsearch
  annotations:
    eck.k8s.elastic.co/disable-upgrade-predicates: "only_restart_healthy_node_if_green_or_yellow"
spec:
  version: 8.4.1
  http:
    tls:
      selfSignedCertificate:
        disabled: true
    service:
      metadata:
        labels: 
          app: quickstart
  auth:
    fileRealm:
    - secretName: es-users
    roles:
    - secretName: es-roles
  volumeClaimDeletePolicy: DeleteOnScaledownOnly
  nodeSets:
  - name: master-nodes
    count: 3
    config:
      node.roles: ["master"]
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: ebs-sc
  - name: data-nodes
    count: 3
    config:
      node.roles: ["data"]
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: ebs-sc
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        containers:
        - name: quickstart
          resources:
            requests:
              memory: "1Gi"
              cpu: 0.3
            limits:
              memory: "2Gi"
              cpu: 0.8
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: eks.amazonaws.com/capacityType
                  operator: In
                  values:
                  - SPOT
```

* Logs:
```
{"log.level":"error","@timestamp":"2022-09-06T19:25:01.131Z","log.logger":"manager.eck-operator","message":"Reconciler error","service.version":"2.4.0+96282ca9","service.type":"eck","ecs.version":"1.4.0","controller":"elasticsearch-controller","object":{"name":"quickstart","namespace":"elasticsearch"},"namespace":"elasticsearch","name":"quickstart","reconcileID":"c673c098-25af-4bd5-9933-4a11526a77bd","error":"reconcile StatefulSet: Validation of PodTemplate for StatefulSet quickstart-es-default in Elasticsearch elasticsearch/quickstart failed for the following reasons: [{FieldValueRequired Required value spec.containers[0].image}]","errorCauses":**[{"error":"reconcile StatefulSet: Validation of PodTemplate for StatefulSet quickstart-es-default in Elasticsearch elasticsearch/quickstart failed for the following reasons: [{FieldValueRequired Required value spec.containers[0].image}]"}]**,"error.stack_trace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/internal/controller/controller.go:234"}
{"log.level":"info","@timestamp":"2022-09-06T19:27:58.526Z","log.logger":"webhook-certificates-controller","message":"Starting reconciliation run","service.version":"2.4.0+96282ca9","service.type":"eck","ecs.version":"1.4.0","iteration":"201","namespace":"","validating_webhook_configuration":"elastic-webhook.k8s.elastic.co"}
{"log.level":"info","@timestamp":"2022-09-06T19:27:58.537Z","log.logger":"webhook-certificates-controller","message":"Creating new webhook certificates","service.version":"2.4.0+96282ca9","service.type":"eck","ecs.version":"1.4.0","webhook":"elastic-webhook.k8s.elastic.co","secret_namespace":"elastic-system","secret_name":"elastic-webhook-server-cert"}
{"log.level":"info","@timestamp":"2022-09-06T19:27:59.265Z","log.logger":"webhook-certificates-controller","message":"Ending reconciliation run","service.version":"2.4.0+96282ca9","service.type":"eck","ecs.version":"1.4.0","iteration":"201","namespace":"","validating_webhook_configuration":"elastic-webhook.k8s.elastic.co","took":0.738902243}
{"log.level":"info","@timestamp":"2022-09-06T19:27:59.265Z","log.logger":"webhook-certificates-controller","message":"Starting reconciliation run","service.version":"2.4.0+96282ca9","service.type":"eck","ecs.version":"1.4.0","iteration":"202","namespace":"elastic-system","validating_webhook_configuration":"elastic-webhook-server-cert"}
{"log.level":"info","@timestamp":"2022-09-06T19:27:59.280Z","log.logger":"webhook-certificates-controller","message":"Ending reconciliation run","service.version":"2.4.0+96282ca9","service.type":"eck","ecs.version":"1.4.0","iteration":"202","namespace":"elastic-system","validating_webhook_configuration":"elastic-webhook-server-cert","took":0.014642046}
```
