### ISSUE TITLE
elasticsearch is not dispatched to the specified node with affinity

### ISSUE THREAD

**Issue by aliuq** [elastic/cloud-on-k8s#6016]
## Bug Report
**What did you do?**

I have three nodes, of which `node2` node memory 4g, the rest `node1` and `server1` 8g, I specify scheduling node `node1` and `server1` when deploying es, it did not deploy the application on `server1`, I found `nodeSelector` and `affinity` is not works.

```bash
kubectl get node --show-labels

NAME      STATUS   ROLES                       AGE   VERSION        LABELS
node1     Ready    <none>                      16d   v1.23.9+k3s1   kubernetes.io/hostname=node1
node2     Ready    <none>                      16d   v1.23.9+k3s1   kubernetes.io/hostname=node2
server1   Ready    control-plane,etcd,master   16d   v1.23.9+k3s1   kubernetes.io/hostname=server1
```

`elasticsearch-es-default-0` is not deploied

```bash
kubectl get pod -n elastic-system

NAME                         READY   STATUS    RESTARTS   AGE     IP            NODE     NOMINATED NODE   READINESS GATES
elastic-operator-0           1/1     Running   0          4h32m   10.42.1.251   node2    <none>           <none>
elasticsearch-es-default-0   0/1     Pending   0          71s     <none>        <none>   <none>           <none>
elasticsearch-es-default-1   1/1     Running   0          71s     10.42.2.202   node1    <none>           <none>
```

decribe elasticsearch-es-default-0

```bash
Type     Reason            Age                   From               Message
----     ------            ----                  ----               -------
Warning  FailedScheduling  21m (x145 over 168m)  default-scheduler  0/3 nodes are available: 1 node(s) didn't match Pod's node affinity/selector, 2 node(s) had volume node affinity conflict.
```

affinity configuration

```yaml
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node1
          - server1
```

<details>
<summary>完整 elasticsearch.yaml</summary>

```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: elastic-system
type: Opaque
stringData:
  access_key: "xxxxxxxxxxxxxxx"
  secret_key: "xxxxxxxxxxxxxxx"
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: elastic-system
spec:
  version: 8.3.3
  volumeClaimDeletePolicy: DeleteOnScaledownOnly
  nodeSets:
  - name: default
    config:
      node.roles: ["master", "data", "ingest", "ml"]
      # this allows ES to run on nodes even if their vm.max_map_count has not been increased, at a performance cost
      node.store.allow_mmap: false
      reindex.remote.whitelist: "nas.bilishare.com:9200, 47.106.14.109:9200"
    podTemplate:
      metadata:
        namespace: elastic-system
        labels:
          app: elastic
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                  - node1
                  - server1
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        - name: compatible-with-aliyun-s3
          command:
          - /bin/bash
          - -c
          - |
            echo "$ACCESS_KEY" | bin/elasticsearch-keystore add --stdin --force s3.client.default.access_key
            echo "$SECRET_KEY" | bin/elasticsearch-keystore add --stdin --force s3.client.default.secret_key
          env:
          - name: ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-credentials
                key: access_key
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: s3-credentials
                key: secret_key
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 1Gi
              cpu: 0.5
            limits:
              memory: 2Gi
              cpu: 1
          env:
          - name: ES_JAVA_OPTS
            value: "-Xmx1g -Xms1g -Des.allow_insecure_settings=true"
    count: 2
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: local-path
  http:
    tls:
      selfSignedCertificate:
        disabled: true
```
</details>

**What did you see instead? Under which circumstances?**

**Environment**

* ECK version: `v2.4.0`

* Kubernetes information: `v1.23.9+k3s1`

	
```
$ kubectl version

WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.9+k3s1", GitCommit:"f45cf3267307b153ed8b418ae5b8ea6c6b9ebaca", GitTreeState:"clean", BuildDate:"2022-07-19T00:42:17Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.25) and server (1.23) exceeds the supported minor version skew of +/-1
```

**Comment by barkbay** [comment]
> 2 node(s) had volume node affinity conflict.

Could you provide the volumes and their locations?

**Comment by aliuq** [comment]
@barkbay Sorry, I'm not very good at using k8s, I don't know how to find volumes and their location.

My last solution is to specify a node instead of using affinity control.

```yaml
spec:
  nodeSelector:
    kubernetes.io/hostname: server1
```
