### ISSUE TITLE
annotations in spec Kubernetes core/v1.ServiceSpec

### ISSUE THREAD

**Issue by ebenezar-mccoy** [elastic/cloud-on-k8s#6038]
## Proposal

Can I ask to get annotations configurable through core/v1.ServiceSpec

spec
[spec Kubernetes core/v1.ServiceSpec](https://www.elastic.co/guide/en/cloud-on-k8s/1.0/k8s-common-k8s-elastic-co-v1.html#common-k8s-elastic-co-v1-servicetemplate)

**Use case. Why is this important?**

That will enable the use of custom loadbalancers (ex. openelb) through annotation configuration

```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic-logs
spec:
  ...
  transport:
    service:
      spec:
        type: LoadBalancer 
        annotations:
          lb.kubesphere.io/v1alpha1: openelb
          protocol.openelb.kubesphere.io/v1alpha1: vip
          eip.openelb.kubesphere.io/v1alpha2: vip-eip
  http:
    service:
      spec:
        type: LoadBalancer 
        annotations:
          lb.kubesphere.io/v1alpha1: openelb
          protocol.openelb.kubesphere.io/v1alpha1: vip
          eip.openelb.kubesphere.io/v1alpha2: vip-eip
```

* Kubernetes information:

	* On premise / RKE2

**Comment by barkbay** [comment]
Annotations are part of the `metadata` section:

```yaml
  http:
    service:
      metadata:
        annotations:
          foo: bar
      spec:
        type: LoadBalancer
```

```
 k get svc elasticsearch-sample-es-http -o jsonpath='{ .metadata.annotations }'
{"foo":"bar"}%
```

**Comment by ebenezar-mccoy** [comment]
When configured I am getting this error 

error: error validating "k8s/elastic/ptc/logs/elastic.yaml": error validating data: [ValidationError(Elasticsearch.spec.http.service.spec): unknown field "annotations" in co.elastic.k8s.elasticsearch.v1.Elasticsearch.spec.http.service.spec, ValidationError(Elasticsearch.spec.transport.service.spec): unknown field "annotations" in co.elastic.k8s.elasticsearch.v1.Elasticsearch.spec.transport.service.spec];

**Comment by ebenezar-mccoy** [comment]
@thbkrkr can you please re-open?

**Comment by thbkrkr** [comment]
> @thbkrkr can you please re-open?

Are you sure you wrote the `metadata` field? Looking at your error, it seems not. If you think so, can you share the manifest you are using?

**Comment by thbkrkr** [comment]
> unknown field "annotations" in co.elastic.k8s.elasticsearch.v1.Elasticsearch.spec.transport.service.spec

Yes, you can't declare the field `annotations` below the field `spec`. 

You must declare it below the `metadata` field as explained in https://github.com/elastic/cloud-on-k8s/issues/6038#issuecomment-1260441295. The full path is then:`http.service.metadata.annotations` or `transport.service.metadata.annotations`.

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic-logs
spec:
  version: 8.4.1
  nodeSets:
  - name: default
    count: 3
    config:
      node.roles: ["master", "data", "ingest", "ml", "transform", "remote_cluster_client"]
      xpack.security.transport.ssl.certificate_authorities:
      - /usr/share/elasticsearch/config/other/KsUE2-head-ca.crt
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: local-storage
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          volumeMounts:
          - mountPath: /usr/share/elasticsearch/config/other
            name: remote-certs
          resources:
            requests:
              memory: 4Gi
              cpu: 1
            limits:
              memory: 4Gi
        volumes:
        - name: remote-certs
          secret:
            secretName: remote-certs
  transport:
    service:
      metadata: <-------------------------------------------
        annotations:
          lb.kubesphere.io/v1alpha1: openelb
          protocol.openelb.kubesphere.io/v1alpha1: vip
          eip.openelb.kubesphere.io/v1alpha2: vip-eip
      spec:
        type: LoadBalancer 
        loadBalancerIP: "10.139.139.99"
  http:
    service:
      metadata: <-------------------------------------------
        annotations:
          lb.kubesphere.io/v1alpha1: openelb
          protocol.openelb.kubesphere.io/v1alpha1: vip
          eip.openelb.kubesphere.io/v1alpha2: vip-eip
      spec:
        type: LoadBalancer 
        loadBalancerIP: "10.139.139.98"
```
