### ISSUE TITLE
Using default elasticsearch 8.4.2 config but keep getting `Authentication to realm file1 failed - Password authentication failed for elastic` error

### ISSUE THREAD

**Issue by codeeong** [elastic/cloud-on-k8s#6039]
## Bug Report
**What did you do?**
I am following the guide on https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-deploy-elasticsearch.html to deploy es into my cluster. 

Previously, I was using the exact config using the eck-stack helm chart and the whole stack worked end to end, but a couple days ago it *suddenly* started showing this error after i restarted my deployment. 
```
{"@timestamp":"2022-09-26T04:09:06.662Z", "log.level": "WARN", "message":"Authentication to realm file1 failed - Password authentication failed for elastic", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"elasticsearch[quickstart-es-default-1][generic][T#47]","log.logger":"org.elasticsearch.xpack.security.authc.RealmsAuthenticator","elasticsearch.cluster.uuid":"e6Fe8dnbRvC6YKKCBKt35w","elasticsearch.node.id":"oCfdzrgjSGu__NJmJSrCkQ","elasticsearch.node.name":"quickstart-es-default-1","elasticsearch.cluster.name":"quickstart"}
```
After some digging around this repository, I moved out my config to the Elasticsearch yaml after finding out that the eck-stack helm chart is only available to enterprise users, as I thought that might be the reason why my es cluster was failing. However, even after doing so, and uninstalling and reinstalling the stack, the same error persists. As shown in my config below, there are no custom users or file realm specified, so I would have expected that the file realm authentication would be handled by the operator itself, out of the box.

Any help debugging is appreciated, thanks!

**Environment**

* ECK version: 2.4.0

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* On premise ?
	* Cloud: GKE / EKS / AKS ? EKS
	* Kubernetes distribution: Openshift / Rancher / PKS ?
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.11-eks-18ef993", GitCommit:"b9628d6d3867ffd84c704af0befd31c7451cdc37", GitTreeState:"clean", BuildDate:"2022-07-06T18:06:23Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```
* Resource definition:
```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 8.4.2
  nodeSets:
    - name: default
      count: 3
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            storageClassName: my-storage-class
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 50Gi
      config:
        xpack.security.authc:
          anonymous:
            roles: "viewer"
            authz_exception: true
```
* Logs:
```
{"@timestamp":"2022-09-26T04:09:06.662Z", "log.level": "WARN", "message":"Authentication to realm file1 failed - Password authentication failed for elastic", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"elasticsearch[quickstart-es-default-1][generic][T#47]","log.logger":"org.elasticsearch.xpack.security.authc.RealmsAuthenticator","elasticsearch.cluster.uuid":"e6Fe8dnbRvC6YKKCBKt35w","elasticsearch.node.id":"oCfdzrgjSGu__NJmJSrCkQ","elasticsearch.node.name":"quickstart-es-default-1","elasticsearch.cluster.name":"quickstart"}
```
