### ISSUE TITLE
Document APM setup with Fleet/Elastic Agent

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#6081]
The APM integration for Fleet is replacing the standalone APM server. We should document how to set up APM through Fleet. How to create a service fronting the Agents, how to configure the secret token and maybe how to configure a client to talk to the APM integration for example Kibana itself.

**Comment by ebuildy** [comment]
fleet seems very complicated to replace APM, so now, if I want to add an APM server, I have to edit then re-deploy kibana (aka the .. UI) ?

Or I can deploy a fleet agent with the right spec instead?

Many thanks

**Comment by fzyzcjy** [comment]
Hi, is there any updates? thanks

**Comment by thomazfohr** [comment]
Thanks for the example @pebrc, you saved my day!

In addition to the changes above I also had to expose port 8200 in the agents in order to get requests from apm client libraries.

```yaml
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata: 
  name: elastic-agent
spec:
  version: 8.4.2
  kibanaRef:
    name: kibana
  fleetServerRef: 
    name: fleet-server
  mode: fleet
  deployment:
    replicas: 1
    podTemplate:
      spec:
        securityContext:
          runAsUser: 0
        containers:
          - name: agent  
            ports:
              - name: apm
                containerPort: 8200
                protocol: TCP
```

Although this works, it would be nice to have a complete example in the official docs.

**Comment by AnarchicSoul** [comment]
Sorry if I come years later...

I have some issues and cannot find information about it... I want enable SSL for APM but it seems not working. Tried same syntaxe used for secret-token but discovered that it's not working too... 


```
      - name: Elastic Agent
        id: eck-agent
        namespace: plouf
        monitoring_enabled:
        - logs
        - metrics
        unenroll_timeout: 900
        package_policies:
        - package:
            name: apm
          name: apm-1
          inputs:
          - type: apm
            enabled: true
            vars:
            - name: host
              value: 0.0.0.0:8200
            - name: auth.secret_token 
              value: apm-token
            - name: enable_rum
              value: true
            - name: ssl.enabled 
              value: true
            - name: ssl.certificate 
              value: /usr/share/elastic-agent/apm/tls.crt 
            - name: ssl.key 
              value: /usr/share/elastic-agent/apm/tls.key 

```
auth.secret_token, ssl.enabled, ssl.certificate and ssl.key are not working.
I've manage to add certs correctly on containers. And it's working if I add ssl configuration directly with Kibana UI.
