### ISSUE TITLE
spec.http.service.metadata.name: in CRD has no function in service.go

### ISSUE THREAD

**Issue by mehmetsalgar** [elastic/cloud-on-k8s#6105]
## Bug Report
**What did you do?**
I am trying to use a custom service name for ES Cluster, CRD defines the [field](https://raw.githubusercontent.com/elastic/cloud-on-k8s/main/config/crds/v1/bases/elasticsearch.k8s.elastic.co_elasticsearches.yaml)  but in [service.go](https://github.com/elastic/cloud-on-k8s/blob/main/pkg/controller/elasticsearch/services/services.go#L43-L45) it is not used at all.

**What did you expect to see?**
   -If it is desired that CRD should be able to customise the Service Metadata Name via service.go, then this should be implemented. 
   - If this is not desired then please remove the field from CRD, I had spent quite lot of time to figure out that it actually has no function.

**What did you see instead? Under which circumstances?**
spec.http.service.metadata.name: has no function

**Environment**
On Premise Kubernetes 1.21

* ECK version:
ECK 2.4
	insert version or git commit id here

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* On premise ? YES

```
$ kubectl version 1.24
```

* Resource definition: 2.4

**Comment by barkbay** [comment]
Hi, this limitation is stated in the CRD you mentioned, around line 92:

```yaml
                  service:
                    description: Service defines the template for the associated Kubernetes
                      Service object.
                    properties:
                      metadata:
                        description: ObjectMeta is the metadata of the service. The
                          name and namespace provided here are managed by ECK and
                          will be ignored.
```

> I had spent quite lot of time to figure out that it actually has no function.

Sorry about that, feel free to open a topic in our [discuss forum](https://discuss.elastic.co/c/orchestration/eck/79) if you have additional questions.
