### ISSUE TITLE
Unable to disable optional Kibana configuration for dashboard examples when deploying Filebeat

### ISSUE THREAD

**Issue by lgenasi-gocity** [elastic/cloud-on-k8s#6107]
## Bug Report
**What did you do?**
Attempted to deploy Filebeat without setting up example dashboards on Kibana by omitting `kibanaRef` from config.

**What did you expect to see?**
No example dashboards on Kibana.

**What did you see instead? Under which circumstances?**
Error from reconciler saying that `kibanaRef` is a required field:

```
{"log.level":"error","@timestamp":"2022-10-21T15:42:27.517Z","log.logger":"manager.eck-operator","message":"Reconciler error","service.version":"2.4.0+96282ca9","service.type":"eck","ecs.version":"1.4.0","controller":"beat-kibana-association-controller","object":{"name":"filebeat","namespace":"elastic-stack"},"namespace":"elastic-stack","name":"filebeat","reconcileID":"0023b289-deda-47d7-8199-e8751b06a2e6","error":"Beat.beat.k8s.elastic.co \"filebeat\" is invalid: spec.kibanaRef.name: Required value","error.stack_trace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/internal/controller/controller.go:234"}
```

**Environment**

* ECK version:

	2.4.0

* Resource definition:
```
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: filebeat
  namespace: elastic-stack
spec:
  type: filebeat
  version: 8.4.2
  elasticsearchRef:
    name: quickstart
  config:
    filebeat.inputs:
    - type: container
      paths:
      - /var/log/containers/*.log
  daemonSet:
    podTemplate:
      spec:
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true
        securityContext:
          runAsUser: 0
        containers:
        - name: filebeat
          volumeMounts:
          - name: varlogcontainers
            mountPath: /var/log/containers
          - name: varlogpods
            mountPath: /var/log/pods
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
        volumes:
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
        - name: varlogpods
          hostPath:
            path: /var/log/pods
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
```

* Logs:
```
{"log.level":"error","@timestamp":"2022-10-21T15:42:27.517Z","log.logger":"manager.eck-operator","message":"Reconciler error","service.version":"2.4.0+96282ca9","service.type":"eck","ecs.version":"1.4.0","controller":"beat-kibana-association-controller","object":{"name":"filebeat","namespace":"elastic-stack"},"namespace":"elastic-stack","name":"filebeat","reconcileID":"0023b289-deda-47d7-8199-e8751b06a2e6","error":"Beat.beat.k8s.elastic.co \"filebeat\" is invalid: spec.kibanaRef.name: Required value","error.stack_trace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.2/pkg/internal/controller/controller.go:234"}
```
