### ISSUE TITLE
Cannot run elasticsearch with security best practice ``readOnlyRootFilesystem: true``

### ISSUE THREAD

**Issue by ebuildy** [elastic/cloud-on-k8s#6126]
## Bug Report

**What did you do?**

As a good practice, we configure security context (here ``readOnlyRootFilesystem: true``):

```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
spec:
  nodeSets:
    - 
      count: 3
      name: master
      podTemplate:
        spec:
          containers:
            - 
              securityContext: &securityContext
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                privileged: false
                readOnlyRootFilesystem: true
                runAsNonRoot: true
                runAsUser: 1000
          initContainers:
            - name: elastic-internal-init-filesystem
              securityContext: 
                <<: *securityContext
            - name: elastic-internal-suspend
              securityContext:
                <<: *securityContext
            - name: elastic-internal-init-keystore
              securityContext:
                <<: *securityContext
```

**What did you expect to see?**

Operator create the STS, create pods, create container and init container can run fine.

**What did you see instead? Under which circumstances?**

The first initContainer cannot run because a folder is not writable. Diging the source code, we can see:

prepare-fs.sh script:

```
...
echo "Linking /mnt/elastic-internal/xpack-file-realm/users to /usr/share/elasticsearch/config/users"
		ln -sf /mnt/elastic-internal/xpack-file-realm/users /usr/share/elasticsearch/config/users
...
```
where the directory `` /usr/share/elasticsearch/config`` is not a volume, hence read-only.

We cant find any workaround, except changing polaris or OPA rules.

As a clean solution, the prepare-fs.sh script should use a temporary directory, mounted as ``emptyDir``.

References:

* https://github.com/elastic/cloud-on-k8s/issues/2108
* https://github.com/elastic/cloud-on-k8s/issues/4022

**Comment by barkbay** [comment]
The way Elasticsearch starts requires the `/tmp` directory to be writable, other than that I think it can be started with `readOnlyRootFilesystem: true`:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
spec:
  version: 8.5.0
  nodeSets:
  - name: default
    config:
      node.store.allow_mmap: false
    podTemplate:
      spec:
        volumes:
          - name: tmp-volume
            emptyDir: { }
        containers:
        - name: elasticsearch
          securityContext:
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
    count: 3
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-sample
spec:
  version: 8.5.0
  count: 1
  elasticsearchRef:
    name: "elasticsearch-sample"
  podTemplate:
    spec:
      containers:
        - name: kibana
          securityContext:
            readOnlyRootFilesystem: true
```
