### ISSUE TITLE
Traffic splitting, elasticsearchRef.serviceName, and certificate validation

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#6165]
The [traffic splitting documentation](https://www.elastic.co/guide/en/cloud-on-k8s/2.5/k8s-traffic-splitting.html) does not mention that referencing a custom `Service` using `elasticsearchRef.serviceName`  does not update the HTTP certificate exposed by the Elasticsearch nodes.

It works for [Kibana as documented](https://www.elastic.co/guide/en/cloud-on-k8s/2.5/k8s-traffic-splitting.html#k8s-traffic-splitting-with-service-name) because the `verificationMode` is set to `certificate` by the [Kibana controller](https://github.com/elastic/cloud-on-k8s/blob/b287d85d3cd3646bc48aa8fdcc19d161986fdc10/pkg/controller/kibana/config_settings.go#L292-L295):

```golang
func elasticsearchTLSSettings(esAssocConf commonv1.AssociationConf) map[string]interface{} {
	cfg := map[string]interface{}{
		ElasticsearchSslVerificationMode: "certificate",
	}
```

But in the case of `Beats`, and maybe other stack applications (see https://github.com/elastic/cloud-on-k8s/issues/4812 about this inconsistency), a full validation is done, which leads to a validation failure:

```json
{
	"log.level": "error",
	"@timestamp": "2022-11-10T08:43:27.961Z",
	"log.logger": "publisher_pipeline_output",
	"log.origin": {
		"file.name": "pipeline/client_worker.go",
		"file.line": 150
	},
	"message": "Failed to connect to backoff(elasticsearch(https://my-ingest-nodes.default.svc:9200)): Get \"https://my-ingest-nodes.default.svc:9200\": x509: certificate is valid for my-es-http.default.es.local, my-es-http, my-es-http.default.svc, my-es-http.default, my-es-internal-http.default.svc, my-es-internal-http.default, *.my-es-master.default.svc, *.my-es-data.default.svc, *.my-es-ingest-1.default.svc, *.my-es-ingest-2.default.svc, not my-ingest-nodes.default.svc",
	"service.name": "filebeat",
	"ecs.version": "1.6.0"
}
```

I think we should at least document the workaround of adding the expected hostname in the SAN extension:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: my-es
spec:
  version: x.x.x
  nodeSets: {}
  http:
    tls:
      selfSignedCertificate:
        subjectAltNames:
          - dns: my-ingest-nodes.default.svc
```

I also think an improvement could be that the Elasticsearch controller automatically adds the expected hostname to the SAN extension?
