### ISSUE TITLE
Not described mandatory parameters for podTemplate

### ISSUE THREAD

**Issue by ptsonkov** [elastic/cloud-on-k8s#6178]
## Bug Report
**What did you do?**
Deploy ECK on OKD using following file (removed same nodesets for hot/warm nodes)
```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ escloud_cluster_name }}
spec:
  version: {{ escloud_cluster_version }}
  nodeSets:
  - name: master-nodes
    count: {{ escloud_cluster_master_node_count }}
    config:
      node.roles: ["master","remote_cluster_client"]
    podTemplate:
      spec:
        containers:
        - name: {{ escloud_cluster_master_node_name }}
#          image: docker.elastic.co/elasticsearch/elasticsearch:{{ escloud_cluster_version }}
          resources:
            requests:
              memory: {{ escloud_cluster_master_node_memory_request }}
              cpu: {{ escloud_cluster_master_node_cpu_request }}
            limits:
              memory: {{ escloud_cluster_master_node_memory_limit }}
              cpu: {{ escloud_cluster_master_node_cpu_limit }}
[...omitted...]
```

**What did you expect to see?**
To deploy Elastic successfully

**What did you see instead? Under which circumstances?**
- When deploy without "podTemplate" (using operator defaults) everything is OK. When add "podTemplate" I see the error below, image parameter appears to be mandatory and deployment fail.
- When add "image" deployment is completed successfully, but create 2 containers in the pod (elasticsearch + name defined in podTemplate) and pod crash continuously, when deploy without "podTemplate" there is 1 container in the pod (elasticsearch) all work fine. 

**Environment**

* ECK version:

2.5.0 (same behavior with 2.4.0)

* Kubernetes information:
OKD 4.11
```
# oc version
Client Version: 4.8.11
Server Version: 4.11.0-0.okd-2022-10-28-153352
Kubernetes Version: v1.24.0-2566+5157800f2a3bc3-dirty
```

* Logs:
```
{"log.level":"error","@timestamp":"2022-11-17T14:39:07.045Z","log.logger":"manager.eck-operator","message":"Reconciler error","service.version":"2.5.0+642f9ecd","service.type":"eck","ecs.version":"1.4.0","controller":"elasticsearch-controller","object":{"name":"elastic","namespace":"elastic-cloud"},"namespace":"elastic-cloud","name":"elastic","reconcileID":"98868e3f-849b-4c98-843d-85e764ce8d65","error":"reconcile StatefulSet: Validation of PodTemplate for StatefulSet elastic-es-master-nodes in Elasticsearch elastic-cloud/elastic failed for the following reasons: [{FieldValueRequired Required value spec.containers[0].image}]","errorCauses":[{"error":"reconcile StatefulSet: Validation of PodTemplate for StatefulSet elastic-es-master-nodes in Elasticsearch elastic-cloud/elastic failed for the following reasons: [{FieldValueRequired Required value spec.containers[0].image}]"}],"error.stack_trace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/c...
```
