### ISSUE TITLE
emptyDir volume is not mounted

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#6186]
Despite [what our document suggests](https://www.elastic.co/guide/en/cloud-on-k8s/2.4/k8s-volume-claim-templates.html#k8s_emptydir) setting an `emptyDir` volume for Elasticsearch data does not actually mount and rely on that `emptyDir`.

To be a bit more explicit, here is the resulting `Pod` when the example from the documentation is applied:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: elasticsearch-sample-es-default-0
  namespace: default
spec:
  containers:
  - name: elasticsearch
    volumeMounts:
    - mountPath: /mnt/elastic-internal/downward-api
      name: downward-api
      readOnly: true
    - mountPath: /usr/share/elasticsearch/bin
      name: elastic-internal-elasticsearch-bin-local
    - mountPath: /mnt/elastic-internal/elasticsearch-config
      name: elastic-internal-elasticsearch-config
      readOnly: true
    - mountPath: /usr/share/elasticsearch/config
      name: elastic-internal-elasticsearch-config-local
    - mountPath: /usr/share/elasticsearch/plugins
      name: elastic-internal-elasticsearch-plugins-local
    - mountPath: /usr/share/elasticsearch/config/http-certs
      name: elastic-internal-http-certificates
      readOnly: true
    - mountPath: /mnt/elastic-internal/probe-user
      name: elastic-internal-probe-user
      readOnly: true
    - mountPath: /usr/share/elasticsearch/config/transport-remote-certs/
      name: elastic-internal-remote-certificate-authorities
      readOnly: true
    - mountPath: /mnt/elastic-internal/scripts
      name: elastic-internal-scripts
      readOnly: true
    - mountPath: /usr/share/elasticsearch/config/transport-certs
      name: elastic-internal-transport-certificates
      readOnly: true
    - mountPath: /mnt/elastic-internal/unicast-hosts
      name: elastic-internal-unicast-hosts
      readOnly: true
    - mountPath: /mnt/elastic-internal/xpack-file-realm
      name: elastic-internal-xpack-file-realm
      readOnly: true
    - mountPath: /usr/share/elasticsearch/logs
      name: elasticsearch-logs
  volumes:
  - downwardAPI:
      defaultMode: 420
      items:
      - fieldRef:
          apiVersion: v1
          fieldPath: metadata.labels
        path: labels
    name: downward-api
  - emptyDir: {}
    name: elastic-internal-elasticsearch-bin-local
  - name: elastic-internal-elasticsearch-config
    secret:
      defaultMode: 420
      optional: false
      secretName: elasticsearch-sample-es-default-es-config
  - emptyDir: {}
    name: elastic-internal-elasticsearch-config-local
  - emptyDir: {}
    name: elastic-internal-elasticsearch-plugins-local
  - name: elastic-internal-http-certificates
    secret:
      defaultMode: 420
      optional: false
      secretName: elasticsearch-sample-es-http-certs-internal
  - name: elastic-internal-probe-user
    secret:
      defaultMode: 420
      items:
      - key: elastic-internal-probe
        path: elastic-internal-probe
      optional: false
      secretName: elasticsearch-sample-es-internal-users
  - name: elastic-internal-remote-certificate-authorities
    secret:
      defaultMode: 420
      optional: false
      secretName: elasticsearch-sample-es-remote-ca
  - configMap:
      defaultMode: 493
      name: elasticsearch-sample-es-scripts
      optional: false
    name: elastic-internal-scripts
  - name: elastic-internal-transport-certificates
    secret:
      defaultMode: 420
      optional: false
      secretName: elasticsearch-sample-es-default-es-transport-certs
  - configMap:
      defaultMode: 420
      name: elasticsearch-sample-es-unicast-hosts
      optional: false
    name: elastic-internal-unicast-hosts
  - name: elastic-internal-xpack-file-realm
    secret:
      defaultMode: 420
      optional: false
      secretName: elasticsearch-sample-es-xpack-file-realm
  - emptyDir: {}
    name: elasticsearch-data
  - emptyDir: {}
    name: elasticsearch-logs
```

While the` elasticsearch-data` volume is created it is not mounted in the `elasticsearch` container. The data are therefore written in the container instance, not in the expected Pod `volume`.

Might be related to https://github.com/elastic/cloud-on-k8s/pull/3848 I'm not sure if it's a bug, if it has ever worked, or if the doc must be fixed to include the `volumeMounts` in the example so adding both `bug` and `docs` label until until we clarify what the expected behavior is.
