### ISSUE TITLE
elastic-operator: can't declare preferred and required podAntiAffinity simultaneously

### ISSUE THREAD

**Issue by nie-kita2** [elastic/cloud-on-k8s#6216]
### Current behavior
Trying to deploy ElasticSearch manifest, where I declare both *preferredDuringSchedulingIgnoredDuringExecution* and *requiredDuringSchedulingIgnoredDuringExecution* **or** only *requiredDuringSchedulingIgnoredDuringExecution* under *podAntiAffinity* rules, I get the following error:

```
Resource: "elasticsearch.k8s.elastic.co/v1, Resource=elasticsearches", GroupVersionKind: "elasticsearch.k8s.elastic.co/v1, Kind=Elasticsearch"
Name: "...", Namespace: "..."
for: "/tmp/es.yaml": admission webhook "elastic-es-validation-v1.k8s.elastic.co" denied the request: Elasticsearch.elasticsearch.k8s.elastic.co "..." is invalid: podAffinityTerm: Invalid value: "podAffinityTerm": podAffinityTerm field found in the kubectl.kubernetes.io/last-applied-configuration annotation is unknown. This is often due to incorrect indentation in the manifest.
```

### Expected behavior
ElasticSearch manifest deploys successfully

* ECK version:

	eck-operator Helm chart v2.5.0 sourced from https://helm.elastic.co

* Kubernetes information:

	GKE, Kubernetes version 1.25.3-gke.800

**Comment by nie-kita2** [comment]
I apologize, but before opening an issue here I definitely checked the formatting about 100500 times. I assume that is a bug, because if I keep ** preferredDuringSchedulingIgnoredDuringExecution only**, with the same formatting, it works. If - with the same formatting, again - I change preferredDuringSchedulingIgnoredDuringExecution to requiredDuringSchedulingIgnoredDuringExecution, it stops working with an error message above.

Here's the manifest:

```
---
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: ${es_name}
  namespace: ${namespace}
spec:
  version: 7.17.7
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
  - name: masters
    count: 3
    podTemplate:
      metadata:
        labels:
          app: "elastic"
          elastic-type: "masters"
      spec:
        containers:
        - name: elasticsearch
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 75
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: elasticsearch.k8s.elastic.co/cluster-name
                    operator: In
                    values:
                    - ${es_name}
                topologyKey: "kubernetes.io/hostname"
            - weight: 75
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: elastic-type
                    operator: In
                    values:
                    - data
            requiredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: elastic-type
                    operator: In
                    values:
                    - masters
                topologyKey: "topology.gke.io/zone"
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 75
              preference:
                matchExpressions:
                - key: xxx/instance-optimization
                  operator: In
                  values:
                  - cpu
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-master
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: premium-rwo
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        storageClassName: premium-rwo
    config:
      node.roles:
      - master
      node.store.allow_mmap: false
  - name: data
    count: 3
    podTemplate:
      metadata:
        labels:
          app: "elastic"
          elastic-type: "data"
      spec:
        containers:
        - name: elasticsearch
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 75
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: elasticsearch.k8s.elastic.co/cluster-name
                    operator: In
                    values:
                    - ${es_name}
                topologyKey: "kubernetes.io/hostname"
            - weight: 75
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: elastic-type
                    operator: In
                    values:
                    - masters
            requiredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: elastic-type
                    operator: In
                    values:
                    - data
                topologyKey: "topology.gke.io/zone"

          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: xxx/instance-optimization
                    operator: In
                    values:
                    - cpu
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        storageClassName: premium-rwo
    config:
      node.roles:
      - data
      - ingest
      node.store.allow_mmap: false
  podDisruptionBudget:
    spec:
      minAvailable: 5
      selector:
        matchLabels:
          elasticsearch.k8s.elastic.co/cluster-name: ${es_name}
```

**Comment by thbkrkr** [comment]
The two inter pod affinity scheduling rules are not exactly the same type:
- `preferredDuringSchedulingIgnoredDuringExecution` is a [WeightedPodAffinityTerm](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#weightedpodaffinityterm-v1-core) array
- `requiredDuringSchedulingIgnoredDuringExecution` is a [PodAffinityTerm](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#podaffinityterm-v1-core) array

This implies that there are no `weight` and `podAffinityTerm` fields under `requiredDuringSchedulingIgnoredDuringExecution`. You have to directly declare the `labelSelector`:

```yaml
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: elastic-type
                  operator: In
                  values:
                  - masters
              topologyKey: "topology.gke.io/zone"
```

The page about "Advanced Elasticsearch node scheduling" in the ECK documentation shows an [example](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-advanced-node-scheduling.html#k8s-affinity-options) with `requiredDuringSchedulingIgnoredDuringExecution` that might have helped you.

Hence, I'm closing. Feel free to re-open if you encounter any further issues.
