### ISSUE TITLE
FleetServer can't connect to referenced Kibana via Secret

### ISSUE THREAD

**Issue by b2ronn** [elastic/cloud-on-k8s#6228]
I have 2 openshift clusters. one has kibana/elasticsearch installed. in the second openshift-cluster, I want to install a fleet server and elastic agents.

```
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: fleet-sample
spec:
  fleetServerRef: {}
  mode: fleet
  kibanaRef:
    secretName: kibana-secret
  deployment:
    podTemplate:
      metadata:
        creationTimestamp: null
      spec:
        automountServiceAccountToken: true
        containers:
          - name: agent
            resources:
              limits:
                cpu: '1'
                memory: 1Gi
              requests:
                cpu: 50m
                memory: 1Gi
        securityContext:
          runAsUser: 0
        serviceAccountName: heartbeat
        volumes:
          - name: agent-data
    replicas: 1
    strategy: {}
  http:
    service:
      metadata: {}
      spec: {}
    tls:
      certificate: {}
  policyID: eck-fleet-server
  fleetServerEnabled: true
  version: 8.5.2
  elasticsearchRefs:
    - secretName: elasticsearch-secret
---
kind: Secret
apiVersion: v1
metadata:
  name: elasticsearch-secret
data:
  ca.crt: Y2EgY2VydHM=
  password: cGFzc3dvcmQ=
  url: aHR0cHM6Ly9lbGFzdGljc2VhcmNoLmRvbWFpbi5jb206NDQz
  username: ZWxhc3RpYw==
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: kibana-secret
data:
  ca.crt: Y2EgY2VydA==
  password: cGFzc3dvcmQ=
  url: aHR0cHM6Ly9raWJhbmEuZG9tYWluLmNvbTo0NDM=
  username: ZWxhc3RpYw==
type: Opaque
```
but the fleet server can't install. elastic operator gives error:
```
{
    "log.level": "error",
    "@timestamp": "2022-12-13T15:00:06.487Z",
    "log.logger": "manager.eck-operator",
    "message": "Reconciler error",
    "service.version": "2.5.0+642f9ecd",
    "service.type": "eck",
    "ecs.version": "1.4.0",
    "controller": "agent-controller",
    "object": {
        "name": "fleet-sample",
        "namespace": "eckagents"
    },
    "namespace": "eckagents",
    "name": "fleet-sample",
    "reconcileID": "76c10394-7e8e-483b-87b5-51b0cdc7632c",
    "error": "Kibana.kibana.k8s.elastic.co \"kibana-secret\" not found",
    "errorCauses": [
        {
            "error": "Kibana.kibana.k8s.elastic.co \"kibana-secret\" not found"
        }
    ],
    "error.stack_trace": "sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:326\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:234"
}
```
Openshift: 4.11.17
ECK: 2.5.0
