### ISSUE TITLE
ElasticsearchAutoscaler documentation is unclear on supported node roles

### ISSUE THREAD

**Issue by brsolomon-deloitte** [elastic/cloud-on-k8s#6236]
The [ECK documentation on `ElasticsearchAutoscaler`](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-autoscaling.html) is unclear as to which node roles it supports.

First it states:

> Currently, autoscaling is supported for Elasticsearch [data tiers](https://www.elastic.co/guide/en/elasticsearch/reference/current/data-tiers.html) and machine learning nodes.

Perhaps I am misreading, but this seems to imply that the autoscaling API, and hence `ElasticsearchAutoscaler`, only supports data nodes or machine learning nodes, and does not support e.g. ingest nodes.

But then it gives this example:

```yaml
spec:
  ...
  policies:
    - name: data-ingest
      roles: ["data", "ingest" , "transform"]
```

...which seems to indicate that nodes other than data nodes are supported.

* ECK version:

	2.5.0
