### ISSUE TITLE
Disable creation of PersistentVolume

### ISSUE THREAD

**Issue by ben5556** [elastic/cloud-on-k8s#6238]
Elastic documentation on installing Elasticsearch using ECK operator says the below

_By default, the operator creates a [PersistentVolumeClaim](https://kubernetes.io/docs/concepts/storage/persistent-volumes/) with a capacity of 1Gi for each pod in an Elasticsearch cluster to prevent data loss in case of accidental pod deletion._

Link to documentation [here](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-volume-claim-templates.html

However, I want to disable this persistent volume creation as I am intending. to use local instance store volumes on AWS EC2.

Setting the `volumeClaimTemplates: {}` or `volumeClaimTemplates: []` in yaml didn't seem to help

**Comment by thbkrkr** [comment]
Hello,

> However, I want to disable this persistent volume creation as I am intending to use local instance store volumes on AWS EC2.

I'm not sure I understand what you want to achieve. Don't you want to use a Local Storage Static Provisioner and therefore PV/PVC (https://aws.amazon.com/fr/blogs/containers/eks-persistent-volumes-for-instance-store/)?
If not, what kind of volume do you want to use to store the elasticsearch data?

ECK will not configure a default PVC of 1Gi if:

- you configured a PVC:

```
spec:
  nodeSets:
  - name: data
    count: 10
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Ti
        storageClassName: standard
```

- you configured a volume named `elasticsearch-data` in the podSpec.volumes, and that volume is not a PVC volume

```
spec:
  nodeSets:
  - name: data
    count: 10
    podTemplate:
      spec:
        volumes:
        - name: elasticsearch-data
          emptyDir: {}
```
