### ISSUE TITLE
Consider setting vm.max_map_count automatically for users (opt-in)

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#6241]
Setting up the kernel in the right way can be perceived as an additional hurdle to getting started with Elasticsearch. We could investigate ways to take on this task that would normally be the responsibility of an administrator. 

One solution could be to deploy a DeamonSet automatically to tweak this kernel parameter needed for Elasticsearch if users chose to opt-in to this mechanism. The DeamonSet would run a container with minimal resources just to set the kernel up. The advantage would be that new k8s nodes would automatically be configured correctly. The disadvantage would be that these containers need to be privileged and that they would keep running forever.

**Comment by barkbay** [comment]
> One solution could be to deploy a DeamonSet automatically to tweak this kernel parameter needed for Elasticsearch if users chose to opt-in to this mechanism. The DeamonSet would run a container with minimal resources just to set the kernel up.

I'm trying to figure out what this `DaemonSet` would look like, maybe something along those lines:

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: max-map-count-setter
  namespace: elastic-system
  labels:
    k8s-app: max-map-count-setter
spec:
  selector:
    matchLabels:
      name: max-map-count-setter
  template:
    metadata:
      labels:
        name: max-map-count-setter
    spec:
      containers:
      - name: max-map-count-setter
        image: docker.io/bash:5.2.15
        resources:
          limits:
            cpu: 100m
            memory: 32Mi
        securityContext:
          privileged: true
          runAsUser: 0
        ## We do not use "sysctl -w ...." here as sysctl does not return a valid error code if something goes wrong.
        command: ['/usr/local/bin/bash', '-e', '-c', 'while true; do echo 262144 > /proc/sys/vm/max_map_count; sleep 10; done']
```
