### ISSUE TITLE
Document known Kibana <8.4.0 bug that prevents xpack.fleet.agents.* settings updates

### ISSUE THREAD

**Issue by thbkrkr** [elastic/cloud-on-k8s#6244]
To have Fleet running properly, there are some settings to correctly set in the Kibana configuration as described in the [Run Fleet-managed Elastic Agent on ECK > Configure Kibana](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-elastic-agent-fleet-configuration.html#k8s-elastic-agent-fleet-configuration-required-kibana-configuration) doc.

```yaml
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-sample
spec:
  config:
    xpack.fleet.agents.elasticsearch.hosts: ["https://es-sample-es-http.default.svc:9200"]    # this setting
    xpack.fleet.agents.fleet_server.hosts: ["https://fs-sample-agent-http.default.svc:8220"]  # and this setting
```

Until Kibana 8.4.0, there is a bug that prevents the settings specified with the above keys to be updated when Kibana restarts:

- https://github.com/elastic/kibana/issues/105400
- https://github.com/elastic/kibana/pull/135669

If you are using a lower version than 8.4.0, the workaround is to edit these settings in the Kibana UI and remove them from the kibana configuration.
