### ISSUE TITLE
Custom initContainers config is being ignored. Containers are not being executed.

### ISSUE THREAD

**Issue by ben5556** [elastic/cloud-on-k8s#6245]
Custom initContainers config is being ignored. Containers are not being executed.

Steps to reproduce:

1) Apply crds.yaml

`kubectl create -f https://download.elastic.co/downloads/eck/2.5.0/crds.yaml`

2) Deploy operator

`kubectl apply -f https://download.elastic.co/downloads/eck/2.5.0/operator.yaml`

3) Deploy elasticsearch using the below definition

```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic
  namespace: elasticsearch
spec:
  version: 7.17.1
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
  - name: elastic
    count: 3
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        - name: install-plugins
          command:
          - sh
          - -c
          - |
            bin/elasticsearch-plugin install --batch repository-s3
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms2g -Xmx2g"
          resources:
            requests:
              memory: 4Gi
              cpu: 2
            limits:
              memory: 4Gi
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
        storageClassName: gp2
```

Sharing one of the pods describe output as below

  ```
Normal   Scheduled               10m                    default-scheduler                      Successfully assigned elasticsearch/ct-elastic-es-ct-elastic-0 to ip-10-65-17-119.ec2.internal
  Normal   SuccessfulAttachVolume  10m                    attachdetach-controller                AttachVolume.Attach succeeded for volume "pvc-4b3b7ed0-29c3-4832-92cc-397bc7d615e2"
  Normal   Pulling                 10m                    kubelet, ip-10-65-17-119.ec2.internal  Pulling image "docker.elastic.co/elasticsearch/elasticsearch:7.17.1"
  Normal   Pulled                  10m                    kubelet, ip-10-65-17-119.ec2.internal  Successfully pulled image "docker.elastic.co/elasticsearch/elasticsearch:7.17.1" in 16.47248592s
  Normal   Created                 9m54s                  kubelet, ip-10-65-17-119.ec2.internal  Created container elastic-internal-init-filesystem
  Normal   Started                 9m54s                  kubelet, ip-10-65-17-119.ec2.internal  Started container elastic-internal-init-filesystem
  Normal   Pulled                  9m52s                  kubelet, ip-10-65-17-119.ec2.internal  Container image "docker.elastic.co/elasticsearch/elasticsearch:7.17.1" already present on machine
  Normal   Created                 9m52s                  kubelet, ip-10-65-17-119.ec2.internal  Created container elastic-internal-suspend
  Normal   Started                 9m51s                  kubelet, ip-10-65-17-119.ec2.internal  Started container elastic-internal-suspend
  Normal   Pulled                  9m51s                  kubelet, ip-10-65-17-119.ec2.internal  Container image "docker.elastic.co/elasticsearch/elasticsearch:7.17.1" already present on machine
  Normal   Created                 9m51s                  kubelet, ip-10-65-17-119.ec2.internal  Created container elasticsearch
  Normal   Started                 9m50s                  kubelet, ip-10-65-17-119.ec2.internal  Started container elasticsearch
```

The output shows the custom initContainers did not run and hence the sysctl command and the plugin installation did not happen.

kubectl version

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.14-eks-fb459a0", GitCommit:"b07006b2e59857b13fe5057a956e86225f0e82b7", GitTreeState:"clean", BuildDate:"2022-10-24T20:32:54Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

AWS EKS version: 1.21

Why is this occurring ? What am I missing ?
