### ISSUE TITLE
Allow custom images in services deployment

### ISSUE THREAD

**Issue by damaca** [elastic/cloud-on-k8s#6262]
## Proposal

Maybe I'm missing something but as far as I can see there is no way to use a auhtenticated custom registry images in elasticsearch, kibana, etc.. crds as doesn't seem to be possible add imagePullSecret. Could this be added?

**Comment by naemono** [comment]
https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-customize-pods.html

All of the custom types support a `podTemplate`, which includes `imagePullSecrets`, as below from `Elasticsearch`:
```
  nodeSets:
    - name: master
      count: 3
      config:
        node.roles: ["master"]
      podTemplate:
        spec:
          imagePullSecrets:
            - name: imageregistrykey
```

Going to close this for now.  In the future https://discuss.elastic.co could help with these questions.
