### ISSUE TITLE
Beat installation - Missing Documentation - Elastic Cloud

### ISSUE THREAD

**Issue by jcamu** [elastic/cloud-on-k8s#6268]
Due to the end of the current [beat](https://github.com/elastic/helm-charts/issues/1731) helm chart, we should apparently migrate to this new chart.

But there is no documentation on how to install and configure only beats in K8s and send data to Elastic Cloud ?

**Comment by brsolomon-deloitte** [comment]
Seconding this concern; the docs only cover the `Beat` CRD but not the usage of the chart.

Has the chart actually been uploaded?

```
$ helm pull --repo https://helm.elastic.co --untar --version 0.1.0 eck-beats
Error: chart "eck-beats" version "0.1.0" not found in https://helm.elastic.co repository
```

**Comment by jcamu** [comment]
In addition, even if the beats chart is present in the [main ](https://github.com/elastic/cloud-on-k8s/tree/main/deploy/eck-beats) branch, it seems to not be included in the coming release [2.6.X](https://github.com/elastic/cloud-on-k8s/tree/v2.6.0-bc3/deploy).

Is it expected or an omission ?

**Comment by jcamu** [comment]
Hello.
Any news on this subject ?
How to use this chart to target Elastic Cloud instance and not Reference to ECK-managed Elasticsearch instance.
Is it expected ? Schedule ?
If not, what is the recommended solution for elastic cloud ?

**Comment by naemono** [comment]
@brsolomon-deloitte @jcamu Apologies for the lack of update here. The 1.0 version of ECK-Beats Helm chart was released with the 2.6.x version of ECK Operator on Jan 11. These Helm charts are released during the standard Elastic Stack release schedule, which is roughly every couple of months.

```
❯ helm repo list | grep 'helm\.elastic'
elastic                	https://helm.elastic.co
❯ helm search repo elastic/eck-beats
NAME             	CHART VERSION	APP VERSION	DESCRIPTION
elastic/eck-beats	0.1.0        	           	A Helm chart to deploy Elastic Beats managed by...
```

I'll investigate the documentation difference between the deprecated Beat Helm chart, and this ECK Beat Helm chart in relation to Elastic Cloud and update here.

**Comment by naemono** [comment]
To connect to Elastic Cloud Instance from Beat using ECK Helm Charts:

Create secret containing password for Beats to use
```
kubectl create secret -n default generic elastic-cloud-credentials --from-literal=output.elasticsearch.password=your-password
```

Example values.yaml file
```
name: filebeat-elastic-cloud
version: 8.6.1
spec:
  type: filebeat
  elasticsearchRef: null
  config:
    filebeat.inputs:
    - type: container
      paths:
      - /var/log/containers/*.log
    processors:
    - add_host_metadata: {}
    - add_cloud_metadata: {}
    output.elasticsearch.hosts:
    - https://your-fqdn.elastic-cloud.com
    output.elasticsearch.username: elastic
  secureSettings:
    - secretName: elastic-cloud-credentials
  daemonSet:
    podTemplate:
      spec:
        automountServiceAccountToken: true
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true # Allows to provide richer host metadata
        initContainers:
        - name: elastic-internal-init-keystore
          securityContext:
            privileged: false
            runAsUser: 0
        containers:
        - name: filebeat
          securityContext:
            runAsUser: 0
            # If using Red Hat OpenShift uncomment this:
            #privileged: true
          volumeMounts:
          - name: varlogcontainers
            mountPath: /var/log/containers
          - name: varlogpods
            mountPath: /var/log/pods
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
        volumes:
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
        - name: varlogpods
          hostPath:
            path: /var/log/pods
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
```

Install
```
helm upgrade -i eck-beats elastic -f ./examples/elastic-cloud.yaml -n default
```

I'll keep this open to get the official docs/examples updated.
