### ISSUE TITLE
Beats CRD does not support running as filebeat user

### ISSUE THREAD

**Issue by brsolomon-deloitte** [elastic/cloud-on-k8s#6280]
It appears (undocumented) that the `Beats` CRD / eck-beats does not support running as the `filebeat` user (UID 1000) from the default docker.elastic.co/beats/filebeat image, and must be run as UID 0 (bad security practice).

Config:

```
version: 8.5.3
spec:
  type: filebeat
  deployment:
    replicas: 1
    strategy:
      type: Recreate
    podTemplate:
      spec:
        containers:
          - name: filebeat
            securityContext:
              runAsUser: 1000
```

Error:

```
{"log.level":"info","@timestamp":"2023-01-05T13:59:39.964Z","log.origin":{"file.name":"instance/beat.go","file.line":708},"message":"Home path: [/usr/share/filebeat] Config path: [/usr/share/filebeat] Data path: [/usr/share/filebeat/data] Logs path: [/usr/share/filebeat/logs]","service.name":"filebeat","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2023-01-05T13:59:39.964Z","log.origin":{"file.name":"instance/beat.go","file.line":1057},"message":"Exiting: failed to create Beat meta file: open /usr/share/filebeat/data/meta.json.new: permission denied","service.name":"filebeat","ecs.version":"1.6.0"}
Exiting: failed to create Beat meta file: open /usr/share/filebeat/data/meta.json.new: permission denied
```

**Comment by brsolomon-deloitte** [comment]
Within the container, the filebeat user is `uid=1000(filebeat) gid=1000(filebeat) groups=1000(filebeat),0(root)` and

```
$ ls -ld /usr/share/filebeat/data
drwxrwxr-x 2 root root 6 Dec  4 05:01 /usr/share/filebeat/data
```

This means the filebeat user _should_ have write access there since they are part of the 0 group and the group octal has a `w` bit set.

**Comment by pknetbcn** [comment]
Same here. 

Is there any solution?

**Comment by ebuildy** [comment]
As you noticed, the ECK operator create a hostPath volume for Beat pod.

The hostPath will be mounted as root (k8s / docker side), hence your user cant read it.

A workaround is to use an initContainer, run as root, to chown the volume before running the beat container:

In pod template, add the following initContainer:

```
command:
- sh
- -c
- chown -R 1000:1000 /usr/share/beat/data
image: docker.elastic.co/beats/filebeat:{{ .version }}
imagePullPolicy: IfNotPresent
name: permissions
securityContext:
  runAsUser: 0
volumeMounts:
- mountPath: /usr/share/beat/data
  name: beat-data
```

BUT, the fix will not work if you use secureSetting, because the operator use an initContainer to create the keystore, before the permissions container.

So, you cant run ECK Beat with both secureSettings and respect security best practices.
