### ISSUE TITLE
Set cluster settings outside of nodesets?

### ISSUE THREAD

**Issue by aleks-m** [elastic/cloud-on-k8s#6283]
Hi.

We are trying to customize some cluster settings via via a CRD. Right now we are adding them to nodesets, something like this:
```
spec:
  nodeSets:
  - name: masters
    count: 3
    config:
      node.roles: ["master"]
      xpack.ml.enabled: true
      node.remote_cluster_client: false
      cluster.routing.allocation.disk.watermark.low: "80%" <============ HERE
      cluster.routing.allocation.disk.watermark.high: "85%"
  - name: data
    count: 10
    config:
      node.roles: ["data", "ingest", "ml", "transform"]
      node.remote_cluster_client: false
      cluster.routing.allocation.disk.watermark.low: "80%" <============ HERE
      cluster.routing.allocation.disk.watermark.high: "85%"
```

While this approach in general works fine, it requires a node restart on settings change and can take a long time on clusters with lots of nodes. Is there any way to set cluster-level settings outside of nodesets instead? I can't find anything like that in documentation...
