### ISSUE TITLE
Upgrading ECK to 2.6.0 and ES to 8.6.0 causes ES to fail to bootstrap/form a cluster

### ISSUE THREAD

**Issue by SpencerLN** [elastic/cloud-on-k8s#6303]
## Bug Report
**What did you do?**

Upgraded ECK to 2.6.0 and ES to 8.6.0

**What did you expect to see?**
Elasticsearch to perform a rolling upgrade and continue functioning.

**What did you see instead? Under which circumstances?**
The master nodes failed to successfully form a cluster after ECK performed the rolling upgrade.

```
{"@timestamp":"2023-01-11T01:36:15.170Z", "log.level": "WARN", "message":"master not discovered or elected yet, an election requires at least 2 nodes with ids from [GDLzi1FtQsmIynZWAABPrw, vnn4kgHxQYWJHGADX67xsQ, zfwXTetqR-uSfUkuUo7LKQ], have discovered possible quorum [{quickstart-es-default-1}{zfwXTetqR-uSfUkuUo7LKQ}{trTZbnD4Rzms0uusHaOknA}{quickstart-es-default-1}{10.64.1.8}{10.64.1.8:9300}{cdfhilmrstw}, {quickstart-es-default-2}{vnn4kgHxQYWJHGADX67xsQ}{bAcNneIsRtOoaII1s2JkCg}{quickstart-es-default-2}{10.64.0.9}{10.64.0.9:9300}{cdfhilmrstw}, {quickstart-es-default-0}{GDLzi1FtQsmIynZWAABPrw}{kJ-auB7nTyyvRumjk183ng}{quickstart-es-default-0}{10.64.2.4}{10.64.2.4:9300}{cdfhilmrstw}]; discovery will continue using [10.64.0.9:9300, 10.64.2.4:9300] from hosts providers and [{quickstart-es-default-1}{zfwXTetqR-uSfUkuUo7LKQ}{trTZbnD4Rzms0uusHaOknA}{quickstart-es-default-1}{10.64.1.8}{10.64.1.8:9300}{cdfhilmrstw}] from last-known cluster state; node term 3, last-accepted version 105 in term 2; joining [{quickstart-es-default-2}{vnn4kgHxQYWJHGADX67xsQ}{bAcNneIsRtOoaII1s2JkCg}{quickstart-es-default-2}{10.64.0.9}{10.64.0.9:9300}{cdfhilmrstw}] in term [3] has status [waiting for response] after [9.9m/599788ms]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"elasticsearch[quickstart-es-default-1][cluster_coordination][T#1]","log.logger":"org.elasticsearch.cluster.coordination.ClusterFormationFailureHelper","elasticsearch.node.name":"quickstart-es-default-1","elasticsearch.cluster.name":"quickstart"}
```

**Environment**

* ECK version:

2.5.0 > 2.6.0

* Kubernetes information:
GKE
```
% kubectl version
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.7-gke.900", GitCommit:"e35c4457f66187eff006dda6d2c0fe12144ef2ec", GitTreeState:"clean", BuildDate:"2022-10-26T09:25:34Z", GoVersion:"go1.18.7b7", Compiler:"gc", Platform:"linux/amd64"}
```

* Resource definition:
```
kubectl create -f https://download.elastic.co/downloads/eck/2.5.0/crds.yaml
kubectl apply -f https://download.elastic.co/downloads/eck/2.5.0/operator.yaml
cat <<EOF | kubectl apply -f -
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 8.5.3
  nodeSets:
  - name: default
    count: 3
    config:
      node.store.allow_mmap: false
EOF

kubectl apply -f https://download.elastic.co/downloads/eck/2.6.0/crds.yaml
kubectl apply -f https://download.elastic.co/downloads/eck/2.6.0/operator.yaml
cat <<EOF | kubectl apply -f -
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 8.6.0
  nodeSets:
  - name: default
    count: 3
    config:
      node.store.allow_mmap: false
EOF
```

Upgrading to 8.6.0 without upgrading ECK to 2.6.0 does not seem to cause the same problem.
