### ISSUE TITLE
missing CRD StackConfigPolicy

### ISSUE THREAD

**Issue by b2ronn** [elastic/cloud-on-k8s#6320]
after operator update from 2.5 to 2.6.1
I get errors
```
{"log.level":"error","@timestamp":"2023-01-13T08:26:50.739Z","log.logger":"controller-runtime.source","message":"if kind is a CRD, it should be installed before calling Start","service.version":"2.6.1+62f2e278","service.type":"eck","ecs.version":"1.4.0","kind":"StackConfigPolicy.stackconfigpolicy.k8s.elastic.co","error":"no matches for kind \"StackConfigPolicy\" in version \"stackconfigpolicy.k8s.elastic.co/v1alpha1\"","error.stack_trace":"sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1.1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/source/source.go:139\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:235\nk8s.io/apimachinery/pkg/util/wait.WaitForWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:662\nk8s.io/apimachinery/pkg/util/wait.poll\n\t/go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:596\nk8s.io/apimachinery/pkg/util/wait.PollImmediateUntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/wait/wait.go:547\nsigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/source/source.go:132"}

```
Openshift

**Comment by b2ronn** [comment]
in the CRD from the elastic site(https://download.elastic.co/downloads/eck/2.6.1/crds.yaml ), I see this CRD - 

```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.10.0
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: 'elastic-operator'
    app.kubernetes.io/name: 'eck-operator-crds'
    app.kubernetes.io/version: '2.6.1'
  name: stackconfigpolicies.stackconfigpolicy.k8s.elastic.co
```

 but I don’t see it in the operator hubs

https://github.com/redhat-openshift-ecosystem/certified-operators/tree/main/operators/elasticsearch-eck-operator-certified/2.6.1/manifests
and
https://github.com/k8s-operatorhub/community-operators/pull/2146
