### ISSUE TITLE
Requesting Beats to run as root in "Logstash with ECK" recipe prevents ReplicaSet from starting any pods on OpenShift 4.x as it violates Pod Security Policy

### ISSUE THREAD

**Issue by gkuzmanov** [elastic/cloud-on-k8s#6328]
## Proposal

**Use case. Why is this important?**

## Bug Report
**What did you do?**

Successfully deployed the "Logstash with ECK" recipe (with suitable name/project/namespace adjustments) to a project on OpenShift 4.10 without the last component (a Beats deployment meant to demonstrate successful grok ingestion through Logstash into the Elastic stack).

Then separately imported the YAML for the last (Beats) component.  The ReplicaSet produced by it failed to create any pods.

**What did you expect to see?**

The Beats YAML should create a Beats object managing a Deployment object managing a ReplicaSet object.  The ReplicaSet should create zero or more replica pods depending on the Deployment configuration which it failed due to security errors.

**What did you see instead? Under which circumstances?**

The ReplicaSet failing to create any pods with errors like the following:

```
Error creating: pods "filebeat-beat-filebeat-769854847b-" is forbidden: unable to validate against any security context constraint
```

followed by an array of provider errors (see "Logs" section below) due to the unnecessary "runAsUser: 0" setting in the YAML from the recipe:

```
        containers:
          - name: filebeat
            securityContext:
              runAsUser: 0
```

which should make no difference to the deployments because both volumes in the recipe YAML for the Beats object are defined as emptyDir: {}

**Environment**

* ECK version:

	2.5

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* On premise ?  No
	* Cloud: GKE / EKS / AKS ?  Plain AWS (not the Amazon-managed Kubernetes)
	* Kubernetes distribution: Openshift / Rancher / PKS ?  OpenShift 4.10 deployed on AWS virtual machine cluster
	
	for each of them please give us the version you are using
```
$ kubectl version

Client Version: 4.10.0-202204291519.p0.g09f825e.assembly.stream-09f825e
Kubernetes Version: v1.23.5+012e945
```

* Resource definition:
```
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: filebeat
  labels:
    app.kubernetes.io/name: eck-logstash
    app.kubernetes.io/component: filebeat
spec:
  type: filebeat
  version: 8.5.0
  config:
    filebeat.inputs:
      - type: log
        paths:
          - /data/logstash-tutorial.log
    output.logstash:
      hosts: ["logstash.default.svc:5044"]
  deployment:
    podTemplate:
      metadata:
        labels:
          app.kubernetes.io/name: eck-logstash
          app.kubernetes.io/component: filebeat
      spec:
        automountServiceAccountToken: true
        initContainers:
          - name: download-tutorial
            image: curlimages/curl
            command: ["/bin/sh"]
            args: ["-c", "curl -L https://download.elastic.co/demos/logstash/gettingstarted/logstash-tutorial.log.gz | gunzip -c > /data/logstash-tutorial.log"]
            volumeMounts:
              - name: data
                mountPath: /data
        containers:
          - name: filebeat
            securityContext:
              runAsUser: 0
            volumeMounts:
              - name: data
                mountPath: /data
              - name: beat-data
                mountPath: /usr/share/filebeat/data
        volumes:
          - name: data
            emptydir: {}
          - name: beat-data
            emptydir: {}
```

* Logs:
```
Error creating: pods "filebeat-beat-filebeat-769854847b-" is forbidden: unable to validate against any security context constraint:
[
  provider "anyuid": Forbidden: not usable by user or serviceaccount,
  provider "pipelines-scc": Forbidden: not usable by user or serviceaccount,
  spec.containers[0].securityContext.runAsUser: Invalid value: 0: must be in the ranges: [1001270000, 1001279999],
  provider "nonroot": Forbidden: not usable by user or serviceaccount,
  provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount,
  provider "elasticsearch-scc": Forbidden: not usable by user or serviceaccount,
  provider "log-collector-scc": Forbidden: not usable by user or serviceaccount,
  provider "machine-api-termination-handler": Forbidden: not usable by user or serviceaccount,
  provider "hostnetwork": Forbidden: not usable by user or serviceaccount,
  provider "hostaccess": Forbidden: not usable by user or serviceaccount,
  provider "node-exporter": Forbidden: not usable by user or serviceaccount,
  provider "privileged": Forbidden: not usable by user or serviceaccount
]
```
