### ISSUE TITLE
Feature request: Add support for topologyKeys for the ES Service

### ISSUE THREAD

**Issue by timstoop** [elastic/cloud-on-k8s#6341]
## Proposal

I'd like to see support for `topologyKeys` in the ElasticSearch service spec. Currently, it does not validate when trying to add it like this:

```
spec:
  version: 8.6.0
  transport:
    service:
      spec:
        topologyKeys:
          - "kubernetes.io/hostname"
          - "topology.kubernetes.io/zone"
          - "*"
```
Using a custom service for this with the topologyKeys set gives us an increase in performance and (slightly, but noticable) less cross-zone traffic.

More about this setting can be found here: https://kubernetes.io/docs/concepts/services-networking/service-topology/

**Comment by KnechtionsCoding** [comment]
@timstoop I'll note the feature you are asking for is deprecated. https://kubernetes.io/docs/concepts/services-networking/topology-aware-hints/ is the replacement and still in beta

**Comment by barkbay** [comment]
As mentioned `topologyKeys` are now deprecated. When relevant, you can enable Topology Aware Hints by setting the `service.kubernetes.io/topology-aware-hints` annotation to `auto`, for example:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
spec:
  version: 8.7.0
  nodeSets:
  - name: default
    config:
      node.roles: ["master", "data", "ingest", "ml"]
      node.store.allow_mmap: false
    count: 3
  http:
    service:
      metadata:
        annotations:
          service.kubernetes.io/topology-aware-hints: auto
```

```
k get endpointslices.discovery.k8s.io -l kubernetes.io/service-name=elasticsearch-sample-es-http -o jsonpath="{range .items[*].endpoints[*]}{.addresses}{.hints.forZones}{end}
```

```json
[
  "11.94.194.14"
]
[
  {
    "name": "europe-west9-c"
  }
]
[
  "11.94.193.7"
]
[
  {
    "name": "europe-west9-b"
  }
]
[
  "11.94.192.6"
]
[
  {
    "name": "europe-west9-a"
  }
]
```
