### ISSUE TITLE
Cannot configure stack monitoring on Beats

### ISSUE THREAD

**Issue by bsakmd** [elastic/cloud-on-k8s#6362]
## Bug Report
**What did you do?**
I set up stack monitoring as per [ECK docs](https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-stack-monitoring.html) for self-monitoring of Elasticsearch cluster and Kibana, and this went well. I can view monitoring data in stack monitoring page. In this case I am populating elasticsearchRefs using the names of Elastic resources since this is the same k8s cluster.

I then wanted to configure stack monitoring in Beats deployed on the same cluster -  following the above doc.

**What did you expect to see?**
Metric data from filebeat in Elasticsearch.

**What did you see instead? Under which circumstances?**
First of all, there were no changes made to the Beat daemonset at all.  When I manually deleted one pod then the newly recreated started with new config.
However this new one went into loop-crash with following error:
`Exiting: could not start the HTTP server for the API: listen unix /var/shared/filebeat-eck-filebeat.sock: bind: no such file or directory`

When I looked into config generated by ECK it looks like this:
```
filebeat:
  autodiscover:
    providers:
    - hints:
        default_config:
          paths:
          - /var/log/containers/*${data.kubernetes.container.id}.log
          type: container
        enabled: true
      host: ${HOSTNAME}
      type: kubernetes
  modules:
  - log:
      enabled: true
      var:
        paths:
        - /var/log/audit/audit.log
    module: auditd
http:
  enabled: true
  host: unix:///var/shared/filebeat-eck-filebeat.sock
  port: null
logging:
  files:
    path: /usr/share/filebeat/logs
  to_files: true
  to_stderr: false
  to_syslog: false
monitoring:
  enabled: false
output:
  elasticsearch:
    api_key: ${ID}:${API_KEY}
    hosts:
    - https://elasticsearch-es-http.eck.svc:9200
    ssl:
      verification_mode: none
processors:
- add_cloud_metadata: null
- add_host_metadata: null
setup:
  dashboards:
    enabled: true
  kibana:
    host: https://kibana-kb-http.eck.svc:5601
    ssl:
      certificate_authorities:
      - /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
      verification_mode: none
```
When I manually tweaked the path it started successfully:
` host: unix:///var/run/filebeat-eck-filebeat.sock`

I tried to put elasticsearch reference via secret instead of instance reference but it made no difference.

I have upgrade the ECK from v2.5.0 to v2.6.2 but it gives same results.

**Environment**

* ECK version:

	2.5.0 & 2.6.2

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* Cloud: Azure, self-manged VMs
	* Kubernetes distribution: Openshift  4.11.18
	
	for each of them please give us the version you are using
```
$ oc version
bash-4.4 ~ $ oc version
Client Version: 4.11.2
Kustomize Version: v4.5.4
Server Version: 4.11.18
Kubernetes Version: v1.24.6+5658434
```

* Resource definition:
https://gist.github.com/bsakmd/82f1cd083fc207dcad0fe0769309dd65

* Logs:
```
`Exiting: could not start the HTTP server for the API: listen unix /var/shared/filebeat-eck-filebeat.sock: bind: no such file or directory`
```
