### ISSUE TITLE
E2E: Single Node ES cluster + Kibana with 8.7.0-Snapshot failing

### ISSUE THREAD

**Issue by naemono** [elastic/cloud-on-k8s#6371]
Currently running `8.7.0-SNAPSHOT` version of *A single node* Elasticsearch + Kibana is not in a functional state.

Apply the following manifest:

```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: testing
spec:
  version: 8.7.0-SNAPSHOT
  nodeSets:
    - name: masters
      count: 1
      config:
        node.roles: ["master", "data"]
        node.store.allow_mmap: false
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: testing
spec:
  version: 8.7.0-SNAPSHOT
  count: 1
  elasticsearchRef:
    name: testing
```

`_cat/shards` shows

```
health status index               uuid                   pri rep docs.count docs.deleted store.size pri.store.size sth
yellow open   .apm-source-map     g_oQPDz-Qx6isHYE16YLiQ   1   1          0            0       225b           225b false
```

Note that there's a replica of `1`.  

The fix is being tracked in https://github.com/elastic/kibana/pull/149979, and has been merged.  Until this is contained within the `-SNAPSHOT` image, we may want to disable the `TestAPMKibanaAssociation` test, as it exhibits this behavior.
