### ISSUE TITLE
Operator crashes on startup with OOMKilled

### ISSUE THREAD

**Issue by b2ronn** [elastic/cloud-on-k8s#6386]
In deployment resources:
```
        - resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 150Mi
```

But the operator uses ~1130 MiB
change resources for deployment
```
kubectl patch deployment elastic-operator -n elastic-operator -p '{"spec":{"template":{"spec":{"containers":[{"name":"manager", "resources":{"limits":{"memory":"2Gi"}}}]}}}}'
```
Or through UI
and get a warning
```
This resource is managed by ClusterServiceVersion CSV elasticsearch-eck-operator-certified.v2.6.2  and any modifications may be overwritten. Edit the managing resource to preserve changes.
```

container starts with the new limits. but after a some time the limits change to those specified in the CSV and the operator again crashes with OOMKilled.

OpenShift version 4.11.25
elasticsearch-eck-operator-certified v2.6.2

**Comment by naemono** [comment]
The warning is noting where to adjust this: `ClusterServiceVersion CSV elasticsearch-eck-operator-certified.v2.6.2`.  Below you will see the install spec in the `clusterserviceversion.yaml`.

Please direct questions that are not bugs to [the Elastic forums](https://discuss.elastic.co/).  The Github issues are typically reserved for bugs, and feature requests.  We found that typical installations do not exceed the 1Gi memory allocation.

```
  install:
    spec:
      deployments:
      - name: elastic-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: elastic-operator
          template:
            metadata:
              annotations:
                "co.elastic.logs/raw": "[{\"type\":\"container\",\"json.keys_under_root\":true,\"paths\":[\"/var/log/containers/*${data.kubernetes.container.id}.log\"],\"processors\":[{\"convert\":{\"mode\":\"rename\",\"ignore_missing\":true,\"fields\":[{\"from\":\"error\",\"to\":\"_error\"}]}},{\"convert\":{\"mode\":\"rename\",\"ignore_missing\":true,\"fields\":[{\"from\":\"_error\",\"to\":\"error.message\"}]}},{\"convert\":{\"mode\":\"rename\",\"ignore_missing\":true,\"fields\":[{\"from\":\"source\",\"to\":\"_source\"}]}},{\"convert\":{\"mode\":\"rename\",\"ignore_missing\":true,\"fields\":[{\"from\":\"_source\",\"to\":\"event.source\"}]}}]}]"
              labels:
                control-plane: elastic-operator
            spec:
              serviceAccountName: elastic-operator
              containers:
              - image: docker.elastic.co/eck/eck-operator:v2.6.2
                name: manager
                args:
                  - "manager"
                  - "--config=/conf/eck.yaml"
                  - "--manage-webhook-certs=false"
                  - "--enable-webhook"
                  - "--distribution-channel=upstream-community-operators"
                env:
                - name: NAMESPACES
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: OPERATOR_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.operatorNamespace']
                - name: OPERATOR_IMAGE
                  value: docker.elastic.co/eck/eck-operator:v2.6.2
                resources:
                  limits:
                    cpu: 1
                    memory: 1Gi
                  requests:
                    cpu: 100m
                    memory: 150Mi
```
