### ISSUE TITLE
Elastic ECK - EKS IRSA repository_verification_exception - Connection pool shut down

### ISSUE THREAD

**Issue by tomsozolins** [elastic/cloud-on-k8s#6414]
## Bug Report
**What did you do?**
Configured elasticsearch s3 snapshot repository according to the documentation of using EKS IRSA method 
 - https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-snapshots.html#k8s-iam-service-accounts

**What did you expect to see?**
Successfull connection to the s3 repository.

**What did you see instead? Under which circumstances?**
Initial connection to s3 repository is working fine but after restarting data nodes and master nodes getting error when clicking verify repository in kibana interface - Verification status Not connected.

Restarting all elasticsearch pods again resolves the problem.

**Environment**

* ECK version:
  2.6.1

* Elasticsearch version:
  8.6.0

* Kubernetes information:
   EKS 1.22

* AWS policy definition:
```
{
      "Statement": [
          {
              "Action": [
                  "s3:ListBucketMultipartUploads",
                  "s3:ListBucketVersions",
                  "s3:ListBucket",
                  "s3:GetBucketLocation"
              ],
              "Effect": "Allow",
              "Resource": [
                  "arn:aws:s3:::example-cluster-elasticsearch"
              ]
          },
          {
              "Action": [
                  "s3:PutObject",
                  "s3:GetObject",
                  "s3:AbortMultipartUpload",
                  "s3:DeleteObject",
                  "s3:ListMultipartUploadParts"
              ],
              "Effect": "Allow",
              "Resource": [
                  "arn:aws:s3:::example-cluster-elasticsearch/*"
              ]
          }
      ],
      "Version": "2012-10-17"
  }
```
* Master and Data nodes resource definition:
```
podTemplate:
              spec:
                serviceAccountName: elasticsearch
                automountServiceAccountToken: true
                containers:
                - name: elasticsearch
                  env:
                    - name: AWS_ROLE_SESSION_NAME
                      value: "example-cluster-elasticsearch"
                    - name: AWS_WEB_IDENTITY_TOKEN_FILE
                      value: "/usr/share/elasticsearch/config/repository-s3/aws-web-identity-token-file" 
                    - name: AWS_ROLE_ARN
                      value: "arn:aws:iam::123456789:role/example-cluster-elasticsearch"
                  volumeMounts:
                    - name: aws-iam-token
                      mountPath: /usr/share/elasticsearch/config/repository-s3
                volumes:
                  - name: aws-iam-token
                    projected:
                      sources:
                      - serviceAccountToken:
                          audience: sts.amazonaws.com
                          expirationSeconds: 86400
                          path: aws-web-identity-token-file
```
* ServiceAccount resource definition:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elasticsearch
  namespace: elastic-stack
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789:role/example-cluster-elasticsearch
```

* Logs - elasticsearch pods:
```
{
  "name": "ResponseError",
  "meta": {
    "body": {
      "error": {
        "root_cause": [
          {
            "type": "repository_verification_exception",
            "reason": "[example_cluster_elasticsearch_s3_repository] path  is not accessible on master node"
          }
        ],
        "type": "repository_verification_exception",
        "reason": "[example_cluster_elasticsearch_s3_repository] path  is not accessible on master node",
        "caused_by": {
          "type": "i_o_exception",
          "reason": "Unable to upload object [tests-G_VDq3WjTIe9C1XqTWqzHQ/master.dat] using a single upload",
          "caused_by": {
            "type": "amazon_client_exception",
            "reason": "amazon_client_exception: java.lang.IllegalStateException: Connection pool shut down",
            "caused_by": {
              "type": "illegal_state_exception",
              "reason": "Connection pool shut down"
            }
          }
        }
      },
      "status": 500
    },
    "statusCode": 500,
    "headers": {
      "x-opaque-id": "id;kibana:application:management:",
      "x-elastic-product": "Elasticsearch",
      "content-type": "application/json;charset=utf-8",
      "content-length": "683"
    },
    "meta": {
      "context": null,
      "request": {
        "params": {
          "method": "POST",
          "path": "/_snapshot/example_cluster_elasticsearch_s3_repository/_verify",
          "querystring": "",
          "headers": {
            "user-agent": "Kibana/8.6.0",
            "x-elastic-product-origin": "kibana",
            "authorization": "Bearer token",
            "x-opaque-id": "id;kibana:application:management:",
            "x-elastic-client-meta": "es=8.4.0p,js=16.18.1,t=8.2.0,hc=16.18.1",
            "accept": "application/vnd.elasticsearch+json; compatible-with=8,text/plain"
          }
        },
        "options": {
          "opaqueId": "id;kibana:application:management:",
          "headers": {
            "x-elastic-product-origin": "kibana",
            "user-agent": "Kibana/8.6.0",
            "authorization": "Bearer token",
            "x-opaque-id": "token",
            "x-elastic-client-meta": "es=8.4.0p,js=16.18.1,t=8.2.0,hc=16.18.1"
          }
        },
        "id": 1
      },
      "name": "elasticsearch-js",
      "connection": {
        "url": "https://elasticsearch-es-data.elastic-stack.svc:9200/",
        "id": "https://elasticsearch-es-data.elastic-stack.svc:9200/",
        "headers": {},
        "status": "alive"
      },
      "attempts": 0,
      "aborted": false
    },
    "warnings": null
  }
}
```
