### ISSUE TITLE
Kibana readiness probe for anonymous authentication

### ISSUE THREAD

**Issue by thbkrkr** [elastic/cloud-on-k8s#6417]
If you enable [Kibana anonymous authentication](https://www.elastic.co/guide/en/kibana/current/kibana-authentication.html#anonymous-authentication), you have to override the path of the Kibana readiness probe because `/login` doesn't exist anymore.

```yaml
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
...
spec:
  podTemplate:
    spec:
      containers:
      - name: kibana
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 5601
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
```

Relates to:
- https://github.com/elastic/cloud-on-k8s/issues/4560
- https://github.com/elastic/cloud-on-k8s/issues/5990
- https://github.com/elastic/cloud-on-k8s/issues/6378

Because several issues about this exist, I wonder if this is something we should document or go further and detect anonymous mode to correctly configure the probe?
