### ISSUE TITLE
Challenge connecting logstash with filebeat,which is running in different K8s cluster 

### ISSUE THREAD

**Issue by chetan94k** [elastic/cloud-on-k8s#6421]
Team I have 2 k8s cluster and having logstash and filebeat in different clusters. I have exposed logstash with ingress on nodebalancer in Linode cloud so that I can configure it in file beat . But facing below error:

```json
{
    "log.level": "info",
    "@timestamp": "2023-02-16T11:33:17.241Z",
    "log.logger": "publisher_pipeline_output",
    "log.origin": {
        "file.name": "pipeline/client_worker.go",
        "file.line": 147
    },
    "message": "Connection to backoff(async(tcp://[Host_name]:5044)) established",
    "service.name": "filebeat",
    "ecs.version": "1.6.0"
}
{
    "log.level": "error",
    "@timestamp": "2023-02-16T11:33:17.391Z",
    "log.logger": "logstash",
    "log.origin": {
        "file.name": "logstash/async.go",
        "file.line": 280
    },
    "message": "Failed to publish events caused by: lumberjack protocol error",
    "service.name": "filebeat",
    "ecs.version": "1.6.0"
}
{
    "log.level": "error",
    "@timestamp": "2023-02-16T11:33:17.474Z",
    "log.logger": "logstash",
    "log.origin": {
        "file.name": "logstash/async.go",
        "file.line": 280
    },
    "message": "Failed to publish events caused by: client is not connected",
    "service.name": "filebeat",
    "ecs.version": "1.6.0"
}
```

Using 8.5.1 v of ELK stack

Logstash config:
```
logstashPipeline:
  logstash.conf: |
    input {
      beats {
        port => 5044  
        ssl => false
      }
      tcp {
        mode => "server"
        codec => "json"
        port => "5055"
        ssl_enable => false
      }
    }
    output { 
      elasticsearch { 
        hosts => "https://elasticsearch-master:9200"
        user => '${ELASTICSEARCH_USERNAME}'
        password => '${ELASTICSEARCH_PASSWORD}'
        index => "onprem"
        ssl_certificate_verification => false
      } 
    }
```

Filebeat config:
```
  filebeatConfig:
    filebeat.yml: |
      filebeat.inputs:
      - type: container
        paths:
          - /var/log/containers/*.log
        processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"
      
      output.logstash:
        hosts: ["[Logstash_hostname]:5044"]
```

Logstash_hostname is Node balancer hostname.

Appreciate your help.
