### ISSUE TITLE
Expose all fields below spec in eck-resources Helm charts

### ISSUE THREAD

**Issue by thbkrkr** [elastic/cloud-on-k8s#6451]
Follow-up of #6249, there are 4 fields that are not exposed in the eck-elasticsearch Helm chart:

```yaml
spec:
  image:
  podDisruptionBudget:
  serviceAccountName:
  revisionHistoryLimit:
```

Let's make a pass on other elastic resources to verify that their Helm chart is ISO with the CRD....
