### ISSUE TITLE
Elastic agent crashloops after manifest update

### ISSUE THREAD

**Issue by boernd** [elastic/cloud-on-k8s#6468]
## Bug Report
**What did you do?**

I have an agent configured in `standalone` mode with the following config:
```
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  labels:
    app.kubernetes.io/managed-by: pulumi
  name: xyz
  namespace: xyz
spec:
  config:
    inputs:
    - type: apm
      vars:
      - name: host
        value: 0.0.0.0:8200
  deployment:
    podTemplate:
      metadata:
        annotations:
          co.elastic.logs.apm/json.keys_under_root: "true"
          co.elastic.logs.apm/json.message_key: message
      spec:
        containers:
        - name: agent
          resources:
            limits:
              cpu: 500m
              memory: 250Mi
            requests:
              cpu: 150m
              memory: 250Mi
        securityContext:
          runAsUser: 0
        volumes:
[...]
    replicas: 1
  elasticsearchRefs:
  - name: xyz
[...]
  mode: standalone
  version: 8.6.2
```

If I do a change to the Agent manifest (e.g. changing resources) the new pod does not start but ends in a crashloop.
```
Error: another elastic-agent is already running
```
It looks like that this is due to the fact that the `agent-data` volume is host bound. For the APM use case I was able to work around this by overwriting the volume part but for e.g. logs I guess this is problematic:
```
        volumes:
        - emptyDir:
            sizeLimit: 100Mi
          name: agent-data
```

**What did you expect to see?**

Rolling update works.

**What did you see instead? Under which circumstances?**

New pod ends in a crashloop.

**Environment**

* ECK version:

	2.6.1

* Kubernetes information:

	EKS v1.24.8
