### ISSUE TITLE
k3s - basic elastic search failed to be ready - operator cannot get health status

### ISSUE THREAD

**Issue by IzioDev** [elastic/cloud-on-k8s#6488]
## Bug Report
**What did you do?**

Followed the installation 'basics' guide:
1. Installed the operator
2. Tried to install an `ElasticSearch` resource

**What did you expect to see?**

I was expecting to see `elasticsearch` statefullset up and running

**What did you see instead? Under which circumstances?**

The statefullset is not ready, and operator is trying to reconciliate in loop, with the same error messages

**Environment**

* ECK version:

	`2.6.1`

* Kubernetes information:

On Premise, with `k3s` : v1.25.6+k3s1 (9176e03c)

```
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:58:16Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.6+k3s1", GitCommit:"9176e03c5788e467420376d10a1da2b6de6ff31f", GitTreeState:"clean", BuildDate:"2023-01-26T00:47:47Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Resource definition:
```
# kustomization
namespace: obs
resources:
- https://download.elastic.co/downloads/eck/2.6.1/crds.yaml
- https://download.elastic.co/downloads/eck/2.6.1/operator.yaml
- ./elasticsearch.yaml

# elasticsearch.yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 8.6.2
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources: # I tried to tweak this, even ommiting it, it doesn't seems to change anything
            requests:
              memory: 3Gi
              cpu: 4
            limits:
              memory: 3Gi
```

* Logs:
```
{"log.level":"info","@timestamp":"2023-03-05T17:30:15.840Z","log.logger":"elasticsearch-controller","message":"Starting reconciliation run","service.version":"2.6.1+62f2e278","service.type":"eck","ecs.version":"1.4.0","iteration":"20","namespace":"obs","es_name":"elasticsearch"}
{"log.level":"debug","@timestamp":"2023-03-05T17:30:15.844Z","log.logger":"elasticsearch-controller","message":"Some pods still need to be created/deleted","service.version":"2.6.1+62f2e278","service.type":"eck","ecs.version":"1.4.0","iteration":"20","namespace":"obs","es_name":"elasticsearch","namespace":"obs","statefulset_name":"elasticsearch-es-default","pending_creations":["elasticsearch-es-default-0"],"pending_deletions":[]}
{"log.level":"debug","@timestamp":"2023-03-05T17:30:15.844Z","log.logger":"elasticsearch-controller","message":"Skipping annotation update","service.version":"2.6.1+62f2e278","service.type":"eck","ecs.version":"1.4.0","iteration":"20","namespace":"obs","es_name":"elasticsearch","es_name":"elasticsearch","namespace":"obs"}
{"log.level":"info","@timestamp":"2023-03-05T17:30:15.844Z","log.logger":"elasticsearch-controller","message":"Ending reconciliation run","service.version":"2.6.1+62f2e278","service.type":"eck","ecs.version":"1.4.0","iteration":"20","namespace":"obs","es_name":"elasticsearch","took":0.004117114}
{"log.level":"debug","@timestamp":"2023-03-05T17:30:25.778Z","log.logger":"elasticsearch-observer","message":"Unable to retrieve cluster health","service.version":"2.6.1+62f2e278","service.type":"eck","ecs.version":"1.4.0","error":"elasticsearch client failed for https://elasticsearch-es-internal-http.obs.svc:9200/_cluster/health: Get \"https://elasticsearch-es-internal-http.obs.svc:9200/_cluster/health\": context deadline exceeded","namespace":"obs","es_name":"elasticsearch"}
{"log.level":"debug","@timestamp":"2023-03-05T17:30:25.778Z","log.logger":"elasticsearch-observer","message":"Retrieving cluster health","service.version":"2.6.1+62f2e278","service.type":"eck","ecs.version":"1.4.0","es_name":"elasticsearch","namespace":"obs"}
{"log.level":"debug","@timestamp":"2023-03-05T17:30:25.778Z","log.logger":"elasticsearch-observer","message":"Elasticsearch HTTP request","service.version":"2.6.1+62f2e278","service.type":"eck","ecs.version":"1.4.0","method":"GET","url":"https://elasticsearch-es-internal-http.obs.svc:9200/_cluster/health","namespace":"obs","es_name":"elasticsearch"}
```

* Resources (same namespace: `elastic-kube`)
```
NAME                     READY   STATUS    RESTARTS   AGE
pod/elastic-operator-0   1/1     Running   0          28m

NAME                                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
service/elastic-webhook-server           ClusterIP   10.43.17.50     <none>        443/TCP    28m
service/elasticsearch-es-default         ClusterIP   None            <none>        9200/TCP   28m
service/elasticsearch-es-http            ClusterIP   10.43.169.63    <none>        9200/TCP   28m
service/elasticsearch-es-internal-http   ClusterIP   10.43.168.156   <none>        9200/TCP   28m
service/elasticsearch-es-transport       ClusterIP   None            <none>        9300/TCP   28m

NAME                                        READY   AGE
statefulset.apps/elastic-operator           1/1     28m
statefulset.apps/elasticsearch-es-default   0/1     28m
```
