### ISSUE TITLE
ECK/Elastic Agent Custom Kafka Logs Integration not working if TLS is enabled in Kibana

### ISSUE THREAD

**Issue by smithd1** [elastic/cloud-on-k8s#6512]
## Bug Report
**What did you do?**
Elastic Agent "Custom Kafka Logs" integration in ECK/Elastic stack not working if Kibana has TLS enabled.

**What did you expect to see?**
Expected ECK Elastic Agent Custom Kafka Logs to work with TLS enabled.

**What did you see instead? Under which circumstances?**
Elastic Agent "Custom Kafka Logs" integration does not work if TLS is enabled in Kibana.  Kibana Filebeats events show error - "error initializing Kafka consumer group id" - and the Kafka server shows no connection attempt from the Elastic Agent.  The Custom Kafka Logs integration with Kibana TLS disabled works fine.  It's only when TLS is enabled in Kibana that this problem occurs.

**Environment**

ECK/Elastic Stack (Kibana, Elasticsearch, APM, Fleet Server, Elastic Agents) v 8.6.2 deployed to RKE2 Kubernetes cluster (v1.21.6+rke2r1) in AWS.  The K8S cluster and ECK/ES stack are self managed.

**Comment by pebrc** [comment]
Can you share more about your Kafka setup? Have you set up TLS between broker and clients? I am slightly surprised by your statement that Kibana TLS has an effect on the integration working or not, because Kibana plays no role in this (at least not directly) When you configure the Kafka integration through Fleet a Filebeat component is configured and run inside the Elastic Agent that are set up with Fleet. These Filebeat process have a Kafka input configured to talk to your Kafka installation to read from the topic you configured.

**Comment by smithd1** [comment]
Hi, Peter,

Thanks for helping out here.  I appreciated it.

I have tested the Kafka set up both with TLS enabled (TCP port 9093) and
without (TCP port 9092) and the Custom Kafka Logs integration breaks if
Kibana has TLS enabled at the application level.  I've tested various
permutations of TLS settings enabled/disabled in the Elastic stack and on
Kafka and I've tested this repeatedly - it only breaks when Kibana has TLS
is enabled at the application level.  I'm not saying that it isn't due
to some setting that I may have missed, but I have not found anything to
account for this problem and the only commonality is the Kibana TLS
setting.  I am wondering if the Filebeats in the Elastic Agent is able to
set up the communication with the Kafka pod because when monitoring the
logs on the Kafka pod during testing, it never sees a connection attempt
from the Elastic Agent when Kibana has TLS enabled.  FYI, I set up the
Custom Kafka Logs integration in the Elastic Agents through the Kibana
interface.  The Elastic stack (KIbana, Elasticsearch, Fleet Server, Elastic
Agents) are all deployed under ECK (all v8.6.2).  If I have TLS enabled at
the application level for all components in the Elastic stack - Kibana,
Elasticsearch, etc., the Custom Kafka Logs integration does not work
("cannot initialize Kafka consumer id").  If I disable TLS at the
application level in Kibana only (leaving everything else the same),
the Custom Kafka Logs integration works fine on both Kafka ports (9092 and
9093).  Also, I have manually tested producers and consumers for Kafka
topics on both 9092 and 9093 from another pod in the cluster and it works
fine.

[Aside] Is it possible to get documentation of all the xpack security
settings available?  I mean, a full api not a partial listing.  During
testing I searched forever to find "xpack.fleet.agents.tlsCheckDisabled" in
a user comment in one of the Elastic issue trackers.  This is required to
get the self-signed certificates to work without error and is not
documented (that I could find) on the Elastic web site.  I apologize if
this is documented somewhere, just that I could not find it.

I can provide more information if you'd like - maybe send configs, etc.
Just let me know.

Thanks again for your attention.

Dee

**Comment by pebrc** [comment]
I tested it with both TLS and non-TLS listener. I used a modified version of the manifest we have in our documentation for the [custom logs example](https://www.elastic.co/guide/en/cloud-on-k8s/2.6/k8s-elastic-agent-fleet-configuration-examples.html#k8s_custom_logs_integration_with_autodiscover)

To make it work with a Kafka listener that uses TLS I had to mount the CA certificate Kafka uses in the Elastic Agent Pods because it was a self-signed CA: 

```
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata: 
  name: elastic-agent
spec:
  version: 8.6.2
  kibanaRef:
    name: kibana
  fleetServerRef: 
    name: fleet-server
  mode: fleet
  daemonSet:
    podTemplate:
      spec:
        serviceAccountName: elastic-agent
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0
        containers:
        - name: agent
          volumeMounts:
          - mountPath: /var/lib/docker/containers
            name: varlibdockercontainers
          - mountPath: /var/log/containers
            name: varlogcontainers
          - mountPath: /var/log/pods
            name: varlogpods
          - mountPath: /mnt/kafka-certs
            name: kafka-certs
        volumes:
        - name: kafka-certs
          secret:
            secretName: kafka-certs
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
        - name: varlogpods
          hostPath:
            path: /var/log/pods
```
and I had to configure these certificates in the custom Kafka log Agent policy as illustrated in my screenshot.

<img width="929" alt="Screenshot 2023-03-24 at 19 53 36" src="https://user-images.githubusercontent.com/697790/227614801-ae7826c9-92a8-453e-bbee-8701d5d9da5f.png">
...snip...
<img width="497" alt="Screenshot 2023-03-24 at 19 53 26" src="https://user-images.githubusercontent.com/697790/227614843-25216f48-b18c-4cfa-a19e-8da32c9cab43.png">
...snip...
<img width="473" alt="Screenshot 2023-03-24 at 19 53 14" src="https://user-images.githubusercontent.com/697790/227614838-80c74b4a-b316-4a09-a7b3-82a8403dd05d.png">

At this point I don't see any indication of a bug in the ECK operator that would prevent this integration to work when Kibana runs with TLS enabled (which my Kibana did). I am going to therefore close this issue. If you are continuing to be stuck with this problem and are a paying customer I would recommend to open a support case with Elastic so that someone from the Elastic Agent or Beats team can take a look and help you further.
