### ISSUE TITLE
dry run Helm chart release

### ISSUE THREAD

**Issue by thbkrkr** [elastic/cloud-on-k8s#6537]
#6528 doesn't work as expected ([cloud-on-k8s-operator/builds/2284](https://buildkite.com/elastic/cloud-on-k8s-operator/builds/2284#0186e9a0-61a5-4178-9653-792611c2b68e)).

```
Error: invalid argument "" for "-d, --dry-run" flag: strconv.ParseBool: parsing "": invalid syntax
````

When doing:
```yaml
- command: buildkite-agent pipeline upload other-pipeline.yml
  env:
    K: 42
```

Steps in `pipeline.yml`doesn't get the env `K=42`.

I confused with the step `trigger` but this requires creating a separate pipeline:

```yaml
- trigger: "other-pipeline"
  build:
    env:
      K: 42
```
