### ISSUE TITLE
Allow setting custom TLS certificates via values.yaml 

### ISSUE THREAD

**Issue by johnkm516** [elastic/cloud-on-k8s#6559]
## Proposal

I have been searching for days looking for a solution to my issue and am convinced the current ECK helm charts do not support my use case, or is at least not documented. 
 
I am trying to deploy a self-managed ECK stack with fleet server and agents on my k8s cluster via the ECK helm charts. 
The only documentation I can find regarding setting up custom TLS certs for fleet-server and agents is [here](https://www.elastic.co/guide/en/fleet/master/secure-connections.html) which assumes the user is installing / deploying the fleet server manually through command line, not via the operator. This is my current kibana config : 

```
 spec:
    config:
      xpack.fleet.agents.elasticsearch.hosts: ["https://elasticsearch.example.com"]
      xpack.fleet.agents.fleet_server.hosts: ["https://fleet-server.example.com"]
      xpack.fleet.outputs:
      - id: fleet-default-output
        name: default
        type: elasticsearch
        hosts: [ https://elasticsearch.example.com ]
        # openssl x509 -fingerprint -sha256 -noout -in tls/kibana/elasticsearch-ca.pem (colons removed)
        ca_trusted_fingerprint: <my ca fingerprint>
        is_default: true
        is_default_monitoring: true
      xpack.fleet.packages:
      - name: system
        version: latest
      - name: elastic_agent
        version: latest
      - name: fleet_server
        version: latest
      - name: kubernetes
        version: latest
      - name: apm
        version: latest
      xpack.fleet.agentPolicies:
      - name: Fleet Server on ECK policy
        id: fleet-server
        namespace: default
        monitoring_enabled:
        - logs
        - metrics
        is_default_fleet_server: true
        package_policies:
        - name: fleet_server-1
          id: fleet_server-1
          package:
            name: fleet_server
      - name: Elastic Agent on ECK policy
        id: eck-agent
        namespace: default
        monitoring_enabled:
        - logs
        - metrics
        unenroll_timeout: 900
        is_default: true
        package_policies:
        - package:
            name: system
          name: system-1
        - package:
            name: kubernetes
          name: kubernetes-1
        - package:
            name: apm
          name: apm-1
          inputs:
            - type: apm
              enabled: true
              vars:
                - name: host
                  value: 0.0.0.0:8200
```

I added a template to create a Traefik IngressRoute that does TLS passthrough to fleet-server-agent-http : 

```
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: fleet-server-ingress
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints: 
    - websecure
  tls:
    passthrough: true
  routes:                           # [2]
    - match: HostSNI(`fleet-server.example.com`) # [3]
      services:                       # [8]
      - name: fleet-server-agent-http
        port: https                     # [9]
```

The IngressRoute works, the problem is the certs. Fleet-server generates its own self-signed certs when I deploy the helm chart (and values.yaml of fleet-server in the current repository show no way of customizing TLS certs). Therefore the current fleet-agent certs do not contain the fleet-server.example.com domain and therefore fails to establish TLS. I have tried to manually update the certs by updating the secret ```fleet-server-agent-http-certs-internal``` which is mounted as a volume at ```/usr/share/fleet-server/config/http-certs```, but the secret seems to be managed by the operator and is instantly regenerated to the self-signed certs when I attempt to delete it or update it in any way. 

The use case of making the fleet server endpoint is obvious, it should have a publicly accessible endpoint so that I can enroll agents on machines outside the cluster. 

If it's currently not possible to set custom certs for fleet-server via values.yaml this issue is a feature request for that. 
If it's already possible, this issue is a request to update the current values.yaml to show how that can be done, and an update on documentation as well.

**Comment by pebrc** [comment]
The `eck-fleet-server` Helm chart is just a thin wrapper around the Elastic Agent custom resource with some presets that are necessary to run Elastic Agent in Fleet mode. Because of that any customisation that is possible with the raw Elastic Agent resources is also possible through the Helm chart. 

For example customising the self-signed certificates as [documented here](https://www.elastic.co/guide/en/cloud-on-k8s/2.6/k8s-tls-certificates.html#k8s-static-ip-custom-domain)

```yaml
# values.yml
version: 8.6.2 

spec:
  kibanaRef:
    name: my-kibana 
  elasticsearchRefs:
  - name: my-elasticsearch 
  http:
    tls:
      selfSignedCertificate:
        subjectAltNames:
        - dns: fleet-server.example.com

```
Similarly it is possible to completely move away from the self-signed certs and use your own certificates that you have to provide in form of a secret in the same namespace [as documented here](https://www.elastic.co/guide/en/cloud-on-k8s/2.6/k8s-tls-certificates.html#k8s-setting-up-your-own-certificate)

```yaml
# values.yml
version: 8.6.2 

spec:
  kibanaRef:
    name: my-kibana 
  elasticsearchRefs:
  - name: my-elasticsearch 
  http:
    tls:
      certificate:
        secretName: my-custom-cert
```

Finally you have the option to terminate TLS with Traefik and accept the self-signed certificates behind the proxy. We have an example here https://github.com/elastic/cloud-on-k8s/tree/main/config/recipes/traefik which is also linked in our documentation https://www.elastic.co/guide/en/cloud-on-k8s/2.6/k8s-recipes.html

I am leaving this issue open for us to expand the documentation of the Helm chart to better explain how you can derive a values file for the Helm charts from the existing documentation and how CRD spec and Helm values correspond to each other.
