### ISSUE TITLE
Make the deployer configurable via environment variables

### ISSUE THREAD

**Issue by thbkrkr** [elastic/cloud-on-k8s#6561]
Today, the deployer is configured via a YAML file.

Example:
```yaml
id: gke-ci
overrides:
  vaultInfo:
    address: https://vault.xyz:1234
    rootPath: secret/ci/abcd
  operation: create
  clusterName: eck-e2e-gke-abcd-0
  kubernetesVersion: 1.22
  gke:
    region: europe-west42
```

It is not convenient to use for CI where it's simpler to use environment variables. 

We had to write an intermediate bash script to write the file from environment variables.

https://github.com/elastic/cloud-on-k8s/blob/fcbc995b75a5f99ca7861c195d3b88b4a2b71065/.ci/setenvconfig#L348-L359

In #6525, I moved this into a new script to remove duplicates and isolate the deployer config from the config to build images and the test runner config. Before that, all configs were mixed in `.ci/setenvconfig`.

It would be better if the deployer could be configured directly via environment variables to avoid this bash script which adds an unnecessary extra layer.

I thought of something generic that would give a way to configure any configuration setting:

```sh
DEPLOYER_PLAN_ID=gke-ci
DEPLOYER_vaultInfo_address=https://vault.xyz:1234
DEPLOYER_vaultInfo_rootPath=ecret/ci/abcd
DEPLOYER_operation=create
DEPLOYER_clusterName=eck-e2e-gke-abcd-0
DEPLOYER_kubernetesVersion=1.22
DEPLOYER_gke_region=europe-west42
```
