### ISSUE TITLE
AKS Annotation failed when I'm deploying Kibana to my AKS Cluster

### ISSUE THREAD

**Issue by aharo-lumificyber** [elastic/cloud-on-k8s#6682]
**Kibana version: 7.17**

**Elasticsearch version: 7.17**

**Kubernetes version: 1.24.10**

**Original install method (e.g. download page, yum, from source, etc.): The installation of kibana has been made through Flux and AKS. **

**Describe the bug: I'm adding an annotation to my elastic search to be able to access my services with an internal IP address from my load balancer. The problem is that Elastic search is working as expected but not Kibana. The annotation that I'm using is what is recommended by Microsoft ``` service.beta.kubernetes.io/azure-load-balancer-internal: "true" ``` If I delete the annotation from the Kibana file, I will be able to see the External IP address but I would like to have an internal IP from my load balancer.**

**Steps to reproduce:**
1. Used and follow this guide to create the new deployment https://www.elastic.co/blog/how-to-run-elastic-cloud-on-kubernetes-from-azure-kubernetes-service
2. Add an annotation into the Kibana configuration file: service.beta.kubernetes.io/azure-load-balancer-internal: "true"
3. Commit and push the code. Then, get the service information to see the Internal IP address "kubectl get service kibana" At this point, you will see that the service is empty.

**Expected behavior: I would like to be able to get an internal IP address from my load-balancer to be able to secure my environment**

**Provide logs and/or server output (if relevant):
![Screenshot 2023-04-11 at 10 10 55 PM](https://user-images.githubusercontent.com/122565465/231347422-485c4fee-e184-45e8-ad40-c49292b0cf85.png) **

These are the configuration that I'm using on Elastic-Search:

```

apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
  labels:
    app: elasticsearch
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  version: 7.17.9
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
  http:
    service:
      spec:
        type: LoadBalancer
        ports:
        - port: 9200
        selector:
          app: elasticsearch

```

This is the configuration for Kibana:

```

apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
  labels:
    app: kibana
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  version: 7.17.9
  count: 1
  elasticsearchRef:
    name: quickstart
  http:
    service:
      spec:
        type: LoadBalancer
        ports:
        - port: 5601
        selector:
          app: kibana
```

Please let me know if it is anything that has to be different.

**Comment by thbkrkr** [comment]
You can customise the service by defining a service template under `http.service` (see [API docs](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-api-kibana-k8s-elastic-co-v1.html#k8s-api-github-com-elastic-cloud-on-k8s-v2-pkg-apis-kibana-v1-kibanaspec)).

This is how you would add an annotation to the service:

```yaml
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: hulk
spec:
  version: 8.7.0
  count: 1
  elasticsearchRef:
    name: hulk
  http:
    service:
      metadata:
        annotations:
          my-annotation: value
```

Note that this has already been answered on the [Elastic community forum](https://discuss.elastic.co/t/eck-kib-service-annotation/245937).

**Comment by aharo-lumificyber** [comment]
This does not resolve my problem because the annotation is coming from Microsoft to accomplish of the internal IP from the load balancer inside of AKS. The annotation itself is recommended from Microsoft, and you can see that Elastic search does not have any problem, the issue is only with Kibana @thbkrkr

**Comment by barkbay** [comment]
The `Service` definitions in both your Elasticsearch and Kibana manifests have several problems:
* the `https` Service name must be referenced somewhere
* the selector `app=elasticsearch` in the Service does not match any Pod (same for Kibana)

⬆️  this prevents Kibana to be created and associated to Elasticsearch.

Here is a fixed version ⬇️ 

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
  labels:
    app: elasticsearch
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  version: 7.17.9
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
  http:
    service:
      metadata:
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      spec:
        type: LoadBalancer
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
  labels:
    app: kibana
spec:
  version: 7.17.9
  count: 1
  elasticsearchRef:
    name: quickstart
  http:
    service:
      metadata:
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      spec:
        type: LoadBalancer
```

```
> kubectl get service | grep LoadBalancer
quickstart-es-http            LoadBalancer   10.0.214.53   10.224.0.8    9200:31252/TCP   61s
quickstart-kb-http            LoadBalancer   10.0.115.69   10.224.0.7    5601:30273/TCP   2m4s
```
