### ISSUE TITLE
Proposal - support TCP retransmission timeout

### ISSUE THREAD

**Issue by itayB** [elastic/cloud-on-k8s#6698]
## Proposal

Elasticsearch recommend [TCP retransmission timeout](https://www.elastic.co/guide/en/elasticsearch/reference/8.6/system-config-tcpretries.html#system-config-tcpretries) as important system configuration.
Can we get it out of the box in Elastic operator?
Today, I had to add an initContainer to configure it manually:
```
initContainers:
  - name: tcp-transmission-settings
  image: "busybox:1.36.0"
  imagePullPolicy: IfNotPresent
  command:
  - sysctl
  - -w
  - net.ipv4.tcp_retries2=5
  securityContext:
    privileged: true
```

The issue originally starts [here](https://discuss.elastic.co/t/publication-of-cluster-state-fails-followers-check-retry-count-exceeded/330097/9?u=itay_bittan). 

**Environment**

* ECK version: **2.6.0**

* Kubernetes information: Cloud: EKS 1.22
