### ISSUE TITLE
Document how to deploy Elasticsearch on GKE Autopilot

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#6713]
It is now possible to set the `vm.max_map_count` kernel setting to [the recommended value for Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/master/vm-max-map-count.html) on GKE Autopilot nodes running K8S `1.25` 🎉 
This removes the need for the `node.store.allow_mmap: false` setting in the configuration and allows our users to run Elasticsearch with a configuration that follows our virtual memory recommendations.

The `DaemonSet` that should be deployed to configure the K8S nodes is the following:

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: max-map-count-setter
  namespace: elastic-system
  labels:
    k8s-app: max-map-count-setter
spec:
  selector:
    matchLabels:
      name: max-map-count-setter
  template:
    metadata:
      labels:
        name: max-map-count-setter
    spec:
      initContainers:
        - name: max-map-count-setter
          image: docker.io/bash:5.2.15
          resources:
            limits:
              cpu: 100m
              memory: 32Mi
          securityContext:
            ## privileged is required to write into /proc/sys/vm/max_map_count (read-only otherwise)
            privileged: true
            runAsUser: 0
          ## We do not use "sysctl -w ...." here as sysctl does not return a valid error code if something goes wrong.
          command: ['/usr/local/bin/bash', '-e', '-c', 'echo 262144 > /proc/sys/vm/max_map_count']
      containers:
        - name: sleep
          image: docker.io/bash:5.2.15
          command: ['sleep', 'infinity']
```

We may also want to document how an Elasticsearch Pod can wait for that value to be set by using an init container:

```yaml
    podTemplate:
      spec:
        initContainers:
          - name: max-map-count-check
            command: ['sh', '-c', "while true; do mmc=$(cat /proc/sys/vm/max_map_count); if [ ${mmc} -eq 262144 ]; then exit 0; fi; sleep 1; done"]
```

I wonder how this update should also affect https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-virtual-memory.html, we may want to offer this proposal outside of Autopilot?

Note: I'm adding the `v2.8.0` label on this issue, but it is actually not tied to that ECK version, it can be used on previous versions as long as the Autopilot version is running K8S `1.25`.
