### ISSUE TITLE
eck StackConfigPolicy not applying base_path option properly in snapshotRepositories section

### ISSUE THREAD

**Issue by bjacoby-codes** [elastic/cloud-on-k8s#6730]
## Bug Report
**What did you do?**
Having previously configured our gcs snapshot repositories via the Kibana UI, we wanted to add them as StackConfigPolicy objects to use config as code.  
We Implemented our snapshot repositories in StackConfigPolicy eck objects among other config blocks (the others worked normally):

**What did you expect to see?**
No change since we already set the repositories up via kibana UI and just wanted to get it into code via StackConfigPolicy

**What did you see instead? Under which circumstances?**
When the change was deployed, ECK created 2 new gcs snapshot repositories with the same names as our previous ones but with different UUIDs, and the base_path that was supplied was ignored.  The resulting base path for the new snapshot repos was a newly created gcs bucket folder that we did not specify, named "monitoring-monitoring/snapshots" instead.  It then created the required substructure in those folders and began writing new snapshots to it.  

We didn't initially notice this issue since nothing appeared broken immediately, but when we implemented an ES version upgrade later that week, and the frozen nodes began to roll off, frozen shards were unable to reallocate to new nodes because the searchable_snapshot_repository's UUID didn't match what they had.  We confirmed this with the shard allocation explain API (logs for this posted in log section below).

Because we saw that the folder path created was "monitoring-monitoring/snapshots," we suspect that the name is derived from the name of the stackconfigpolicy object, the namespace, or something else, rather than what's passed into base_path.

**Environment**
prod

* ECK version:

	2.7.0

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* Cloud: GKE 
	* Kubernetes distribution: GKE
	

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.8-dispatcher", GitCommit:"283881f025da4f5b3cefb6cd4c35f2ee4c2a79b8", GitTreeState:"clean", BuildDate:"2021-09-14T05:14:54Z", GoVersion:"go1.15.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.10-gke.2300", GitCommit:"1d7ae0799b40b0cd95502e3a5e698db62572e341", GitTreeState:"clean", BuildDate:"2023-02-22T09:28:49Z", GoVersion:"go1.19.6 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```

* Resource definition:
```
apiVersion: stackconfigpolicy.k8s.elastic.co/v1alpha1
kind: StackConfigPolicy
metadata:
  name: monitoring
spec:
    snapshotRepositories:
      my_gcs_repository:
        type: gcs
        settings:
          bucket: my-bucket-infra-prod
          project_id: my-project-infra-prod
          base_path: es-snapshots/infra-prod
      searchable_snapshot_repository:
        type: gcs
        settings:
          bucket: my-bucket-infra-prod
          base_path: es-searchable/infra-prod
```

* Logs:
```
cluster allocation explain API results for unallocated frozen shards

 "explanation": "this index is backed by a searchable snapshot in a repository with UUID [qfoa5pP1T0Kx0K3JBW_0Xg] but no such repository is registered with this cluster; the required repository was originally named [searchable_snapshot_repository]


get snapshot repository API call results on bad repo, you can see different UUID:

{
    "searchable_snapshot_repository": {
        "type": "gcs",
        "uuid": "9hIUsXk2QR-kptwbzgFX9w",
        "settings": {
            "bucket": "my-bucket-infra-prod",
            "base_path": "snapshots/monitoring-monitoring"
        }
    }
}
```
