### ISSUE TITLE
Cannot downscale from 3 to 1 mdi nodes in v7.0.0

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#678]
How to reproduce:
1. deploy a 7.0.0 3-nodes cluster:
```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: sample
spec:
  version: 7.0.0
  nodes:
    - config:
        node.master: true
        node.data: true
        node.ingest: true
        xpack.license.self_generated.type: trial
      resources:
        limits:
          memory: 1Gi
          cpu: 1
      nodeCount: 3
```
2. wait for deployment to be complete
3. downscale to 1 node
```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: sample
spec:
  version: 7.0.0
  nodes:
    - config:
        node.master: true
        node.data: true
        node.ingest: true
        xpack.license.self_generated.type: trial
      resources:
        limits:
          memory: 1Gi
          cpu: 1
      nodeCount: 1
```
4. the operator logs the following and never deletes any pod:
```
2019-04-24T20:10:32.773Z        ERROR   kubebuilder.controller  Reconciler error        {"controller": "elasticsearch-controller", "request": "default/sample", "error": "unable to add to voting_config_exclusions: 400 Bad Request: add voting config exclusions request for [sample-es-n2f7njwjml,sample-es-mlmkvkchmx] matched no master-eligible nodes", "errorCauses": [{"error": "unable to add to voting_config_exclusions: 400 Bad Request: unknown", "errorVerbose": "400 Bad Request: unknown\nunable to add to voting_config_exclusions\ngithub.com/elastic/k8s-operators/operators/pkg/controller/elasticsearch/client.(*clientV7).AddVotingConfigExclusions\n\t/go/src/github.com/elastic/k8s-operators/operators/pkg/controller/elasticsearch/client/v7.go:41\ngithub.com/elastic/k8s-operators/operators/pkg/controller/elasticsearch/version/version7.UpdateZen2Settings\n\t/go/src/github.com/elastic/k8s-operators/operators/pkg/controller/elasticsearch/version/version7/zen2.go:47\ngithub.com/elastic/k8s-operators/operators/pkg/controller/elasticsearch/driver.(*defaultDriver).Reconcile\n\t/go/src/github.com/elastic/k8s-operators/operators/pkg/controller/elasticsearch/driver/default.go:360\ngithub.com/elastic/k8s-operators/operators/pkg/controller/elasticsearch.(*ReconcileElasticsearch).internalReconcile\n\t/go/src/github.com/elastic/k8s-operators/operators/pkg/controller/elasticsearch/elasticsearch_controller.go:279\ngithub.com/elastic/k8s-operators/operators/pkg/controller/elasticsearch.(*ReconcileElasticsearch).Reconcile\n\t/go/src/github.com/elastic/k8s-operators/operators/pkg/controller/elasticsearch/elasticsearch_controller.go:228\ngithub.com/elastic/k8s-operators/operators/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/elastic/k8s-operators/operators/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215\ngithub.com/elastic/k8s-operators/operators/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/elastic/k8s-operators/operators/vendor/sigs.k8s.io/controller-runtime/$kg/internal/controller/controller.go:158\ngithub.com/elastic/k8s-operators/operators/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/elastic/k8s-operators/operators/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/elastic/k8s-operators/operators/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/elastic/k8s-operators/operators/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/elastic/k8s-operators/operators/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/elastic/k8s-operators/operators/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1333"}]}
```

Downscaling from 3 to 2 nodes seems to work fine.
