### ISSUE TITLE
Renaming a nodeSet may allow forbidden changes in the volumeClaimTemplates

### ISSUE THREAD

**Issue by barkbay** [elastic/cloud-on-k8s#6796]
Assuming that:
1.  A `nodeSet` with an initial `spec1` exists
2. This `nodeSet` has both its name and its `volumeClaimTemplates` modified through a new specification `spec2`
3. The name is reverted back to its previous value, **while the `StatefulSet` of `spec1` still exists**.

➡️  Then the operator might be stuck trying to apply a `StatefulSet` with a `volumeClaimTemplates` of the intermediate specification `spec2` because that `volumeClaimTemplates` may hold a different settings (between `spec1` and `spec2`) that cannot be changed.

The error observed in the logs is the following:

```
updates to statefulset spec for fields other than ‘replicas’, ‘template’, and ‘updateStrategy’ are forbidden
```

Here are a few examples to reproduce the issue:

### 1. `spec1` - Initial `nodeSet`
```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
spec:
  version: 8.7.0
  nodeSets:
  - name: default
    config:
      # this allows ES to run on nodes even if their vm.max_map_count has not been increased, at a performance cost
      node.store.allow_mmap: false
    count: 3
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: standard
```

### 2. `spec2` - Rename the nodeSet with a new `storageClassName` 

```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
spec:
  version: 8.7.0
  nodeSets:
  - name: default-new
    config:
      # this allows ES to run on nodes even if their vm.max_map_count has not been increased, at a performance cost
      node.store.allow_mmap: false
    count: 3
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: invalid
```

### 3.  `spec3` - Revert the `nodeSet` name back to the original before the last update is successful 💥 

```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
spec:
  version: 8.7.0
  nodeSets:
  - name: default
    config:
      # this allows ES to run on nodes even if their vm.max_map_count has not been increased, at a performance cost
      node.store.allow_mmap: false
    count: 3
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: invalid
```

Note that we do have a validation [here](https://github.com/elastic/cloud-on-k8s/blob/ad886c9914a1c19312641b79b6ab39924948933a/pkg/controller/elasticsearch/validation/volume_validation.go#L107-L118) to detect this kind of change, but the "renaming" makes it ineffective as only existing `nodeSets` are taken into account.

```golang
	for i, proposedNodeSet := range proposed.Spec.NodeSets {
		currentNodeSet := getNodeSet(proposedNodeSet.Name, current)
		if currentNodeSet == nil {
			// initial creation
			continue
		}

		// Check that no modification was made to the claims, except on storage requests.
		if !apiequality.Semantic.DeepEqual(
			claimsWithoutStorageReq(currentNodeSet.VolumeClaimTemplates),
			claimsWithoutStorageReq(proposedNodeSet.VolumeClaimTemplates),
		) {
			errs = append(errs, field.Invalid(
				field.NewPath("spec").Child("nodeSet").Index(i).Child("volumeClaimTemplates"),
				proposedNodeSet.VolumeClaimTemplates,
				pvcImmutableErrMsg,
			))
			continue
		}
```
