### ISSUE TITLE
Unable to disable podDisruptionBudget

### ISSUE THREAD

**Issue by ccaillet1974** [elastic/cloud-on-k8s#6871]
## Bug Report
**What did you do?**
I want to disable the podDisruptionBudget by setting podDisruptionBudget with an empty hash

**What did you expect to see?**
I should have the following directive in the result of helm chart

```
eck-elasticksearch:
  ...
  podDisruptionBudget: {}
```

**What did you see instead? Under which circumstances?**
directive podDisruptionBudget is absent from the manifest generated by the Helm

**Environment**

* ECK version:

	2.8.0

* Kubernetes information:
	* On premise : deployed with kubespray 2.21.0
	
	for each of them please give us the version you are using
```
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.6", GitCommit:"b39bf148cd654599a52e867485c02c4f9d28b312", GitTreeState:"clean", BuildDate:"2022-09-21T13:19:24Z", GoVersion:"go1.18.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.6", GitCommit:"ff2c119726cc1f8926fb0585c74b25921e866a28", GitTreeState:"clean", BuildDate:"2023-01-18T19:15:26Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Resource definition:
```
eck-elasticsearch:
  enabled: true
  fullnameOverride: "sophie-mon"
  version: 8.7.0
  monitoring:
    metrics:
      elasticsearchRefs:
      - name: sophie-mon
        namespace: cdn-bigdata
    logs:
      elasticsearchRefs:
      - name: sophie-mon
        namespace: cdn-bigdata
  nodeSets:
  - name: "nodes"
    count: 3
    config:
      # No need to define specific role on nodes
      node.roles: ["master","data","ingest","transform","ml","remote_cluster_client"]
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms8g -Xmx8g
          resources:
            limits:
              cpu: 8
              memory: 12Gi
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 200Gi
        storageClassName: lyo0-oc9k-nfs
  podDisruptionBudget: {}
```

* Logs:
```
No error
```

I could also check this by generating the global manifest with helm template command and my values file.

As a workaround I do an ugly hack by defining a value disablePdb on value file with true value

and the following code on template for eck-elasticsearch
```
{{- if .Values.disablePdb }}
  podDisruptionBudget: {}
  {{- else }}
  {{- with .Values.podDisruptionBudget }}
  podDisruptionBudget:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
```

Thanks by advance for your replies.

--
Regards
Christophe
