### ISSUE TITLE
Setting custom Resource requests and limits via podTemplate fails to create kibana

### ISSUE THREAD

**Issue by fritz-net** [elastic/cloud-on-k8s#6886]
## Bug Report
**What did you do?**
I created a kibana resource with custom resource requests and limits (since the defaults are way to high for single user test setup):
```
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: {{ .Values.elastic.name }}
spec:
  version: {{ .Values.elastic.version }}
  count: 1
  elasticsearchRef:
    name: {{ .Values.elastic.name }}
  podTemplate: # https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-managing-compute-resources.html#k8s-compute-resources-kibana-and-apm
    spec:
      containers:
      - resources:
          requests:
            cpu: null
            memory: 256Mi
          limits:
            cpu: null
            memory: 256Mi
        # name: null
        # image: null # also overrides image of test sidecar
        # name: kibana-server
```

values.yaml
```
elastic:
  name: elastic
  version: 8.7.0
```

**What did you expect to see?**
Kibana starting up normaly
Guide from https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-managing-compute-resources.html#k8s-compute-resources-kibana-and-apm giving working example

(for elasticsearch and apm it seems to work this way)

**What did you see instead? Under which circumstances?**
If I just set ressources like in the template given above it fails cause of missing image and name. I tried leaving them out and setting them to null.
```
Reconciliation error: Deployment.apps "elastic-kb" is invalid: [spec.template.spec.containers[0].name: Required value, spec.template.spec.containers[0].image: Required value]
```

If I set the name on the template like described [here](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-managing-compute-resources.html#k8s-compute-resources-kibana-and-apm) I get an error that the image is missing
```
Reconciliation error: Deployment.apps "elastic-kb" is invalid: spec.template.spec.containers[0].image: Required value
```

if also set the image it overwrites the image for the test sidecar but not for the main image. The test container then fails

**Environment**

* ECK version:
installed via helm
docker.elastic.co/eck/eck-operator:2.8.0

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* On premise: Ubuntu 20.04.6 LTS
	* Kubernetes: installed via kubeadm v1.27.2
	
```
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:20:07Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"windows/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:13:28Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}
```
