### ISSUE TITLE
Enabled by default SSL for Logstash API

### ISSUE THREAD

**Issue by thbkrkr** [elastic/cloud-on-k8s#6971]
We should enabled by default SSL for Logstash API and make it possible to configure it through `spec.http` like it's possible for other stack apps (see [k8s-tls-certificates doc](https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-tls-certificates.html)).

```yaml
spec:
  http:
  
    service:
      spec:
        type: LoadBalancer
    
    tls:  
      selfSignedCertificate:
        disabled: true

      selfSignedCertificate:
        subjectAltNames:
          - ip: 160.46.176.15
          - dns: hulk.example.com
      
      certificate:
        secretName: my-cert
```

There is currently a TODO related to this:

https://github.com/elastic/cloud-on-k8s/blob/3a2ce8d4a2ca64c915b56e0b2e73ad0bc68e6eea/pkg/controller/logstash/pod.go#L104-L110
