### ISSUE TITLE
TestVersionUpgradeAndRespecToLatest is failing

### ISSUE THREAD

**Issue by thbkrkr** [elastic/cloud-on-k8s#7013]
[cloud-on-k8s-operator-nightly/builds/237](https://buildkite.com/elastic/cloud-on-k8s-operator-nightly/builds/237#018948f4-34bd-4c05-904a-270038163182)

- 🐞 `TestVersionUpgradeAndRespecToLatest8x` stack-8-10-0-sna
- 🐞 `TestVersionUpgradeAndRespecToLatest7x` stack-7-16-3

```scala
TestVersionUpgradeAndRespecToLatest8x/ES_endpoint_should_eventually_be_reachable
error: cluster health is not green, but yellow

TestVersionUpgradeAndRespecToLatest7x/Kibana_Pods_should_eventually_be_ready#01
error: pod not ready yet
```

In TestVersionUpgradeAndRespecToLatest8x, ES is created with 1 node.
https://github.com/elastic/cloud-on-k8s/blob/2e369fc428ab366e67d1a98f12b3c13983a9347e/test/e2e/kb/version_upgrade_test.go#L184

Looking at the diagnostics, in each test, the 1 node ES cluster has an index with 1 primary, 1 replica UNASSIGNED:
```sh
# test-upgrade-and-respec-to-7x-pk7r
index: yellow open   .kibana_7.17.8_reindex_temp      iLkXeJDdQo21NBTjLJeH1g 1 1 0 0 226b 226b false
shard: .kibana_7.17.8_reindex_temp                                   0     r      UNASSIGNED                             

# test-upgrade-and-respec-to-8x-kbf2
index: yellow open   .fleet-file-data-agent-000001    E6L5TwNFRWCQrRevPR-ZWA 1 1 0 0 248b 248b false
index: yellow open   .fleet-files-agent-000001        HKPPEX-lSm6ZEMpBkNvUzg  1 1 0 0 248b 248b false
.fleet-file-data-agent-000001                                 0     r      UNASSIGNED
.fleet-files-agent-000001  
```

Not sure if this is the mapping behind `.fleet-file-data-agent-000001`, but I see `auto_expand_replicas: 0-1` for `.fleet-fileds-fromhost-meta`.

Could it be that the index was created at a time when there were 2 nodes, in the middle of the upgrade?

**Comment by thbkrkr** [comment]
The issue isn't related to the upgrade.
It can be reproduced simply by deploying a 1-node ES cluster in `8.10.0-SNAPSHOT` with Kibana in `8.8.0`.

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: yo
spec:
  version: 8.10.0-SNAPSHOT
  nodeSets:
  - name: "n"
    count: 1
    config:
      node.store.allow_mmap: false
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: yo
spec:
  version: 8.8.0
  count: 1
  elasticsearchRef:
    name: yo
```

After a few seconds, the cluster is `yellow` because of unassigned `fleet-files-agent-000001` and `fleet-file-data-agent-000001` shards.

```
> k get es
NAME   HEALTH   NODES   VERSION           PHASE   AGE
yo     yellow   1       8.10.0-SNAPSHOT   Ready   5m24s

> eckurl default yo /_cat/shards | grep UNAS
.fleet-files-agent-000001                                     0 r UNASSIGNED
.fleet-file-data-agent-000001                                 0 r UNASSIGNED
```
