### ISSUE TITLE
Improve Logstash keystore command performance

### ISSUE THREAD

**Issue by kaisecheng** [elastic/cloud-on-k8s#7027]
Logstash keystore init container slows down the startup process. To update the keystore, `logstash-keystore` command starts and stops jvm for each key. The process is proportion to the number of keys. In the local env, adding 10 keys takes six minutes to get Logstash ready.

Logstash keystore command should allow adding keys in a batch.

**Config to reproduce the issue** 

```yml
apiVersion: v1
kind: Secret
metadata:
  name: logstash-secure-settings
stringData:
  A: a
  B: b
  C: c
  D: d
  E: e
  F: f
  G: g
  H: h
  I: i
  J: j
---
apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: logstash-sample
spec:
  version: 8.8.0
  count: 1
  pipelines:
    - pipeline.id: main
      config.string: |-
        input { exec { command => 'uptime' interval => 10 } }
        filter {
          if ("${HELLO:}" != "") {
            mutate { add_tag => ["awesome"] }
          }
        }
  secureSettings:
    - secretName: logstash-secure-settings
```

relates: https://github.com/elastic/logstash/issues/15186
