### ISSUE TITLE
Create a CRD ElasticBeat PodMonitor to copy prometheus PodMonitor concept

### ISSUE THREAD

**Issue by ebuildy** [elastic/cloud-on-k8s#7100]
## Proposal

**Use case. Why is this important?**

We use a lot of PodMonitor objects to scrap metrics from prometheus. The little CRD allow to tell to prometheus operator: "add a new scrap to this pod / service", in a few lines we got metrics on prometheus, pretty cool.

Today, as a big fan of elastic stack, I have decided to give a try to https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-prometheus.html, this work like a charm !!! But quite complicate to setup.

So, what about to create a new CRD:

```
apiVersion: beat.k8s.elastic.co/v1beta1
kind: PodMonitor
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
  podMetricsEndpoints:
  - port: metrics
```

to configure an elastic beat instance to scrap this "prometheus format" endpoint?

(also copy PrometheusRule to manage elastic alerts will be awesome ^^)
