### ISSUE TITLE
403 - assigned roles [all,manage,monitor] were not found, but users_roles claim the user has them assigned. 

### ISSUE THREAD

**Issue by maxkokocom** [elastic/cloud-on-k8s#7148]
## Bug Report
**What did you do?**

Created a role with realm options in order to allow aggregator to push logs

**What did you expect to see?**
Auth logs and logs being pushed

**What did you see instead? Under which circumstances?**
```bash
2023-09-01 20:09:53 +0000 [warn]: #0 [ClusterFluentdConfig-cluster-cluster-fluentd-config::cluster::clusteroutput::cluster-fluentd-output-es-0] Could not communicate to Elasticsearch, resetting connection and trying again. [403] {"error":{"root_cause":[{"type":"security_exception","reason":"action [cluster:monitor/main] is unauthorized for user [fluent] with effective roles [] (assigned roles [all,manage,monitor] were not found), this action is granted by the cluster privileges [monitor,manage,all]"}],"type":"security_exception","reason":"action [cluster:monitor/main] is unauthorized for user [fluent] with effective roles [] (assigned roles [all,manage,monitor] were not found), this action is granted by the cluster privileges [monitor,manage,all]"},"status":403}
```

but when I run `k exec elasticsearch-es-default-0 -n logging -c elasticsearch -- cat config/users_roles`
the role `fluent` has all listed permissions, I even gave it superuser temporary

```bash
all:fluent
elastic-internal_cluster_manage:elastic-internal-pre-stop
elastic_internal_probe_user:elastic-internal-probe
manage:fluent
monitor:fluent
remote_monitoring_collector:elastic-internal-monitoring
superuser:elastic,elastic-internal,fluent
```

**Environment**

* ECK version:

	docker.elastic.co/eck/eck-operator:2.9.0

* Kubernetes information:

	EKS - v1.24.16

* Resource definition:
```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: logging
spec:
  version: 8.9.0
  auth:
    fileRealm:
    - secretName: fluentd-elastic-user
  secureSettings:
  - secretName: elastic-logs-iam-creds
```

^It does seem to create users and roles properly, secrets are also correct checked it inside fluent container. 

When running `curl -X GET "http://localhost:9200" -u fluent:XXX` I am getting a valid response as well.

**Comment by rhr323** [comment]
Hey @maxkokocom, thanks for reporting this issue. Could you try running `bin/elasticsearch-users  list` on an Elasticsearch node to see if users + roles are applied as expected?

**Comment by rhr323** [comment]
We also have documentation on the topic you might find useful: 
https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-users-and-roles.html#k8s_creating_custom_roles.

**Comment by oshmyrko** [comment]
@maxkokocom @rhr323 

I had exact same issue:
```
[2025/01/21 13:58:43] [error] [output:es:es.0] HTTP status=403 URI=/_bulk, response:
{"error":{"root_cause":[{"type":"security_exception","reason":"action [indices:data/write/bulk] is unauthorized for user [anonymous_user] with effective roles [] (assigned roles [monitoring,writer] were not found), this action is granted by the index privileges [create_doc,create,delete,index,write,all]"}],"type":"security_exception","reason":"action [indices:data/write/bulk] is unauthorized for user [anonymous_user] with effective roles [] (assigned roles [monitoring,writer] were not found), this action is granted by the index privileges [create_doc,create,delete,index,write,all]"},"status":403}
```

missing quotes around role names caused the issue:
```yaml
  - name: data
    count: 1
    config:
      node.roles: ['master', 'data', 'ingest']
      xpack.security.authc:
        anonymous:
          username: anonymous_user
          # This does not work without quotes (assigned roles [monitoring,writer] were not found)
          #roles: [writer, monitoring]     <---------- the root cause is the absence of quotes around roles
          # You should use quotes here
          roles: ['writer', 'monitoring']
```
