### ISSUE TITLE
ECK Operator 2.6.1 failing to upgrade ES from 7.17.10 to 8.9.1 due to invalid setting which is actually valid

### ISSUE THREAD

**Issue by gustavosci** [elastic/cloud-on-k8s#7173]
## Bug Report
**What did you do?**
Tried to upgrade an ES cluster from v7.17.10 to v8.9.1 using eck-operator v2.6.1 with setting `thread_pool.write.size` defined in  `elasticsearch.yaml`.

**What did you expect to see?**
Successful ES upgrade and write thread pool size with the correct size.

**What did you see instead? Under which circumstances?**
Error to upgrade the cluster (please see logs). The operator does not allow proceeding with the upgrade with the setting `thread_pool.write.size` defined in the `elasticsearch.yaml`.

**Environment**

* ECK version: 

	2.6.1

* Kubernetes information:

	* Version: v1.23.17-eks-2d98532
	* Cloud: EKS
	
* Logs:
```
{
  "log.level": "error",
  "@timestamp": "2023-09-19T11:07:02.716Z",
  "log.logger": "manager.eck-operator",
  "message": "Reconciler error",
  "service.version": "2.6.1+62f2e278",
  "service.type": "eck",
  "ecs.version": "1.4.0",
  "controller": "elasticsearch-controller",
  "object": {
    "name": "es",
    "namespace": "perf-04"
  },
  "namespace": "perf-04",
  "name": "es",
  "reconcileID": "be7acb4e-2873-4b7e-a7b4-91a6d77e895c",
  "error": "elasticsearch client failed for http://es-es-internal-http.perf-04.svc:9200/_internal/desired_nodes/96095ac8-af0b-46bb-81b3-66614f9489a4/10: 400 Bad Request: {Status:400 Error:{CausedBy:{Reason: Type:} Reason:Nodes with ids [es-es-data-1-0,es-es-data-2-0,es-es-data-3-0] in positions [3,4,5] contain invalid settings Type:illegal_argument_exception StackTrace: RootCause:[{Reason:Nodes with ids [es-es-data-1-0,es-es-data-2-0,es-es-data-3-0] in positions [3,4,5] contain invalid settings Type:illegal_argument_exception}]}}",
  "errorCauses": [
    {
      "error": "elasticsearch client failed for http://es-es-internal-http.perf-04.svc:9200/_internal/desired_nodes/96095ac8-af0b-46bb-81b3-66614f9489a4/10: 400 Bad Request: {Status:400 Error:{CausedBy:{Reason: Type:} Reason:Nodes with ids [es-es-data-1-0,es-es-data-2-0,es-es-data-3-0] in positions [3,4,5] contain invalid settings Type:illegal_argument_exception StackTrace: RootCause:[{Reason:Nodes with ids [es-es-data-1-0,es-es-data-2-0,es-es-data-3-0] in positions [3,4,5] contain invalid settings Type:illegal_argument_exception}]}}"
    }
  ],
  "error.stack_trace": "sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:326\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:234"
}
```

**Comment by barkbay** [comment]
How do know that the problem comes from `thread_pool.write.size`? I'm asking because other issues are known to generate the same error: https://github.com/elastic/elasticsearch/pull/96138 I want to double check that it is a new one.

**Comment by gustavosci** [comment]
Hi @barkbay 
Once we remove this setting from the yaml, the cluster is created without issues. That's why we suspect of this setting.
Please let me know if you want more information about our configs.

**Comment by pebrc** [comment]
I tried to reproduce this error with the following manifest and ES upgraded without problems:

```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
spec:
  version: 7.17.10 # then changed to 8.9.1
  nodeSets:
  - name: default
    config:
      thread_pool.write.size: 10
      node.roles: ["master", "data", "ingest", "ml"]
      # this allows ES to run on nodes even if their vm.max_map_count has not been increased, at a performance cost
      node.store.allow_mmap: false
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: 4Gi
              cpu: 1
    count: 3
```
