### ISSUE TITLE
Deploying Kibana with a Loadbalancer service type using the AWS Load Balancer Controller add-on seem to have some race condition

### ISSUE THREAD

**Issue by psypuff** [elastic/cloud-on-k8s#7198]
## Bug Report
**What did you do?**
Deployed the `eck_stack` Helm chart using the attached `values.yaml` in order to have an AWS LB pointing at the Kibana pod.

**What did you expect to see?**
Browsing to the LB endpoint should have resulted with the Kibana login page.

**What did you see instead? Under which circumstances?**
Both Helm charts are installed successfully (including a successful creation of the LB) but the LB health check fails so it responds with an empty response. Kibana is accessible when forwarding the pod's port so it feels like something with the Service/Endpoint is wrong.
When omitting the LB config at first, letting Helm create the pods with a ClusterIP and only then updating the `values.yaml` with the LB config and applying again - it works. Same config, couldn't find any difference with the K8s resources (apart from the random port ofc). Feels like some race condition between the ECK operator and the AWS LB one.
Another strange behavior with provisioning everything at once - after the Kibana pod goes up it seems there's some reconciliation mechanism that spins up another Kibana pod and kills the first one.

**Environment**
Provisioning both charts using the TF Helm provider (version 2.11.0) so `kubectl version` is less relevant. Waiting 1m between the `eck-operator` chart and the `eck-stack` chart installations to avoid race conditions.

* ECK version:
`eck-operator` chart - 2.9.0
`eck-stack` chart - 0.7.0

* Kubernetes information:
EKS 1.22

* Resource definition (`values.yaml`):
```
eck-elasticsearch:
  enabled: true
  version: 8.10.2

eck-kibana:
  enabled: true
  version: 8.10.2
  spec:
    http:
      service:
        metadata:
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-backend-protocol: ssl
            service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm...
        spec:
          type: LoadBalancer
          ports:
            - port: 443
```

**Comment by pebrc** [comment]
Not a bug in the operator. But potentially room for improvement in our docs cc @eedugon 

AI-generated summary below:


**The issue is a port mismatch caused by incomplete port configuration.**

When users specify custom ports in their `values.yaml`:

```yaml
eck-kibana:
  spec:
    http:
      service:
        spec:
          type: LoadBalancer
          ports:
            - port: 443  # ❌ Missing targetPort!
```

### What Goes Wrong:

1. Kibana **always** listens on port `5601` (hardcoded in `pkg/controller/kibana/network/ports.go`)
2. The user specifies `port: 443` for the LoadBalancer's external port
3. The user **omits** `targetPort` 
4. Kubernetes defaults `targetPort` to match `port` value (443)
5. The service tries to route traffic to port `443` on the pods
6. **But Kibana is listening on port `5601`, not `443`**
7. Result: Health checks fail, connections fail

### Why the Workaround Works:

When deploying as ClusterIP first, then updating to LoadBalancer, the workaround succeeds due to the **ECK operator's service reconciliation logic** (not Kubernetes behavior).

**Evidence from code:** `pkg/controller/common/service_control.go` (lines 119-129)

The `applyServerSideValues` function intentionally preserves `targetPort` from the existing service when:
1. The number of ports remains the same (`len(expected.Spec.Ports) == len(reconciled.Spec.Ports)`)
2. The new configuration doesn't specify `targetPort` (`expected.Spec.Ports[i].TargetPort.IntValue() == 0`)

```go
if len(expected.Spec.Ports) == len(reconciled.Spec.Ports) {
    for i := range expected.Spec.Ports {
        if expected.Spec.Ports[i].TargetPort.IntValue() == 0 {
            expected.Spec.Ports[i].TargetPort = reconciled.Spec.Ports[i].TargetPort  // Preserves existing targetPort!
        }
    }
}
```

**The flow:**
1. Initial ClusterIP deployment: ECK sets defaults → `port: 5601, targetPort: 5601`
2. User updates values.yaml: Changes to `type: LoadBalancer, port: 443` (no targetPort specified)
3. ECK reconciliation: Sees targetPort unset, **copies existing `targetPort: 5601`**
4. Result: Service has `port: 443, targetPort: 5601` ✅ (correct!)

**Why this only works as a workaround:**
- ✅ Works when **updating** an existing service
- ❌ Fails on **fresh deployments** (no existing service to copy from)
- ❌ Breaks if port count changes (condition on line 119 fails)
- ❌ Breaks if service is deleted and recreated
- ⚠️ Relies on implicit behavior, not explicit configuration

## The Fix

Users must explicitly specify `targetPort`:

```yaml
eck-kibana:
  spec:
    http:
      service:
        spec:
          type: LoadBalancer
          ports:
            - port: 443              # External LoadBalancer port
              targetPort: 5601        # ✅ Kibana's actual port - REQUIRED!
              protocol: TCP
              name: https
```
