### ISSUE TITLE
setting config for ApmServer (apm.k8s.elastic.co/v1)

### ISSUE THREAD

**Issue by 3rfun0** [elastic/cloud-on-k8s#7236]
I am trying to set index replica and ilm policy for apm server indices with configuration bellow although the changes applied in file config/config-secret/apm-server.yml not take effect either in apm-server.yml nor ilm in index management on kibana.
```
spec:
  version: 8.9.1
  count: 1
  config:
    setup:
      dashboards.enabled: true
      template:
        enabled: true
        name: "apm-server"
        index: "apm-"
        overwrite: true
      settings:
        index.number_of_shards: 1
        index.number_of_replicas: 0
    apm-server:
      ilm:
        enabled: true
        setup:
          enabled: true
          overwrite: true
          require_policy: true
        mapping:
          - event_type: "error"
            policy_name: "apm-rollover-30-days"
            index_suffix: "apm-"
          - event_type: "span"
            policy_name: "apm-rollover-30-days"
            index_suffix: "apm-"
          - event_type: "transaction"
            policy_name: "apm-rollover-30-days"
            index_suffix: "apm-"
          - event_type: "metric"
            policy_name: "apm-rollover-30-days"
            index_suffix: "apm-"
      policies:
        - name: "apm-rollover-30-days"
          policy:
            phases:
              hot:
                actions:
                  rollover:
                    max_age: "1d"
              delete:
                action:
                  delete:
                    min_age: "30d"
                    index: "apm-"
    default_service_environment: "staging"
    rum:
      enabled: true  
    kibana:
      enabled: true     
    apm-server.ssl:
      enabled: false       
    apm-server.instrumentation:
      enabled: true
      environment: staging     
  elasticsearchRef:
    name: elasticsearch-apm
    namespace: stage-orbis-apm
  kibanaRef:
    name: kibana-apm
    namespace: stage-orbis-apm  

```

* ECK version: eck-operator:2.9.0

* Kubernetes information:
	* On premise (kubespray - v1.26.5)
