### ISSUE TITLE
Issue when Kubernetes Secret is created using Vault Secrets Operator

### ISSUE THREAD

**Issue by rgarcia89** [elastic/cloud-on-k8s#7261]
## Bug Report
**What did you do?**
When using the shortly released Vault Secrets Operator (VSO) to consume Vault secrets natively from Kubernetes Secrets, the VSO adds one additional key `_raw` to the Kubernetes Secret. Within this VSO stores the whole secret information in JSON format. Please find below an example:

```yaml
apiVersion: v1
data:
  _raw: {"data":{"fleetUrl":"https://es-fleet-lab","kibanaUrl":"https://kibana-lab"},"metadata":{"created_time":"2023-10-24T08:49:50.326180226Z","custom_metadata":null,"deletion_time":"","destroyed":false,"version":1}}
  fleetUrl: https://es-fleet-lab
  kibanaUrl: https://kibana-lab
kind: Secret
...
```

This unfortunately leads to an issues in the ECK operator since it is trying to import these values into the keystore and afterwards fail due to not knowing the variable. Next to this the Kubernetes Secret including the license is also not being consumed anymore, as the operator complains about an additional data field, which is not allowed for this secret.

We therefore had to stop the migration to VSO for Elastic resources.

**What did you expect to see?**
I would expect the ECK operator to throw a warning about an unknown field but not to fail.

**What did you see instead? Under which circumstances?**
Log from a elasticsearch node pod:
```
"log.level":"ERROR", "message":"fatal exception while booting Elasticsearch", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.elasticsearch.bootstrap.Elasticsearch","elasticsearch.node.name":"elastic-es-masterdata-2","elasticsearch.cluster.name":"elastic","error.type":"java.lang.IllegalArgumentException","error.message":"unknown secure setting [_raw]
```

**Environment**

* ECK version:

	2.9.0

* Kubernetes information:

	Cloud: AKS
```
$ kubectl version 
1.26.6
```
```[tasklist]
### Tasks
```
