### ISSUE TITLE
Include all the metricsets to Metricbeat collected monitoring data

### ISSUE THREAD

**Issue by fdartayre** [elastic/cloud-on-k8s#7277]
When shipping metrics with [Stack monitoring](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-stack-monitoring.html), include all the [metricsets](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-elasticsearch.html#_metricsets_24) in the Elasticsearch module of Metricbeat.

Today only a [subset](https://github.com/elastic/cloud-on-k8s/blob/2.10/config/recipes/beats/stack_monitoring.yaml#L25-L34) is configured. As a result, the ingest pipelines view in Stack monitoring is empty for example.

**Comment by gui-elastic** [comment]
Hello,

I have a question. Should this be considered a bug or an enhancement request? I am asking that because this problem really impacts any attempt to monitor Ingest Pipeline if you use an ECK cluster monitored using the [ECK Stack Monitoring](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-stack-monitoring.html).

The workaround I found for this situation was to configure custom args for the Metricbeat container by following the steps described [here](https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s_override_the_beats_pod_template.html).

The final workaround would be as in the example below:

```
    podTemplate:
      spec:
        containers:
        - name: metricbeat
          args: 
          - "-c"
          - "/etc/metricbeat-config/metricbeat.yml"
          - "-E" 
          - "metricbeat.modules=[{module: elasticsearch, metricsets: ['node', 'node_stats', 'ccr', 'cluster_stats', 'enrich', 'index', 'index_recovery', 'index_summary', 'ml_job', 'shard', 'ingest_pipeline']}]"
          - "-e"
```
