### ISSUE TITLE
Enable ECK Fleet Server to run as non-root

### ISSUE THREAD

**Issue by GeorgeGkinis** [elastic/cloud-on-k8s#7303]
## Proposal

**Enable ECK Fleet Server to run as non-root**

The agents can now run as non-root when the installed integrations do not need root.
For the APM Server and Fleet we do not need persistence right?

In the case of K8s logs we do need persistence and root access to the logs.
We are allowed to run daemonsets as root, because daemonsets are managed by another team.

Fleet server and APM server are managed by a team that are not allowed to run as root.

Since Elasticsearch, Kibana and Agents can run non-root it would be great if the full set of ECK products can run non-root.
This should include on-prem package registry as well.

According to [documentation](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-elastic-agent-fleet-quickstart.html#CO18-1) root for Fleet is only needed for CA's:
"The root user is required to persist state in a hostPath volume and to **trust the Elasticsearch CA in Fleet mode**. See [Storing local state in host path volume](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-elastic-agent-configuration-examples.html#k8s_storing_local_state_in_host_path_volume) for options to not run the Agent container as root."

**Comment by GeorgeGkinis** [comment]
BTW it seems that the documentation is misleading.
We cannot run an APM server nor a simple agent as non-root.

ECK version: 2.10
Agent version: 8.11.0

Logs:
```
{"log.level":"info","@timestamp":"2023-11-09T12:48:54.812Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":479},"message":"Starting enrollment to URL: https://fleet-server-agent-http.obs-dev-elastic-stack.svc:8220/","ecs.version":"1.6.0"}
Error: fail to enroll: remove /usr/share/elastic-agent/state/data/state.enc: permission denied
For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.11/fleet-troubleshooting.html
Error: enrollment failed: exit status 1
For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.11/fleet-troubleshooting.html

Process finished with exit code 0
```

agent.yml:
```
---
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata: 
  name: elastic
spec:
  version: {{ .Env.ELASTIC_VERSION }}
  image: {{ .Env.ELASTIC_AGENT_IMAGE }}
  kibanaRef:
    name: kibana
  fleetServerRef: 
    name: fleet-server
  policyID: eck-agent
  mode: fleet
  deployment:
    replicas: 1
    podTemplate:
      spec:
#        securityContext:
#          fsGroup: 1000
#        volumes:
#          - name: agent-data
#            emptyDir: {}
        containers:
          - name: agent
            image: {{ .Env.ELASTIC_AGENT_IMAGE }}
            resources:
              requests:
                memory: 250Mi
                cpu: 30m
              limits:
                memory: 500Mi
                cpu: 50m
---
apiVersion: v1
kind: Service
metadata:
  name: elastic-agent-http
spec:
  selector:
    agent.k8s.elastic.co/name: elastic
  ports:
  - protocol: TCP
    port: 8200
    targetPort: 8200

```

**Comment by barkbay** [comment]
I applied the following manifest and it is working as expected:

```yaml
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: fleet-server-quickstart
  namespace: obs-dev-elastic-stack
spec:
  version: 8.11.1
  kibanaRef:
    name: kibana-quickstart
  elasticsearchRefs:
    - name: elasticsearch-quickstart
  mode: fleet
  fleetServerEnabled: true
  policyID: eck-fleet-server
  deployment:
    replicas: 1
    podTemplate:
      spec:
        securityContext:
          fsGroup: 1000
        volumes:
          - name: agent-data
            emptyDir: {}
        serviceAccountName: elastic-agent
        automountServiceAccountToken: true
```

```
> k exec pod/fleet-server-quickstart-agent-7c7f8d7754-tcnxv -- id
uid=1000(elastic-agent) gid=1000(elastic-agent) groups=1000(elastic-agent),0(root)
```

(full manifest [here](https://gist.github.com/barkbay/fed35562c5884f9760ff23cb769c2a72))


> Pod description:
> ```yaml
>  volumes:
>  - hostPath:
>      path: /var/lib/elastic-agent/obs-dev-elastic-stack/elastic/state
>      type: DirectoryOrCreate
>    name: agent-data
>```

This volume is not supposed to be created by the operator if it is already defined in the manifest. Could you double check that you applied to correct manifest and that there is nothing in the operator logs that would explain why the Pod is not reconciled.
