### ISSUE TITLE
Allow PVC annotations to be modified

### ISSUE THREAD

**Issue by sle78** [elastic/cloud-on-k8s#7310]
## Proposal

**Use case. Why is this important?**
My use case is Velero backups configuration controlled via PVC annotations

**What did you do?**
I tried to add some velero annotations to an existing nodeset's volumeclaim metadata:
```
        annotations:
          velero.io/exclude-from-backup: "true"
```

**What did you expect to see?**
PVC patched

**What did you see instead? Under which circumstances?**
`admission webhook "elastic-es-validation-v1.k8s.elastic.co" denied the request`

**Environment**

* ECK version:

    ECK 2.10.0 
    ELK 8.11.0

* Kubernetes information:

	* On premise 
```
$ kubectl version
Client Version: v1.28.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.7
```

* Initial Resource definition:
```
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.cluster.masters.storage }}
        storageClassName: mystorageclass
```

* Logs:
`admission webhook "elastic-es-validation-v1.k8s.elastic.co" denied the request`
