### ISSUE TITLE
cannot set ulimit -n 65536 in all ways

### ISSUE THREAD

**Issue by einsteinarbert** [elastic/cloud-on-k8s#7311]
## Proposal

**Java return ulimit 65536 but elastic still error**

## Bug Report
**What did you do?**
- I deploy eck on k8s with all setting below:
    + init container set sysctl -w vm.max_map_count=262144
    + config default containerd RLIMIT to 65536 in file `/etc/containerd/cri-base.json` - test ulimit -n with new container ok
    + mount some file into elastic image: `/etc/sysctl.conf`, `/etc/security/limits.conf`
    + create a test image and run your code java bootstrap check like this [code](https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/monitor/process/ProcessProbe.java):
And the result is ok (jdk8):
```java
root@ulimit-6754c9f7bc-rbwvx:/# ls
Main.java  bin  boot  dev  etc  home  lib  lib64  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
root@ulimit-6754c9f7bc-rbwvx:/# javac Main.java
root@ulimit-6754c9f7bc-rbwvx:/# java Main
sun.management.OperatingSystemImpl
6/65536
root@ulimit-6754c9f7bc-rbwvx:/# cat Main.java
import java.lang.management.ManagementFactory;
import java.lang.management.OperatingSystemMXBean;
import java.lang.reflect.Method;
public class Main
{
        public static void main(String [ ] args) {
        OperatingSystemMXBean osMxBean = ManagementFactory.getOperatingSystemMXBean();
        System.out.println(osMxBean.getClass().getName());
        try {
            Method getMaxFileDescriptorCountField = osMxBean.getClass().getDeclaredMethod("getMaxFileDescriptorCount");
            Method getOpenFileDescriptorCountField = osMxBean.getClass().getDeclaredMethod("getOpenFileDescriptorCount");
            getMaxFileDescriptorCountField.setAccessible(true);
            getOpenFileDescriptorCountField.setAccessible(true);
            System.out.println(getOpenFileDescriptorCountField.invoke(osMxBean) + "/" + getMaxFileDescriptorCountField.invoke(osMxBean));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```
 
**What did you expect to see?**
elastic pod run ok
**What did you see instead? Under which circumstances?**
Elastic pod loopback error with nofiles too low
**Environment**

* ECK version:

	[v2.9.0](https://github.com/elastic/cloud-on-k8s/releases/tag/v2.9.0)

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	**On premise**
```
$ kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.2
```

* Resource definition:
```yml
---
# cloud-on-k8s-2.9.0/deploy/eck-stack/charts/eck-elasticsearch/values.yaml
version: 8.9.0
nodeSets:
- name: default
  count: 1
  config:
    node.store.allow_mmap: false
    network.host: 0.0.0.0
  podTemplate:
    spec:
      volumes:
        - name: unlimit
          configMap:
            name: unlimit
            optional: false
        - name: sysctl
          configMap:
            name: sysctl
            optional: false
      initContainers:
        - command:
          - bash
          - "-c"
          - sysctl -w vm.max_map_count=262144
          name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
      containers:
      - name: elasticsearch
        securityContext:
          resources:
            limits:
              nofile: 65535
        lifecycle:
            postStart:
              exec:
                command: ["bash", "-c", "ulimit -n 65535"]
        volumeMounts:
          - name: unlimit
            mountPath: /etc/security/limits.conf
            subPath: limits.conf
          - name: sysctl
            mountPath: /etc/sysctl.conf
            subPath: sysctl.conf
        resources:
          limits:
            memory: 4Gi
          requests:
            memory: 2Gi
    volumes: ["elastic-pv"]
```
```yml
apiVersion: v1
kind: ConfigMap
# /etc/security/limits.conf
metadata:
  name: unlimit
  namespace: elastic-stack
  labels:
    app.kubernetes.io/managed-by: es-kb-quickstart
  annotations:
    app.kubernetes.io/managed-by: es-kb-quickstart
data:
  limits.conf: |
    *    soft nofile 65536
    *    hard nofile 65536
---
# /etc/sysctl.conf
apiVersion: v1
kind: ConfigMap
metadata:
  name: sysctl
  namespace: elastic-stack
  labels:
    app.kubernetes.io/managed-by: es-kb-quickstart
  annotations:
    app.kubernetes.io/managed-by: es-kb-quickstart
data:
  sysctl.conf: |
    fs.file-max = 9223372036854775807

```

* Logs:
```json
{
    "@timestamp": "2023-11-10T17:58:10.366Z",
    "log.level": "ERROR",
    "message": "node validation exception\n[1] bootstrap checks failed. You must address the points described in the following [1] lines before starting Elasticsearch.\nbootstrap check failure [1] of [1]: max file descriptors [4096] for elasticsearch process is too low, increase to at least [65535]",
    "ecs.version": "1.2.0",
    "service.name": "ES_ECS",
    "event.dataset": "elasticsearch.server",
    "process.thread.name": "main",
    "log.logger": "org.elasticsearch.bootstrap.Elasticsearch",
    "elasticsearch.node.name": "elasticsearch-es-default-0",
    "elasticsearch.cluster.name": "elasticsearch"
}
```

**Comment by barkbay** [comment]
>```yaml
>        lifecycle:
>            postStart:
>              exec:
>                command: ["bash", "-c", "ulimit -n 65535"]
>```

I _think_ this is useless, IIRC `ulimit` only applies to the current shell and its subprocesses.

```yaml
      - name: elasticsearch
        securityContext:
          resources:
            limits:
              nofile: 65535
```

I can't find any documentation about a resource named "nolimit".

> config default containerd RLIMIT to 65536 in file /etc/containerd/cri-base.json - test ulimit -n with new container ok

My understanding is that the limit should be driven by the container runtime.
Could you:
* Double check that the K8S `Node` on which the ES `Pod` is running has that new setting ⬆️ effectively applied.
* [Suspend](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-troubleshooting-methods.html#k8s-suspend-elasticsearch) the Elasticsearch Pod and check the limit?

**Comment by einsteinarbert** [comment]
> > ```yaml
> >        lifecycle:
> >            postStart:
> >              exec:
> >                command: ["bash", "-c", "ulimit -n 65535"]
> > ```
> 
> I _think_ this is useless, IIRC `ulimit` only applies to the current shell and its subprocesses.
> 
> ```yaml
>       - name: elasticsearch
>         securityContext:
>           resources:
>             limits:
>               nofile: 65535
> ```
> 
> I can't find any documentation about a resource named "nolimit".
> 
> > config default containerd RLIMIT to 65536 in file /etc/containerd/cri-base.json - test ulimit -n with new container ok
> 
> My understanding is that the limit should be driven by the container runtime. Could you:
> 
> * Double check that the K8S `Node` on which the ES `Pod` is running has that new setting ⬆️ effectively applied.
> * [Suspend](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-troubleshooting-methods.html#k8s-suspend-elasticsearch) the Elasticsearch Pod and check the limit?

Thanks for reply, I set all nodes with default RLIMIT to 65536, when in shell of Elastic, I ran `ulimit -n` as elasticsearch user and it showed `65536` but bootstrap failure, I also create Java file with your trunk of bootstrap checking code and it run fine. So I have no idea why your java code has been failure in this context !?

**Comment by barkbay** [comment]
Just to be sure I understand your setup:
* Could you remove the  volumes `sysctl` and `unlimit` as they should not be needed.
* Set `LimitNOFILE=infinity` in `/etc/systemd/system/containerd.service` and restart `containerd`
* Create a new Elasticsearch cluster or ensure existing Elasticsearch Pods are recreated (which was one of the reason I explicitly asked for using https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-troubleshooting-methods.html#k8s-suspend-elasticsearch )

**Comment by barkbay** [comment]
Closing due to inactivity, feel free to reopen if needed.

**Comment by manticorecao** [comment]
```yaml
...
      containers:
        - name: elasticsearch
          image: <es-image>
          securityContext:
            privileged: true
          command:
            - sh
            - -c
            - ulimit -n 655350 && <es cmd>
...
```
enter your container:
```shell
$ cat /proc/1/limits 
Limit                     Soft Limit           Hard Limit           Units     
Max cpu time              unlimited            unlimited            seconds   
Max file size             unlimited            unlimited            bytes     
Max data size             unlimited            unlimited            bytes     
Max stack size            8388608              unlimited            bytes     
Max core file size        unlimited            unlimited            bytes     
Max resident set          unlimited            unlimited            bytes     
Max processes             unlimited            unlimited            processes 
Max open files            655350               655350               files     
Max locked memory         unlimited            unlimited            bytes     
Max address space         unlimited            unlimited            bytes     
Max file locks            unlimited            unlimited            locks     
Max pending signals       513044               513044               signals   
Max msgqueue size         819200               819200               bytes     
Max nice priority         0                    0                    
Max realtime priority     0                    0                    
Max realtime timeout      unlimited            unlimited            us  
```
