### ISSUE TITLE
Non-existent secret key: elastic-internal-pre-stop

### ISSUE THREAD

**Issue by ElSamhaa** [elastic/cloud-on-k8s#7315]
## Bug Report
**What did you do?**
I've spun a single node eck cluster using the following configuration

**What did you expect to see?**
The eck instance/cluster should start successfully.

**What did you see instead? Under which circumstances?**
The elasticsearch pod is reporting this event and can't be started
```
MountVolume.SetUp failed for volume "elastic-internal-probe-user" : references non-existent secret key: elastic-internal-pre-stop
```

**Environment**

* ECK version: 2.9.0

* Kubernetes information:
  * On premise
  * Kubernetes distribution: Openshift 4.8 (Kubernetes v1.21.1)
  
```
$ oc version

Client Version: 4.14.1
Kustomize Version: v5.0.1
Kubernetes Version: v1.21.1+a620f50
```

* Resource definition:
```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch7
spec:
  auth: {}
  http:
    service:
      metadata:
        creationTimestamp: null
      spec: {}
    tls:
      certificate: {}
      selfSignedCertificate:
        disabled: true
  nodeSets:
  - config:
      node.data: true
      node.ingest: true
      node.master: true
      node.ml: false
      node.store.allow_mmap: false
      xpack.security.authc:
        anonymous:
          authz_exception: true
          roles: superuser
          username: anonymous
    count: 1
    name: default
    podTemplate:
      spec:
        containers:
        - env:
          - name: ES_JAVA_OPTS
            value: -Xms2g -Xmx2g
          name: elasticsearch
          resources:
            limits:
              cpu: 400m
              memory: 3Gi
            requests:
              cpu: 200m
              memory: 2304Mi
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 30Gi
        storageClassName: ocs-storagecluster-ceph-rbd
  podDisruptionBudget:
    metadata:
      creationTimestamp: null
    spec: {}
  transport:
    service:
      metadata:
        creationTimestamp: null
      spec: {}
    tls:
      certificate: {}
  updateStrategy:
    changeBudget: {}
  version: 7.17.11
```

* Logs:
The last event in the pod description:
```
Events:
  Type     Reason       Age   From               Message
  ----     ------       ----  ----               -------
  Normal   Scheduled    5s    default-scheduler  Successfully assigned redacted/elasticsearch7-es-default-0 to worker03.redacted
  Warning  FailedMount  5s    kubelet            MountVolume.SetUp failed for volume "elastic-internal-probe-user" : references non-existent secret key: elastic-internal-pre-stop
```
* Controller logs:
Very spammy, basically recurrences of the following:
```
{"log.level":"info","@timestamp":"2023-11-14T12:36:21.837Z","log.logger":"es-monitoring","message":"Ending reconciliation run","service.version":"2.9.0+f24ccc37","service.
type":"eck","ecs.version":"1.4.0","iteration":"384134","namespace":"redacted","es-mon_name":"elasticsearch7","took":0.000192213}
{"log.level":"info","@timestamp":"2023-11-14T12:36:21.857Z","log.logger":"remoteca-controller","message":"Starting reconciliation run","service.version":"2.9.0+f24ccc37","
service.type":"eck","ecs.version":"1.4.0","iteration":"383006","namespace":"redacted","es_name":"elasticsearch7"}
{"log.level":"info","@timestamp":"2023-11-14T12:36:21.857Z","log.logger":"remoteca-controller","message":"Ending reconciliation run","service.version":"2.9.0+f24ccc37","se
rvice.type":"eck","ecs.version":"1.4.0","iteration":"383006","namespace":"redacted","es_name":"elasticsearch7","took":0.000284948}
{"log.level":"info","@timestamp":"2023-11-14T12:36:21.923Z","log.logger":"elasticsearch-controller","message":"Updating resource","service.version":"2.9.0+f24ccc37","servi
ce.type":"eck","ecs.version":"1.4.0","iteration":"85378","namespace":"redacted","es_name":"elasticsearch7","kind":"Secret","namespace":"redacted","name":"ela
sticsearch7-es-internal-users"}
{"log.level":"info","@timestamp":"2023-11-14T12:36:21.930Z","log.logger":"remoteca-controller","message":"Starting reconciliation run","service.version":"2.9.0+f24ccc37","
service.type":"eck","ecs.version":"1.4.0","iteration":"383007","namespace":"redacted","es_name":"elasticsearch7"}
{"log.level":"info","@timestamp":"2023-11-14T12:36:21.931Z","log.logger":"remoteca-controller","message":"Ending reconciliation run","service.version":"2.9.0+f24ccc37","se
rvice.type":"eck","ecs.version":"1.4.0","iteration":"383007","namespace":"redacted","es_name":"elasticsearch7","took":0.000311782}
{"log.level":"info","@timestamp":"2023-11-14T12:36:21.931Z","log.logger":"es-monitoring","message":"Starting reconciliation run","service.version":"2.9.0+f24ccc37","servic
e.type":"eck","ecs.version":"1.4.0","iteration":"384135","namespace":"redacted","es-mon_name":"elasticsearch7"}
{"log.level":"info","@timestamp":"2023-11-14T12:36:21.931Z","log.logger":"es-monitoring","message":"Ending reconciliation run","service.version":"2.9.0+f24ccc37","service.
type":"eck","ecs.version":"1.4.0","iteration":"384135","namespace":"redacted","es-mon_name":"elasticsearch7","took":0.000112892}
{"log.level":"info","@timestamp":"2023-11-14T12:36:21.933Z","log.logger":"elasticsearch-controller","message":"Updating resource","service.version":"2.9.0+f24ccc37","servi
ce.type":"eck","ecs.version":"1.4.0","iteration":"85378","namespace":"redacted","es_name":"elasticsearch7","kind":"Secret","namespace":"redacted","name":"ela
sticsearch7-es-xpack-file-realm"}
{"log.level":"info","@timestamp":"2023-11-14T12:36:21.942Z","log.logger":"elasticsearch-controller","message":"Skipping pod because it has no IP yet","service.version":"2.
9.0+f24ccc37","service.type":"eck","ecs.version":"1.4.0","iteration":"85378","namespace":"redacted","es_name":"elasticsearch7","namespace":"redacted","pod_na
me":"elasticsearch7-es-default-0"}
{"log.level":"info","@timestamp":"2023-11-14T12:36:21.945Z","log.logger":"elasticsearch-controller","message":"Ending reconciliation run","service.version":"2.9.0+f24ccc37
","service.type":"eck","ecs.version":"1.4.0","iteration":"85378","namespace":"redacted","es_name":"elasticsearch7","took":0.150849241}
{"log.level":"info","@timestamp":"2023-11-14T12:36:21.945Z","log.logger":"elasticsearch-controller","message":"Starting reconciliation run","service.version":"2.9.0+f24ccc
37","service.type":"eck","ecs.version":"1.4.0","iteration":"85379","namespace":"redacted","es_name":"elasticsearch7"}
{"log.level":"info","@timestamp":"2023-11-14T12:36:21.949Z","log.logger":"elasticsearch-controller","message":"Updating resource","service.version":"2.9.0+f24ccc37","servi
ce.type":"eck","ecs.version":"1.4.0","iteration":"85379","namespace":"redacted","es_name":"elasticsearch7","kind":"ConfigMap","namespace":"redacted","name":"
elasticsearch7-es-scripts"}
{"log.level":"info","@timestamp":"2023-11-14T12:36:21.955Z","log.logger":"es-monitoring","message":"Starting reconciliation run","service.version":"2.9.0+f24ccc37","servic
e.type":"eck","ecs.version":"1.4.0","iteration":"384136","namespace":"redacted","es-mon_name":"elasticsearch7"}
{"log.level":"info","@timestamp":"2023-11-14T12:36:21.955Z","log.logger":"es-monitoring","message":"Ending reconciliation run","service.version":"2.9.0+f24ccc37","service.
type":"eck","ecs.version":"1.4.0","iteration":"384136","namespace":"redacted","es-mon_name":"elasticsearch7","took":0.000537597}
{"log.level":"info","@timestamp":"2023-11-14T12:36:21.957Z","log.logger":"remoteca-controller","message":"Starting reconciliation run","service.version":"2.9.0+f24ccc37","
service.type":"eck","ecs.version":"1.4.0","iteration":"383008","namespace":"redacted","es_name":"elasticsearch7"}
{"log.level":"info","@timestamp":"2023-11-14T12:36:21.958Z","log.logger":"remoteca-controller","message":"Ending reconciliation run","service.version":"2.9.0+f24ccc37","se
rvice.type":"eck","ecs.version":"1.4.0","iteration":"383008","namespace":"redacted","es_name":"elasticsearch7","took":0.000545798}
{"log.level":"info","@timestamp":"2023-11-14T12:36:21.961Z","log.logger":"remoteca-controller","message":"Starting reconciliation run","service.version":"2.9.0+f24ccc37","
service.type":"eck","ecs.version":"1.4.0","iteration":"383009","namespace":"redacted","es_name":"elasticsearch7"}
{"log.level":"info","@timestamp":"2023-11-14T12:36:21.961Z","log.logger":"es-monitoring","message":"Starting reconciliation run","service.version":"2.9.0+f24ccc37","servic
e.type":"eck","ecs.version":"1.4.0","iteration":"384137","namespace":"redacted","es-mon_name":"elasticsearch7"}
{"log.level":"info","@timestamp":"2023-11-14T12:36:21.962Z","log.logger":"remoteca-controller","message":"Ending reconciliation run","service.version":"2.9.0+f24ccc37","se
rvice.type":"eck","ecs.version":"1.4.0","iteration":"383009","namespace":"redacted","es_name":"elasticsearch7","took":0.000784393}
{"log.level":"info","@timestamp":"2023-11-14T12:36:21.962Z","log.logger":"remoteca-controller","message":"Starting reconciliation run","service.version":"2.9.0+f24ccc37","
service.type":"eck","ecs.version":"1.4.0","iteration":"383010","namespace":"redacted","es_name":"elasticsearch7"}
```

```bash
$ oc logs -f -n redacted elastic-operator-0 | jq -r '.message'

Updating resource
Starting reconciliation run
Ending reconciliation run
Starting reconciliation run
Ending reconciliation run
Starting reconciliation run
Ending reconciliation run
Updating resource
Starting reconciliation run
Ending reconciliation run
Starting reconciliation run
Ending reconciliation run
Starting reconciliation run
Ending reconciliation run
Starting reconciliation run
Ending reconciliation run
Skipping pod because it has no IP yet
Ending reconciliation run
Starting reconciliation run
Updating resource
Starting reconciliation run
Ending reconciliation run
Starting reconciliation run
Ending reconciliation run
Starting reconciliation run
Ending reconciliation run
Starting reconciliation run
Ending reconciliation run
Starting reconciliation run
Ending reconciliation run
Starting reconciliation run
Ending reconciliation run
Starting reconciliation run
Ending reconciliation run
Starting reconciliation run
Ending reconciliation run
Starting reconciliation run
Ending reconciliation run
Starting reconciliation run
Ending reconciliation run
Updating resource
Updating resource
Starting reconciliation run
Ending reconciliation run
Starting reconciliation run
Ending reconciliation run
Skipping pod because it has no IP yet
Ending reconciliation run
Starting reconciliation run
Updating resource
Starting reconciliation run
Starting reconciliation run
Ending reconciliation run
Starting reconciliation run
Ending reconciliation run
Ending reconciliation run
Starting reconciliation run
Ending reconciliation run
Starting reconciliation run
Ending reconciliation run
Starting reconciliation run
Ending reconciliation run
Updating resource
Updating resource
Starting reconciliation run
Ending reconciliation run
Starting reconciliation run
Ending reconciliation run
Skipping pod because it has no IP yet
Ending reconciliation run
Starting reconciliation run
Updating resource
Starting reconciliation run
Starting reconciliation run
Ending reconciliation run
Starting reconciliation run
Ending reconciliation run
Ending reconciliation run
Starting reconciliation run
Ending reconciliation run
Starting reconciliation run
```

**Comment by ElSamhaa** [comment]
Restarting the controller pod resolved the issue!

**Comment by barkbay** [comment]
I'm not able to reproduce, could you check if:

* If there is any log message in the operator logs with a reference to a `Secret` named `elasticsearch7-es-internal-users`, something like:

`TIMESTAMP    INFO    elasticsearch-controller        Creating resource       {"service.version": "0.0.0-SNAPSHOT+00000000", "iteration": "XX", "namespace": "default", "es_name": "elasticsearch7", "kind": "Secret", "namespace": "default", "name": "elasticsearch7-es-internal-users"}`

* If the aforementioned `Secret` does exist with the following keys:

```yaml
apiVersion: v1
kind: Secret
metadata:
  labels:
    common.k8s.elastic.co/type: elasticsearch
    eck.k8s.elastic.co/credentials: "true"
    elasticsearch.k8s.elastic.co/cluster-name: elasticsearch7
  name: elasticsearch7-es-internal-users
data:
  elastic-internal: REDACTED
  elastic-internal-monitoring: REDACTED
  elastic-internal-pre-stop: REDACTED
  elastic-internal-probe: REDACTED
```

**Comment by ElSamhaa** [comment]
@barkbay yes, but the `elastic-internal-pre-stop` is not. I've also fiddled with patching the secret with the missing key myself, but the controller continuously overwrites it.

**Comment by ElSamhaa** [comment]
1. The logs are rotated. I'll recreate the `elasticsearch` cr and update you.

2. no `elastic-internal-pre-stop` key in the secret:
```yaml
apiVersion: v1
data:
  elastic-internal: redacted
  elastic-internal-monitoring: redacted
  elastic-internal-probe: redacted
kind: Secret
metadata:
  labels:
    common.k8s.elastic.co/type: elasticsearch
    eck.k8s.elastic.co/credentials: "true"
    elasticsearch.k8s.elastic.co/cluster-name: elasticsearch7
  name: elasticsearch7-es-internal-users
  namespace: redacted
type: Opaque
```
