### ISSUE TITLE
Make it easier to download ECK and apply license

### ISSUE THREAD

**Issue by arthurdasilvagoncalves** [elastic/cloud-on-k8s#7360]
Currently to apply an ECK license it is required to create a YML with the license in base64. It would be great if the license download page could have the option to download the orchestration license in .yml format already, with the instructions to apply it as well.

i.e.

>Download license.yml manifest
```yml
apiVersion: v1
kind: Secret
metadata:
  labels:
    license.k8s.elastic.co/scope: operator 
  name: eck-license
type: Opaque
data:
  license: "eyeREDACTED=="
```

`kubectl apply -f license.yml`

or even a one-line command:

```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Secret
metadata:
  labels:
    license.k8s.elastic.co/scope: operator 
  name: eck-license
type: Opaque
data:
  license: "eyeREDACTED=="
EOF
```
