### ISSUE TITLE
Add clarifications regarding custom volume claim

### ISSUE THREAD

**Issue by romain-chanu** [elastic/cloud-on-k8s#7362]
The following [documentation](https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-volume-claim-templates.html) provides an important section:

>The name of the volume claim must always be elasticsearch-data. If you chose a different name you have to set up a corresponding volume mount matching the [data.path](https://www.elastic.co/guide/en/elasticsearch/reference/current/important-settings.html#path-settings) yourself ( /usr/share/elasticsearch/data by default).

However, it is not clear that `path.data` has to be in the `config` section of the Elasticsearch specification file (c.f [Node configuration](https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-node-configuration.html)).

Could we add clarifications regarding this?

**Comment by afamorim** [comment]
Anyone?

**Comment by thbkrkr** [comment]
It depends if you use `/usr/share/elasticsearch/data` as mount path or another value.

Let's use a different volume claim and so volume name `my-data` than `elasticsearch-data`.

Using `/usr/share/elasticsearch/data` as mount path, the default expected value, there is no need to configure `path.data`.

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: data1 
spec:
  version: 8.13.4
  nodeSets:
  - name: "n"
    count: 3
    config:
      node.store.allow_mmap: false
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          volumeMounts:
          - name: my-data
            mountPath: /usr/share/elasticsearch/data # <-- default path
    volumeClaimTemplates:
    - metadata:
        name: my-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: standard
```

With a custom path, you have to configure `path.data`.

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: data2 
spec:
  version: 8.13.4
  nodeSets:
  - name: "n"
    count: 3
    config:
      node.store.allow_mmap: false
      path.data: /mnt/data # <-- custom path
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          volumeMounts:
          - name: my-data
            mountPath: /mnt/data # <-- custom path
    volumeClaimTemplates:
    - metadata:
        name: my-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: standard
```

Check:
```sh
> k exec data1-es-n-0 -c elasticsearch -- ls /usr/share/elasticsearch/data 🟢
_state
lost+found
node.lock
nodes
snapshot_cache

> k exec data2-es-n-0 -c elasticsearch -- ls /usr/share/elasticsearch/data 🔴

> k exec data2-es-n-0 -c elasticsearch -- ls /mnt/data 🟢
_state
lost+found
node.lock
nodes
snapshot_cache

> k exec data1-es-n-0 -c elasticsearch -- ls /mnt/data 🔴
ls: cannot access '/mnt/data': No such file or directory
command terminated with exit code 2

```
