### ISSUE TITLE
Kibana 8.11.1 ECK 2.8.0 Cluster.Name

### ISSUE THREAD

**Issue by charliek17** [elastic/cloud-on-k8s#7370]
Azure AKS
Kibana 8.11.1 
ECK 2.8.0 

During upgrade from 8.9.2 to 8.11.1 Kibana seems to look for a cluster called "docker-cluster" not the one defined in elasticsearchRef:

Kibana doesn't come up, once rolled back to 8.9.2 even with a 8.11.1 cluster it seems to work.

Thanks,

**Comment by charliek17** [comment]
I have also confirmed this on separate K8 Clusters.

**Comment by barkbay** [comment]
Could you please check that you are not in the same situation as described in https://github.com/elastic/cloud-on-k8s/issues/1705 This seems to be an "environmental issue", unrelated to ECK itself.
If not could you provide your manifests and the list of all the Pods running ES on you k8s cluster.

**Comment by charliek17** [comment]
I can't provide helm charts explicitly. However I can confirm it's not related to the other issue - oddly if i redeploy a 8.9.2 kibana it works and searches the correct cluster.

**Comment by charliek17** [comment]
`eck-kibana:
  spec:
    version: 8.11.1
    http:
      service:
        spec:
         type: LoadBalancer
      tls:
        selfSignedCertificate:
          subjectAltNames:
          - dns: kibana.kc101.com
        certificate:
         secretName: my-cert
    
  #   metadata:
  #     labels:
  #       my-custom: label

    # Count of Kibana replicas to create.
    #
    count: 1

    # Reference to ECK-managed Elasticsearch resource, ideally from {{ "elasticsearch.fullname" }}
    #
    elasticsearchRef:
      name: elasticsearch


`
This doesn't work.


`---
eck-kibana:
  spec:
    version: 8.9.2
    http:
      service:
        spec:
         type: LoadBalancer
      tls:
        selfSignedCertificate:
          subjectAltNames:
          - dns: kibana.kc101.com
        certificate:
         secretName: my-cert
    
  #   metadata:
  #     labels:
  #       my-custom: label

    # Count of Kibana replicas to create.
    #
    count: 1

    # Reference to ECK-managed Elasticsearch resource, ideally from {{ "elasticsearch.fullname" }}
    #
    elasticsearchRef:
      name: elasticsearch
`

This does

**Comment by barkbay** [comment]
> This doesn't work.

I deployed an Elasticsearch resource named `elasticsearch`, and then used you example on ECK `2.10.0`. It seems to be working as expected:

```bash
> helm upgrade test-kb -n foo --values should-not-work.yaml $ECK/deploy/eck-stack/charts/eck-kibana 
Release "test-kb" has been upgraded. Happy Helming!
NAME: test-kb
LAST DEPLOYED: Tue Jan  2 09:21:51 2024
NAMESPACE: foo
STATUS: deployed
REVISION: 5
TEST SUITE: None
NOTES:
1. Check Kibana status
  $ kubectl get kibana test-kb-eck-kibana -n foo

2. Check Kibana pod status
  $ kubectl get pods --namespace=foo -l kibana.k8s.elastic.co/name=test-kb-eck-kibana
```

```
 kubectl get kibana test-kb-eck-kibana -n foo
NAME                 HEALTH   NODES   VERSION   AGE
test-kb-eck-kibana   green    1       8.11.1    22m
```

```yaml
 > cat should-not-work.yaml 
spec:
  version: 8.11.1
  http:
    service:
      spec:
        type: LoadBalancer
    tls:
      selfSignedCertificate:
        subjectAltNames:
          - dns: kibana.kc101.com
      certificate:
        secretName: my-cert

  #   metadata:
  #     labels:
  #       my-custom: label

  # Count of Kibana replicas to create.
  #
  count: 1

  # Reference to ECK-managed Elasticsearch resource, ideally from {{ "elasticsearch.fullname" }}
  #
  elasticsearchRef:
    name: elasticsearch
```

> I can't provide helm charts explicitly. 

Not sure what you mean, are you using the Helm Charts from this repo?

**Comment by barkbay** [comment]
As a side note I also successfully got Kibana running using the `eck-stack` chart:

```
> helm upgrade -i test-kb -n foo --values should-not-work.yaml $ECK/deploy/eck-stack/
Release "test-kb" does not exist. Installing it now.
NAME: test-kb
LAST DEPLOYED: Tue Jan  2 09:41:19 2024
NAMESPACE: foo
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Elasticsearch ECK-Stack 0.10.0-SNAPSHOT has been deployed successfully!

To see status of all resources, run

kubectl get elastic -n foo -l "app.kubernetes.io/instance"=test-kb

More information on the Elastic ECK Operator, and its Helm chart can be found
within our documentation.

https://www.elastic.co/guide/en/cloud-on-k8s/current/index.html
```

```yaml
✗ cat should-not-work.yaml  
eck-kibana:
  spec:
    version: 8.11.1
    http:
      service:
        spec:
          type: LoadBalancer
      tls:
        selfSignedCertificate:
          subjectAltNames:
            - dns: kibana.kc101.com
        certificate:
          secretName: my-cert

    #   metadata:
    #     labels:
    #       my-custom: label

    # Count of Kibana replicas to create.
    #
    count: 1

    # Reference to ECK-managed Elasticsearch resource, ideally from {{ "elasticsearch.fullname" }}
    #
    elasticsearchRef:
      name: elasticsearch
```
