### ISSUE TITLE
Enable the filebeat.yml configuration of the sidecar filebeat on Logstash

### ISSUE THREAD

**Issue by pbdger** [elastic/cloud-on-k8s#7415]
## Proposal

Enable the filebeat.yml configuration of the sidecar filebeat on Logstash.
This allows specific adjustments to be made, such as the dropping of certain log events.

## Bug Report
**What did you do?**

Configured Logstash via ECK

```
apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  namespace:  mynamespace
  name:  mycluster
spec:
  version: 8.11.1
  count: 32
  elasticsearchRefs:
    - name:  mycluster
      namespace: mynamespace
      clusterName: mycluster
  monitoring:
    metrics:
      elasticsearchRefs:
        - name: mycluster
      logs:
        elasticsearchRefs:
          - name: mycluster
     podTemplate:
  spec:
    containers:
      - name: "filebeat"
    
```

**What did you expect to see?**

I'm missing a (documented) way to pass a custom filebeat.yml file to the sidecar filebeat.

**What did you see instead? Under which circumstances?**

The ECK operator creates a secret mycluster-ls-monitoring-filebeat-config.
I cannot change this secret. I also cannot assign another secret to the filebeat sidecar as a mount for filebeat.yml.

**Environment**

* ECK version:

	2.10

**Comment by thbkrkr** [comment]
You should be able to customize the Filebeat and Metricbeat containers through the Pod template. Your configuration is then merged with the values of the default Pod template that ECK uses.

https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s_override_the_beats_pod_template.html

**Comment by pbdger** [comment]
Yeah, you are right. 

Here my solution for my request as an example for others, too;

```
apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  namespace: mynamespace
  name: mycluster
spec:
  version: 8.11.1
  count: 32
  elasticsearchRefs:
    - name: mycluster
      namespace: mynamespace
      clusterName: mycluster
  monitoring:
    metrics:
      elasticsearchRefs:
        - name: mycluster
      logs:
        elasticsearchRefs:
          - name: mycluster
      podTemplate:
  volumes:
    - name: phoenix-filebeat-config
      secret:
        secretName: mycustomized-logstash-filebeat-config
        defaultMode: 420
        optional: false
  spec:
    containers:
      - name: filebeat
        volumeMounts:
          - name: phoenix-filebeat-config
            readOnly: true
            mountPath: /etc/filebeat-config

```
