### ISSUE TITLE
Refactor expose to http.service.spec.type

### ISSUE THREAD

**Issue by nkvoll** [elastic/cloud-on-k8s#746]
Currently our resources use `expose: <string>` as the service type, but we'd like to expand the possible config settings here, and the first step is changing the format slightly to be more expandable and in line with how a Service in K8s is defined:

Suggested new format:
```
  http:
    service:
      metadata:
        annotations:
          # example showing how to set custom annotation-driven settings
          service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
      spec:
        # supports automatically creating a LoadBalancer for the HTTP endpoints.
        type: LoadBalancer
```
