### ISSUE TITLE
Operator fail to watch multi-namespace

### ISSUE THREAD

**Issue by stefTLomba** [elastic/cloud-on-k8s#7542]
## Bug Report
**What did you do?**

I'm trying to use OLM (Operator Lifecycle Manager) with this kind of configuration to select which namespace can use CR provided by the operator:

```yaml
kind: Namespace
apiVersion: v1
metadata:
  name: elasticsearch-eck-operator
  labels:
    poste.io/elasticsearch-eck-operator: "true"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: elasticsearch-eck-operatorgroup
  namespace: elasticsearch-eck-operator
spec:
  selector:
    matchLabels:
      mycustomlabel/elasticsearch-eck-operator: "true"
```
then, one can label *myapp* namespace to provide visibility of the CR:

```bash
oc label ns myapp mycustomlabel/elasticsearch-eck-operator=true
```

**What did you expect to see?**

creation of resource managed by the operator in *myapp* namespace

**What did you see instead? Under which circumstances?**

CrashLoopBackOff by operator, with these logs:

```
W0208 14:28:14.511805       1 reflector.go:535] pkg/mod/k8s.io/client-go@v0.28.4/tools/cache/reflector.go:229: failed to list *v1.Elasticsearch: elasticsearches.elasticsearch.k8s.elastic.co is forbidden: User "system:serviceaccount:elasticsearch-eck-operator:elastic-operator" cannot list resource "elasticsearches" in API group "elasticsearch.k8s.elastic.co" in the namespace "elasticsearch-eck-operator,myapp"
E0208 14:28:14.511836       1 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.4/tools/cache/reflector.go:229: Failed to watch *v1.Elasticsearch: failed to list *v1.Elasticsearch: elasticsearches.elasticsearch.k8s.elastic.co is forbidden: User "system:serviceaccount:elasticsearch-eck-operator:elastic-operator" cannot list resource "elasticsearches" in API group "elasticsearch.k8s.elastic.co" in the namespace "elasticsearch-eck-operator,myapp"
```

but OLM already copied necessary role and rolebinding in *myapp* namespace:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: elasticsearch-eck-operator
  ownerReferences:
  - apiVersion: operators.coreos.com/v2
    blockOwnerDeletion: false
    controller: true
    kind: OperatorCondition
    name: myapp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: elasticsearch-eck-operator-certified.v2.11.1
subjects:
- kind: ServiceAccount
  name: elastic-operator
  namespace: elasticsearch-eck-operator
```

In fact, `kubectl auth can-i` report that serviceaccount of operator can list relevant resource in *myapp* namespace

```bash
kubectl auth can-i list elasticsearches.elasticsearch.k8s.elastic.co --as=system:serviceaccount:elasticsearch-eck-operator:elastic-operator -n myapp
yes
yes
```

It seems that operator append list from OLM and treat as single string instead of expand list

```yaml
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
...
status:
  namespaces:
  - elasticsearch-eck-operator
  - myapp
```

**Environment**

* ECK version:

	Elasticsearch (ECK) Operator 2.11.1

* Kubernetes information:

	Openshift 4.12.30
	

* Resource definition:
```
if relevant insert the resource definition
```

* Logs:
```
insert operator logs or any relevant message to the issue here
```

**Comment by pebrc** [comment]
I think the issue we are running into here is this viper bug https://github.com/spf13/viper/issues/380 where string slices are handled differently when specified via an environment variable compared to using the flag directly. 

When using OLM the list of namespaces is propagated to the ECK operator via the environment: 
```
env:                                                                                                                                                                                 │
  - name: NAMESPACES                                                                                                                                                                   │
     valueFrom:                                                                                                                                                                         │
       fieldRef:                                                                                                                                                                        │
         apiVersion: v1                                                                                                                                                                 │
         fieldPath: metadata.annotations['olm.targetNamespaces']    
```
which means we are hitting the aforementioned bug. Instead of an slice with two entries we are getting a single string unparsed and still comma-separated.

**Comment by pebrc** [comment]
There is a workaround by editing the subscription and specfying the `NAMESPACES` environment variable as a whitespace separated list instead: 

```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: elasticsearch-eck-operator-certified
  namespace: elasticsearch-eck-operator
spec:
  channel: stable
  config:
    env:
    - name: NAMESPACES
      value: "elasticsearch-eck-operator myapp"
```
