### ISSUE TITLE
Kibana misconfiguration can cause Fleet errors.

### ISSUE THREAD

**Issue by naemono** [elastic/cloud-on-k8s#7543]
There appear to be Kibana settings that can cause the operator to fail to check Kibana's Fleet api which in turn causes errors which causes reconciliation delays or reconciliation failures for Elastic Agent Fleet.:

example
```
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
spec:
  config:
    xpack.security.authc.providers:
      saml.saml1:
        order: 0
        realm: saml1
```

potentially related:
```
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
spec:
  config:
    xpack.security.authc.http.schemes:
    - apikey
    - bearer
    - basic
```

The relevant error from the logs:
```
Reconciliation error: failed to request https://kibana-kb-http.namespace.svc:5601/api/fleet/setup, status is 401)
```

This seems to disable `basic` authentication provider, which ECK uses to query the Kibana api.

Potential changes to discuss:
1. Maybe use another provider such as bearer/apikey, but what's stopping that from being disabled as well?
2. Add validation which prevents Kibana from being configured in this manner.
