### ISSUE TITLE
[Docs][Bug] ECK Documentation about EmptyDir for Logstash is wrong

### ISSUE THREAD

**Issue by vladelleus** [elastic/cloud-on-k8s#7546]
## Bug Report
**What did you do?**
On the official [documentation](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-logstash-configuration.html#k8s-emptydir) it is said that: if you are not concerned about data loss, you can use an emptyDir volume for Logstash data. For that, I should use such values:
```yaml
spec:
  count: 5
  podTemplate:
    spec:
      volumeClaimTemplates:
      - name: logstash-data
        emptyDir: {}
```

**What did you expect to see?**
I expected to see that there are no PVC and PV created in the EKS cluster and the volume at the path `/usr/share/logstash/data` is just an empty dir.

**What did you see instead? Under which circumstances?**
I saw that PVC still creates and claims the PV. 
Here is the configuration from the Logstash StatefulSet resource, and you can see that the volume is an `emptyDir`, but the `volumeClaimTemplates` still rendering in the StatefulSet thus creating the PVC and PV for `emptyDir` volume:
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: logstash-ls
spec:
  replicas: 1
  selector:
    matchLabels:
      common.k8s.elastic.co/type: logstash
      logstash.k8s.elastic.co/name: logstash
  template:
    metadata:
      creationTimestamp: null
      labels:
        common.k8s.elastic.co/type: logstash
        logstash.k8s.elastic.co/name: logstash
        logstash.k8s.elastic.co/version: 8.9.0
      annotations:
        logstash.k8s.elastic.co/config-hash: '459650449'
    spec:
      volumes:
        - name: config
          emptyDir: {}
        - name: elastic-internal-logstash-config
          secret:
            secretName: logstash-ls-config
            defaultMode: 420
            optional: false
        - name: elastic-internal-logstash-pipeline
          secret:
            secretName: logstash-ls-pipeline
            defaultMode: 420
            optional: false
        - name: elasticsearch-certs-0
          secret:
            secretName: logstash-logstash-es-monitoring-elasticsearch-ca
            defaultMode: 420
            optional: false
        - name: logstash-data
          emptyDir: {}
        - name: logstash-logs
          emptyDir: {}
      initContainers:
        - name: logstash-internal-init-config
          image: docker.elastic.co/logstash/logstash:8.9.0
          command:
            - /usr/bin/env
            - bash
            - '-c'
            - >
              #!/usr/bin/env bash

              set -eu


              init_config_initialized_flag=/mnt/elastic-internal/logstash-config-local/elastic-internal-init-config.ok


              if [[ -f "${init_config_initialized_flag}" ]]; then
                  echo "Logstash configuration already initialized."
                  exit 0
              fi


              echo "Setup Logstash configuration"


              mount_path=/mnt/elastic-internal/logstash-config-local


              cp -f /usr/share/logstash/config/*.* "$mount_path"


              ln -sf /mnt/elastic-internal/logstash-config/logstash.yml
              $mount_path

              ln -sf /mnt/elastic-internal/logstash-pipeline/pipelines.yml
              $mount_path


              touch "${init_config_initialized_flag}"

              echo "Logstash configuration successfully prepared."
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
            requests:
              cpu: 100m
              memory: 50Mi
          volumeMounts:
            - name: config
              mountPath: /mnt/elastic-internal/logstash-config-local
            - name: elastic-internal-logstash-config
              readOnly: true
              mountPath: /mnt/elastic-internal/logstash-config
            - name: elastic-internal-logstash-pipeline
              readOnly: true
              mountPath: /mnt/elastic-internal/logstash-pipeline
            - name: elasticsearch-certs-0
              readOnly: true
              mountPath: >-
                /mnt/elastic-internal/elasticsearch-association/monitoring/elasticsearch/certs
            - name: logstash-data
              mountPath: /usr/share/logstash/data
            - name: logstash-logs
              mountPath: /usr/share/logstash/logs
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:8.9.0
          ports:
            - name: http
              containerPort: 9600
              protocol: TCP
          env:
            - name: ECK_ES_HOSTS
              value: https://elasticsearch-es-http.monitoring.svc:9200
            - name: ECK_ES_USER
              value: monitoring-logstash-monitoring-elasticsearch-logstash-user
            - name: ECK_ES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: logstash-monitoring-elasticsearch-logstash-user
                  key: monitoring-logstash-monitoring-elasticsearch-logstash-user
            - name: ECK_ES_SSL_CERTIFICATE_AUTHORITY
              value: >-
                /mnt/elastic-internal/elasticsearch-association/monitoring/elasticsearch/certs/ca.crt
          resources:
            limits:
              cpu: '2'
              memory: 2Gi
            requests:
              cpu: '1'
              memory: 2Gi
          volumeMounts:
            - name: config
              mountPath: /usr/share/logstash/config
            - name: elastic-internal-logstash-config
              readOnly: true
              mountPath: /mnt/elastic-internal/logstash-config
            - name: elastic-internal-logstash-pipeline
              readOnly: true
              mountPath: /mnt/elastic-internal/logstash-pipeline
            - name: elasticsearch-certs-0
              readOnly: true
              mountPath: >-
                /mnt/elastic-internal/elasticsearch-association/monitoring/elasticsearch/certs
            - name: logstash-data
              mountPath: /usr/share/logstash/data
            - name: logstash-logs
              mountPath: /usr/share/logstash/logs
          readinessProbe:
            httpGet:
              path: /
              port: 9600
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 1000
      schedulerName: default-scheduler
  volumeClaimTemplates:
    - kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: logstash-data
        creationTimestamp: null
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        volumeMode: Filesystem
      status:
        phase: Pending
```
Here are the screenshots:
![image](https://github.com/elastic/cloud-on-k8s/assets/84621365/7bd75d3b-d74e-4617-9b68-d9219f1d29d4)
![image](https://github.com/elastic/cloud-on-k8s/assets/84621365/c0be0914-e231-4396-b73d-d21ef3b3ce94)
As a solution I tried:
```yaml
spec:
  count: 5
  podTemplate:
    spec:
      volumes:
      - name: logstash-data
        emptyDir: {}
```
And here is the configuration of the StatefulSet resource, as you can see the PVC and PV were not created due to absent `volumeClaimTemplates` field in the spec:
```yaml
spec:
  replicas: 1
  selector:
    matchLabels:
      common.k8s.elastic.co/type: logstash
      logstash.k8s.elastic.co/name: logstash
  template:
    metadata:
      creationTimestamp: null
      labels:
        common.k8s.elastic.co/type: logstash
        logstash.k8s.elastic.co/name: logstash
        logstash.k8s.elastic.co/version: 8.9.0
      annotations:
        logstash.k8s.elastic.co/config-hash: '3172760363'
    spec:
      volumes:
        - name: config
          emptyDir: {}
        - name: elastic-internal-logstash-config
          secret:
            secretName: logstash-ls-config
            defaultMode: 420
            optional: false
        - name: elastic-internal-logstash-pipeline
          secret:
            secretName: logstash-ls-pipeline
            defaultMode: 420
            optional: false
        - name: elasticsearch-certs-0
          secret:
            secretName: logstash-logstash-es-monitoring-elasticsearch-ca
            defaultMode: 420
            optional: false
        - name: logstash-data
          emptyDir: {}
        - name: logstash-logs
          emptyDir: {}
      initContainers:
        - name: logstash-internal-init-config
          image: docker.elastic.co/logstash/logstash:8.9.0
          command:
            - /usr/bin/env
            - bash
            - '-c'
            - >
              #!/usr/bin/env bash

              set -eu


              init_config_initialized_flag=/mnt/elastic-internal/logstash-config-local/elastic-internal-init-config.ok


              if [[ -f "${init_config_initialized_flag}" ]]; then
                  echo "Logstash configuration already initialized."
                  exit 0
              fi


              echo "Setup Logstash configuration"


              mount_path=/mnt/elastic-internal/logstash-config-local


              cp -f /usr/share/logstash/config/*.* "$mount_path"


              ln -sf /mnt/elastic-internal/logstash-config/logstash.yml
              $mount_path

              ln -sf /mnt/elastic-internal/logstash-pipeline/pipelines.yml
              $mount_path


              touch "${init_config_initialized_flag}"

              echo "Logstash configuration successfully prepared."
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
            requests:
              cpu: 100m
              memory: 50Mi
          volumeMounts:
            - name: config
              mountPath: /mnt/elastic-internal/logstash-config-local
            - name: elastic-internal-logstash-config
              readOnly: true
              mountPath: /mnt/elastic-internal/logstash-config
            - name: elastic-internal-logstash-pipeline
              readOnly: true
              mountPath: /mnt/elastic-internal/logstash-pipeline
            - name: elasticsearch-certs-0
              readOnly: true
              mountPath: >-
                /mnt/elastic-internal/elasticsearch-association/monitoring/elasticsearch/certs
            - name: logstash-data
              mountPath: /usr/share/logstash/data
            - name: logstash-logs
              mountPath: /usr/share/logstash/logs
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:8.9.0
          ports:
            - name: http
              containerPort: 9600
              protocol: TCP
          env:
            - name: ECK_ES_HOSTS
              value: https://elasticsearch-es-http.monitoring.svc:9200
            - name: ECK_ES_USER
              value: monitoring-logstash-monitoring-elasticsearch-logstash-user
            - name: ECK_ES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: logstash-monitoring-elasticsearch-logstash-user
                  key: monitoring-logstash-monitoring-elasticsearch-logstash-user
            - name: ECK_ES_SSL_CERTIFICATE_AUTHORITY
              value: >-
                /mnt/elastic-internal/elasticsearch-association/monitoring/elasticsearch/certs/ca.crt
          resources:
            limits:
              cpu: '2'
              memory: 2Gi
            requests:
              cpu: '1'
              memory: 2Gi
          volumeMounts:
            - name: config
              mountPath: /usr/share/logstash/config
            - name: elastic-internal-logstash-config
              readOnly: true
              mountPath: /mnt/elastic-internal/logstash-config
            - name: elastic-internal-logstash-pipeline
              readOnly: true
              mountPath: /mnt/elastic-internal/logstash-pipeline
            - name: elasticsearch-certs-0
              readOnly: true
              mountPath: >-
                /mnt/elastic-internal/elasticsearch-association/monitoring/elasticsearch/certs
            - name: logstash-data
              mountPath: /usr/share/logstash/data
            - name: logstash-logs
              mountPath: /usr/share/logstash/logs
          readinessProbe:
            httpGet:
              path: /
              port: 9600
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 1000
      schedulerName: default-scheduler
  serviceName: logstash-ls-api
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  revisionHistoryLimit: 10
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
```
In the Elasticsearch volume claim template [docs](https://www.elastic.co/guide/en/cloud-on-k8s/2.11/k8s-volume-claim-templates.html#k8s_emptydir) is stated to use `volume` not the `volumeClaimTemplates`. So, please update the docs of fix this issue.

**Environment**

* ECK version:

2.11

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* Cloud: EKS, 1.27
```
$ kubectl version
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.9-eks-5e0fdde
WARNING: version difference between client (1.29) and server (1.27) exceeds the supported minor version skew of +/-1
```

* Resource definition:
Here is the rendered Logstash template:
```yaml
apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: logstash
  labels:
    "app": "logstash"
  annotations:
    eck.k8s.elastic.co/license: basic
spec:
  version: 8.9.0
  count: 1
  config:
    queue.type: memory
  podTemplate:
    spec:
      volumeClaimTemplates:
      - emptyDir: {}
        name: logstash-data
   otherconfiguration:
```

* Logs:
No logs from the ECK operator about Logstash when claiming volume or something else.

**Comment by thbkrkr** [comment]
Hello, thank you for reporting, there is indeed a problem in the documentation that we will correct.
As you have noticed, the correct specification to have an `emptyDir` volume for Logstash data is:

```yaml
spec:
  count: 5
  podTemplate:
    spec:
      volumes:
      - name: logstash-data
        emptyDir: {}
```
