### ISSUE TITLE
Cannot resize logstash volume

### ISSUE THREAD

**Issue by mrad-bilel** [elastic/cloud-on-k8s#7620]
## Proposal

**Allow the resize of logstash volume size**

## Bug Report
**What did you do?**

Update the helm chart value by increasing the value of volumeClaimTemplates section

**What did you expect to see?**

PVC updated then PV with the new size

**What did you see instead? Under which circumstances?**

helm upgrade throw an error volume claim templates cannot be modified .

**Environment**

* ECK version:  2.11.1

* Kubernetes information:

	* Cloud:  AKS v1.27.9
	
	for each of them please give us the version you are using
```
kubectl version
Client Version: v1.28.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.9
```

* Resource definition:
```
#logstash
eck-logstash:
  enabled: true
  version: 8.12.2
  annotations:
    eck.k8s.elastic.co/license: basic
  count: 1
  podTemplate:
    spec:
      containers:
      - name: logstash
        resources:
          requests:
            memory: 1Gi
            cpu: 1
          limits:
            memory: 4Gi
            cpu: 3
  volumeClaimTemplates:
  - metadata:
      name: logstash-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
      storageClassName: managed-csi-premium-retain
  elasticsearchRefs:
    - clusterName: "int"
      name: "int"
```
```
k get pvc
NAME                                                 STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                 AGE
elasticsearch-data-int-es-master-0            Bound    pvc-fa41dedc-d017-4b63-b515-535c17c10d2f   128Gi      RWO            managed-csi-premium-retain   4m23s
logstash-data-elastic-int-eck-logstash-ls-0   Bound    pvc-88309b5a-8e23-4738-b636-1cd095f946a6   10Gi       RWO            managed-csi-premium-retain   4m23s
```
```
k describe sc managed-csi-premium-retain
Name:            managed-csi-premium-retain
IsDefaultClass:  No
Annotations:     kubectl.kubernetes.io/last-applied-configuration={"allowVolumeExpansion":true,"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"EnsureExists","kubernetes.io/cluster-service":"true"},"name":"managed-csi-premium-retain"},"parameters":{"skuname":"Premium_LRS"},"provisioner":"disk.csi.azure.com","reclaimPolicy":"Retain","volumeBindingMode":"WaitForFirstConsumer"}

Provisioner:           disk.csi.azure.com
Parameters:            skuname=Premium_LRS
AllowVolumeExpansion:  True
MountOptions:          <none>
ReclaimPolicy:         Retain
VolumeBindingMode:     WaitForFirstConsumer
Events:                <none>
```
```
helm ls
NAME                    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
elastic-int              elastic-system  2               2024-03-13 15:25:19.864548663 +0100 CET failed          eck-stack-0.9.1
elastic-operator        elastic-system  1               2024-03-11 14:20:29.793384647 +0100 CET deployed        eck-operator-2.11.1     2.11.1
```

* Logs:
```
helm upgrade   elastic-int -f es-values.yaml elastic/eck-stack -n elastic-system
Error: UPGRADE FAILED: cannot patch "elastic-museng-int-eck-logstash" with kind Logstash: admission webhook "elastic-logstash-validation-v1alpha1.k8s.elastic.co" denied the request: Logstash.logstash.k8s.elastic.co "elastic-museng-int-eck-logstash" is invalid: spec.volumeClaimTemplates: Invalid value: []v1.PersistentVolumeClaim{v1.PersistentVolumeClaim{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"logstash-data", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ManagedFields:[]v1.ManagedFieldsEntry(nil)}, Spec:v1.PersistentVolumeClaimSpec{AccessModes:[]v1.PersistentVolumeAccessMode{"ReadWriteOnce"}, Selector:(*v1.LabelSelector)(nil), Resources:v1.ResourceRequirements{Limits:v1.ResourceList(nil), Requests:v1.ResourceList{"storage":resource.Quantity{i:resource.int64Amount{value:21474836480, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"20Gi", Format:"BinarySI"}}, Claims:[]v1.ResourceClaim(nil)}, VolumeName:"", StorageClassName:(*string)(0xc00119e250), VolumeMode:(*v1.PersistentVolumeMode)(nil), DataSource:(*v1.TypedLocalObjectReference)(nil), DataSourceRef:(*v1.TypedObjectReference)(nil)}, Status:v1.PersistentVolumeClaimStatus{Phase:"", AccessModes:[]v1.PersistentVolumeAccessMode(nil), Capacity:v1.ResourceList(nil), Conditions:[]v1.PersistentVolumeClaimCondition(nil), AllocatedResources:v1.ResourceList(nil), AllocatedResourceStatuses:map[v1.ResourceName]v1.ClaimResourceStatus(nil)}}}: Volume claim templates cannot be modified
```
