### ISSUE TITLE
do_not_restart_healthy_node_if_MaxUnavailable_reached can not rollout

### ISSUE THREAD

**Issue by lanss315425** [elastic/cloud-on-k8s#7656]
## Bug Report
**What did you do?**
First, I added secureSettings and executed kubectl apply - f es.yaml, but pods couldn't start. Then, I added initContainers and executed kubectl apply - f es.yaml, but kept getting loop errors. Even when I executed kubectl delete - f es.yaml, it didn't work
**What did you expect to see?**
I expected that ECK rollout my ES StatefullSet
**What did you see instead? Under which circumstances?**
I get error pasted below
**Environment**

* ECK version:

2.10.0

* Kubernetes information:
 On premise 
```
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.13", GitCommit:"7ba444e261616cb572b2c9e3aa6ee8876140f46a", GitTreeState:"clean", BuildDate:"2024-01-17T13:45:13Z", GoVersion:"go1.20.13", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.13", GitCommit:"7ba444e261616cb572b2c9e3aa6ee8876140f46a", GitTreeState:"clean", BuildDate:"2024-01-17T13:37:06Z", GoVersion:"go1.20.13", Compiler:"gc", Platform:"linux/amd64"}
```

* Resource definition:
```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: es-cluster
  namespace: es
spec:
  version: 7.17.15
  secureSettings:
  - secretName: es-cluster-snapshot-settings
  nodeSets:
  - name: master-nodes
    count: 3
    config:
      node.master: true
      node.data: false
      node.ingest: false
    podTemplate:
      metadata:
        labels:
          node_type: master
      spec:
        initContainers:
        - name: install-plugins
          command:
          - sh
          - -c
          - |
            bin/elasticsearch-plugin install --batch repository-gcs
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 2Gi
              cpu: 1000m
            limits:
              memory: 2Gi
              cpu: 1000m
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: local-path
  - name: data-nodes
    count: 3
    config:
      node.master: false
      node.data: true
      node.ingest: true
    podTemplate:
      metadata:
        labels:
          node_type: data
      spec:
        initContainers:
        - name: install-plugins
          command:
          - sh
          - -c
          - |
            bin/elasticsearch-plugin install --batch repository-gcs
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 2Gi
              cpu: 1
            limits:
              memory: 2Gi
              cpu: 1
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: local-path
  http:
    tls:
      selfSignedCertificate:
        disabled: true
    service:
      spec:
        type: NodePort
```

* Logs:
```
{"log.level":"info","@timestamp":"2024-03-26T05:46:59.537Z","log.logger":"elasticsearch-controller","message":"Starting reconciliation run","service.version":"2.10.0+59c1e727","service.type":"eck","ecs.version":"1.4.0","iteration":"480","namespace":"default","es_name":"es-cluster"}
{"log.level":"info","@timestamp":"2024-03-26T05:46:59.538Z","log.logger":"elasticsearch-controller","message":"Updating resource","service.version":"2.10.0+59c1e727","service.type":"eck","ecs.version":"1.4.0","iteration":"480","namespace":"default","es_name":"es-cluster","kind":"Service","namespace":"default","name":"es-cluster-es-http"}
{"log.level":"info","@timestamp":"2024-03-26T05:46:59.579Z","log.logger":"elasticsearch-controller","message":"Ensuring no voting exclusions are set","service.version":"2.10.0+59c1e727","service.type":"eck","ecs.version":"1.4.0","iteration":"480","namespace":"default","es_name":"es-cluster","namespace":"default","es_name":"es-cluster"}
{"log.level":"info","@timestamp":"2024-03-26T05:46:59.607Z","log.logger":"elasticsearch-controller","message":"Cannot restart some nodes for upgrade at this time","service.version":"2.10.0+59c1e727","service.type":"eck","ecs.version":"1.4.0","iteration":"480","namespace":"default","es_name":"es-cluster","namespace":"default","es_name":"es-cluster","failed_predicates":{"do_not_restart_healthy_node_if_MaxUnavailable_reached":["es-cluster-es-data-nodes-0","es-cluster-es-data-nodes-1","es-cluster-es-master-nodes-0","es-cluster-es-master-nodes-1","es-cluster-es-master-nodes-2"]}}
{"log.level":"info","@timestamp":"2024-03-26T05:46:59.607Z","log.logger":"elasticsearch-controller","message":"Ending reconciliation run","service.version":"2.10.0+59c1e727","service.type":"eck","ecs.version":"1.4.0","iteration":"480","namespace":"default","es_name":"es-cluster","took":0.069697229}
```
