### ISSUE TITLE
Reconciler error - elasticsearch client failed - [update_desired_nodes_request] failed to parse field [nodes]

### ISSUE THREAD

**Issue by thbkrkr** [elastic/cloud-on-k8s#7664]
After upgrading ECK 2.12.0, upgrading Elasticsearch from 8.12.2 to 8.13.0 is stalled on the following error:
```go
2024-03-27T11:48:26.479+0100    ERROR   manager.eck-operator    Reconciler error        {
  "service.version": "2.12.0-SNAPSHOT+dbdcc1c5", 
  "controller": "elasticsearch-controller", 
  "object": {"name":"q","namespace":"test"}, "namespace": "test", "name": "q", 
  "reconcileID": "f7ab9df2-ab31-4a34-b07e-c0c56c36e5f0", 
  "error": "elasticsearch client failed for https://q-es-internal-http.test.svc:9200/_internal/desired_nodes/4859b6c6-4d16-41a2-a59b-563dcb9cf34c/3?error_trace=true: 
  400 Bad Request: {Status:400 Error:{CausedBy:{Reason:Required [node_version] Type:illegal_argument_exception}
  Reason:[1:1387] [update_desired_nodes_request] failed to parse field [nodes] Type:x_content_parse_exception
  StackTrace:org.elasticsearch.xcontent.XContentParseException: [1:1387] [update_desired_nodes_request] failed to parse field [nodes]
...
```

**Comment by thbkrkr** [comment]
The bug was introduced in:
- https://github.com/elastic/cloud-on-k8s/pull/7628

The Elasticsearch version from the `Spec` is used to check if the deprecated field needs to be removed or not, instead of the minimum Elasticsearch version in the cluster.

**Comment by thbkrkr** [comment]
Manifest to reproduce:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: test
spec:
  version: 8.12.0
  nodeSets:
  - name: master
    count: 1
    config:
      node.store.allow_mmap: false
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 4Gi
              cpu: 2
            limits:
              memory: 4Gi
```
