### ISSUE TITLE
Deploy ECK on GKE Autopilot: the Daemonset with "sleep infinity" as recommended approach has drawbacks

### ISSUE THREAD

**Issue by simonecaf** [elastic/cloud-on-k8s#7686]
Hello!

By reading the [official documentation in here](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-autopilot-setting-virtual-memory.html) it seems that the recommended approach to setup the Virtual Memory on a Elasticsearch cluster running in GKE Autopilot is by using a Daemonset.

I fully understand the reason behind this option as alternatives based on using privileged containers are not allowed.

However I would like to challenge the recommendation of using a **sleep infinity** based solution as suggested approach within the [docs](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-virtual-memory.html) and the examples. Here is the example from the docs:

```
cat <<EOF | kubectl apply -n elastic-system -f -
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: max-map-count-setter
  labels:
    k8s-app: max-map-count-setter
spec:
  selector:
    matchLabels:
      name: max-map-count-setter
  template:
    metadata:
      labels:
        name: max-map-count-setter
    spec:
      initContainers:
        - name: max-map-count-setter
          image: docker.io/bash:5.2.21
          resources:
            limits:
              cpu: 100m
              memory: 32Mi
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['/usr/local/bin/bash', '-e', '-c', 'echo 262144 > /proc/sys/vm/max_map_count']
      containers:
        - name: sleep
          image: docker.io/bash:5.2.21
          command: ['sleep', 'infinity']
EOF
```

While I can see that it's low resource in itself, I can't see it as a Prod ready solution. If my understanding is correct, to fullfil Daemonset manifest, one additional pod will be created to each corresponding K8s node (often hosting an Elasticsearch pod only). 

The result is that it doubles the IP usage of an ES cluster and adds some cpu and ram footprint for the entire lifespan of the cluster, even if its aim is scoped to the init container setup.

In essence my suggestion is to try to revisit it with an approach that makes the Daemonset short lived or at least scoped to only its memory setup activity.
