### ISSUE TITLE
Operator error logs - enterprisesearch.k8s.elastic.co/v1: the server could not find the requested resource\nfailed to aggregate Enterprise Search memory

### ISSUE THREAD

**Issue by dacriper** [elastic/cloud-on-k8s#7689]
ECK version: 2.11.1
Kubernetes information: On premise
kubernetes version: v1.24.2

I am receiving the error log from the ECK operator. 
I have deployed Elasticsearch (x3) and Kibana (x3) without any issues. However, the operator restarts after issuing the following error.

Logs operator:
```
{
  "log.level": "error",
  "@timestamp": "2024-04-04T16:08:48.819Z",
  "log.logger": "resource-reporter",
  "message": "Failed to report licensing information",
  "service.version": "2.11.1+ddde9953",
  "service.type": "eck",
  "ecs.version": "1.4.0",
  "error": "failed to aggregate Enterprise Search memory: failed to get API group resources: unable to retrieve the complete list of server APIs: enterprisesearch.k8s.elastic.co/v1: the server could not find the requested resource",
  "errorVerbose": "failed to get API group resources: unable to retrieve the complete list of server APIs: enterprisesearch.k8s.elastic.co/v1: the server could not find the requested resource\nfailed to aggregate Enterprise Search memory\ngithub.com/elastic/cloud-on-k8s/v2/pkg/license.Aggregator.aggregateEnterpriseSearchMemory\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/license/aggregator.go:91\ngithub.com/elastic/cloud-on-k8s/v2/pkg/license.Aggregator.AggregateMemory\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/license/aggregator.go:48\ngithub.com/elastic/cloud-on-k8s/v2/pkg/license.ResourceReporter.Get\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/license/reporter.go:80\ngithub.com/elastic/cloud-on-k8s/v2/pkg/license.ResourceReporter.Report\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/license/reporter.go:67\ngithub.com/elastic/cloud-on-k8s/v2/pkg/license.ResourceReporter.Start\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/license/reporter.go:48\ngithub.com/elastic/cloud-on-k8s/v2/cmd/manager.asyncTasks.func1\n\t/go/src/github.com/elastic/cloud-on-k8s/cmd/manager/main.go:781\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1650",
  "error.stack_trace": "github.com/elastic/cloud-on-k8s/v2/pkg/license.ResourceReporter.Start\n\t/go/src/github.com/elastic/cloud-on-k8s/pkg/license/reporter.go:50\ngithub.com/elastic/cloud-on-k8s/v2/cmd/manager.asyncTasks.func1\n\t/go/src/github.com/elastic/cloud-on-k8s/cmd/manager/main.go:781"
}
```

Clearly, the error is enterprisesearch.k8s.elastic.co/v1: the server could not find the requested resource.

I read this thread [link](https://discuss.elastic.co/t/eck-operator-1-4-stuck-in-deployment-error-no-matches-for-kind-enterprisesearch-in-version-enterpriseseach-k8s-elastic-co-v1/271818) which helped me understand that the version v1 of enterprise search was not declared, only v1beta1 was.

In my case, the crd.yaml file does contain the version v1 as well as the version v1beta1.

```
spec:
  group: enterprisesearch.k8s.elastic.co
  names:
    categories:
    - elastic
    kind: EnterpriseSearch
    listKind: EnterpriseSearchList
    plural: enterprisesearches
    shortNames:
    - ent
    singular: enterprisesearch
  scope: Namespaced
  versions:
   - additionalPrinterColumns:
     - [...]
       name: v1
       [...]
   - additionalPrinterColumns:
     - [...]
       name: v1beta1
       [...]
```

So, ¿why is the error mentioned by the operator occurring?

Elasticsearch and Kibana were deployed and functioning. I mention this for context.

To apply the CRD and the operator, I used [this guide](https://www.elastic.co/guide/en/cloud-on-k8s/2.11/k8s-deploy-eck.html) with the operator version 2.11.1 and CRD version 2.11.1.

Extra:
I don't have Enterprise deployed. 
However, if I deploy it with apiVersion: enterprisesearch.k8s.elastic.co/v1, it tells me that version v1 is not recognized (I'm using Helm). On the other hand, if I deploy with apiVersion: enterprisesearch.k8s.elastic.co/v1beta1, I don't get any errors from Helm, but the deployment is not visible in the workload visualizer (Rancher).
