### ISSUE TITLE
Service xxx is invalid: spec.loadBalancerClass: Invalid value: "null"

### ISSUE THREAD

**Issue by alekc** [elastic/cloud-on-k8s#7691]
## Bug Report
**What did you do?**
Given the logstash config 
```yaml
apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: ${stack_name}
  namespace: ${namespace}
spec:
  count: 1
  elasticsearchRefs:
    - name: ${stack_name}
      clusterName: ${stack_name}
  version: ${version}
  pipelines:
    - pipeline.id: gelf
      config.string: |
        input {
          gelf {
            port => 12201
            add_field => { "input_source" => "gelf" }
          }
        }
        output {
          elasticsearch {
            hosts => [ "$${MAIN_ES_HOSTS}" ]
            user => "$${MAIN_ES_USER}"
            password => "$${MAIN_ES_PASSWORD}"
            ssl_certificate_authorities => "$${MAIN_ES_SSL_CERTIFICATE_AUTHORITY}"
            index => "gelf-%%{+YYYY.MM.dd}"
          }
        }
  services:
    - name: beats
      service:
        spec:
          type: NodePort
          ports:
            - port: 5044
              name: "filebeat"
              protocol: TCP
              targetPort: 5044
    - name: udp
      service:
        spec:
          type: LoadBalancer
          ports:
            - port: 12201
              name: "filebeat"
              protocol: UDP
              targetPort: 12201
```
The reconciliation was failing with 
```
{"log.level":"info","@timestamp":"2024-04-05T11:15:26.411Z","log.logger":"logstash-controller","message":"Updating resource","service.version":"2.12.1+a56215f7","service.type":"eck","ecs.version":"1.4.0","iteration":"20","namespace":"logging","logstash_name":"main","kind":"Service","namespace":"logging","name":"main-ls-udp"}
{"log.level":"info","@timestamp":"2024-04-05T11:15:26.437Z","log.logger":"logstash-es","message":"Ending reconciliation run","service.version":"2.12.1+a56215f7","service.type":"eck","ecs.version":"1.4.0","iteration":"2","namespace":"logging","logstash_name":"main","took":0.099525177}
{"log.level":"info","@timestamp":"2024-04-05T11:15:26.437Z","log.logger":"logstash-es","message":"Starting reconciliation run","service.version":"2.12.1+a56215f7","service.type":"eck","ecs.version":"1.4.0","iteration":"3","namespace":"logging","logstash_name":"main"}
{"log.level":"info","@timestamp":"2024-04-05T11:15:26.437Z","log.logger":"logstash-controller","message":"Ending reconciliation run","service.version":"2.12.1+a56215f7","service.type":"eck","ecs.version":"1.4.0","iteration":"20","namespace":"logging","logstash_name":"main","took":0.026232342}
{"log.level":"error","@timestamp":"2024-04-05T11:15:26.448Z","log.logger":"manager.eck-operator","message":"Reconciler error","service.version":"2.12.1+a56215f7","service.type":"eck","ecs.version":"1.4.0","controller":"logstash-controller","object":{"name":"main","namespace":"logging"},"namespace":"logging","name":"main","reconcileID":"fd0c79d7-32a7-4846-bada-3e8afd619e62","error":"Service \"main-ls-udp\" is invalid: spec.loadBalancerClass: Invalid value: \"null\": may not change once set","errorCauses":[{"error":"Service \"main-ls-udp\" is invalid: spec.loadBalancerClass: Invalid value: \"null\": may not change once set"}],"error.stack_trace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:227"}
{"log.level":"info","@timestamp":"2024-04-05T11:15:26.523Z","log.logger":"logstash-es","message":"Ending reconciliation run","service.version":"2.12.1+a56215f7","service.type":"eck","ecs.version":"1.4.0","iteration":"3","namespace":"logging","logstash_name":"main","took":0.086298936}
```

preventing any further reconciliation (i.e. pipelines changes was not reflected in the secrets). Since the error was silent (pod not crashing etc), it took a while to get noticed. 

In order to fix the issue I had to explicitely define the `loadBalancerClass` field
```
  services:
    - name: udp
      service:
        spec:
          type: LoadBalancer
          loadBalancerClass: service.k8s.aws/nlb
          ports:
            - port: 12201
              name: "filebeat"
              protocol: UDP
              targetPort: 12201
```

AFAIK, this is not a required field, so the lack of it should not prevent the creation of the service. 

**What did you see instead? Under which circumstances?**

**Environment**

* ECK version:

	2.12.1

* Kubernetes information:
AWS
```
Server Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.10-eks-508b6b3", GitCommit:"e99f7c75641f738090d483d988dc4a70001e01cf", GitTreeState:"clean", BuildDate:"2024-01-29T20:59:05Z", GoVersion:"go1.20.13", Compiler:"gc", Platform:"linux/amd64"}
```
