### ISSUE TITLE
Feature request: Beats predefined role permissions compatibility with ECS guidelines

### ISSUE THREAD

**Issue by haam3r** [elastic/cloud-on-k8s#7692]
### Context

The Elastic Common Schema, besides field names and types, also defines a [common index naming schema](https://www.elastic.co/guide/en/ecs/8.13/ecs-data_stream.html) as part of the `data_stream` fields definition.
Elastic has previously published a blog post on this here: https://www.elastic.co/blog/an-introduction-to-the-elastic-data-stream-naming-scheme
These index naming conventions are also followed by Elastic Agent integrations. With the current ECS versions the definition for `data_stream.type` [states](https://www.elastic.co/guide/en/ecs/8.13/ecs-data_stream.html#field-data-stream-type):

> Currently allowed values are "logs" and "metrics". We expect to also add "traces" and "synthetics" in the near future.

### Current problem

Currently the predefined roles definition for beats [here](https://github.com/elastic/cloud-on-k8s/blob/c65eeafc65342d77becb83c6f9d81be14cd0da0f/pkg/controller/elasticsearch/user/roles.go#L203) sets the beats user role to allow index permissions only for that beat types name e.g. `filebeat-*`. This means using ECS compliant index names with beats requires custom role permissions overrides, which are further complicated with the versioning implemented for the beats i.e. overriding that role can break during future cluster upgrades.
Meanwhile logstash already has a predefined role that allows creating indexes with the `logs-*` prefix.

### Proposed solution

Duplicate the current index permissions for `*beat-*`to `logs-*` here: https://github.com/elastic/cloud-on-k8s/blob/c65eeafc65342d77becb83c6f9d81be14cd0da0f/pkg/controller/elasticsearch/user/roles.go#L203

An example on how the defined role could look like:

```
eck_beat_es_filebeat_role_v77:
    cluster:
        - monitor
        - manage_ilm
        - manage_ml
        - read_ilm
        - cluster:admin/ingest/pipeline/get
    indices:
        - names:
            - filebeat-*
            - logs-*
          privileges:
            - manage
            - read
            - create_doc
            - view_index_metadata
            - create_index
    applications: []
```

Would this be a change the maintainers find acceptable? If so I can raise a PR to implement the change.
