### ISSUE TITLE
Heartbeat Openshift specific documentation needs an update?

### ISSUE THREAD

**Issue by mmentges** [elastic/cloud-on-k8s#7707]
## Documentation Update Suggestion
**What did you do?**
I tried to get Heartbeat running in an Azure Redhat Openshift environment for quiet some time and different Openshift versions with more or less effort.
Yesterday I finally got it running. I followed the official documentation https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-openshift-beats.html but it never worked out. The service account with the privleged scc is not enough, at least for me. The finally working configuration is below. 
**What did you expect to see?**
I expected to see a running heatbeat pod without failing
**What did you see instead? Under which circumstances?**
A failing pod with permission issues
**Environment**

* ECK version:

	ECK 2.11 - Heartbeat 8.12.1 (and all other Images)

* Kubernetes information:

	* Azure Redhat Openshift 4.12.47
```
$ kubectl version

Server Version: v1.25.16+5c97f5b

```

* Working Resource definition:
```
  deployment:
    replicas: 1
    podTemplate:
      spec:
        containers:
        - name: heartbeat
          securityContext:
            capabilities:
              add: ["NET_RAW", "SYS_CHROOT"]
        serviceAccountName: heartbeat
        securityContext:
          runAsUser: 0
        volumes:
          - name: beat-data
            emptyDir: {}
```

* Error Logs without the added capabilities:
```
/usr/local/bin/docker-entrypoint: line 8: /usr/share/heartbeat/heartbeat: Operation not permitted
```

Not sure if it is only my specific environment or does the documentation need an update?
