### ISSUE TITLE
[eck-operator] No possibility to configure custom SM labels, interval and etc

### ISSUE THREAD

**Issue by kseniyashaydurova** [elastic/cloud-on-k8s#7717]
## Proposal

Pls add possibility to configure custom ServiceMonitor parameters for eck-operator. Current HELM chart provides possibility to define prometheus ServiceMonitor params - https://github.com/elastic/cloud-on-k8s/blob/main/deploy/eck-operator/values.yaml#L323 But in reality it allows to configure only its `namespace` and nothing else - https://github.com/elastic/cloud-on-k8s/blob/main/deploy/eck-operator/templates/serviceMonitor.yaml#L6

![image](https://github.com/elastic/cloud-on-k8s/assets/26448672/54f499a5-7fb7-44af-8005-5e90d408e46a)

**Use case. Why is this important?**

Currently we can't configure SM interval and what is more important to add custom labels and annotations. Adding custom labels is useful on `eck-operator + prometheus` integration, cause it needs a `release` label to be passed. Otherwise prometheus won't add SM as target.

![image](https://github.com/elastic/cloud-on-k8s/assets/26448672/182fa88d-7042-4bc6-9ec9-9690af8cf47d)

**Comment by maorojloo** [comment]
The ECK operator chart allows configuring settings such as:

```yaml
serviceMonitor:
  enabled: true
  namespace: elastic-system
  insecureSkipVerify: true
```

However, there is currently no way to add custom metadata labels or annotations to the generated `ServiceMonitor`.

For example, we need:

```yaml
serviceMonitor:
  labels:
    release: kube-prometheus-stack
```

Our centrally managed Prometheus installation selects `ServiceMonitor` resources using:

```yaml
serviceMonitorSelector:
  matchLabels:
    release: kube-prometheus-stack
```

The ECK 3.5.0 chart ignores `serviceMonitor.labels`, and the rendered resource only contains the standard ECK labels:

```yaml
metadata:
  labels:
    app.kubernetes.io/instance: elastic-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: elastic-operator
    app.kubernetes.io/version: 3.5.0
    helm.sh/chart: eck-operator-3.5.0
```

As a result, the generated `ServiceMonitor` is valid but is not discovered by Prometheus.

We cannot modify the centrally managed Prometheus selector. Our current workaround is to create and maintain a second `ServiceMonitor` with:

```yaml
metadata:
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - elastic-system
  selector:
    matchLabels:
      app.kubernetes.io/instance: elastic-operator
      app.kubernetes.io/name: elastic-operator-metrics-service
```

It would be much cleaner if the ECK Helm chart supported custom metadata:

```yaml
serviceMonitor:
  labels:
    release: kube-prometheus-stack
  annotations: {}
```

The template could render these values approximately as follows:

```yaml
metadata:
  labels:
    {{- include "eck-operator.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
```

Supporting custom endpoint settings such as `interval` and `scrapeTimeout` would also be useful, but custom labels are the immediate requirement.

### Environment

* ECK operator Helm chart: `3.5.0`
* Secure operator metrics: enabled
* Prometheus integration: Prometheus Operator / `ServiceMonitor`
