### ISSUE TITLE
[Elasticsearch] - double containers with use podTemplate.spec.containers

### ISSUE THREAD

**Issue by dacriper** [elastic/cloud-on-k8s#7721]
ECK version: 2.11.1
Kubernetes information: On premise
kubernetes version: v1.24.2
reference: https://www.elastic.co/guide/en/cloud-on-k8s/2.11/k8s-managing-compute-resources.html

Hello everyone..

 I have the following problem. 
When I deploy Elasticsearch with the configuration `spec.nodeSets.podTemplate.spec.containers` to set the resources of the pod, I find that two pods are created for each desired count. 

This is my Elasticsearch configuration
```yml
[....]
spec:
  version: 8.12.2
  nodeSets:
  - name: test
    count: 3
    podTemplate:
      metadata:
        labels:
          app: elastic
          release: 'eck-ob-test'
          chart: "eck-observability"
      spec:
        containers:
        - name: es
          image: 'docker.elastic.co/elasticsearch/elasticsearch:8.12.2'
          resources:
            requests:
              memory: 100Gi
              cpu: 10
            limits:
              memory: 100Gi
```
This is the capture from rancher. While the red indicates taint problems, they have already been resolved by adding tolerations. The issue I'm reporting is in the 'Ready' column showing 0/2.
![image](https://github.com/elastic/cloud-on-k8s/assets/49571488/35bce8e9-e0ee-4d8b-b23d-2677748b9f3b)

In the case where I deploy without `containers` in `spec.nodeSets.podTemplate.spec.containers`, only one pod is deployed as desired.

What could be causing the issues?

This is my template.

```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: eck-observability
  namespace: eck8-ob-test
  labels:
    release: 'eck-ob-test'
    chart: "eck-observability"
    entorno: test
  annotations:
    esMajorVersion: '8'
spec:
  version: 8.12.2
  nodeSets:
  - name: test
    count: 3
    podTemplate:
      metadata:
        labels:
          app: elastic
          release: 'eck-ob-test'
          chart: "eck-observability"
      spec:
        containers:
        - name: es
          image: 'docker.elastic.co/elasticsearch/elasticsearch:8.12.2'
          resources:
            requests:
              memory: 100Gi
              cpu: 10
            limits:
              memory: 100Gi
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
        labels:
          release: "eck-ob-test"
          chart: "eck-observability"
          app: "eck-observability"
          entorno: test
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 2Ti
        storageClassName: oci-bv
```
