### ISSUE TITLE
Logstash StatefulSet initContainers command is not properly reconciliated

### ISSUE THREAD

**Issue by Kiliandeca** [elastic/cloud-on-k8s#7742]
## Bug Report
**What did you do?**
I recently upgraded ECK from version `2.11.1` to `2.12.1`.

**What did you expect to see?**
I expected the upgrade to work transparently.

**What did you see instead? Under which circumstances?**
My new Logstash pods being rolled out started to fail with the following error message:
```
Your settings are invalid. Reason: File "/usr/share/logstash/config/api_keystore.p12" must exist but was not found.
```

After investigating what could be root cause I found out it's related to this change https://github.com/elastic/cloud-on-k8s/pull/7408
To summarize what I think is happening, the [PR properly changed](https://github.com/elastic/cloud-on-k8s/pull/7408/files#diff-000e81cb01c6f6b546ab205bc72599d2cc662ddcb8c5df9106eb7a2dd316c25aR26-R39) the `initContainers` to generate a Keystore for Logstash so it would not be breaking but my Statefulset `initContainers` didn't include the new script it was stuck on the old script which explain why my pod is failing.

In the end, I solved my problem by deleting the Logstash Statefulset without deleting the pods that were still running if this can help anyone. The operator immediately recreated the Statefulset with the new `initContainers` script as expected.
```
kubectl delete statefulset mylogstash-ls --cascade=orphan
```

I would expect ECK to update the `initContainers` command script during the reconciliation and I think that's a bug? 
Here's the instructions to reproduce this behavior:
- Creates a Logstash resource and wait for it to be deployed
- Manually update the Statefulset `initContainers` command script by adding anything
- The ECK operator never replace the change you made

```
apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: quickstart
spec:
  count: 1
  version: 8.13.2
  pipelines:
    - pipeline.id: main
      config.string: |
        input {
          beats {
            port => 5044
          }
        }
  services:
    - name: beats
      service:
        spec:
          type: NodePort
          ports:
            - port: 5044
              name: "filebeat"
              protocol: TCP
              targetPort: 5044
```

`quickstart-ls` Statefulset:
```
      initContainers:
        - name: logstash-internal-init-config
          image: docker.elastic.co/logstash/logstash:8.13.2
          command:
            - /usr/bin/env
            - bash
            - '-c'
            - "#!/usr/bin/env bash\nset -eu\n\necho 'this should be replaced in the next reconciliation'\n\ninit_config_initialized_f...
 ```

**Environment**

* ECK version:

	2.12.1

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* Cloud: AKS
	
	for each of them please give us the version you are using
```
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"28", GitVersion:"v1.28.5", GitCommit:"05f2dca83369807327c976b24846de8687923cb6", GitTreeState:"clean", BuildDate:"2024-04-12T23:22:53Z", GoVersion:"go1.20.12", Compiler:"gc", Platform:"linux/amd64"}
```
