### ISSUE TITLE
Hardened Security Context for Kibana

### ISSUE THREAD

**Issue by naemono** [elastic/cloud-on-k8s#7787]
similar to #6703, I think we should investigate setting a default security context for Kibana as well.

The following seems to work fine with (at least) newer versions of Kibana:
```yaml
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  podTemplate:
    spec:
      containers:
      - name: kibana
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsUser: 1000
          runAsGroup: 1000
      securityContext:
        fsGroup: 1000
  version: 8.13.2
```

Things to address/test:
- [ ] Does this work in previous versions of 8.x?
- [ ] Does this work in 7.x?
