### ISSUE TITLE
opentelemetry collector -> APM server 401 error

### ISSUE THREAD

**Issue by kobayashita** [elastic/cloud-on-k8s#7823]
## Bug Report
**What did you do?**

I tried to connect opentelemetry collector -> APM server.

**What did you expect to see?**

I can connect and check the trace information on kibana.

**What did you see instead? Under which circumstances?**

cannot connect due to 401 error
"http.response.status_code":401,"error.message":"authentication failed"

**Environment**

* ECK version:

image version
- apm-server:8.13.0
- opentelemetry-collector-k8s:0.100.0

I use the following helm

```
- name: eck-stack
  version: 0.10.0 
  repository: "https://helm.elastic.co"
```
```
- name: opentelemetry-collector
  version: "0.91.0"
  repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"
```
* Kubernetes information:

EKS
	
	for each of them please give us the version you are using

k8s version
```
Client Version: v1.29.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.9-eks-036c24b
```

* Resource definition:
```
apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-server
  labels:
    helm.sh/chart: eck-apm-server-0.10.0
    app.kubernetes.io/name: eck-apm-server
    app.kubernetes.io/instance: cluster
    app.kubernetes.io/managed-by: Helm
  annotations:
    eck.k8s.elastic.co/license: basic
spec:
  version: 8.13.0
  count: 1
  config:
    logging.level: debug
  http:
    service:
      spec:
        ports:
        - name: http
          port: 8200
          targetPort: 8200
    tls:
      selfSignedCertificate:
        disabled: true
  elasticsearchRef:
    name: elasticsearch
  kibanaRef:
    name: kibana
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elk-ingress

spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - example.com
      secretName: apm-tls-cert
  rules:
  - host: example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: apm-server-apm-http
            port:
              number: 8200
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opentelemetry-collector
  namespace: cluster
  labels:
    helm.sh/chart: opentelemetry-collector-0.91.0
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/instance: cluster
    app.kubernetes.io/version: "0.100.0"
    app.kubernetes.io/managed-by: Helm
    
data:
  relay: |
    exporters:
      debug:
        verbosity: detailed
      otlphttp/elastic:
        endpoint: ${env:ELASTIC_APM_ENDPOINT}:443
        headers:
          Authorization: Bearer ${env:ELASTIC_APM_SECRET_TOKEN}
    extensions:
      health_check:
...
```
env
|key|value|
|-|-|
|ELASTIC_APM_ENDPOINT|example.com|
|ELASTIC_APM_SECRET_TOKEN|MY_SECRET|

* Logs:
```
{"log.level":"error","@timestamp":"2024-05-17T07:48:54.283Z","log.logger":"request","log.origin":{"function":"github.com/elastic/apm-server/internal/beater/api.apmMiddleware.LogMiddleware.func1.1","file.name":"middleware/log_middleware.go","file.line":59},"message":"authentication failed","service.name":"apm-server","url.original":"/v1/traces","http.request.method":"POST","user_agent.original":"OpenTelemetry Collector for Kubernetes/0.100.0 (linux/amd64)","source.address":"10.0.223.18","http.request.id":"a8950466-8c75-4b7a-84db-7a3cccfba2b2","event.duration":108680,"http.request.body.bytes":1356,"http.response.status_code":401,"error.message":"authentication failed","ecs.version":"1.6.0"}
```
I set according to the following document.

https://www.elastic.co/guide/en/observability/current/apm-open-telemetry-direct.html

APM settings are default except for the following

APM setting(Edit Elastic APM integration)

|key|value|
|-|-|
|serverconfiguration.URL|example.com:443|
|API key for agent authentication|ON|
|Secret token|MY_SECRET|

**Comment by heidihe2024** [comment]
i met the same 401 error when I'm try to send data into apm-server ingress

**Comment by renzedj** [comment]
Same issue here, using Elastic Cloud APM.

We didn't find this bug report on our first search, so we found the following generates the 401 error:

```
curl "https://my-apm.elastic-cloud.com/v1/traces" -H "authorization: Bearer ${MY_APM_TOKEN}"
```

But this does not:

```
curl "https://my-apm.elastic-cloud.com/" -H "authorization: Bearer ${MY_APM_TOKEN}"
```

When we override the endpoint with the above in the otel configuration, we do not get any errors, but we also do not see any data coming into Elastic APM.

**Comment by renzedj** [comment]
Any progress on this? I have some users who need this functionality.

**Comment by naemono** [comment]
I cannot replicate this issue, although I don't have the otel-collector setup, I can verify data being accepted through the Loadbalancer to a configured apm-server.

Full values file used:
```
eck-elasticsearch:
  nodeSets:
    - name: default
      count: 3
      config:
        node.store.allow_mmap: false
        node.roles: ["master", "data", "ingest"]
      podTemplate:
        metadata:
          labels:
            app: elasticsearch
            version: 0.0.1
eck-kibana:
  enabled: true
  podTemplate:
    metadata:
      labels:
        app: kibana
        version: 0.0.1
eck-apm-server:
  enabled: true
  config:
    apm-server.auth.secret_token: --random-data--
  http:
    service:
      metadata:
        annotations:
          cloud.google.com/neg: '{"ingress": true}'
          cloud.google.com/app-protocols: '{"https":"HTTPS"}'
      spec:
        ports:
        - name: http
          port: 8200
          targetPort: 8200
    tls:
      selfSignedCertificate:
        disabled: true
  elasticsearchRef:
    name: elasticsearch
  kibanaRef:
    name: eck-stack-eck-kibana
  podTemplate:
    metadata:
      labels:
        app: apm-server
        version: 0.0.1
```

Installed with
```
helm upgrade -i eck-stack elastic-helm-charts/eck-stack -n elastic --create-namespace -f ./deploy/eck-stack/temp-values.yaml --reuse-values
```

Ingress configuration:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elk-ingress
  namespace: elastic
spec:
  rules:
  - host: apm.company.dev
    http:
      paths:
      - backend:
          service:
            name: eck-stack-eck-apm-server-apm-http
            port:
              number: 8200
        path: /*
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - apm.company.dev
    secretName: eck-stack-eck-kibana-kb-http-certs-internal
```

Default endpoint with valid authentication

```
❯ curl -k -X GET "https://apm.company.dev/" -H "Authorization: Bearer base-64-encoded-apm-server.auth.secret_token"
{
  "build_date": "2025-03-25T15:32:57Z",
  "build_sha": "8a80b42fe664d49038342d721bb6bc4b25f52e47",
  "publish_ready": true,
  "version": "9.0.0"
}
```

Sending test data:

```
curl -vk -X POST "https://apm.company.dev/intake/v2/events" \
  -H "Authorization: Bearer --cut--" \
  -H "Content-Type: application/x-ndjson" \
  -d $'{"metadata":{"service":{"name":"test-service","environment":"development","agent":{"name":"generic","version":"1.0.0"}}}}\n{"transaction":{"id":"abc123","trace_id":"def456","parent_id":null,"name":"test-transaction","type":"request","duration":100.5,"timestamp":"2025-07-02T13:14:00.000Z","result":"success","span_count":{"started":0,"dropped":0},"context":{"system":{"hostname":"test-host"}}}}\n'

< HTTP/2 202
< x-content-type-options: nosniff
< date: Wed, 02 Jul 2025 18:35:40 GMT
< content-length: 0
< via: 1.1 google

```

3 questions:
1. How was the apm-server token configured? Through the secret referenced above?
2. How do you translate this apm-server token into the Bearer token?
3. I see one user uses `/v1` endpoint, but I'm using the `v2` endpoints. The `/v1` endpoints would just give a 404 for me.

I suspect this is a configuration issue with either the nginx ingress itself, or some issue translating the token to a base64 encoded bearer token...

Either way this doesn't appear to be an issue with the eck operator itself, so I'm going to close this for now until further information is provided showing that it's an issue with eck itself.
