### ISSUE TITLE
Delayed Elasticsearch Pod Initialization

### ISSUE THREAD

**Issue by fkaksa** [elastic/cloud-on-k8s#7835]
**Description:**
I am experiencing a noticeable delay in the creation of Elasticsearch pods on OpenShift clusters. Each pod is taking approximately 10 minutes to initialize after the `Elasticsearch` Custom Resource (CR) has been created. In the cluster, there are 10+ `Elasticsearch` CRs.

**Cluster Details:**
- **OpenShift Version:** 4.15.13
- **Infrastructure Provider:** VSphere
- **Storage Provisioner:** cephfs.csi.ceph.com
- **Elasticsearch Version:** 2.12.1

**Subscription Configuration:**
```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: elasticsearch-eck-operator-certified
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: elasticsearch-eck-operator-certified
  source: certified-operators
  sourceNamespace: openshift-marketplace
```

**Steps to Reproduce:**
1. Create multiple `Elasticsearch` CRs (10+).
2. Monitor the time taken for each Elasticsearch pod to initialize.

**Issue Resolution Attempt:**
I was able to solve the problem by configuring `max-concurrent-reconciles` to a value of 20+. 

**Questions:**
1. Is this normal behavior, or is it indicative of a bug?
2. Which metrics can help me determine the underlying issue?

**Expected Behavior:**
Elasticsearch pods should initialize in a timely manner, significantly faster than the observed 10 minutes per pod.
