### ISSUE TITLE
Custom Logstash service labels are not preserved

### ISSUE THREAD

**Issue by lpeter91** [elastic/cloud-on-k8s#7855]
**What did you do?**

I tried to add custom labels to a [Logstash service definition](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-logstash-configuration.html#k8s-logstash-expose-services) (see below how).

**What did you expect to see?**

I expected to see the defined labels on the created service resource.

**What did you see instead? Under which circumstances?**

The custom labels were replaced by the ones generated by the operator.

**Environment**

* ECK version: 2.12.1

* Kubernetes information: On premise, Kubespary v2.25.0.

* Partial resource definition:

```
apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: "logstash"
spec:
  # Actual spec cut for brevity
  services:
    - name: inputs
      service:
        metadata:
          annotations:
            io.cilium/lb-ipam-ips: "1.2.3.4"
          labels:
            io.cilium/address-pool: public
        spec:
          type: LoadBalancer
          allocateLoadBalancerNodePorts: false
          ports:
            - port: 5044
              name: agent
              protocol: TCP
              targetPort: 5044
            - port: 9800
              name: logstash
              protocol: TCP
              targetPort: 9800

```

**Comments**
The custom annotations are preserved, but the labels are replaced. I think here:

https://github.com/elastic/cloud-on-k8s/blob/v2.12.1/pkg/controller/logstash/service.go#L72-L74

I think merging with user-defined labels would be preferrable.
