### ISSUE TITLE
How do I specify the elastic user's password at deployment time

### ISSUE THREAD

**Issue by LiTeng51** [elastic/cloud-on-k8s#7928]
```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: es
  labels:
    app: elasticsearch
spec:
  version: 6.6.6
  image: elasticsearch:6.6.6
  nodeSets:
  - name: master
    count: 1
    config:
      node.roles: ["master", "ml", "data", "ingest",]
      node.store.allow_mmap: false
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          env:
          - name: ELASTIC_PASSWORD
            value: "elastic"
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: supermap-nfs-storage```

**Comment by thbkrkr** [comment]
Please note that we discourage the use of the elastic user for any productive use. For some use cases it also no longer holds the necessary permissions (e.g. stack monitoring).

> How do I specify the elastic user's password at deployment time?

You can use File realm to set the elastic user's password. It's mentioned in the 'Creating custom user > File realm' section of the 'Users and roles' doc: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-users-and-roles.html#k8s_file_realm

> If you specify the password for the elastic user through such a basic authentication secret then the secret holding the password described in [Default elastic user](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-users-and-roles.html#k8s-default-elastic-user) will not be created by the operator.

Example:
```yaml
cat <<EOF | kubectl apply -f -
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: ploum
spec:
  version: 8.14.2
  auth:
    fileRealm:
    - secretName: elastic-user-password
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
---
apiVersion: v1
kind: Secret
metadata:
  name: elastic-user-password
type: kubernetes.io/basic-auth
stringData:
  username: elastic
  password: mypassword
  roles: superuser
EOF
```
