### ISSUE TITLE
Support api-key - elasticsearchRefs - monitoring + output

### ISSUE THREAD

**Issue by syepes** [elastic/cloud-on-k8s#7942]
## Proposal

It would be great if we could also use the `api-key` authentication method for the external Elasticsearch destinations and also the monitoring ones.
This would simplify the usage and its deployment.

https://github.com/elastic/cloud-on-k8s/blob/0d18fcb14913c0ab749edf53a423ac6c2408340d/config/crds/v1/all-crds.yaml#L241

## Details:

* ECK version: 2.13

* Resource definition:

```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: ext-es
stringData:
  url: https://XXXXX.elastic-cloud.com:9243
  api-key: XXXX
---
apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: logstash
spec:
  count: 1
  version: 8.14.3
  config:
    log.level: info
  elasticsearchRefs:
    - clusterName: ext-es
      secretName: ext-es
  monitoring:
    metrics:
      elasticsearchRefs:
        - secretName: ext-es
    logs:
      elasticsearchRefs:
        - secretName: ext-es
  podTemplate:
    spec:
      containers:
        - name: logstash
---
```
