### ISSUE TITLE
Discrepancy between Logstash Helm Chart and docs for pipelinesRef

### ISSUE THREAD

**Issue by wescran** [elastic/cloud-on-k8s#7957]
## Bug Report
**What did you do?**
I have a found a discrepancy between the helm chart for Logstash and what the documentation describes for configuring pipelines using `pipelinesRef`

**What did you expect to see?**
As per the [Logstash helm chart](https://github.com/elastic/cloud-on-k8s/blob/main/deploy/eck-stack/charts/eck-logstash/values.yaml#L82-L84]), the `pipelinesRef` object shows that the format should be:
```yaml
pipelinesRef:
  secretRef:
    secretName: <secret>
```
However the [Logstash ECK docs](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-logstash-configuration.html#k8s-logstash-pipelines) define the correct usage.
```yaml
  pipelinesRef:
    secretName: <secret>
```
I expected to see some sort of error when using the incorrect format.

**What did you see instead? Under which circumstances?**
Nothing. I was confused as to why my logstash deployment was not using my configured pipelines. I discovered there was an error when I looked at the logstash resource. It only showed an empty object for `pipelinesRef`
```yaml
spec:
  count: 1
  elasticsearchRefs:
  - clusterName: eck
    name: elasticsearch
  monitoring:
    logs: {}
    metrics: {}
  pipelinesRef: {}
```
I looked at the [template for the logstash helm chart](https://github.com/elastic/cloud-on-k8s/blob/main/deploy/eck-stack/charts/eck-logstash/templates/logstash.yaml#L34-L37), and it technically accepts any yaml after the `pipelinesRef` key
```yaml
  {{- with .Values.pipelinesRef }}
  pipelinesRef:
    {{- toYaml . | nindent 4 }}
  {{- end }}
```
And the [test](https://github.com/elastic/cloud-on-k8s/blob/main/deploy/eck-stack/charts/eck-logstash/templates/tests/logstash_test.yaml#L160-L168) fails to catch this as well as it uses the incorrect definition.
```yaml
  - it: should render pipelinesRef properly
    set:
      pipelinesRef:
        secretRef:
          secretName: pipelineLogstashSecretName
    asserts:
      - equal:
          path: spec.pipelinesRef.secretRef.secretName
          value: pipelineLogstashSecretName
```
