### ISSUE TITLE
Elastic Agent in ECK has no option to output to Logstash created by ECK. 

### ISSUE THREAD

**Issue by fxdgear** [elastic/cloud-on-k8s#7968]
## Allow ECK deployed Elastic Agents to output to a Logstash Ref

I'm trying to configure my Elastic Agents to output to Logstash so that I can do some logstashy things before sending the data to Elasticsearch as well as some other locations. 

I can't figure out how to configure the Elastic Agent CRD to reference the output to a Logstash instance deployed by ECK.

**Comment by strawgate** [comment]
I believe the CRD only supports dynamic output configuration using an ElasticsearchRef but you can always setup a manual output -- instructions here https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-elastic-agent-configuration.html

> The outputs can also be set manually. To do that, remove the elasticsearchRefs element from the specification and include an appropriate output configuration in the config, or indirectly through the configRef mechanism.

```
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: quickstart
spec:
  version: 8.15.3
  daemonSet:
    podTemplate:
      spec:
        securityContext:
          runAsUser: 0
  config:
    outputs:
      default:
        type: elasticsearch
        hosts:
          - "https://my-custom-elasticsearch-cluster.cloud.elastic.co:9243"
        password: ES_PASSWORD
        username: ES_USER
...
```

Another option would be to enroll them in Fleet management and configure the Logstash output in Fleet
