### ISSUE TITLE
Create an E2E test for accessing ES within a pod in the cluster

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#798]
This will make sure we can access the cluster using any standard ES library, while mounting password and CA secrets into a pod.
Basically what people would have to do in order to interact with Elasticsearch in a programatic way from the k8s cluster.

I think we can simply use a k8s Job in one of the e2e test, to spin up a pod requesting Elasticsearch with the official Python lib:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: python-client-test
spec:
  template:
    metadata:
      name: python-client-test
    spec:
      containers:
        - name: python-client-test
          image: python:latest
          command: ["bash"]
          args:
          - -c
          - |
            pip install elasticsearch && python -c '
            import os
            from elasticsearch import Elasticsearch
            print("starting python client test job")
            # build an ES client with TLS verification enabled
            es = Elasticsearch(
               [os.environ["ES_HOST"]],
               http_auth=(os.environ["ES_USER"], os.environ["ES_PASSWORD"]),
               scheme="https",
               port=int(os.environ["ES_PORT"]),
               use_ssl=True,
               verify_certs=True,
               ca_certs="/mnt/ca/ca.pem",
            )
            health = es.cat.health()
            print(health)
            print("python client test job successful")
            '
          env:
          - name: ES_HOST
            value: elasticsearch-sample-es
          - name: ES_PORT
            value: "9200"
          - name: ES_USER
            value: elastic
          - name: ES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: elasticsearch-sample-elastic-user
                key: elastic
          volumeMounts:
          - name: ca
            mountPath: "/mnt/ca"
            readOnly: true
      volumes:
        - name: ca
          secret:
            secretName: elasticsearch-sample-ca
      restartPolicy: Never
```

**Comment by sebgl** [comment]
Updated sample job with newer naming conventions:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: python-client-test
spec:
  template:
    metadata:
      name: python-client-test
    spec:
      containers:
        - name: python-client-test
          image: python:latest
          command: ["bash"]
          args:
          - -c
          - |
            pip install elasticsearch && python -c '
            import os
            from elasticsearch import Elasticsearch
            print("starting python client test job")
            # build an ES client with TLS verification enabled
            es = Elasticsearch(
               [os.environ["ES_HOST"]],
               http_auth=(os.environ["ES_USER"], os.environ["ES_PASSWORD"]),
               scheme="https",
               port=int(os.environ["ES_PORT"]),
               use_ssl=True,
               verify_certs=True,
               ca_certs="/mnt/certs/tls.crt",
            )
            health = es.cat.health()
            print(health)
            print("python client test job successful")
            '
          env:
          - name: ES_HOST
            value: quickstart-es-http
          - name: ES_PORT
            value: "9200"
          - name: ES_USER
            value: elastic
          - name: ES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: quickstart-es-elastic-user
                key: elastic
          volumeMounts:
          - name: certs
            mountPath: "/mnt/certs"
            readOnly: true
      volumes:
        - name: certs
          secret:
            secretName: quickstart-es-http-certs-public
      restartPolicy: Never
```
