### ISSUE TITLE
Handle overrides for Readiness probe with the new readiness port feature

### ISSUE THREAD

**Issue by kvalliyurnatt** [elastic/cloud-on-k8s#8006]
We added a new way to do the readiness probe, by using a tcp port. When this is enabled we remove the credentials that were added as ENV and used for the old readiness probe from the pods. So when there are overrides present in the spec that is pointing to the old script, this script does not have the credentials in place to succeed, we need a way to handle this.

**Comment by pebrc** [comment]
I think we should discuss whether this warrants a patch release

**Comment by kvalliyurnatt** [comment]
I feel like it does, since this is going to be hit any customer with an override trying to upgrade to 2.14

**Comment by akfav** [comment]
Hey folks we might be seeing this issue surface in one of our Infosec clusters. After upgrading to 2.14.0 and 8.15.0 one of clusters was not able to start up and noticed that the readiness probe environment variables are not set. 

There are more details here - https://github.com/elastic/seceng/issues/7672#issuecomment-2292205152

Here the config for the cluster:
- [ECK Chart](https://github.com/elastic/seceng/tree/master/kubernetes/epsilon/charts/eck)
- [Cluster values.yml](https://github.com/elastic/seceng/tree/master/kubernetes/dev/infosec-utilities-dev/opencti)

**Comment by naemono** [comment]
I can't disagree with releasing a patch, as we've had a customer report, and an internal report already of running into this issue.

**Comment by pebrc** [comment]
The argument against a patch release is that there is an easy to implement solution to the problem that moves customers configuration to the desired future-proof state. A patch release with the proposed fix of keeping the environment variables, keeps customers on a deprecated configuration for perpetuity.

**Comment by ibalat** [comment]
Hi, I have upgraded 2.14 and it uses new readiness script checks 8080 port. But, we use **9200** port for elasticsearch container. How can I customize the script or is there another solution to solve the problem? I had updated `readiness-port-script.sh` with old `readiness-probe-script.sh` but it is not working because of missing env. At last status, pod is **NotReady**.

**readiness-port-script.sh**: `nc -z -v -w5 127.0.0.1 8080 `

![Image](https://github.com/user-attachments/assets/52f4fb31-6d5c-489b-8ba3-acde7507f80a)

**Comment by fdmota** [comment]
I also ran into the same issue in all my elasticsearch clusters, so I decide to create a new cluster from scratch and the same is happening.
In my case, only the elected master is not binding to port 8080. All other nodes are fine. Also as soon as I restart the master node and another one takes over, the new master stops binding to port 8080 and when the old master comes back up it binds to port 8080 as expected.

So in conclusion, the probe is failing only for the node that is master.

here my configuration:
```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-test
  namespace: monitoring
spec:
  auth: {}
  http:
    service:
      metadata: {}
      spec: {}
    tls:
      certificate: {}
      selfSignedCertificate:
        disabled: true
  monitoring:
    logs: {}
    metrics: {}
  nodeSets:
  - config:
      node.roles:
      - master
      - remote_cluster_client
      node.store.allow_mmap: false
    count: 3
    name: master-nodes
    podTemplate:
      spec:
        containers:
        - env:
          - name: xpack.security.enabled
            value: "false"
          - name: READINESS_PROBE_PROTOCOL
            value: http
          - name: AWS_WEB_IDENTITY_TOKEN_FILE
            value: /usr/share/elasticsearch/config/repository-s3/aws-web-identity-token-file
          - name: AWS_ROLE_ARN
            value: arn:aws:iam::XXXXXXXXXXXX:role/dev-eck
          name: elasticsearch
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: "1"
              memory: 2Gi
          volumeMounts:
          - mountPath: /usr/share/elasticsearch/config/repository-s3
            name: aws-iam-token
        serviceAccountName: elasticsearch-test-aws-sa
        volumes:
        - name: aws-iam-token
          projected:
            sources:
            - serviceAccountToken:
                audience: sts.amazonaws.com
                expirationSeconds: 86400
                path: aws-web-identity-token-file
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: ebs-gp3-3000-125
  - config:
      node.roles:
      - data
      - ingest
      - ml
      - transform
      - remote_cluster_client
      node.store.allow_mmap: false
    count: 3
    name: worker-nodes
    podTemplate:
      spec:
        containers:
        - env:
          - name: xpack.security.enabled
            value: "false"
          - name: READINESS_PROBE_PROTOCOL
            value: http
          - name: AWS_WEB_IDENTITY_TOKEN_FILE
            value: /usr/share/elasticsearch/config/repository-s3/aws-web-identity-token-file
          - name: AWS_ROLE_ARN
            value: arn:aws:iam::XXXXXXXXXXXX:role/dev-eck
          name: elasticsearch
          resources:
            limits:
              cpu: "4"
              memory: 8Gi
            requests:
              cpu: "4"
              memory: 8Gi
          volumeMounts:
          - mountPath: /usr/share/elasticsearch/config/repository-s3
            name: aws-iam-token
        serviceAccountName: elasticsearch-test-aws-sa
        volumes:
        - name: aws-iam-token
          projected:
            sources:
            - serviceAccountToken:
                audience: sts.amazonaws.com
                expirationSeconds: 86400
                path: aws-web-identity-token-file
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 500Gi
        storageClassName: ebs-gp3-3000-125
  podDisruptionBudget:
    metadata: {}
    spec:
      minAvailable: 2
      selector:
        matchLabels:
          elasticsearch.k8s.elastic.co/cluster-name: elasticsearch-test
  transport:
    service:
      metadata: {}
      spec: {}
    tls:
      certificate: {}
      certificateAuthorities: {}
  updateStrategy:
    changeBudget: {}
  version: 8.11.0
```
