### ISSUE TITLE
Unable to output from logstash to elasticearch data hot nodes with full ssl enabled

### ISSUE THREAD

**Issue by octane100** [elastic/cloud-on-k8s#8031]
I am using ECK operator to manage my elasticsearch cluster and want to have a logstash instance which can output logs to it.

It works as expected if I use the basic elasticsearch service in elasticsearchRefs : 
```
apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: logstash
spec:
  elasticsearchRefs:
    - clusterName: eck
      name: elasticsearch
```

I am able to use this code in logstash output : 
```
output {
  elasticsearch {
    id                          => "output.elasticsearch(@target_index)"
    hosts                       => [ "${ECK_ES_HOSTS}" ]
    user                        => "${ECK_ES_USER}"
    password                    => "${ECK_ES_PASSWORD}"
    ssl_certificate_authorities => "${ECK_ES_SSL_CERTIFICATE_AUTHORITY}"
    ssl_verification_mode       => full
  }
```

But it's more difficult if I try to output only to data hot nodes (And avoid disturbing master dedicated nodes): 
```
apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: logstash
spec:
  elasticsearchRefs:
    - clusterName: eck
      name: elasticsearch
      serviceName: elasticsearch-es-hot
```

The certificate generated by the operator doesn't contain the name used by the elasticsearch-es-hot service in SAN field. I get the following error message if I keep **ssl_verification_mode** at **full** (it works if I set it to **none**) : 
```
Certificate for <elasticsearch-es-hot.elastic.svc> doesn't match any of the subject alternative names: [elasticsearch-es-http.elastic.es.local, elasticsearch-es-http, elasticsearch-es-http.elastic.svc, elasticsearch-es-http.elastic, elasticsearch-es-internal-http.elastic.svc, elasticsearch-es-internal-http.elastic, *.elasticsearch-es-masters.elastic.svc, *.elasticsearch-es-hot.elastic.svc, *.elasticsearch-es-warm.elastic.svc, *.elasticsearch-es-cold.elastic.svc]"}}
```
Shouldn't the certificate SAN contain ```elasticsearch-es-hot.elastic.svc``` instead of ```*.elasticsearch-es-hot.elastic.svc``` ?
