### ISSUE TITLE
Readiness probe not working with custom container port

### ISSUE THREAD

**Issue by ibalat** [elastic/cloud-on-k8s#8042]
Hi, I have upgraded 2.14 and it uses new readiness script checks 8080 port. But, we use 9200 port for elasticsearch container. How can I customize the script or is there another solution to solve the problem? I had updated readiness-port-script.sh with old readiness-probe-script.sh but it is not working because of missing env. At last status, pod is NotReady.

**readiness-port-script.sh**: `nc -z -v -w5 127.0.0.1 8080`

![Image](https://github.com/user-attachments/assets/69a96170-5bc4-429f-9916-393a7605962a)

Old version had used probe script but it is not working now because of missing environment variables ([#8009](https://github.com/elastic/cloud-on-k8s/pull/8009))
![Image](https://github.com/user-attachments/assets/eaca0707-996f-401e-8c8d-c7f295ac7b1f)

**Comment by ashuec90** [comment]
I am also facing this issue just after disabling the xpack.security.http.ssl.enabled. and the readiness probe is failing with connection error.
```nc: connect to 127.0.0.1 port 8080 (tcp) failed: Connection refused```

**Comment by pebrc** [comment]
@ibalat the container ports are irrelevant for the readiness check. It uses port 8080 on localhost. Don't update the readiness port script, don't override the readiness probe.  See the guidance in our docs https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-readiness.html#k8s_elasticsearch_versions_8_2_0_and_later

@ashuec90 this likely just means that your Elasticsearch pod is not ready. Check the logs.

**Comment by ibalat** [comment]
@pebrc but no exposed 8080 port in container, how it check non-exists port? 8080 check return connection refused

**Comment by Mason0920** [comment]
@pebrc 
[The document](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-readiness.html#k8s_elasticsearch_versions_8_2_0_and_later) says not to override the readiness probe, but I resolved the issue by overriding it as shown below.

```
        - name: elasticsearch
          readinessProbe:
            exec:
              command:
                - bash
                - -c
                - |
                  nc -z -v -w5 127.0.0.1 9200 #port change
```

**Comment by pebrc** [comment]
@Mason0920 this is not doing what you think it is doing and you are putting the safe operation of the ECK operator at risk with this change. 

Elasticsearch will respond on 9200 as soon as the process is running. A main motivation for this change was to make sure that we consider nodes only ready when they actually have joined the cluster. Checking 9200 does not guarantee that. See the the following issues for more context https://github.com/elastic/cloud-on-k8s/issues/916 and https://github.com/elastic/cloud-on-k8s/issues/5449

@ibalat 8080 does not need to be exposed as a container port because this is a `exec` probe that runs locally inside the runnig container and uses localhost as mentioned before.

**Comment by ibalat** [comment]
@pebrc yes, I don't need 8080 as exposed port but netstat output doesn't show 8080 port. I added outputs up comment. If 8080 port not exists, how can checkable? Am I missing something? Why 8080 port not exists in container :/

**Comment by ibalat** [comment]
@pebrc I have only data pod and this pod's container has not 8080 port. Okey, I am not waiting 8080 to see at exposed port list but at this situation, how can 8080 check is available? Am I missing something? And my cluster is green

![Image](https://github.com/user-attachments/assets/04281f58-2451-4a20-83c0-8f53ac6246d5)

![Image](https://github.com/user-attachments/assets/398d9844-10c5-4ab8-b677-90f9776216e9)

```
127.0.0.1:57592 - 127.0.0.1:9200
127.0.0.1:34228 - 127.0.0.1:9200
127.0.0.1:37662 - 127.0.0.1:9200
127.0.0.1:57608 - 127.0.0.1:9200
127.0.0.1:52186 - 127.0.0.1:9200
```

**Comment by ibalat** [comment]
sure, I can share.

**Elastic setup:**

```
resource "kubectl_manifest" "elasticsearch_dev" {
  yaml_body = file("${path.module}/config/elasticsearch/elasticsearch.yaml")
}
```

**elasticsearch.yaml**
```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata: 
  name: elasticsearch-dev
  namespace: elasticsearch
spec:
  version: 8.13.4
  nodeSets:
  - name: data
    count: 1
    config:
      node.store.allow_mmap: false
      xpack.security.enabled: false
      xpack.ml.enabled: false
      xpack.graph.enabled: false
      xpack.watcher.enabled: false
      bootstrap.memory_lock: true
    volumeClaimTemplates:
    - metadata: 
        name: elasticsearch-data
      spec: 
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: gp3
    podTemplate:
      spec: 
        containers:
        - name: elasticsearch
           resources: 
            requests: 
              memory: 2800Mi
              cpu: "1"
            limits: 
              memory: 2800Mi
              cpu: "1200m"
        nodeSelector:
            elasticsearch: green
        tolerations: 
        - key: elasticsearch
          value: green
          effect: NoSchedule
  http: 
    tls:
      selfSignedCertificate: 
        disabled: true
    service:
      spec: 
        type: NodePort
```

**ECK operator:**
```
eck_operator_helm_config = {
    max_history      = 3
    version          = "2.14.0"
    create_namespace = true
    values           = [file("${path.module}/config/eck/eck-operator.yaml")]
  }
```

**eck-operator.yaml**
```
image:
  pullPolicy: "Always"
```

**Comment by harveyjing** [comment]
Have the same problem. I ran three replicas. One pod is down because this readiness probe. `nc: connect to 127.0.0.1 port 8080 (tcp) failed: Connection refused`. I setuped with just two command. No other customizations.
```
helm install elastic-operator elastic/eck-operator -n elastic-stack --create-namespace --set=installCRDs=true

apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
  namespace: elastic-stack
spec:
  version: 8.15.0
  nodeSets:
  - name: default
    count: 3
    config:
      node.store.allow_mmap: false
```
According this post https://www.elastic.co/blog/red-elasticsearch-cluster-panic-no-longer, I got some sessage:
```
curl -u "elastic:$PASSWORD" -k "https://localhost:9200/_cluster/allocation/explain?pretty"
{
  "note" : "No shard was specified in the explain API request, so this response explains a randomly chosen unassigned shard. There may be other unassigned shards in this cluster which cannot be assigned for different reasons. It may not be possible to assign this shard until one of the other shards is assigned correctly. To explain the allocation of other shards (whether assigned or unassigned) you must specify the target shard in the request to this API.",
  "index" : ".ds-filebeat-8.15.0-2024.09.09-000001",
  "shard" : 0,
  "primary" : true,
  "current_state" : "unassigned",
  "unassigned_info" : {
    "reason" : "NODE_LEFT",
    "at" : "2024-09-12T02:15:15.456Z",
    "details" : "node_left [0IKKAc4kRZm2qfN40WlJVA]",
    "last_allocation_status" : "no_valid_shard_copy"
  },
  "can_allocate" : "no_valid_shard_copy",
  "allocate_explanation" : "Elasticsearch can't allocate this shard because all the copies of its data in the cluster are stale or corrupt. Elasticsearch will allocate this shard when a node containing a good copy of its data joins the cluster. If no such node is available, restore this index from a recent snapshot.",
  "node_allocation_decisions" : [
    {
      "node_id" : "9o1iHmAGTo-vcZs4s3SIew",
      "node_name" : "quickstart-es-default-2",
      "transport_address" : "10.244.1.78:9300",
      "node_attributes" : {
        "ml.allocated_processors_double" : "4.0",
        "ml.machine_memory" : "2147483648",
        "ml.config_version" : "12.0.0",
        "ml.max_jvm_size" : "1073741824",
        "ml.allocated_processors" : "4",
        "xpack.installed" : "true",
        "transform.config_version" : "10.0.0",
        "k8s_node_name" : "worker03"
      },
      "roles" : [
        "data",
        "data_cold",
        "data_content",
        "data_frozen",
        "data_hot",
        "data_warm",
        "ingest",
        "master",
        "ml",
        "remote_cluster_client",
        "transform"
      ],
      "node_decision" : "no",
      "store" : {
        "in_sync" : false,
        "allocation_id" : "28a5a2__RVyR_VUV0ahEVA"
      }
    },
    {
      "node_id" : "_kAiqcc0RwCOysr3fypbsA",
      "node_name" : "quickstart-es-default-1",
      "transport_address" : "10.244.3.238:9300",
      "node_attributes" : {
        "ml.allocated_processors_double" : "4.0",
        "ml.machine_memory" : "2147483648",
        "ml.config_version" : "12.0.0",
        "ml.max_jvm_size" : "1073741824",
        "ml.allocated_processors" : "4",
        "xpack.installed" : "true",
        "transform.config_version" : "10.0.0",
        "k8s_node_name" : "worker01"
      },
      "roles" : [
        "data",
        "data_cold",
        "data_content",
        "data_frozen",
        "data_hot",
        "data_warm",
        "ingest",
        "master",
        "ml",
        "remote_cluster_client",
        "transform"
      ],
      "node_decision" : "no",
      "store" : {
        "in_sync" : false,
        "allocation_id" : "auY6WVS9SJKipfWHRD2Xqg"
      }
    }
  ]
}
```

**Comment by harveyjing** [comment]
I found the root cause. After I restart the issue pod, I got the logs `Failed to load persistent cache`. And according this post https://opster.com/analysis/elasticsearch-failed-to-close-persistent-cache-index/, it mentioned some disk space clues. And I remeber that the initial PV size is only 1GB. After I increace the PV size. The pod is up and running!!!

**Comment by ibalat** [comment]
@harveyjing I don't have any disk or another problem and my cluster is green, everything is ok, no error messages, although, 8080 port is not exists. I added some cluster details below:

```
nc -z -v -w5 127.0.0.1 8080
nc: connect to 127.0.0.1 port 8080 (tcp) failed: Connection refused
```

`/_cluster/health?filter_path=status,*_shards`:
```
{"status":"green","active_primary_shards":1610,"active_shards":1999,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":0,"delayed_unassigned_shards":0}
```

**Comment by harveyjing** [comment]
![Image](https://github.com/user-attachments/assets/c8ca6c8c-df32-495f-aed9-ad3948b62882)
I can connect this port. My version is :
NAMESPACE       NAME         HEALTH   NODES   VERSION   PHASE   AGE
elastic-stack   quickstart   green    3       8.15.0    Ready   9d
@ibalat

**Comment by ibalat** [comment]
my version 8.13.4, but is the reason that, I don't know :/

**Comment by jjnunogarcia** [comment]
I'm experiencing the same issue when updating to 2.14.0, so I had to downgrade to 2.13.0, which seems to work.

**Comment by harveyjing** [comment]
Maybe the issue is related with resources limitation, your hardware.

**Comment by vanthome** [comment]
I had the same issue, for me version 8.15.1 did not even dare to open the port 8080 for health checking that's why they always failed. I have solved this in the same way as @Mason0920 suggested.

**Comment by maggieghamry** [comment]
Observing same issue `8.15.0`

**Comment by pebrc** [comment]
Please don't take this the wrong way but I am going to close this issue and block further comments. This is because this issue already causes a lot of confusion and creates the impression that there is a bug in ECK when at least to our current understanding and based on all the evidence brought forward in the discussion here there is not. If you have a new finding that indicates that there is indeed a bug in ECK you can always open a new issue.

Just to recap the main points for future readers coming here (and I will look into incorporating some if it in our docs):

### What does the following log statement mean?
```
nc: connect to 127.0.0.1 port 8080 (tcp) failed: Connection refused
``` 
It means Elasticsearch is not ready. There is no configuration error or similar, this is an expected log message.  It just means Elasticsearch has not reached the ready state. The reasons could be manifold @harveyjing for example mentioned not enough disk space.

### But 8080 is not exposed as a container port, how can this work?
It does not have to be because the kubelet runs `exec` readiness probes inside the container. No need to expose a port. 

### Regarding the OP
@ibalat in your example you turned `xpack.security.enabled` off. This is an [ECK managed setting](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-reserved-settings.html) that we don't recommend to change. Once you turn it on the readiness check will pass. However I admit that it seems odd that Elasticsearch does not report readiness when security is turned off. I will follow up with the Elasticsearch team to verify if this could be a bug in Elasticsearch itself.

**Comment by kunisen** [comment]
A little additional information to 8080 port:

### [1] It's a concept introduced by ES 

https://www.elastic.co/guide/en/elasticsearch/reference/current/advanced-configuration.html#readiness-tcp-port

To use it, user needs to set `readiness.port` in `elasticsearch.yml`

### [2] Motivation is to check if "a node has joined the cluster or not", but not only "node started"

https://www.elastic.co/guide/en/elasticsearch/reference/current/advanced-configuration.html#readiness-tcp-port

```
If configured, a node can open a TCP port when the node is in a ready state. 
A node is deemed ready when it has successfully joined a cluster. 
In a single node configuration, the node is said to be ready, when it’s able to accept requests.
```

### [3] In ECK, it's configured as `8080` in `readiness.port` in `elasticsearch.yml`

My test env:

```bash
# to check
➜  ~ kubectl get secret elasticsearch-quickstart-es-default-es-config -o jsonpath="{.data['elasticsearch\.yml']}" | base64 --decode | grep 8080 -B1    

# response
readiness:
    port: "8080"
```

### [4] Can check inside or outside the pod

Where we can get check when it's ready:

```bash
# inside the pod
elasticsearch@elasticsearch-quickstart-es-default-0:~$ nc -z -v -w5 127.0.0.1 8080
Connection to 127.0.0.1 8080 port [tcp/*] succeeded!

# outside the pod - check pod logs
➜  ~ k logs elasticsearch-quickstart-es-default-0 -c elasticsearch | grep 8080

{"@timestamp":"2024-10-09T01:20:33.805Z", "log.level": "INFO", "message":"readiness service up and running on 0.0.0.0:8080", "ecs.version": ...
```

**Comment by alxivanov** [comment]
It may take a while for a node (pod) to become ready, provided all configuration is ok and there are no error/warn messages in pod log - in my case one of the nodes was "ready" 3 hours after it was restarted.

**Comment by fabienvauchelles** [comment]
Hello,

If you deactivate the security (login/password), the probe doesn't work anymore:
```
xpack.security.enabled: false
```

Workaround is to change the port of the probe from 8080 to 9200 with:
```
podTemplate:
  spec:
    containers:
    - name: elasticsearch
      readinessProbe:
        exec:
          command:
            - bash
            - -c
            - "nc -z -v -w5 127.0.0.1 9200"
```
