### ISSUE TITLE
Allow setting SecurityContext for Kibana InitContainer

### ISSUE THREAD

**Issue by cospeedster** [elastic/cloud-on-k8s#8046]
We need to set the SecurityContext for all Containers including InitContainers.
Therefore I request the feature to be able to set at least the following values in the SecurityContext for the kibana InitContainer:

```yaml
SecurityContext:
  privileged: false
  runAsUser: <uid>
  runAsGroup: <gid>
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
```

References:
- Source [kibana/init_configuration.go#L47](https://github.com/elastic/cloud-on-k8s/blob/d1a0de657215519666b7d4623a0e13abdb668b44/pkg/controller/kibana/init_configuration.go#L47)
- Related to #7787

**Comment by thbkrkr** [comment]
I don't know if this is a feasible change. However, quickly in order to unblock you, note that you can customize initContainers using podTemplate, see the documentation page: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-customize-pods.html.

**Comment by cospeedster** [comment]
Thank you for that idea. I'll try that.

I would still like to see the feature implemented, because you don't really want to deal with the initContainer when using an operator. For example if the startup command which the initContainer uses change, you have to always check that in the original podTemplate and then implement it in your own podTemplate.

**Comment by thbkrkr** [comment]
I understand. Note that you don't have to redefine all fields of the initContainer, just the field you want to change and the operator merges your definition with its own.

**Comment by cospeedster** [comment]
@thbkrkr Thank you for the hint!

I managed to fit our needs mit this snippet:

```yaml
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
[...]
      initContainers:
        - name: elastic-internal-init-config
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
            runAsGroup: 65532
            runAsNonRoot: true
            runAsUser: 65532
```
