### ISSUE TITLE
Adding a new package_policies does not update elastic agent policy

### ISSUE THREAD

**Issue by kaykhan** [elastic/cloud-on-k8s#8109]
In  Kibana i am trying to install 2 extra integrations `kibana` and `kubernetes`. However after applying the change, i can see the integration was installed but the policy has not been added to the existing agent policy

![Image](https://github.com/user-attachments/assets/80816ce1-6d16-4b08-8830-5c13da433d99)

![Image](https://github.com/user-attachments/assets/5730389e-42ea-4736-bb64-b06bc644a1e6)

```
    version: 8.15.2
    spec:
      count: 1
      elasticsearchRef:
        name: elasticsearch-prod-eck-elasticsearch
      http:
        service:
          spec:
            type: NodePort
      podTemplate:
        metadata:
          labels:
            scrape: kb
        spec:
          containers:
          - name: kibana
            resources:
              limits:
                memory: 2Gi
                cpu: 1
          tolerations:
            - key: "karpenter/elastic"
              operator: "Exists"
              effect: "NoSchedule"
          nodeSelector:
            karpenter-node-pool: elastic
            karpenter.k8s.aws/instance-size: large
      config:
        xpack.fleet.agents.elasticsearch.hosts: ["https://elasticsearch-prod-eck-elasticsearch-es-http.elastic-system.svc:9200"]
        xpack.fleet.agents.fleet_server.hosts: ["https://fleet-server-prod-eck-fleet-server-agent-http.elastic-system.svc:8220"]
        xpack.fleet.packages:
          - name: system
            version: latest
          - name: elastic_agent
            version: latest
          - name: fleet_server
            version: latest
          - name: kibana // Added
            version: latest
          - name: kubernetes // Added
            version: latest
        xpack.fleet.agentPolicies:
          - name: Fleet Server on ECK policy
            id: eck-fleet-server
            namespace: default
            monitoring_enabled:
              - logs
              - metrics
            unenroll_timeout: 900
            package_policies:
            - name: fleet_server-1
              id: fleet_server-1
              package:
                name: fleet_server
          - name: Elastic Agent on ECK policy
            id: eck-agent
            namespace: default
            monitoring_enabled:
              - logs
              - metrics
            unenroll_timeout: 900
            is_default: true
            package_policies:
              - id: system-1
                name: system-1
                package:
                  name: system
              - id: kibana-1 // Added
                name: kibana-1
                package:
                  name: kibana
              - name: kubernetes-1 // Added
                id: kubernetes-1
                package:
                  name: kubernetes
```
