### ISSUE TITLE
Unable to get AKS container logs to elasticsearch (Kubernetes Integration) - Fleet agents and package policies

### ISSUE THREAD

**Issue by florentvaldelievre** [elastic/cloud-on-k8s#8115]
```
Elasticsearch: **8.15.2**
AKS: 1.30.5
```

``Hello,

We are attempting to ingest Kubernetes (AKS) container logs into Elasticsearch using the Kubernetes Integration, but the container logs are not appearing on the Elasticsearch side. It seems that by default, the logs should be ingested into the logs-kubernetes.container_logs-* index, but this index is empty.

We've also tried [custom logs](https://github.com/elastic/cloud-on-k8s/blob/main/config/recipes/elastic-agent/fleet-custom-logs-integration.yaml) integration, but I dont think it's currently working with elastic **8.15.2**. Related issues: 

1. https://github.com/elastic/cloud-on-k8s/issues/7136
2. https://github.com/elastic/cloud-on-k8s/issues/7781
3. https://github.com/elastic/cloud-on-k8s/issues/5105

The logs can be found on the kubernetes node here (as an example):
`/host/var/log/pods/app-dev_app-ui-6b8d5cdcf5-nksx2_d01a3094-aad3-406e-a9db-880948b98a44/app/0.log`

Do you have any thoughts on what might be causing the issue or how we could further pinpoint the problem?

The following configuration is used

```
        xpack.fleet.packages:
        - name: system
          version: latest
        - name: elastic_agent
          version: latest
        - name: fleet_server
          version: latest
        - name: kubernetes
          version: latest
        - name: apm
          version: latest
        - name: log
          version: latest
        xpack.fleet.agentPolicies:
          - name: Fleet Server on ECK policy
            id: eck-fleet-server
            namespace: default
            monitoring_enabled:
            - logs
            - metrics
            package_policies:
            - name: fleet_server-1
              id: fleet_server-1
              package:
                name: fleet_server
          - name: Elastic Agent on ECK policy
            id: eck-agent
            namespace: default
            monitoring_enabled:
            - logs
            - metrics
            unenroll_timeout: 900
            package_policies:
            - package:
                name: system
              name: system-1
            - package:
                name: kubernetes
              name: kubernetes-1
              inputs:
                - type: filestream
                  enabled: true
                  streams:
                    - data_stream:
                        dataset: kubernetes.container_logs
                      enabled: true
                      vars:
                        - name: paths
                          value: 
                          - '/host/var/log/pods/*/*/*.log'
```

After deploying this policy, I can see this configuration when I click 'View Policy' in Kibana
```
 - id: filestream-container-logs-a3b718bd-efec-54f4-b513-7711c744a8ec
    name: kubernetes-1
    revision: 1
    type: filestream
    use_output: default
    meta:
      package:
        name: kubernetes
        version: 1.68.1
    data_stream:
      namespace: default
    package_policy_id: a3b718bd-efec-54f4-b513-7711c744a8ec
    streams:
      - id: >-
          kubernetes-container-logs-${kubernetes.pod.name}-${kubernetes.container.id}
        data_stream:
          dataset: kubernetes.container_logs
        paths:
          - /host/var/log/pods/*/*/*.log
        prospector:
          scanner:
            fingerprint.enabled: true
            symlinks: true
        file_identity.fingerprint: null
        parsers:
          - container:
              stream: all
              format: auto
        processors:
          - add_fields:
              target: kubernetes
              fields:
                annotations.elastic_co/dataset: '${kubernetes.annotations.elastic.co/dataset|""}'
                annotations.elastic_co/namespace: '${kubernetes.annotations.elastic.co/namespace|""}'
                annotations.elastic_co/preserve_original_event: >-
                  ${kubernetes.annotations.elastic.co/preserve_original_event|""}
          - drop_fields:
              fields:
                - kubernetes.annotations.elastic_co/dataset
              when:
                equals:
                  kubernetes.annotations.elastic_co/dataset: ''
              ignore_missing: true
          - drop_fields:
              fields:
                - kubernetes.annotations.elastic_co/namespace
              when:
                equals:
                  kubernetes.annotations.elastic_co/namespace: ''
              ignore_missing: true
          - drop_fields:
              fields:
                - kubernetes.annotations.elastic_co/preserve_original_event
              when:
                equals:
                  kubernetes.annotations.elastic_co/preserve_original_event: ''
              ignore_missing: true
          - add_tags:
              tags:
                - preserve_original_event
              when:
                and:
                  - has_fields:
                      - >-
                        kubernetes.annotations.elastic_co/preserve_original_event
                  - regexp:
                      kubernetes.annotations.elastic_co/preserve_original_event: ^(?i)true$
```
