### ISSUE TITLE
Kubernetes Elastic Agent Integration does not recognize all k8s nodes within the cluster.

### ISSUE THREAD

**Issue by kaykhan** [elastic/cloud-on-k8s#8152]
I have a ECK cluster provisioned in a new K8s AWS EKS cluster. We have elastic agent installed managed by fleet server.

It appears to be case that there are only as many elastic agents deployed as there are number of elasticsearch nodes. In elasticsaerch we have defined 3 nodes sets with 2 nodes each (3x2=6). But our overall k8s cluster contains 14 nodes.

![Image](https://github.com/user-attachments/assets/841d9edc-afad-42d1-902a-ef2157c27bc8)

![Image](https://github.com/user-attachments/assets/6aa1a22c-0f19-44fc-b70e-ba437cc66808)

![Image](https://github.com/user-attachments/assets/16a069b0-9fd1-487c-b28a-20d1ec25a2d7)

We are installing eck elastic agent using the helm chart - below is our configuration

```
My elastic agent configuration

    version: 8.15.2
    spec:
      elasticsearchRefs: []
      fleetServerRef:
        name: ${data.terraform_remote_state.eck_fleet.outputs.fleet_server_name}
      kibanaRef:
        name: ${data.terraform_remote_state.eck_kibana.outputs.kibana_name}
      mode: fleet
      policyID: ${local.eck_agent_policy_id}
      daemonSet:
        podTemplate:
          spec:
            automountServiceAccountToken: true
            serviceAccountName: elastic-agent
            hostNetwork: true
            dnsPolicy: ClusterFirstWithHostNet
            containers:
            - name: agent
              securityContext:
                runAsUser: 0
              resources:
                limits:
                  cpu: 500m 
                  memory: 1000Mi
                requests:
                  cpu: 100m
                  memory: 200Mi
              env:
              - name: NODE_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
              volumeMounts:
              - name: varlogcontainers
                mountPath: /var/log/containers
              - name: varlogpods
                mountPath: /var/log/pods
              - name: varlibdockercontainers
                mountPath: /var/lib/docker/containers
            volumes:
            - name: varlogcontainers
              hostPath:
                path: /var/log/containers
            - name: varlogpods
              hostPath:
                path: /var/log/pods
            - name: varlibdockercontainers
              hostPath:
                path: /var/lib/docker/containers 
```

Coming from filebeat/metrics we understood that there should be a pod for every node. Should this not also be the case for elastic agents given that it is defined as a daemonSet.

Have we misconfigured something?

https://www.elastic.co/guide/en/fleet/current/running-on-kubernetes-managed-by-fleet.html

> The Elastic Agent is deployed as a [DaemonSet](https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/) to ensure that there is a running instance on each node of the cluster.
