### ISSUE TITLE
APM Server NodePort

### ISSUE THREAD

**Issue by kaykhan** [elastic/cloud-on-k8s#8157]
We are trying to create an APM Server with the http type set to NodePort. However despite setting `http.service.spec.type` to `NodePort`. It seems to be getting reverted/set to ClusterIP.

![Image](https://github.com/user-attachments/assets/3628bfb4-3003-4b27-8191-8310ffebf34b)

**apm server config**
```
    count: 1
    version: 8.15.2
    fullnameOverride: ${local.apm_server_name}
    spec:
      elasticsearchRef:
        name: ${data.terraform_remote_state.eck_elasticsearch.outputs.elasticsearch_name}
      kibanaRef: 
        name: ${data.terraform_remote_state.eck_kibana.outputs.kibana_name}
      http:
        service:
          spec:
            type: NodePort
    config:
      logging:
        level: debug
      apm-server:
        rum:
          enabled: true
      # output.elasticsearch:
      #   hosts: ["${data.terraform_remote_state.eck_elasticsearch.outputs.elasticsearch_name}-es-http.elastic-system.svc:9200"]
      #   username: "elastic"
      #   password: ${data.terraform_remote_state.eck_elasticsearch.outputs.elasticsearch_elastic_user_password}
      #   protocol: "https"
```
