### ISSUE TITLE
Service not reset when set then removed from definition

### ISSUE THREAD

**Issue by thbkrkr** [elastic/cloud-on-k8s#8161]
ECK manages a set of services per Elasticsearch cluster that users can configure. By default, the operator configures the http service with type`ClusterIP`. If a user configures it with type `LoadBalancer` and later completely deletes it from the es resource definition, the service is never reconfigured to the default type`ClusterIP`.

### Step to reproduce:
- Deploy an Elasticsearch with a `LoadBalancer` service:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: c0
spec:
  version: 8.15.3
  http:
    service:
      spec:
        type: LoadBalancer
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
```

- Remove the service from the definition and redeploy:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: c0
spec:
  version: 8.15.3
  # http:
  #   service:
  #     metadata:
  #       annotations:
  #         answer: "42"
  #     spec:
  #       type: LoadBalancer
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
```

- Check that the service type is still `LoadBalancer`:

```sh
NAME                  TYPE           CLUSTER-IP      EXTERNAL-IP    PORT(S)          AGE
c0-es-http            LoadBalancer   10.1.2.3   192.1.2.3   9200:31142/TCP   3m24s
```

### Why?

We have a function to set the defaults, but we don't set the `type` there: https://github.com/elastic/cloud-on-k8s/blob/645f75022f5117960381b7e52c95c16409a5bcd3/pkg/controller/common/defaults/service.go#L14.

We have a function to `applyServerSideValues` for several reasons, to decide if we need to recreate or update the service, where we retrieve and restore the current reconciled type.
https://github.com/elastic/cloud-on-k8s/blob/645f75022f5117960381b7e52c95c16409a5bcd3/pkg/controller/common/service_control.go#L53-L54
