### ISSUE TITLE
Adding nodeSelctor to eck-kibana values.yaml seems that it does not work as expected

### ISSUE THREAD

**Issue by babinos87** [elastic/cloud-on-k8s#8193]
Hi,

I am trying to install ELK with helm, and I want to set specific node selector for the created resources. While this works great with Elasticsearch, I cannot make it work with Kibana. I have tried to place the `nodeSelector` object in various places, but still the pod is created in some other node(s). 

Here is an example of my custom `values.yaml` file:

```
---
eck-elasticsearch:
  enabled: true
  fullnameOverride: my-elk-elasticsearch
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              resources:
                limits:
                  memory: 2Gi
                requests:
                  memory: 2Gi
          nodeSelector:
            kubernetes.io/os: linux
            usage: my-elk-nodes
            subnet_type: private

eck-kibana:
  enabled: true
  fullnameOverride: my-elk-kibana

# Tried to put nodeSelector here as well, on the top level, no luck
#  nodeSelector:
#    kubernetes.io/os: linux
#    usage: my-elk-nodes
#    subnet_type: private

  spec:
    elasticsearchRef:
      name: my-elk-elasticsearch

# Tried to put nodeSelector here as well, just under "spec", no luck
#    nodeSelector:
#      kubernetes.io/os: linux
#      usage: my-elk-nodes
#      subnet_type: private

    podTemplate:
      nodeSelector:
        kubernetes.io/os: linux
        usage: my-elk-nodes
        subnet_type: private
```

I also checked the helm template file, and I think this is the one that is used: https://github.com/elastic/cloud-on-k8s/blob/main/deploy/eck-operator/charts/eck-operator-crds/templates/all-crds.yaml#L8422

which shows that the `podTemplate` can be used to customize the pods? 

Have I missed something here? Is it even possible to set the `nodeSelector` for the kibana chart?

**Comment by babinos87** [comment]
Oh my goodness. While I was reviewing my post, I found the problem. It should be:

```
...
    podTemplate:
      spec:
        nodeSelector:
          kubernetes.io/os: linux
          usage: my-elk-nodes
          subnet_type: private
...
```

(have missed the `spec` inside the `podTemplate`).

WORKS 💃
