### ISSUE TITLE
Logstash secureSettings does not properly populate secrets with spaces

### ISSUE THREAD

**Issue by h3xcat** [elastic/cloud-on-k8s#8270]
Secrets containing spaces are being cut-off at first space when they're stored inside Logstash keystore. 
I have encountered the issue as I was trying to populate `sasl_jaas_config` for `kafka` output, which is typically considered sensitive.

**Comment by barkbay** [comment]
Can be reproduced with:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: logstash-secure-settings
  namespace: logstash-sample
stringData:
  V1: "Hello, world!"
---
apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: logstash-sample
  namespace: logstash-sample
spec:
  version: 8.16.1
  count: 1
  pipelines:
    - pipeline.id: main
      config.string: |-
        input { exec { command => 'uptime' interval => 10 } }
        output {
          stdout {}
        }
        filter {
          if ("${V1:}" != "") {   
            mutate { add_tag => ["${V1:}"] }
          }
        }
  secureSettings:
    - secretName: logstash-secure-settings
```

In the container logs we can see that the value is only `Hello,`:

```
{
       "message" => " 09:26:12 up 1 day, 23:55,  0 users,  load average: 1.34, 0.56, 0.44\n",
          "tags" => [
        [0] "Hello,"
    ],
...
```
