### ISSUE TITLE
imagePullSecrets not working

### ISSUE THREAD

**Issue by ak1008** [elastic/cloud-on-k8s#8304]
Helmchart version: 2.17.0

ImagePullSecrets seems to pull images from a private repository for ECK Operator but not for Elasticsearch, Kibana etc. Tried many variations of the Elasticsearch values file including the below but always get a 403.

Also, it seems that it's not part other components values files. I can only find a reference to it on the elasticsearch value file...how would it work for other components? 

```
version: 8.18.0-SNAPSHOT
image:
nodeSets:
- name: default
  count: 1
  config:
    node.store.allow_mmap: false
  podTemplate:
    spec:
      containers:
      - name: elasticsearch
        resources:
          limits:
            memory: 2Gi
          requests:
            # cpu: 1
            memory: 2Gi
    imagePullSecrets:
    - name: "image-pull-secret"
```

**Comment by thbkrkr** [comment]
> ImagePullSecrets seems to pull images from a private repository for ECK Operator but not for Elasticsearch, Kibana etc.

I'm not sure I follow the issue. `ImagePullSecrets` does not pull images. `ImagePullSecrets` is used to reference a Secret to be used for authentication when pulling images. The fact that a public or a private repository is used depends on the image name.

Either because you explicitly set the image:
```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 8.18.0-SNAPSHOT
  image: myprivaterepository.io/elasticsearch/elasticsearch:8.18.0-SNAPSHOT
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
    podTemplate:
      spec:
        imagePullSecrets:
        - name: "image-pull-secret"
```

or you set a global private registry via `--container-repository` (https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-air-gapped.html#k8s-container-repository-override).

> Also, it seems that it's not part other components values files. I can only find a reference to it on the elasticsearch value file...how would it work for other components?

`imagePullSecrets` needs to be set in the PodSpec, https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#containers.html

All ECK custom resources have a `podTemplate.spec` field that is used to defined the PodSpec, and this where you can set `imagePullSecrets`.

```sh
~/dev/src/github.com/elastic/cloud-on-k8s/config/crds/v1/resources > grep podTemplate -l -r
./elasticsearch.k8s.elastic.co_elasticsearches.yaml
./beat.k8s.elastic.co_beats.yaml
./logstash.k8s.elastic.co_logstashes.yaml
./kibana.k8s.elastic.co_kibanas.yaml
./enterprisesearch.k8s.elastic.co_enterprisesearches.yaml
./agent.k8s.elastic.co_agents.yaml
./maps.k8s.elastic.co_elasticmapsservers.yaml
./apm.k8s.elastic.co_apmservers.yaml
```
