### ISSUE TITLE
ERU handling with enterprise license file

### ISSUE THREAD

**Issue by ktzsolt** [elastic/cloud-on-k8s#8347]
Would you please consider adding an extra maxERUs field to the eck-license Kubernetes secret, allowing Kubernetes cluster administrators to control how many ERUs can be used in a specific Kubernetes cluster? 

The effective number of ERUs allowed in the cluster would then be the lesser of this maxERUs field and the number of ERUs included in the license key. This would help to better prevent an underlicensed scenario, particularly in a development/test Kubernetes cluster where Elasticsearch clusters and nodes are created dynamically on demand by the developers.

Example:
```
apiVersion: v1
kind: Secret
data:
  license: <base64encoded key>
  maxERUs: 2
metadata:
  name: eck-license
  namespace: elastic-system
  labels:
    license.k8s.elastic.co/scope: operator
type: Opaque
```

Even if the license key includes 10 ERUs, no more than 2 ERUs can be utilized in this Kubernetes cluster with this eck-license Secret. This approach allows us to use the same license key/file in two different Kubernetes clusters (e.g., dev and prod) and allocate 2 ERUs to the dev cluster and 8 ERUs to the prod cluster. This way, we could better mitigate the risk of an underlicensed scenario.
