### ISSUE TITLE
Fleet on AKS error "failed to request https://kibana-kb-http.elkstack.svc:5601/api/fleet/setup, status is 401"

### ISSUE THREAD

**Issue by Magister-Machinis** [elastic/cloud-on-k8s#8406]
Hello,
I am in the process of setting up a 2.16 eck deployment on kubernetes 1.30 on aks. The images are hosted on an azure container registry. I'm still configuring various bits but have elasticsearch and kibana reporting as ready. When the operator tries to spin up the fleet server i get the below error:

```
{"log.level":"error","@timestamp":"2025-01-14T21:07:55.295Z","log.logger":"manager.eck-operator","message":"Reconciler error","service.version":"2.15.0+61f99ee5","service.type":"eck","ecs.version":"1.4.0","controller":"agent-controller","object":{"name":"fleet-server","namespace":"elkstack"},"namespace":"elkstack","name":"fleet-server","reconcileID":"f73ddff1-5511-466b-85d5-b7fab46ed204","error":"failed to request https://kibana-kb-http.elkstack.svc:5601/api/fleet/setup, status is 401)","errorCauses":[{"error":"failed to request https://kibana-kb-http.elkstack.svc:5601/api/fleet/setup, status is 401)"}],"error.stack_trace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:224"}
```

I based the yml on the quickstart examples in the official guide. Below are configs for fleet,  and the kibana config, currently I'm just trying to get the fleet server running for data ingestion at a later date and may circle back to agents later. Any insights to what I am missing or could try to troubleshoot this would be greatly appreciated.

fleet
```
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: fleet-server
  namespace: elkstack
  labels:
      env: prod
spec:
  version: 8.17.0
  image: internalrepo
  kibanaRef:
    name: kibana
  elasticsearchRefs:
  - name: elasticsearch-cluster
  mode: fleet
  fleetServerEnabled: true
  policyID: eck-fleet-server
  deployment:
    replicas: 1
    podTemplate:
      spec:
        nodeSelector:
          env: elk-stack
        serviceAccountName: elastic-agent
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0 
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elastic-agent
  namespace: elkstack
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - pods
  - nodes
  - namespaces
  verbs:
  - get
  - watch
  - list
- apiGroups: ["coordination.k8s.io"]
  resources:
  - leases
  verbs:
  - get
  - create
  - update
- apiGroups: ["apps"]
  resources:
  - replicasets
  verbs:
  - list
  - watch
- apiGroups: ["batch"]
  resources:
  - jobs
  verbs:
  - list
  - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elastic-agent
  namespace: elkstack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: elastic-agent
subjects:
- kind: ServiceAccount
  name: elastic-agent
  namespace: elkstack
roleRef:
  kind: ClusterRole
  name: elastic-agent
  apiGroup: rbac.authorization.k8s.io
```
kibana config
```
apiVersion: stackconfigpolicy.k8s.elastic.co/v1alpha1
kind: StackConfigPolicy
metadata:
  name: elk-stack-config-policy
  namespace: elkstack
spec:
  resourceSelector:
    matchLabels:
      env: prod
  
  kibana:
    secureSettings:
      
    config: 
      xpack.fleet.agents.elasticsearch.hosts: ["https://elasticsearch-cluster-es-http.elkstack:9200"] #https://ES_RESOURCE_NAME-es-http.ES_RESOURCE_NAMESPACE.svc:9200
      xpack.fleet.agents.fleet_server.hosts: ["https://fleet-server-agent-http.elkstack.svc:8220"] #https://FS_RESOURCE_NAME-agent-http.FS_RESOURCE_NAMESPACE.svc:8220
      xpack.fleet.packages:
        - name: system
          version: latest
        - name: elastic_agent
          version: latest
        - name: fleet_server
          version: latest
      xpack.fleet.agentPolicies:
        - name: Fleet Server on ECK policy
          id: eck-fleet-server
          namespace: elkstack
          is_managed: true
          monitoring_enabled:
          - logs
          - metrics
          unenroll_timeout: 900
          package_policies:
          - name: fleet_server-1
            id: fleet_server-1
            package:
              name: fleet_server
```
