### ISSUE TITLE
[Doc] Add central pipeline management example to Logstash

### ISSUE THREAD

**Issue by kaisecheng** [elastic/cloud-on-k8s#8462]
CPM is a popular feature in Logstash. Customers want guidelines on how to config in ECK Logstash

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-sample
spec:
  version: 9.0.0-SNAPSHOT
  nodeSets:
    - name: default
      count: 3 
      config:
        node.store.allow_mmap: false
        xpack.license.self_generated.type: trial # for CPM
  monitoring:
    metrics:
      elasticsearchRefs:
        - name: elasticsearch-sample
---
apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: logstash-sample
spec:
  count: 1
  version: 9.0.0-SNAPSHOT
  elasticsearchRefs:
    - clusterName: production
      name: elasticsearch-sample
  podTemplate:
    spec:
      containers:
        - name: logstash
  config:
    xpack.management.enabled: true
    xpack.management.elasticsearch.hosts: "${PRODUCTION_ES_HOSTS}"
    xpack.management.elasticsearch.username: "${PRODUCTION_ES_USER}"
    xpack.management.elasticsearch.password: "${PRODUCTION_ES_PASSWORD}"
    xpack.management.elasticsearch.ssl.certificate_authority: "${PRODUCTION_ES_SSL_CERTIFICATE_AUTHORITY}"
    xpack.management.pipeline.id: ["*somekeys*"]
  monitoring:
    metrics:
      elasticsearchRefs:
        - name: elasticsearch-sample
    logs:
      elasticsearchRefs:
        - name: elasticsearch-sample
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-sample
spec:
  version: 9.0.0-SNAPSHOT
  elasticsearchRef:
    name: elasticsearch-sample
  count: 1
  monitoring:
    metrics:
      elasticsearchRefs:
        - name: elasticsearch-sample
```
