### ISSUE TITLE
Elasticsearch validating webhook swallows errors

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#8465]
https://github.com/elastic/cloud-on-k8s/blob/49dc892dacd9d3f83c95a111812506485c3bf319/pkg/controller/elasticsearch/validation/validations.go#L189-L190

The error returned from `UnpackConfig` is swallowed. We should at least log it is not return it to the user. 

https://github.com/elastic/cloud-on-k8s/blob/49dc892dacd9d3f83c95a111812506485c3bf319/pkg/controller/elasticsearch/validation/validations.go#L212-L214

is triggered incorrectly if `UnpackConfig` fails and the validations haven't even run. 

Examples test case: 

```
  - name: default
    config:
      node.roles: ["master", "data", "ingest", "ml"]
      cluster.max_shards_per_node: "2000"
      cluster.max_shards_per_node.frozen: "4000"
```

This is theoretically [correct Elasticsearch configuration](https://www.elastic.co/guide/en/elasticsearch/reference/current/misc-cluster-settings.html#cluster-shard-limit) but impossible to express in valid YAML
