### ISSUE TITLE
How to use imagePullSecrets on helm install

### ISSUE THREAD

**Issue by tylerlittlefield** [elastic/cloud-on-k8s#8474]
Sorry, I see this topic reported multiple times but I cannot figure out how to set imagePullSecrets during helm install? Can someone share the helm command I should run to set it?

**Comment by pkoutsovasilis** [comment]
Hey @tylerlittlefield 👋 For support and how-to questions like this, we recommend using the [Elastic Community Forums](https://discuss.elastic.co/c/orchestration/eck/79) where you'll get help from both the community and Elastic team members. GitHub issues are best reserved for bug reports and feature requests.

That said, to answer your question about `imagePullSecrets`:

**For ECK-managed resources (Elasticsearch, Kibana, etc.):**

You can define `imagePullSecrets` through the `podTemplate` field in your CRDs:
```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: my-es
spec:
  version: 8.11.0
  nodeSets:
  - name: default
    count: 3
    podTemplate:
      spec:
        imagePullSecrets:
        - name: my-registry-secret
```

**For the ECK operator itself:**

You can set `imagePullSecrets` in the Helm chart values:
```yaml
imagePullSecrets:
  - name: my-registry-secret
```

I'm closing this issue, but feel free to continue the discussion on the forums if you need further assistance!
