### ISSUE TITLE
Add option to configure logstash statefulset persistentVolumeClaimRetentionPolicy

### ISSUE THREAD

**Issue by martin-ilavsky** [elastic/cloud-on-k8s#8478]
Logstash statefulset has current default:
```
 spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain    
```

I want to be able to change `whenScaled` to `Delete` with logstash CRD. Currently when I patch it, operator will change it to the original values. Have I just missed where is it supposed to be configured ?
