### ISSUE TITLE
apm-server-wolfi 8.17.2 "exec: "apm-server": executable file not found in $PATH: unknown"

### ISSUE THREAD

**Issue by kourosh-forti-hands** [elastic/cloud-on-k8s#8485]
Currently building a deployment using [eck-stack](https://github.com/elastic/cloud-on-k8s/tree/2.16/deploy/eck-stack) to deploy elasticsearch, kibana, logstash, fleet-server, enterprise-search and apm-server. 

They are all using wolfi images. Up to now I was able to deploy everything successfully using wolfi images. 

During my apm-server deployment I began getting the following events from my pods:
```
"Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: 
runc create failed: unable to start container process: exec: "apm-server": executable file not found in $PATH: unknown"
```

I discovered this was brought up and closed in issue #8447 upon further digging and testing. I switched it from the wolfi image and it deployed successfully. 

Is it possible the issue still exists but with the wolfi images only?

```
eck-apm-server:
  version: 8.17.2
  enabled: true
  image: 000000000000.dkr.ecr.us-gov-west-1.amazonaws.com/apm/apm-server-wolfi:8.17.2-amd64
  imagePullPolicy: Always
  count: 3
  elasticsearchRef:
    name: elasticsearch
  kibanaRef:
    name: kibana
  config:
    name: elastic-apm
    apm-server.jaeger.grpc.enabled: true
    apm-server.jaeger.grpc.host: "0.0.0.0:14250"
    apm-server.rum.enabled: true
    apm-server.ilm.enabled: true
    xpack.fleet.packages:
      - name: apm
        version: latest
  http:
    tls:
      selfSignedCertificate:
        disabled: true
    service:
      spec:
        ports:
          - name: http
            port: 8200
            targetPort: 8200
          - name: grpc
            port: 14250
            targetPort: 14250
```

**Comment by naemono** [comment]
I cannot replicate this issue:
```
❯ kc get pod -n elastic-stack
NAME                                                 READY   STATUS    RESTARTS   AGE
eck-stack-eck-apm-server-apm-server-55b6f89f-57xng   1/1     Running   0          97s
eck-stack-eck-apm-server-apm-server-55b6f89f-kpqmh   1/1     Running   0          68s
eck-stack-eck-apm-server-apm-server-55b6f89f-rqq94   1/1     Running   0          82s
elasticsearch-es-default-0                           1/1     Running   0          19m
elasticsearch-es-default-1                           1/1     Running   0          19m
elasticsearch-es-default-2                           1/1     Running   0          19m
kibana-kb-7b684467fd-68tff                           1/1     Running   0          19m

❯ kc get pod -n elastic-stack eck-stack-eck-apm-server-apm-server-55b6f89f-57xng -o yaml | yq '.spec.containers[].image'
docker.elastic.co/apm/apm-server-wolfi:8.17.2-amd64
```

Exact manifest used:
```yaml
---
eck-elasticsearch:
  enabled: true

  # Name of the Elasticsearch instance.
  #
  fullnameOverride: elasticsearch
  version: 8.17.2

  nodeSets:
  - name: default
    count: 3
    # Comment out when setting the vm.max_map_count via initContainer, as these are mutually exclusive.
    # For production workloads, it is strongly recommended to increase the kernel setting vm.max_map_count to 262144
    # and leave node.store.allow_mmap unset.
    # ref: https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-virtual-memory.html
    #
    config:
      node.store.allow_mmap: false

eck-kibana:
  enabled: true

  # Name of the Kibana instance.
  #
  fullnameOverride: kibana
  version: 8.17.2
  spec:
    config:
      xpack.fleet.packages:
      - name: apm
        version: latest

eck-apm-server:
  enabled: true

  # Count of APM Server replicas to create.
  #
  image: docker.elastic.co/apm/apm-server-wolfi:8.17.2-amd64
  version: 8.17.2

  # Reference to ECK-managed Elasticsearch resource.
  #
  elasticsearchRef:
    name: elasticsearch
  kibanaRef:
    name: kibana
  imagePullPolicy: Always
  count: 3
  config:
    name: elastic-apm
    apm-server.jaeger.grpc.enabled: true
    apm-server.jaeger.grpc.host: "0.0.0.0:14250"
    apm-server.rum.enabled: true
    apm-server.ilm.enabled: true
    xpack.fleet.packages:
      - name: apm
        version: latest
  http:
    tls:
      selfSignedCertificate:
        disabled: true
    service:
      spec:
        ports:
          - name: http
            port: 8200
            targetPort: 8200
          - name: grpc
            port: 14250
            targetPort: 14250

```

Please re-open if you have additional information that can help track down the issue.
