### ISSUE TITLE
Custom PVC Name

### ISSUE THREAD

**Issue by michaelact** [elastic/cloud-on-k8s#8490]
## Issue

I need to update the PVC name after changing the storage class while keeping the old PVC. Using the following Helm values:

```yaml
nodeSets:
- name: elasticsearch-main
  count: 1
  config:
    cluster.name: "our-cluster"
    node.roles: ["master", "data"]
  podTemplate:
    spec:
      containers:
        - name: elasticsearch
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elasticsearch-main-data
  volumeClaimTemplates:
  - metadata:
      name: elasticsearch-main-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: efs
  podTemplate:
    spec:
      initContainers:
      - name: initial-configurator
        securityContext:
          privileged: true
          runAsUser: 0
        command:
          - 'sh'
          - '-c'
          - 'sysctl -w vm.max_map_count=262144'
          - 'ulimit -n 65536'
```

However, I encounter the error:

```
Error: UPGRADE FAILED: failed to create resource: admission webhook "elastic-es-validation-v1.k8s.elastic.co" denied the request: Elasticsearch.elasticsearch.k8s.elastic.co "add-ons-es-eck-elasticsearch" is invalid: spec.nodeSet[0].volumeClaimTemplates: Invalid value: "elasticsearch-main-data": volume claim declared but volume not mounted in any container. Note that the Elasticsearch data volume should be named 'elasticsearch-data'
```

## Expected

I have set the volume mounts, so I expect it to work. Based on this PR: https://github.com/elastic/cloud-on-k8s/pull/4526/files, it should work since the volume mounts are configured.

## Versions

1. Helm Chart ECK/Operator: `elastic/eck-operator`, version `2.14.0`
2. Helm Chart ECK/Elasticsearch: `elastic/eck-elasticsearch`, version `0.13.0`

**Comment by michaelact** [comment]
My bad 😄 , it should be:
```
nodeSets:
- name: elasticsearch-main
  count: 1
  config:
    cluster.name: "our-cluster"
    node.roles: ["master", "data"]
  volumeClaimTemplates:
  - metadata:
      name: elasticsearch-main-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: efs
  podTemplate:
    spec:
      initContainers:
      - name: initial-configurator
        securityContext:
          privileged: true
          runAsUser: 0
        command:
          - 'sh'
          - '-c'
          - 'sysctl -w vm.max_map_count=262144'
          - 'ulimit -n 65536'
      containers:
        - name: elasticsearch
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elasticsearch-main-data
```
