### ISSUE TITLE
Unable to add cors parameters to elasticsearch

### ISSUE THREAD

**Issue by PrinceBaghel258025** [elastic/cloud-on-k8s#8491]
```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: monitoring
spec:
  version: 8.13.0
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
      extraConfig:
        http: 
          cors.allow-origin: "*"
          cors.enabled : true
          cors.allow-methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
          cors.allow-headers: X-Requested-With,X-Auth-Token,Content-Type,Content-Length
```
