### ISSUE TITLE
VolumeClaimTemplate for APM

### ISSUE THREAD

**Issue by JulienOrain** [elastic/cloud-on-k8s#8495]
For elastic and logstash, a PersistentVolume called `<service>-data` is created by default. It maps to /usr/share/<service>/data for persistent storage.

It is possible to have the same behavior for apm-server ? This way, we would be able to store tail-sampling data for example

**Comment by rhr323** [comment]
Hi @JulienOrain! Thanks for the question.

The difference here is that Elasticsearch and Logstash, for example, use StatefulSets, which natively support volumeClaimTemplates. APM Server uses a Deployment because historically it was designed as a stateless service that just forwards data to Elasticsearch.

That said, you can achieve per-pod storage using generic ephemeral volumes via the podTemplate. 

Here's an example:

```yaml
apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-server
spec:
  version: 9.2.3
  count: 2  # Each pod gets its own dynamically provisioned volume
  elasticsearchRef:
    name: quickstart
  podTemplate:
    spec:
      containers:
        - name: apm-server
          volumeMounts:
            - name: apm-server-data
              mountPath: /usr/share/apm-server/data
      volumes:
        - name: apm-server-data
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 50Gi
                storageClassName:  # Your CSI driver storage class
                volumeMode: Filesystem
```

Each pod will get its own dynamically provisioned PVC. This could work well for tail-sampling storage.

One caveat: these ephemeral volumes survive container/pod restarts, but are deleted when the pod itself is deleted (e.g., during rolling updates or scale-downs). This is different from StatefulSet behavior where PVCs persist across pod deletions.

Hope this helps!
