### ISSUE TITLE
Elastic operator incorrectly reconciles Kibana config into secret

### ISSUE THREAD

**Issue by Fiki80** [elastic/cloud-on-k8s#8499]
We are deploying Elastic stack via cloud-on-k8s helmcharts. If we use the "simplified" object syntax to configure xpack fleet agent policy in Kibana values, then Kibana config secret is incorrectly interpreted.

This is a part of Kibana object in yaml:
```
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  annotations:
    association.k8s.elastic.co/es-conf: xxx
    eck.k8s.elastic.co/license: basic
  generation: 34
  labels:
    app.kubernetes.io/instance: ecn-monitoring
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: eck-kibana
    argocd.argoproj.io/instance: ecn-monitoring
    helm.sh/chart: eck-kibana-0.14.1
  name: ecn-monitoring-eck-kibana
  namespace: sdlc-monitoring
spec:
  config:
    server:
      publicBaseUrl: https://xxx.xxx
    xpack:
      fleet:
        agentPolicies:
        - id: eck-external-agent-policy
          monitoring_enabled:
          - logs
          - metrics
          name: Elastic Agent on ECK policy - external
          namespace: extern
          package_policies:
          - id: kubernetes-3
            name: kubernetes-3
            package:
              name: kubernetes
            inputs:
              kube-proxy-kubernetes/metrics:
                enabled: true
                streams:
                  '[kubernetes.proxy]':
                    enabled: true
                    vars:
                      hosts:
                      - ecn-monitoring-kube-promet-kube-proxy.kube-system:10249
                vars: {}
          unenroll_timeout: 900
```

And this is how Kibana configuration secret is created by the operator:
```
xpack:
    fleet:
        agentPolicies:
            - id: eck-external-agent-policy
              monitoring_enabled:
                - logs
                - metrics
              name: Elastic Agent on ECK policy - external
              namespace: extern
              package_policies:
                - id: kubernetes-3
                  inputs:
                    kube-proxy-kubernetes/metrics:
                        enabled: true
                        streams:
                            '[kubernetes':
                                proxy]:
                                    enabled: true
                                    vars:
                                        hosts:
                                            - ecn-monitoring-kube-promet-kube-proxy.kube-system:10249
                        vars: null
              unenroll_timeout: 900
```

We can see 2 issues with the created secret. 

1. It seems the key "kubernetes.proxy" is being expanded into two separate keys even if we try to escape the dot according to the official Kibana [documentation](https://www.elastic.co/guide/en/kibana/current/fleet-settings-kb.html)
2. The value of "vars" inside kube-proxy-kubernetes/metrics is transformed from empty object to null, which Kibana does not accept.

version of cloud-on-k8s: 2.16.1
version of kibana: 8.17.0
