### ISSUE TITLE
Deleting a pod while cluster is red results in pod not being replaced.

### ISSUE THREAD

**Issue by jordansissel** [elastic/cloud-on-k8s#850]
## Bug Report
**What did you do?**

Deleted an elasticsearch pod.

**What did you expect to see?**

The loss of a pod should be reconciled by replacing the lost pod.

**What did you see instead? Under which circumstances?**

* No replacement arrived
* The PVC was still Bound (?)

Controller logged `503 Service Unavailable` inside the reconciler.

Circumstances:
* The cluster was "red" according to `kubectl get elasticsearch`.

**Environment**

* Version information:

	https://github.com/elastic/cloud-on-k8s/blob/pre-release/docs/k8s-quickstart.asciidoc

* Kubernetes information:

GKE master 1.11.8-gke.6, nodes 1.11.7-gke.12
	
* Resource definition:

```
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.0.1
  nodes:
  - nodeCount: 3
    config:
      node.master: false
      node.data: true
      node.ingest: true
      node.ml: true
      xpack.license.self_generated.type: trial
    volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1T
        storageClassName: ssd 

  - nodeCount: 3
    config:
      node.master: true
      node.data: false
      node.ingest: false
      node.ml: false
      xpack.license.self_generated.type: trial
    volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 30G
        storageClassName: ssd 

```

* Logs:

I don't have logs from the session, but we did observe a reconciler error message reporting 503 Service Unavailable at the time of the issue.
