### ISSUE TITLE
Document remote cluster setup with non-eck clusters 

### ISSUE THREAD

**Issue by strawgate** [elastic/cloud-on-k8s#8502]
With https://github.com/elastic/cloud-on-k8s/issues/8167 we added the ability to easily configure CCS between two eck clusters

What's less clear is if and how a user who wants to use an eck cluster as a remote cluster would configure it.

The documentation we provide leads the user to setting up certificate based CCS "Connect from an Elasticsearch cluster running outside the Kubernetes cluster" but it doesn't look like we tell the user they need to setup client certificates https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-remote-clusters.html

We should document the setup for connecting a cluster from outside of eck using API keys and rename the current section to be for certificate based ccs

**Comment by barkbay** [comment]
Although we still need to write proper documentation, here are the steps to connect to a hosted deployment in https://cloud.elastic.co/deployments from an ECK managed Elasticsearch cluster:

> [!WARNING]  
> The instructions below assume that the ECK cluster is not configured to connect to others Elasticsearch clusters, within the same Kubernetes clusters, using `spec.remoteClusters`. It is a known limitation because there is currently no way to add trusted certificates to the remote cluster client when using `spec.remoteClusters` is set.

## In the hosted deployment

### Create an API key 

* Create a remote cluster API key in Kibana (`https://<deployment>.kb.<region>.<cloud_provider>.elastic-cloud.com/app/management/security/api_keys/create`)
* Copy the encoded key to a safe location. You will need it in the next steps.

### Get the proxy URL and server name

* In your deployment security settings (`https://cloud.elastic.co/deployments/<deployment id>/security`), get the proxy address and the server name in the `Remote cluster parameters` section.
* **Change the port from `9400` to `9443` in the proxy address.**

## In the ECK cluster

### Store the API key encoded value in a Secret

```yaml
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Secret
metadata:
  name: hosted-remote-api-keys
stringData:
  cluster.remote.elastic-cloud.credentials: <encoded value>
type: Opaque
EOF
```

### Configure the Elasticsearch resource

Enable the remote cluster SSL client and load the API key as a secure setting:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: cluster-in-eck
spec:
  version: 8.17.4
  secureSettings:
    - secretName: hosted-remote-api-keys
  nodeSets:
    - name: default
      config:
        node.store.allow_mmap: false
        xpack:
          security:
            remote_cluster_client:
              ssl:
                enabled: true ## repeat this for each nodeSet
      count: 3
```

### Create the remote cluster using the Elasticsearch API

```
PUT /_cluster/settings
{
  "persistent": {
    "cluster": {
      "remote": {
        "elastic-cloud": {
          "mode":"proxy",
          "proxy_address": "<proxy address, ending with 9443, from step above>",
          "server_name": "<server name from step above>"
        }
      }
    }
  }
}
```

### Check that the ECK cluster is connected to your hosted deployment

```
GET /_remote/info
```

```json
{
  "elastic-cloud": {
    "connected": true,
    "mode": "proxy",
    "proxy_address": "[...]elastic-cloud.com:9443",
    "server_name": "[....].elastic-cloud.com",
    "num_proxy_sockets_connected": 18,
    "max_proxy_socket_connections": 18,
    "initial_connect_timeout": "30s",
    "skip_unavailable": true,
    "cluster_credentials": "::es_redacted::"
  }
}
```
