### ISSUE TITLE
Reference ConfigMap data from StackConfigPolicy for S3-compatible snapshot repository configuration

### ISSUE THREAD

**Issue by takahisa** [elastic/cloud-on-k8s#8511]
## Background
I'm currently using Rook/Ceph as an S3-compatible storage solution for my snapshot repository. When creating an ObjectBucketClaim in Rook/Ceph, it automatically generates a ConfigMap containing essential connection information for the S3-compatible bucket (such as endpoint URLs and bucket names).

Below is an example manifest definition and documentation:

```yaml
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: elasticsearch-snapshot-repository
  namespace: elasticsearch
spec:
  generateBucketName: elasticsearch-snapshot
  storageClassName: rook-ceph-bucket
```

https://github.com/rook/rook/blob/master/Documentation/Storage-Configuration/Object-Storage-RGW/ceph-object-bucket-claim.md

When you apply this definition to a Kubernetes cluster, a ConfigMap containing connection destination information will be generated:

```
$ kubectl get cm -n elasticsearch elasticsearch-snapshot-repository -o json | jq '.data'
{
  "BUCKET_HOST": "rook-ceph-bucket-store.svc",
  "BUCKET_NAME": "elasticsearch-snapshot-837b4c3d-1054-46a5-9f16-982784b8093f",
  "BUCKET_PORT": "443",
  "BUCKET_REGION": "",
  "BUCKET_SUBREGION": ""
}
```

## Problem
I need to configure a StackConfigPolicy custom resource to utilize this S3-compatible storage as a snapshot repository. However, I've encountered a limitation: there doesn't appear to be a mechanism to reference or propagate the connection information stored in the auto-generated ConfigMap to the StackConfigPolicy resource.

Currently, I have to manually copy the connection details from the ConfigMap and hardcode them in the StackConfigPolicy definition, which is not compatible with GitOps workflows as it requires manual intervention.

## Questions
- Is there an existing way to reference ConfigMap data from StackConfigPolicy that I've overlooked?
- If not, are there plans to add such functionality in the future?
- Are there any alternative approaches or workarounds to solve this integration challenge?

**Comment by naemono** [comment]
> Is there an existing way to reference ConfigMap data from StackConfigPolicy that I've overlooked?

This functionality does not exist at this time.

> If not, are there plans to add such functionality in the future?

There are no plans to add this functionality at this time. It seems as though it could be a potential feature for SCPs; something such as:
```
apiVersion: stackconfigpolicy.k8s.elastic.co/v1alpha1
kind: StackConfigPolicy
spec:
  elasticsearch:
    snapshotRepositories:
      my-s3-repo:
        type: s3
        settings:
          bucket:
            valueFrom:
              configMapKeyRef:
                name: elasticsearch-snapshot-repository
                key: BUCKET_NAME
          endpoint:
            valueFrom:
              configMapKeyRef:
                name: elasticsearch-snapshot-repository  
                key: BUCKET_HOST
```

I'll bring it up with the team to see if this is something we want to pursue.

> Are there any alternative approaches or workarounds to solve this integration challenge?

Fluxcd seems to support this: https://fluxcd.io/flux/components/kustomize/kustomizations/#post-build-variable-substitution

**Comment by pkoutsovasilis** [comment]
Hey @takahisa 👋 this has been addressed in #9541, and is gonna be available in the upcoming v3.5.0 release.

The PR introduces a variablesFrom field on StackConfigPolicy that lets you reference ConfigMaps (and Secrets) as substitution variable sources. Keys from the referenced objects become ${VAR} expressions you can use anywhere in the Elasticsearch or Kibana spec fields of the policy.

Specifically, for your Rook/Ceph use case, I am assuming this would look something like:

```yaml
apiVersion: stackconfigpolicy.k8s.elastic.co/v1alpha1
kind: StackConfigPolicy
metadata:
  name: my-policy
spec:
  variablesFrom:
    - kind: ConfigMap
      name: elasticsearch-snapshot-repository
  elasticsearch:
    config:
      s3.client.default.endpoint: "${BUCKET_HOST}:${BUCKET_PORT}"
    # ... rest of snapshot repo config using ${BUCKET_NAME}, etc.
```

The controller watches the referenced ConfigMaps/Secrets and automatically reconciles the policy when they change.
