### ISSUE TITLE
Unable to scale down from 5 to 3 nodes with pods stuck in Pending state.

### ISSUE THREAD

**Issue by nkvoll** [elastic/cloud-on-k8s#853]
Applying the following on a 3 node K8s cluster:
```
cat <<EOFES | kubectl apply -f -
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.0.1
  nodes:
  - nodeCount: 5
    config:
      node.master: true
      node.data: true
      node.ingest: true
      
      xpack.monitoring.collection.enabled: true
      xpack.license.self_generated.type: trial
    podTemplate:
      spec:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: elasticsearch.k8s.elastic.co/cluster-name
                  operator: In
                  values: [quickstart]
              topologyKey: kubernetes.io/hostname
EOFES
```

yields a state like this:

```
NAME                                     READY   STATUS    RESTARTS   AGE
pod/quickstart-es-2ksh7fm5qb             1/1     Running   0          9m
pod/quickstart-es-bh4ctk6fhb             1/1     Running   0          7m
pod/quickstart-es-cg7fxcj5x8             1/1     Running   0          7m
pod/quickstart-es-gdztphvsg2             0/1     Pending   0          7m
pod/quickstart-es-qqw69grpwt             0/1     Pending   0          7m
pod/quickstart-kibana-68485c6954-zldmw   1/1     Running   0          1h
```

Editing the resources and setting `nodeCount: 3` does not delete the two Pods in the `Pending` state (which would be perfectly safe in this case, but perhaps subject to race conditions on a general basis).
