### ISSUE TITLE
eck-apm-server using "8.17.2" cannot adjust count

### ISSUE THREAD

**Issue by heidihe2024** [elastic/cloud-on-k8s#8539]
I'm trying to increase our apm-server replica counts from 30 to 60 using the below values.yaml file

```
apm-server: 
    enabled: true
    version: "8.17.2"
    count: 30
    ...

```

the template file I'm using
```
{{- if index .Values "apm-server" "enabled" | default false }}
---
apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: {{ index .Values "apm-server" "fullnameOverride" | default "apm-server" }}
  namespace: {{ .Release.Namespace }}
spec:
  version: {{ index .Values "apm-server" "version" }}
  count: {{ index .Values "apm-server" "count" }}
  ...
```

helm always revert this config back to 30

is this a known issue for this version?
