### ISSUE TITLE
ECK logstash container can't read pod template's container volumeMounts in AWS EKS

### ISSUE THREAD

**Issue by qoovsxp** [elastic/cloud-on-k8s#8553]
We try to run logstash by ECK operator in AWS EKS.

And we try to use configmap solution for put kafka jaas config to podtemplate's logstash containter and let main logstash containter can read it.
https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-logstash-plugins.html

The part of relevent logstash yml as below.
```yaml
  podTemplate:
    spec:
      nodeSelector:
        eks.amazonaws.com/nodegroup: "test-logstash-nodegroup"
      tolerations:
      - key: "noderole"
        operator: "Equal"
        value: "logstash"
        effect: "NoSchedule"
      volumes:
        - name: kafka-jaas-config
          configMap:
            name: kafkajaas
              #- name: kafka-jaas-config
              #secret:
              #secretName: kafka-config
      containers:
        - name: logtash-service
          image: "docker.elastic.co/logstash/logstash:8.17.3"
          volumeMounts:
            - name: kafka-jaas-config
              mountPath: "/usr/share/logstash/data"
              readOnly: true
          env:
          - name: LS_JAVA_OPTS
            value: "-Xmx2g -Xms2g"
          resources:
            requests:
              memory: 1Gi
              cpu: 0.5
            limits:
              memory: 4Gi
              cpu: 2
```
There are two container in logstash pod as below. 

![Image](https://github.com/user-attachments/assets/e7ea0527-a89b-4e6f-a1c8-85e49133e003)

We can see kafka jaas file in podtemplate's logstash named "logstash service" container as below.

![Image](https://github.com/user-attachments/assets/4ddc3d3a-9d13-4c33-bc63-f8feed189e8b)

But we can't see it in main logstash named "logstash" container as belows.

![Image](https://github.com/user-attachments/assets/a30bd35e-017a-4664-81be-e3124fba8b51)

I can see the logs about main logstash try to running pipeline but can't find kafka jaas config.

![Image](https://github.com/user-attachments/assets/c834370d-3526-474c-81c5-31eeb8d482f7)

Is there any wrong config in my yml file or it's just a bug?

What did you expect to see?
container logstash can read kafka jaas config and run pipeline

Environment

    ECK version: 2.16.1
    EKS version: 1.30
    Logstash version: 8.17.3
