### ISSUE TITLE
Unable to run Elastic Search as non root user

### ISSUE THREAD

**Issue by TheGrussalo** [elastic/cloud-on-k8s#8556]
I'm trying to run Elastic Search as a non root user on AKS but the pod always has the root group (0).

My understanding is that the pods will by default run as a non root user as the [security context](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-security-context.html) sets `readOnlyRootFilesystem` and `allowPrivilegeEscalation`.  Although it still seems to run as root even if these are specified.

Steps to follow:
- Apply the CRDs and enable the Operator:
```
kubectl create -f https://download.elastic.co/downloads/eck/2.16.1/crds.yaml
kubectl apply -f https://download.elastic.co/downloads/eck/2.16.1/operator.yaml
```

- Deploy Elastic Search following the [Quick Start documentation](https://www.elastic.co/guide/en/cloud-on-k8s/2.16/k8s-deploy-elasticsearch.html) adding a volume claim for elasticsearch-data:
```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 8.17.3
  nodeSets:
  - name: default
    config:
      node.store.allow_mmap: false
    count: 1
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 6Gi
        storageClassName: default
```

The pods are created and when I exec into the pod and run `id` it shows:
```
kubectl exec -it elasticsearch-sample-es-default-0 -- id  

uid=1000(elasticsearch) gid=1000(elasticsearch) groups=1000(elasticsearch),0(root)
```

I have tried adding the security context but the pod always shows root:
```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 8.17.3
  nodeSets:
  - name: default
    config:
      node.store.allow_mmap: false
    count: 1
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 6Gi
        storageClassName: local-path
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
        securityContext:
          fsGroup: 1000
          runAsUser: 1000
```

I have also tried this using k8s locally using Rancher (I changed the storage-class to local-path) but the pod always seems to have the root group.

How can I make stop it having root permission?

**Comment by barkbay** [comment]
> I have tried adding the security context but the pod always shows root:

I think what you are looking for is `runAsGroup`: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod

With the following manifest:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 8.17.3
  nodeSets:
  - name: default
    config:
      node.store.allow_mmap: false
    count: 1
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
        securityContext:
          runAsGroup: 1001
          runAsUser: 1001
          fsGroup: 1001
```

The result is:

```
I have no name!@quickstart-es-default-0:/usr/share/elasticsearch$ id
uid=1001 gid=1001 groups=1001
```

Not that unlike the root user, group 0 does not give any special privilege at the kernel level, `groups=1000(elasticsearch),0(root)` does not mean that the process is running as root. Also this is required to run on OpenShift: https://docs.redhat.com/en/documentation/openshift_container_platform/4.18/html/images/creating-images#use-uid_create-images

> For an image to support running as an arbitrary user, directories and files that are written to by processes in the image must be owned by the root group and be read/writable by that group.
