### ISSUE TITLE
elastic-internal-init-keystore - CPU resource limit too low

### ISSUE THREAD

**Issue by BenjaminBanwart** [elastic/cloud-on-k8s#8563]
The init containter `elastic-internal-init-keystore` is preconfigured with resources, but is not configurable using the helm chart.

Linked issue for reference: https://github.com/elastic/cloud-on-k8s/issues/2660#issuecomment-639380726

Here, it was decided that these values would be enough.

### Our Issue

For our workload, we are getting throttling for that container.

### Suggestions

I would like to suggest that this gets reconfigured to allow chart users to modify these resources via `values.yaml`.
If that can't happen, I would request that the current `cpu limit` gets raised.

**Comment by barkbay** [comment]
The Helm charts allows you to tweak the pod template, so I think the following values should work:

```yaml
secureSettings:
  - secretName: hosted-remote-api-keys
nodeSets:
- name: default
  count: 1
  config:
    node.store.allow_mmap: false
  podTemplate:
    spec:
      initContainers:
      - name: elastic-internal-init-keystore
        resources:
          limits:
            cpu: 16
          requests:
            cpu: 500m
```
