### ISSUE TITLE
APM server returns 403 Forbidden to OpenTelemetry Collector

### ISSUE THREAD

**Issue by ohmychill** [elastic/cloud-on-k8s#8564]
Deployed self-hosted ECK cluster in EKS and exposed my APM server thru ingress nginx to be accessed by a remote cluster. The remote cluster has an opentelemetry-collector deployed to forward telemetry signals to APM. I have tried this first on the ECK cloud trial version and it worked. But in self-hosted ECK, I can’t make it work. APM server returns 403 Forbidden error to opentelemetry-collector.

opentelemetry-collector logs when it attempts to forward telemetry signals to APM:

```
2025-03-22T13:46:14.461Z	info	Traces	{"otelcol.component.id": "debug", "otelcol.component.kind": "Exporter", "otelcol.signal": "traces", "resource spans": 1, "spans": 1}
2025-03-22T13:46:14.461Z	info	ResourceSpans #0
Resource SchemaURL: https://opentelemetry.io/schemas/1.17.0
Resource attributes:
     -> service.name: Str(my-api-dev)
ScopeSpans #0
ScopeSpans SchemaURL:
InstrumentationScope my-api-dev
Span #0
    Trace ID       : ff609c08a18eac50477d710bb2588cbd
    Parent ID      :
    ID             : f2ce26ae07ddeec1
    Name           : HTTP GET /v2/users/search
    Kind           : Internal
    Start time     : 2025-03-22 13:46:13.111200734 +0000 UTC
    End time       : 2025-03-22 13:46:13.149619211 +0000 UTC
    Status code    : Unset
    Status message :
Attributes:
     -> status.Code: Int(2)
     -> http.status_code: Int(401)
	{"otelcol.component.id": "debug", "otelcol.component.kind": "Exporter", "otelcol.signal": "traces"}
2025-03-22T13:46:14.480Z	error	internal/queue_sender.go:46	Exporting failed. Dropping data.	{"otelcol.component.id": "otlp/elastic", "otelcol.component.kind": "Exporter", "otelcol.signal": "traces", "error": "not retryable error: Permanent error: rpc error: code = PermissionDenied desc = unexpected HTTP status code received from server: 403 (Forbidden); transport: received unexpected content-type \"text/html\"", "dropped_items": 1}
go.opentelemetry.io/collector/exporter/exporterhelper/internal.NewQueueSender.func1
	go.opentelemetry.io/collector/exporter@v0.121.0/exporterhelper/internal/queue_sender.go:46
go.opentelemetry.io/collector/exporter/exporterhelper/internal/batcher.(*disabledBatcher[...]).Consume
	go.opentelemetry.io/collector/exporter@v0.121.0/exporterhelper/internal/batcher/disabled_batcher.go:23
go.opentelemetry.io/collector/exporter/exporterqueue.(*asyncQueue[...]).Start.func1
	go.opentelemetry.io/collector/exporter@v0.121.0/exporterqueue/async_queue.go:47
```

ECK stack helm values:

```
eck-elasticsearch:
  version: 8.17.3
  enabled: true
  fullnameOverride: elasticsearch

  nodeSets:
  - name: default
    count: 3
    config:
      node.store.allow_mmap: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
        storageClassName: ebs-sc
  
  ingress:
    enabled: true
    className: nginx
    pathType: Prefix
    hosts:
    - host: elasticsearch.mydomain.com
      path: /


  http:
    tls:
      selfSignedCertificate:
        disabled: true
    
eck-kibana:
  version: 8.17.3
  enabled: true
  elasticsearchRef:
    name: elasticsearch
  
  fullnameOverride: kibana

  config:
    server:
      publicBaseUrl: http://kibana.mydomain.com
  
  http:
    service:
      spec:
        type: ClusterIP
    tls:
      selfSignedCertificate:
        disabled: true
  
  ingress:
    enabled: true
    className: nginx
    pathType: Prefix
    hosts:
    - host: kibana.mydomain.com
      path: /
      
  spec:
    config:
      xpack.fleet.packages:
      - name: apm
        version: latest

eck-agent:
  enabled: false

eck-fleet-server:
  enabled: false

eck-beats:
  enabled: false

eck-logstash:
  enabled: false

eck-apm-server:
  version: 8.17.3
  enabled: true
  count: 1
  config:
    apm-server.auth.anonymous.enabled: true
    apm-server.rum.enabled: true
  elasticsearchRef:
    name: elasticsearch
  kibanaRef:
    name: kibana
    
  http:
    service:
      spec:
        type: ClusterIP
        ports:
        - name: http
          port: 8200
          targetPort: 8200
    tls:
      selfSignedCertificate:
        disabled: false

eck-enterprise-search:
  enabled: false
```
opentelemetry-collector helm values:
```
mode: "deployment"
replicaCount: 1
config:
  receivers:
    jaeger:
      protocols:
        grpc:
    otlp:
      protocols:
        http:
          endpoint: 0.0.0.0:4318
          cors:
            allowed_origins:
              - "http://*"
              - "https://*"
        grpc:
          endpoint: 0.0.0.0:4317
  
  exporters:
    debug:
      verbosity: detailed        
    otlp/elastic:
      endpoint: "elasticsearch-apm-server.mydomain.com:443"
      headers:
        Authorization: "Bearer xxxxxxxxxxxx"
      timeout: 20s
      sending_queue:
        enabled: true
        num_consumers: 10
        queue_size: 10000
      retry_on_failure:
        enabled: true
        initial_interval: 1s
        max_interval: 10s
        max_elapsed_time: 300s


  service:
    pipelines:
      metrics:
        receivers: [otlp]
        exporters: [otlp/elastic, debug]
      traces:
        receivers: [otlp]
        exporters: [otlp/elastic, debug]
      logs:
        receivers: [otlp]
        exporters: [otlp/elastic, debug]
image:
   repository: "otel/opentelemetry-collector"
 command:
   name: "otelcol"
service:
  type: ClusterIP
```

Curl test from remote client cluster:
```
# curl https://elasticsearch-apm-server.mydomain.com/v1/traces -H "Authorization: Bearer xxxxxxxxxxxxxxxxx" -v
* Host elasticsearch-apm-server.mydomain.com:443 was resolved.
* IPv6: (none)
* IPv4: 123.12.123.12, 123.14.123.14``````````````
*   Trying 123.12.123.12:443...
* Connected to elasticsearch-apm-server.mydomain.com (123.12.123.12) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384 / X25519 / id-ecPublicKey
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=axosclearing.com
*  start date: Feb  8 00:21:34 2025 GMT
*  expire date: May  9 01:21:31 2025 GMT
*  subjectAltName: host "elasticsearch-apm-server.mydomain.com" matched cert's "*-server.mydomain.com"
*  issuer: C=US; O=Google Trust Services; CN=WE1
*  SSL certificate verify ok.
*   Certificate level 0: Public key type EC/prime256v1 (256/128 Bits/secBits), signed using ecdsa-with-SHA256
*   Certificate level 1: Public key type EC/prime256v1 (256/128 Bits/secBits), signed using ecdsa-with-SHA384
*   Certificate level 2: Public key type EC/secp384r1 (384/192 Bits/secBits), signed using ecdsa-with-SHA384
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://elasticsearch-apm-server.mydomain.com/v1/traces
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: elasticsearch-apm-server.mydomain.com]
* [HTTP/2] [1] [:path: /v1/traces]
* [HTTP/2] [1] [user-agent: curl/8.5.0]
* [HTTP/2] [1] [accept: */*]
* [HTTP/2] [1] [authorization: Bearer xxxxxxxxxxxxxxxxx]
> GET /v1/traces HTTP/2
> Host: elasticsearch-apm-server.mydomain.com
> User-Agent: curl/8.5.0
> Accept: */*
> Authorization: Bearer xxxxxxxxxxxxxxxxx
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/2 200
< date: Sun, 23 Mar 2025 02:41:31 GMT
< content-type: application/x-protobuf
< content-length: 2
< strict-transport-security: max-age=2592000; includeSubDomains
< cf-cache-status: DYNAMIC
< set-cookie: __cf_bm=1SRDHCn3IrPGtZErb33BqwTKSO3G8crvXHOlt9dzdOQ-1742697691-1.0.1.1-0BHhfKkMdpeA8S.o9KXAw4OUDiYVjYXk9pt12pWtTDu9TupKlIF4BjQ431DvTt_H8WnR9Jn3oLA2Kb8DbyEHj5gH0GjFu9QA3Loqr9x.bA8; path=/; expires=Sun, 23-Mar-25 03:11:31 GMT; domain=.axosclearing.com; HttpOnly; Secure; SameSite=None
< x-content-type-options: nosniff
< server: cloudflare
< cf-ray: 213saf343534a324-IAD
<
Warning: Binary output can mess up your terminal. Use "--output -" to tell
Warning: curl to output it to your terminal anyway, or consider "--output
Warning: <FILE>" to save to a file.
* Failure writing output to destination
* Connection #0 to host elasticsearch-apm-server.mydomain.com left intact
```
curl test from my local:
```
$ curl https://elasticsearch-apm-server.mydomain.com -H "Authorization: Bearer xxxxxxxxxxxx"
{
  "build_date": "2025-02-27T18:17:35Z",
  "build_sha": "f6b917b725e1a22af433e5b52c5c6f0ff9164adf",
  "publish_ready": true,
  "version": "8.17.3"
}
```

apm-server logs if curl test from remote client is success:
```
{"log.level":"info","@timestamp":"2025-03-23T02:48:26.234Z","log.logger":"request","log.origin":{"function":"github.com/elastic/apm-server/internal/beater/api.apmMiddleware.LogMiddleware.func1.1","file.name":"middleware/log_middleware.go","file.line":62},"message":"handled request","service.name":"apm-server","url.original":"/v1/traces","http.request.method":"GET","user_agent.original":"curl/8.5.0","source.address":"172.22.32.0","http.request.id":"13e4eee1-e616-4777-930b-8943749d8939","event.duration":81082,"http.request.body.bytes":0,"http.response.status_code":200,"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2025-03-23T02:48:39.902Z","log.logger":"request","log.origin":{"function":"github.com/elastic/apm-server/internal/beater/api.apmMiddleware.LogMiddleware.func1.1","file.name":"middleware/log_middleware.go","file.line":62},"message":"handled request","service.name":"apm-server","url.original":"/v1/traces","http.request.method":"GET","user_agent.original":"curl/8.5.0","source.address":"172.22.73.64","http.request.id":"a14811c9-df07-4c30-b43d-10c7613fb82d","event.duration":91563,"http.request.body.bytes":0,"http.response.status_code":200,"ecs.version":"1.6.0"}
```

So, any idea why APM server returns 403 Forbidden to otel-collector but APM token works when tried to manually curl from the remote client?

> ECK version: 8.17.3
> otel-collector chart version: 0.119.0
