### ISSUE TITLE
Cannot disable TLS in Logstash

### ISSUE THREAD

**Issue by pebrc** [elastic/cloud-on-k8s#8600]
Disabling TLS [as documented](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-logstash-securing-api.html#k8s-logstash-http-disable-tls) does not work:
```yaml
apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: logstash
  namespace: elasticsearch
spec:
  version: 8.17.4
  count: 2
  services:
    - name: api
      tls:
        selfSignedCertificate:
          disabled: true
```

it fails with:
```
{"log.level":"error","@timestamp":"2025-04-11T07:53:39.535Z","log.logger":"manager.eck-operator","message":"Reconciler error","service.version":"2.16.1+1f74bdd9","service.type":"eck","ecs.version":"1.4.0","controller":"logstash-controller","object":{"name":"logstash","namespace":"elasticsearch"},"namespace":"elasticsearch","name":"logstash","reconcileID":"2fd6ec62-dddd-41e0-8183-30f9997d2c8a","error":"Service \"logstash-ls-api\" is invalid: spec.ports: Required value","errorCauses":[{"error":"Service \"logstash-ls-api\" is invalid: spec.ports: Required value"}],"error.stack_trace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:224"}
```

because the defaulting logic in 

https://github.com/elastic/cloud-on-k8s/blob/00803849a7e4a641586ef13d6bf2452b9dd8fab0/pkg/controller/logstash/service.go#L44-L51

only works if no services has been spec'ed out. 

If we specify a port like so: 

```yaml
apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: logstash
spec:
  version: 8.17.4
  count: 2
  services:
    - name: api
      service:
        spec:
          ports:
          - port: 9600
      tls:
        selfSignedCertificate:
          disabled: true
```

reconciliation still fails because 

https://github.com/elastic/cloud-on-k8s/blob/00803849a7e4a641586ef13d6bf2452b9dd8fab0/pkg/controller/logstash/pod.go#L224

only looks at `api.ssl.enabled` and not at the TLS options in the service.

So the full workaround manifest is:
```yaml
apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: logstash
spec:
  version: 8.17.4
  config:
    api.ssl.enabled: false
  count: 2
  services:
    - name: api
      service:
        spec:
          ports:
          - port: 9600
      tls:
        selfSignedCertificate:
          disabled: true
```
