### ISSUE TITLE
eck-operator PDB template generates corrupt YAML with bad labels placement

### ISSUE THREAD

**Issue by den-is** [elastic/cloud-on-k8s#8615]
This issue was caught by ArgoCD automatically during upgrade 2.16.1 -> 3.0.0.
I was able to replicate the same issue on my workstations using plain `helm template ...`
```sh
helm template -n elastic-system \
elastic-operator elastic/eck-operator \
--kube-version 1.30 \
--values values.yaml \
--version=3.0.0 --debug > eck-rendered.yaml
```

values.yaml
```yaml
installCRDs: true
replicaCount: 2
podDisruptionBudget:
  enabled: true
  minAvailable: 1
serviceMonitor:
  enabled: false
podLabels:
  env: staging
```

Resulting PodDisruptionBudget yaml:
```yaml
---
# Source: eck-operator/templates/pdb.yaml

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: elastic-operator
  namespace: elastic-system
  labels:    app.kubernetes.io/name: elastic-operator
    app.kubernetes.io/instance: elastic-operator
    app.kubernetes.io/version: "3.0.0"
    helm.sh/chart: eck-operator-3.0.0
    app.kubernetes.io/managed-by: Helm
spec:
  minAvailable: 1
  selector:
    matchLabels:      app.kubernetes.io/name: elastic-operator
      app.kubernetes.io/instance: elastic-operator
```
