### ISSUE TITLE
Setting stack monitoring for Beats duplicates volume mounts.

### ISSUE THREAD

**Issue by naemono** [elastic/cloud-on-k8s#8622]
In the case of Beats both the main container and the sidecar share the same /usr/share/filebeat/logs:

```
apiVersion: v1
kind: Pod
metadata:
  name: filebeat-beat-filebeat-8jxr2
spec:
  containers:
  - name: filebeat
    volumeMounts:
    - mountPath: /usr/share/filebeat/logs ## same mount point
      name: filebeat-logs ## same volume
  - name: logs-monitoring-sidecar
    volumeMounts:
    - mountPath: /usr/share/filebeat/logs ## same mount point
      name: filebeat-logs ## same volume
  volumes:
  - emptyDir: {}
    name: filebeat-logs
```

We do not know whether this is causing issues, but we probably want to avoid this scenario. This is likely the same for metricbeat as well.
