### ISSUE TITLE
Setting CR.spec.version of ApmServer to unreleased version does not allow rollback

### ISSUE THREAD

**Issue by Javatar81** [elastic/cloud-on-k8s#8662]
I've set spec.version in the ApmServer CR to a yet unavailable version.

```
apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-server
  namespace: geo-application
spec:
  version: 9.0.2
  count: 1
  elasticsearchRef:
    name: backend
  kibanaRef:
    name: frontend
```

I am not able to rollback to 9.0.1 because of the admission web hook that prevents version downgrades. 

```
Error from server (Forbidden): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"apm.k8s.elastic.co/v1\",\"kind\":\"ApmServer\",\"metadata\":{\"annotations\":{},\"name\":\"apm-server\",\"namespace\":\"geo-application\"},\"spec\":{\"count\":1,\"elasticsearchRef\":{\"name\":\"geo-backend\"},\"kibanaRef\":{\"name\":\"geo-frontend\"},\"version\":\"9.0.1\"}}\n"}},"spec":{"version":"9.0.1"}}
to:
Resource: "apm.k8s.elastic.co/v1, Resource=apmservers", GroupVersionKind: "apm.k8s.elastic.co/v1, Kind=ApmServer"
Name: "apm-server", Namespace: "geo-application"
for: "test.yaml": error when patching "test.yaml": admission webhook "elastic-apm-validation-v1.k8s.elastic.co" denied the request: ApmServer.apm.k8s.elastic.co "apm-server" is invalid: spec.version: Forbidden: Version downgrades are not supported
```

It would be an improvement to have a web hook preventing to deploy unavailable versions. This would prevent the issue.
