### ISSUE TITLE
eck-operator helm chart 3.0.0 yaml parse error on podDisruptionBudget

### ISSUE THREAD

**Issue by dat-intellis** [elastic/cloud-on-k8s#8674]
setting `podDisruptionBudget.enabled = true` causes the chart unable to parse. 

This is most likely due to unquoted labels within the `pdb.yaml` template.

Reference: `pdb.yaml`
```yaml
{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "eck-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "eck-operator.labels" . | nindent 4 }}
spec:
  {{- with .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ . }}
  {{- end  }}
  {{- with .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end  }}
  selector:
    matchLabels:
      {{- include "eck-operator.selectorLabels" . | nindent 6 }}
{{- end -}}
```

**Comment by dat-intellis** [comment]
@naemono > simply installing the chart with the following values should be enough to replicate: 

```yaml
...
replicaCount: 2
podDisruptionBudget:
  enabled: true
  minAvailable: 1
...
```

If I don't forget it I'll get you the full error the next time I'm at my machine.
