### ISSUE TITLE
Automatically inject service external IP to the certs SAN

### ISSUE THREAD

**Issue by sebgl** [elastic/cloud-on-k8s#910]
When users expose the ES cluster through `http.service.type`, they're hitting a cert validity issue while requesting the cluster:

```
Failed to connect to backoff(elasticsearch(https://34.66.153.170:9200)): Get https://34.66.153.170:9200: x509: certificate is valid for 10.60.1.15, 127.0.0.1, 10.63.247.8, not 34.66.153.179
```

It's expected, since the external IP is never injected into ES certs SANs.

The workaround currently is for users to manually inject that IP into the Elasticsearch Spec:
https://github.com/elastic/cloud-on-k8s/blob/5a8a8a340b19403d75659595fcf96ad7c95a167f/operators/config/samples/elasticsearch/elasticsearch.yaml#L46-L51

We should be able to inject that IP automatically, and reconcile on any IP change.
Do we need a way for this to be an opt-in/opt-out feature, or is it OK to just enforce it?

**Comment by pebrc** [comment]
Why would someone not want this?

**Comment by sebgl** [comment]
A few things we discussed in today's sync meeting:

* this only matters for ES cluster http endpoint, not individual nodes certs involved in internal node-to-node communication
* we plan to support users providing their own certificate, in such case we don't need to care at all about this. In this issue we only care about the "default" behaviour when people rely on our self-signed certs.
* it may feel wrong to automatically include an external IP to be trusted instead of a DNS name. Most public CAs would not allow that when signing certificates (see https://cabforum.org/baseline-requirements-documents/)
* not having this feature breaks a bit the quickstart experience of exposing an Elasticsearch cluster publicly, if you don't also have a DNS setup
* should we support user-provided services? For example people may want to create their own service to target the Ingest nodes, using a selector on corresponding pods. In such situation, we would also need to inject the IP and service name of these user-provided services.
* we could decide to make this opt-in by having the user provide some logical values in the `subjectAltNames` section, to also support additional services. Something like:
```
tls: 
  selfSignedCertificate: 
    subjectAltNames: 
    - ip: 192.168.1.2 
    - dns: elasticsearch-sample.example.com
    - service:
        ref:
            namespace: default
            name: es-ingest-nodes
        serviceName: true
        clusterIP: true
        loadBalancerIP: true
```
