### ISSUE TITLE
Support Configuring RackID

### ISSUE THREAD

**Issue by weeco** [elastic/cloud-on-k8s#933]
## Proposal

**Use case. Why is this important?**

I am running a kubernetes cluster in two availability zones and I'd like to configure my Elasticsearch Cluster so, that one AV zone can fail and it will still be fully functional. Therefore I'd like to use Elasticsearch's RackID feature, so that shard replicas will always be distributed across the two zones.

I couldn't find an option to configure the operator / CRD accordingly, hence I believe this is not yet supported.

**Comment by nkvoll** [comment]
You can add any node attribute through the `config` section in the `nodes` list, and you can specify the node affinity in the `podTemplate` section.

Thus, if you've the right labels attached to your Kubernetes nodes, you can try the following:

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.1.0
  nodes:
  - nodeCount: 1
    config:
      node.attr.zone: europe-west3-a
      cluster.routing.allocation.awareness.attributes: zone
    podTemplate:
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: failure-domain.beta.kubernetes.io/zone
                  operator: In
                  values:
                  - europe-west3-a
  - nodeCount: 1
    config:
      node.attr.zone: europe-west3-b
      cluster.routing.allocation.awareness.attributes: zone
    podTemplate:
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: failure-domain.beta.kubernetes.io/zone
                  operator: In
                  values:
                  - europe-west3-b
```

If you're using different keys/values as labels, this needs adjusting accordingly.

Disclaimer: I haven't tried this specifically myself, but pieced it together from https://www.elastic.co/guide/en/elasticsearch/reference/current/allocation-awareness.html and https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#node-affinity-beta-feature.
