### ISSUE TITLE
[feature-request] Support node selector

### ISSUE THREAD

**Issue by yacut** [elastic/cloud-on-k8s#944]
## Proposal

We want to completely isolate the elastic search cluster from the rest of the k8s services, so that we can better control the allocated resources.

https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector

**Comment by sebgl** [comment]
Makes sense 👍 
This will be supported as part of https://github.com/elastic/cloud-on-k8s/pull/943 (inherit user-provided `podTemplate`) in the next release.
We also need to write corresponding documentation.

**Comment by weeco** [comment]
@sebgl I saw you already created and merged the PR (thanks for that), but I wonder if there's a workaround to use node selectors until a new version with this feature is released?

**Comment by sebgl** [comment]
@weeco yes, you can use [node affinity](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#node-affinity-beta-feature), already available and exposed in release 0.8.

**Comment by nkvoll** [comment]
Closing because this is solved in master and there's a workaround for alpha if required.

**Comment by dikatok** [comment]
Hi, is `nodeSelector` supported in 0.8.0? I tried to deploy the service using below yaml with no avail.

```
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: elastic
spec:
  version: 7.2.0
  nodes:
    - nodeCount: 3
      config:
        node.master: true
        node.data: true
        node.ingest: true
      podTemplate:
        spec:
          nodeSelector:
            nodeType: es
```

It is not registered as label selector when I checked via GKE console. Also have tried using node affinity as stated [here](https://github.com/elastic/cloud-on-k8s/blob/d914e2b3992f9c7a13865e1d543b8176bfe2e418/docs/advanced-node-scheduling.asciidoc) with the same result.
