### ISSUE TITLE
Validate `metadata.name` of `volumeClaimTemplates` exists in the resulting Pod `spec.containers[].volumeMounts`

### ISSUE THREAD

**Issue by nkvoll** [elastic/cloud-on-k8s#959]
It's currently a bit tricky to find and use the correct name for `metadata.name` in the `volumeClaimTemplates` section for different volumes we use (specifically `data` etc). If a user makes a typo here it's easy to think that a persistent volume is used for the data directory, but in reality, it's not mounted to the Elasticsearch container.

A validation error message could look something like this: 

```Unknown volume name "es-data" used in volumeClaimTemplates, possible values: [a, b, c]```.

/cc @jordansissel for pointing this out.

**Comment by racevedoo** [comment]
Hi, any progress on this? Right now my config does not mount the volume into the elasticsearch container, I think the problem could be the `metadata.name` that was mentioned.

**Comment by sebgl** [comment]
Hi @racevedoo, with ECK 0.9 your data volume must be named `elasticsearch-data`, as [specified in the documentation](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-volume-claim-templates.html). Can you double check this is the case?
Otherwise, can you please open another issue with more details about your deployment?

**Comment by racevedoo** [comment]
Hi @sebgl , when setting to `elasticsearch-data`, it does not mount. Just opened an issue with more details. #1601

**Comment by JamiKarvanen** [comment]
I have the same problem. I have added volumeClaimTemplates configuration like the documentation suggests, but the volumes are not created and the pods use the default 1Gi volumes instead. When describing the elasticsearch resource, I can see that the Volume Claim Template is added. 

Here's my manifest:
```
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: es
  namespace: elasticsearch
spec:
  version: 7.3.1
  nodes:
  - nodeCount: 3
    config:
      node.master: true
      node.data: true
      node.ingest: true
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          securityContext:
            runAsUser: 1000
    volumeClaimTemplates:
      - metadata:
          name: elasticsearch-data
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
          storageClassName: gp2
```
