### ISSUE TITLE
Cannot connect to elasticsearch internally within cluster

### ISSUE THREAD

**Issue by dlmiddlecote** [elastic/cloud-on-k8s#964]
## Bug Report
**What did you do?**
Tried to connect to the elasticsearch within the cluster.

I'm running an elasticsearch called 'foo' in the 'bar' namespace, and so my cluster should be accessible under `https://foo-es.bar.svc.cluster.local:9200`.

When I connect to this from an Go app, using [this lib](https://github.com/olivere/elastic), I receive an error.

**What did you expect to see?**
No error. I see that there is a possibility of adding `subjectAltNames` to the `http.tls.selfSignedCertificate` section of the elasticsearch resource, but 1. I don't know what I should put there, and 2. I'm not sure I should need to do that.

**What did you see instead? Under which circumstances?**
An error saying `x509: certificate signed by unknown authority` on all requests.

**Environment**

* Version information:

	Running v0.8.0 of the operator and v6.8.0 of elasticsearch

* Kubernetes information:

	insert any information about your Kubernetes environment that could help us:
	* Cloud: DigitalOcean v1.13.1	
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```

* Resource definition:
```
---
apiVersion: elasticsearch.k8s.elastic.co/v1alpha1
kind: Elasticsearch
metadata:
  name: foo
  namespace: bar
spec:
  version: 6.8.0
  nodes:
    - nodeCount: 1
      config:
        node.master: true
        node.data: true
        node.ingest: true
      volumeClaimTemplates:
        - metadata:
            name: data
          spec:
            storageClassName: do-block-storage
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
```
